#ifndef __MAPS__
#define __MAPS__

// Generated automagically from Resurrection.zip/data/MAPS.TXT //

#define MAP_ALB_CISA      (25)
#define MAP_ALB_CISB      (26)
#define MAP_ALB_DIV1      (92)
#define MAP_ALB_DIV2      (93)
#define MAP_ALB_DIV3      (94)
#define MAP_ALB_KRYT      (84)
#define MAP_ALB_LOVA      (23)
#define MAP_ALB_LOVB      (24)
#define MAP_ALB_MRTV      (22)
#define MAP_ALB_NEM1      (98)
#define MAP_ALB_NEM2      (97)
#define MAP_ALB_NEM3      (96)
#define MAP_ALB_NEM4      (95)
#define MAP_ALB_PRED      (21)
#define MAP_ALB_VEXR      (28)
#define MAP_ALB_VLTA      (27)
#define MAP_ASMODEUS      (020)
#define MAP_BHRNDDST      (82)
#define MAP_BHRNDMNT      (83)
#define MAP_CAVE0         (39)
#define MAP_CAVE1         (040)
#define MAP_CAVE2         (41)
#define MAP_CAVE3         (42)
#define MAP_CAVE4         (43)
#define MAP_CAVE5         (48)
#define MAP_CAVE6         (69)
#define MAP_CAVE7         (070)
#define MAP_CAVEDIV       (109)
#define MAP_CITY1         (38)
#define MAP_CITY2         (75)
#define MAP_CITY3         (76)
#define MAP_CITY4         (77)
#define MAP_CITY5         (78)
#define MAP_CITY6         (79)
#define MAP_CITY7         (080)
#define MAP_CITY8         (81)
#define MAP_COAST1        (46)
#define MAP_COAST10       (060)
#define MAP_COAST11       (61)
#define MAP_COAST2        (47)
#define MAP_COAST3        (53)
#define MAP_COAST4        (54)
#define MAP_COAST5        (55)
#define MAP_COAST6        (56)
#define MAP_COAST7        (57)
#define MAP_COAST8        (58)
#define MAP_COAST9        (59)
#define MAP_CORATH1       (15)
#define MAP_CORATH2       (16)
#define MAP_CORATH3       (17)
#define MAP_CORATH4       (18)
#define MAP_CORATHEX      (090)
#define MAP_CORATHNX      (91)
#define MAP_DESERT1       (0)
#define MAP_DESERT2       (1)
#define MAP_DESERT3       (2)
#define MAP_DESERT4       (49)
#define MAP_DESERT5       (050)
#define MAP_DESERT6       (51)
#define MAP_DESERT7       (52)
#define MAP_DESERT8       (63)
#define MAP_DESERT9       (64)
#define MAP_DESRT10       (65)
#define MAP_DESRT11       (66)
#define MAP_DESRT12       (67)
#define MAP_DSRT13        (68)
#define MAP_ENDGAME       (101)
#define MAP_GHOUL0        (030)
#define MAP_GHOUL13       (31)
#define MAP_GHOUL46       (32)
#define MAP_GHOULMET      (108)
#define MAP_KARAVAN1      (102)
#define MAP_KARAVAN2      (103)
#define MAP_KARAVAN3      (104)
#define MAP_KARAVAN4      (105)
#define MAP_KARAVAN5      (106)
#define MAP_KARAVAN6      (107)
#define MAP_MOUNTN1       (44)
#define MAP_MOUNTN2       (45)
#define MAP_MOUNTN3       (71)
#define MAP_MOUNTN4       (72)
#define MAP_MOUNTN5       (73)
#define MAP_MOUNTN6       (74)
#define MAP_MUTANT        (29)
#define MAP_NH_CAVE       (3)
#define MAP_NH_CAVEN      (4)
#define MAP_NH_LOV        (88)
#define MAP_NH_PAST       (5)
#define MAP_NH_VILL       (6)
#define MAP_PROGEMA1      (99)
#define MAP_PROGEMA2      (100)
#define MAP_RHALXPAY      (89)
#define MAP_RH_JIZ        (7)
#define MAP_RH_SEV        (8)
#define MAP_RNDBIS        (37)
#define MAP_RNDCLOS       (36)
#define MAP_RNDMACG       (34)
#define MAP_RNDSG         (33)
#define MAP_RNDSPAM       (35)
#define MAP_SED_CENT      (010)
#define MAP_SED_HLTR      (12)
#define MAP_SED_KRUL      (9)
#define MAP_SED_MHUB      (11)
#define MAP_SED_TUNL      (85)
#define MAP_SED_ZTR       (13)
#define MAP_SED_ZTR2      (14)
#define MAP_SFRENOTI      (86)
#define MAP_SSANCHMT      (87)
#define MAP_VRAKOV        (19)
#define MAP_07DESERT      (62)
//
#define CUR_MAP_ALB_CISA  (cur_map_index == MAP_ALB_CISA)
#define CUR_MAP_ALB_CISB  (cur_map_index == MAP_ALB_CISB)
#define CUR_MAP_ALB_DIV1  (cur_map_index == MAP_ALB_DIV1)
#define CUR_MAP_ALB_DIV2  (cur_map_index == MAP_ALB_DIV2)
#define CUR_MAP_ALB_DIV3  (cur_map_index == MAP_ALB_DIV3)
#define CUR_MAP_ALB_KRYT  (cur_map_index == MAP_ALB_KRYT)
#define CUR_MAP_ALB_LOVA  (cur_map_index == MAP_ALB_LOVA)
#define CUR_MAP_ALB_LOVB  (cur_map_index == MAP_ALB_LOVB)
#define CUR_MAP_ALB_MRTV  (cur_map_index == MAP_ALB_MRTV)
#define CUR_MAP_ALB_NEM1  (cur_map_index == MAP_ALB_NEM1)
#define CUR_MAP_ALB_NEM2  (cur_map_index == MAP_ALB_NEM2)
#define CUR_MAP_ALB_NEM3  (cur_map_index == MAP_ALB_NEM3)
#define CUR_MAP_ALB_NEM4  (cur_map_index == MAP_ALB_NEM4)
#define CUR_MAP_ALB_PRED  (cur_map_index == MAP_ALB_PRED)
#define CUR_MAP_ALB_VEXR  (cur_map_index == MAP_ALB_VEXR)
#define CUR_MAP_ALB_VLTA  (cur_map_index == MAP_ALB_VLTA)
#define CUR_MAP_ASMODEUS  (cur_map_index == MAP_ASMODEUS)
#define CUR_MAP_BHRNDDST  (cur_map_index == MAP_BHRNDDST)
#define CUR_MAP_BHRNDMNT  (cur_map_index == MAP_BHRNDMNT)
#define CUR_MAP_CAVE0     (cur_map_index == MAP_CAVE0)
#define CUR_MAP_CAVE1     (cur_map_index == MAP_CAVE1)
#define CUR_MAP_CAVE2     (cur_map_index == MAP_CAVE2)
#define CUR_MAP_CAVE3     (cur_map_index == MAP_CAVE3)
#define CUR_MAP_CAVE4     (cur_map_index == MAP_CAVE4)
#define CUR_MAP_CAVE5     (cur_map_index == MAP_CAVE5)
#define CUR_MAP_CAVE6     (cur_map_index == MAP_CAVE6)
#define CUR_MAP_CAVE7     (cur_map_index == MAP_CAVE7)
#define CUR_MAP_CAVEDIV   (cur_map_index == MAP_CAVEDIV)
#define CUR_MAP_CITY1     (cur_map_index == MAP_CITY1)
#define CUR_MAP_CITY2     (cur_map_index == MAP_CITY2)
#define CUR_MAP_CITY3     (cur_map_index == MAP_CITY3)
#define CUR_MAP_CITY4     (cur_map_index == MAP_CITY4)
#define CUR_MAP_CITY5     (cur_map_index == MAP_CITY5)
#define CUR_MAP_CITY6     (cur_map_index == MAP_CITY6)
#define CUR_MAP_CITY7     (cur_map_index == MAP_CITY7)
#define CUR_MAP_CITY8     (cur_map_index == MAP_CITY8)
#define CUR_MAP_COAST1    (cur_map_index == MAP_COAST1)
#define CUR_MAP_COAST10   (cur_map_index == MAP_COAST10)
#define CUR_MAP_COAST11   (cur_map_index == MAP_COAST11)
#define CUR_MAP_COAST2    (cur_map_index == MAP_COAST2)
#define CUR_MAP_COAST3    (cur_map_index == MAP_COAST3)
#define CUR_MAP_COAST4    (cur_map_index == MAP_COAST4)
#define CUR_MAP_COAST5    (cur_map_index == MAP_COAST5)
#define CUR_MAP_COAST6    (cur_map_index == MAP_COAST6)
#define CUR_MAP_COAST7    (cur_map_index == MAP_COAST7)
#define CUR_MAP_COAST8    (cur_map_index == MAP_COAST8)
#define CUR_MAP_COAST9    (cur_map_index == MAP_COAST9)
#define CUR_MAP_CORATH1   (cur_map_index == MAP_CORATH1)
#define CUR_MAP_CORATH2   (cur_map_index == MAP_CORATH2)
#define CUR_MAP_CORATH3   (cur_map_index == MAP_CORATH3)
#define CUR_MAP_CORATH4   (cur_map_index == MAP_CORATH4)
#define CUR_MAP_CORATHEX  (cur_map_index == MAP_CORATHEX)
#define CUR_MAP_CORATHNX  (cur_map_index == MAP_CORATHNX)
#define CUR_MAP_DESERT1   (cur_map_index == MAP_DESERT1)
#define CUR_MAP_DESERT2   (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT3   (cur_map_index == MAP_DESERT3)
#define CUR_MAP_DESERT4   (cur_map_index == MAP_DESERT4)
#define CUR_MAP_DESERT5   (cur_map_index == MAP_DESERT5)
#define CUR_MAP_DESERT6   (cur_map_index == MAP_DESERT6)
#define CUR_MAP_DESERT7   (cur_map_index == MAP_DESERT7)
#define CUR_MAP_DESERT8   (cur_map_index == MAP_DESERT8)
#define CUR_MAP_DESERT9   (cur_map_index == MAP_DESERT9)
#define CUR_MAP_DESRT10   (cur_map_index == MAP_DESRT10)
#define CUR_MAP_DESRT11   (cur_map_index == MAP_DESRT11)
#define CUR_MAP_DESRT12   (cur_map_index == MAP_DESRT12)
#define CUR_MAP_DSRT13    (cur_map_index == MAP_DSRT13)
#define CUR_MAP_ENDGAME   (cur_map_index == MAP_ENDGAME)
#define CUR_MAP_GHOUL0    (cur_map_index == MAP_GHOUL0)
#define CUR_MAP_GHOUL13   (cur_map_index == MAP_GHOUL13)
#define CUR_MAP_GHOUL46   (cur_map_index == MAP_GHOUL46)
#define CUR_MAP_GHOULMET  (cur_map_index == MAP_GHOULMET)
#define CUR_MAP_KARAVAN1  (cur_map_index == MAP_KARAVAN1)
#define CUR_MAP_KARAVAN2  (cur_map_index == MAP_KARAVAN2)
#define CUR_MAP_KARAVAN3  (cur_map_index == MAP_KARAVAN3)
#define CUR_MAP_KARAVAN4  (cur_map_index == MAP_KARAVAN4)
#define CUR_MAP_KARAVAN5  (cur_map_index == MAP_KARAVAN5)
#define CUR_MAP_KARAVAN6  (cur_map_index == MAP_KARAVAN6)
#define CUR_MAP_MOUNTN1   (cur_map_index == MAP_MOUNTN1)
#define CUR_MAP_MOUNTN2   (cur_map_index == MAP_MOUNTN2)
#define CUR_MAP_MOUNTN3   (cur_map_index == MAP_MOUNTN3)
#define CUR_MAP_MOUNTN4   (cur_map_index == MAP_MOUNTN4)
#define CUR_MAP_MOUNTN5   (cur_map_index == MAP_MOUNTN5)
#define CUR_MAP_MOUNTN6   (cur_map_index == MAP_MOUNTN6)
#define CUR_MAP_MUTANT    (cur_map_index == MAP_MUTANT)
#define CUR_MAP_NH_CAVE   (cur_map_index == MAP_NH_CAVE)
#define CUR_MAP_NH_CAVEN  (cur_map_index == MAP_NH_CAVEN)
#define CUR_MAP_NH_LOV    (cur_map_index == MAP_NH_LOV)
#define CUR_MAP_NH_PAST   (cur_map_index == MAP_NH_PAST)
#define CUR_MAP_NH_VILL   (cur_map_index == MAP_NH_VILL)
#define CUR_MAP_PROGEMA1  (cur_map_index == MAP_PROGEMA1)
#define CUR_MAP_PROGEMA2  (cur_map_index == MAP_PROGEMA2)
#define CUR_MAP_RHALXPAY  (cur_map_index == MAP_RHALXPAY)
#define CUR_MAP_RH_JIZ    (cur_map_index == MAP_RH_JIZ)
#define CUR_MAP_RH_SEV    (cur_map_index == MAP_RH_SEV)
#define CUR_MAP_RNDBIS    (cur_map_index == MAP_RNDBIS)
#define CUR_MAP_RNDCLOS   (cur_map_index == MAP_RNDCLOS)
#define CUR_MAP_RNDMACG   (cur_map_index == MAP_RNDMACG)
#define CUR_MAP_RNDSG     (cur_map_index == MAP_RNDSG)
#define CUR_MAP_RNDSPAM   (cur_map_index == MAP_RNDSPAM)
#define CUR_MAP_SED_CENT  (cur_map_index == MAP_SED_CENT)
#define CUR_MAP_SED_HLTR  (cur_map_index == MAP_SED_HLTR)
#define CUR_MAP_SED_KRUL  (cur_map_index == MAP_SED_KRUL)
#define CUR_MAP_SED_MHUB  (cur_map_index == MAP_SED_MHUB)
#define CUR_MAP_SED_TUNL  (cur_map_index == MAP_SED_TUNL)
#define CUR_MAP_SED_ZTR   (cur_map_index == MAP_SED_ZTR)
#define CUR_MAP_SED_ZTR2  (cur_map_index == MAP_SED_ZTR2)
#define CUR_MAP_SFRENOTI  (cur_map_index == MAP_SFRENOTI)
#define CUR_MAP_SSANCHMT  (cur_map_index == MAP_SSANCHMT)
#define CUR_MAP_VRAKOV    (cur_map_index == MAP_VRAKOV)
#define CUR_MAP_07DESERT  (cur_map_index == MAP_07DESERT)

#endif // __MAPS__ //
