variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;
variable caught_thief;
variable the_follow_obj;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;

variable prev_node;
variable party_being_sold;
variable party_price;

import variable generic_temp_box;
import variable den_metzger_box_obj;

procedure set_sell_davin;
procedure set_sell_miria;
procedure set_sell_myron;
procedure set_sell_vic;
procedure set_sell_macrae;
procedure set_sell_sulik;
procedure Node990;
procedure Node989;
procedure Node988;
procedure Node987;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (((local_var(4) bwand 2) != 0) or ((global_var(446) bwand 16777216) != 0)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
        else begin
            if (((local_var(4) bwand 1) != 0) == 0) then begin
                dialogue_system_enter;
            end
        end
    end
    else begin
        if (tile_num(self_obj) != local_var(7)) then begin
            animate_move_obj_to_tile(self_obj, local_var(7), 0);
        end
        else begin
            if (has_trait(1, self_obj, 10) != local_var(8)) then begin
                anim(self_obj, 1000, local_var(8));
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure talk_p_proc
begin
    debug_msg("global_var(GVAR_DEN_GANGWAR) == " + global_var(454));
    prev_node := 0;
    if (((local_var(4) bwand 2) != 0) or ((global_var(446) bwand 16777216) != 0)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    else begin
        move_obj_inven_to_obj(self_obj, generic_temp_box);
        if ((global_var(446) bwand 536870912) != 0) then begin
            if (in_dialog == 0) then begin
                in_dialog := 1;
                start_gdialog(46, self_obj, 4, -1, -1);
                gsay_start;
                call Node030();
                gsay_end;
                end_dialogue;
                in_dialog := 0;
            end
            else begin
                call Node030();
            end
        end
        else begin
            if (((global_var(446) bwand --2147483648) != 0) and (((global_var(446) bwand 1073741824) != 0) == 0)) then begin
                call Node001();
                call Node998();
            end
            else begin
                if ((global_var(446) bwand 8388608) != 0) then begin
                    if (in_dialog == 0) then begin
                        in_dialog := 1;
                        start_gdialog(46, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node043();
                        gsay_end;
                        end_dialogue;
                        in_dialog := 0;
                    end
                    else begin
                        call Node043();
                    end
                end
                else begin
                    move_obj_inven_to_obj(den_metzger_box_obj, self_obj);
                    if ((global_var(446) bwand 2097152) != 0) then begin
                        if (in_dialog == 0) then begin
                            in_dialog := 1;
                            start_gdialog(46, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node028();
                            gsay_end;
                            end_dialogue;
                            in_dialog := 0;
                        end
                        else begin
                            call Node028();
                        end
                        set_global_var(446, global_var(446) bwand (-1 - 2097152));
                    end
                    else begin
                        if (in_dialog == 0) then begin
                            in_dialog := 1;
                            start_gdialog(46, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node002();
                            gsay_end;
                            end_dialogue;
                            in_dialog := 0;
                        end
                        else begin
                            call Node002();
                        end
                    end
                    move_obj_inven_to_obj(self_obj, den_metzger_box_obj);
                end
            end
        end
        move_obj_inven_to_obj(generic_temp_box, self_obj);
        set_local_var(4, local_var(4) bwor 1);
    end
end

procedure destroy_p_proc
begin
    if (global_var(100) < 2) then begin
        set_global_var(100, 2);
    end
    set_global_var(445, global_var(445) bwor 134217728);
    if (global_var(470) == 0) then begin
        set_global_var(49, global_var(49) + 1);
        set_global_var(0, global_var(0) + 50);
        debug_msg("Player gains " + 50 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        display_msg(message_str(46, 800));
        give_exp_points(1500);
        display_msg(message_str(14, 100) + 1500 + message_str(14, 101));
        set_global_var(470, game_time + (2 * (24 * (60 * (60 * 10)))));
    end
    set_global_var(445, global_var(445) bwor 1);
    move_obj_inven_to_obj(den_metzger_box_obj, self_obj);
    if (source_obj == dude_obj) then begin
        set_global_var(4, global_var(4) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) - -15);
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        set_global_var(0, global_var(0) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    debug_msg("HEY D, CAN YOU SEE ME??? IF SO, PUT YOUR HANDS UP I THE AIR AND WAVE EM LIKE YOU JUST DON'T CARE. AND YELL ALOT TOO.");
    script_overrides;
    debug_msg(" the line number is == " + (100 + ((local_var(4) bwand 1) != 0)));
    display_msg(message_str(46, 100 + ((local_var(4) bwand 1) != 0)));
end

procedure description_p_proc
begin
    debug_msg("HEY D, CAN YOU SEE ME??? IF SO, PUT YOUR HANDS UP I THE AIR AND WAVE EM LIKE YOU JUST DON'T CARE. AND YELL ALOT TOO.");
    script_overrides;
    display_msg(message_str(46, 150));
    set_local_var(4, local_var(4) bwor 4);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (combat_is_initialized == 0) then begin
            call Node001();
        end
        set_global_var(446, global_var(446) bwor 16777216);
        set_local_var(4, local_var(4) bwor 8);
        set_local_var(4, local_var(4) bwor 2);
    end
end

procedure map_enter_p_proc
begin
    if (metarule(22, 0) == 0) then begin
        if (metarule(14, 0)) then begin
            set_local_var(7, tile_num(self_obj));
            set_local_var(8, has_trait(1, self_obj, 10));
            critter_add_trait(self_obj, 1, 6, 12);
            critter_add_trait(self_obj, 1, 5, 16);
        end
    end
end

procedure map_exit_p_proc
begin
end

procedure timed_event_p_proc
begin
    if (fixed_param == 4) then begin
        if (combat_is_initialized == 0) then begin
            call Node029();
        end
    end
end

procedure Node998
begin
    set_local_var(4, local_var(4) bwor 2);
    set_global_var(446, global_var(446) bwor 16777216);
end

procedure Node999
begin
end

procedure Node001
begin
    float_msg(self_obj, message_str(46, 200), 8);
end

procedure Node002
begin
    if (((local_var(4) bwand 1) != 0) == 0) then begin
        set_global_var(445, global_var(445) bwor 32768);
        gsay_reply(46, 210 + ((get_critter_stat(dude_obj, 34) == 1) * (1 + (get_critter_stat(dude_obj, 3) > 5))));
    end
    else begin
        if (global_var(11) == 1) then begin
            gsay_reply(46, random(217, 223));
        end
        else begin
            gsay_reply(46, random(213, 216));
        end
    end
    prev_node := 2;
    call Node005();
end

procedure Node003
begin
    if ((party_member_obj(16777379) != 0) or (party_member_obj(16777380) != 0) or (party_member_obj(16777278) != 0) or (party_member_obj(16777376) != 0) or (party_member_obj(16777305) != 0) or (party_member_obj(16777313) != 0)) then begin
        gsay_reply(46, 230);
        if (party_member_obj(16777379) != 0) then begin
            giq_option(4, 46, 234, set_sell_davin, 50);
        end
        if (party_member_obj(16777380) != 0) then begin
            giq_option(4, 46, 233, set_sell_miria, 50);
        end
        if (party_member_obj(16777278) != 0) then begin
            giq_option(4, 46, 235, set_sell_vic, 50);
        end
        if (party_member_obj(16777376) != 0) then begin
            giq_option(4, 46, 236, set_sell_myron, 50);
        end
        if (party_member_obj(16777305) != 0) then begin
            giq_option(4, 46, 237, set_sell_macrae, 50);
        end
        if (party_member_obj(16777313) != 0) then begin
            giq_option(4, 46, 238, set_sell_sulik, 50);
        end
    end
    else begin
        debug_msg("true_party_size == " + (metarule(16, 0) - 1));
        gsay_reply(46, 231 + ((metarule(16, 0) - 1) == 0));
    end
    giq_option(4, 46, 239, Node004, 50);
    giq_option(4, 46, 240, Node999, 50);
    prev_node := 3;
end

procedure Node004
begin
    gsay_reply(46, random(245, 250));
    prev_node := 4;
    call Node005();
end

procedure Node005
begin
    giq_option(4, 46, 255, Node003, 50);
    if ((((global_var(445) bwand 134217728) != 0) == 0) and ((global_var(452) == 0) == 0)) then begin
        giq_option(4, 46, 256 + (global_var(452) == 1), Node020, 50);
    end
    if (global_var(454) == 2) then begin
        giq_option(4, 46, 258, Node016, 50);
    end
    if ((global_var(11) == 1) == 0) then begin
        giq_option(4, 46, 259, Node006, 50);
        giq_option(4, 46, 260, Node007, 50);
    end
    else begin
        if (local_var(6) == 0) then begin
            giq_option(4, 46, 261, Node010, 50);
        end
    end
    giq_option(4, 46, 262, Node999, 50);
    giq_option(-3, 46, obj_name(dude_obj) + message_str(46, 263), Node990, 50);
    giq_option(-3, 46, 264, Node999, 50);
    prev_node := 5;
end

procedure Node006
begin
    if ((get_critter_stat(dude_obj, 4) <= 3) == 0) then begin
        gsay_reply(46, 270 + ((local_var(4) bwand 512) != 0));
        set_local_var(4, local_var(4) bwor 512);
        giq_option(4, 46, 273, Node009, 50);
        giq_option(4, 46, 274, Node999, 50);
        giq_option(4, 46, 275, Node999, 50);
    end
    else begin
        gsay_reply(46, 272);
        giq_option(-3, 46, 276, Node009, 50);
        giq_option(-3, 46, 277, Node999, 50);
    end
    prev_node := 6;
end

procedure Node007
begin
    gsay_reply(46, 285);
    giq_option(4, 46, 286, Node008, 50);
    giq_option(4, 46, 287, Node006, 50);
    giq_option(4, 46, 288, Node004, 50);
    giq_option(4, 46, 289, Node999, 50);
    prev_node := 7;
end

procedure Node008
begin
    gsay_reply(46, 300);
    giq_option(4, 46, 301, Node006, 50);
    giq_option(4, 46, 302, Node004, 50);
    giq_option(4, 46, 303, Node999, 50);
    prev_node := 8;
end

procedure Node009
begin
    gfade_out(10);
    set_global_var(49, global_var(49) + 1);
    game_time_advance(60 * 10 * 30);
    set_global_var(11, 1);
    gfade_in(10);
    gsay_reply(46, 310);
    giq_option(4, 46, 312, Node010, 50);
    giq_option(4, 46, 311, Node999, 50);
    giq_option(-3, 46, 313, Node010, 50);
    giq_option(-3, 46, 314, Node999, 50);
    prev_node := 9;
end

procedure Node010
begin
    if (((local_var(4) bwand 1024) != 0) == 0) then begin
        set_local_var(4, local_var(4) bwor 1024);
        gsay_reply(46, 320);
        giq_option(4, 46, 327, Node011, 50);
        giq_option(-3, 46, 328, Node011, 50);
    end
    else begin
        if (local_var(5) >= 30) then begin
            if (2 > local_var(6)) then begin
                set_local_var(6, 2);
            end
            gsay_reply(46, 321);
            giq_option(4, 46, 239, Node004, 50);
            giq_option(4, 46, 327, Node999, 50);
            giq_option(-3, 46, 328, Node999, 50);
        end
        else begin
            if (local_var(5) < 0) then begin
                if (1 > local_var(6)) then begin
                    set_local_var(6, 1);
                end
                gsay_reply(46, 322);
                giq_option(4, 46, 239, Node004, 50);
                giq_option(4, 46, 327, Node999, 50);
                giq_option(-3, 46, 328, Node999, 50);
            end
            else begin
                gsay_reply(46, random(323, 326));
                giq_option(4, 46, 327, Node989, 50);
                giq_option(-3, 46, 328, Node989, 50);
            end
        end
    end
    prev_node := 10;
end

procedure Node011
begin
    gsay_reply(46, 340);
    giq_option(4, 46, 341, Node012, 50);
    giq_option(-3, 46, 342, Node012, 50);
    prev_node := 11;
end

procedure Node012
begin
    gsay_reply(46, 350);
    giq_option(4, 46, 351, Node010, 50);
    giq_option(-3, 46, 352, Node010, 50);
    prev_node := 12;
end

procedure Node013
begin
    if (party_being_sold == party_member_obj(16777379)) then begin
        party_price := floor(2 * 450 * ((160.00000 + has_skill(self_obj, 15)) / (160.00000 + has_skill(dude_obj, 15))));
        gsay_reply(46, message_str(46, 361) + party_price + message_str(46, 1361));
    end
    else begin
        if (party_being_sold == party_member_obj(16777380)) then begin
            party_price := floor(2 * 550 * ((160.00000 + has_skill(self_obj, 15)) / (160.00000 + has_skill(dude_obj, 15))));
            gsay_reply(46, message_str(46, 360) + party_price + message_str(46, 1360));
        end
        else begin
            if (party_being_sold == party_member_obj(16777376)) then begin
                party_price := floor(2 * 400 * ((160.00000 + has_skill(self_obj, 15)) / (160.00000 + has_skill(dude_obj, 15))));
                gsay_reply(46, message_str(46, 363) + party_price + message_str(46, 1363));
            end
            else begin
                if (party_being_sold == party_member_obj(16777278)) then begin
                    party_price := 0;
                    gsay_reply(46, 362);
                    giq_option(4, 46, 368, Node999, 50);
                    giq_option(4, 46, 369, Node999, 50);
                end
                else begin
                    if (party_being_sold == party_member_obj(16777305)) then begin
                        party_price := floor(2 * 650 * ((160.00000 + has_skill(self_obj, 15)) / (160.00000 + has_skill(dude_obj, 15))));
                        gsay_reply(46, message_str(46, 364) + party_price + message_str(46, 1364));
                    end
                    else begin
                        if (party_being_sold == party_member_obj(16777313)) then begin
                            party_price := floor(2 * 600 * ((160.00000 + has_skill(self_obj, 15)) / (160.00000 + has_skill(dude_obj, 15))));
                            gsay_reply(46, message_str(46, 365) + party_price + message_str(46, 1365));
                        end
                    end
                end
            end
        end
    end
    if ((metarule(16, 0) - 1) > 1) then begin
        giq_option(4, 46, 366, Node003, 50);
    end
    giq_option(4, 46, 367, Node004, 50);
    if (party_being_sold != party_member_obj(16777278)) then begin
        giq_option(4, 46, 370, Node988, 50);
        giq_option(4, 46, 371, Node015, 50);
        giq_option(4, 46, 372, Node015, 50);
    end
    prev_node := 13;
end

procedure Node015
begin
    gsay_reply(46, 390);
    giq_option(4, 46, 391, Node004, 50);
    giq_option(4, 46, 392, Node999, 50);
    prev_node := 15;
end

procedure Node016
begin
    gsay_reply(46, 400);
    giq_option(4, 46, 401, Node017, 50);
    giq_option(4, 46, 402, Node018, 50);
    prev_node := 16;
end

procedure Node017
begin
    gsay_reply(46, 410);
    giq_option(4, 46, 411, Node018, 50);
    prev_node := 17;
end

procedure Node018
begin
    gsay_reply(46, 420);
    giq_option(4, 46, 421, Node019, 50);
    giq_option(4, 46, 422, Node019, 50);
    prev_node := 18;
end

procedure Node019
begin
    if (3 == 3) then begin
        if (global_var(454) == 2) then begin
            display_msg(message_str(59, 1400));
            give_exp_points(200);
            display_msg(message_str(14, 100) + 200 + message_str(14, 101));
        end
        set_global_var(446, global_var(446) bwor 1073741824);
    end
    else begin
        if (3 == 1) then begin
            set_global_var(447, global_var(447) bwor 1);
        end
        else begin
            if (3 == 5) then begin
                if (global_var(469) == 0) then begin
                    set_global_var(469, game_time + ((24 * (60 * (60 * 10)) * (game_time_hour > 600)) + (((600 / 100) - (game_time_hour / 100)) * (60 * (60 * 10))) + (((600 % 100) - (game_time_hour % 100)) * (60 * 10))) + (24 * (60 * (60 * 10)) * (game_time < 600)));
                end
                if (global_var(454) == 4) then begin
                    display_msg(message_str(59, 1300));
                    give_exp_points(200);
                    display_msg(message_str(14, 100) + 200 + message_str(14, 101));
                end
            end
            else begin
                if (3 == 10) then begin
                    if (((global_var(454) == 10) == 0) and ((global_var(454) == 11) == 0)) then begin
                        display_msg(message_str(59, 200));
                        give_exp_points(1000);
                        display_msg(message_str(14, 100) + 1000 + message_str(14, 101));
                    end
                end
                else begin
                    if (3 == 11) then begin
                        if (((global_var(454) == 10) == 0) and ((global_var(454) == 11) == 0)) then begin
                            if ((global_var(471) == 0) == 0) then begin
                                set_global_var(0, global_var(0) + -50);
                                debug_msg("Player gains " + -50 + " Karma Points.");
                                set_global_var(37, 0);
                                set_global_var(38, 0);
                                set_global_var(39, 0);
                                set_global_var(40, 0);
                                set_global_var(41, 0);
                                set_global_var(42, 0);
                                set_global_var(43, 0);
                                set_global_var(44, 0);
                                set_global_var(45, 0);
                                if (global_var(0) >= 1000) then begin
                                    set_global_var(37, 1);
                                end
                                else begin
                                    if (global_var(0) >= 750) then begin
                                        set_global_var(38, 1);
                                    end
                                    else begin
                                        if (global_var(0) >= 500) then begin
                                            set_global_var(39, 1);
                                        end
                                        else begin
                                            if (global_var(0) >= 250) then begin
                                                set_global_var(40, 1);
                                            end
                                            else begin
                                                if (global_var(0) > -250) then begin
                                                    set_global_var(41, 1);
                                                end
                                                else begin
                                                    if (global_var(0) > -500) then begin
                                                        set_global_var(42, 1);
                                                    end
                                                    else begin
                                                        if (global_var(0) > -750) then begin
                                                            set_global_var(43, 1);
                                                        end
                                                        else begin
                                                            if (global_var(0) > -1000) then begin
                                                                set_global_var(44, 1);
                                                            end
                                                            else begin
                                                                set_global_var(45, 1);
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                                display_msg(message_str(59, 300));
                                give_exp_points(1100);
                                display_msg(message_str(14, 100) + 1100 + message_str(14, 101));
                            end
                        end
                    end
                end
            end
        end
    end
    if (3 > global_var(454)) then begin
        set_global_var(454, 3);
    end
    debug_msg("set_gangwar(" + 3 + ") == " + global_var(454));
    gsay_reply(46, 430);
    giq_option(4, 46, 431, Node004, 50);
    giq_option(4, 46, 432, Node999, 50);
    prev_node := 19;
end

procedure Node020
begin
    if (global_var(452) == 2) then begin
        gsay_reply(46, 441 + ((local_var(4) bwand 2048) != 0));
        if (global_var(457) == 0) then begin
            giq_option(4, 46, 444, Node022, 50);
        end
        giq_option(4, 46, 445, Node021, 50);
        giq_option(4, 46, 446, Node999, 50);
    end
    else begin
        gsay_reply(46, 440);
        if (2 > global_var(452)) then begin
            set_global_var(452, 2);
        end
        giq_option(4, 46, 443, Node020, 50);
    end
    set_local_var(4, local_var(4) bwor 2048);
    prev_node := 20;
end

procedure Node021
begin
    if (((global_var(446) bwand 4194304) != 0) == 0) then begin
        gsay_reply(46, 455 + ((local_var(4) bwand 4096) != 0));
        if (global_var(457) == 0) then begin
            giq_option(4, 46, 459, Node022, 50);
        end
        giq_option(4, 46, 460 + (3 * ((local_var(4) bwand 4096) != 0)), Node023, 50);
        set_local_var(4, local_var(4) bwor 4096);
    end
    else begin
        gsay_reply(46, 457 + ((local_var(4) bwand 8192) != 0));
        set_local_var(4, local_var(4) bwor 8192);
        giq_option(4, 46, 462, Node024, 50);
        if ((local_var(4) bwand 4096) != 0) then begin
            giq_option(4, 46, 463, Node023, 50);
        end
    end
    giq_option(4, 46, 461, Node999, 50);
    prev_node := 21;
end

procedure Node022
begin
    if (2 > global_var(457)) then begin
        set_global_var(457, 2);
    end
    gsay_reply(46, 475);
    giq_option(4, 46, 476, Node021, 50);
    giq_option(4, 46, 477, Node999, 50);
    prev_node := 22;
end

procedure Node023
begin
    gsay_reply(46, 485 + ((local_var(4) bwand 16384) != 0));
    set_local_var(4, local_var(4) bwor 16384);
    if ((global_var(446) bwand 4194304) != 0) then begin
        giq_option(4, 46, 462, Node024, 50);
    end
    giq_option(4, 46, 487, Node999, 50);
    prev_node := 23;
end

procedure Node024
begin
    party_price := 1000 / (((global_var(446) bwand 131072) != 0) + 1);
    gsay_reply(46, message_str(46, 495 + ((local_var(4) bwand 32768) != 0)) + party_price + message_str(46, 1496));
    set_local_var(4, local_var(4) bwor 32768);
    if ((get_critter_stat(dude_obj, 3) > 5) and (get_critter_stat(dude_obj, 34) == 1) and (((global_var(446) bwand 131072) != 0) == 0)) then begin
        giq_option(4, 46, 497, Node026, 49);
    end
    if (item_caps_total(dude_obj) >= party_price) then begin
        giq_option(4, 46, 498, Node025, 49);
    end
    giq_option(4, 46, 499, Node004, 50);
    giq_option(4, 46, 500, Node999, 50);
    prev_node := 24;
end

procedure Node025
begin
    item_caps_adjust(dude_obj, -party_price);
    set_global_var(457, 2);
    if (global_var(100) < 2) then begin
        set_global_var(100, 2);
    end
    set_global_var(445, global_var(445) bwor 134217728);
    gsay_reply(46, 510);
    giq_option(4, 46, 511, Node004, 50);
    giq_option(4, 46, 512, Node999, 50);
    prev_node := 25;
end

procedure Node026
begin
    gsay_reply(46, 520 + ((local_var(4) bwand 65536) != 0));
    set_local_var(4, local_var(4) bwor 65536);
    giq_option(4, 46, 522, Node027, 50);
    giq_option(4, 46, 523, Node987, 50);
    giq_option(4, 46, 524, Node999, 51);
    prev_node := 26;
end

procedure Node027
begin
    gsay_reply(46, 530);
    giq_option(4, 46, 531, Node987, 50);
    prev_node := 27;
end

procedure Node028
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    set_global_var(446, global_var(446) bwand (-1 - 2097152));
    if (((local_var(4) bwand 131072) != 0) == 0) then begin
        display_msg(message_str(59, 700));
        give_exp_points(500);
        display_msg(message_str(14, 100) + 500 + message_str(14, 101));
        set_global_var(0, global_var(0) + -100);
        debug_msg("Player gains " + -100 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        set_global_var(0, global_var(0) + -15);
        debug_msg("Player gains " + -15 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_local_var(4, local_var(4) bwor 131072);
    LVar2 := 100 * global_var(31);
    LVar1 := global_var(31) - (global_var(34) * 7);
    if (LVar1 >= 7) then begin
        LVar0 := random(0, 3);
        if (LVar0 == 0) then begin
            gsay_reply(46, message_str(46, 540) + LVar2 + message_str(46, 1540) + obj_name(dude_obj) + message_str(46, 2540));
        end
        else begin
            if (LVar0 == 3) then begin
                gsay_reply(46, message_str(46, 543) + obj_name(dude_obj) + message_str(46, 1543) + LVar2 + message_str(46, 2543));
            end
            else begin
                gsay_reply(46, message_str(46, 540 + LVar0) + LVar2 + message_str(46, 1540));
            end
        end
        item_caps_adjust(dude_obj, LVar2);
    end
    else begin
        if (LVar1 >= 4) then begin
            LVar0 := random(4, 7);
            gsay_reply(46, message_str(46, 540 + LVar0) + LVar2 + message_str(46, 1540 + LVar0));
            item_caps_adjust(dude_obj, LVar2);
        end
        else begin
            if (LVar1 >= 1) then begin
                LVar0 := random(8, 11);
                gsay_reply(46, message_str(46, 540 + LVar0) + LVar2 + message_str(46, 1540 + LVar0));
                item_caps_adjust(dude_obj, LVar2);
            end
            else begin
                gsay_reply(46, 552);
                giq_option(4, 46, 553, Node999, 49);
                giq_option(4, 46, 554, Node999, 51);
            end
        end
    end
    set_local_var(5, local_var(5) + LVar1);
    if (LVar1 >= 1) then begin
        giq_option(4, 46, 555, Node999, 49);
    end
    giq_option(-3, 46, 556, Node999, 50);
    prev_node := 28;
end

procedure Node029
begin
    variable LVar0 := 0;
    LVar0 := (((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj));
    if (LVar0 >= 10) then begin
        float_msg(self_obj, message_str(46, 575), 8);
    end
    else begin
        if (LVar0 >= 9) then begin
            float_msg(self_obj, message_str(46, 574), 8);
        end
        else begin
            if (LVar0 >= 7) then begin
                float_msg(self_obj, message_str(46, 573), 8);
            end
            else begin
                if (LVar0 >= 5) then begin
                    float_msg(self_obj, message_str(46, 572), 8);
                end
                else begin
                    if (LVar0 >= 3) then begin
                        float_msg(self_obj, message_str(46, 571), 8);
                    end
                    else begin
                        float_msg(self_obj, message_str(46, 570), 8);
                    end
                end
            end
        end
    end
end

procedure Node030
begin
    gsay_reply(46, 620);
    giq_option(4, 46, 621, Node034, 51);
    giq_option(4, 46, 622, Node034, 51);
    giq_option(-3, 46, 623, Node031, 51);
end

procedure Node031
begin
    gsay_reply(46, 630);
    giq_option(-3, 46, 631, Node032, 51);
    giq_option(-3, 46, 632, Node032, 51);
end

procedure Node032
begin
    gsay_reply(46, 640);
    giq_option(-3, 46, 641, Node033, 51);
    giq_option(-3, 46, 642, Node033, 51);
end

procedure Node033
begin
    gsay_reply(46, 650 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(-3, 46, 652, Node998, 51);
    giq_option(-3, 46, 653, Node998, 51);
    giq_option(-3, 46, 654, Node998, 51);
end

procedure Node034
begin
    gsay_reply(46, 670);
    giq_option(4, 46, 671, Node035, 51);
    giq_option(8, 46, 672, Node036, 51);
    giq_option(4, 46, 673, Node037, 51);
end

procedure Node035
begin
    gsay_reply(46, 680);
    giq_option(4, 46, 681, Node998, 51);
    giq_option(4, 46, 682, Node998, 51);
end

procedure Node036
begin
    gsay_reply(46, 690);
    giq_option(4, 46, 691, Node040, 51);
    giq_option(4, 46, 692, Node041, 51);
end

procedure Node037
begin
    gsay_reply(46, 700);
    giq_option(4, 46, 701, Node038, 51);
    giq_option(4, 46, 702, Node998, 51);
    giq_option(4, 46, 703, Node039, 51);
end

procedure Node038
begin
    gsay_reply(46, 710);
    giq_option(4, 46, 711, Node998, 51);
    giq_option(4, 46, 712, Node998, 51);
end

procedure Node039
begin
    gsay_reply(46, 720);
    giq_option(4, 46, 721, Node998, 51);
end

procedure Node040
begin
    gsay_reply(46, 730);
    giq_option(4, 46, 731, Node998, 51);
    giq_option(4, 46, 732, Node998, 51);
end

procedure Node041
begin
    gsay_reply(46, 740);
    giq_option(4, 46, 741, Node998, 51);
    giq_option(4, 46, 742, Node042, 51);
end

procedure Node042
begin
    gsay_reply(46, 750);
    giq_option(4, 46, 751, Node998, 51);
    giq_option(4, 46, 752, Node998, 51);
end

procedure Node043
begin
    gsay_reply(46, 600);
    giq_option(4, 46, 601, Node998, 51);
    giq_option(4, 46, 602, Node998, 51);
    prev_node := 30;
end

procedure set_sell_davin
begin
    party_being_sold := party_member_obj(16777379);
    call Node013();
end

procedure set_sell_miria
begin
    party_being_sold := party_member_obj(16777380);
    call Node013();
end

procedure set_sell_myron
begin
    party_being_sold := party_member_obj(16777376);
    call Node013();
end

procedure set_sell_vic
begin
    party_being_sold := party_member_obj(16777278);
    call Node013();
end

procedure set_sell_macrae
begin
    party_being_sold := party_member_obj(16777305);
    call Node013();
end

procedure set_sell_sulik
begin
    party_being_sold := party_member_obj(16777313);
    call Node013();
end

procedure Node990
begin
    if (global_var(11) == 1) then begin
        call Node010();
    end
    else begin
        call Node006();
    end
end

procedure Node989
begin
    set_global_var(446, global_var(446) bwor 2097152);
    game_time_advance((2 * (24 * (60 * (60 * 10)))) + (random(-6, 6) * (60 * (60 * 10))));
    load_map("DNSlvRun.map", 0);
end

procedure Node988
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    gfade_out(10);
    item_caps_adjust(dude_obj, party_price);
    if ((party_being_sold == party_member_obj(16777380)) or (party_being_sold == party_member_obj(16777379))) then begin
        debug_msg("start: set_dude_was_married");
        if ((global_var(6) != 0) and ((global_var(449) != 0) == 0)) then begin
            debug_msg("   GVAR_PLAYER_WAS_MARRIED before == " + global_var(449));
            set_global_var(449, global_var(6));
            debug_msg("   GVAR_PLAYER_WAS_MARRIED after == " + global_var(449));
            set_global_var(6, 0);
        end
        debug_msg("finished: set_dude_was_married");
        set_global_var(0, global_var(0) + -15);
        debug_msg("Player gains " + -15 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        set_global_var(0, global_var(0) + -15);
        debug_msg("Player gains " + -15 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    LVar0 := obj_pid(party_being_sold);
    set_global_var(445, global_var(445) bwor 4194304);
    if ((obj_item_subtype(critter_inven_obj(party_being_sold, 1)) == 3) or (obj_item_subtype(critter_inven_obj(party_being_sold, 2)) == 3)) then begin
        metarule(43, party_being_sold);
    end
    move_obj_inven_to_obj(party_being_sold, self_obj);
    party_remove(party_being_sold);
    destroy_object(party_being_sold);
    LVar0 := create_object_sid(LVar0, 0, 0, 907);
    while (tile_in_tile_rect(8483, 8465, 14083, 14065, tile_num(LVar0)) == 0) do begin
        LVar1 := random(1, 3);
        if (LVar1 == 1) then begin
            critter_attempt_placement(LVar0, 12271, elevation(self_obj));
        end
        else begin
            if (LVar1 == 2) then begin
                critter_attempt_placement(LVar0, 12077, elevation(self_obj));
            end
            else begin
                critter_attempt_placement(LVar0, 10075, elevation(self_obj));
            end
        end
    end
    debug_msg("exit metzger while loop");
    gfade_in(10);
end

procedure Node987
begin
    gfade_out(10);
    game_time_advance(get_critter_stat(dude_obj, 2) * random(4, 8) * (60 * 10));
    set_global_var(194, global_var(194) + (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) * 1));
    if (global_var(358) >= 9) then begin
        set_global_var(588, 1);
    end
    if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) >= 9) then begin
        set_global_var(589, 1);
    end
    set_global_var(358, global_var(358) + 1);
    set_global_var(446, global_var(446) bwor 131072);
    critter_attempt_placement(self_obj, 14867, elevation(self_obj));
    critter_attempt_placement(dude_obj, 15469, elevation(self_obj));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    metarule3(100, self_obj, 4, 0);
    add_timer_event(self_obj, game_ticks(1), 4);
    gfade_in(10);
end

