variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat;
procedure Node995;
procedure Node996;
procedure Node997;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;

variable Only_Once;
variable k;
variable from_15;
variable item;

procedure Node940;
procedure Node043;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (global_var(395) == 1) then begin
            set_local_var(5, 1);
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
        else begin
            if (local_var(5) == 2) then begin
                set_local_var(5, 1);
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (get_critter_stat(dude_obj, 3) - get_critter_stat(self_obj, 3)) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(51) >= 0) then begin
        reaction_bonus_town_rep := global_var(51) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(51) / 2);
    end
    if (has_trait(2, dude_obj, 13)) then begin
        if (get_critter_stat(dude_obj, 34) == get_critter_stat(self_obj, 34)) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(11) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(11) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(11) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(0, dude_obj, 10));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(1) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if (local_var(6) == 1) then begin
        debug_msg("GCBRAIN: case 1");
        call Node998();
    end
    else begin
        if ((global_var(390) == 2) and (local_var(8) == 0)) then begin
            debug_msg("GCBRAIN: case 2");
            set_local_var(8, 1);
            start_gdialog(130, self_obj, 4, -1, -1);
            gsay_start;
            call Node040();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(83) == 8) then begin
                debug_msg("GCBRAIN: case 3");
                call Node012();
            end
            else begin
                if (get_critter_stat(dude_obj, 4) <= 3) then begin
                    debug_msg("GCBRAIN: case 4");
                    call Node002();
                end
                else begin
                    if (global_var(161) == 2) then begin
                        debug_msg("GCBRAIN: case 5");
                        start_gdialog(130, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node004();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if (obj_is_carrying_obj_pid(dude_obj, 295)) then begin
                            debug_msg("GCBRAIN: case 6");
                            start_gdialog(130, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node022();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            if (global_var(83) == 15) then begin
                                debug_msg("GCBRAIN: case 7");
                                start_gdialog(130, self_obj, 4, -1, -1);
                                gsay_start;
                                call Node014();
                                gsay_end;
                                end_dialogue;
                            end
                            else begin
                                if (global_var(82) == 13) then begin
                                    debug_msg("GCBRAIN: case 8");
                                    start_gdialog(130, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node013();
                                    gsay_end;
                                    end_dialogue;
                                end
                                else begin
                                    if (global_var(82) == 12) then begin
                                        debug_msg("GCBRAIN: case 9");
                                        start_gdialog(130, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node013();
                                        gsay_end;
                                        end_dialogue;
                                    end
                                    else begin
                                        if (global_var(82) == 9) then begin
                                            debug_msg("GCBRAIN: case 10");
                                            start_gdialog(130, self_obj, 4, -1, -1);
                                            gsay_start;
                                            call Node013();
                                            gsay_end;
                                            end_dialogue;
                                        end
                                        else begin
                                            if (global_var(82) == 5) then begin
                                                debug_msg("GCBRAIN: case 11");
                                                start_gdialog(130, self_obj, 4, -1, -1);
                                                gsay_start;
                                                call Node013();
                                                gsay_end;
                                                end_dialogue;
                                            end
                                            else begin
                                                if (global_var(82) == 0) then begin
                                                    debug_msg("GCBRAIN: case 12");
                                                    start_gdialog(130, self_obj, 4, -1, -1);
                                                    gsay_start;
                                                    call Node013();
                                                    gsay_end;
                                                    end_dialogue;
                                                end
                                                else begin
                                                    if (global_var(161) == 1) then begin
                                                        debug_msg("GCBRAIN: case 13");
                                                        start_gdialog(130, self_obj, 4, -1, -1);
                                                        gsay_start;
                                                        call Node003();
                                                        gsay_end;
                                                        end_dialogue;
                                                    end
                                                    else begin
                                                        if (local_var(12) == 0) then begin
                                                            debug_msg("GCBRAIN: case 14");
                                                            start_gdialog(130, self_obj, 4, -1, -1);
                                                            gsay_start;
                                                            call Node005();
                                                            gsay_end;
                                                            end_dialogue;
                                                        end
                                                        else begin
                                                            debug_msg("GCBRAIN: case 15");
                                                            float_msg(self_obj, message_str(130, 700), 2);
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    set_global_var(51, global_var(51) + -10);
    set_global_var(0, global_var(0) + -25);
    debug_msg("Player gains " + -25 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(51, global_var(51) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(51, global_var(51) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(130, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(130, 101));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
        set_global_var(238, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, 1, 6, 49);
    critter_add_trait(self_obj, 1, 5, 177);
end

procedure combat
begin
    call Node998();
end

procedure Node995
begin
    if (get_critter_stat(dude_obj, 3) >= 7) then begin
        set_local_var(3, 100);
        set_local_var(1, 4);
    end
    else begin
        set_local_var(1, -4);
        set_local_var(3, -100);
    end
end

procedure Node996
begin
    set_local_var(1, -4);
    set_local_var(3, -100);
end

procedure Node997
begin
    if (get_critter_stat(dude_obj, 3) >= 8) then begin
        call Node004();
    end
    else begin
        call Node005();
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    float_msg(self_obj, message_str(130, 110), 2);
    call combat();
end

procedure Node002
begin
    k := random(1, 4);
    if (k == 1) then begin
        float_msg(self_obj, message_str(130, 120), 2);
    end
    else begin
        if (k == 2) then begin
            float_msg(self_obj, message_str(130, 121), 2);
        end
        else begin
            if (k == 3) then begin
                float_msg(self_obj, message_str(130, 122), 2);
            end
            else begin
                if (k == 4) then begin
                    float_msg(self_obj, message_str(130, 123), 2);
                end
            end
        end
    end
end

procedure Node003
begin
    debug_msg("GVAR_VAULT_GECKO_PLANT: " + global_var(82));
    if (global_var(82) == 13) then begin
        gsay_reply(130, 602);
        giq_option(4, 130, 606, Node037, 50);
    end
    else begin
        if (global_var(82) == 12) then begin
            gsay_reply(130, 601);
            giq_option(4, 130, 605, Node036, 50);
        end
        else begin
            if (global_var(82) >= 5) then begin
                gsay_reply(130, 603);
                giq_option(4, 130, 607, Node041, 50);
            end
            else begin
                if (global_var(82) == 0) then begin
                    gsay_reply(130, 600);
                    giq_option(4, 130, 604, Node030, 50);
                end
            end
        end
    end
    giq_option(4, 130, 610, Node999, 50);
end

procedure Node004
begin
    gsay_reply(130, 140);
    giq_option(4, 130, 141, Node008, 50);
    giq_option(4, 130, 142, Node008, 50);
    giq_option(4, 130, 143, Node008, 50);
    giq_option(4, 130, 144, Node008, 51);
end

procedure Node005
begin
    gsay_reply(130, 150);
    giq_option(4, 130, 151, Node011, 49);
    giq_option(4, 130, 152, Node026, 50);
    giq_option(4, 130, 154, Node007, 50);
end

procedure Node006
begin
    gsay_reply(130, 160);
    giq_option(4, 130, 161, Node031, 50);
end

procedure Node007
begin
    gsay_reply(130, 170);
    giq_option(4, 130, 171, Node026, 50);
    giq_option(4, 130, 172, Node011, 49);
end

procedure Node008
begin
    gsay_reply(130, 180);
    giq_option(4, 130, 181, Node005, 50);
    giq_option(4, 130, 182, Node024, 51);
end

procedure Node009
begin
    gsay_reply(130, 190);
    giq_option(4, 130, 191, Node010, 50);
end

procedure Node010
begin
    gsay_reply(130, 200);
    giq_option(4, 130, 201, Node011, 50);
end

procedure Node011
begin
    if (local_var(10) == 0) then begin
        set_local_var(10, 1);
        gsay_reply(130, 210);
    end
    else begin
        gsay_reply(130, 211);
    end
    giq_option(1, 130, 212, Node940, 50);
    giq_option(1, 130, 213, Node024, 50);
    giq_option(1, 130, 214, Node009, 50);
end

procedure Node012
begin
    set_local_var(11, local_var(11) + 1);
    if (local_var(11) == 1) then begin
        float_msg(self_obj, message_str(130, 220), 2);
    end
    else begin
        if (local_var(11) == 2) then begin
            float_msg(self_obj, message_str(130, 221), 2);
        end
        else begin
            if (local_var(11) > 2) then begin
                float_msg(self_obj, message_str(130, 222), 2);
                call Node998();
            end
        end
    end
end

procedure Node013
begin
    if (global_var(82) == 13) then begin
        gsay_reply(130, 632);
        giq_option(4, 130, 637, Node037, 50);
    end
    else begin
        if (global_var(82) == 12) then begin
            gsay_reply(130, 631);
            giq_option(4, 130, 636, Node036, 50);
        end
        else begin
            if (global_var(82) == 9) then begin
                gsay_reply(130, 230);
                giq_option(4, 130, 639, Node015, 50);
                giq_option(4, 130, 641, Node015, 50);
            end
            else begin
                if (global_var(82) == 5) then begin
                    gsay_reply(130, 633);
                    giq_option(4, 130, 638, Node041, 50);
                end
                else begin
                    if (global_var(82) == 0) then begin
                        gsay_reply(130, 630);
                        giq_option(4, 130, 635, Node030, 50);
                    end
                end
            end
        end
    end
    giq_option(4, 130, 232, Node016, 50);
    giq_option(4, 130, 233, Node999, 50);
    if (global_var(82) < 5) then begin
        giq_option(4, 130, 234, Node026, 50);
    end
end

procedure Node014
begin
    gsay_reply(130, 240);
    giq_option(4, 130, 241, Node999, 50);
    giq_option(4, 130, 242, Node999, 51);
end

procedure Node015
begin
    from_15 := 1;
    set_global_var(397, 1);
    gsay_reply(130, 250);
    giq_option(4, 130, 251, Node018, 50);
    giq_option(4, 130, 252, Node018, 50);
end

procedure Node016
begin
    gsay_reply(130, 260);
    giq_option(4, 130, 261, Node017, 50);
end

procedure Node017
begin
    if (global_var(82) == 13) then begin
        gsay_reply(130, 652);
        giq_option(4, 130, 656, Node037, 50);
    end
    else begin
        if (global_var(82) == 12) then begin
            gsay_reply(130, 651);
            giq_option(4, 130, 655, Node036, 50);
        end
        else begin
            if (global_var(82) == 9) then begin
                gsay_reply(130, 230);
                giq_option(4, 130, 659, Node015, 50);
            end
            else begin
                if (global_var(82) == 5) then begin
                    gsay_reply(130, 653);
                    giq_option(4, 130, 658, Node041, 50);
                end
                else begin
                    if (global_var(82) == 0) then begin
                        gsay_reply(130, 270);
                        giq_option(4, 130, 654, Node030, 50);
                    end
                end
            end
        end
    end
    gsay_reply(130, 270);
    giq_option(4, 130, 271, Node015, 50);
    giq_option(4, 130, 272, Node999, 50);
end

procedure Node018
begin
    if (from_15) then begin
        from_15 := 0;
        if (global_var(158) == 2) then begin
            gsay_reply(130, 283);
            giq_option(4, 130, 284, Node999, 50);
        end
        else begin
            gsay_reply(130, 280);
        end
    end
    else begin
        gsay_reply(130, 281);
    end
    giq_option(4, 130, 282, Node019, 50);
end

procedure Node019
begin
    gsay_reply(130, 290);
    giq_option(4, 130, 291, Node021, 50);
    giq_option(4, 130, 292, Node020, 50);
end

procedure Node020
begin
    if (local_var(12) == 0) then begin
        gsay_reply(130, 300);
        giq_option(4, 130, 301, Node011, 50);
    end
    else begin
        gsay_message(130, 300, 50);
    end
end

procedure Node021
begin
    gsay_reply(130, 310);
    giq_option(4, 130, 311, Node020, 50);
    giq_option(4, 130, 312, Node999, 51);
end

procedure Node022
begin
    gsay_reply(130, 320);
    giq_option(4, 130, 321, Node033, 50);
    giq_option(4, 130, 322, Node034, 49);
end

procedure Node023
begin
    gsay_reply(130, 330);
    giq_option(4, 130, 331, Node032, 50);
    giq_option(4, 130, 332, Node025, 51);
end

procedure Node024
begin
    gsay_reply(130, 340);
    giq_option(4, 130, 341, Node025, 51);
    giq_option(4, 130, 342, Node027, 50);
    giq_option(4, 130, 343, Node025, 51);
end

procedure Node025
begin
    gsay_message(130, 350, 50);
    call combat();
end

procedure Node026
begin
    gsay_reply(130, 360);
    giq_option(4, 130, 361, Node028, 50);
end

procedure Node027
begin
    gsay_reply(130, 370);
    giq_option(4, 130, 371, Node011, 49);
    giq_option(4, 130, 372, Node024, 51);
end

procedure Node028
begin
    gsay_reply(130, 380);
    giq_option(4, 130, 381, Node029, 50);
end

procedure Node029
begin
    gsay_reply(130, 390);
    giq_option(4, 130, 391, Node030, 50);
end

procedure Node030
begin
    if (global_var(82) < 5) then begin
        debug_msg("set part needed");
        set_global_var(82, 5);
    end
    else begin
        debug_msg("DIDN'T SET PART NEEDED");
    end
    gsay_reply(130, 400);
    giq_option(4, 130, 401, Node006, 50);
    giq_option(4, 130, 402, Node031, 50);
end

procedure Node031
begin
    gsay_reply(130, 410);
    giq_option(4, 130, 411, Node018, 50);
end

procedure Node032
begin
    gsay_reply(130, 420);
    giq_option(4, 130, 421, Node999, 50);
    giq_option(4, 130, 422, Node999, 50);
end

procedure Node033
begin
    gsay_reply(130, 430);
    giq_option(4, 130, 431, Node035, 51);
    giq_option(4, 130, 432, Node034, 49);
end

procedure Node034
begin
    item := obj_carrying_pid_obj(dude_obj, 295);
    rm_obj_from_inven(dude_obj, item);
    destroy_object(item);
    if (global_var(82) >= 15) then begin
        gsay_reply(130, 443);
        giq_option(4, 130, 444, Node014, 50);
    end
    else begin
        if ((global_var(161) == 1) and (global_var(82) < 5)) then begin
            gsay_reply(130, 441);
            giq_option(4, 130, 444, Node003, 50);
        end
        else begin
            gsay_reply(130, 440);
            giq_option(4, 130, 444, Node011, 50);
        end
    end
end

procedure Node035
begin
    gsay_message(130, 450, 50);
    call combat();
end

procedure Node036
begin
    gsay_reply(130, 460);
    giq_option(4, 130, 461, Node015, 50);
    giq_option(4, 130, 462, Node999, 50);
end

procedure Node037
begin
    gsay_reply(130, 463);
    giq_option(4, 130, 462, Node999, 50);
end

procedure Node038
begin
    gsay_reply(130, 464);
    if (global_var(82) == 5) then begin
        giq_option(4, 130, 465, Node031, 50);
    end
    giq_option(4, 130, 466, Node999, 50);
end

procedure Node039
begin
    gsay_reply(130, 467);
    giq_option(4, 130, 468, Node999, 50);
end

procedure Node040
begin
    gsay_reply(130, 500);
    giq_option(1, 130, 501, Node999, 50);
end

procedure Node041
begin
    gsay_reply(130, 504);
    giq_option(4, 130, 505, Node038, 50);
    giq_option(4, 130, 506, Node999, 50);
end

procedure Node042
begin
    gsay_reply(130, 510);
    giq_option(4, 130, 511, Node039, 50);
    giq_option(4, 130, 512, Node999, 50);
end

procedure Node940
begin
    set_local_var(12, 1);
    item := create_object_sid(309, 0, 0, -1);
    add_obj_to_inven(dude_obj, item);
    set_global_var(161, 1);
    set_global_var(51, global_var(51) + 5);
    call Node023();
end

procedure Node043
begin
    if (local_var(9) == 0) then begin
        set_local_var(9, 1);
        float_msg(self_obj, message_str(130, 670), 2);
    end
    else begin
        float_msg(self_obj, message_str(130, 671), 2);
    end
end

