variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure look_at_p_proc
begin
end

procedure description_p_proc
begin
    if ((obj_pid(self_obj) >= 33555648) and (obj_pid(self_obj) <= 33555653)) then begin
        script_overrides;
        if (is_success(do_check(dude_obj, 1, 0))) then begin
            display_msg(message_str(610, 100));
            if (global_var(120) == 0) then begin
                set_global_var(120, 1);
            end
        end
        else begin
            display_msg(message_str(610, 101));
        end
    end
end

procedure map_enter_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    if (metarule(14, 0)) then begin
        if ((obj_pid(self_obj) >= 33555648) and (obj_pid(self_obj) <= 33555659)) then begin
            LVar0 := random(1, 3);
            while (LVar0 > 0) do begin
                LVar0 := LVar0 - 1;
                LVar1 := create_object_sid(random(33555753, 33555761), 0, 0, 610);
                move_to(LVar1, tile_num_in_direction(tile_num(self_obj), random(0, 5), random(1, 7)), 0);
            end
            if (obj_pid(self_obj) <= 33555653) then begin
                if ((obj_pid(self_obj) >= 33555648) and (obj_pid(self_obj) <= 33555653)) then begin
                    LVar0 := random(1, 2);
                    LVar2 := random(0, 5);
                    while (LVar0 > 0) do begin
                        LVar0 := LVar0 - 1;
                        LVar1 := create_object_sid(random(33555756, 33555758), 0, 0, 610);
                        if (LVar0 > 0) then begin
                            move_to(LVar1, tile_num_in_direction(tile_num(self_obj), LVar2, random(0, 1)), 0);
                            LVar2 := (LVar2 + random(1, 2)) % 6;
                        end
                        else begin
                            move_to(LVar1, tile_num(self_obj), 0);
                        end
                    end
                end
            end
        end
    end
    else begin
        if (((global_var(402) bwand 4) != 0) or (global_var(388) == 4)) then begin
            if ((obj_pid(self_obj) >= 33555648) and (obj_pid(self_obj) <= 33555653) or (random(1, 3) != 1)) then begin
                if (has_trait(1, self_obj, 666) == 1) then begin
                    set_obj_visibility(self_obj, 1);
                end
            end
        end
    end
end

procedure map_exit_p_proc
begin
    if (has_trait(1, self_obj, 666) == 0) then begin
        destroy_object(self_obj);
    end
end

