variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;
procedure old_pickup_p_proc;
procedure pickup_p_proc;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure getTimeBit;
procedure tvar_callback(variable arg0);

variable numTvars;
variable cbFunc;
variable target_tile;
variable tt_num;
variable tt_time;
variable tt_go;
variable tile0;
variable lTime0;
variable tile1;
variable lTime1;
variable tile2;
variable lTime2;
variable tile3;
variable lTime3;
variable tile4;
variable lTime4;
variable tile5;
variable lTime5;
variable tile6;
variable lTime6;
variable tile7;
variable lTime7;
variable tile8;
variable lTime8;
variable tile9;
variable lTime9;
variable tile10;
variable lTime10;
variable tile11;
variable lTime11;
variable tile12;
variable lTime12;
variable tile13;
variable lTime13;
variable tile14;
variable lTime14;
variable tile15;
variable lTime15;
variable tile16;
variable lTime16;
variable tile17;
variable lTime17;
variable tile18;
variable lTime18;
variable tile19;
variable lTime19;
variable tile20;
variable lTime20;
variable tile21;
variable lTime21;
variable tile22;
variable lTime22;
variable tile23;
variable lTime23;
variable tile24;
variable lTime24;
variable tile25;
variable lTime25;

procedure getTile(variable arg0);
procedure getTileTime(variable arg0);
procedure curTimeIsGreater(variable arg0);
procedure check_tile_events(variable arg0);
procedure tvar_Warp_To_Pos(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node009a;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;

variable Only_Once;
variable q1;
variable q2;
variable q3;
variable q4;
variable q5;

procedure Node005a;
procedure Node010a;
procedure Node013a;
procedure Node014a;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure old_pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (3 == 1) then begin
            attack_complex(source_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
        else begin
            if (3 == 2) then begin
                float_msg(self_obj, message_str(14, random(3325, 3329)), 0);
                if (7 > -1) then begin
                    if (local_var(7) >= 1) then begin
                        attack_complex(source_obj, 0, 1, 0, 0, 30000, 0, 0);
                    end
                    set_local_var(7, local_var(7) + 1);
                end
            end
            else begin
                if (3 == 3) then begin
                    float_msg(self_obj, message_str(14, random(3050, 3064)), 0);
                    if (7 > -1) then begin
                        if (local_var(7) >= 1) then begin
                            attack_complex(source_obj, 0, 1, 0, 0, 30000, 0, 0);
                        end
                        set_local_var(7, local_var(7) + 1);
                    end
                end
                else begin
                    if (3 == 4) then begin
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), rotation_to_tile(tile_num(source_obj), tile_num(self_obj)), random(8, 14)), 1);
                    end
                end
            end
        end
    end
    if (-1 == 1) then begin
        call old_pickup_p_proc();
    end
end

procedure getTimeBit
begin
    variable LVar0 := 0;
    LVar0 := game_time_hour;
    if ((LVar0 >= 100) and (LVar0 <= 159)) then begin
        return 1;
    end
    if ((LVar0 >= 200) and (LVar0 <= 259)) then begin
        return 2;
    end
    if ((LVar0 >= 300) and (LVar0 <= 359)) then begin
        return 4;
    end
    if ((LVar0 >= 400) and (LVar0 <= 459)) then begin
        return 8;
    end
    if ((LVar0 >= 500) and (LVar0 <= 559)) then begin
        return 16;
    end
    if ((LVar0 >= 600) and (LVar0 <= 659)) then begin
        return 32;
    end
    if ((LVar0 >= 700) and (LVar0 <= 759)) then begin
        return 64;
    end
    if ((LVar0 >= 800) and (LVar0 <= 859)) then begin
        return 128;
    end
    if ((LVar0 >= 900) and (LVar0 <= 959)) then begin
        return 256;
    end
    if ((LVar0 >= 1000) and (LVar0 <= 1059)) then begin
        return 512;
    end
    if ((LVar0 >= 1100) and (LVar0 <= 1159)) then begin
        return 1024;
    end
    if ((LVar0 >= 1200) and (LVar0 <= 1259)) then begin
        return 2048;
    end
    if ((LVar0 >= 1300) and (LVar0 <= 1359)) then begin
        return 4096;
    end
    if ((LVar0 >= 1400) and (LVar0 <= 1459)) then begin
        return 8192;
    end
    if ((LVar0 >= 1500) and (LVar0 <= 1559)) then begin
        return 16384;
    end
    if ((LVar0 >= 1600) and (LVar0 <= 1659)) then begin
        return 32768;
    end
    if ((LVar0 >= 1700) and (LVar0 <= 1759)) then begin
        return 65536;
    end
    if ((LVar0 >= 1800) and (LVar0 <= 1859)) then begin
        return 131072;
    end
    if ((LVar0 >= 1900) and (LVar0 <= 1959)) then begin
        return 262144;
    end
    if ((LVar0 >= 2000) and (LVar0 <= 2059)) then begin
        return 524288;
    end
    if ((LVar0 >= 2100) and (LVar0 <= 2159)) then begin
        return 1048576;
    end
    if ((LVar0 >= 2200) and (LVar0 <= 2259)) then begin
        return 2097152;
    end
    if ((LVar0 >= 2300) and (LVar0 <= 2359)) then begin
        return 4194304;
    end
    if ((LVar0 >= 0) and (LVar0 <= 100)) then begin
        return 8388608;
    end
end

procedure tvar_callback(variable arg0)
begin
    debug_msg("OCJIMMY: callback called");
end

procedure getTile(variable arg0)
begin
    if (arg0 == 0) then begin
        return tile0;
    end
    if (arg0 == 1) then begin
        return tile1;
    end
    if (arg0 == 2) then begin
        return tile2;
    end
    if (arg0 == 3) then begin
        return tile3;
    end
    if (arg0 == 4) then begin
        return tile4;
    end
    if (arg0 == 5) then begin
        return tile5;
    end
    if (arg0 == 6) then begin
        return tile6;
    end
    if (arg0 == 7) then begin
        return tile7;
    end
    if (arg0 == 8) then begin
        return tile8;
    end
    if (arg0 == 9) then begin
        return tile9;
    end
    if (arg0 == 10) then begin
        return tile10;
    end
    if (arg0 == 11) then begin
        return tile11;
    end
    if (arg0 == 12) then begin
        return tile12;
    end
    if (arg0 == 13) then begin
        return tile13;
    end
    if (arg0 == 14) then begin
        return tile14;
    end
    if (arg0 == 15) then begin
        return tile15;
    end
    if (arg0 == 16) then begin
        return tile16;
    end
    if (arg0 == 17) then begin
        return tile17;
    end
    if (arg0 == 18) then begin
        return tile18;
    end
    if (arg0 == 19) then begin
        return tile19;
    end
    if (arg0 == 20) then begin
        return tile20;
    end
    if (arg0 == 21) then begin
        return tile21;
    end
    if (arg0 == 22) then begin
        return tile22;
    end
    if (arg0 == 23) then begin
        return tile23;
    end
    if (arg0 == 24) then begin
        return tile24;
    end
    if (arg0 == 25) then begin
        return tile25;
    end
end

procedure getTileTime(variable arg0)
begin
    if (arg0 == 0) then begin
        return lTime0;
    end
    if (arg0 == 1) then begin
        return lTime1;
    end
    if (arg0 == 2) then begin
        return lTime2;
    end
    if (arg0 == 3) then begin
        return lTime3;
    end
    if (arg0 == 4) then begin
        return lTime4;
    end
    if (arg0 == 5) then begin
        return lTime5;
    end
    if (arg0 == 6) then begin
        return lTime6;
    end
    if (arg0 == 7) then begin
        return lTime7;
    end
    if (arg0 == 8) then begin
        return lTime8;
    end
    if (arg0 == 9) then begin
        return lTime9;
    end
    if (arg0 == 10) then begin
        return lTime10;
    end
    if (arg0 == 11) then begin
        return lTime11;
    end
    if (arg0 == 12) then begin
        return lTime12;
    end
    if (arg0 == 13) then begin
        return lTime13;
    end
    if (arg0 == 14) then begin
        return lTime14;
    end
    if (arg0 == 15) then begin
        return lTime15;
    end
    if (arg0 == 16) then begin
        return lTime16;
    end
    if (arg0 == 17) then begin
        return lTime17;
    end
    if (arg0 == 18) then begin
        return lTime18;
    end
    if (arg0 == 19) then begin
        return lTime19;
    end
    if (arg0 == 20) then begin
        return lTime20;
    end
    if (arg0 == 21) then begin
        return lTime21;
    end
    if (arg0 == 22) then begin
        return lTime22;
    end
    if (arg0 == 23) then begin
        return lTime23;
    end
    if (arg0 == 24) then begin
        return lTime24;
    end
    if (arg0 == 25) then begin
        return lTime25;
    end
end

procedure curTimeIsGreater(variable arg0)
begin
    if (game_time > arg0) then begin
        return 1;
    end
    return 0;
end

procedure check_tile_events(variable arg0)
begin
    variable LVar1 := 0;
    if (arg0 == -1) then begin
        if (tt_go) then begin
            if (tile_num(self_obj) == target_tile) then begin
                call cbFunc(target_tile);
                tt_go := 0;
                tt_num := tt_num + 1;
                if (tt_num >= numTvars) then begin
                    tt_num := 0;
                end
                target_tile := getTile(tt_num);
                tt_time := game_time + getTileTime(tt_num);
            end
        end
        else begin
            if (curTimeIsGreater(tt_time)) then begin
                debug_msg("should be going to tile: " + target_tile);
                tt_go := 1;
                if (not(combat_is_initialized)) then begin
                    reg_anim_func(2, self_obj);
                    reg_anim_func(1, 1);
                    animate_move_obj_to_tile(self_obj, target_tile, 0);
                    reg_anim_func(3, 0);
                end
            end
        end
        return 1;
    end
    else begin
        return 0;
    end
end

procedure tvar_Warp_To_Pos(variable arg0, variable arg1)
begin
    move_to(self_obj, getTile(arg0), elevation(self_obj));
    arg0 := arg0 + 1;
    if (arg0 >= numTvars) then begin
        arg0 := 0;
    end
    target_tile := getTile(arg0);
    tt_go := 0;
    tt_time := arg1;
end

procedure start
begin
    if ((global_var(582) bwand 1) != 0) then begin
        global_temp := create_object_sid(128, 0, 0, -1);
        move_obj_inven_to_obj(self_obj, global_temp);
        destroy_object(global_temp);
        kill_critter(self_obj, 62);
    end
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) or map_var(5) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        set_map_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 2;
    Karma_Perception := 10;
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (get_critter_stat(dude_obj, 3) - get_critter_stat(self_obj, 3)) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(59) >= 0) then begin
        reaction_bonus_town_rep := global_var(59) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(59) / 2);
    end
    if (has_trait(2, dude_obj, 13)) then begin
        if (get_critter_stat(dude_obj, 34) == get_critter_stat(self_obj, 34)) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(11) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(11) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(11) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(0, dude_obj, 10));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(1) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if (local_var(5)) then begin
        call Node019();
    end
    else begin
        if (global_var(350) == 3) then begin
            call Node020();
        end
        else begin
            if (global_var(350) == 7) then begin
                call Node018();
            end
            else begin
                if (local_var(4) == 0) then begin
                    start_gdialog(531, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node001();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    start_gdialog(531, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node016();
                    gsay_end;
                    end_dialogue;
                end
            end
        end
    end
    set_local_var(4, 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(59, global_var(59) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(59, global_var(59) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(531, 100));
    end
    else begin
        display_msg(message_str(531, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(531, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
        set_map_var(5, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, 1, 6, 114);
    critter_add_trait(self_obj, 1, 5, 22);
    numTvars := 4;
    cbFunc := "tvar_callback";
    tile0 := 23265;
    lTime0 := game_ticks(1);
    tile1 := 23059;
    lTime1 := game_ticks(1);
    tile2 := 21058;
    lTime2 := game_ticks(1);
    tile3 := 23258;
    lTime3 := game_ticks(1);
    if (not(metarule(22, 0))) then begin
        call tvar_Warp_To_Pos(0, game_ticks(random(10, 20)));
    end
    add_timer_event(self_obj, game_ticks(5), -1);
end

procedure push_p_proc
begin
end

procedure timed_event_p_proc
begin
    if (check_tile_events(fixed_param)) then begin
        add_timer_event(self_obj, game_ticks(5), -1);
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    gsay_reply(531, 103);
    giq_option(-3, 531, 104, Node002, 50);
    giq_option(-3, 531, message_str(531, 105) + " " + obj_name(dude_obj) + message_str(531, 180), Node004, 50);
    giq_option(-3, 531, 106, Node999, 50);
    giq_option(4, 531, 107, Node002, 50);
    giq_option(4, 531, message_str(531, 108) + " " + obj_name(dude_obj) + message_str(531, 181), Node004, 49);
    giq_option(4, 531, 109, Node003, 51);
    giq_option(4, 531, 110, Node999, 50);
end

procedure Node002
begin
    gsay_reply(531, 111);
    giq_option(-3, 531, 112, Node999, 50);
    giq_option(4, 531, 113, Node999, 50);
    giq_option(4, 531, 114, Node003, 51);
end

procedure Node003
begin
    gsay_reply(531, 115);
    giq_option(4, 531, 116, Node999, 50);
end

procedure Node004
begin
    if (local_var(9) == 0) then begin
        set_local_var(9, local_var(9) + 1);
        gsay_reply(531, message_str(531, 117) + " " + obj_name(dude_obj) + message_str(531, 182));
    end
    else begin
        gsay_reply(531, 118);
    end
    if (not(q1)) then begin
        giq_option(-3, 531, 119, Node005a, 50);
        giq_option(4, 531, 126, Node005a, 50);
    end
    if (not(q2)) then begin
        giq_option(-3, 531, 120, Node009a, 50);
        giq_option(4, 531, 127, Node009a, 50);
    end
    if (not(q3)) then begin
        giq_option(-3, 531, 121, Node010a, 50);
        giq_option(4, 531, 128, Node010a, 50);
    end
    if (not(q4)) then begin
        giq_option(-3, 531, 122, Node013a, 50);
        giq_option(4, 531, 129, Node013a, 50);
    end
    if (not(q5)) then begin
        giq_option(-3, 531, 123, Node014a, 50);
        giq_option(4, 531, 130, Node014a, 50);
    end
    if ((global_var(350) == 2) or (global_var(350) == 1)) then begin
        giq_option(-3, 531, 124, Node017, 50);
        giq_option(4, 531, 131, Node017, 50);
    end
    giq_option(-3, 531, 125, Node999, 50);
    giq_option(4, 531, 132, Node999, 50);
end

procedure Node005
begin
    gsay_reply(531, 133);
    giq_option(-3, 531, 134, Node006, 50);
    giq_option(4, 531, 135, Node006, 50);
    if ((global_var(350) == 6) or (global_var(350) == 2)) then begin
        giq_option(4, 531, 136, Node008, 50);
    end
end

procedure Node006
begin
    gsay_reply(531, 137);
    giq_option(-3, 531, 138, Node007, 50);
    giq_option(4, 531, 139, Node007, 50);
end

procedure Node007
begin
    gsay_reply(531, 140);
    giq_option(-3, 531, 141, Node008, 50);
    giq_option(4, 531, 142, Node008, 50);
    if ((global_var(350) == 6) or (global_var(350) == 2)) then begin
        giq_option(4, 531, 143, Node008, 50);
    end
end

procedure Node008
begin
    if (not(global_var(487))) then begin
        set_global_var(487, 1);
    end
    if (get_critter_stat(dude_obj, 4) < 3) then begin
        gsay_reply(531, 144);
    end
    else begin
        gsay_reply(531, 145);
    end
    giq_option(-3, 531, 146, Node004, 50);
    giq_option(4, 531, 147, Node004, 50);
end

procedure Node009
begin
    gsay_reply(531, 148);
    giq_option(-3, 531, 149, Node004, 50);
    giq_option(4, 531, 150, Node004, 50);
end

procedure Node009a
begin
    q2 := 1;
    call Node009();
end

procedure Node010
begin
    gsay_reply(531, 151);
    giq_option(-3, 531, 152, Node011, 50);
    giq_option(-3, 531, 153, Node004, 50);
    giq_option(4, 531, 154, Node011, 50);
    giq_option(4, 531, 155, Node004, 50);
end

procedure Node011
begin
    gsay_reply(531, 156);
    giq_option(-3, 531, 157, Node012, 50);
    giq_option(4, 531, 158, Node012, 50);
end

procedure Node012
begin
    gsay_reply(531, 159);
    giq_option(-3, 531, 160, Node004, 50);
    giq_option(4, 531, 161, Node004, 50);
end

procedure Node013
begin
    gsay_reply(531, 162);
    giq_option(-3, 531, 163, Node004, 50);
    giq_option(4, 531, 164, Node004, 50);
end

procedure Node014
begin
    gsay_reply(531, 165);
    giq_option(-3, 531, 166, Node015, 50);
    giq_option(4, 531, 167, Node015, 50);
end

procedure Node015
begin
    gsay_reply(531, 168);
    giq_option(-3, 531, 169, Node004, 50);
    giq_option(4, 531, 170, Node004, 50);
end

procedure Node016
begin
    gsay_reply(531, 171);
    giq_option(-3, 531, 172, Node004, 50);
    giq_option(-3, 531, 173, Node999, 50);
    giq_option(4, 531, 174, Node004, 50);
    giq_option(4, 531, 175, Node999, 50);
end

procedure Node017
begin
    gsay_reply(531, 176);
    giq_option(1, 531, 177, Node004, 50);
end

procedure Node018
begin
    float_msg(self_obj, message_str(531, 178), 0);
end

procedure Node019
begin
    float_msg(self_obj, message_str(531, 179), 2);
    call Node998();
end

procedure Node020
begin
    float_msg(self_obj, message_str(531, 183), 0);
end

procedure Node005a
begin
    q1 := 1;
    call Node005();
end

procedure Node010a
begin
    q3 := 1;
    call Node010();
end

procedure Node013a
begin
    q4 := 1;
    call Node013();
end

procedure Node014a
begin
    q5 := 1;
    call Node014();
end

