variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node015a;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node020a;
procedure Node021;
procedure Node022;
procedure Node022a;
procedure Node023;
procedure Node023a;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;

import variable vault_city_randal_box;
import variable vault_city_downtown_temp_box;
import variable Randal_Ptr;

variable Only_Once;
variable From_WTG;
variable From_19;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    Randal_Ptr := self_obj;
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(5) == 2) or (global_var(137) == 1)) then begin
            debug_msg("LVAR_Hostile == " + local_var(5));
            debug_msg("GVAR_ENEMY_VAULT_CITY == " + global_var(137));
            set_local_var(5, 1);
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 3;
    Karma_Perception := 30;
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (get_critter_stat(dude_obj, 3) - get_critter_stat(self_obj, 3)) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(50) >= 0) then begin
        reaction_bonus_town_rep := global_var(50) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(50) / 2);
    end
    if (has_trait(2, dude_obj, 13)) then begin
        if (get_critter_stat(dude_obj, 34) == get_critter_stat(self_obj, 34)) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(11) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(11) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(11) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(0, dude_obj, 10));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(1) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    From_WTG := 1;
    From_19 := 0;
    move_obj_inven_to_obj(self_obj, vault_city_downtown_temp_box);
    if ((local_var(7) == 2) or (global_var(79) == 5) or (global_var(79) == 4)) then begin
        move_obj_inven_to_obj(vault_city_randal_box, self_obj);
    end
    if (global_var(494) == 8) then begin
        call Node001();
    end
    else begin
        if (global_var(79) == 6) then begin
            call Node002();
        end
        else begin
            if (obj_can_see_obj(self_obj, party_member_obj(16777377)) and (global_var(79) != 5)) then begin
                call Node003();
            end
            else begin
                if (obj_can_see_obj(self_obj, party_member_obj(16777323)) and (global_var(79) != 5)) then begin
                    call Node004();
                end
                else begin
                    if ((game_time_hour <= 600) or (game_time_hour >= 1800)) then begin
                        call Node008();
                    end
                    else begin
                        if (local_var(7) > 0) then begin
                            start_gdialog(119, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node014();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            start_gdialog(119, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node009();
                            gsay_end;
                            end_dialogue;
                        end
                    end
                end
            end
        end
    end
    if ((local_var(7) == 2) or (global_var(79) == 5) or (global_var(79) == 4)) then begin
        move_obj_inven_to_obj(self_obj, vault_city_randal_box);
    end
    move_obj_inven_to_obj(vault_city_downtown_temp_box, self_obj);
    set_local_var(4, 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(50, global_var(50) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(50, global_var(50) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(119, 101));
    end
    else begin
        display_msg(message_str(119, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(119, 101));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
        set_global_var(137, 1);
        set_global_var(79, 6);
        set_global_var(50, global_var(50) + -30);
        set_global_var(81, 0);
    end
end

procedure map_enter_p_proc
begin
    Randal_Ptr := self_obj;
    Only_Once := 0;
    critter_add_trait(self_obj, 1, 6, 26);
    critter_add_trait(self_obj, 1, 5, 33);
    if (not(metarule(22, 0))) then begin
        if ((game_time_hour > 700) and (game_time_hour < 1800)) then begin
            if (not(has_trait(1, self_obj, 666))) then begin
                set_obj_visibility(self_obj, 0);
                add_timer_event(self_obj, game_ticks(random(20, 40)), 1);
            end
        end
        else begin
            if (has_trait(1, self_obj, 666)) then begin
                set_obj_visibility(self_obj, 1);
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (not(combat_is_initialized)) then begin
            if (global_var(494) == 8) then begin
                call Node001();
            end
            else begin
                if ((game_time_hour > 600) and (game_time_hour < 1800)) then begin
                    if (global_var(79) == 5) then begin
                        call Node005();
                    end
                    else begin
                        if (global_var(79) == 6) then begin
                            call Node002();
                        end
                        else begin
                            if (obj_can_see_obj(self_obj, party_member_obj(16777377)) and (global_var(79) != 5)) then begin
                                call Node003();
                            end
                            else begin
                                if (obj_can_see_obj(self_obj, party_member_obj(16777323)) and (global_var(79) != 5)) then begin
                                    call Node004();
                                end
                                else begin
                                    if (global_var(79) == 4) then begin
                                        call Node006();
                                    end
                                    else begin
                                        call Node007();
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        add_timer_event(self_obj, game_ticks(random(20, 40)), 1);
    end
end

procedure map_update_p_proc
begin
    Randal_Ptr := self_obj;
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    variable LVar0 := 0;
    LVar0 := random(104, 106);
    if (LVar0 == 104) then begin
        float_msg(self_obj, message_str(119, message_str(119, 104) + obj_name(dude_obj) + message_str(119, 225)), 8);
    end
    else begin
        float_msg(self_obj, message_str(119, LVar0), 8);
    end
end

procedure Node002
begin
    float_msg(self_obj, message_str(119, 107), 8);
    call Node998();
end

procedure Node003
begin
    float_msg(self_obj, message_str(119, 108), 8);
    call Node998();
end

procedure Node004
begin
    float_msg(self_obj, message_str(119, 109), 8);
    call Node998();
end

procedure Node005
begin
    float_msg(self_obj, message_str(119, random(110, 111)), 8);
end

procedure Node006
begin
    float_msg(self_obj, message_str(119, random(112, 113)), 8);
end

procedure Node007
begin
    float_msg(self_obj, message_str(119, random(114, 117)), 8);
end

procedure Node008
begin
    float_msg(self_obj, message_str(119, random(118, 119)), 8);
end

procedure Node009
begin
    From_WTG := 0;
    gsay_reply(119, 120);
    if (not(global_var(233))) then begin
        giq_option(-3, 119, 121, Node010, 50);
    end
    giq_option(-3, 119, 122, Node999, 50);
    giq_option(-3, 119, 123, Node999, 50);
    giq_option(4, 119, 124, Node015, 50);
    giq_option(4, 119, 125, Node999, 50);
end

procedure Node010
begin
    gsay_reply(119, 126);
    giq_option(-3, 119, 127, Node011, 50);
    giq_option(-3, 119, 128, Node999, 50);
    giq_option(4, 119, 129, Node011, 50);
    giq_option(4, 119, 130, Node014, 50);
    giq_option(4, 119, 131, Node999, 50);
end

procedure Node011
begin
    gsay_reply(119, 132);
    giq_option(-3, 119, 133, Node012, 50);
    giq_option(-3, 119, 134, Node999, 50);
    giq_option(4, 119, 135, Node012, 50);
    giq_option(4, 119, 136, Node014, 50);
    giq_option(4, 119, 137, Node999, 50);
end

procedure Node012
begin
    gsay_reply(119, 138);
    giq_option(-3, 119, 139, Node013, 50);
    giq_option(-3, 119, 140, Node999, 50);
    giq_option(4, 119, 141, Node013, 50);
    giq_option(4, 119, 142, Node014, 50);
    giq_option(4, 119, 143, Node999, 50);
end

procedure Node013
begin
    if ((global_var(79) == 5) or (global_var(79) == 4)) then begin
        gsay_reply(119, 144);
    end
    else begin
        gsay_reply(119, 145);
    end
    giq_option(-3, 119, 146, Node999, 50);
    giq_option(4, 119, 147, Node014, 50);
    giq_option(4, 119, 148, Node999, 50);
end

procedure Node014
begin
    if (From_WTG == 1) then begin
        From_WTG := 0;
        gsay_reply(119, 149);
    end
    gsay_reply(119, 150);
    giq_option(-3, 119, 151, Node010, 50);
    giq_option(-3, 119, 152, Node999, 50);
    giq_option(4, 119, 153, Node015, 50);
    if (not(global_var(233))) then begin
        giq_option(4, 119, 154, Node010, 50);
    end
    if (global_var(493) == 1) then begin
        giq_option(4, 119, 155, Node029, 50);
    end
    if (global_var(82) == 6) then begin
        if (get_critter_stat(dude_obj, 4) == 4) then begin
            giq_option(4, 119, 156, Node023, 50);
        end
        giq_option(5, 119, 157, Node023, 50);
    end
    if (global_var(88) == 7) then begin
        giq_option(4, 119, 158, Node025, 50);
    end
    giq_option(4, 119, 159, Node999, 50);
end

procedure Node015
begin
    gsay_reply(119, 160);
    giq_option(4, 119, 161, Node015a, 50);
    if (not(global_var(233))) then begin
        giq_option(4, 119, 162, Node010, 50);
    end
    if (global_var(493) == 1) then begin
        giq_option(4, 119, 163, Node029, 50);
    end
    if (global_var(82) == 6) then begin
        if (get_critter_stat(dude_obj, 4) == 4) then begin
            giq_option(4, 119, 164, Node023, 50);
        end
        giq_option(5, 119, 165, Node023, 50);
    end
    if (global_var(88) == 7) then begin
        giq_option(4, 119, 166, Node025, 50);
    end
    giq_option(4, 119, 167, Node014, 50);
    giq_option(4, 119, 168, Node999, 50);
end

procedure Node015a
begin
    if ((global_var(79) == 5) or (global_var(79) == 4) or (local_var(7) == 2)) then begin
        gdialog_mod_barter(-35);
        gsay_reply(119, 228);
        giq_option(4, 119, 229, Node028, 50);
    end
    else begin
        call Node016();
    end
end

procedure Node016
begin
    gsay_reply(119, 169);
    giq_option(4, 119, 171, Node017, 50);
    giq_option(4, 119, 172, Node019, 50);
    if (global_var(82) == 6) then begin
        if (get_critter_stat(dude_obj, 4) == 4) then begin
            giq_option(4, 119, 164, Node023, 50);
        end
        giq_option(5, 119, 174, Node023, 50);
    end
    if (global_var(88) == 7) then begin
        giq_option(4, 119, 175, Node025, 50);
    end
    giq_option(4, 119, 176, Node014, 50);
    giq_option(4, 119, 177, Node999, 50);
end

procedure Node017
begin
    gsay_reply(119, 178);
    giq_option(4, 119, 179, Node018, 50);
    giq_option(4, 119, 180, Node014, 50);
    giq_option(4, 119, 181, Node999, 50);
end

procedure Node018
begin
    gsay_reply(119, 182);
    giq_option(4, 119, 183, Node014, 50);
    giq_option(4, 119, 184, Node999, 50);
end

procedure Node019
begin
    From_19 := 1;
    gsay_reply(119, 185);
    giq_option(4, 119, 186, Node021, 50);
    if (obj_is_carrying_obj_pid(dude_obj, 256) > 0) then begin
        giq_option(4, 119, 187, Node020, 50);
    end
    giq_option(4, 119, 188, Node999, 50);
end

procedure Node020
begin
    gsay_reply(119, 189);
    giq_option(4, 119, 190, Node021, 51);
    giq_option(4, 119, 191, Node021, 50);
    giq_option(4, 119, 192, Node020a, 50);
end

procedure Node020a
begin
    gfade_out(600);
    gfade_in(600);
    call Node022();
end

procedure Node021
begin
    gsay_reply(119, 193);
    if (From_19 == 1) then begin
        From_19 := 0;
        giq_option(4, 119, 194, Node014, 50);
    end
    giq_option(4, 119, 195, Node999, 50);
end

procedure Node022
begin
    set_local_var(7, 2);
    move_obj_inven_to_obj(vault_city_randal_box, self_obj);
    gsay_reply(119, 196);
    giq_option(4, 119, 197, Node022a, 50);
    giq_option(4, 119, 198, Node014, 50);
    giq_option(4, 119, 199, Node999, 50);
end

procedure Node022a
begin
    gdialog_mod_barter(-35);
    gsay_reply(119, 228);
    giq_option(4, 119, 229, Node028, 50);
end

procedure Node023
begin
    if (global_var(79) == 4) then begin
        gsay_reply(119, message_str(119, 200) + obj_name(dude_obj) + message_str(119, 226));
    end
    else begin
        gsay_reply(119, message_str(119, 201) + obj_name(dude_obj) + message_str(119, 227));
    end
    giq_option(4, 119, 202, Node023a, 50);
    giq_option(4, 119, 203, Node999, 50);
end

procedure Node023a
begin
    gfade_out(600);
    gfade_in(600);
    call Node024();
end

procedure Node024
begin
    variable LVar0 := 0;
    LVar0 := create_object_sid(258, 0, 0, -1);
    add_obj_to_inven(dude_obj, LVar0);
    set_global_var(139, 2);
    set_global_var(82, 7);
    gsay_reply(119, 204);
    giq_option(4, 119, 205, Node015a, 50);
    giq_option(4, 119, 206, Node014, 50);
    giq_option(8, 119, 207, Node999, 50);
    giq_option(4, 119, 208, Node999, 50);
end

procedure Node025
begin
    if (global_var(79) == 5) then begin
        gsay_reply(119, 209);
    end
    else begin
        gsay_reply(119, 210);
    end
    giq_option(4, 119, 211, Node026, 50);
    giq_option(4, 119, 212, Node999, 50);
end

procedure Node026
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    LVar0 := create_object_sid(352, 0, 0, -1);
    add_obj_to_inven(dude_obj, LVar0);
    LVar1 := create_object_sid(25, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, LVar1, 2);
    set_global_var(88, 8);
    gsay_reply(119, 213);
    giq_option(4, 119, 214, Node027, 50);
end

procedure Node027
begin
    gsay_reply(119, 215);
    giq_option(4, 119, 216, Node015a, 50);
    giq_option(4, 119, 217, Node014, 50);
    giq_option(4, 119, 218, Node999, 50);
end

procedure Node028
begin
    gsay_reply(119, 219);
    giq_option(4, 119, 220, Node014, 50);
    giq_option(4, 119, 221, Node999, 50);
end

procedure Node029
begin
    gsay_reply(119, 222);
    giq_option(4, 119, 223, Node014, 50);
    giq_option(4, 119, 224, Node999, 50);
end

