variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure use_p_proc;
procedure talk_p_proc;
procedure look_p_proc;
procedure description_p_proc;
procedure push_p_proc;
procedure Node001;
procedure Node002;
procedure Node010;
procedure Node011;
procedure Node999;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure use_p_proc
begin
    variable LVar0 := 0;
    if (get_critter_stat(source_obj, 4) < 4) then begin
        if (source_obj == dude_obj) then begin
            display_msg(message_str(161, 102));
        end
        else begin
            display_msg(obj_name(source_obj) + message_str(161, 200));
        end
    end
    else begin
        dialogue_system_enter;
    end
end

procedure talk_p_proc
begin
    if (local_var(0) == 1) then begin
        start_gdialog(161, self_obj, 4, -1, -1);
        gsay_start;
        call Node002();
        gsay_end;
        end_dialogue;
    end
    else begin
        start_gdialog(161, self_obj, 4, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
    end
end

procedure look_p_proc
begin
    script_overrides;
    display_msg(message_str(161, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(161, 101));
end

procedure push_p_proc
begin
end

procedure Node001
begin
    gsay_reply(161, message_str(161, 103) + message_str(161, 104));
    giq_option(4, 161, 105, Node010, 50);
    giq_option(4, 161, 106, Node011, 50);
    giq_option(4, 161, 107, Node999, 50);
end

procedure Node002
begin
    gsay_reply(161, 110);
    giq_option(4, 161, 111, Node999, 50);
end

procedure Node010
begin
    if (map_var(72) == 1) then begin
        if (map_var(73) == 1) then begin
            if (map_var(74) == 1) then begin
                gsay_reply(161, 113);
            end
            else begin
                gsay_reply(161, 117);
            end
        end
        else begin
            if (map_var(74) == 1) then begin
                gsay_reply(161, 115);
            end
            else begin
                gsay_reply(161, 119);
            end
        end
    end
    else begin
        if (map_var(73) == 1) then begin
            if (map_var(74) == 1) then begin
                gsay_reply(161, 114);
            end
            else begin
                gsay_reply(161, 118);
            end
        end
        else begin
            if (map_var(74) == 1) then begin
                gsay_reply(161, 116);
            end
            else begin
                gsay_reply(161, 120);
            end
        end
    end
    giq_option(4, 161, 153, Node011, 50);
    giq_option(4, 161, 154, Node999, 50);
end

procedure Node011
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    set_local_var(0, 1);
    if ((map_var(73) == 0) or (map_var(74) == 0) or (map_var(72) == 0)) then begin
        set_map_var(75, 1);
        gsay_reply(161, message_str(161, 155) + message_str(161, 156));
    end
    else begin
        gfade_out(600);
        gfade_in(600);
        if (tile_contains_obj_pid(8908, elevation(self_obj), 33555662)) then begin
            LVar0 := tile_contains_pid_obj(8908, elevation(self_obj), 33555662);
            destroy_object(LVar0);
            if (global_var(155) == 4) then begin
                LVar1 := create_object_sid(16777295, 8908, elevation(self_obj), 167);
                debug_msg("Made Cybernetic Robobrain " + obj_pid(LVar1));
            end
            else begin
                if (global_var(155) == 3) then begin
                    LVar1 := create_object_sid(16777597, 8908, elevation(self_obj), 167);
                    debug_msg("Made Human Robobrain " + obj_pid(LVar1));
                end
                else begin
                    if (global_var(155) == 2) then begin
                        LVar1 := create_object_sid(16777595, 8908, elevation(self_obj), 167);
                        debug_msg("Made Chimp Robobrain " + obj_pid(LVar1));
                    end
                    else begin
                        if (global_var(155) == 1) then begin
                            LVar1 := create_object_sid(16777596, 8908, elevation(self_obj), 167);
                            debug_msg("Made Abnormal Robobrain " + obj_pid(LVar1));
                        end
                    end
                end
            end
        end
        if (global_var(155) == 4) then begin
            gsay_reply(161, 500);
        end
        else begin
            if (global_var(155) == 3) then begin
                gsay_reply(161, message_str(161, 164) + message_str(161, 165) + message_str(161, 166) + message_str(161, 167));
            end
            else begin
                if (global_var(155) == 2) then begin
                    gsay_reply(161, message_str(161, 164) + message_str(161, 165) + message_str(161, 170) + message_str(161, 167));
                end
                else begin
                    if (global_var(155) == 1) then begin
                        gsay_reply(161, message_str(161, 164) + message_str(161, 165) + message_str(161, 174) + message_str(161, 167));
                    end
                end
            end
        end
    end
    giq_option(4, 161, 176, Node999, 50);
end

procedure Node999
begin
end

