variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure combat_p_proc;
procedure timed_event_p_proc;
procedure Node997;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;

import variable Map_event;
import variable Kuggar_obj;

variable probability;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Kuggar_obj := self_obj;
end

procedure critter_p_proc
begin
    if (((global_var(865) bwand 4096) != 0) and (global_var(882) != 3) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure pickup_p_proc
begin
end

procedure talk_p_proc
begin
    if (local_var(4) == 1) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            float_msg(self_obj, message_str(1715, 300), 3);
        end
        else begin
            float_msg(self_obj, message_str(1715, 301), 3);
        end
    end
    else begin
        anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
        start_gdialog(1715, self_obj, 4, -1, -1);
        gsay_start;
        call Node500();
        gsay_end;
        end_dialogue;
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(51, global_var(51) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(51, global_var(51) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(867, global_var(867) bwor 4194304);
    if (global_var(882) != 3) then begin
        set_map_var(1, map_var(1) + 1);
    end
    if (global_var(882) == 1) then begin
        set_global_var(882, 2);
    end
    if ((map_var(1) >= 3) and (global_var(862) == 0) and (global_var(864) == 0)) then begin
        terminate_combat;
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(1715, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1715, 200));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    probability := random(0, 12);
    if ((probability >= 12) and (get_critter_stat(self_obj, 35) > 1) and not(critter_is_fleeing(self_obj))) then begin
        float_msg(self_obj, message_str(1715, 403), 2);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 263);
    critter_add_trait(self_obj, 1, 5, 1);
end

procedure map_exit_p_proc
begin
    destroy_object(self_obj);
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        probability := random(0, 12);
        if ((probability >= 12) and not(critter_is_fleeing(self_obj))) then begin
            float_msg(self_obj, message_str(1715, random(400, 402)), 2);
        end
    end
    if (((map_var(0) bwand 1024) != 0) and (global_var(862) == 0)) then begin
        set_global_var(862, 1);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        dialogue_system_enter;
    end
end

procedure Node997
begin
    set_local_var(4, 1);
    set_global_var(864, 1);
    set_global_var(910, global_var(910) bwand (-1 - 65536));
end

procedure Node998
begin
    add_timer_event(Map_event, 0, 2);
    set_global_var(865, global_var(865) bwor 4096);
    set_global_var(910, global_var(910) bwand (-1 - 65536));
end

procedure Node999
begin
    set_global_var(882, 3);
    set_global_var(51, global_var(51) - 5);
    set_global_var(865, global_var(865) bwor 4096);
    set_global_var(910, global_var(910) bwand (-1 - 65536));
    add_timer_event(Map_event, 2, 3);
end

procedure Node500
begin
    if (((global_var(867) bwand 2097152) != 0) and ((global_var(867) bwand 512) != 0)) then begin
        gsay_reply(1715, 501);
    end
    else begin
        gsay_reply(1715, 500);
    end
    giq_option(4, 1715, 502, Node550, 50);
end

procedure Node550
begin
    if ((global_var(867) bwand 512) != 0) then begin
        gsay_reply(1715, 551);
    end
    else begin
        gsay_reply(1715, 550);
    end
    giq_option(4, 1715, 552, Node600, 50);
    giq_option(4, 1715, 553, Node997, 50);
end

procedure Node600
begin
    gsay_reply(1715, 600);
    if (has_skill(dude_obj, 14) > 95) then begin
        giq_option(4, 1715, 601, Node650, 50);
    end
    giq_option(4, 1715, 602, Node998, 50);
end

procedure Node650
begin
    gsay_reply(1715, 650);
    giq_option(4, 1715, 651, Node999, 50);
end

