variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node998_float402;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Sex_With_Tulsa;
procedure LEAVE_1ST_FLOOR;

variable sequence;
variable probability;
variable Condom_removed;
variable warning;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (cur_map_index == 24) then begin
        if ((local_var(4) == 1) or ((global_var(859) == 0) and not((global_var(904) bwand 4) != 0)) or (global_var(864) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
    else begin
        if ((local_var(4) == 1) or (global_var(864) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
    if (((global_var(865) bwand 67108864) != 0) and not((global_var(865) bwand 268435456) != 0) and obj_can_see_obj(self_obj, dude_obj) and (warning == 0)) then begin
        float_msg(self_obj, message_str(1708, 350), 2);
        add_timer_event(self_obj, 8, 4);
        warning := 1;
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(864, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    start_gdialog(1708, self_obj, 4, -1, -1);
    gsay_start;
    if (global_var(902) == 2) then begin
        set_local_var(6, local_var(6) bwor 16);
        call Node1850();
    end
    else begin
        if (local_var(5) == 1) then begin
            if ((get_critter_stat(dude_obj, 34) == 1) and ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) > 3) and has_trait(2, dude_obj, 13) and (((game_time - local_var(7)) > (60 * (60 * 10) * 24)) or (local_var(7) == 0))) then begin
                if ((local_var(6) bwand 4) == 0) then begin
                    call Node1600();
                end
                else begin
                    call Node1800();
                end
            end
            else begin
                if ((get_critter_stat(dude_obj, 34) == 0) or (get_critter_stat(dude_obj, 3) < 6)) then begin
                    call Node1200();
                end
                else begin
                    call Node1550();
                end
            end
        end
        else begin
            call Node500();
            set_local_var(5, 1);
        end
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(51, global_var(51) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + 0);
        debug_msg("Player gains " + 0 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(867, global_var(867) bwor 33554432);
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_msg(message_str(1708, 150));
    end
    else begin
        display_msg(message_str(1708, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_msg(message_str(1708, 250));
    end
    else begin
        display_msg(message_str(1708, 200));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(864, 1);
    end
    if ((global_var(864) == 1) and (get_critter_stat(self_obj, 35) < 15) and (get_critter_stat(self_obj, 35) > 1) and ((local_var(6) bwand 2) == 0)) then begin
        float_msg(self_obj, message_str(1708, 407), 2);
        set_local_var(6, local_var(6) bwor 2);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 258);
    critter_add_trait(self_obj, 1, 5, 3);
    if (cur_map_index == 24) then begin
        add_timer_event(self_obj, game_ticks(300), 3);
        if (((global_var(865) bwand 67108864) != 0) and not((global_var(865) bwand 268435456) != 0)) then begin
            move_to(self_obj, 13703, 0);
            anim(self_obj, 1000, 5);
        end
        if ((global_var(903) == 3) and not((global_var(865) bwand 67108864) != 0) and not((global_var(865) bwand 268435456) != 0)) then begin
            move_to(self_obj, 13503, 0);
            anim(self_obj, 1000, 0);
            add_timer_event(self_obj, game_ticks(1), 7);
        end
    end
    else begin
    end
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        if ((global_var(864) == 1) and obj_can_see_obj(self_obj, dude_obj) and ((local_var(6) bwand 1) == 0) and not((global_var(865) bwand 67108864) != 0)) then begin
            if (get_critter_stat(dude_obj, 34) == 0) then begin
                float_msg(self_obj, message_str(1708, 400), 2);
            end
            if (get_critter_stat(dude_obj, 34) == 1) then begin
                float_msg(self_obj, message_str(1708, 401), 2);
            end
            set_local_var(6, local_var(6) bwor 1);
        end
        probability := random(0, 12);
        if ((probability >= 12) and not(critter_is_fleeing(self_obj))) then begin
            if ((global_var(864) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
                float_msg(self_obj, message_str(1708, random(404, 406)), 2);
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (fixed_param == 1) then begin
            sequence := sequence + 1;
        end
        if (sequence == 1) then begin
            game_ui_disable;
            set_local_var(6, local_var(6) bwor 8);
            gfade_out(600);
            add_timer_event(self_obj, game_ticks(1), 1);
        end
        if (sequence == 2) then begin
            if (get_critter_stat(dude_obj, 34) == 1) then begin
                if ((obj_is_carrying_obj_pid(dude_obj, 314) > 0) and (Condom_removed == 0)) then begin
                    removed_qty := obj_is_carrying_obj_pid(dude_obj, 314);
                    if (1 < removed_qty) then begin
                        removed_qty := 1;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(dude_obj, 314);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(dude_obj, 314);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(dude_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(dude_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(dude_obj, restock_obj);
                                    add_obj_to_inven(dude_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(dude_obj, 2) == restock_obj) or (critter_inven_obj(dude_obj, 1) == restock_obj)) then begin
                                    metarule(43, dude_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
                        if (restock_amt == 0) then begin
                            toRemove_qty := 1;
                            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 314)) do begin
                                restock_obj := obj_carrying_pid_obj(dude_obj, 314);
                                rm_obj_from_inven(dude_obj, restock_obj);
                                destroy_object(restock_obj);
                                toRemove_qty := toRemove_qty - 1;
                            end
                        end
                        else begin
                            destroy_object(restock_obj);
                        end
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                    Condom_removed := 1;
                end
                if ((obj_is_carrying_obj_pid(dude_obj, 315) > 0) and (Condom_removed == 0)) then begin
                    removed_qty := obj_is_carrying_obj_pid(dude_obj, 315);
                    if (1 < removed_qty) then begin
                        removed_qty := 1;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(dude_obj, 315);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(dude_obj, 315);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(dude_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(dude_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(dude_obj, restock_obj);
                                    add_obj_to_inven(dude_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(dude_obj, 2) == restock_obj) or (critter_inven_obj(dude_obj, 1) == restock_obj)) then begin
                                    metarule(43, dude_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
                        if (restock_amt == 0) then begin
                            toRemove_qty := 1;
                            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 315)) do begin
                                restock_obj := obj_carrying_pid_obj(dude_obj, 315);
                                rm_obj_from_inven(dude_obj, restock_obj);
                                destroy_object(restock_obj);
                                toRemove_qty := toRemove_qty - 1;
                            end
                        end
                        else begin
                            destroy_object(restock_obj);
                        end
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                    Condom_removed := 1;
                end
                if ((obj_is_carrying_obj_pid(dude_obj, 316) > 0) and (Condom_removed == 0)) then begin
                    removed_qty := obj_is_carrying_obj_pid(dude_obj, 316);
                    if (1 < removed_qty) then begin
                        removed_qty := 1;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(dude_obj, 316);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(dude_obj, 316);
                            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(dude_obj, 0)) == 0) then begin
                                    restock_obj := critter_inven_obj(dude_obj, 0);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(dude_obj, restock_obj);
                                    add_obj_to_inven(dude_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(dude_obj, 2) == restock_obj) or (critter_inven_obj(dude_obj, 1) == restock_obj)) then begin
                                    metarule(43, dude_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
                        if (restock_amt == 0) then begin
                            toRemove_qty := 1;
                            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 316)) do begin
                                restock_obj := obj_carrying_pid_obj(dude_obj, 316);
                                rm_obj_from_inven(dude_obj, restock_obj);
                                destroy_object(restock_obj);
                                toRemove_qty := toRemove_qty - 1;
                            end
                        end
                        else begin
                            destroy_object(restock_obj);
                        end
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                    Condom_removed := 1;
                end
                Condom_removed := 0;
            end
            game_time_advance(get_critter_stat(dude_obj, 2) * random(4, 8) * (60 * 10));
            set_global_var(194, global_var(194) + (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) * 1));
            set_global_var(358, global_var(358) + 1);
            if ((global_var(713) >= 1) and (global_var(714) >= 1) and (global_var(715) >= 1)) then begin
                if (global_var(358) >= 16) then begin
                    if (get_critter_stat(dude_obj, 34) == 0) then begin
                        set_global_var(589, 1);
                    end
                    if (get_critter_stat(dude_obj, 34) == 1) then begin
                        set_global_var(588, 1);
                    end
                end
            end
            set_global_var(714, global_var(714) + 1);
            add_timer_event(self_obj, game_ticks(1), 1);
        end
        if (sequence == 3) then begin
            gfade_in(600);
            add_timer_event(self_obj, 5, 1);
        end
        if (sequence == 4) then begin
            sequence := 0;
            game_ui_enable;
            set_local_var(7, game_time);
            add_timer_event(self_obj, 2, 2);
        end
    end
    if (fixed_param == 2) then begin
        anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
        start_gdialog(1708, self_obj, 4, -1, -1);
        gsay_start;
        call Node1650();
        set_local_var(6, local_var(6) bwand (-1 - 8));
        gsay_end;
        end_dialogue;
    end
    if (fixed_param == 3) then begin
        if ((local_var(6) bwand 8) == 0) then begin
            float_msg(self_obj, message_str(1708, 300), 8);
        end
        add_timer_event(self_obj, game_ticks(300), 3);
    end
    if (fixed_param == 4) then begin
        call Node998();
    end
    if (fixed_param == 5) then begin
        if (fixed_param == 5) then begin
            sequence := sequence + 1;
        end
        if (sequence == 1) then begin
            game_ui_disable;
            add_timer_event(self_obj, 2, 5);
        end
        if (sequence == 2) then begin
            gfade_out(600);
            add_timer_event(self_obj, 5, 5);
        end
        if (sequence == 3) then begin
            set_obj_visibility(self_obj, 1);
            add_timer_event(self_obj, game_ticks(1), 5);
        end
        if (sequence == 4) then begin
            gfade_in(600);
            add_timer_event(self_obj, 5, 5);
        end
        if (sequence == 5) then begin
            game_ui_enable;
            sequence := 0;
            destroy_object(self_obj);
        end
    end
    if ((fixed_param == 6) and ((local_var(6) bwand 16) == 0) and not(combat_is_initialized)) then begin
        dialogue_system_enter;
    end
    if (fixed_param == 7) then begin
        game_ui_disable;
        float_msg(self_obj, message_str(1708, 5000), 2);
        add_timer_event(self_obj, game_ticks(6), 8);
    end
    if (fixed_param == 8) then begin
        float_msg(self_obj, message_str(1708, 5001 + (get_critter_stat(dude_obj, 34) == 1)), 2);
        anim(self_obj, 1000, 5);
        set_local_var(6, local_var(6) bwor 1);
        add_timer_event(self_obj, game_ticks(1), 9);
    end
    if (fixed_param == 9) then begin
        game_ui_enable;
        set_global_var(864, 1);
        set_global_var(866, global_var(866) bwor 1073741824);
    end
end

procedure Node998
begin
    set_local_var(4, 1);
    set_global_var(864, 1);
end

procedure Node998_float402
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        float_msg(self_obj, message_str(1708, 402), 2);
    end
    else begin
        float_msg(self_obj, message_str(1708, 403), 2);
    end
    set_local_var(4, 1);
    set_global_var(864, 1);
end

procedure Node999
begin
    anim(self_obj, 1000, 0);
end

procedure Node500
begin
    gsay_reply(1708, 500);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1708, 501, Node550, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1708, 501, Node800, 50);
    end
    giq_option(-3, 1708, 502, Node2100, 50);
end

procedure Node550
begin
    if ((global_var(865) bwand 2097152) != 0) then begin
        gsay_reply(1708, 551);
    end
    else begin
        gsay_reply(1708, 550);
    end
    giq_option(4, 1708, 552, Node600, 50);
end

procedure Node600
begin
    gsay_reply(1708, 600);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1708, 601, Node650, 50);
    end
    else begin
        giq_option(4, 1708, 601, Node850, 50);
    end
end

procedure Node650
begin
    gsay_reply(1708, 650);
    giq_option(4, 1708, 651, Node700, 50);
    giq_option(4, 1708, 652, Node750, 50);
end

procedure Node700
begin
    gsay_reply(1708, 700);
    set_map_var(0, map_var(0) bwor 1);
    if (not((global_var(865) bwand 1048576) != 0)) then begin
        giq_option(4, 1708, 701, Node900, 50);
    end
    giq_option(4, 1708, 702, Node1000, 50);
    giq_option(4, 1708, 703, Node1250, 50);
    giq_option(4, 1708, 704, Node999, 50);
end

procedure Node750
begin
    gsay_reply(1708, 750);
    giq_option(4, 1708, 751, Node998_float402, 50);
end

procedure Node800
begin
    if ((global_var(865) bwand 2097152) != 0) then begin
        gsay_reply(1708, 801);
    end
    else begin
        gsay_reply(1708, 800);
    end
    giq_option(4, 1708, 802, Node600, 50);
end

procedure Node850
begin
    gsay_reply(1708, 850);
    giq_option(4, 1708, 851, Node700, 50);
    giq_option(4, 1708, 852, Node750, 50);
end

procedure Node900
begin
    gsay_reply(1708, 900);
    if (not((global_var(865) bwand 1048576) != 0)) then begin
        set_global_var(865, global_var(865) bwor 1048576);
    end
    giq_option(4, 1708, 901, Node950, 50);
end

procedure Node950
begin
    gsay_reply(1708, 950);
    giq_option(4, 1708, 951, Node1000, 50);
    giq_option(4, 1708, 952, Node1250, 50);
    giq_option(4, 1708, 953, Node999, 50);
end

procedure Node1000
begin
    gsay_reply(1708, 1000);
    giq_option(4, 1708, 1001, Node1050, 50);
end

procedure Node1050
begin
    gsay_reply(1708, 1050);
    giq_option(4, 1708, 1051, Node1100, 50);
end

procedure Node1100
begin
    gsay_reply(1708, 1100);
    giq_option(6, 1708, 1101, Node1150, 50);
    if (not((global_var(865) bwand 1048576) != 0)) then begin
        giq_option(4, 1708, 1102, Node900, 50);
    end
    giq_option(4, 1708, 1103, Node1250, 50);
    giq_option(4, 1708, 1104, Node999, 50);
end

procedure Node1150
begin
    gsay_reply(1708, 1150);
    if (not((global_var(865) bwand 1048576) != 0)) then begin
        giq_option(4, 1708, 1151, Node900, 50);
    end
    giq_option(4, 1708, 1152, Node1250, 50);
    giq_option(4, 1708, 1153, Node999, 50);
end

procedure Node1200
begin
    gsay_reply(1708, 1200);
    giq_option(4, 1708, 1201, Node1300, 50);
    giq_option(4, 1708, 1202, Node1350, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1203, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1203, Node1400, 50);
    end
    giq_option(6, 1708, 1204, Node1500, 50);
    giq_option(4, 1708, 1205, Node999, 50);
    giq_option(-3, 1708, 1206, Node999, 50);
end

procedure Node1250
begin
    gsay_reply(1708, 1250);
    giq_option(4, 1708, 1251, Node1300, 50);
    giq_option(4, 1708, 1252, Node1350, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1253, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1253, Node1400, 50);
    end
    giq_option(6, 1708, 1254, Node1500, 50);
    giq_option(4, 1708, 1255, Node999, 50);
end

procedure Node1300
begin
    gsay_reply(1708, 1300);
    if (not((global_var(865) bwand 1048576) != 0)) then begin
        giq_option(4, 1708, 1301, Node900, 50);
    end
    giq_option(4, 1708, 1302, Node1000, 50);
    giq_option(4, 1708, 1303, Node1250, 50);
    giq_option(4, 1708, 1304, Node999, 50);
end

procedure Node1350
begin
    gsay_reply(1708, 1350);
    giq_option(4, 1708, 1351, Node1300, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1352, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1352, Node1400, 50);
    end
    giq_option(6, 1708, 1353, Node1500, 50);
    giq_option(4, 1708, 1354, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(1708, 1400);
    giq_option(4, 1708, 1401, Node1300, 50);
    giq_option(4, 1708, 1402, Node1350, 50);
    giq_option(6, 1708, 1403, Node1500, 50);
    giq_option(4, 1708, 1404, Node999, 50);
end

procedure Node1450
begin
    gsay_reply(1708, 1450);
    giq_option(4, 1708, 1451, Node1300, 50);
    giq_option(4, 1708, 1452, Node1350, 50);
    giq_option(6, 1708, 1453, Node1500, 50);
    giq_option(4, 1708, 1454, Node999, 50);
end

procedure Node1500
begin
    gsay_reply(1708, 1500);
    giq_option(4, 1708, 1501, Node1300, 50);
    giq_option(4, 1708, 1502, Node1350, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1503, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1503, Node1400, 50);
    end
    giq_option(4, 1708, 1504, Node999, 50);
end

procedure Node1550
begin
    gsay_reply(1708, 1550);
    giq_option(4, 1708, 1551, Node1300, 50);
    giq_option(4, 1708, 1552, Node1350, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1553, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1553, Node1400, 50);
    end
    giq_option(6, 1708, 1554, Node1500, 50);
    giq_option(4, 1708, 1555, Node999, 50);
    giq_option(-3, 1708, 1556, Node999, 50);
end

procedure Node1600
begin
    gsay_reply(1708, 1600);
    set_local_var(6, local_var(6) bwor 4);
    giq_option(4, 1708, 1601, Sex_With_Tulsa, 50);
    giq_option(4, 1708, 1602, Node1700, 50);
end

procedure Node1650
begin
    if (has_trait(0, dude_obj, 94)) then begin
        gsay_reply(1708, 1656);
    end
    else begin
        gsay_reply(1708, 1650);
    end
    giq_option(4, 1708, 1651, Node1300, 50);
    giq_option(4, 1708, 1652, Node1350, 50);
    if ((global_var(867) bwand 1) != 0) then begin
        giq_option(4, 1708, 1653, Node1450, 50);
    end
    else begin
        giq_option(4, 1708, 1653, Node1400, 50);
    end
    giq_option(6, 1708, 1654, Node1500, 50);
    giq_option(4, 1708, 1655, Node999, 50);
end

procedure Node1700
begin
    gsay_reply(1708, 1700);
    giq_option(4, 1708, 1701, Node1750, 50);
    giq_option(4, 1708, 1702, Node750, 50);
end

procedure Node1750
begin
    gsay_reply(1708, 1750);
    giq_option(4, 1708, 1751, Sex_With_Tulsa, 50);
end

procedure Node1800
begin
    gsay_reply(1708, 1800);
    giq_option(4, 1708, 1801, Sex_With_Tulsa, 50);
    giq_option(4, 1708, 1802, Node1700, 50);
end

procedure Node1850
begin
    gsay_reply(1708, 1850);
    if ((global_var(904) bwand 1) != 0) then begin
        giq_option(4, 1708, 1851, Node1900, 50);
    end
    else begin
        giq_option(4, 1708, 1852, Node1900, 50);
    end
end

procedure Node1900
begin
    gsay_reply(1708, 1900);
    giq_option(4, 1708, 1901, Node1950, 50);
end

procedure Node1950
begin
    gsay_reply(1708, 1950);
    if ((global_var(904) bwand 1) != 0) then begin
        giq_option(4, 1708, 1951, Node2050, 50);
    end
    else begin
        giq_option(4, 1708, 1952, Node2050, 50);
    end
    giq_option(4, 1708, 1953, Node2000, 50);
end

procedure Node2000
begin
    gsay_reply(1708, 2000);
    if ((global_var(904) bwand 1) != 0) then begin
        giq_option(4, 1708, 2001, Node2050, 50);
    end
    else begin
        giq_option(4, 1708, 2002, Node2050, 50);
    end
end

procedure Node2050
begin
    gsay_reply(1708, 2050);
    giq_option(4, 1708, 2051, LEAVE_1ST_FLOOR, 50);
end

procedure Node2100
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1708, 2100);
    end
    else begin
        gsay_reply(1708, 2101);
    end
    giq_option(4, 1708, 2102, Node998, 50);
end

procedure Sex_With_Tulsa
begin
    add_timer_event(self_obj, 2, 1);
end

procedure LEAVE_1ST_FLOOR
begin
    set_global_var(902, 3);
    add_timer_event(self_obj, 2, 5);
end

