variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure use_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;

variable removable_screen;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure use_p_proc
begin
    script_overrides;
    if (combat_is_initialized) then begin
        display_msg(message_str(112, 300));
    end
    else begin
        if ((get_critter_stat(dude_obj, 6) > 9) and (local_var(5) != 1)) then begin
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(112, self_obj, 4, -1, -1);
            gsay_start;
            call Node500();
            set_local_var(5, 1);
            gsay_end;
            end_dialogue;
        end
    end
end

procedure description_p_proc
begin
    if (local_var(5) == 1) then begin
        script_overrides;
        display_msg(message_str(112, 950));
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 12) then begin
        call use_p_proc();
    end
end

procedure damage_p_proc
begin
end

procedure map_enter_p_proc
begin
    if ((get_critter_stat(dude_obj, 6) > 9) and not((map_var(0) bwand 64) != 0)) then begin
        create_object_sid(33554478, 14493, 0, -1);
        set_map_var(0, map_var(0) bwor 64);
    end
end

procedure Node999
begin
    removable_screen := tile_contains_pid_obj(14493, 0, 33554478);
    destroy_object(removable_screen);
    removable_screen := tile_contains_pid_obj(14493, 0, 33554479);
    destroy_object(removable_screen);
    removable_screen := tile_contains_pid_obj(14493, 0, 33554480);
    destroy_object(removable_screen);
end

procedure Node500
begin
    gsay_reply(112, 500);
    giq_option(4, 112, 501, Node550, 50);
    giq_option(-3, 112, 502, Node550, 50);
end

procedure Node550
begin
    gsay_reply(112, 550);
    giq_option(1, 112, 551, Node600, 50);
end

procedure Node600
begin
    gsay_reply(112, 600);
    giq_option(1, 112, 601, Node650, 50);
end

procedure Node650
begin
    gsay_reply(112, 650);
    giq_option(1, 112, 651, Node700, 50);
end

procedure Node700
begin
    gsay_reply(112, 700);
    giq_option(1, 112, 701, Node750, 50);
end

procedure Node750
begin
    gsay_reply(112, 750);
    giq_option(1, 112, 751, Node800, 50);
end

procedure Node800
begin
    gsay_reply(112, 800);
    giq_option(1, 112, 801, Node850, 50);
end

procedure Node850
begin
    gsay_reply(112, 850);
    giq_option(1, 112, 851, Node900, 50);
end

procedure Node900
begin
    gsay_reply(112, 900);
    set_map_var(0, map_var(0) bwor 32);
    giq_option(4, 112, 901, Node999, 50);
    giq_option(-3, 112, 902, Node999, 50);
end

