variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure combat_p_proc;
procedure Node998;

import variable Vex_Guard;

variable Projed_smycku;
variable probability;
variable DO_FLOAT_PST := 9;
variable pojistka;
variable counter;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) or (global_var(861) == 1) and (has_trait(1, self_obj, 666) == 1) and (obj_can_see_obj(self_obj, dude_obj) or (tile_distance(tile_num(self_obj), tile_num(dude_obj)) < 5))) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    if ((global_var(861) == 1) and (has_trait(1, self_obj, 666) == 1) and (elevation(self_obj) == 2) and (elevation(dude_obj) == 2)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    if (((map_var(0) bwand 64) != 0) and (elevation(dude_obj) != 2)) then begin
        set_map_var(0, map_var(0) bwand (-1 - 64));
    end
    if ((elevation(dude_obj) == 2) and (elevation(self_obj) == 2) and (global_var(724) == 0) and (has_trait(1, self_obj, 666) == 1) and obj_can_see_obj(self_obj, dude_obj) and not((map_var(0) bwand 64) != 0)) then begin
        call Node998();
    end
    if (((map_var(0) bwand 64) != 0) and (elevation(dude_obj) == 2) and (has_trait(1, self_obj, 666) == 1) and tile_in_tile_rect(14113, 14105, 15513, 15505, tile_num(self_obj))) then begin
        set_obj_visibility(self_obj, 1);
    end
    if (not((map_var(0) bwand 64) != 0) and (has_trait(1, self_obj, 666) == 0)) then begin
        set_obj_visibility(self_obj, 0);
    end
    if ((global_var(871) == 2) and ((map_var(0) bwand 131072) != 0) and (elevation(self_obj) == 0) and (local_var(5) == 13720) and (global_var(860) == 0) and not((map_var(0) bwand 262144) != 0) and not(combat_is_initialized)) then begin
        if ((map_var(0) bwand 524288) != 0) then begin
            anim(self_obj, 1000, 1);
        end
        if ((map_var(0) bwand 1048576) != 0) then begin
            anim(self_obj, 1000, 2);
        end
        if ((map_var(0) bwand 2097152) != 0) then begin
            anim(self_obj, 1000, 3);
        end
        if (not(obj_is_carrying_obj_pid(self_obj, 18))) then begin
            restock_obj := create_object_sid(18, 0, 0, -1);
        end
        add_mult_objs_to_inven(self_obj, restock_obj, 1);
        wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 18));
        add_timer_event(self_obj, game_ticks(1), 5);
        set_map_var(0, map_var(0) bwor 262144);
    end
    if ((global_var(871) == 2) and ((map_var(0) bwand 131072) != 0) and (elevation(self_obj) == 0) and (local_var(5) == 13727) and (global_var(860) == 0) and not((map_var(0) bwand 4194304) != 0) and not(combat_is_initialized)) then begin
        if ((map_var(0) bwand 524288) != 0) then begin
            anim(self_obj, 1000, 1);
        end
        if ((map_var(0) bwand 1048576) != 0) then begin
            anim(self_obj, 1000, 1);
        end
        if ((map_var(0) bwand 2097152) != 0) then begin
            anim(self_obj, 1000, 2);
        end
        if (not(obj_is_carrying_obj_pid(self_obj, 18))) then begin
            restock_obj := create_object_sid(18, 0, 0, -1);
        end
        add_mult_objs_to_inven(self_obj, restock_obj, 1);
        add_timer_event(self_obj, 6, 6);
        set_map_var(0, map_var(0) bwor 4194304);
    end
    if ((local_var(5) == 12117) and ((map_var(0) bwand 33554432) != 0)) then begin
        restock_obj := create_object_sid(90, 0, 0, -1);
        add_mult_objs_to_inven(self_obj, restock_obj, 1);
        set_map_var(0, map_var(0) bwand (-1 - 33554432));
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
    end
end

procedure talk_p_proc
begin
    if (((global_var(867) bwand 16) != 0) and (Projed_smycku == 0)) then begin
        probability := random(0, 3);
        if (probability == 0) then begin
            if (get_critter_stat(dude_obj, 34) == 0) then begin
                float_msg(self_obj, message_str(1672, 300), 8);
            end
            if (get_critter_stat(dude_obj, 34) == 1) then begin
                float_msg(self_obj, message_str(1672, 311), 8);
            end
        end
        else begin
            if (probability == 1) then begin
                float_msg(self_obj, message_str(1672, 301), 8);
            end
            else begin
                if (probability == 2) then begin
                    float_msg(self_obj, message_str(1672, random(305, 306)), 8);
                end
                else begin
                    if (probability == 3) then begin
                        float_msg(self_obj, message_str(1672, random(308, 309)), 8);
                    end
                end
            end
        end
        Projed_smycku := 1;
    end
    if (Projed_smycku == 0) then begin
        while (Projed_smycku == 0) do begin
            probability := random(0, 12);
            if ((party_member_obj(16777812) != 0) and (probability >= DO_FLOAT_PST) and (Projed_smycku == 0)) then begin
                if (get_critter_stat(dude_obj, 34) == 0) then begin
                    float_msg(self_obj, message_str(1672, random(321, 322)), 8);
                end
                if (get_critter_stat(dude_obj, 34) == 1) then begin
                    float_msg(self_obj, message_str(1672, random(322, 323)), 8);
                end
                Projed_smycku := 1;
            end
            probability := random(0, 12);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(859) == 1)) then begin
                float_msg(self_obj, message_str(1672, random(313, 314)), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(724) == 11)) then begin
                float_msg(self_obj, message_str(1672, 318), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 11);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(886) == 1)) then begin
                float_msg(self_obj, message_str(1672, random(319, 320)), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(867) bwand 1) != 0)) then begin
                float_msg(self_obj, message_str(1672, 317), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(878) >= 3)) then begin
                float_msg(self_obj, message_str(1672, 315), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(871) == 3)) then begin
                float_msg(self_obj, message_str(1672, 316), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(859) == 0)) then begin
                float_msg(self_obj, message_str(1672, 312), 8);
                Projed_smycku := 1;
            end
            pojistka := pojistka + 1;
            probability := random(0, 12);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) or (pojistka > 4)) then begin
                if (get_critter_stat(dude_obj, 34) == 0) then begin
                    float_msg(self_obj, message_str(1672, random(300, 310)), 8);
                end
                if (get_critter_stat(dude_obj, 34) == 1) then begin
                    float_msg(self_obj, message_str(1672, random(301, 311)), 8);
                end
                pojistka := 0;
                Projed_smycku := 1;
            end
        end
    end
    Projed_smycku := 0;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(4, global_var(4) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(51, global_var(51) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        set_global_var(0, global_var(0) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(51, global_var(51) + 2);
        debug_msg("Added " + 2 + " to Town Rep");
    end
    set_map_var(5, map_var(5) + 1);
    if (local_var(5) == 11524) then begin
        set_global_var(867, global_var(867) bwor 1024);
    end
    if (local_var(5) == 11704) then begin
        set_global_var(867, global_var(867) bwor 2048);
    end
    if (local_var(5) == 12702) then begin
        set_global_var(867, global_var(867) bwor 4096);
    end
    if (local_var(5) == 12506) then begin
        set_global_var(867, global_var(867) bwor 8192);
    end
    if ((local_var(5) == 16708) and (elevation(self_obj) == 2) and (local_var(6) == 0) and (map_var(6) != 2)) then begin
        set_map_var(6, 1);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (get_critter_stat(self_obj, 34) == 0) then begin
        display_msg(message_str(1672, 100));
    end
    else begin
        display_msg(message_str(1672, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (get_critter_stat(self_obj, 34) == 0) then begin
        display_msg(message_str(1672, 200));
    end
    else begin
        display_msg(message_str(1672, 201));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(861, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 257);
    critter_add_trait(self_obj, 1, 5, 13);
    if ((global_var(1059) > 0) and not((global_var(867) bwand 16) != 0) and ((global_var(1059) == get_day) and (game_time_hour >= 131) or (global_var(1059) < get_day))) then begin
        set_global_var(861, 1);
    end
    if (global_var(878) == 1) then begin
        set_local_var(4, 0);
    end
    if (local_var(5) == 0) then begin
        set_local_var(5, tile_num(self_obj));
    end
    if ((local_var(5) == 11524) and ((global_var(867) bwand 1024) != 0)) then begin
        destroy_object(self_obj);
    end
    if ((local_var(5) == 11704) and ((global_var(867) bwand 2048) != 0)) then begin
        destroy_object(self_obj);
    end
    if ((local_var(5) == 12702) and ((global_var(867) bwand 4096) != 0)) then begin
        destroy_object(self_obj);
    end
    if ((local_var(5) == 12506) and ((global_var(867) bwand 8192) != 0)) then begin
        destroy_object(self_obj);
    end
    if (tile_num(self_obj) == 12512) then begin
        Vex_Guard := self_obj;
    end
    if ((local_var(5) == 13720) and (tile_num(self_obj) == 13720) and (global_var(861) == 0) and (has_trait(1, self_obj, 10) != 2)) then begin
        anim(self_obj, 1000, 2);
    end
    if ((local_var(5) == 13727) and (tile_num(self_obj) == 13727) and (global_var(861) == 0) and (has_trait(1, self_obj, 10) != 2)) then begin
        anim(self_obj, 1000, 2);
    end
    if ((global_var(724) >= 8) and (global_var(724) <= 10) or ((global_var(723) >= 4) and (global_var(723) <= 6))) then begin
        if ((local_var(5) == 16708) and (elevation(self_obj) == 2) and (local_var(6) == 0)) then begin
            add_timer_event(self_obj, 0, 8);
        end
    end
    if ((global_var(861) == 0) and (map_var(7) != 0) and ((((2 * (60 * (60 * 10))) + map_var(7)) <= game_time) or (global_var(870) == 2))) then begin
        set_map_var(7, 0);
        set_global_var(861, 1);
        if ((local_var(5) == 13720) or (local_var(5) == 13727)) then begin
            destroy_object(self_obj);
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (counter > 2) then begin
            set_global_var(861, 1);
        end
        float_msg(self_obj, message_str(1672, random(330, 333)), 2);
        counter := counter + 1;
    end
    if (fixed_param == 2) then begin
        float_msg(self_obj, message_str(1672, 334), 8);
    end
    if (fixed_param == 5) then begin
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 45, -1);
        reg_anim_func(3, 0);
        play_sfx("whg1sxx1");
    end
    if (fixed_param == 6) then begin
        wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 18));
        add_timer_event(self_obj, game_ticks(1), 7);
    end
    if (fixed_param == 7) then begin
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 45, -1);
        reg_anim_func(3, 0);
        play_sfx("whg1sxx1");
    end
    if (fixed_param == 8) then begin
        if (local_var(6) == 0) then begin
            set_local_var(6, 1);
            restock_obj := create_object_sid(298, 0, 0, -1);
            add_mult_objs_to_inven(self_obj, restock_obj, 1);
        end
    end
end

procedure combat_p_proc
begin
end

procedure Node998
begin
    while ((Projed_smycku == 0) and not((map_var(0) bwand 32) != 0)) do begin
        probability := random(0, 10);
        if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
            if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(self_obj, 34) == 0)) then begin
                float_msg(self_obj, message_str(1672, 351), 2);
            end
            if ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(self_obj, 34) == 0)) then begin
                float_msg(self_obj, message_str(1672, 352), 2);
            end
            if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(self_obj, 34) == 1)) then begin
                float_msg(self_obj, message_str(1672, 353), 2);
            end
            if ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(self_obj, 34) == 1)) then begin
                float_msg(self_obj, message_str(1672, 354), 2);
            end
            set_map_var(0, map_var(0) bwor 32);
            Projed_smycku := 1;
        end
        probability := random(0, 10);
        if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
            float_msg(self_obj, message_str(1672, 355), 2);
            set_map_var(0, map_var(0) bwor 32);
            Projed_smycku := 1;
        end
        probability := random(0, 10);
        if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
            if (get_critter_stat(dude_obj, 34) == 0) then begin
                float_msg(self_obj, message_str(1672, 356), 2);
            end
            if (get_critter_stat(dude_obj, 34) == 1) then begin
                float_msg(self_obj, message_str(1672, 357), 2);
            end
            set_map_var(0, map_var(0) bwor 32);
            Projed_smycku := 1;
        end
        pojistka := pojistka + 1;
        probability := random(0, 11);
        if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) or (pojistka > 4)) then begin
            float_msg(self_obj, message_str(1672, 350), 2);
            pojistka := 0;
            Projed_smycku := 1;
            set_map_var(0, map_var(0) bwor 32);
        end
    end
    Projed_smycku := 0;
    set_local_var(4, 1);
    set_global_var(861, 1);
end

