variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);

variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure timed_event_p_proc;

variable Projed_smycku;
variable probability;
variable DO_FLOAT_PST := 9;
variable pojistka;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) or (global_var(824) == 1) or (global_var(853) == 1) or (global_var(851) == 1) or (global_var(850) == 1) or ((global_var(842) bwand 8192) != 0) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            float_msg(self_obj, message_str(1571, 400), 2);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            float_msg(self_obj, message_str(1571, 401), 2);
        end
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    if (local_var(5) == 1) then begin
        if ((game_time_hour < 800) or (2000 < game_time_hour) and (tile_num(self_obj) != 19749) and (art_anim(obj_art_fid(self_obj)) != 1)) then begin
            animate_move_obj_to_tile(self_obj, 19749, 0);
        end
        if ((game_time_hour < 800) or (2000 < game_time_hour) and (tile_num(self_obj) == 19749) and has_trait(1, self_obj, 666)) then begin
            set_obj_visibility(self_obj, 1);
        end
        if ((game_time_hour >= 800) and (2000 >= game_time_hour) and (tile_num(self_obj) != 21117) and (art_anim(obj_art_fid(self_obj)) != 1)) then begin
            if (not(has_trait(1, self_obj, 666))) then begin
                set_obj_visibility(self_obj, 0);
            end
            animate_move_obj_to_tile(self_obj, 21117, 0);
        end
        if ((game_time_hour >= 800) and (2000 >= game_time_hour) and (tile_num(self_obj) == 21117) and (has_trait(1, self_obj, 10) != 1)) then begin
            anim(self_obj, 1000, 1);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(824, 1);
        float_msg(self_obj, message_str(1571, 403), 2);
    end
end

procedure talk_p_proc
begin
    if (Projed_smycku == 0) then begin
        while (Projed_smycku == 0) do begin
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= (DO_FLOAT_PST - 2)) and (party_member_obj(16777812) != 0)) then begin
                float_msg(self_obj, message_str(1571, 312), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= (DO_FLOAT_PST - 2)) and (party_member_obj(16777812) != 0)) then begin
                float_msg(self_obj, message_str(1571, 311), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(841) == 3)) then begin
                float_msg(self_obj, message_str(1571, 310), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(842) bwand 131072) != 0)) then begin
                float_msg(self_obj, message_str(1571, 309), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(848) == 1)) then begin
                float_msg(self_obj, message_str(1571, 308), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(825) != 3) and (global_var(827) != 3) and not((global_var(843) bwand 1024) != 0) and not((global_var(842) bwand 65536) != 0)) then begin
                float_msg(self_obj, message_str(1571, 313), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(825) == 3)) then begin
                float_msg(self_obj, message_str(1571, 307), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(825) == 3)) then begin
                float_msg(self_obj, message_str(1571, 306), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, message_str(1571, 305), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, message_str(1571, 304), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(825) != 3) or ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0) and ((global_var(831) == 3) or (global_var(841) == 3))) or ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0) and ((global_var(835) == 3) or (global_var(841) == 2))))) then begin
                float_msg(self_obj, message_str(1571, 303), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(825) != 3) or ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0) and ((global_var(831) == 3) or (global_var(841) == 3))) or ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0) and ((global_var(835) == 3) or (global_var(841) == 2))))) then begin
                float_msg(self_obj, message_str(1571, 302), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, message_str(1571, 301), 8);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(825) != 3) or ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0) and ((global_var(831) == 3) or (global_var(841) == 3))) or ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0) and ((global_var(835) == 3) or (global_var(841) == 2))))) then begin
                float_msg(self_obj, message_str(1571, 300), 8);
                Projed_smycku := 1;
            end
            pojistka := pojistka + 1;
            if ((Projed_smycku == 0) and (pojistka > 4)) then begin
                float_msg(self_obj, message_str(1571, random(304, 305)), 8);
                pojistka := 0;
                Projed_smycku := 1;
            end
        end
    end
    Projed_smycku := 0;
end

procedure destroy_p_proc
begin
    if (cur_map_index != 17) then begin
        if (source_obj == dude_obj) then begin
            set_global_var(5, global_var(5) + 1);
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
                set_global_var(2, 1);
                set_global_var(3, 0);
            end
            if (metarule(51, self_obj) == 2) then begin
                if (source_obj == dude_obj) then begin
                    set_global_var(2, 0);
                    set_global_var(1, global_var(1) + 1);
                    set_global_var(0, global_var(0) + -15);
                    debug_msg("Player gains " + -15 + " Karma Points.");
                    set_global_var(37, 0);
                    set_global_var(38, 0);
                    set_global_var(39, 0);
                    set_global_var(40, 0);
                    set_global_var(41, 0);
                    set_global_var(42, 0);
                    set_global_var(43, 0);
                    set_global_var(44, 0);
                    set_global_var(45, 0);
                    if (global_var(0) >= 1000) then begin
                        set_global_var(37, 1);
                    end
                    else begin
                        if (global_var(0) >= 750) then begin
                            set_global_var(38, 1);
                        end
                        else begin
                            if (global_var(0) >= 500) then begin
                                set_global_var(39, 1);
                            end
                            else begin
                                if (global_var(0) >= 250) then begin
                                    set_global_var(40, 1);
                                end
                                else begin
                                    if (global_var(0) > -250) then begin
                                        set_global_var(41, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -500) then begin
                                            set_global_var(42, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -750) then begin
                                                set_global_var(43, 1);
                                            end
                                            else begin
                                                if (global_var(0) > -1000) then begin
                                                    set_global_var(44, 1);
                                                end
                                                else begin
                                                    set_global_var(45, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    set_global_var(50, global_var(50) + -8);
                    debug_msg("Added " + -8 + " to Town Rep");
                end
            end
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
                set_global_var(3, 1);
                set_global_var(2, 0);
            end
            set_global_var(0, global_var(0) + -10);
            debug_msg("Player gains " + -10 + " Karma Points.");
            set_global_var(37, 0);
            set_global_var(38, 0);
            set_global_var(39, 0);
            set_global_var(40, 0);
            set_global_var(41, 0);
            set_global_var(42, 0);
            set_global_var(43, 0);
            set_global_var(44, 0);
            set_global_var(45, 0);
            if (global_var(0) >= 1000) then begin
                set_global_var(37, 1);
            end
            else begin
                if (global_var(0) >= 750) then begin
                    set_global_var(38, 1);
                end
                else begin
                    if (global_var(0) >= 500) then begin
                        set_global_var(39, 1);
                    end
                    else begin
                        if (global_var(0) >= 250) then begin
                            set_global_var(40, 1);
                        end
                        else begin
                            if (global_var(0) > -250) then begin
                                set_global_var(41, 1);
                            end
                            else begin
                                if (global_var(0) > -500) then begin
                                    set_global_var(42, 1);
                                end
                                else begin
                                    if (global_var(0) > -750) then begin
                                        set_global_var(43, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -1000) then begin
                                            set_global_var(44, 1);
                                        end
                                        else begin
                                            set_global_var(45, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            set_global_var(50, global_var(50) + -5);
            debug_msg("Added " + -5 + " to Town Rep");
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (get_critter_stat(self_obj, 34) == 0) then begin
        display_msg(message_str(1571, 100));
    end
    else begin
        display_msg(message_str(1571, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (get_critter_stat(self_obj, 34) == 0) then begin
        display_msg(message_str(1571, 200));
    end
    else begin
        display_msg(message_str(1571, 201));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(824, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 254);
    critter_add_trait(self_obj, 1, 5, 22);
    if (metarule(14, 0) and (cur_map_index == 16)) then begin
        if (tile_num(self_obj) == 21117) then begin
            set_local_var(5, 1);
        end
    end
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        probability := random(0, 10);
        if ((probability >= 10) and not(critter_is_fleeing(self_obj))) then begin
            if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
                float_msg(self_obj, message_str(1571, 402), 2);
            end
        end
    end
    if (global_var(853) == 1) then begin
        critter_add_trait(self_obj, 1, 6, 243);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 10) then begin
        float_msg(self_obj, message_str(1571, 403), 2);
        display_msg(message_str(1571, 450));
        set_local_var(4, 1);
        set_global_var(824, 1);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

