variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure combat_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Node2150;
procedure Node550_Bridge;
procedure Node900_Bridge;
procedure Node1200_Bridge;
procedure Node1200_Bridge2;
procedure GO_TO_RING;
procedure copy_items;

import variable Cedrick_obj;
import variable Strycek_obj;
import variable items_carrier;

variable Projed_Smycku;
variable probability;
variable count;
variable item_pid_number;
variable Gabriel_React;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Strycek_obj := self_obj;
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) or (global_var(824) == 1) or (global_var(851) == 1) or (global_var(837) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    if ((local_var(5) != 1) and tile_in_tile_rect(19504, 19490, 23904, 23890, tile_num(dude_obj)) and (tile_distance(tile_num(self_obj), tile_num(dude_obj)) < 6) and obj_can_see_obj(self_obj, dude_obj)) then begin
        call talk_p_proc();
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    start_gdialog(1555, self_obj, 4, -1, -1);
    gsay_start;
    if (local_var(5) != 1) then begin
        set_local_var(5, 1);
        call Node500();
        add_timer_event(Cedrick_obj, game_ticks(0), 5);
    end
    else begin
        if ((Projed_Smycku == 0) and (global_var(832) == 1) and ((global_var(843) bwand 4) != 0)) then begin
            call Node1450();
            Projed_Smycku := 1;
        end
        if ((Projed_Smycku == 0) and (global_var(832) == 1) and not((global_var(843) bwand 4) != 0)) then begin
            call Node1400();
            Projed_Smycku := 1;
        end
        if ((Projed_Smycku == 0) and ((local_var(6) bwand 8) != 0) and (global_var(832) < 2)) then begin
            call Node1350();
            Projed_Smycku := 1;
        end
        if ((Projed_Smycku == 0) and ((local_var(6) bwand 16) != 0)) then begin
            call Node1300();
            Projed_Smycku := 1;
        end
        if (Projed_Smycku == 0) then begin
            call Node1800();
            Projed_Smycku := 1;
        end
    end
    gsay_end;
    end_dialogue;
    Projed_Smycku := 0;
    if (global_var(849) == 3) then begin
        load_map("CORATH1.MAP", 0);
    end
    if ((global_var(830) == 4) and (global_var(834) != 0)) then begin
        set_global_var(834, 0);
    end
    if ((global_var(831) == 3) and (global_var(835) != 0)) then begin
        set_global_var(835, 0);
    end
    if ((global_var(832) == 2) and (global_var(836) != 0)) then begin
        set_global_var(836, 0);
    end
end

procedure destroy_p_proc
begin
    if (global_var(837) == 1) then begin
        set_global_var(50, global_var(50) - 10);
    end
    else begin
    end
    set_global_var(842, global_var(842) bwor 131072);
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_msg(message_str(1555, 150));
    end
    else begin
        display_msg(message_str(1555, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_msg(message_str(1555, 250));
    end
    else begin
        display_msg(message_str(1555, 200));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        if (not((global_var(842) bwand 1048576) != 0)) then begin
            set_global_var(851, 1);
        end
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 245);
    critter_add_trait(self_obj, 1, 5, 22);
    if ((global_var(842) bwand 131072) != 0) then begin
        destroy_object(self_obj);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        set_local_var(6, local_var(6) bwor 1);
    end
    if (fixed_param == 5) then begin
        float_msg(self_obj, message_str(1555, 402), 2);
    end
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        if ((local_var(4) == 1) or (global_var(837) == 1) and obj_can_see_obj(self_obj, dude_obj) and ((local_var(6) bwand 512) == 0)) then begin
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0) or ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) or ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) or (party_member_obj(16777813) != 0) or (party_member_obj(16777729) != 0) or (party_member_obj(16777812) != 0)) then begin
                float_msg(self_obj, message_str(1555, 402), 2);
            end
            else begin
                if (get_critter_stat(dude_obj, 34) == 0) then begin
                    float_msg(self_obj, message_str(1555, 400), 2);
                end
                if (get_critter_stat(dude_obj, 34) == 1) then begin
                    float_msg(self_obj, message_str(1555, 401), 2);
                end
            end
            set_local_var(6, local_var(6) bwor 512);
        end
        probability := random(0, 20);
        if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj) and (probability == 10) and not(critter_is_fleeing(self_obj))) then begin
            if ((global_var(837) == 1) or ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0) or ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) or ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) or (party_member_obj(16777813) != 0) or (party_member_obj(16777729) != 0) or (party_member_obj(16777812) != 0))) then begin
                float_msg(self_obj, message_str(1555, 404), 2);
            end
            else begin
                float_msg(self_obj, message_str(1555, 403), 2);
            end
        end
    end
end

procedure Node998
begin
    set_local_var(4, 1);
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0) or ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) or ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) or (party_member_obj(16777813) != 0) or (party_member_obj(16777729) != 0) or (party_member_obj(16777812) != 0)) then begin
        float_msg(self_obj, message_str(1555, 402), 2);
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            float_msg(self_obj, message_str(1555, 400), 2);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            float_msg(self_obj, message_str(1555, 401), 2);
        end
    end
    set_local_var(6, local_var(6) bwor 512);
end

procedure Node999
begin
    anim(self_obj, 1000, 2);
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0) and (Gabriel_React == 1)) then begin
        add_timer_event(party_member_obj(16777811), 10, 20);
    end
    Gabriel_React := 0;
end

procedure Node500
begin
    gsay_reply(1555, message_str(1555, 500) + obj_name(dude_obj) + message_str(1555, 501));
    giq_option(4, 1555, 502, Node550, 50);
    giq_option(4, 1555, 503, Node800, 50);
    if (global_var(832) == 0) then begin
        giq_option(4, 1555, 504, Node1200, 50);
    end
    else begin
        giq_option(4, 1555, 504, Node1750, 50);
    end
    giq_option(4, 1555, 505, Node1150, 50);
    if (((local_var(6) bwand 1) != 0) or ((global_var(842) bwand 67108864) != 0)) then begin
        giq_option(-3, 1555, 507, Node2000, 50);
    end
    else begin
        giq_option(-3, 1555, 506, Node1000, 50);
    end
end

procedure Node550
begin
    if ((get_critter_stat(dude_obj, 34) == 0) and ((global_var(841) == 3) or (global_var(831) == 3))) then begin
        gsay_reply(1555, 550);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and ((global_var(841) == 3) or (global_var(831) == 3))) then begin
        gsay_reply(1555, 551);
    end
    if ((get_critter_stat(dude_obj, 34) == 0) and ((global_var(841) == 2) or (global_var(835) >= 2))) then begin
        gsay_reply(1555, 552);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and ((global_var(841) == 2) or (global_var(835) >= 2))) then begin
        gsay_reply(1555, 553);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1555, 554, Node600, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1555, 555, Node600, 50);
    end
end

procedure Node600
begin
    if ((global_var(841) == 3) or (global_var(831) == 3)) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            gsay_reply(1555, 600);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            gsay_reply(1555, 601);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            gsay_reply(1555, 602);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            gsay_reply(1555, 603);
        end
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1555, 604, Node650, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1555, 605, Node650, 50);
    end
end

procedure Node650
begin
    gsay_reply(1555, 650);
    if ((local_var(6) bwand 2) == 0) then begin
        giq_option(4, 1555, 651, Node700, 50);
    end
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(4, 1555, 652, Node750, 50);
    end
    if (global_var(832) < 1) then begin
        giq_option(4, 1555, 653, Node900, 50);
    end
    giq_option(4, 1555, 654, Node850, 50);
end

procedure Node700
begin
    gsay_reply(1555, 700);
    set_local_var(6, local_var(6) bwor 2);
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(4, 1555, 701, Node750, 50);
    end
    if (global_var(832) < 1) then begin
        giq_option(4, 1555, 702, Node900, 50);
    end
    giq_option(4, 1555, 703, Node850, 50);
end

procedure Node750
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 750);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 751);
    end
    set_local_var(6, local_var(6) bwor 4);
    if ((local_var(6) bwand 2) == 0) then begin
        giq_option(4, 1555, 752, Node700, 50);
    end
    if (global_var(832) < 1) then begin
        giq_option(4, 1555, 753, Node900, 50);
    end
    giq_option(4, 1555, 754, Node850, 50);
end

procedure Node800
begin
    gsay_reply(1555, 800);
    giq_option(4, 1555, 801, Node550, 50);
end

procedure Node850
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 850);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 851);
    end
    set_local_var(6, local_var(6) bwor 8);
    giq_option(4, 1555, 852, Node999, 50);
end

procedure Node900
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 900);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 901);
    end
    set_global_var(832, 1);
    set_global_var(1015, global_var(1015) bwand (-1 - 4096));
    giq_option(4, 1555, 902, Node999, 50);
    giq_option(4, 1555, 903, Node950, 50);
end

procedure Node950
begin
    gsay_reply(1555, 950);
    if ((global_var(832) != 2) and ((local_var(6) bwand 32) == 0)) then begin
        giq_option(4, 1555, 951, Node1050, 50);
    end
    if ((global_var(832) == 2) and ((local_var(6) bwand 128) == 0)) then begin
        giq_option(4, 1555, 952, Node1650, 50);
    end
    if (((global_var(1027) bwand 1) != 0) and ((local_var(6) bwand 64) == 0)) then begin
        giq_option(4, 1555, 953, Node1100, 50);
    end
    giq_option(4, 1555, 954, Node999, 50);
end

procedure Node1000
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1000);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1001);
    end
    set_local_var(6, local_var(6) bwor 16);
    giq_option(-3, 1555, 1002, Node999, 50);
end

procedure Node1050
begin
    gsay_reply(1555, 1050);
    set_local_var(6, local_var(6) bwor 32);
    if (((global_var(1027) bwand 1) != 0) and ((local_var(6) bwand 64) == 0)) then begin
        giq_option(4, 1555, 1051, Node1100, 50);
    end
    giq_option(4, 1555, 1052, Node999, 50);
end

procedure Node1100
begin
    gsay_reply(1555, 1100);
    set_local_var(6, local_var(6) bwor 64);
    critter_mod_skill(dude_obj, 15, 3);
    display_msg(message_str(1555, 300));
    if ((global_var(832) != 2) and ((local_var(6) bwand 32) == 0)) then begin
        giq_option(4, 1555, 1101, Node1050, 50);
    end
    if ((global_var(832) == 2) and ((local_var(6) bwand 128) == 0)) then begin
        giq_option(4, 1555, 1102, Node1650, 50);
    end
    giq_option(4, 1555, 1103, Node999, 50);
end

procedure Node1150
begin
    gsay_reply(1555, 1150);
    giq_option(4, 1555, 1151, Node550, 50);
    if (global_var(832) == 0) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1152, Node1200, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1153, Node1200, 50);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1152, Node1750, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1153, Node1750, 50);
        end
    end
    giq_option(4, 1555, 1154, Node998, 50);
end

procedure Node1200
begin
    gsay_reply(1555, 1200);
    if ((global_var(836) == 1) and ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0)) and ((global_var(831) == 3) or (global_var(841) == 3)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1201, Node1250, 50);
    end
    if ((global_var(836) == 1) and ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0)) and ((global_var(835) == 3) or (global_var(841) == 2)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1202, Node1250, 50);
    end
    if ((global_var(836) == 1) and ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0)) and ((global_var(835) == 3) or (global_var(841) == 2)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1203, Node1250, 50);
    end
    giq_option(4, 1555, 1204, Node998, 50);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1555, 1205, Node550, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1555, 1206, Node550, 50);
    end
end

procedure Node1250
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1250);
    end
    else begin
        gsay_reply(1555, 1251);
    end
    giq_option(4, 1555, 1252, GO_TO_RING, 50);
end

procedure Node1300
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1300);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1301);
    end
    giq_option(4, 1555, 1302, Node550_Bridge, 50);
    if (global_var(832) == 0) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1303, Node1200_Bridge, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1304, Node1200_Bridge, 50);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1303, Node1750, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1304, Node1750, 50);
        end
    end
    giq_option(4, 1555, 1305, Node999, 50);
    giq_option(-3, 1555, 1306, Node999, 50);
end

procedure Node1350
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1350);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1351);
    end
    if (global_var(832) < 1) then begin
        giq_option(4, 1555, 1352, Node900_Bridge, 50);
    end
    if (global_var(832) == 0) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1353, Node1200_Bridge2, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1354, Node1200_Bridge2, 50);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1353, Node1750, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1354, Node1750, 50);
        end
    end
    giq_option(4, 1555, 1355, Node999, 50);
    giq_option(-3, 1555, 1356, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(1555, 1400);
    giq_option(4, 1555, 1401, Node950, 50);
    if (global_var(832) == 0) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1403, Node1200, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1404, Node1200, 50);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 1555, 1403, Node1750, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 1555, 1404, Node1750, 50);
        end
    end
    giq_option(4, 1555, 1402, Node999, 50);
    giq_option(-3, 1555, 1405, Node999, 50);
end

procedure Node1450
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1450);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1451);
    end
    set_global_var(832, 2);
    item_caps_adjust(dude_obj, 3000);
    give_exp_points(3000);
    display_msg(message_str(14, 100) + 3000 + message_str(14, 101));
    giq_option(4, 1555, 1452, Node1500, 50);
    giq_option(-3, 1555, 1453, Node1500, 50);
end

procedure Node1500
begin
    if ((global_var(831) == 3) and ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0))) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            gsay_reply(1555, 1500);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            gsay_reply(1555, 1501);
        end
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            gsay_reply(1555, 1502);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            gsay_reply(1555, 1503);
        end
    end
    giq_option(4, 1555, 1504, Node1550, 50);
    giq_option(4, 1555, 1505, Node1700, 50);
    giq_option(-3, 1555, 1506, Node1700, 50);
end

procedure Node1550
begin
    gsay_reply(1555, 1550);
    giq_option(4, 1555, 1551, Node1600, 50);
end

procedure Node1600
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1600);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1601);
    end
    set_global_var(833, 1);
    giq_option(4, 1555, 1602, Node999, 50);
    giq_option(4, 1555, 1603, Node950, 50);
end

procedure Node1650
begin
    gsay_reply(1555, 1650);
    set_local_var(6, local_var(6) bwor 128);
    giq_option(4, 1555, 1651, Node999, 50);
end

procedure Node1700
begin
    gsay_reply(1555, 1700);
    set_local_var(6, local_var(6) bwor 256);
    giq_option(4, 1555, 1701, Node999, 50);
    giq_option(-3, 1555, 1702, Node999, 50);
end

procedure Node1750
begin
    gsay_reply(1555, 1750);
    if ((global_var(836) == 1) and ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0)) and ((global_var(831) == 3) or (global_var(841) == 3)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1751, Node1250, 50);
    end
    if ((global_var(836) == 1) and ((global_var(834) == 5) or ((global_var(842) bwand 16384) != 0)) and ((global_var(835) == 3) or (global_var(841) == 2)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1752, Node1250, 50);
    end
    if ((global_var(836) == 1) and ((global_var(830) == 4) or ((global_var(842) bwand 1024) != 0)) and ((global_var(835) == 3) or (global_var(841) == 2)) and not((global_var(843) bwand 64) != 0)) then begin
        giq_option(4, 1555, 1753, Node1250, 50);
    end
    giq_option(4, 1555, 1754, Node998, 50);
    giq_option(4, 1555, 1755, Node999, 50);
end

procedure Node1800
begin
    gsay_reply(1555, 1800);
    if ((get_critter_stat(dude_obj, 34) == 0) and ((local_var(6) bwand 256) != 0) and (global_var(833) == 0)) then begin
        giq_option(4, 1555, 1801, Node1550, 50);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and ((local_var(6) bwand 256) != 0) and (global_var(833) == 0)) then begin
        giq_option(4, 1555, 1802, Node1550, 50);
    end
    if (global_var(833) == 2) then begin
        giq_option(4, 1555, 1803, Node1850, 50);
    end
    giq_option(4, 1555, 1804, Node950, 50);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1555, 1805, Node999, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1555, 1806, Node999, 50);
    end
    giq_option(-3, 1555, 1807, Node999, 50);
end

procedure Node1850
begin
    gsay_reply(1555, 1850);
    if ((global_var(833) == 2) and (obj_is_carrying_obj_pid(dude_obj, 429) >= 1)) then begin
        giq_option(4, 1555, 1851, Node1900, 50);
    end
    if ((global_var(833) == 2) and (obj_is_carrying_obj_pid(dude_obj, 429) == 0)) then begin
        giq_option(4, 1555, 1852, Node999, 50);
    end
end

procedure Node1900
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1900);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1901);
    end
    item_caps_adjust(dude_obj, 4000);
    give_exp_points(3500);
    display_msg(message_str(14, 100) + 3500 + message_str(14, 101));
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 429);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 429);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 429);
            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, 0)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, 0);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, 2) == restock_obj) or (critter_inven_obj(dude_obj, 1) == restock_obj)) then begin
                    metarule(43, dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 429)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 429);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    set_global_var(833, 3);
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        Gabriel_React := 1;
    end
    giq_option(4, 1555, 1902, Node1950, 50);
end

procedure Node1950
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 1950);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 1951);
    end
    giq_option(4, 1555, 1952, Node999, 50);
    giq_option(4, 1555, 1953, Node950, 50);
end

procedure Node2000
begin
    gsay_reply(1555, 2000);
    item_caps_adjust(dude_obj, 3000);
    give_exp_points(3000);
    display_msg(message_str(14, 100) + 3000 + message_str(14, 101));
    giq_option(-3, 1555, 2001, Node2050, 50);
end

procedure Node2050
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1555, 2050);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1555, 2051);
    end
    giq_option(-3, 1555, message_str(1555, 2052) + obj_name(dude_obj) + message_str(1555, 2053), Node2100, 50);
    giq_option(-3, 1555, 2054, Node2150, 50);
end

procedure Node2100
begin
    gsay_reply(1555, 2100);
    set_global_var(842, global_var(842) bwor 4096);
    set_global_var(833, 1);
    giq_option(-3, 1555, 2101, Node999, 50);
end

procedure Node2150
begin
    gsay_reply(1555, 2150);
    giq_option(-3, 1555, 2151, Node2100, 50);
end

procedure Node550_Bridge
begin
    set_local_var(6, local_var(6) bwand (-1 - 16));
    call Node550();
end

procedure Node900_Bridge
begin
    set_local_var(6, local_var(6) bwor 8);
    call Node900();
end

procedure Node1200_Bridge
begin
    set_local_var(6, local_var(6) bwand (-1 - 16));
    call Node1200();
end

procedure Node1200_Bridge2
begin
    set_local_var(6, local_var(6) bwor 8);
    call Node1200();
end

procedure GO_TO_RING
begin
    set_global_var(849, 3);
    call copy_items();
    call Node999();
end

procedure copy_items
begin
    while (item_pid_number < 560) do begin
        item_pid_number := item_pid_number + 1;
        if (obj_is_carrying_obj_pid(Cedrick_obj, item_pid_number)) then begin
            if (obj_is_carrying_obj_pid(Cedrick_obj, item_pid_number) > 1) then begin
                count := 0;
                while (obj_is_carrying_obj_pid(Cedrick_obj, item_pid_number) > count) do begin
                    restock_obj := create_object_sid(item_pid_number, 0, 0, -1);
                    add_mult_objs_to_inven(items_carrier, restock_obj, 1);
                    count := count + 1;
                end
                count := 0;
            end
            else begin
                restock_obj := create_object_sid(item_pid_number, 0, 0, -1);
                add_mult_objs_to_inven(items_carrier, restock_obj, 1);
            end
        end
    end
    count := 0;
    item_pid_number := 0;
    set_global_var(843, global_var(843) bwor 1048576);
    party_add(items_carrier);
end

