variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure equip_caravan_team;
procedure choose_random_weapon_for_caravan;
procedure generate_enemy_type;
procedure generate_enemy_team;
procedure choose_random_weapon_for_enemy;
procedure generate_fourth_guard;

variable Karavan_Leader;
variable Karavan_Guard1;
variable Karavan_Guard2;
variable Karavan_Guard3;
variable Karavan_Guard4;
variable Jeremy;
variable Enemy;
variable Enemy_Attacker;
variable map_number;
variable no_smg;
variable no_knife;
variable no_spear;
variable no_rifle;
variable item;
variable enemy_PID;
variable enemy_TILE;
variable enemy_SCRIPT;
variable enemy_ROTATION;
variable enemy_AI;
variable enemy_TEAM;
variable probability;
variable probability_drugs;
variable probability_2nd_ambush;
variable enemy_count;
variable enemy_type;
variable replacing_guard_ID;
variable choose_sub_random_class;
variable powered_ghoul_counter;
variable big_dethclaw_counter;

export variable Map_event;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Map_event := self_obj;
end

procedure map_enter_p_proc
begin
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 40);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(100 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 40);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(100 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 40);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 40);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
    if (((global_var(911) bwand 1) != 0) and not(metarule(22, 0))) then begin
        game_ui_disable;
        if (cur_map_index == 102) then begin
            wm_area_set_pos(31, random(520, 580), random(350, 450));
            if ((global_var(911) bwand 1048576) != 0) then begin
                set_global_var(911, global_var(911) bwand (-1 - 1048576));
                add_timer_event(self_obj, game_ticks(1), 3);
            end
        end
        if ((cur_map_index == 103) or (cur_map_index == 104) or (cur_map_index == 105) or (cur_map_index == 106)) then begin
            if (((global_var(911) bwand 4096) != 0) or ((global_var(911) bwand 256) != 0)) then begin
                wm_area_set_pos(31, random(200, 350), random(110, 170));
            end
            if (((global_var(911) bwand 1024) != 0) or ((global_var(911) bwand 64) != 0)) then begin
                wm_area_set_pos(31, random(680, 740), random(220, 280));
            end
            if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0)) then begin
                wm_area_set_pos(31, random(520, 580), random(350, 450));
            end
            game_time_advance(random(1, 2) * (24 * (60 * (60 * 10))));
            if ((global_var(911) bwand 1048576) != 0) then begin
                set_global_var(911, global_var(911) bwand (-1 - 1048576));
                add_timer_event(self_obj, game_ticks(1), 3);
            end
            else begin
                add_timer_event(self_obj, 8, 3);
            end
        end
        set_global_var(916, 0);
        game_time_advance(random(1, 12) * (60 * (60 * 10)));
        game_time_advance(random(1, 30) * (60 * 10));
        if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0)) then begin
            if ((global_var(911) bwand 4) != 0) then begin
                enemy_count := random(4, 5);
            end
            if ((global_var(911) bwand 8) != 0) then begin
                enemy_count := random(4, 6);
            end
            if ((global_var(911) bwand 16) != 0) then begin
                enemy_count := random(5, 7);
            end
        end
        else begin
            if ((global_var(911) bwand 4) != 0) then begin
                enemy_count := random(4, 5);
            end
            if ((global_var(911) bwand 8) != 0) then begin
                enemy_count := random(4, 6);
            end
            if ((global_var(911) bwand 16) != 0) then begin
                enemy_count := random(5, 7);
            end
        end
        if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0)) then begin
            if ((global_var(867) bwand 268435456) != 0) then begin
                if ((global_var(911) bwand 4) != 0) then begin
                    choose_sub_random_class := random(1, 5);
                    if ((choose_sub_random_class == 1) or (choose_sub_random_class == 2)) then begin
                        enemy_type := 1;
                    end
                    else begin
                        enemy_type := random(13, 18);
                    end
                end
                if ((global_var(911) bwand 8) != 0) then begin
                    choose_sub_random_class := random(1, 6);
                    if ((choose_sub_random_class == 1) or (choose_sub_random_class == 2)) then begin
                        enemy_type := 1;
                    end
                    else begin
                        enemy_type := random(14, 19);
                    end
                end
                if ((global_var(911) bwand 16) != 0) then begin
                    choose_sub_random_class := random(1, 5);
                    if (choose_sub_random_class == 1) then begin
                        enemy_type := 1;
                    end
                    else begin
                        enemy_type := random(14, 20);
                    end
                end
            end
            else begin
                if (get_critter_stat(dude_obj, 6) > 6) then begin
                    choose_sub_random_class := random(1, 4);
                end
                else begin
                    choose_sub_random_class := random(1, 5);
                end
                if (choose_sub_random_class == 1) then begin
                    enemy_type := 1;
                end
                else begin
                    enemy_type := random(15, 20);
                end
            end
        end
        else begin
            if ((global_var(911) bwand 4) != 0) then begin
                enemy_type := random(2, 11);
            end
            if ((global_var(911) bwand 8) != 0) then begin
                enemy_type := random(1, 13);
            end
            if ((global_var(911) bwand 16) != 0) then begin
                enemy_type := random(1, 15);
            end
        end
        if (enemy_type == 4) then begin
            enemy_type := random(5, 8);
        end
        if ((enemy_type == 1) and (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0))) then begin
            if ((global_var(911) bwand 4) != 0) then begin
                enemy_count := random(2, 3);
            end
            if ((global_var(911) bwand 8) != 0) then begin
                enemy_count := random(3, 4);
            end
            if ((global_var(911) bwand 16) != 0) then begin
                enemy_count := random(4, 5);
            end
        end
        if (cur_map_index == 102) then begin
            enemy_type := 7;
            if (global_var(747) == 1) then begin
                enemy_count := 10;
            end
            else begin
                enemy_count := 5;
            end
        end
        if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0)) then begin
            if ((enemy_type == 1) and (enemy_count > 6)) then begin
                enemy_count := 6;
            end
            if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20) and (enemy_count > 6)) then begin
                enemy_count := 6;
            end
        end
        else begin
            if ((enemy_type == 1) and (enemy_count > 5)) then begin
                enemy_count := 5;
            end
            if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20) and (enemy_count > 6)) then begin
                enemy_count := 6;
            end
        end
        if ((global_var(911) bwand 8) != 0) then begin
            if (cur_map_index == 103) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777989, 17502, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777799, 19497, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777799, 22098, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777800, 20708, 0, 23);
                end
            end
            if (cur_map_index == 104) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777989, 19486, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777799, 18496, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777799, 21105, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777800, 19113, 0, 23);
                end
            end
            if (cur_map_index == 105) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777989, 21490, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777799, 22306, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777799, 20108, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777800, 22716, 0, 23);
                end
            end
            if (cur_map_index == 106) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777989, 19079, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777799, 17485, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777799, 17893, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777800, 19705, 0, 23);
                end
            end
        end
        if ((global_var(911) bwand 16) != 0) then begin
            if (cur_map_index == 103) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777990, 17502, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 19497, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 22098, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 20708, 0, 23);
                end
            end
            if (cur_map_index == 104) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777990, 19486, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 18496, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 21105, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 19113, 0, 23);
                end
            end
            if (cur_map_index == 105) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777990, 21490, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 22306, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 20108, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 22716, 0, 23);
                end
            end
            if (cur_map_index == 106) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777990, 19079, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 17485, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 17893, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 19705, 0, 23);
                end
            end
        end
        if ((global_var(911) bwand 4) != 0) then begin
            if (cur_map_index == 102) then begin
                Karavan_Leader := create_object_sid(16777765, 17898, 0, 23);
                Karavan_Guard1 := create_object_sid(16777797, 19501, 0, 23);
                Karavan_Guard2 := create_object_sid(16777797, 20908, 0, 23);
                Karavan_Guard3 := create_object_sid(16777798, 21295, 0, 23);
                Karavan_Guard4 := create_object_sid(16777798, 22902, 0, 23);
            end
            if (cur_map_index == 103) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777991, 17502, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 19497, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 22098, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 20708, 0, 23);
                end
            end
            if (cur_map_index == 104) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777991, 19486, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 18496, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 21105, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 19113, 0, 23);
                end
            end
            if (cur_map_index == 105) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777991, 21490, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 22306, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 20108, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 22716, 0, 23);
                end
            end
            if (cur_map_index == 106) then begin
                if (not((global_var(911) bwand 8192) != 0)) then begin
                    Karavan_Leader := create_object_sid(16777991, 19079, 0, 23);
                end
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    Karavan_Guard1 := create_object_sid(16777797, 17485, 0, 23);
                end
                if (not((global_var(911) bwand 32768) != 0)) then begin
                    Karavan_Guard2 := create_object_sid(16777797, 17893, 0, 23);
                end
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    Karavan_Guard3 := create_object_sid(16777798, 19705, 0, 23);
                end
            end
        end
        if (cur_map_index == 102) then begin
            anim(Karavan_Leader, 1000, 5);
            anim(Karavan_Guard1, 1000, 5);
            anim(Karavan_Guard2, 1000, 5);
            anim(Karavan_Guard3, 1000, 5);
            anim(Karavan_Guard4, 1000, 5);
        end
        if (cur_map_index == 103) then begin
            if (not((global_var(911) bwand 8192) != 0)) then begin
                anim(Karavan_Leader, 1000, 5);
            end
            if (not((global_var(911) bwand 16384) != 0)) then begin
                anim(Karavan_Guard1, 1000, 5);
            end
            if (not((global_var(911) bwand 32768) != 0)) then begin
                anim(Karavan_Guard2, 1000, 5);
            end
            if (not((global_var(911) bwand 65536) != 0)) then begin
                anim(Karavan_Guard3, 1000, 5);
            end
        end
        if (cur_map_index == 104) then begin
            if (not((global_var(911) bwand 8192) != 0)) then begin
                anim(Karavan_Leader, 1000, 0);
            end
            if (not((global_var(911) bwand 16384) != 0)) then begin
                anim(Karavan_Guard1, 1000, 0);
            end
            if (not((global_var(911) bwand 32768) != 0)) then begin
                anim(Karavan_Guard2, 1000, 0);
            end
            if (not((global_var(911) bwand 65536) != 0)) then begin
                anim(Karavan_Guard3, 1000, 0);
            end
        end
        if (cur_map_index == 105) then begin
            if (not((global_var(911) bwand 8192) != 0)) then begin
                anim(Karavan_Leader, 1000, 1);
            end
            if (not((global_var(911) bwand 16384) != 0)) then begin
                anim(Karavan_Guard1, 1000, 1);
            end
            if (not((global_var(911) bwand 32768) != 0)) then begin
                anim(Karavan_Guard2, 1000, 1);
            end
            if (not((global_var(911) bwand 65536) != 0)) then begin
                anim(Karavan_Guard3, 1000, 1);
            end
        end
        if (cur_map_index == 106) then begin
            if (not((global_var(911) bwand 8192) != 0)) then begin
                anim(Karavan_Leader, 1000, 1);
            end
            if (not((global_var(911) bwand 16384) != 0)) then begin
                anim(Karavan_Guard1, 1000, 1);
            end
            if (not((global_var(911) bwand 32768) != 0)) then begin
                anim(Karavan_Guard2, 1000, 1);
            end
            if (not((global_var(911) bwand 65536) != 0)) then begin
                anim(Karavan_Guard3, 1000, 1);
            end
        end
        call equip_caravan_team();
        if ((global_var(911) bwand 8192) != 0) then begin
            if ((global_var(911) bwand 4) != 0) then begin
                if (not((global_var(911) bwand 65536) != 0)) then begin
                    replacing_guard_ID := 3;
                end
                else begin
                    if (not((global_var(911) bwand 32768) != 0)) then begin
                        replacing_guard_ID := 2;
                    end
                    else begin
                        replacing_guard_ID := 1;
                    end
                end
            end
            else begin
                if (not((global_var(911) bwand 16384) != 0)) then begin
                    replacing_guard_ID := 1;
                end
                else begin
                    if (not((global_var(911) bwand 32768) != 0)) then begin
                        replacing_guard_ID := 2;
                    end
                    else begin
                        replacing_guard_ID := 3;
                    end
                end
            end
            if (replacing_guard_ID == 1) then begin
                if (cur_map_index == 103) then begin
                    move_to(Karavan_Guard1, 17502, 0);
                end
                if (cur_map_index == 104) then begin
                    move_to(Karavan_Guard1, 19486, 0);
                end
                if (cur_map_index == 105) then begin
                    move_to(Karavan_Guard1, 21490, 0);
                end
                if (cur_map_index == 106) then begin
                    move_to(Karavan_Guard1, 19079, 0);
                end
            end
            if (replacing_guard_ID == 2) then begin
                if (cur_map_index == 103) then begin
                    move_to(Karavan_Guard2, 17502, 0);
                end
                if (cur_map_index == 104) then begin
                    move_to(Karavan_Guard2, 19486, 0);
                end
                if (cur_map_index == 105) then begin
                    move_to(Karavan_Guard2, 21490, 0);
                end
                if (cur_map_index == 106) then begin
                    move_to(Karavan_Guard2, 19079, 0);
                end
            end
            if (replacing_guard_ID == 3) then begin
                if (cur_map_index == 103) then begin
                    move_to(Karavan_Guard3, 17502, 0);
                end
                if (cur_map_index == 104) then begin
                    move_to(Karavan_Guard3, 19486, 0);
                end
                if (cur_map_index == 105) then begin
                    move_to(Karavan_Guard3, 21490, 0);
                end
                if (cur_map_index == 106) then begin
                    move_to(Karavan_Guard3, 19079, 0);
                end
            end
        end
        if (cur_map_index == 102) then begin
            add_timer_event(Karavan_Leader, game_ticks(0), 6);
        end
        else begin
            if (not((global_var(911) bwand 8192) != 0)) then begin
                add_timer_event(Karavan_Leader, game_ticks(0), 1);
            end
        end
        if (not((global_var(911) bwand 16384) != 0)) then begin
            add_timer_event(Karavan_Guard1, game_ticks(0), 2);
        end
        if (not((global_var(911) bwand 32768) != 0)) then begin
            add_timer_event(Karavan_Guard2, game_ticks(0), 3);
        end
        if (not((global_var(911) bwand 65536) != 0)) then begin
            add_timer_event(Karavan_Guard3, game_ticks(0), 4);
        end
        if (cur_map_index == 102) then begin
            add_timer_event(Karavan_Guard4, game_ticks(0), 5);
        end
        if (not((global_var(911) bwand 524288) != 0) and not((global_var(911) bwand 262144) != 0)) then begin
            call generate_fourth_guard();
            add_timer_event(Karavan_Guard4, game_ticks(0), 5);
            set_global_var(911, global_var(911) bwor 2097152);
        end
        if (not((global_var(911) bwand 8192) != 0)) then begin
            add_timer_event(Karavan_Leader, 5, 10);
        end
        if (not((global_var(911) bwand 16384) != 0)) then begin
            add_timer_event(Karavan_Guard1, 5, 10);
        end
        if (not((global_var(911) bwand 32768) != 0)) then begin
            add_timer_event(Karavan_Guard2, 5, 10);
        end
        if (not((global_var(911) bwand 65536) != 0)) then begin
            add_timer_event(Karavan_Guard3, 5, 10);
        end
        if (cur_map_index == 102) then begin
            add_timer_event(Karavan_Guard4, 5, 10);
        end
        if ((global_var(1024) == 1) and (cur_map_index == 102)) then begin
        end
        else begin
            add_timer_event(self_obj, 6, 1);
        end
        if (cur_map_index == 102) then begin
            move_to(dude_obj, 18303, 0);
            anim(dude_obj, 1000, 5);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (has_trait(1, party_member_obj(16777729), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (has_trait(1, party_member_obj(16777779), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (has_trait(1, party_member_obj(16777811), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (has_trait(1, party_member_obj(16777812), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (has_trait(1, party_member_obj(16777814), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (has_trait(1, party_member_obj(16777748), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (has_trait(1, party_member_obj(16778017), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (has_trait(1, party_member_obj(16778016), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (has_trait(1, party_member_obj(16778049), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (has_trait(1, party_member_obj(16778050), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (has_trait(1, party_member_obj(16778051), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (has_trait(1, party_member_obj(16777293), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 5);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 5);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 5);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 5);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 5);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 5);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 5);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 5);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 5);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 5);
            end
        end
        if (cur_map_index == 103) then begin
            move_to(dude_obj, 18307, 0);
            anim(dude_obj, 1000, 5);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (has_trait(1, party_member_obj(16777729), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (has_trait(1, party_member_obj(16777779), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (has_trait(1, party_member_obj(16777811), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (has_trait(1, party_member_obj(16777812), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (has_trait(1, party_member_obj(16777814), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (has_trait(1, party_member_obj(16777748), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (has_trait(1, party_member_obj(16778017), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (has_trait(1, party_member_obj(16778016), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (has_trait(1, party_member_obj(16778049), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (has_trait(1, party_member_obj(16778050), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (has_trait(1, party_member_obj(16778051), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (has_trait(1, party_member_obj(16777293), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 5);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 5);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 5);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 5);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 5);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 5);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 5);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 5);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 5);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 5);
            end
        end
        if (cur_map_index == 104) then begin
            move_to(dude_obj, 20693, 0);
            anim(dude_obj, 1000, 0);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (has_trait(1, party_member_obj(16777729), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (has_trait(1, party_member_obj(16777779), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (has_trait(1, party_member_obj(16777811), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (has_trait(1, party_member_obj(16777812), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (has_trait(1, party_member_obj(16777814), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (has_trait(1, party_member_obj(16777748), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (has_trait(1, party_member_obj(16778017), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (has_trait(1, party_member_obj(16778016), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (has_trait(1, party_member_obj(16778049), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (has_trait(1, party_member_obj(16778050), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (has_trait(1, party_member_obj(16778051), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (has_trait(1, party_member_obj(16777293), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 0);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 0);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 0);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 0);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 0);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 0);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 0);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 0);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 0);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 0);
            end
        end
        if (cur_map_index == 105) then begin
            move_to(dude_obj, 19891, 0);
            anim(dude_obj, 1000, 1);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (has_trait(1, party_member_obj(16777729), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (has_trait(1, party_member_obj(16777779), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (has_trait(1, party_member_obj(16777811), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (has_trait(1, party_member_obj(16777812), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (has_trait(1, party_member_obj(16777814), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (has_trait(1, party_member_obj(16777748), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (has_trait(1, party_member_obj(16778017), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (has_trait(1, party_member_obj(16778016), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (has_trait(1, party_member_obj(16778049), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (has_trait(1, party_member_obj(16778050), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (has_trait(1, party_member_obj(16778051), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (has_trait(1, party_member_obj(16777293), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 1);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 1);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 1);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 1);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 1);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 1);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 1);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 1);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 1);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 1);
            end
        end
        if (cur_map_index == 106) then begin
            move_to(dude_obj, 19887, 0);
            anim(dude_obj, 1000, 1);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (has_trait(1, party_member_obj(16777729), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (has_trait(1, party_member_obj(16777779), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (has_trait(1, party_member_obj(16777811), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (has_trait(1, party_member_obj(16777812), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (has_trait(1, party_member_obj(16777814), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (has_trait(1, party_member_obj(16777748), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (has_trait(1, party_member_obj(16778017), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (has_trait(1, party_member_obj(16778016), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (has_trait(1, party_member_obj(16778049), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (has_trait(1, party_member_obj(16778050), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (has_trait(1, party_member_obj(16778051), 666)) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (has_trait(1, party_member_obj(16777293), 666)) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 2), elevation(dude_obj));
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 1);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 1);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 1);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 1);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 1);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 1);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 1);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 1);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 1);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 1);
            end
            add_timer_event(self_obj, 1, 2);
        end
        call generate_enemy_type();
        if (cur_map_index == 102) then begin
            enemy_TILE := 16298;
            enemy_ROTATION := 2;
        end
        if (cur_map_index == 103) then begin
            enemy_TILE := 16303;
            enemy_ROTATION := 2;
        end
        if (cur_map_index == 104) then begin
            enemy_TILE := 18677;
            enemy_ROTATION := 3;
        end
        if (cur_map_index == 105) then begin
            enemy_TILE := 22487;
            enemy_ROTATION := 4;
        end
        if (cur_map_index == 106) then begin
            enemy_TILE := 20280;
            enemy_ROTATION := 5;
        end
        Enemy_Attacker := create_object_sid(enemy_PID, enemy_TILE, 0, enemy_SCRIPT);
        critter_add_trait(Enemy_Attacker, 1, 6, enemy_TEAM);
        critter_add_trait(Enemy_Attacker, 1, 5, enemy_AI);
        anim(Enemy_Attacker, 1000, enemy_ROTATION);
        set_global_var(916, global_var(916) + 1);
        if (enemy_type == 1) then begin
            display_msg(message_str(35, 100));
        end
        if (enemy_type == 2) then begin
            display_msg(message_str(35, 101));
        end
        if (enemy_type == 3) then begin
            display_msg(message_str(35, 102));
        end
        if (enemy_type == 4) then begin
            display_msg(message_str(35, 103));
        end
        if (enemy_type == 5) then begin
            display_msg(message_str(35, 104));
        end
        if (enemy_type == 6) then begin
            display_msg(message_str(35, 105));
        end
        if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15)) then begin
            display_msg(message_str(35, 106));
        end
        if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20)) then begin
            display_msg(message_str(35, 107));
        end
        if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15) or ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20))) then begin
            call choose_random_weapon_for_enemy();
            restock_obj := create_object_sid(item, 0, 0, -1);
            add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
            if (obj_is_carrying_obj_pid(Enemy_Attacker, 94)) then begin
                restock_obj := create_object_sid(95, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
            end
            if (obj_is_carrying_obj_pid(Enemy_Attacker, 13)) then begin
                restock_obj := create_object_sid(14, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 2);
            end
            if (obj_is_carrying_obj_pid(Enemy_Attacker, 143)) then begin
                restock_obj := create_object_sid(34, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
            end
            if (obj_is_carrying_obj_pid(Enemy_Attacker, 12)) then begin
                restock_obj := create_object_sid(35, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
            end
            if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15)) then begin
                probability_drugs := random(1, 10);
                restock_obj := create_object_sid(41, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, random(10, 30));
                if (probability_drugs == 1) then begin
                    restock_obj := create_object_sid(87, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                if (probability_drugs == 2) then begin
                    restock_obj := create_object_sid(53, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                if (probability_drugs == 3) then begin
                    restock_obj := create_object_sid(110, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                if (probability_drugs == 4) then begin
                    restock_obj := create_object_sid(40, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                if (probability_drugs == 5) then begin
                    restock_obj := create_object_sid(87, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                if (probability_drugs == 6) then begin
                    restock_obj := create_object_sid(53, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                add_timer_event(Enemy_Attacker, 1, 20);
            end
            if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20)) then begin
                if (not(obj_carrying_pid_obj(Enemy_Attacker, 309))) then begin
                    restock_obj := create_object_sid(309, 0, 0, -1);
                    add_mult_objs_to_inven(Enemy_Attacker, restock_obj, 1);
                end
                restock_obj := create_object_sid(40, 0, 0, -1);
                add_mult_objs_to_inven(Enemy_Attacker, restock_obj, random(1, 2));
                add_timer_event(Enemy_Attacker, 1, 20);
            end
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 16293;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 16298;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 18081;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 23293;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 19675;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 16507;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 15502;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 20482;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 23488;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 20877;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 15300;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 15907;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 19676;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 22081;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 20284;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 14894;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 17108;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 17274;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 24492;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 21683;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 16890;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 16895;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 18272;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 23283;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 21286;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 15487;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 17913;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 16677;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 24296;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 21880;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 17888;
            end
            if (cur_map_index == 103) then begin
                enemy_TILE := 15296;
            end
            if (cur_map_index == 104) then begin
                enemy_TILE := 16682;
            end
            if (cur_map_index == 105) then begin
                enemy_TILE := 24486;
            end
            if (cur_map_index == 106) then begin
                enemy_TILE := 20072;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 17710;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 14088;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (enemy_count > global_var(916)) then begin
            if (cur_map_index == 102) then begin
                enemy_TILE := 14096;
            end
            call generate_enemy_type();
            call generate_enemy_team();
        end
        if (cur_map_index == 102) then begin
            if (global_var(1024) == 1) then begin
                Jeremy := create_object_sid(16777764, 17103, 0, 12);
                anim(Jeremy, 1000, 2);
                restock_obj := create_object_sid(18, 0, 0, -1);
                add_mult_objs_to_inven(Jeremy, restock_obj, 1);
                restock_obj := create_object_sid(31, 0, 0, -1);
                add_mult_objs_to_inven(Jeremy, restock_obj, 1);
                restock_obj := create_object_sid(40, 0, 0, -1);
                add_mult_objs_to_inven(Jeremy, restock_obj, 1);
                restock_obj := create_object_sid(110, 0, 0, -1);
                add_mult_objs_to_inven(Jeremy, restock_obj, 1);
                set_global_var(916, global_var(916) + 1);
                if (cur_map_index == 102) then begin
                    add_timer_event(Jeremy, 2, 20);
                end
            end
        end
        set_global_var(911, global_var(911) bwor 33554432);
        game_ui_enable;
    end
end

procedure map_update_p_proc
begin
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 40);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(100 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 40);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(100 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 40);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 40);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
    if (((global_var(911) bwand 33554432) == 0) or (((global_var(911) bwand 8192) != 0) and ((global_var(911) bwand 16384) != 0) and ((global_var(911) bwand 32768) != 0) and ((global_var(911) bwand 65536) != 0) and not((global_var(911) bwand 2097152) != 0)) or (((global_var(911) bwand 16384) != 0) and ((global_var(911) bwand 32768) != 0) and ((global_var(911) bwand 65536) != 0) and ((global_var(911) bwand 524288) != 0)) or (global_var(916) > 0) or ((global_var(911) bwand 131072) != 0)) then begin
    end
    else begin
        probability_2nd_ambush := 0;
        if (not((global_var(911) bwand 262144) != 0)) then begin
            if (((global_var(911) bwand 1024) != 0) or ((global_var(911) bwand 64) != 0)) then begin
                if ((global_var(911) bwand 8) != 0) then begin
                    probability_2nd_ambush := random(1, 20);
                end
                if ((global_var(911) bwand 16) != 0) then begin
                    probability_2nd_ambush := random(1, 5);
                end
                if ((global_var(911) bwand 4) != 0) then begin
                    probability_2nd_ambush := random(1, 30);
                end
            end
            else begin
                if ((global_var(911) bwand 8) != 0) then begin
                    probability_2nd_ambush := random(1, 10);
                end
                if ((global_var(911) bwand 16) != 0) then begin
                    probability_2nd_ambush := random(1, 3);
                end
                if ((global_var(911) bwand 4) != 0) then begin
                    probability_2nd_ambush := random(1, 20);
                end
            end
            set_global_var(911, global_var(911) bwor 262144);
        end
        if (probability_2nd_ambush == 1) then begin
            map_number := random(1, 3);
            if (cur_map_index == 102) then begin
                if ((global_var(911) bwand 2048) != 0) then begin
                    if ((global_var(867) bwand 268435456) != 0) then begin
                        set_exit_grids(0, 21, 0, 25707, 0);
                    end
                    else begin
                        set_exit_grids(0, 21, 0, 28911, 5);
                    end
                end
            end
            if (cur_map_index == 103) then begin
                if (map_number == 1) then begin
                    set_exit_grids(0, 104, 0, 20693, 0);
                end
                if (map_number == 2) then begin
                    set_exit_grids(0, 105, 0, 19891, 1);
                end
                if (map_number == 3) then begin
                    set_exit_grids(0, 106, 0, 19887, 1);
                end
            end
            if (cur_map_index == 104) then begin
                if (map_number == 1) then begin
                    set_exit_grids(0, 103, 0, 18307, 5);
                end
                if (map_number == 2) then begin
                    set_exit_grids(0, 105, 0, 19891, 1);
                end
                if (map_number == 3) then begin
                    set_exit_grids(0, 106, 0, 19887, 1);
                end
            end
            if (cur_map_index == 105) then begin
                if (map_number == 1) then begin
                    set_exit_grids(0, 103, 0, 18307, 5);
                end
                if (map_number == 2) then begin
                    set_exit_grids(0, 104, 0, 20693, 0);
                end
                if (map_number == 3) then begin
                    set_exit_grids(0, 106, 0, 19887, 1);
                end
            end
            if (cur_map_index == 106) then begin
                if (map_number == 1) then begin
                    set_exit_grids(0, 103, 0, 18307, 5);
                end
                if (map_number == 2) then begin
                    set_exit_grids(0, 104, 0, 20693, 0);
                end
                if (map_number == 3) then begin
                    set_exit_grids(0, 105, 0, 19891, 1);
                end
            end
        end
        else begin
            if ((global_var(911) bwand 512) != 0) then begin
                if ((global_var(911) bwand 8) != 0) then begin
                    set_exit_grids(0, 12, 0, 22104, 3);
                end
                if ((global_var(911) bwand 16) != 0) then begin
                    set_exit_grids(0, 11, 0, 14475, 5);
                end
                if ((global_var(911) bwand 4) != 0) then begin
                    set_exit_grids(0, 9, 0, 18888, 5);
                end
            end
            if ((global_var(911) bwand 1024) != 0) then begin
                if ((global_var(842) bwand 1073741824) != 0) then begin
                    set_exit_grids(0, 15, 0, 21751, 3);
                end
                else begin
                    set_exit_grids(0, 15, 0, 18944, 0);
                end
            end
            if ((global_var(911) bwand 2048) != 0) then begin
                if ((global_var(867) bwand 268435456) != 0) then begin
                    set_exit_grids(0, 21, 0, 25707, 0);
                end
                else begin
                    set_exit_grids(0, 21, 0, 28911, 5);
                end
            end
            if ((global_var(911) bwand 4096) != 0) then begin
                set_exit_grids(0, 6, 1, 25523, 0);
            end
        end
    end
end

procedure map_exit_p_proc
begin
    set_global_var(911, global_var(911) bwand (-1 - 33554432));
    if (((global_var(911) bwand 8192) != 0) and ((global_var(911) bwand 16384) != 0) and ((global_var(911) bwand 32768) != 0) and ((global_var(911) bwand 65536) != 0) and not((global_var(911) bwand 2097152) != 0) or (((global_var(911) bwand 16384) != 0) and ((global_var(911) bwand 32768) != 0) and ((global_var(911) bwand 65536) != 0) and ((global_var(911) bwand 524288) != 0)) or (global_var(916) > 0) or ((global_var(911) bwand 131072) != 0)) then begin
        if ((global_var(911) bwand 1) != 0) then begin
            if ((global_var(911) bwand 8) != 0) then begin
                set_global_var(735, 1);
            end
            if ((global_var(911) bwand 16) != 0) then begin
                set_global_var(783, 1);
            end
            if ((global_var(911) bwand 4) != 0) then begin
                set_global_var(742, 1);
            end
        end
        set_global_var(911, 0);
        set_global_var(915, 0);
        set_global_var(916, 0);
        if ((global_var(748) == 2) and (global_var(747) == 1) and (global_var(751) == 0)) then begin
            set_global_var(751, 1);
        end
        if ((global_var(748) == 2) and (global_var(751) == 1)) then begin
            set_global_var(1058, 1);
        end
    end
    else begin
        gfade_out(1);
        set_global_var(911, global_var(911) bwor 1048576);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        set_global_var(911, global_var(911) bwor 8388608);
        if (not((global_var(911) bwand 8192) != 0)) then begin
            attack_setup(Enemy_Attacker, Karavan_Leader);
        end
        else begin
            if (replacing_guard_ID == 1) then begin
                attack_setup(Enemy_Attacker, Karavan_Guard1);
            end
            if (replacing_guard_ID == 2) then begin
                attack_setup(Enemy_Attacker, Karavan_Guard2);
            end
            if (replacing_guard_ID == 3) then begin
                attack_setup(Enemy_Attacker, Karavan_Guard3);
            end
        end
    end
    if (fixed_param == 2) then begin
        metarule3(108, 18284, 0, 0);
    end
    if (fixed_param == 3) then begin
        gfade_in(1);
    end
    if (fixed_param == 4) then begin
        if (not((global_var(911) bwand 8192) != 0)) then begin
            if (obj_is_carrying_obj_pid(Karavan_Leader, 18) >= 1) then begin
                wield_obj_critter(Karavan_Leader, obj_carrying_pid_obj(Karavan_Leader, 18));
            end
            if (obj_is_carrying_obj_pid(Karavan_Leader, 9) >= 1) then begin
                wield_obj_critter(Karavan_Leader, obj_carrying_pid_obj(Karavan_Leader, 9));
            end
            if (obj_is_carrying_obj_pid(Karavan_Leader, 10) >= 1) then begin
                wield_obj_critter(Karavan_Leader, obj_carrying_pid_obj(Karavan_Leader, 10));
            end
            if (obj_is_carrying_obj_pid(Karavan_Leader, 8) >= 1) then begin
                wield_obj_critter(Karavan_Leader, obj_carrying_pid_obj(Karavan_Leader, 8));
            end
            if (obj_is_carrying_obj_pid(Karavan_Leader, 16) >= 1) then begin
                wield_obj_critter(Karavan_Leader, obj_carrying_pid_obj(Karavan_Leader, 16));
            end
        end
        if (not((global_var(911) bwand 16384) != 0)) then begin
            if (obj_is_carrying_obj_pid(Karavan_Guard1, 18) >= 1) then begin
                wield_obj_critter(Karavan_Guard1, obj_carrying_pid_obj(Karavan_Guard1, 18));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard1, 9) >= 1) then begin
                wield_obj_critter(Karavan_Guard1, obj_carrying_pid_obj(Karavan_Guard1, 9));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard1, 10) >= 1) then begin
                wield_obj_critter(Karavan_Guard1, obj_carrying_pid_obj(Karavan_Guard1, 10));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard1, 8) >= 1) then begin
                wield_obj_critter(Karavan_Guard1, obj_carrying_pid_obj(Karavan_Guard1, 8));
            end
        end
        if (not((global_var(911) bwand 32768) != 0)) then begin
            if (obj_is_carrying_obj_pid(Karavan_Guard2, 18) >= 1) then begin
                wield_obj_critter(Karavan_Guard2, obj_carrying_pid_obj(Karavan_Guard2, 18));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard2, 9) >= 1) then begin
                wield_obj_critter(Karavan_Guard2, obj_carrying_pid_obj(Karavan_Guard2, 9));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard2, 10) >= 1) then begin
                wield_obj_critter(Karavan_Guard2, obj_carrying_pid_obj(Karavan_Guard2, 10));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard2, 8) >= 1) then begin
                wield_obj_critter(Karavan_Guard2, obj_carrying_pid_obj(Karavan_Guard2, 8));
            end
        end
        if (not((global_var(911) bwand 65536) != 0)) then begin
            if (obj_is_carrying_obj_pid(Karavan_Guard3, 18) >= 1) then begin
                wield_obj_critter(Karavan_Guard3, obj_carrying_pid_obj(Karavan_Guard3, 18));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard3, 9) >= 1) then begin
                wield_obj_critter(Karavan_Guard3, obj_carrying_pid_obj(Karavan_Guard3, 9));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard3, 10) >= 1) then begin
                wield_obj_critter(Karavan_Guard3, obj_carrying_pid_obj(Karavan_Guard3, 10));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard3, 8) >= 1) then begin
                wield_obj_critter(Karavan_Guard3, obj_carrying_pid_obj(Karavan_Guard3, 8));
            end
        end
        if (((global_var(911) bwand 2097152) != 0) or (cur_map_index == 102) and not((global_var(911) bwand 524288) != 0)) then begin
            if (obj_is_carrying_obj_pid(Karavan_Guard4, 18) >= 1) then begin
                wield_obj_critter(Karavan_Guard4, obj_carrying_pid_obj(Karavan_Guard4, 18));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard4, 9) >= 1) then begin
                wield_obj_critter(Karavan_Guard4, obj_carrying_pid_obj(Karavan_Guard4, 9));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard4, 10) >= 1) then begin
                wield_obj_critter(Karavan_Guard4, obj_carrying_pid_obj(Karavan_Guard4, 10));
            end
            if (obj_is_carrying_obj_pid(Karavan_Guard4, 8) >= 1) then begin
                wield_obj_critter(Karavan_Guard4, obj_carrying_pid_obj(Karavan_Guard4, 8));
            end
        end
        add_timer_event(self_obj, game_ticks(1), 3);
    end
end

procedure equip_caravan_team
begin
    call choose_random_weapon_for_caravan();
    if (cur_map_index == 102) then begin
        restock_obj := create_object_sid(16, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        restock_obj := create_object_sid(38, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
    end
    else begin
        if (not((global_var(911) bwand 8192) != 0)) then begin
            restock_obj := create_object_sid(item, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        end
    end
    call choose_random_weapon_for_caravan();
    if (not((global_var(911) bwand 16384) != 0)) then begin
        restock_obj := create_object_sid(item, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
    end
    call choose_random_weapon_for_caravan();
    if (not((global_var(911) bwand 32768) != 0)) then begin
        restock_obj := create_object_sid(item, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
    end
    call choose_random_weapon_for_caravan();
    if (not((global_var(911) bwand 65536) != 0)) then begin
        restock_obj := create_object_sid(item, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
    end
    if (not((global_var(911) bwand 8192) != 0)) then begin
        restock_obj := create_object_sid(40, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
    end
    if (not((global_var(911) bwand 16384) != 0)) then begin
        restock_obj := create_object_sid(40, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
    end
    if (not((global_var(911) bwand 32768) != 0)) then begin
        restock_obj := create_object_sid(40, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
    end
    if (not((global_var(911) bwand 65536) != 0)) then begin
        restock_obj := create_object_sid(40, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
    end
    if (not((global_var(911) bwand 8192) != 0) and not(cur_map_index == 102)) then begin
        if (obj_is_carrying_obj_pid(Karavan_Leader, 94)) then begin
            restock_obj := create_object_sid(95, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Leader, 18)) then begin
            restock_obj := create_object_sid(31, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Leader, 9)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Leader, 8)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Leader, restock_obj, 1);
        end
    end
    if (not((global_var(911) bwand 16384) != 0)) then begin
        if (obj_is_carrying_obj_pid(Karavan_Guard1, 94)) then begin
            restock_obj := create_object_sid(95, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard1, 18)) then begin
            restock_obj := create_object_sid(31, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard1, 9)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard1, 8)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard1, restock_obj, 1);
        end
    end
    if (not((global_var(911) bwand 32768) != 0)) then begin
        if (obj_is_carrying_obj_pid(Karavan_Guard2, 94)) then begin
            restock_obj := create_object_sid(95, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard2, 18)) then begin
            restock_obj := create_object_sid(31, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard2, 9)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard2, 8)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard2, restock_obj, 1);
        end
    end
    if (not((global_var(911) bwand 65536) != 0)) then begin
        if (obj_is_carrying_obj_pid(Karavan_Guard3, 94)) then begin
            restock_obj := create_object_sid(95, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard3, 18)) then begin
            restock_obj := create_object_sid(31, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard3, 9)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Karavan_Guard3, 8)) then begin
            restock_obj := create_object_sid(29, 0, 0, -1);
            add_mult_objs_to_inven(Karavan_Guard3, restock_obj, 1);
        end
    end
    if (not((global_var(911) bwand 8192) != 0)) then begin
        restock_obj := create_object_sid(41, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Leader, restock_obj, random(20, 100));
    end
    if (not((global_var(911) bwand 16384) != 0)) then begin
        restock_obj := create_object_sid(41, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard1, restock_obj, random(10, 50));
    end
    if (not((global_var(911) bwand 32768) != 0)) then begin
        restock_obj := create_object_sid(41, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard2, restock_obj, random(10, 50));
    end
    if (not((global_var(911) bwand 65536) != 0)) then begin
        restock_obj := create_object_sid(41, 0, 0, -1);
        add_mult_objs_to_inven(Karavan_Guard3, restock_obj, random(10, 50));
    end
    add_timer_event(self_obj, 2, 4);
end

procedure choose_random_weapon_for_caravan
begin
    if ((global_var(911) bwand 4) != 0) then begin
        probability := random(1, 4);
    end
    else begin
        probability := random(1, 3);
    end
    if (probability == 1) then begin
        item := 18;
    end
    if (probability == 2) then begin
        item := 9;
    end
    if (probability == 3) then begin
        item := 10;
    end
    if (probability == 4) then begin
        item := 8;
    end
end

procedure generate_enemy_type
begin
    if (enemy_type == 1) then begin
        if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0) and (big_dethclaw_counter < 1)) then begin
            probability := random(1, 4);
        end
        else begin
            if (not((global_var(911) bwand 2048) != 0) and not((global_var(911) bwand 128) != 0) and (big_dethclaw_counter < 3)) then begin
                probability := random(1, 4);
            end
            else begin
                probability := random(1, 3);
            end
        end
        if (((global_var(911) bwand 2048) != 0) or ((global_var(911) bwand 128) != 0)) then begin
            if ((probability == 1) or (probability == 2) or (probability == 3)) then begin
                enemy_PID := 16777460;
            end
            else begin
                enemy_PID := 16777461;
            end
        end
        else begin
            if ((probability == 1) or (probability == 2) or (probability == 3)) then begin
                enemy_PID := 16777223;
            end
            else begin
                enemy_PID := 16777224;
            end
        end
        if (probability == 4) then begin
            big_dethclaw_counter := big_dethclaw_counter + 1;
        end
        enemy_SCRIPT := 791;
        enemy_AI := 10;
        enemy_TEAM := 187;
    end
    if (enemy_type == 2) then begin
        enemy_PID := 16778046;
        enemy_SCRIPT := 632;
        enemy_AI := 186;
        enemy_TEAM := 144;
    end
    if (enemy_type == 3) then begin
        probability := random(1, 3);
        if ((probability == 1) or (probability == 2)) then begin
            enemy_PID := 16777302;
        end
        else begin
            enemy_PID := 16777297;
        end
        enemy_SCRIPT := 615;
        enemy_AI := 26;
        enemy_TEAM := 122;
    end
    if (enemy_type == 4) then begin
        enemy_PID := 16777432;
        enemy_SCRIPT := 630;
        enemy_AI := 9;
        enemy_TEAM := 142;
    end
    if (enemy_type == 5) then begin
        probability := random(1, 3);
        if (probability == 1) then begin
            enemy_PID := 16777329;
        end
        else begin
            enemy_PID := 16777333;
        end
        enemy_SCRIPT := 617;
        enemy_AI := 7;
        enemy_TEAM := 124;
    end
    if (enemy_type == 6) then begin
        probability := random(1, 3);
        if ((probability == 1) or (probability == 2)) then begin
            enemy_PID := 16777222;
        end
        else begin
            enemy_PID := 16777221;
        end
        enemy_SCRIPT := 616;
        enemy_AI := 8;
        enemy_TEAM := 123;
    end
    if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15)) then begin
        probability := random(1, 7);
        if ((probability == 1) or (probability == 2)) then begin
            enemy_PID := 16777998;
        end
        if ((probability == 3) or (probability == 4)) then begin
            enemy_PID := 16777999;
        end
        if (probability == 5) then begin
            enemy_PID := 16777775;
        end
        if (probability == 6) then begin
            enemy_PID := 16777776;
        end
        if (probability == 7) then begin
            enemy_PID := 16777777;
        end
        if ((probability == 1) or (probability == 2)) then begin
            no_spear := 1;
            no_rifle := 1;
        end
        if ((probability == 3) or (probability == 4)) then begin
            no_rifle := 1;
        end
        if (probability == 6) then begin
            no_spear := 1;
            no_smg := 1;
            no_knife := 1;
        end
        enemy_SCRIPT := 81;
        enemy_AI := 13;
        enemy_TEAM := 45;
    end
    if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20)) then begin
        if (powered_ghoul_counter < 1) then begin
            probability := random(1, 5);
        end
        else begin
            probability := random(3, 5);
        end
        if ((probability == 1) or (probability == 2)) then begin
            enemy_PID := 16778019;
        end
        if ((probability == 3) or (probability == 4)) then begin
            enemy_PID := 16777820;
        end
        if (probability == 5) then begin
            enemy_PID := 16777822;
        end
        if ((probability == 1) or (probability == 2)) then begin
            powered_ghoul_counter := powered_ghoul_counter + 1;
        end
        if ((probability == 3) or (probability == 4) or (probability == 5)) then begin
            no_rifle := 1;
        end
        enemy_SCRIPT := 48;
        enemy_AI := 36;
        enemy_TEAM := 103;
    end
end

procedure generate_enemy_team
begin
    Enemy := create_object_sid(enemy_PID, enemy_TILE, 0, enemy_SCRIPT);
    critter_add_trait(Enemy, 1, 6, enemy_TEAM);
    critter_add_trait(Enemy, 1, 5, enemy_AI);
    anim(Enemy, 1000, enemy_ROTATION);
    set_global_var(916, global_var(916) + 1);
    if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15) or ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20))) then begin
        call choose_random_weapon_for_enemy();
        restock_obj := create_object_sid(item, 0, 0, -1);
        add_mult_objs_to_inven(Enemy, restock_obj, 1);
        if (obj_is_carrying_obj_pid(Enemy, 94)) then begin
            restock_obj := create_object_sid(95, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Enemy, 13)) then begin
            restock_obj := create_object_sid(14, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, 2);
        end
        if (obj_is_carrying_obj_pid(Enemy, 143)) then begin
            restock_obj := create_object_sid(34, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, 1);
        end
        if (obj_is_carrying_obj_pid(Enemy, 12)) then begin
            restock_obj := create_object_sid(35, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, 1);
        end
        if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15)) then begin
            probability_drugs := random(1, 10);
            restock_obj := create_object_sid(41, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, random(5, 20));
            if (probability_drugs == 1) then begin
                restock_obj := create_object_sid(87, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            if (probability_drugs == 2) then begin
                restock_obj := create_object_sid(53, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            if (probability_drugs == 3) then begin
                restock_obj := create_object_sid(110, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            if (probability_drugs == 4) then begin
                restock_obj := create_object_sid(40, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            if (probability_drugs == 5) then begin
                restock_obj := create_object_sid(87, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            if (probability_drugs == 6) then begin
                restock_obj := create_object_sid(53, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            add_timer_event(Enemy, 1, 20);
        end
        if ((enemy_type == 16) or (enemy_type == 17) or (enemy_type == 18) or (enemy_type == 19) or (enemy_type == 20)) then begin
            if (not(obj_carrying_pid_obj(Enemy, 309))) then begin
                restock_obj := create_object_sid(309, 0, 0, -1);
                add_mult_objs_to_inven(Enemy, restock_obj, 1);
            end
            restock_obj := create_object_sid(40, 0, 0, -1);
            add_mult_objs_to_inven(Enemy, restock_obj, random(1, 2));
            add_timer_event(Enemy, 1, 20);
        end
    end
end

procedure choose_random_weapon_for_enemy
begin
    if ((enemy_type == 7) or (enemy_type == 8) or (enemy_type == 9) or (enemy_type == 10) or (enemy_type == 11) or (enemy_type == 12) or (enemy_type == 13) or (enemy_type == 14) or (enemy_type == 15)) then begin
        probability := random(1, 10);
        if (probability == 1) then begin
            item := 234;
        end
        if (probability == 2) then begin
            item := 8;
        end
        if (probability == 3) then begin
            item := 8;
        end
        if (probability == 4) then begin
            item := 18;
        end
        if ((probability == 5) and (no_smg == 0)) then begin
            item := 9;
        end
        else begin
            item := 21;
        end
        if ((probability == 6) and (no_rifle == 0)) then begin
            item := 10;
        end
        else begin
            item := 18;
        end
        if ((probability == 7) and (no_rifle == 0)) then begin
            item := 94;
        end
        else begin
            item := 21;
        end
        if ((probability == 8) and (no_rifle == 0)) then begin
            item := 94;
        end
        else begin
            item := 8;
        end
        if ((probability == 9) and (no_knife == 0)) then begin
            item := 4;
        end
        else begin
            item := 21;
        end
        if ((probability == 10) and (no_spear == 0)) then begin
            item := 280;
        end
        else begin
            item := 18;
        end
        no_smg := 0;
        no_knife := 0;
        no_spear := 0;
        no_rifle := 0;
    end
    else begin
        probability := random(1, 5);
        if (no_rifle == 0) then begin
            if (probability == 1) then begin
                item := 118;
            end
            if (probability == 2) then begin
                item := 143;
            end
            if (probability == 3) then begin
                item := 235;
            end
            if (probability == 4) then begin
                item := 115;
            end
            if (probability == 5) then begin
                item := 12;
            end
        end
        else begin
            if (probability == 1) then begin
                item := 23;
            end
            if (probability == 2) then begin
                item := 23;
            end
            if (probability == 3) then begin
                item := 143;
            end
            if (probability == 4) then begin
                item := 242;
            end
            if (probability == 5) then begin
                item := 242;
            end
        end
        no_rifle := 0;
    end
end

procedure generate_fourth_guard
begin
    if (replacing_guard_ID == 1) then begin
        if (((global_var(911) bwand 4) != 0) or ((global_var(911) bwand 16) != 0)) then begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777797, 19497, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777797, 18496, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777797, 22306, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777797, 17485, 0, 23);
            end
        end
        else begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777799, 19497, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777799, 18496, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777799, 22306, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777799, 17485, 0, 23);
            end
        end
    end
    if (replacing_guard_ID == 2) then begin
        if (((global_var(911) bwand 4) != 0) or ((global_var(911) bwand 16) != 0)) then begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777797, 22098, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777797, 21105, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777797, 20108, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777797, 17893, 0, 23);
            end
        end
        else begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777799, 22098, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777799, 21105, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777799, 20108, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777799, 17893, 0, 23);
            end
        end
    end
    if (replacing_guard_ID == 3) then begin
        if (((global_var(911) bwand 4) != 0) or ((global_var(911) bwand 16) != 0)) then begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777797, 20708, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777797, 19113, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777797, 22716, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777797, 19705, 0, 23);
            end
        end
        else begin
            if (cur_map_index == 103) then begin
                Karavan_Guard4 := create_object_sid(16777799, 20708, 0, 23);
            end
            if (cur_map_index == 104) then begin
                Karavan_Guard4 := create_object_sid(16777799, 19113, 0, 23);
            end
            if (cur_map_index == 105) then begin
                Karavan_Guard4 := create_object_sid(16777799, 22716, 0, 23);
            end
            if (cur_map_index == 106) then begin
                Karavan_Guard4 := create_object_sid(16777799, 19705, 0, 23);
            end
        end
    end
    if (cur_map_index == 103) then begin
        anim(Karavan_Guard4, 1000, 5);
    end
    if (cur_map_index == 104) then begin
        anim(Karavan_Guard4, 1000, 0);
    end
    if (cur_map_index == 105) then begin
        anim(Karavan_Guard4, 1000, 1);
    end
    if (cur_map_index == 106) then begin
        anim(Karavan_Guard4, 1000, 1);
    end
    call choose_random_weapon_for_caravan();
    restock_obj := create_object_sid(item, 0, 0, -1);
    add_mult_objs_to_inven(Karavan_Guard4, restock_obj, 1);
    restock_obj := create_object_sid(40, 0, 0, -1);
    add_mult_objs_to_inven(Karavan_Guard4, restock_obj, 1);
    restock_obj := create_object_sid(41, 0, 0, -1);
    add_mult_objs_to_inven(Karavan_Guard4, restock_obj, random(10, 50));
end

