variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Node2150;
procedure Node2200;
procedure Node2250;
procedure Node2300;
procedure Node2350;

import variable sg_tealc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    sg_tealc := self_obj;
end

procedure critter_p_proc
begin
    if ((map_var(1) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_map_var(1, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    start_gdialog(1589, self_obj, 4, -1, -1);
    gsay_start;
    call Node500();
    gsay_end;
    end_dialogue;
    set_local_var(4, 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(1589, 150));
    end
    else begin
        display_msg(message_str(1589, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(1589, 250));
    end
    else begin
        display_msg(message_str(1589, 200));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_map_var(1, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 285);
    critter_add_trait(self_obj, 1, 5, 3);
    metarule3(100, self_obj, 1, 0);
    add_timer_event(self_obj, game_ticks(random(18, 24)), 1);
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if ((map_var(2) == 0) and not(combat_is_initialized)) then begin
            float_msg(self_obj, message_str(1589, random(300, 302)), 8);
        end
        metarule3(100, self_obj, 1, 0);
        add_timer_event(self_obj, game_ticks(random(18, 24)), 1);
    end
end

procedure Node998
begin
    set_map_var(1, 1);
end

procedure Node999
begin
end

procedure Node500
begin
    gsay_reply(1589, 500);
    giq_option(4, 1589, 501, Node550, 50);
    giq_option(4, 1589, 502, Node600, 50);
    giq_option(4, 1589, 503, Node650, 50);
    giq_option(-3, 1589, 504, Node700, 50);
    giq_option(4, 1589, 505, Node999, 50);
end

procedure Node550
begin
    gsay_reply(1589, 550);
    giq_option(4, 1589, 551, Node750, 50);
    giq_option(4, 1589, 552, Node800, 50);
    giq_option(-3, 1589, 553, Node700, 50);
end

procedure Node600
begin
    gsay_reply(1589, 600);
    giq_option(4, 1589, 601, Node999, 50);
    giq_option(4, 1589, 602, Node850, 50);
end

procedure Node650
begin
    gsay_reply(1589, 650);
    giq_option(4, 1589, 651, Node900, 50);
    giq_option(4, 1589, 652, Node950, 50);
    giq_option(4, 1589, 653, Node1000, 50);
end

procedure Node700
begin
    gsay_reply(1589, 700);
    giq_option(-3, 1589, 701, Node550, 50);
    giq_option(-3, 1589, 702, Node1050, 50);
    giq_option(-3, 1589, 703, Node999, 50);
end

procedure Node750
begin
    gsay_reply(1589, 750);
    giq_option(4, 1589, 751, Node800, 50);
end

procedure Node800
begin
    gsay_reply(1589, 800);
    giq_option(4, 1589, 801, Node1050, 50);
    giq_option(4, 1589, 802, Node650, 50);
    giq_option(4, 1589, 803, Node1250, 50);
    giq_option(4, 1589, 804, Node999, 50);
end

procedure Node850
begin
    gsay_reply(1589, 850);
    giq_option(4, 1589, 851, Node1100, 50);
end

procedure Node900
begin
    gsay_reply(1589, 900);
    giq_option(4, 1589, 901, Node950, 50);
    giq_option(4, 1589, 902, Node1150, 50);
end

procedure Node950
begin
    gsay_reply(1589, 950);
    giq_option(4, 1589, 951, Node999, 50);
    giq_option(4, 1589, 952, Node1200, 50);
end

procedure Node1000
begin
    gsay_reply(1589, 1000);
    giq_option(4, 1589, 1001, Node999, 50);
end

procedure Node1050
begin
    gsay_reply(1589, 1050);
    giq_option(-3, 1589, 1051, Node700, 50);
    giq_option(4, 1589, 1052, Node1250, 50);
end

procedure Node1100
begin
    gsay_reply(1589, 1100);
    giq_option(4, 1589, 1101, Node1300, 50);
end

procedure Node1150
begin
    gsay_reply(1589, 1150);
    giq_option(4, 1589, 1151, Node1350, 50);
    giq_option(4, 1589, 1152, Node800, 50);
end

procedure Node1200
begin
    gsay_reply(1589, 1200);
    giq_option(4, 1589, 1201, Node1400, 50);
    giq_option(4, 1589, 1202, Node1450, 50);
end

procedure Node1250
begin
    gsay_reply(1589, 1250);
    giq_option(4, 1589, 1251, Node1750, 50);
    giq_option(4, 1589, 1252, Node800, 50);
end

procedure Node1300
begin
    gsay_reply(1589, 1300);
    giq_option(4, 1589, 1301, Node1200, 50);
end

procedure Node1350
begin
    gsay_reply(1589, 1350);
    giq_option(4, 1589, 1351, Node1500, 50);
    giq_option(4, 1589, 1352, Node1550, 50);
end

procedure Node1400
begin
    gsay_reply(1589, 1400);
    giq_option(5, 1589, 1401, Node1600, 50);
    giq_option(4, 1589, 1402, Node1650, 50);
    giq_option(4, 1589, 1403, Node1700, 50);
    giq_option(4, 1589, 1404, Node1450, 50);
end

procedure Node1450
begin
    gsay_reply(1589, 1450);
    giq_option(4, 1589, 1451, Node1250, 50);
    giq_option(4, 1589, 1452, Node1650, 50);
    giq_option(4, 1589, 1453, Node1800, 50);
    giq_option(4, 1589, 1454, Node1400, 50);
end

procedure Node1500
begin
    gsay_reply(1589, 1500);
    giq_option(4, 1589, 1501, Node800, 50);
end

procedure Node1550
begin
    gsay_reply(1589, 1550);
    giq_option(4, 1589, 1551, Node1850, 50);
end

procedure Node1600
begin
    gsay_reply(1589, 1600);
    giq_option(4, 1589, 1601, Node1700, 50);
end

procedure Node1650
begin
    gsay_reply(1589, 1650);
    giq_option(4, 1589, 1651, Node1800, 50);
    giq_option(4, 1589, 1652, Node1250, 50);
    giq_option(4, 1589, 1653, Node1900, 50);
end

procedure Node1700
begin
    gsay_reply(1589, 1700);
    giq_option(4, 1589, 1701, Node1950, 50);
    giq_option(4, 1589, 1702, Node999, 50);
end

procedure Node1750
begin
    gsay_reply(1589, 1750);
    giq_option(4, 1589, 1751 + (get_critter_stat(dude_obj, 34) == 1), Node999, 50);
end

procedure Node1800
begin
    gsay_reply(1589, 1800);
    giq_option(4, 1589, 1801, Node800, 50);
end

procedure Node1850
begin
    gsay_reply(1589, 1850);
    giq_option(4, 1589, 1851, Node1950, 50);
    giq_option(4, 1589, 1852, Node2000, 50);
end

procedure Node1900
begin
    gsay_reply(1589, 1900);
    giq_option(4, 1589, 1901, Node2050, 50);
    giq_option(4, 1589, 1902, Node2100, 50);
end

procedure Node1950
begin
    gsay_reply(1589, 1950);
    giq_option(4, 1589, 1951, Node2150, 50);
end

procedure Node2000
begin
    gsay_reply(1589, 2000);
    giq_option(4, 1589, 2001, Node2150, 50);
end

procedure Node2050
begin
    gsay_reply(1589, 2050);
    giq_option(4, 1589, 2051, Node2200, 50);
    giq_option(4, 1589, 2052, Node2250, 50);
end

procedure Node2100
begin
    gsay_reply(1589, 2100);
    giq_option(4, 1589, 2101, Node1700, 50);
    giq_option(4, 1589, 2102, Node999, 50);
end

procedure Node2150
begin
    gsay_reply(1589, 2150);
    giq_option(4, 1589, 2151, Node2300, 50);
end

procedure Node2200
begin
    set_map_var(0, 1);
    gsay_reply(1589, 2200);
    giq_option(4, 1589, 2201, Node2350, 50);
end

procedure Node2250
begin
    gsay_reply(1589, 2250);
    giq_option(4, 1589, 2251, Node999, 50);
end

procedure Node2300
begin
    gsay_reply(1589, 2300);
    giq_option(4, 1589, 2301, Node999, 50);
end

procedure Node2350
begin
    gsay_reply(1589, 2350);
    giq_option(4, 1589, 2351, Node999, 50);
end

