variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Node2150;
procedure Node2200;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((((obj_pid(critter_inven_obj(dude_obj, 0)) == 3) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 113) and (not((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) or (obj_pid(critter_inven_obj(party_member_obj(16777779), 0)) == 3) or (obj_pid(critter_inven_obj(party_member_obj(16777779), 0)) == 113)) and (not((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) or (obj_pid(critter_inven_obj(party_member_obj(16777811), 0)) == 3) or (obj_pid(critter_inven_obj(party_member_obj(16777811), 0)) == 113)) and (not((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) or (obj_pid(critter_inven_obj(party_member_obj(16777814), 0)) == 3) or (obj_pid(critter_inven_obj(party_member_obj(16777814), 0)) == 113)) and (global_var(930) == 0)) == 0) and not(game_ui_is_disabled) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((global_var(927) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(927, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    start_gdialog(402, self_obj, 4, -1, -1);
    gsay_start;
    if (((local_var(4) bwand 1) == 0) or ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3)) then begin
        call Node500();
    end
    else begin
        call Node1450();
    end
    gsay_end;
    end_dialogue;
end

procedure look_at_p_proc
begin
    script_overrides;
    if ((local_var(4) bwand 1) == 0) then begin
        display_msg(message_str(402, 100));
    end
    else begin
        display_msg(message_str(402, 150));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if ((local_var(4) bwand 1) == 0) then begin
        display_msg(message_str(402, 200));
    end
    else begin
        display_msg(message_str(402, 250));
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (global_var(942) == 3) then begin
            float_msg(self_obj, message_str(402, random(300, 306)), 8);
        end
        else begin
            float_msg(self_obj, message_str(402, random(300, 307)), 8);
        end
        metarule3(100, self_obj, 1, 0);
        add_timer_event(self_obj, game_ticks(random(30, 60)), 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 271);
    critter_add_trait(self_obj, 1, 5, 126);
    if ((global_var(953) >= 1) and (global_var(953) <= 3)) then begin
        destroy_object(self_obj);
    end
    metarule3(100, self_obj, 1, 0);
    add_timer_event(self_obj, game_ticks(random(30, 60)), 1);
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(927, 1);
    end
end

procedure destroy_p_proc
begin
end

procedure Node998
begin
    set_global_var(927, 1);
end

procedure Node999
begin
    anim(self_obj, 1000, 2);
end

procedure Node500
begin
    gsay_reply(402, 500);
    set_local_var(4, local_var(4) bwor 1);
    giq_option(4, 402, 501, Node550, 50);
    giq_option(4, 402, 502, Node999, 50);
    giq_option(-3, 402, 503, Node2100, 50);
    giq_option(-3, 402, 504, Node999, 50);
end

procedure Node550
begin
    gsay_reply(402, 550);
    set_global_var(944, 1);
    giq_option(4, 402, 551, Node600, 50);
    giq_option(4, 402, 552, Node1050, 50);
    giq_option(4, 402, 553, Node999, 50);
end

procedure Node600
begin
    gsay_reply(402, 600);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 402, 601, Node650, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 402, 601, Node1300, 50);
    end
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 602, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 603, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 603, Node1500, 50);
        end
    end
    giq_option(4, 402, 604, Node999, 50);
end

procedure Node650
begin
    gsay_reply(402, 650);
    if (global_var(791) == 3) then begin
        giq_option(4, 402, 651, Node750, 50);
    end
    else begin
        giq_option(4, 402, 651, Node700, 50);
    end
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 652, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 653, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 653, Node1500, 50);
        end
    end
    giq_option(4, 402, 654, Node999, 50);
end

procedure Node700
begin
    gsay_reply(402, 700);
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 701, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 702, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 702, Node1500, 50);
        end
    end
    giq_option(4, 402, 703, Node999, 50);
end

procedure Node750
begin
    gsay_reply(402, 750);
    giq_option(4, 402, 751, Node800, 50);
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 752, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 753, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 753, Node1500, 50);
        end
    end
    giq_option(4, 402, 754, Node999, 50);
end

procedure Node800
begin
    gsay_reply(402, 800);
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 801, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 802, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 802, Node1500, 50);
        end
    end
    giq_option(4, 402, 803, Node999, 50);
end

procedure Node850
begin
    gsay_reply(402, 850);
    set_local_var(4, local_var(4) bwor 2);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 402, 851, Node900, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 402, 851, Node1350, 50);
    end
end

procedure Node900
begin
    gsay_reply(402, 900);
    giq_option(4, 402, 901, Node1000, 50);
    giq_option(4, 402, 902, Node950, 50);
end

procedure Node950
begin
    gsay_reply(402, 950);
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 951, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 951, Node1500, 50);
        end
    end
    giq_option(4, 402, 952, Node999, 50);
end

procedure Node1000
begin
    gsay_reply(402, 1000);
    giq_option(4, 402, 1001, Node999, 50);
end

procedure Node1050
begin
    gsay_reply(402, 1050);
    set_local_var(4, local_var(4) bwor 4);
    set_global_var(942, 1);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 402, 1051, Node1100, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 402, 1051, Node1400, 50);
    end
    giq_option(4, 402, 1052, Node1150, 50);
end

procedure Node1100
begin
    gsay_reply(402, 1100);
    giq_option(4, 402, 1101, Node1200, 50);
    giq_option(4, 402, 1102, Node1250, 50);
    giq_option(4, 402, 1103, Node600, 50);
    giq_option(4, 402, 1104, Node999, 50);
end

procedure Node1150
begin
    gsay_reply(402, 1150);
    giq_option(4, 402, 1151, Node1200, 50);
    giq_option(4, 402, 1152, Node1250, 50);
    giq_option(4, 402, 1153, Node600, 50);
    giq_option(4, 402, 1154, Node999, 50);
end

procedure Node1200
begin
    gsay_reply(402, 1200);
    giq_option(4, 402, 1201, Node1250, 50);
    giq_option(4, 402, 1202, Node600, 50);
    giq_option(4, 402, 1203, Node999, 50);
end

procedure Node1250
begin
    gsay_reply(402, 1250);
    giq_option(4, 402, 1251, Node1200, 50);
    giq_option(4, 402, 1252, Node600, 50);
    giq_option(4, 402, 1253, Node999, 50);
end

procedure Node1300
begin
    gsay_reply(402, 1300);
    if (global_var(791) == 3) then begin
        giq_option(4, 402, 1301, Node750, 50);
    end
    else begin
        giq_option(4, 402, 1301, Node700, 50);
    end
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 402, 1302, Node850, 50);
    end
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 1303, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 1303, Node1500, 50);
        end
    end
    giq_option(4, 402, 1304, Node999, 50);
end

procedure Node1350
begin
    gsay_reply(402, 1350);
    giq_option(4, 402, 1351, Node1000, 50);
    giq_option(4, 402, 1352, Node950, 50);
end

procedure Node1400
begin
    gsay_reply(402, 1400);
    giq_option(4, 402, 1401, Node1200, 50);
    giq_option(4, 402, 1402, Node1250, 50);
    giq_option(4, 402, 1403, Node600, 50);
    giq_option(4, 402, 1404, Node999, 50);
end

procedure Node1450
begin
    gsay_reply(402, 1450);
    giq_option(4, 402, 1451, Node600, 50);
    if ((local_var(4) bwand 8) == 0) then begin
        if ((local_var(4) bwand 4) == 0) then begin
            giq_option(4, 402, 1452, Node1050, 50);
        end
        else begin
            giq_option(4, 402, 1452, Node1500, 50);
        end
    end
    if (global_var(942) == 2) then begin
        giq_option(4, 402, 1453 + (get_critter_stat(dude_obj, 34) == 1), Node1550, 50);
    end
    if (local_var(5) == 1) then begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 402, 1455, Node1800, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 402, 1455, Node1850, 50);
        end
    end
    if (local_var(5) == 2) then begin
        giq_option(4, 402, 1455, Node1900, 50);
    end
    if (local_var(5) == 3) then begin
        giq_option(4, 402, 1455, Node1950, 50);
    end
    if (local_var(5) == 4) then begin
        if (global_var(791) == 3) then begin
            giq_option(4, 402, 1455, Node2000, 50);
        end
        else begin
            giq_option(4, 402, 1455, Node2050, 50);
        end
    end
    if ((local_var(5) == 5) and (global_var(791) == 3) and ((local_var(4) bwand 16) == 0)) then begin
        giq_option(4, 402, 1455, Node2000, 50);
    end
    giq_option(4, 402, 1456, Node999, 50);
end

procedure Node1500
begin
    gsay_reply(402, 1500);
    giq_option(4, 402, 1501, Node600, 50);
    giq_option(4, 402, 1502, Node999, 50);
end

procedure Node1550
begin
    gsay_reply(402, 1550);
    set_local_var(4, local_var(4) bwor 8);
    set_global_var(942, 3);
    giq_option(4, 402, 1551, Node1600, 50);
end

procedure Node1600
begin
    gsay_reply(402, 1600);
    if ((get_critter_stat(dude_obj, 4) > 5) and (has_skill(dude_obj, 14) >= 60)) then begin
        giq_option(4, 402, 1601, Node1750, 50);
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            giq_option(4, 402, 1602, Node1650, 50);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            giq_option(4, 402, 1602, Node1700, 50);
        end
    end
end

procedure Node1650
begin
    gsay_reply(402, 1650);
    restock_obj := create_object_sid(544, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    giq_option(4, 402, 1651, Node999, 50);
end

procedure Node1700
begin
    gsay_reply(402, 1700);
    restock_obj := create_object_sid(544, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    giq_option(4, 402, 1701, Node999, 50);
end

procedure Node1750
begin
    gsay_reply(402, 1750);
    set_local_var(5, 1);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 402, 1751, Node1800, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 402, 1751, Node1850, 50);
    end
    giq_option(4, 402, 1752, Node999, 50);
end

procedure Node1800
begin
    gsay_reply(402, 1800);
    set_local_var(5, 2);
    giq_option(4, 402, 1801, Node1900, 50);
    giq_option(4, 402, 1802, Node999, 50);
end

procedure Node1850
begin
    gsay_reply(402, 1850);
    set_local_var(5, 2);
    giq_option(4, 402, 1851, Node1900, 50);
    giq_option(4, 402, 1852, Node999, 50);
end

procedure Node1900
begin
    gsay_reply(402, 1900);
    set_local_var(5, 3);
    giq_option(4, 402, 1901, Node1950, 50);
    giq_option(4, 402, 1902, Node999, 50);
end

procedure Node1950
begin
    gsay_reply(402, 1950);
    set_local_var(5, 4);
    if (global_var(791) == 3) then begin
        giq_option(4, 402, 1951, Node2000, 50);
    end
    else begin
        giq_option(4, 402, 1951, Node2050, 50);
    end
    giq_option(4, 402, 1952, Node999, 50);
end

procedure Node2000
begin
    gsay_reply(402, 2000);
    set_local_var(4, local_var(4) bwor 16);
    giq_option(4, 402, 2001, Node2050, 50);
    giq_option(4, 402, 2002, Node999, 50);
end

procedure Node2050
begin
    gsay_reply(402, 2050);
    set_local_var(5, 5);
    giq_option(4, 402, 2051, Node999, 50);
end

procedure Node2100
begin
    gsay_reply(402, 2100);
    giq_option(-3, 402, 2101, Node2150, 50);
    giq_option(-3, 402, 2102, Node2200, 50);
    giq_option(-3, 402, 2103, Node999, 50);
end

procedure Node2150
begin
    gsay_reply(402, 2150);
    giq_option(-3, 402, 2151, Node2200, 50);
    giq_option(-3, 402, 2152, Node999, 50);
end

procedure Node2200
begin
    gsay_reply(402, 2200 + (get_critter_stat(dude_obj, 34) == 1));
    critter_heal(dude_obj, random(1, 3));
    giq_option(-3, 402, 2202, Node999, 50);
end

