variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Prisoner_reaction;

variable dead_timer;

import variable Prisoner_1;
import variable Prisoner_2;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Prisoner_2 := self_obj;
end

procedure critter_p_proc
begin
    if ((global_var(949) == 1) and (dead_timer == 0)) then begin
        dead_timer := 1;
        add_timer_event(self_obj, game_ticks(random(2, 6)), 2);
    end
    if ((map_var(0) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_map_var(0, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    start_gdialog(439, self_obj, 4, -1, -1);
    gsay_start;
    if ((global_var(951) == 0) and (global_var(952) == 0)) then begin
        if ((obj_pid(critter_inven_obj(dude_obj, 0)) == 3) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 113)) then begin
            if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) > 3) then begin
                call Node500();
            end
            else begin
                call Node1000();
            end
        end
        else begin
            if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) > 3) then begin
                call Node950();
            end
            else begin
                call Node1250();
            end
        end
    end
    else begin
        if (global_var(952) == 0) then begin
            if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) > 3) then begin
                call Node750();
            end
            else begin
                call Node1200();
            end
        end
        else begin
            if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) > 3) then begin
                call Node800();
            end
            else begin
                call Node1350();
            end
        end
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    if ((global_var(949) != 1) and (global_var(952) != 2) and (global_var(951) != 2)) then begin
        if (source_obj == dude_obj) then begin
            set_global_var(5, global_var(5) + 1);
            if (metarule(51, self_obj) == 2) then begin
                if (source_obj == dude_obj) then begin
                    set_global_var(2, 0);
                    set_global_var(1, global_var(1) + 1);
                    set_global_var(0, global_var(0) + -15);
                    debug_msg("Player gains " + -15 + " Karma Points.");
                    set_global_var(37, 0);
                    set_global_var(38, 0);
                    set_global_var(39, 0);
                    set_global_var(40, 0);
                    set_global_var(41, 0);
                    set_global_var(42, 0);
                    set_global_var(43, 0);
                    set_global_var(44, 0);
                    set_global_var(45, 0);
                    if (global_var(0) >= 1000) then begin
                        set_global_var(37, 1);
                    end
                    else begin
                        if (global_var(0) >= 750) then begin
                            set_global_var(38, 1);
                        end
                        else begin
                            if (global_var(0) >= 500) then begin
                                set_global_var(39, 1);
                            end
                            else begin
                                if (global_var(0) >= 250) then begin
                                    set_global_var(40, 1);
                                end
                                else begin
                                    if (global_var(0) > -250) then begin
                                        set_global_var(41, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -500) then begin
                                            set_global_var(42, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -750) then begin
                                                set_global_var(43, 1);
                                            end
                                            else begin
                                                if (global_var(0) > -1000) then begin
                                                    set_global_var(44, 1);
                                                end
                                                else begin
                                                    set_global_var(45, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
                set_global_var(2, 1);
                set_global_var(3, 0);
            end
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
                set_global_var(3, 1);
                set_global_var(2, 0);
            end
            set_global_var(0, global_var(0) + -10);
            debug_msg("Player gains " + -10 + " Karma Points.");
            set_global_var(37, 0);
            set_global_var(38, 0);
            set_global_var(39, 0);
            set_global_var(40, 0);
            set_global_var(41, 0);
            set_global_var(42, 0);
            set_global_var(43, 0);
            set_global_var(44, 0);
            set_global_var(45, 0);
            if (global_var(0) >= 1000) then begin
                set_global_var(37, 1);
            end
            else begin
                if (global_var(0) >= 750) then begin
                    set_global_var(38, 1);
                end
                else begin
                    if (global_var(0) >= 500) then begin
                        set_global_var(39, 1);
                    end
                    else begin
                        if (global_var(0) >= 250) then begin
                            set_global_var(40, 1);
                        end
                        else begin
                            if (global_var(0) > -250) then begin
                                set_global_var(41, 1);
                            end
                            else begin
                                if (global_var(0) > -500) then begin
                                    set_global_var(42, 1);
                                end
                                else begin
                                    if (global_var(0) > -750) then begin
                                        set_global_var(43, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -1000) then begin
                                            set_global_var(44, 1);
                                        end
                                        else begin
                                            set_global_var(45, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(439, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(439, 200));
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        dialogue_system_enter;
    end
    if (fixed_param == 2) then begin
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 20, -1);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, game_ticks(1), 3);
    end
    if (fixed_param == 3) then begin
        kill_critter(self_obj, 20);
    end
    if (fixed_param == 4) then begin
        if ((global_var(951) == 0) and (global_var(952) == 0)) then begin
            if ((tile_distance_objs(self_obj, dude_obj) <= 4) and not((obj_pid(critter_inven_obj(dude_obj, 0)) == 3) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 113))) then begin
                float_msg(self_obj, message_str(439, random(300, 303)), 8);
                metarule3(100, self_obj, 4, 0);
                add_timer_event(self_obj, game_ticks(random(3, 7)), 4);
            end
            else begin
                metarule3(100, self_obj, 4, 0);
                add_timer_event(self_obj, game_ticks(1), 4);
            end
        end
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_map_var(0, 1);
        set_global_var(927, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 276);
    critter_add_trait(self_obj, 1, 5, 2);
    metarule3(100, self_obj, 4, 0);
    add_timer_event(self_obj, game_ticks(1), 4);
end

procedure map_update_p_proc
begin
    if ((global_var(952) == 2) or (global_var(951) == 2) and (elevation(dude_obj) == 0)) then begin
        destroy_object(self_obj);
    end
end

procedure Node999
begin
    anim(self_obj, 1000, 0);
end

procedure Node500
begin
    gsay_reply(439, 500);
    giq_option(4, 439, 501, Node550, 50);
    giq_option(4, 439, 502, Node999, 50);
end

procedure Node550
begin
    gsay_reply(439, 550);
    giq_option(4, 439, 551, Node600, 50);
    giq_option(4, 439, 552, Node999, 50);
end

procedure Node600
begin
    gsay_reply(439, 600 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(4, 439, 602, Node650, 50);
end

procedure Node650
begin
    gsay_reply(439, 650);
    giq_option(4, 439, 651, Node700, 50);
end

procedure Node700
begin
    gsay_reply(439, 700);
    set_global_var(952, 1);
    giq_option(4, 439, 701, Prisoner_reaction, 50);
end

procedure Node750
begin
    gsay_reply(439, 750);
    set_local_var(4, local_var(4) bwor 1);
    giq_option(4, 439, 751, Node700, 50);
end

procedure Node800
begin
    gsay_reply(439, 800 + (get_critter_stat(dude_obj, 34) == 1));
    if ((local_var(4) bwand 1) == 0) then begin
        giq_option(4, 439, 802, Node850, 50);
    end
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 439, 803, Node900, 50);
    end
    giq_option(4, 439, 804, Node999, 50);
end

procedure Node850
begin
    gsay_reply(439, 850);
    set_local_var(4, local_var(4) bwor 1);
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(4, 439, 851, Node900, 50);
    end
    giq_option(4, 439, 852, Node999, 50);
end

procedure Node900
begin
    gsay_reply(439, 900 + (get_critter_stat(dude_obj, 34) == 1));
    set_local_var(4, local_var(4) bwor 2);
    if ((local_var(4) bwand 1) == 0) then begin
        giq_option(4, 439, 902, Node850, 50);
    end
    giq_option(4, 439, 903, Node999, 50);
end

procedure Node950
begin
    gsay_reply(439, 950 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(4, 439, 952, Node650, 50);
end

procedure Node1000
begin
    gsay_reply(439, 1000);
    giq_option(-3, 439, 1001, Node1050, 50);
    giq_option(-3, 439, 1002, Node999, 50);
end

procedure Node1050
begin
    gsay_reply(439, 1050 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(-3, 439, 1052, Node1100, 50);
end

procedure Node1100
begin
    gsay_reply(439, 1100);
    giq_option(-3, 439, 1101, Node1150, 50);
end

procedure Node1150
begin
    gsay_reply(439, 1150);
    set_global_var(952, 1);
    giq_option(-3, 439, 1151, Prisoner_reaction, 50);
end

procedure Node1200
begin
    gsay_reply(439, 1200);
    set_local_var(4, local_var(4) bwor 1);
    giq_option(-3, 439, 1201, Node1150, 50);
end

procedure Node1250
begin
    gsay_reply(439, 1250 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(-3, 439, 1252, Node1300, 50);
end

procedure Node1300
begin
    gsay_reply(439, 1300 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(-3, 439, 1302, Node1150, 50);
end

procedure Node1350
begin
    gsay_reply(439, 1350);
    if ((local_var(4) bwand 1) == 0) then begin
        giq_option(-3, 439, 1351, Node1400, 50);
    end
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(-3, 439, 1352, Node1450, 50);
    end
    giq_option(-3, 439, 1353, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(439, 1400);
    set_local_var(4, local_var(4) bwor 1);
    if ((local_var(4) bwand 2) == 0) then begin
        giq_option(-3, 439, 1401, Node1450, 50);
    end
    giq_option(-3, 439, 1402, Node999, 50);
end

procedure Node1450
begin
    gsay_reply(439, 1450 + (get_critter_stat(dude_obj, 34) == 1));
    set_local_var(4, local_var(4) bwor 2);
    if ((local_var(4) bwand 1) == 0) then begin
        giq_option(-3, 439, 1452, Node1400, 50);
    end
    giq_option(-3, 439, 1453, Node999, 50);
end

procedure Prisoner_reaction
begin
    anim(self_obj, 1000, 0);
    if (global_var(951) == 0) then begin
        add_timer_event(Prisoner_1, 1, 1);
    end
    else begin
        if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
            set_global_var(1015, global_var(1015) bwor 8388608);
        end
        if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
            set_global_var(1018, global_var(1018) bwor 134217728);
        end
        if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
            set_global_var(1020, global_var(1020) bwor 16384);
        end
    end
end

