variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150a;
procedure Node1150b;
procedure Node1150c;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure PayDrink;
procedure NodeBeer;
procedure NodeBooze;
procedure NodeRum;

variable Projed_Smycku;
variable counter;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((item_caps_total(self_obj) <= 250) and (global_var(800) == 5)) then begin
        set_global_var(800, 6);
        set_global_var(49, global_var(49) + 3);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    if (local_var(6) == 1) then begin
        float_msg(self_obj, message_str(1478, 300), 2);
        anim(self_obj, 1000, 2);
        Projed_Smycku := 1;
    end
    if ((global_var(804) == 8) or (global_var(804) == 3) and (Projed_Smycku == 0)) then begin
        start_gdialog(1478, self_obj, 4, -1, -1);
        gsay_start;
        call Node900();
        gsay_end;
        end_dialogue;
        set_local_var(5, 1);
        Projed_Smycku := 1;
    end
    if ((local_var(5) != 1) and (Projed_Smycku == 0)) then begin
        start_gdialog(1478, self_obj, 4, -1, -1);
        gsay_start;
        call Node500();
        gsay_end;
        end_dialogue;
        set_local_var(5, 1);
        Projed_Smycku := 1;
    end
    if ((local_var(5) == 1) and (Projed_Smycku == 0)) then begin
        start_gdialog(1478, self_obj, 4, -1, -1);
        gsay_start;
        call Node550();
        gsay_end;
        end_dialogue;
        Projed_Smycku := 1;
    end
    Projed_Smycku := 0;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(49, global_var(49) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + 0);
        debug_msg("Player gains " + 0 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(49, global_var(49) - 3);
    if (global_var(800) == 5) then begin
        set_global_var(800, 6);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_msg(message_str(1478, 100));
    end
    else begin
        display_msg(message_str(1478, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if ((local_var(7) != 1) and (local_var(6) != 1)) then begin
        display_msg(message_str(1478, 200));
    end
    if ((local_var(7) == 1) or (local_var(6) == 1)) then begin
        display_msg(message_str(1478, 201));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(820, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 56);
    critter_add_trait(self_obj, 1, 5, 24);
    if (local_var(11) >= 1) then begin
        add_timer_event(self_obj, 1, 1);
    end
    counter := local_var(11);
    if (not(metarule(22, 0))) then begin
        if (global_var(801) == 4) then begin
            set_local_var(4, 0);
        end
        if ((global_var(800) == 5) and (local_var(10) != 1)) then begin
            item_caps_adjust(self_obj, 450);
            set_local_var(10, 1);
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and (local_var(11) >= 1) and not(combat_is_initialized)) then begin
        if ((game_time - local_var(12)) > (24 * (60 * (60 * 10)) * 1)) then begin
            set_local_var(11, 0);
            counter := 0;
        end
        else begin
            add_timer_event(self_obj, 1, 1);
        end
    end
end

procedure Node998
begin
    set_local_var(4, 1);
end

procedure Node999
begin
    anim(self_obj, 1000, 2);
end

procedure Node500
begin
    gsay_reply(1478, 500);
    giq_option(4, 1478, 501, Node600, 50);
    if ((global_var(800) == 5) and (local_var(9) != 1) and (global_var(803) != 8) and (global_var(798) == 0)) then begin
        giq_option(4, 1478, 503, Node950, 50);
    end
    giq_option(4, 1478, 502, Node650, 50);
    giq_option(-3, 1478, 504, Node600, 50);
    giq_option(-3, 1478, 505, Node650, 50);
end

procedure Node550
begin
    gsay_reply(1478, 550);
    if (local_var(11) < 5) then begin
        giq_option(4, 1478, 551, Node600, 50);
    end
    if (local_var(11) >= 5) then begin
        giq_option(4, 1478, 551, Node1500, 50);
    end
    if ((global_var(800) == 5) and (local_var(9) != 1) and (global_var(803) != 8) and (global_var(798) == 0)) then begin
        giq_option(4, 1478, 553, Node950, 50);
    end
    giq_option(4, 1478, 552, Node999, 50);
    if (local_var(11) < 5) then begin
        giq_option(-3, 1478, 554, Node600, 50);
    end
    if (local_var(11) >= 5) then begin
        giq_option(-3, 1478, 554, Node1500, 50);
    end
    giq_option(-3, 1478, 555, Node999, 50);
end

procedure Node600
begin
    if ((local_var(7) != 1) and not((global_var(804) == 8) or (global_var(804) == 3))) then begin
        gsay_reply(1478, 600);
    end
    if ((local_var(7) == 1) and not((global_var(804) == 8) or (global_var(804) == 3))) then begin
        gsay_reply(1478, 601);
    end
    if ((global_var(804) == 8) or (global_var(804) == 3)) then begin
        gsay_reply(1478, 611);
    end
    if ((local_var(8) != 1) and (get_critter_stat(dude_obj, 3) > 4) and not((global_var(804) == 8) or (global_var(804) == 3))) then begin
        giq_option(8, 1478, 610, Node800, 50);
    end
    if ((local_var(8) != 1) and (get_critter_stat(dude_obj, 3) < 5) and not((global_var(804) == 8) or (global_var(804) == 3))) then begin
        giq_option(8, 1478, 610, Node750, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(4, 1478, 602, NodeBeer, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(4, 1478, 603, NodeBooze, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(4, 1478, 604, NodeRum, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(-3, 1478, 605, NodeBeer, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(-3, 1478, 606, NodeBooze, 50);
    end
    if ((item_caps_total(dude_obj) >= 20) or ((item_caps_total(dude_obj) >= 10) and (local_var(7) == 1)) or (global_var(804) == 3)) then begin
        giq_option(-3, 1478, 607, NodeRum, 50);
    end
    giq_option(4, 1478, 608, Node999, 50);
    giq_option(-3, 1478, 609, Node999, 50);
end

procedure Node650
begin
    gsay_reply(1478, 650);
    giq_option(1, 1478, 651, Node999, 50);
end

procedure Node700
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1478, 700);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(1478, 701);
    end
    set_local_var(11, counter);
    if (local_var(11) >= 1) then begin
        set_local_var(12, game_time);
        add_timer_event(self_obj, 1, 1);
    end
    giq_option(4, 1478, 702, Node999, 50);
    giq_option(-3, 1478, 703, Node999, 50);
end

procedure Node750
begin
    gsay_reply(1478, 750);
    set_local_var(8, 1);
    giq_option(4, 1478, 751, Node600, 50);
    giq_option(4, 1478, 752, Node999, 50);
end

procedure Node800
begin
    gsay_reply(1478, 800);
    set_local_var(8, 1);
    if ((has_skill(dude_obj, 14) >= 70) and (has_skill(dude_obj, 15) >= 40)) then begin
        giq_option(4, 1478, 803, Node850, 50);
    end
    giq_option(4, 1478, 801, Node600, 50);
    giq_option(4, 1478, 802, Node999, 50);
end

procedure Node850
begin
    gsay_reply(1478, 850);
    give_exp_points(100);
    display_msg(message_str(14, 100) + 100 + message_str(14, 101));
    set_local_var(7, 1);
    giq_option(4, 1478, 851, Node600, 50);
    giq_option(4, 1478, 852, Node999, 50);
end

procedure Node900
begin
    gsay_reply(1478, 900);
    if (local_var(11) < 5) then begin
        giq_option(4, 1478, 901, Node600, 50);
    end
    if (local_var(11) >= 5) then begin
        giq_option(4, 1478, 901, Node1500, 50);
    end
    giq_option(4, 1478, 902, Node999, 50);
    if (local_var(11) < 5) then begin
        giq_option(-3, 1478, 903, Node600, 50);
    end
    if (local_var(11) >= 5) then begin
        giq_option(-3, 1478, 903, Node1500, 50);
    end
    giq_option(-3, 1478, 904, Node999, 50);
end

procedure Node950
begin
    gsay_reply(1478, 950);
    set_local_var(9, 1);
    if (has_skill(dude_obj, 14) >= 80) then begin
        giq_option(4, 1478, 951, Node1000, 50);
    end
    if (has_skill(dude_obj, 14) < 80) then begin
        giq_option(4, 1478, 951, Node1050, 50);
    end
    if (has_skill(dude_obj, 14) >= 70) then begin
        giq_option(6, 1478, 952, Node1000, 50);
    end
    if (has_skill(dude_obj, 14) < 70) then begin
        giq_option(6, 1478, 952, Node1050, 50);
    end
    if ((get_critter_stat(dude_obj, 0) > 7) or has_trait(2, dude_obj, 1)) then begin
        giq_option(4, 1478, 953, Node1450, 50);
    end
    else begin
        giq_option(4, 1478, 953, Node1100, 50);
    end
    giq_option(4, 1478, 954, Node1350, 50);
end

procedure Node1000
begin
    gsay_reply(1478, 1000);
    giq_option(4, 1478, 1001, Node1150a, 50);
    if ((has_skill(dude_obj, 14) >= 75) and (item_caps_total(self_obj) >= 300)) then begin
        giq_option(4, 1478, 1002, Node1150b, 50);
    end
    if ((has_skill(dude_obj, 14) < 75) and (item_caps_total(self_obj) >= 300)) then begin
        giq_option(4, 1478, 1002, Node1200, 50);
    end
    giq_option(4, 1478, 1003, Node1250, 50);
end

procedure Node1050
begin
    gsay_reply(1478, 1050);
    set_local_var(6, 1);
    set_local_var(13, local_var(13) + 1);
    if (local_var(13) < 2) then begin
        if ((get_critter_stat(dude_obj, 0) > 7) or has_trait(2, dude_obj, 1)) then begin
            giq_option(4, 1478, 1054, Node1450, 50);
        end
        else begin
            giq_option(4, 1478, 1054, Node1100, 50);
        end
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1478, 1051, Node999, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1478, 1052, Node999, 50);
    end
    giq_option(4, 1478, 1053, Node998, 50);
end

procedure Node1100
begin
    gsay_reply(1478, 1100);
    set_local_var(6, 1);
    set_local_var(13, local_var(13) + 1);
    if (local_var(13) < 2) then begin
        if (has_skill(dude_obj, 14) >= 80) then begin
            giq_option(4, 1478, 1104, Node1000, 50);
        end
        if (has_skill(dude_obj, 14) < 80) then begin
            giq_option(4, 1478, 1104, Node1050, 50);
        end
        if (has_skill(dude_obj, 14) >= 70) then begin
            giq_option(6, 1478, 1105, Node1000, 50);
        end
        if (has_skill(dude_obj, 14) < 70) then begin
            giq_option(6, 1478, 1105, Node1050, 50);
        end
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1478, 1101, Node999, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1478, 1102, Node999, 50);
    end
    giq_option(4, 1478, 1103, Node998, 50);
end

procedure Node1150a
begin
    gsay_reply(1478, 1150);
    set_local_var(6, 1);
    set_global_var(800, 6);
    set_global_var(49, global_var(49) + 3);
    item_caps_adjust(dude_obj, 200);
    if (item_caps_total(self_obj) > 199) then begin
        item_caps_adjust(self_obj, -200);
    end
    else begin
        item_caps_adjust(self_obj, -item_caps_total(self_obj));
    end
    giq_option(4, 1478, 1151, Node999, 50);
end

procedure Node1150b
begin
    gsay_reply(1478, 1150);
    set_local_var(6, 1);
    set_global_var(800, 6);
    set_global_var(49, global_var(49) + 3);
    item_caps_adjust(dude_obj, 300);
    if (item_caps_total(self_obj) > 299) then begin
        item_caps_adjust(self_obj, -300);
    end
    else begin
        item_caps_adjust(self_obj, -item_caps_total(self_obj));
    end
    giq_option(4, 1478, 1151, Node999, 50);
end

procedure Node1150c
begin
    gsay_reply(1478, 1150);
    set_local_var(6, 1);
    set_global_var(800, 6);
    set_global_var(49, global_var(49) + 3);
    item_caps_adjust(dude_obj, item_caps_total(self_obj));
    item_caps_adjust(self_obj, -item_caps_total(self_obj));
    giq_option(4, 1478, 1151, Node999, 50);
end

procedure Node1200
begin
    gsay_reply(1478, 1200);
    giq_option(4, 1478, 1201, Node998, 50);
    giq_option(4, 1478, 1202, Node1150a, 50);
end

procedure Node1250
begin
    gsay_reply(1478, 1250);
    if (has_skill(dude_obj, 14) >= 80) then begin
        giq_option(4, 1478, 1251, Node1150c, 50);
    end
    if (has_skill(dude_obj, 14) < 80) then begin
        giq_option(4, 1478, 1251, Node1300, 50);
    end
    giq_option(4, 1478, 1252, Node999, 50);
end

procedure Node1300
begin
    gsay_reply(1478, 1300);
    set_local_var(6, 1);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1478, 1301, Node999, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1478, 1302, Node999, 50);
    end
    giq_option(4, 1478, 1303, Node998, 50);
end

procedure Node1350
begin
    gsay_reply(1478, 1350);
    giq_option(4, 1478, 1351, Node1400, 50);
    if (has_skill(dude_obj, 14) >= 80) then begin
        giq_option(4, 1478, 1352, Node1000, 50);
    end
    if (has_skill(dude_obj, 14) < 80) then begin
        giq_option(4, 1478, 1352, Node1050, 50);
    end
    if ((get_critter_stat(dude_obj, 0) > 7) or has_trait(2, dude_obj, 1)) then begin
        giq_option(4, 1478, 1353, Node1450, 50);
    end
    else begin
        giq_option(4, 1478, 1353, Node1100, 50);
    end
    giq_option(4, 1478, 1354, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(1478, 1400);
    set_local_var(6, 1);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 1478, 1401, Node999, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 1478, 1402, Node999, 50);
    end
    giq_option(4, 1478, 1403, Node998, 50);
end

procedure Node1450
begin
    gsay_reply(1478, 1450);
    giq_option(4, 1478, 1451, Node1150a, 50);
    if ((has_skill(dude_obj, 14) >= 35) and (item_caps_total(self_obj) >= 300)) then begin
        giq_option(4, 1478, 1452, Node1150b, 50);
    end
    if ((has_skill(dude_obj, 14) < 35) and (item_caps_total(self_obj) >= 300)) then begin
        giq_option(4, 1478, 1452, Node1200, 50);
    end
    giq_option(4, 1478, 1453, Node1250, 50);
end

procedure Node1500
begin
    gsay_reply(1478, 1500);
    giq_option(4, 1478, 1501, Node999, 50);
    giq_option(-3, 1478, 1502, Node999, 50);
end

procedure PayDrink
begin
    if ((global_var(804) == 8) or (global_var(804) == 3)) then begin
        Projed_Smycku := 1;
    end
    if (Projed_Smycku == 0) then begin
        if (local_var(7) != 1) then begin
            item_caps_adjust(dude_obj, -20);
        end
        else begin
            item_caps_adjust(dude_obj, -10);
        end
    end
    Projed_Smycku := 0;
end

procedure NodeBeer
begin
    restock_obj := create_object_sid(124, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    counter := counter + 1;
    call PayDrink();
    call Node700();
end

procedure NodeBooze
begin
    restock_obj := create_object_sid(125, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    counter := counter + 1;
    call PayDrink();
    call Node700();
end

procedure NodeRum
begin
    restock_obj := create_object_sid(311, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    counter := counter + 1;
    call PayDrink();
    call Node700();
end

