variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure David_status;

variable place;
variable dialog_loop;
variable police1;
variable police2;
variable police3;

import variable Chuva;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Chuva := self_obj;
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if (cur_map_index == 11) then begin
        if ((local_var(7) == 1) and ((game_time_hour >= 2300) or (game_time_hour <= 100)) and (has_trait(1, self_obj, 666) == 0)) then begin
            set_obj_visibility(self_obj, 0);
        end
        if (not((local_var(7) == 1) and ((game_time_hour >= 2300) or (game_time_hour <= 100)))) then begin
            if (has_trait(1, self_obj, 666) == 1) then begin
                set_obj_visibility(self_obj, 1);
            end
        end
    end
    if (global_var(769) == 1) then begin
        if (obj_can_see_obj(self_obj, dude_obj) or obj_can_hear_obj(self_obj, dude_obj)) then begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (cur_map_index == 10) then begin
        if (global_var(723) == 2) then begin
            anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(1360, self_obj, 4, -1, -1);
            gsay_start;
            if ((local_var(6) bwand 2) == 0) then begin
                call Node550();
            end
            else begin
                call Node1450();
            end
            gsay_end;
            end_dialogue;
            set_local_var(4, 1);
            dialog_loop := 1;
        end
        if ((global_var(723) > 2) and (dialog_loop == 0)) then begin
            if ((global_var(723) == 7) or (global_var(723) == 8)) then begin
                anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
                anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
                start_gdialog(1360, self_obj, 4, -1, -1);
                gsay_start;
                call Node1600();
                gsay_end;
                end_dialogue;
                set_local_var(4, 1);
            end
            else begin
                float_msg(self_obj, message_str(1360, 300), 8);
            end
            dialog_loop := 1;
        end
        if ((global_var(724) == 3) and (global_var(775) != 1) and (dialog_loop == 0)) then begin
            if (place == 2) then begin
                anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
                anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
                start_gdialog(1360, self_obj, 4, -1, -1);
                gsay_start;
                call Node500();
                gsay_end;
                end_dialogue;
                set_local_var(4, 1);
            end
            else begin
                float_msg(self_obj, message_str(1360, 303), 8);
            end
            dialog_loop := 1;
        end
        if (dialog_loop == 0) then begin
            anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(1360, self_obj, 4, -1, -1);
            gsay_start;
            call Node1600();
            gsay_end;
            end_dialogue;
            set_local_var(4, 1);
        end
        dialog_loop := 0;
    end
    if (cur_map_index == 11) then begin
        if ((local_var(6) bwand 256) == 0) then begin
            anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(1360, self_obj, 4, -1, -1);
            gsay_start;
            call Node1500();
            gsay_end;
            end_dialogue;
        end
        else begin
            float_msg(self_obj, message_str(1360, 302), 8);
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if ((local_var(4) == 1) or (cur_map_index == 11)) then begin
        display_msg(message_str(1360, 150));
    end
    else begin
        display_msg(message_str(1360, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if ((local_var(4) == 1) or (cur_map_index == 11)) then begin
        display_msg(message_str(1360, 250));
    end
    else begin
        display_msg(message_str(1360, 200));
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if ((global_var(723) != 0) and (global_var(723) != 7) and (party_member_obj(16777748) == 0) and (global_var(723) != 8)) then begin
            if (David_status() == 3) then begin
                place := 2;
                move_to(self_obj, 22650, 0);
                metarule3(100, self_obj, 1, 0);
                add_timer_event(self_obj, game_ticks(240), 1);
            end
        end
        else begin
            if ((game_time_hour >= 1200) and (game_time_hour <= 2000) and (David_status() == 3)) then begin
                if (place == 2) then begin
                    metarule3(100, self_obj, 1, 0);
                    add_timer_event(self_obj, game_ticks(240), 1);
                end
                else begin
                    place := 2;
                    move_to(self_obj, 22650, 0);
                    metarule3(100, self_obj, 1, 0);
                    add_timer_event(self_obj, game_ticks(240), 1);
                end
            end
            else begin
                if (place == 1) then begin
                    metarule3(100, self_obj, 1, 0);
                    add_timer_event(self_obj, game_ticks(240), 1);
                end
                else begin
                    place := 1;
                    move_to(self_obj, 21880, 0);
                    metarule3(100, self_obj, 1, 0);
                    add_timer_event(self_obj, game_ticks(240), 1);
                end
            end
        end
    end
    if (fixed_param == 10) then begin
        float_msg(self_obj, message_str(1360, 301), 8);
    end
    if (fixed_param == 11) then begin
        set_local_var(7, 1);
    end
    if (fixed_param == 12) then begin
        float_msg(self_obj, message_str(1360, 303), 8);
    end
end

procedure map_enter_p_proc
begin
    if (global_var(767) == 1) then begin
        destroy_object(self_obj);
    end
    if (cur_map_index == 11) then begin
        critter_add_trait(self_obj, 1, 6, 218);
    end
    else begin
        critter_add_trait(self_obj, 1, 6, 212);
    end
    critter_add_trait(self_obj, 1, 5, 27);
    if (cur_map_index == 10) then begin
        if (global_var(724) > 5) then begin
            set_obj_visibility(self_obj, 1);
        end
        else begin
            set_obj_visibility(self_obj, 0);
        end
        if ((global_var(723) != 0) and (global_var(723) != 7) and (party_member_obj(16777748) == 0) and (global_var(723) != 8)) then begin
            if (David_status() == 3) then begin
                place := 2;
                move_to(self_obj, 22650, 0);
            end
        end
        else begin
            if ((game_time_hour >= 1200) and (game_time_hour <= 2000) and (David_status() == 3)) then begin
                place := 2;
                move_to(self_obj, 22650, 0);
            end
            else begin
                place := 1;
                move_to(self_obj, 21880, 0);
            end
        end
        metarule3(100, self_obj, 1, 0);
        add_timer_event(self_obj, game_ticks(240), 1);
    end
end

procedure map_exit_p_proc
begin
    if (global_var(724) > 5) then begin
        set_local_var(7, 0);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
        if (cur_map_index == 10) then begin
            set_global_var(769, 1);
        end
    end
end

procedure destroy_p_proc
begin
    set_global_var(767, 1);
    if (global_var(724) == 6) then begin
        set_global_var(724, 7);
    end
    set_global_var(0, global_var(0) + -10);
    debug_msg("Player gains " + -10 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if ((global_var(724) >= 1) and (global_var(724) < 6)) then begin
        set_global_var(895, 1);
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    if (cur_map_index == 10) then begin
        if (place == 2) then begin
            anim(self_obj, 1000, 3);
        end
        if (place == 1) then begin
            anim(self_obj, 1000, 2);
        end
    end
end

procedure Node500
begin
    gsay_reply(1360, 500);
    set_local_var(6, local_var(6) bwor 1);
    giq_option(4, 1360, 501, Node999, 50);
    giq_option(-3, 1360, 502, Node999, 50);
end

procedure Node550
begin
    gsay_reply(1360, 550);
    giq_option(4, 1360, 551, Node600, 50);
    giq_option(-3, 1360, 552, Node999, 50);
end

procedure Node600
begin
    gsay_reply(1360, 600);
    set_local_var(6, local_var(6) bwor 2);
    giq_option(4, 1360, 601, Node650, 50);
end

procedure Node650
begin
    gsay_reply(1360, 650);
    giq_option(4, 1360, 651, Node700, 50);
end

procedure Node700
begin
    gsay_reply(1360, 700);
    if ((get_critter_stat(dude_obj, 1) > 6) and (get_critter_stat(dude_obj, 4) > 7)) then begin
        giq_option(4, 1360, 702, Node1400, 50);
    end
    else begin
        giq_option(4, 1360, 701, Node750, 50);
    end
end

procedure Node750
begin
    gsay_reply(1360, 750);
    giq_option(4, 1360, 751, Node800, 50);
    giq_option(4, 1360, 752, Node999, 50);
end

procedure Node800
begin
    gsay_reply(1360, 800);
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(4, 1360, 801, Node850, 50);
    end
    if ((local_var(6) bwand 8) == 0) then begin
        giq_option(4, 1360, 802, Node900, 50);
    end
    if (((local_var(6) bwand 32) == 0) and ((local_var(6) bwand 4) != 0) and ((local_var(6) bwand 8) != 0)) then begin
        giq_option(4, 1360, 803, Node1000, 50);
    end
    if (((local_var(6) bwand 64) == 0) and ((local_var(6) bwand 4) != 0)) then begin
        giq_option(4, 1360, 804, Node1050, 50);
    end
    if (((local_var(6) bwand 16) == 0) and ((local_var(6) bwand 8) != 0)) then begin
        giq_option(4, 1360, 805, Node950, 50);
    end
    if (((local_var(6) bwand 128) == 0) and ((local_var(6) bwand 16) != 0) and ((local_var(6) bwand 32) != 0)) then begin
        giq_option(4, 1360, 806, Node1150, 50);
    end
    if (((local_var(6) bwand 64) != 0) and ((local_var(6) bwand 128) != 0)) then begin
        giq_option(4, 1360, 807, Node1200, 50);
    end
    giq_option(4, 1360, 808, Node999, 50);
end

procedure Node850
begin
    gsay_reply(1360, 850);
    set_local_var(6, local_var(6) bwor 4);
    giq_option(4, 1360, 851, Node800, 50);
    giq_option(4, 1360, 852, Node999, 50);
end

procedure Node900
begin
    gsay_reply(1360, 900);
    set_local_var(6, local_var(6) bwor 8);
    giq_option(4, 1360, 901, Node800, 50);
    giq_option(4, 1360, 902, Node999, 50);
end

procedure Node950
begin
    gsay_reply(1360, 950);
    set_local_var(6, local_var(6) bwor 16);
    giq_option(4, 1360, 951, Node800, 50);
    giq_option(4, 1360, 952, Node999, 50);
end

procedure Node1000
begin
    gsay_reply(1360, 1000);
    set_local_var(6, local_var(6) bwor 32);
    giq_option(4, 1360, 1001, Node800, 50);
    giq_option(4, 1360, 1002, Node999, 50);
end

procedure Node1050
begin
    gsay_reply(1360, 1050);
    giq_option(4, 1360, 1051, Node1100, 50);
end

procedure Node1100
begin
    gsay_reply(1360, 1100);
    set_local_var(6, local_var(6) bwor 64);
    giq_option(4, 1360, 1101, Node800, 50);
    giq_option(4, 1360, 1102, Node999, 50);
end

procedure Node1150
begin
    gsay_reply(1360, 1150);
    set_local_var(6, local_var(6) bwor 128);
    giq_option(4, 1360, 1151, Node800, 50);
    giq_option(4, 1360, 1152, Node999, 50);
end

procedure Node1200
begin
    gsay_reply(1360, 1200);
    giq_option(4, 1360, 1201, Node1250, 50);
end

procedure Node1250
begin
    gsay_reply(1360, 1250);
    set_global_var(723, 3);
    giq_option(4, 1360, 1251, Node1300, 50);
end

procedure Node1300
begin
    gsay_reply(1360, 1300);
    giq_option(4, 1360, 1301, Node1350, 50);
end

procedure Node1350
begin
    gsay_reply(1360, 1350);
    giq_option(4, 1360, 1351, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(1360, 1400);
    giq_option(4, 1360, 1401, Node1250, 50);
end

procedure Node1450
begin
    gsay_reply(1360, 1450);
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(4, 1360, 1451, Node850, 50);
    end
    if ((local_var(6) bwand 8) == 0) then begin
        giq_option(4, 1360, 1452, Node900, 50);
    end
    if (((local_var(6) bwand 32) == 0) and ((local_var(6) bwand 4) != 0) and ((local_var(6) bwand 8) != 0)) then begin
        giq_option(4, 1360, 1453, Node1000, 50);
    end
    if (((local_var(6) bwand 64) == 0) and ((local_var(6) bwand 4) != 0)) then begin
        giq_option(4, 1360, 1454, Node1050, 50);
    end
    if (((local_var(6) bwand 16) == 0) and ((local_var(6) bwand 8) != 0)) then begin
        giq_option(4, 1360, 1455, Node950, 50);
    end
    if (((local_var(6) bwand 128) == 0) and ((local_var(6) bwand 16) != 0) and ((local_var(6) bwand 32) != 0)) then begin
        giq_option(4, 1360, 1456, Node1150, 50);
    end
    if (((local_var(6) bwand 64) != 0) and ((local_var(6) bwand 128) != 0)) then begin
        giq_option(4, 1360, 1457, Node1200, 50);
    end
    giq_option(4, 1360, 1458, Node999, 50);
    giq_option(-3, 1360, 1459, Node999, 50);
end

procedure Node1500
begin
    gsay_reply(1360, 1500);
    set_local_var(6, local_var(6) bwor 256);
    set_global_var(724, 6);
    give_exp_points(500);
    display_msg(message_str(14, 100) + 500 + message_str(14, 101));
    giq_option(4, 1360, 1501, Node1550, 50);
    giq_option(-3, 1360, 1502, Node1550, 50);
end

procedure Node1550
begin
    gsay_reply(1360, 1550);
    police1 := create_object_sid(16777752, 14509, 0, 1422);
    police2 := create_object_sid(16777752, 14110, 0, 1422);
    police3 := create_object_sid(16777754, 14710, 0, 1422);
    critter_add_trait(police1, 1, 6, 218);
    critter_add_trait(police1, 1, 5, 146);
    critter_add_trait(police2, 1, 6, 218);
    critter_add_trait(police2, 1, 5, 146);
    critter_add_trait(police3, 1, 6, 218);
    critter_add_trait(police3, 1, 5, 146);
    restock_obj := create_object_sid(242, 0, 0, -1);
    add_mult_objs_to_inven(police1, restock_obj, 1);
    if (obj_carrying_pid_obj(police1, 242)) then begin
        wield_obj_critter(police1, obj_carrying_pid_obj(police1, 242));
    end
    restock_obj := create_object_sid(8, 0, 0, -1);
    add_mult_objs_to_inven(police2, restock_obj, 1);
    if (obj_carrying_pid_obj(police2, 8)) then begin
        wield_obj_critter(police2, obj_carrying_pid_obj(police2, 8));
    end
    restock_obj := create_object_sid(236, 0, 0, -1);
    add_mult_objs_to_inven(police3, restock_obj, 1);
    if (obj_carrying_pid_obj(police3, 236)) then begin
        wield_obj_critter(police3, obj_carrying_pid_obj(police3, 236));
    end
    giq_option(4, 1360, 1551, Node999, 50);
    giq_option(-3, 1360, 1552, Node999, 50);
end

procedure Node1600
begin
    gsay_reply(1360, 1600);
    if ((get_critter_stat(dude_obj, 34) == 0) and ((local_var(6) bwand 512) == 0) and ((local_var(6) bwand 1) == 0) and ((local_var(6) bwand 2) == 0)) then begin
        giq_option(4, 1360, 1601, Node1650, 50);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and ((local_var(6) bwand 1024) == 0) and ((local_var(6) bwand 1) == 0) and ((local_var(6) bwand 2) == 0)) then begin
        giq_option(4, 1360, 1601, Node1700, 50);
    end
    giq_option(4, 1360, 1602, Node999, 50);
    giq_option(-3, 1360, 1603, Node999, 50);
end

procedure Node1650
begin
    gsay_reply(1360, 1650);
    set_local_var(6, local_var(6) bwor 512);
    giq_option(4, 1360, 1651, Node999, 50);
end

procedure Node1700
begin
    gsay_reply(1360, 1700);
    set_local_var(6, local_var(6) bwor 1024);
    giq_option(4, 1360, 1701, Node999, 50);
end

procedure David_status
begin
    if ((global_var(723) == 0) or (global_var(723) == 7) or (global_var(723) == 8) or (global_var(724) < 4)) then begin
        return 3;
    end
    else begin
        return 4;
    end
end

