variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure Node998;
procedure Node999;
procedure Node999swap;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Node2150;
procedure ThrowOutFromShop;
procedure Buy_elvis;
procedure Buy_nixon;
procedure Buy_cats_paw;
procedure Buy_rubber_doll;
procedure Buy_talisman;
procedure Barter;
procedure Open_hours;
procedure Time_check;

variable time1;
variable time2;
variable dude_seen;

import variable salem;
import variable salem_table_trade;
import variable salem_table_swap;
import variable salem_door;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    salem := self_obj;
end

procedure critter_p_proc
begin
    if (local_var(16) == 1) then begin
        if (obj_can_see_obj(self_obj, dude_obj) and (combat_is_initialized == 0) and (dude_seen != 1)) then begin
            dude_seen := 1;
            dialogue_system_enter;
        end
    end
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        salem := -1;
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if (global_var(769) == 1) then begin
        if (obj_can_see_obj(self_obj, dude_obj) or obj_can_hear_obj(self_obj, dude_obj)) then begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (local_var(16) == 1) then begin
        anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
        start_gdialog(1356, self_obj, 4, -1, -1);
        gsay_start;
        call Node2150();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (local_var(4) != 1) then begin
            anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(1356, self_obj, 4, -1, -1);
            gsay_start;
            if (get_critter_stat(dude_obj, 34) == 0) then begin
                call Node500();
            end
            if (get_critter_stat(dude_obj, 34) == 1) then begin
                call Node750();
            end
            gsay_end;
            end_dialogue;
            set_local_var(4, 1);
        end
        else begin
            anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
            start_gdialog(1356, self_obj, 4, -1, -1);
            gsay_start;
            if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
                call Node950();
            end
            else begin
                if (local_var(6) == 1) then begin
                    call Node950();
                end
                else begin
                    if (get_critter_stat(dude_obj, 34) == 0) then begin
                        call Node850();
                    end
                    if (get_critter_stat(dude_obj, 34) == 1) then begin
                        call Node900();
                    end
                end
            end
            gsay_end;
            end_dialogue;
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(1356, 150));
    end
    else begin
        display_msg(message_str(1356, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(1356, 250));
    end
    else begin
        display_msg(message_str(1356, 200));
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        time1 := game_time_hour;
        metarule3(100, self_obj, 2, 0);
        add_timer_event(self_obj, game_ticks(60), 2);
    end
    if (fixed_param == 2) then begin
        time2 := game_time_hour;
        if (((time2 - time1) > 15) or ((time2 - time1) < -15)) then begin
            call Time_check();
        end
        metarule3(100, self_obj, 1, 0);
        add_timer_event(self_obj, game_ticks(1), 1);
    end
    if (fixed_param == 10) then begin
        dialogue_system_enter;
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 212);
    critter_add_trait(self_obj, 1, 5, 17);
    if (metarule(14, 0)) then begin
        if (not(metarule(22, 0))) then begin
            set_local_var(9, 1051);
            set_local_var(10, 1052);
            set_local_var(11, 1053);
            set_local_var(12, 1054);
            set_local_var(13, 1055);
            set_local_var(14, 1705);
        end
    end
    if (not(metarule(22, 0))) then begin
        call Time_check();
    end
    metarule3(100, self_obj, 1, 0);
    add_timer_event(self_obj, game_ticks(1), 1);
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
        set_global_var(769, 1);
    end
end

procedure destroy_p_proc
begin
    salem := -1;
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(48, global_var(48) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(48, global_var(48) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    anim(self_obj, 1000, 3);
end

procedure Node999swap
begin
    move_obj_inven_to_obj(salem, salem_table_trade);
    move_obj_inven_to_obj(salem_table_swap, salem);
    anim(self_obj, 1000, 3);
end

procedure Node500
begin
    gsay_reply(1356, 500);
    giq_option(4, 1356, 501, Node550, 50);
    giq_option(4, 1356, 502, Node999, 50);
    giq_option(-3, 1356, 503, Node650, 50);
end

procedure Node550
begin
    gsay_reply(1356, 550);
    giq_option(4, 1356, 551, Node600, 50);
end

procedure Node600
begin
    gsay_reply(1356, 600);
    set_local_var(6, 1);
    giq_option(4, 1356, 601, Barter, 50);
    giq_option(4, 1356, 602, Node1050, 50);
    giq_option(4, 1356, 603, Node999, 50);
end

procedure Node650
begin
    gsay_reply(1356, 650);
    giq_option(-3, 1356, 651, Node700, 50);
end

procedure Node700
begin
    gsay_reply(1356, 700);
    giq_option(-3, 1356, 701, Barter, 50);
    giq_option(-3, 1356, 702, Node1700, 50);
    giq_option(-3, 1356, 703, Node999, 50);
end

procedure Node750
begin
    gsay_reply(1356, 750);
    giq_option(4, 1356, 751, Node800, 50);
    giq_option(4, 1356, 752, Node999, 50);
    giq_option(-3, 1356, 753, Node650, 50);
end

procedure Node800
begin
    gsay_reply(1356, 800);
    giq_option(4, 1356, 801, Node600, 50);
end

procedure Node850
begin
    gsay_reply(1356, 850);
    giq_option(4, 1356, 851, Node550, 50);
    giq_option(4, 1356, 852, Node999, 50);
end

procedure Node900
begin
    gsay_reply(1356, 900);
    giq_option(4, 1356, 901, Node800, 50);
    giq_option(4, 1356, 902, Node999, 50);
end

procedure Node950
begin
    gsay_reply(1356, 950);
    giq_option(4, 1356, 951, Barter, 50);
    if (local_var(15) == 5) then begin
        giq_option(4, 1356, 952, Node1650, 50);
    end
    else begin
        giq_option(4, 1356, 952, Node1050, 50);
    end
    giq_option(4, 1356, 953, Node999, 50);
    giq_option(-3, 1356, 954, Barter, 50);
    if (local_var(15) == 5) then begin
        giq_option(-3, 1356, 955, Node1650, 50);
    end
    else begin
        giq_option(-3, 1356, 955, Node1700, 50);
    end
    giq_option(-3, 1356, 956, Node999, 50);
end

procedure Node1000
begin
    gsay_reply(1356, 1000);
    giq_option(4, 1356, 1001, Node999swap, 50);
    giq_option(-3, 1356, 1002, Node999swap, 50);
end

procedure Node1050
begin
    gsay_reply(1356, message_str(1356, 1050) + message_str(1356, local_var(9)) + message_str(1356, local_var(10)) + message_str(1356, local_var(11)) + message_str(1356, local_var(12)) + message_str(1356, local_var(13)) + message_str(1356, 1056));
    if (local_var(9) != 1070) then begin
        giq_option(4, 1356, 1057, Node1100, 50);
    end
    if (local_var(10) != 1070) then begin
        giq_option(4, 1356, 1058, Node1150, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        if (local_var(11) != 1070) then begin
            giq_option(4, 1356, 1059, Node1200, 50);
        end
        if (local_var(12) != 1070) then begin
            giq_option(4, 1356, 1060, Node1300, 50);
        end
        if (local_var(13) != 1070) then begin
            giq_option(4, 1356, 1061, Node1400, 50);
        end
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        if (local_var(11) != 1070) then begin
            giq_option(4, 1356, 1059, Node1250, 50);
        end
        if (local_var(12) != 1070) then begin
            giq_option(4, 1356, 1060, Node1350, 50);
        end
        if (local_var(13) != 1070) then begin
            giq_option(4, 1356, 1061, Node1600, 50);
        end
    end
    giq_option(4, 1356, 1062, Node999, 50);
end

procedure Node1100
begin
    gsay_reply(1356, 1100);
    if (item_caps_total(dude_obj) >= 50) then begin
        giq_option(4, 1356, 1101, Buy_elvis, 50);
    end
    else begin
        giq_option(4, 1356, 1102, Node999, 50);
    end
    giq_option(4, 1356, 1103, Node1050, 50);
    giq_option(4, 1356, 1104, Node999, 50);
end

procedure Node1150
begin
    gsay_reply(1356, 1150);
    if (item_caps_total(dude_obj) >= 100) then begin
        giq_option(4, 1356, 1151, Buy_nixon, 50);
    end
    else begin
        giq_option(4, 1356, 1152, Node999, 50);
    end
    giq_option(4, 1356, 1153, Node1050, 50);
    giq_option(4, 1356, 1154, Node999, 50);
end

procedure Node1200
begin
    gsay_reply(1356, 1200);
    if (item_caps_total(dude_obj) >= 60) then begin
        giq_option(4, 1356, 1201, Buy_cats_paw, 50);
    end
    else begin
        giq_option(4, 1356, 1202, Node999, 50);
    end
    giq_option(4, 1356, 1203, Node1050, 50);
    giq_option(4, 1356, 1204, Node999, 50);
end

procedure Node1250
begin
    gsay_reply(1356, 1250);
    if (item_caps_total(dude_obj) >= 60) then begin
        giq_option(4, 1356, 1251, Buy_cats_paw, 50);
    end
    else begin
        giq_option(4, 1356, 1252, Node999, 50);
    end
    giq_option(4, 1356, 1253, Node1050, 50);
    giq_option(4, 1356, 1254, Node999, 50);
end

procedure Node1300
begin
    gsay_reply(1356, 1300);
    if (item_caps_total(dude_obj) >= 300) then begin
        giq_option(4, 1356, 1301, Buy_rubber_doll, 50);
    end
    else begin
        giq_option(4, 1356, 1302, Node999, 50);
    end
    giq_option(4, 1356, 1303, Node1050, 50);
    giq_option(4, 1356, 1304, Node999, 50);
end

procedure Node1350
begin
    gsay_reply(1356, 1350);
    if (item_caps_total(dude_obj) >= 300) then begin
        giq_option(4, 1356, 1351, Buy_rubber_doll, 50);
    end
    else begin
        giq_option(4, 1356, 1352, Node999, 50);
    end
    giq_option(4, 1356, 1353, Node1050, 50);
    giq_option(4, 1356, 1354, Node999, 50);
end

procedure Node1400
begin
    gsay_reply(1356, 1400);
    if (item_caps_total(dude_obj) >= 10) then begin
        giq_option(4, 1356, 1401, Buy_talisman, 50);
    end
    else begin
        giq_option(4, 1356, 1402, Node999, 50);
    end
    giq_option(4, 1356, 1403, Node1050, 50);
    giq_option(4, 1356, 1404, Node999, 50);
    if (local_var(7) != 1) then begin
        giq_option(4, 1356, 1405, Node1450, 50);
    end
end

procedure Node1450
begin
    gsay_reply(1356, 1450);
    if (item_caps_total(dude_obj) >= 10) then begin
        giq_option(4, 1356, 1451, Buy_talisman, 50);
    end
    else begin
        giq_option(4, 1356, 1452, Node999, 50);
    end
    giq_option(4, 1356, 1453, Node1050, 50);
    giq_option(4, 1356, 1454, Node999, 50);
    giq_option(4, 1356, 1455, Node1500, 50);
end

procedure Node1500
begin
    gsay_reply(1356, 1500);
    if (item_caps_total(dude_obj) >= 10) then begin
        giq_option(4, 1356, 1501, Buy_talisman, 50);
    end
    else begin
        giq_option(4, 1356, 1502, Node999, 50);
    end
    giq_option(4, 1356, 1503, Node1050, 50);
    giq_option(4, 1356, 1504, Node999, 50);
    if ((has_skill(dude_obj, 15) > 50) and (item_caps_total(dude_obj) >= 40)) then begin
        giq_option(4, 1356, 1505, Node1550, 50);
    end
end

procedure Node1550
begin
    gsay_reply(1356, 1550);
    set_local_var(7, 1);
    item_caps_adjust(dude_obj, -40);
    if (item_caps_total(dude_obj) >= 10) then begin
        giq_option(4, 1356, 1551, Buy_talisman, 50);
    end
    else begin
        giq_option(4, 1356, 1552, Node999, 50);
    end
    giq_option(4, 1356, 1553, Node1050, 50);
    giq_option(4, 1356, 1554, Node999, 50);
end

procedure Node1600
begin
    gsay_reply(1356, 1600);
    if (item_caps_total(dude_obj) >= 10) then begin
        giq_option(4, 1356, 1601, Buy_talisman, 50);
    end
    else begin
        giq_option(4, 1356, 1602, Node999, 50);
    end
    giq_option(4, 1356, 1603, Node1050, 50);
    giq_option(4, 1356, 1604, Node999, 50);
    if (local_var(7) != 1) then begin
        giq_option(4, 1356, 1605, Node1450, 50);
    end
end

procedure Node1650
begin
    gsay_reply(1356, 1650);
    giq_option(4, 1356, 1651, Barter, 50);
    giq_option(4, 1356, 1652, Node999, 50);
    giq_option(-3, 1356, 1653, Barter, 50);
    giq_option(-3, 1356, 1654, Node999, 50);
end

procedure Node1700
begin
    gsay_reply(1356, message_str(1356, 1700) + message_str(1356, local_var(9)) + message_str(1356, local_var(10)) + message_str(1356, local_var(11)) + message_str(1356, local_var(12)) + message_str(1356, local_var(14)) + message_str(1356, 1706));
    if (local_var(9) != 1070) then begin
        giq_option(-3, 1356, 1707, Node1750, 50);
    end
    if (local_var(10) != 1070) then begin
        giq_option(-3, 1356, 1708, Node1800, 50);
    end
    if ((local_var(11) != 1070) and (get_critter_stat(dude_obj, 34) == 0)) then begin
        giq_option(-3, 1356, 1709, Node1850, 50);
    end
    if ((local_var(11) != 1070) and (get_critter_stat(dude_obj, 34) == 1)) then begin
        giq_option(-3, 1356, 1709, Node1900, 50);
    end
    if ((local_var(12) != 1070) and (get_critter_stat(dude_obj, 34) == 0)) then begin
        giq_option(-3, 1356, 1710, Node1950, 50);
    end
    if ((local_var(12) != 1070) and (get_critter_stat(dude_obj, 34) == 1)) then begin
        giq_option(-3, 1356, 1710, Node2000, 50);
    end
    if (local_var(14) != 1070) then begin
        giq_option(-3, 1356, 1711, Node2050, 50);
    end
    giq_option(-3, 1356, 1712, Node999, 50);
end

procedure Node1750
begin
    gsay_reply(1356, 1750);
    if (item_caps_total(dude_obj) >= 70) then begin
        giq_option(-3, 1356, 1751, Buy_elvis, 50);
    end
    else begin
        giq_option(-3, 1356, 1752, Node999, 50);
    end
    giq_option(-3, 1356, 1753, Node1700, 50);
    giq_option(-3, 1356, 1754, Node999, 50);
end

procedure Node1800
begin
    gsay_reply(1356, 1800);
    if (item_caps_total(dude_obj) >= 200) then begin
        giq_option(-3, 1356, 1801, Buy_nixon, 50);
    end
    else begin
        giq_option(-3, 1356, 1802, Node999, 50);
    end
    giq_option(-3, 1356, 1803, Node1700, 50);
    giq_option(-3, 1356, 1804, Node999, 50);
end

procedure Node1850
begin
    gsay_reply(1356, 1850);
    if (item_caps_total(dude_obj) >= 100) then begin
        giq_option(-3, 1356, 1851, Buy_cats_paw, 50);
    end
    else begin
        giq_option(-3, 1356, 1852, Node999, 50);
    end
    giq_option(-3, 1356, 1853, Node1700, 50);
    giq_option(-3, 1356, 1854, Node999, 50);
end

procedure Node1900
begin
    gsay_reply(1356, 1900);
    if (item_caps_total(dude_obj) >= 100) then begin
        giq_option(-3, 1356, 1901, Buy_cats_paw, 50);
    end
    else begin
        giq_option(-3, 1356, 1902, Node999, 50);
    end
    giq_option(-3, 1356, 1903, Node1700, 50);
    giq_option(-3, 1356, 1904, Node999, 50);
end

procedure Node1950
begin
    gsay_reply(1356, 1950);
    if (item_caps_total(dude_obj) >= 500) then begin
        giq_option(-3, 1356, 1951, Buy_rubber_doll, 50);
    end
    else begin
        giq_option(-3, 1356, 1952, Node999, 50);
    end
    giq_option(-3, 1356, 1953, Node1700, 50);
    giq_option(-3, 1356, 1954, Node999, 50);
end

procedure Node2000
begin
    gsay_reply(1356, 2000);
    if (item_caps_total(dude_obj) >= 500) then begin
        giq_option(-3, 1356, 2001, Buy_rubber_doll, 50);
    end
    else begin
        giq_option(-3, 1356, 2002, Node999, 50);
    end
    giq_option(-3, 1356, 2003, Node1700, 50);
    giq_option(-3, 1356, 2004, Node999, 50);
end

procedure Node2050
begin
    if (obj_carrying_pid_obj(dude_obj, 309)) then begin
        gsay_reply(1356, 2050);
    end
    else begin
        if (get_critter_stat(dude_obj, 34) == 0) then begin
            gsay_reply(1356, 2051);
        end
        if (get_critter_stat(dude_obj, 34) == 1) then begin
            gsay_reply(1356, 2052);
        end
    end
    if (item_caps_total(dude_obj) >= 30) then begin
        giq_option(-3, 1356, 2053, Buy_talisman, 50);
    end
    else begin
        giq_option(-3, 1356, 2054, Node999, 50);
    end
    giq_option(-3, 1356, 2055, Node1700, 50);
    giq_option(-3, 1356, 2056, Node999, 50);
    if (obj_carrying_pid_obj(dude_obj, 309) and (local_var(8) != 1)) then begin
        giq_option(-3, 1356, message_str(1356, 2057) + obj_name(dude_obj) + message_str(1356, 2058), Node2100, 50);
    end
end

procedure Node2100
begin
    gsay_reply(1356, 2100);
    set_local_var(8, 1);
    if (item_caps_total(dude_obj) >= 30) then begin
        giq_option(-3, 1356, 2101, Buy_talisman, 50);
    end
    else begin
        giq_option(-3, 1356, 2102, Node999, 50);
    end
    giq_option(-3, 1356, 2103, Node1700, 50);
    giq_option(-3, 1356, 2104, Node999, 50);
end

procedure Node2150
begin
    gsay_reply(1356, 2150);
    giq_option(4, 1356, 2151, ThrowOutFromShop, 50);
    giq_option(4, 1356, 2152, Node998, 50);
    giq_option(-3, 1356, 2153, ThrowOutFromShop, 50);
    giq_option(-3, 1356, 2154, Node998, 50);
end

procedure ThrowOutFromShop
begin
    anim(self_obj, 1000, 3);
    move_to(dude_obj, 25942, 0);
    if (party_member_obj(16777729) != 0) then begin
        if (party_member_obj(16777729) != 0) then begin
            if (has_trait(1, party_member_obj(16777729), 666)) then begin
                critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
        if (party_member_obj(16777779) != 0) then begin
            if (has_trait(1, party_member_obj(16777779), 666)) then begin
                critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(910) bwand 64) == 0)) then begin
        if (party_member_obj(16777811) != 0) then begin
            if (has_trait(1, party_member_obj(16777811), 666)) then begin
                critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (party_member_obj(16777812) != 0) then begin
            if (has_trait(1, party_member_obj(16777812), 666)) then begin
                critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(910) bwand 128) == 0)) then begin
        if (party_member_obj(16777814) != 0) then begin
            if (has_trait(1, party_member_obj(16777814), 666)) then begin
                critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (party_member_obj(16777748) != 0) then begin
            if (has_trait(1, party_member_obj(16777748), 666)) then begin
                critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (party_member_obj(16778017) != 0) then begin
            if (has_trait(1, party_member_obj(16778017), 666)) then begin
                critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (party_member_obj(16778016) != 0) then begin
            if (has_trait(1, party_member_obj(16778016), 666)) then begin
                critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (party_member_obj(16778049) != 0) then begin
            if (has_trait(1, party_member_obj(16778049), 666)) then begin
                critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (party_member_obj(16778050) != 0) then begin
            if (has_trait(1, party_member_obj(16778050), 666)) then begin
                critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (party_member_obj(16778051) != 0) then begin
            if (has_trait(1, party_member_obj(16778051), 666)) then begin
                critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (party_member_obj(16777293) != 0) then begin
            if (has_trait(1, party_member_obj(16777293), 666)) then begin
                critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(tile_num(dude_obj), (has_trait(1, dude_obj, 10) + 3) % 6, 1), 0);
            end
        end
    end
    dude_seen := 0;
    if ((salem_door != -1) and salem_door) then begin
        add_timer_event(salem_door, 1, 3);
    end
end

procedure Buy_elvis
begin
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        item_caps_adjust(dude_obj, -70);
    end
    else begin
        item_caps_adjust(dude_obj, -50);
    end
    restock_obj := create_object_sid(78, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_local_var(9, 1070);
    set_local_var(15, local_var(15) + 1);
end

procedure Buy_nixon
begin
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        item_caps_adjust(dude_obj, -200);
    end
    else begin
        item_caps_adjust(dude_obj, -100);
    end
    restock_obj := create_object_sid(491, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_local_var(10, 1070);
    set_local_var(15, local_var(15) + 1);
end

procedure Buy_cats_paw
begin
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        item_caps_adjust(dude_obj, -100);
    end
    else begin
        item_caps_adjust(dude_obj, -60);
    end
    restock_obj := create_object_sid(225, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_local_var(11, 1070);
    set_local_var(15, local_var(15) + 1);
end

procedure Buy_rubber_doll
begin
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        item_caps_adjust(dude_obj, -500);
    end
    else begin
        item_caps_adjust(dude_obj, -300);
    end
    restock_obj := create_object_sid(508, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_local_var(12, 1070);
    set_local_var(15, local_var(15) + 1);
end

procedure Buy_talisman
begin
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        item_caps_adjust(dude_obj, -30);
    end
    else begin
        item_caps_adjust(dude_obj, -10);
    end
    restock_obj := create_object_sid(309, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_local_var(13, 1070);
    set_local_var(14, 1070);
    set_local_var(15, local_var(15) + 1);
end

procedure Barter
begin
    move_obj_inven_to_obj(salem, salem_table_swap);
    move_obj_inven_to_obj(salem_table_trade, salem);
    if ((get_critter_stat(dude_obj, 4) + has_trait(0, dude_obj, 49)) <= 3) then begin
        if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
            gdialog_mod_barter(60 - 15);
        end
        else begin
            gdialog_mod_barter(60);
        end
    end
    else begin
        if ((party_member_obj(16777779) != 0) and ((global_var(910) bwand 32) == 0)) then begin
            gdialog_mod_barter(50 - 15);
        end
        else begin
            gdialog_mod_barter(50);
        end
    end
    call Node1000();
end

procedure Open_hours
begin
    if ((game_time_hour < 600) or (2000 < game_time_hour)) then begin
        return 0;
    end
    else begin
        return 1;
    end
end

procedure Time_check
begin
    if (Open_hours() == 0) then begin
        set_local_var(16, 1);
    end
    if (Open_hours() == 1) then begin
        set_local_var(16, 0);
    end
end

