variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node016a;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node999;
procedure Node998;
procedure NodeBarter;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(50, 60));
        set_local_var(5, random(20, 30));
        set_local_var(6, random(-30, 20));
        critter_add_trait(self_obj, 1, 6, 20);
        critter_add_trait(self_obj, 1, 5, 23);
        add_obj_to_inven(self_obj, create_object_sid(137, 1, 2, -1));
        add_mult_objs_to_inven(self_obj, create_object_sid(19, 1, 2, -1), random(2, 3));
        wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 137));
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(215, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(109, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(10, 40));
        end
        if (random(0, 100) <= 25) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(220, 1, 2, -1), random(1, 3));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(66, 1, 2, -1));
        end
        if (random(0, 100) <= 9) then begin
            add_obj_to_inven(self_obj, create_object_sid(431, 1, 2, -1));
        end
        if (random(0, 100) <= 8) then begin
            add_obj_to_inven(self_obj, create_object_sid(427, 1, 2, -1));
        end
        if (random(0, 100) <= 7) then begin
            add_obj_to_inven(self_obj, create_object_sid(226, 1, 2, -1));
        end
        if (random(0, 100) <= 6) then begin
            add_obj_to_inven(self_obj, create_object_sid(229, 1, 2, -1));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(53) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(299, 2));
    end
    else begin
        display_msg(message_str(299, 4));
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(299, 1));
    end
    else begin
        display_msg(message_str(299, 3));
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    start_gdialog(299, self_obj, -1, -1, -1);
    gsay_start;
    if (local_var(7) == 0) then begin
        call Node001();
    end
    else begin
        call Node010();
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    set_global_var(119, global_var(119) bwor 2048);
    if (global_var(182) < 7) then begin
        set_global_var(182, 0);
        add_obj_to_inven(self_obj, create_object_sid(394, 1, 2, -1));
    end
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 1);
        if ((53 == 50) or (53 == 59)) then begin
            set_global_var(53, global_var(53) - 3);
        end
        else begin
            set_global_var(53, global_var(53) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
end

procedure Node001
begin
    gsay_reply(299, 10);
    gsay_option(299, 11, Node011, 50);
    gsay_option(299, 12, Node011, 50);
    gsay_option(299, 13, Node999, 50);
end

procedure Node010
begin
    if ((global_var(182) == 7) or (global_var(183) == 2)) then begin
        gsay_reply(299, 1002);
        gsay_option(299, 105, Node012, 50);
        gsay_option(299, 106, Node999, 50);
        gsay_option(299, 107, Node999, 50);
    end
    else begin
        gsay_reply(299, 1001);
        gsay_option(299, 101, Node012, 50);
        if (global_var(182) == 6) then begin
            gsay_option(299, 102, Node019, 50);
        end
        if ((local_var(8) == 1) and (global_var(182) == 0)) then begin
            gsay_option(299, 103, Node016, 50);
        end
        gsay_option(299, 104, Node999, 50);
    end
end

procedure Node011
begin
    set_local_var(7, 1);
    gsay_reply(299, 110);
    gsay_option(299, 111, Node013, 50);
    gsay_option(299, 112, Node021, 50);
    gsay_option(299, 113, Node020, 50);
    gsay_option(299, 114, Node999, 50);
end

procedure Node012
begin
    gsay_reply(299, 120);
    if ((global_var(182) == 0) and not(obj_carrying_pid_obj(dude_obj, 394))) then begin
        gsay_option(299, 121, Node013, 50);
    end
    gsay_option(299, 122, Node021, 50);
    gsay_option(299, 123, Node020, 50);
    gsay_option(299, 124, Node999, 50);
end

procedure Node013
begin
    gsay_reply(299, 130);
    if (global_var(182) == 0) then begin
        gsay_option(299, 131, Node014, 50);
    end
    gsay_option(299, 132, Node012, 50);
    gsay_option(299, 133, Node999, 50);
end

procedure Node014
begin
    gsay_reply(299, 140);
    gsay_option(299, 141, Node015, 50);
end

procedure Node015
begin
    set_local_var(8, 1);
    gsay_reply(299, 150);
    gsay_option(299, 151, Node016, 50);
    gsay_option(299, 152, Node024, 50);
    gsay_option(299, 153, Node999, 50);
end

procedure Node016
begin
    gsay_reply(299, 160);
    gsay_option(299, 161, Node016a, 50);
    gsay_option(299, 162, Node024, 50);
    if (global_var(285) == 2) then begin
        gsay_option(299, 163, Node017, 50);
    end
    gsay_option(299, 164, Node999, 50);
end

procedure Node016a
begin
    set_global_var(182, 1);
end

procedure Node017
begin
    gsay_reply(299, 170);
    gsay_option(299, 171, Node018, 50);
end

procedure Node018
begin
    set_global_var(182, 8);
    give_exp_points(floor(1208 / 2 / 5) + (get_critter_stat(dude_obj, 4) * floor(1208 / 2 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1208 / 2 / 30)) + (floor(1208 / 2 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
    display_msg(message_str(10, random(140, 143)) + (floor(1208 / 2 / 5) + (get_critter_stat(dude_obj, 4) * floor(1208 / 2 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1208 / 2 / 30)) + (floor(1208 / 2 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
    add_obj_to_inven(dude_obj, create_object_sid(394, 1, 2, -1));
    gsay_reply(299, 180);
    gsay_option(299, 181, Node999, 50);
    gsay_option(299, 182, Node999, 50);
end

procedure Node019
begin
    set_global_var(182, 7);
    give_exp_points(floor(1208 / 5) + (get_critter_stat(dude_obj, 4) * floor(1208 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1208 / 30)) + (floor(1208 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
    display_msg(message_str(10, random(140, 143)) + (floor(1208 / 5) + (get_critter_stat(dude_obj, 4) * floor(1208 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1208 / 30)) + (floor(1208 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
    add_obj_to_inven(dude_obj, create_object_sid(394, 1, 2, -1));
    gsay_reply(299, 190);
    gsay_option(299, 191, Node999, 50);
    gsay_option(299, 192, Node999, 50);
end

procedure Node020
begin
    gsay_reply(299, 200);
    gsay_option(299, 201, Node022, 50);
    gsay_option(299, 202, Node012, 50);
    gsay_option(299, 203, Node999, 50);
end

procedure Node021
begin
    gsay_reply(299, 210);
    gsay_option(299, 211, Node022, 50);
    gsay_option(299, 212, Node012, 50);
    gsay_option(299, 213, Node999, 50);
end

procedure Node022
begin
    gsay_reply(299, 220);
    gsay_option(299, 221, Node023, 50);
    gsay_option(299, 222, Node012, 50);
    gsay_option(299, 223, Node999, 50);
end

procedure Node023
begin
    gsay_reply(299, 230);
    gsay_option(299, 231, Node012, 50);
    gsay_option(299, 232, Node999, 50);
end

procedure Node024
begin
    gsay_reply(299, 240);
    gsay_option(299, 241, Node998, 50);
    gsay_option(299, 242, Node998, 50);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    set_local_var(2, 1);
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end

