variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure spatial_p_proc;


procedure start
begin
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure spatial_p_proc
begin
    if (source_obj == dude_obj) then begin
        if ((global_var(182) > 0) and (global_var(182) < 6)) then begin
            if (get_critter_stat(dude_obj, 1) >= 8) then begin
                if (local_var(1) == 0) then begin
                    set_local_var(1, 1);
                    set_global_var(182, global_var(182) + 1);
                    if (global_var(182) == 6) then begin
                        play_sfx("LEVELUP");
                        display_msg(message_str(10, 860));
                    end
                    create_object_sid(42, tile_num(self_obj), elevation(self_obj), -1);
                end
            end
            else begin
                if (local_var(3) == 0) then begin
                    set_local_var(3, 1);
                    display_msg(message_str(10, 862));
                    explosion(tile_num(self_obj), elevation(self_obj), random(10, 15));
                    set_global_var(182, global_var(182) + 1);
                    if (global_var(182) == 6) then begin
                        play_sfx("LEVELUP");
                        display_msg(message_str(10, 860));
                    end
                    if (local_var(4) == 0) then begin
                        set_local_var(4, 1);
                        display_msg(message_str(10, 863));
                    end
                end
            end
        end
    end
    else begin
        if (global_var(183) == 1) then begin
            if (local_var(3) == 0) then begin
                set_local_var(3, 1);
                explosion(tile_num(self_obj), elevation(self_obj), random(20, 45));
            end
        end
    end
end

