procedure start;
procedure HMS_global_check;
procedure HMS_check;
procedure initialize_HMS;
procedure close_HMS;
procedure initialize_HMS_dialogue;
procedure Node1;
procedure Node11;
procedure Node12;
procedure Node2;
procedure Node3;
procedure Node_Exit;
procedure refresh_all;
procedure NodeMiss;
procedure NodeBuzzPart;
procedure NodeBuzzPartOK;
procedure NodeFakeArmor;
procedure NodeFakeArmorOK;
procedure NodeElectroTrap;
procedure NodeElectroTrapOK;
procedure NodeExplTrap;
procedure NodeExplTrapOK;
procedure NodeButchKnife;
procedure NodeButchKnifeOK;
procedure NodeRustyArmor;
procedure NodeRustyArmorOK;
procedure NodeBazooka;
procedure NodeBazookaOK;
procedure NodeHandGrenade;
procedure NodeHandGrenadeOK;
procedure NodeEnergetic;
procedure NodeEnergeticOK;
procedure NodeUdobrenie;
procedure NodeUdobrenieOK;
procedure NodeJackalGun;
procedure NodeJackalGunOK;
procedure NodeSugarMeat;
procedure NodeSugarMeatOK;

variable mouse_1_is_pressed;
variable HMS_is_called;
variable options_count;
variable options1_count;
variable waterpump_shown;
variable buzzpart_shown;
variable fakearmor_shown;
variable electrotrap_shown;
variable expltrap_shown;
variable butchknife_shown;
variable rustyarmor_shown;
variable bazooka_shown;
variable handgrenade_shown;
variable energetic_shown;
variable udobrenie_shown;
variable jackalgun_shown;
variable sugarmeat_shown;
variable refresh_shown;


procedure start
begin
    set_global_script_type(0);
    set_global_script_repeat(1);
    call HMS_global_check();
end

procedure HMS_global_check
begin
    if ((get_mouse_x > ((get_screen_width / 2) + 345)) and (get_mouse_x < ((get_screen_width / 2) + 395)) and (get_mouse_y > (get_screen_height - 90)) and (get_mouse_y < (get_screen_height - 65))) then begin
        call HMS_check();
    end
end

procedure HMS_check
begin
    if ((get_mouse_buttons == 1) and (mouse_1_is_pressed == 0) and (HMS_is_called == 0)) then begin
        if ((get_game_mode bwand 64) != 0) then begin
            play_sfx("BUTIN2");
            create_message_window("You can't open your HMS while in combat!");
        end
        else begin
            mouse_1_is_pressed := 1;
            HMS_is_called := 1;
            animate_move_obj_to_tile(dude_obj, tile_num(dude_obj), 0 bwor 16);
            play_sfx("BUTIN2");
            call initialize_HMS();
        end
    end
    if ((get_mouse_buttons == 0) and (mouse_1_is_pressed == 1)) then begin
        mouse_1_is_pressed := 0;
    end
end

procedure initialize_HMS
begin
    if (get_screen_height >= 600) then begin
        createWin("fxtools", (get_screen_width / 2) - 400, (get_screen_height / 2) - 300, 209, 339);
    end
    else begin
        createWin("fxtools", (get_screen_width / 2) - 400, get_screen_height - 339 - 161, 209, 339);
    end
    selectWin("fxtools");
    displayGfx("PCX/fxtools.pcx", 0, 0, 209, 339);
    showWin;
    if (get_screen_height >= 600) then begin
        createWin("fxresult", (get_screen_width / 2) - 400, (get_screen_height / 2) + 39, 209, 161);
    end
    else begin
        createWin("fxresult", (get_screen_width / 2) - 400, get_screen_height - 161, 209, 161);
    end
    selectWin("fxresult");
    displayGfx("PCX/fxresult.pcx", 0, 0, 209, 161);
    showWin;
    if (get_screen_height >= 600) then begin
        createWin("fxtop", (get_screen_width / 2) - 191, (get_screen_height / 2) - 300, 408, 50);
    end
    else begin
        createWin("fxtop", (get_screen_width / 2) - 191, get_screen_height - 500, 408, 50);
    end
    selectWin("fxtop");
    displayGfx("PCX/fxtop.pcx", 0, 0, 408, 50);
    showWin;
    if (get_screen_height >= 600) then begin
        createWin("fxskills", (get_screen_width / 2) + 215, (get_screen_height / 2) - 300, 183, 500);
    end
    else begin
        createWin("fxskills", (get_screen_width / 2) + 215, get_screen_height - 500, 183, 500);
    end
    selectWin("fxskills");
    displayGfx("PCX/fxskills.pcx", 0, 0, 183, 500);
    setFont(4);
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    showWin;
    if (get_screen_height >= 600) then begin
        createWin("fxreply", (get_screen_width / 2) - 191, (get_screen_height / 2) - 250, 408, 177);
    end
    else begin
        createWin("fxreply", (get_screen_width / 2) - 191, get_screen_height - 273 - 177, 408, 177);
    end
    selectWin("fxreply");
    displayGfx("PCX/fxreply.pcx", 0, 0, 408, 177);
    showWin;
    if (get_screen_height >= 600) then begin
        createWin("fxoption", (get_screen_width / 2) - 191, (get_screen_height / 2) - 73, 408, 273);
    end
    else begin
        createWin("fxoption", (get_screen_width / 2) - 191, get_screen_height - 273, 408, 273);
    end
    selectWin("fxoption");
    displayGfx("PCX/fxoption.pcx", 0, 0, 408, 273);
    showWin;
    call initialize_HMS_dialogue();
end

procedure close_HMS
begin
    deleteWin("fxtools");
    deleteWin("fxresult");
    deleteWin("fxtop");
    deleteWin("fxskills");
    deleteWin("fxreply");
    deleteWin("fxoption");
    HMS_is_called := 0;
end

procedure initialize_HMS_dialogue
begin
    setFont(4);
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    if (get_screen_height >= 600) then begin
        sayReplyWindow((get_screen_width / 2) - 191, (get_screen_height / 2) - 300 + 50, 407, 177, "PCX/fxreply.pcx");
        sayOptionWindow((get_screen_width / 2) - 191, (get_screen_height / 2) - 73, 407, 273, "PCX/fxoption.pcx");
    end
    else begin
        sayReplyWindow((get_screen_width / 2) - 191, get_screen_height - 273 - 177, 407, 177, "PCX/fxreply.pcx");
        sayOptionWindow((get_screen_width / 2) - 191, get_screen_height - 273, 407, 273, "PCX/fxoption.pcx");
    end
    sayReplyTitle("Welcome to the Hand Made System!");
    sayBorder(25, 25);
    saySetSpacing(20);
    sayOptionFlags(2);
    sayReplyFlags(0);
    game_ui_disable;
    mouseShape("PCX/mouse2.PCX", 0, 0);
    sayStart;
    call Node1();
    sayEnd;
    call close_HMS();
end

procedure Node1
begin
    call refresh_all();
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 11));
    waterpump_shown := 0;
    buzzpart_shown := 0;
    fakearmor_shown := 0;
    electrotrap_shown := 0;
    expltrap_shown := 0;
    butchknife_shown := 0;
    rustyarmor_shown := 0;
    bazooka_shown := 0;
    handgrenade_shown := 0;
    energetic_shown := 0;
    udobrenie_shown := 0;
    jackalgun_shown := 0;
    sugarmeat_shown := 0;
    refresh_shown := 0;
    options_count := 0;
    if ((global_var(31) == 1) and (obj_carrying_pid_obj(dude_obj, 296) == 0) and (waterpump_shown == 0)) then begin
        sayOption(message_str(78, 110), Node2);
        options_count := options_count + 1;
        waterpump_shown := 0;
    end
    if ((get_sfall_global_int(30) == 1) and (obj_carrying_pid_obj(dude_obj, 486) == 0) and (buzzpart_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 111), NodeBuzzPart);
            buzzpart_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(31) == 1) and (options_count < 6) and (fakearmor_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 112), NodeFakeArmor);
            fakearmor_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(32) == 1) and (options_count < 6) and (electrotrap_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 113), NodeElectroTrap);
            electrotrap_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(33) == 1) and (options_count < 6) and (expltrap_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 114), NodeExplTrap);
            expltrap_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(34) == 1) and (options_count < 6) and (butchknife_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 115), NodeButchKnife);
            butchknife_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(35) == 1) and (options_count < 6) and (rustyarmor_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 116), NodeRustyArmor);
            rustyarmor_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(36) == 1) and (options_count < 6) and (bazooka_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 117), NodeBazooka);
            bazooka_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(37) == 1) and (options_count < 6) and (handgrenade_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 118), NodeHandGrenade);
            handgrenade_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(38) == 1) and (options_count < 6) and (energetic_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 119), NodeEnergetic);
            energetic_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(39) == 1) and (options_count < 6) and (udobrenie_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 120), NodeUdobrenie);
            udobrenie_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(40) == 1) and (options_count < 6) and (jackalgun_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 121), NodeJackalGun);
            jackalgun_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(41) == 1) and (options_count < 6) and (sugarmeat_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 122), NodeSugarMeat);
            sugarmeat_shown := 1;
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure Node11
begin
    call refresh_all();
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 11));
    if (refresh_shown == 1) then begin
        refresh_shown := 0;
        options_count := 0;
        options1_count := 0;
        waterpump_shown := 0;
        buzzpart_shown := 0;
        fakearmor_shown := 0;
        electrotrap_shown := 0;
        expltrap_shown := 0;
        butchknife_shown := 0;
        rustyarmor_shown := 0;
        bazooka_shown := 0;
        handgrenade_shown := 0;
        energetic_shown := 0;
        udobrenie_shown := 0;
        jackalgun_shown := 0;
        sugarmeat_shown := 0;
        if ((global_var(31) == 1) and (obj_carrying_pid_obj(dude_obj, 296) == 0) and (waterpump_shown == 0)) then begin
            if (options1_count < 5) then begin
                waterpump_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 110), Node2);
                    waterpump_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(30) == 1) and (obj_carrying_pid_obj(dude_obj, 486) == 0) and (buzzpart_shown == 0)) then begin
            if (options1_count < 5) then begin
                buzzpart_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 111), NodeBuzzPart);
                    buzzpart_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(31) == 1) and (options_count < 6) and (fakearmor_shown == 0)) then begin
            if (options1_count < 5) then begin
                fakearmor_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 112), NodeFakeArmor);
                    fakearmor_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(32) == 1) and (options_count < 6) and (electrotrap_shown == 0)) then begin
            if (options1_count < 5) then begin
                electrotrap_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 113), NodeElectroTrap);
                    electrotrap_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(33) == 1) and (options_count < 6) and (expltrap_shown == 0)) then begin
            if (options1_count < 5) then begin
                expltrap_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 114), NodeExplTrap);
                    expltrap_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(34) == 1) and (options_count < 6) and (butchknife_shown == 0)) then begin
            if (options1_count < 5) then begin
                butchknife_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 115), NodeButchKnife);
                    butchknife_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(35) == 1) and (options_count < 6) and (rustyarmor_shown == 0)) then begin
            if (options1_count < 5) then begin
                rustyarmor_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 116), NodeRustyArmor);
                    rustyarmor_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(36) == 1) and (options_count < 6) and (bazooka_shown == 0)) then begin
            if (options1_count < 5) then begin
                bazooka_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 117), NodeBazooka);
                    bazooka_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(37) == 1) and (options_count < 6) and (handgrenade_shown == 0)) then begin
            if (options1_count < 5) then begin
                handgrenade_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 118), NodeHandGrenade);
                    handgrenade_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(38) == 1) and (options_count < 6) and (energetic_shown == 0)) then begin
            if (options1_count < 5) then begin
                energetic_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 119), NodeEnergetic);
                    energetic_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(39) == 1) and (options_count < 6) and (udobrenie_shown == 0)) then begin
            if (options1_count < 5) then begin
                udobrenie_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 120), NodeUdobrenie);
                    udobrenie_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(40) == 1) and (options_count < 6) and (jackalgun_shown == 0)) then begin
            if (options1_count < 5) then begin
                jackalgun_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 121), NodeJackalGun);
                    jackalgun_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(41) == 1) and (options_count < 6) and (sugarmeat_shown == 0)) then begin
            if (options1_count < 5) then begin
                sugarmeat_shown := 1;
                options1_count := options1_count + 1;
            end
            else begin
                if (options_count <= 4) then begin
                    sayOption(message_str(78, 122), NodeSugarMeat);
                    sugarmeat_shown := 1;
                end
                else begin
                    sayOption(message_str(78, 103), Node12);
                end
            end
            options_count := options_count + 1;
        end
    end
    else begin
        options_count := 0;
        if ((get_sfall_global_int(34) == 1) and (options_count < 6) and (butchknife_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 115), NodeButchKnife);
                butchknife_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(35) == 1) and (options_count < 6) and (rustyarmor_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 116), NodeRustyArmor);
                rustyarmor_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(36) == 1) and (options_count < 6) and (bazooka_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 117), NodeBazooka);
                bazooka_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(37) == 1) and (options_count < 6) and (handgrenade_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 118), NodeHandGrenade);
                handgrenade_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(38) == 1) and (options_count < 6) and (energetic_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 119), NodeEnergetic);
                energetic_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(39) == 1) and (options_count < 6) and (udobrenie_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 120), NodeUdobrenie);
                udobrenie_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(40) == 1) and (options_count < 6) and (jackalgun_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 121), NodeJackalGun);
                jackalgun_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
        if ((get_sfall_global_int(41) == 1) and (options_count < 6) and (sugarmeat_shown == 0)) then begin
            if (options_count <= 4) then begin
                sayOption(message_str(78, 122), NodeSugarMeat);
                sugarmeat_shown := 1;
            end
            else begin
                sayOption(message_str(78, 103), Node12);
            end
            options_count := options_count + 1;
        end
    end
    sayOption(message_str(78, 104), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure Node12
begin
    call refresh_all();
    refresh_shown := 1;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 11));
    options_count := 0;
    if ((get_sfall_global_int(39) == 1) and (options_count < 6) and (udobrenie_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 120), NodeUdobrenie);
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(40) == 1) and (options_count < 6) and (jackalgun_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 121), NodeJackalGun);
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    if ((get_sfall_global_int(41) == 1) and (options_count < 6) and (sugarmeat_shown == 0)) then begin
        if (options_count <= 4) then begin
            sayOption(message_str(78, 122), NodeSugarMeat);
        end
        else begin
            sayOption(message_str(78, 103), Node11);
        end
        options_count := options_count + 1;
    end
    sayOption(message_str(78, 104), Node11);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure Node2
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 295)) then begin
        displayGfx("PCX/HMS/watrdet1F.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/watrdet1S.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 294)) then begin
        displayGfx("PCX/HMS/watrdet2F.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/watrdet2S.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 293)) then begin
        displayGfx("PCX/HMS/watrdet3F.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/watrdet3S.pcx", 22, 133, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 293) and obj_carrying_pid_obj(dude_obj, 294) and obj_carrying_pid_obj(dude_obj, 295)) then begin
        displayGfx("PCX/HMS/watzpchF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/watzpchS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 4) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 4) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 4) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 20) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 30) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 15) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 293) and obj_carrying_pid_obj(dude_obj, 294) and obj_carrying_pid_obj(dude_obj, 295) and (get_critter_stat(dude_obj, 0) >= 4) and (get_critter_stat(dude_obj, 4) >= 4) and (get_critter_stat(dude_obj, 5) >= 4) and (has_skill(dude_obj, 13) >= 20) and (has_skill(dude_obj, 12) >= 30) and (has_skill(dude_obj, 9) >= 15)) then begin
        sayOption(message_str(78, 109), Node3);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure Node3
begin
    call refresh_all();
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 293));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 294));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 295));
    add_obj_to_inven(dude_obj, create_object_sid(296, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure Node_Exit
begin
    game_ui_enable;
end

procedure refresh_all
begin
    selectWin("fxtools");
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 22, 13, 170, 60);
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 22, 73, 170, 60);
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 22, 133, 170, 60);
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 22, 193, 170, 60);
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 22, 253, 170, 60);
    showWin;
    selectWin("fxresult");
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 24, 14, 170, 60);
    displayGfx("PCX/HMS/HMS_Blanc.pcx", 24, 74, 170, 60);
    showWin;
    selectWin("fxskills");
    displayGfx("PCX/fxskills.pcx", 0, 0, 183, 500);
    setFont(4);
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    setTextColor(0.50000, 0.50000, 0.50000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    format(message_str(78, 70) + "   ", 15, 220, 168, 20, 0);
    format(message_str(78, 71) + "   ", 15, 240, 168, 20, 0);
    format(message_str(78, 72) + "   ", 15, 260, 168, 20, 0);
    format(message_str(78, 73) + "   ", 15, 280, 168, 20, 0);
    format(message_str(78, 74) + "   ", 15, 300, 168, 20, 0);
    format(message_str(78, 75) + "   ", 15, 320, 168, 20, 0);
    showWin;
end

procedure NodeMiss
begin
    sayReply(-1, message_str(78, random(13, 16)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeBuzzPart
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 484)) then begin
        displayGfx("PCX/HMS/buzzdet1F.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/buzzdet1S.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 485)) then begin
        displayGfx("PCX/HMS/buzzdet2F.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/buzzdet2S.pcx", 22, 73, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 484) and obj_carrying_pid_obj(dude_obj, 485)) then begin
        displayGfx("PCX/HMS/buzzdetlF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/buzzdetlS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 1) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 1) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 1) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 1, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 1, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 1, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 5, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 5, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 5, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 484) and obj_carrying_pid_obj(dude_obj, 485) and (get_critter_stat(dude_obj, 0) >= 1) and (get_critter_stat(dude_obj, 4) >= 1) and (get_critter_stat(dude_obj, 5) >= 1) and (has_skill(dude_obj, 13) >= 5) and (has_skill(dude_obj, 12) >= 5) and (has_skill(dude_obj, 9) >= 5)) then begin
        sayOption(message_str(78, 109), NodeBuzzPartOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeBuzzPartOK
begin
    call refresh_all();
    game_time_advance(game_ticks(600));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    set_sfall_global(30, 2);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 484));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 485));
    add_obj_to_inven(dude_obj, create_object_sid(486, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeFakeArmor
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 113)) then begin
        displayGfx("PCX/HMS/sctarm1F.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/sctarm1S.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 435)) then begin
        displayGfx("PCX/HMS/paintF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/paintS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/nitkiF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/nitkiS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 436)) then begin
        displayGfx("PCX/HMS/lavskinF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/lavskinS.pcx", 22, 193, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 113) and obj_carrying_pid_obj(dude_obj, 435) and obj_carrying_pid_obj(dude_obj, 423) and obj_carrying_pid_obj(dude_obj, 436)) then begin
        displayGfx("PCX/HMS/scutarmF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/scutarmS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 25) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 15) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 15) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 5, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 5, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 5, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 25, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 15, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 15, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 113) and obj_carrying_pid_obj(dude_obj, 435) and obj_carrying_pid_obj(dude_obj, 423) and obj_carrying_pid_obj(dude_obj, 436) and (get_critter_stat(dude_obj, 0) >= 5) and (get_critter_stat(dude_obj, 4) >= 5) and (get_critter_stat(dude_obj, 5) >= 5) and (has_skill(dude_obj, 13) >= 25) and (has_skill(dude_obj, 12) >= 15) and (has_skill(dude_obj, 9) >= 15)) then begin
        sayOption(message_str(78, 109), NodeFakeArmorOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeFakeArmorOK
begin
    call refresh_all();
    game_time_advance(game_ticks(60 * 60 * 5));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 113));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 435));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 423));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 436));
    add_obj_to_inven(dude_obj, create_object_sid(123, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeElectroTrap
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 57)) then begin
        displayGfx("PCX/HMS/elpickF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/elpickS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 420)) then begin
        displayGfx("PCX/HMS/forkF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/forkS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/nitkiF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/nitkiS.pcx", 22, 133, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 57) and obj_carrying_pid_obj(dude_obj, 420) and obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/eltrapF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/eltrapS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 3) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 47) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 52) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 34) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 3, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 6, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 6, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 47, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 52, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 34, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 57) and obj_carrying_pid_obj(dude_obj, 420) and obj_carrying_pid_obj(dude_obj, 423) and (get_critter_stat(dude_obj, 0) >= 3) and (get_critter_stat(dude_obj, 4) >= 6) and (get_critter_stat(dude_obj, 5) >= 6) and (has_skill(dude_obj, 13) >= 47) and (has_skill(dude_obj, 12) >= 52) and (has_skill(dude_obj, 9) >= 34)) then begin
        sayOption(message_str(78, 109), NodeElectroTrapOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeElectroTrapOK
begin
    call refresh_all();
    game_time_advance(game_ticks(4800));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 57));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 420));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 423));
    add_obj_to_inven(dude_obj, create_object_sid(48, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeExplTrap
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 215)) then begin
        displayGfx("PCX/HMS/grenadeF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/grenadeS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/nitkiF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/nitkiS.pcx", 22, 73, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 215) and obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/exptrapF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/exptrapS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 3) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 3) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 17) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 23) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 15) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 3, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 3, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 7, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 17, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 23, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 15, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 215) and obj_carrying_pid_obj(dude_obj, 423) and (get_critter_stat(dude_obj, 0) >= 3) and (get_critter_stat(dude_obj, 4) >= 3) and (get_critter_stat(dude_obj, 5) >= 7) and (has_skill(dude_obj, 13) >= 17) and (has_skill(dude_obj, 12) >= 23) and (has_skill(dude_obj, 9) >= 15)) then begin
        sayOption(message_str(78, 109), NodeExplTrapOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeExplTrapOK
begin
    call refresh_all();
    game_time_advance(game_ticks(600));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 215));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 423));
    add_obj_to_inven(dude_obj, create_object_sid(49, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeButchKnife
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 66)) then begin
        displayGfx("PCX/HMS/tesakF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/tesakS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 306)) then begin
        displayGfx("PCX/HMS/stoneF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/stoneS.pcx", 22, 73, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 66) and obj_carrying_pid_obj(dude_obj, 306)) then begin
        displayGfx("PCX/HMS/tesak2F.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/tesak2S.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 2) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 28) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 14) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 14) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 7, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 2, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 6, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 28, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 14, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 14, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 66) and obj_carrying_pid_obj(dude_obj, 306) and (get_critter_stat(dude_obj, 0) >= 7) and (get_critter_stat(dude_obj, 4) >= 2) and (get_critter_stat(dude_obj, 5) >= 6) and (has_skill(dude_obj, 13) >= 28) and (has_skill(dude_obj, 12) >= 14) and (has_skill(dude_obj, 9) >= 14)) then begin
        sayOption(message_str(78, 109), NodeButchKnifeOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeButchKnifeOK
begin
    call refresh_all();
    game_time_advance(game_ticks(7200));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 66));
    add_obj_to_inven(dude_obj, create_object_sid(68, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeRustyArmor
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 437)) then begin
        displayGfx("PCX/HMS/tinrollF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/tinrollS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 108)) then begin
        displayGfx("PCX/HMS/hummerF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/hummerS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 84)) then begin
        displayGfx("PCX/HMS/reppistF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/reppistS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 244)) then begin
        displayGfx("PCX/HMS/screwF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/screwS.pcx", 22, 193, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 437) and obj_carrying_pid_obj(dude_obj, 108) and obj_carrying_pid_obj(dude_obj, 84) and obj_carrying_pid_obj(dude_obj, 244)) then begin
        displayGfx("PCX/HMS/kirsarmF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/kirsarmS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 8) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 64) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 39) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 35) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 7, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 5, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 8, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 64, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 39, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 35, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 437) and obj_carrying_pid_obj(dude_obj, 108) and obj_carrying_pid_obj(dude_obj, 84) and obj_carrying_pid_obj(dude_obj, 244) and (get_critter_stat(dude_obj, 0) >= 7) and (get_critter_stat(dude_obj, 4) >= 5) and (get_critter_stat(dude_obj, 5) >= 8) and (has_skill(dude_obj, 13) >= 64) and (has_skill(dude_obj, 12) >= 39) and (has_skill(dude_obj, 9) >= 35)) then begin
        sayOption(message_str(78, 109), NodeRustyArmorOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeRustyArmorOK
begin
    call refresh_all();
    game_time_advance(game_ticks(7200));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 437));
    add_obj_to_inven(dude_obj, create_object_sid(118, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeBazooka
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 111)) then begin
        displayGfx("PCX/HMS/pipeF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/pipeS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 411)) then begin
        displayGfx("PCX/HMS/boltF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/boltS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 423)) then begin
        displayGfx("PCX/HMS/nitkiF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/nitkiS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 244)) then begin
        displayGfx("PCX/HMS/screwF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/screwS.pcx", 22, 193, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 426)) then begin
        displayGfx("PCX/HMS/plateF.pcx", 22, 253, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/plateS.pcx", 22, 253, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 111) and obj_carrying_pid_obj(dude_obj, 411) and obj_carrying_pid_obj(dude_obj, 423) and obj_carrying_pid_obj(dude_obj, 244) and obj_carrying_pid_obj(dude_obj, 426)) then begin
        displayGfx("PCX/HMS/rcktlncF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/rcktlncS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 69) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 72) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 54) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 7, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 6, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 6, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 69, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 72, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 54, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 111) and obj_carrying_pid_obj(dude_obj, 411) and obj_carrying_pid_obj(dude_obj, 423) and obj_carrying_pid_obj(dude_obj, 244) and obj_carrying_pid_obj(dude_obj, 426) and (get_critter_stat(dude_obj, 0) >= 7) and (get_critter_stat(dude_obj, 4) >= 6) and (get_critter_stat(dude_obj, 5) >= 6) and (has_skill(dude_obj, 13) >= 69) and (has_skill(dude_obj, 12) >= 72) and (has_skill(dude_obj, 9) >= 54)) then begin
        sayOption(message_str(78, 109), NodeBazookaOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeBazookaOK
begin
    call refresh_all();
    game_time_advance(game_ticks(7200));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 111));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 411));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 423));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 426));
    add_obj_to_inven(dude_obj, create_object_sid(197, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeHandGrenade
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 421)) then begin
        displayGfx("PCX/HMS/gvozdiF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/gvozdiS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 422)) then begin
        displayGfx("PCX/HMS/matchesF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/matchesS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 438)) then begin
        displayGfx("PCX/HMS/tincanF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/tincanS.pcx", 22, 133, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 421) and obj_carrying_pid_obj(dude_obj, 422) and obj_carrying_pid_obj(dude_obj, 438)) then begin
        displayGfx("PCX/HMS/hmgrenF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/hmgrenS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 51) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 43) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 68) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 5, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 6, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 5, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 51, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 43, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 68, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 421) and obj_carrying_pid_obj(dude_obj, 422) and obj_carrying_pid_obj(dude_obj, 438) and (get_critter_stat(dude_obj, 0) >= 5) and (get_critter_stat(dude_obj, 4) >= 6) and (get_critter_stat(dude_obj, 5) >= 5) and (has_skill(dude_obj, 13) >= 51) and (has_skill(dude_obj, 12) >= 43) and (has_skill(dude_obj, 9) >= 68)) then begin
        sayOption(message_str(78, 109), NodeHandGrenadeOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeHandGrenadeOK
begin
    call refresh_all();
    game_time_advance(game_ticks(1800));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 421));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 422));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 438));
    add_obj_to_inven(dude_obj, create_object_sid(219, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeEnergetic
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 237)) then begin
        displayGfx("PCX/HMS/spotsupF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/spotsupS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 239)) then begin
        displayGfx("PCX/HMS/pearF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/pearS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 238)) then begin
        displayGfx("PCX/HMS/appleF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/appleS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 222)) then begin
        displayGfx("PCX/HMS/healupF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/healupS.pcx", 22, 193, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 237) and obj_carrying_pid_obj(dude_obj, 239) and obj_carrying_pid_obj(dude_obj, 238) and obj_carrying_pid_obj(dude_obj, 222)) then begin
        displayGfx("PCX/HMS/energtkF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/energtkS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 1) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 5) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 10) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 64) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 35) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 1, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 5, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 6, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 10, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 64, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 35, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 237) and obj_carrying_pid_obj(dude_obj, 239) and obj_carrying_pid_obj(dude_obj, 238) and obj_carrying_pid_obj(dude_obj, 222) and (get_critter_stat(dude_obj, 0) >= 1) and (get_critter_stat(dude_obj, 4) >= 5) and (get_critter_stat(dude_obj, 5) >= 6) and (has_skill(dude_obj, 13) >= 10) and (has_skill(dude_obj, 12) >= 64) and (has_skill(dude_obj, 9) >= 35)) then begin
        sayOption(message_str(78, 109), NodeEnergeticOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeEnergeticOK
begin
    call refresh_all();
    game_time_advance(game_ticks(600));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 237));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 239));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 238));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 222));
    add_obj_to_inven(dude_obj, create_object_sid(246, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeUdobrenie
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 439)) then begin
        displayGfx("PCX/HMS/leafsF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/leafsS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 440)) then begin
        displayGfx("PCX/HMS/zolaF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/zolaS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 238)) then begin
        displayGfx("PCX/HMS/appleF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/appleS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 234)) then begin
        displayGfx("PCX/HMS/whiskyF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/whiskyS.pcx", 22, 193, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 439) and obj_carrying_pid_obj(dude_obj, 440) and obj_carrying_pid_obj(dude_obj, 238) and obj_carrying_pid_obj(dude_obj, 234)) then begin
        displayGfx("PCX/HMS/udobrenF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/udobrenS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 0, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 0, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 0, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 0, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 0, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 0, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 439) and obj_carrying_pid_obj(dude_obj, 440) and obj_carrying_pid_obj(dude_obj, 238) and obj_carrying_pid_obj(dude_obj, 234) and (get_critter_stat(dude_obj, 0) >= 0) and (get_critter_stat(dude_obj, 4) >= 0) and (get_critter_stat(dude_obj, 5) >= 0) and (has_skill(dude_obj, 13) >= 0) and (has_skill(dude_obj, 12) >= 0) and (has_skill(dude_obj, 9) >= 0)) then begin
        sayOption(message_str(78, 109), NodeUdobrenieOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeUdobrenieOK
begin
    call refresh_all();
    game_time_advance(game_ticks(1800));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 439));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 440));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 238));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 234));
    add_obj_to_inven(dude_obj, create_object_sid(305, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeJackalGun
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 488)) then begin
        displayGfx("PCX/HMS/jcklbrlF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/jcklbrlS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 489)) then begin
        displayGfx("PCX/HMS/jckldrmF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/jckldrmS.pcx", 22, 73, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 487)) then begin
        displayGfx("PCX/HMS/jcklhndF.pcx", 22, 133, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/jcklhndS.pcx", 22, 133, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 84)) then begin
        displayGfx("PCX/HMS/reppistF.pcx", 22, 193, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/reppistS.pcx", 22, 193, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 488) and obj_carrying_pid_obj(dude_obj, 489) and obj_carrying_pid_obj(dude_obj, 487) and obj_carrying_pid_obj(dude_obj, 84)) then begin
        displayGfx("PCX/HMS/jcklpstF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/jcklpstS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 6) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 7) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 79) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 49) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 54) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 7, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 6, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 7, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 79, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 49, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 54, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 488) and obj_carrying_pid_obj(dude_obj, 489) and obj_carrying_pid_obj(dude_obj, 487) and obj_carrying_pid_obj(dude_obj, 84) and (get_critter_stat(dude_obj, 0) >= 7) and (get_critter_stat(dude_obj, 4) >= 6) and (get_critter_stat(dude_obj, 5) >= 7) and (has_skill(dude_obj, 13) >= 79) and (has_skill(dude_obj, 12) >= 49) and (has_skill(dude_obj, 9) >= 54)) then begin
        sayOption(message_str(78, 109), NodeJackalGunOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeJackalGunOK
begin
    call refresh_all();
    game_time_advance(game_ticks(7200));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 488));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 489));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 487));
    add_obj_to_inven(dude_obj, create_object_sid(144, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeSugarMeat
begin
    selectWin("fxtools");
    if (obj_carrying_pid_obj(dude_obj, 442)) then begin
        displayGfx("PCX/HMS/lavmtcF.pcx", 22, 13, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/lavmtcS.pcx", 22, 13, 170, 60);
    end
    if (obj_carrying_pid_obj(dude_obj, 443)) then begin
        displayGfx("PCX/HMS/sugarF.pcx", 22, 73, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/sugarS.pcx", 22, 73, 170, 60);
    end
    showWin;
    selectWin("fxresult");
    if (obj_carrying_pid_obj(dude_obj, 442) and obj_carrying_pid_obj(dude_obj, 443)) then begin
        displayGfx("PCX/HMS/lavmtsF.pcx", 24, 14, 170, 60);
    end
    else begin
        displayGfx("PCX/HMS/lavmtsS.pcx", 24, 14, 170, 60);
    end
    showWin;
    selectWin("fxskills");
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 50), 15, 32, 168, 20, 0);
    if (get_critter_stat(dude_obj, 0) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 60) + get_critter_stat(dude_obj, 0), 15, 50, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 4) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 61) + get_critter_stat(dude_obj, 4), 15, 70, 168, 20, 0);
    end
    if (get_critter_stat(dude_obj, 5) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 62) + get_critter_stat(dude_obj, 5), 15, 90, 168, 20, 0);
    end
    if (has_skill(dude_obj, 13) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 63) + has_skill(dude_obj, 13), 15, 110, 168, 20, 0);
    end
    if (has_skill(dude_obj, 12) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 64) + has_skill(dude_obj, 12), 15, 130, 168, 20, 0);
    end
    if (has_skill(dude_obj, 9) >= 0) then begin
        setTextColor(0.00000, 0.90000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    else begin
        setTextColor(0.90000, 0.00000, 0.00000);
        format(message_str(78, 65) + has_skill(dude_obj, 9), 15, 150, 168, 20, 0);
    end
    setTextColor(0.90000, 0.90000, 0.00000);
    format(message_str(78, 51), 15, 190, 168, 20, 0);
    if (has_skill(dude_obj, 13) < 100) then begin
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 70) + message_str(78, 105), 15, 220, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 71) + message_str(78, 105), 15, 240, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 72) + message_str(78, 105), 15, 260, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 73) + message_str(78, 105), 15, 280, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 74) + message_str(78, 105), 15, 300, 168, 20, 0);
        setTextColor(0.50000, 0.50000, 0.50000);
        format(message_str(78, 75) + message_str(78, 105), 15, 320, 168, 20, 0);
    end
    else begin
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 70) + 0, 15, 220, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 71) + 0, 15, 240, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 72) + 0, 15, 260, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 73) + 0, 15, 280, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 74) + 0, 15, 300, 168, 20, 0);
        setTextColor(0.70000, 0.70000, 0.70000);
        format(message_str(78, 75) + 0, 15, 320, 168, 20, 0);
    end
    showWin;
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    sayReply(-1, message_str(78, 12));
    if (obj_carrying_pid_obj(dude_obj, 442) and obj_carrying_pid_obj(dude_obj, 443) and (get_critter_stat(dude_obj, 0) >= 0) and (get_critter_stat(dude_obj, 4) >= 0) and (get_critter_stat(dude_obj, 5) >= 0) and (has_skill(dude_obj, 13) >= 0) and (has_skill(dude_obj, 12) >= 0) and (has_skill(dude_obj, 9) >= 0)) then begin
        sayOption(message_str(78, 109), NodeSugarMeatOK);
    end
    else begin
        sayOption(message_str(78, 109), NodeMiss);
    end
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

procedure NodeSugarMeatOK
begin
    call refresh_all();
    game_time_advance(game_ticks(600));
    setTextColor(0.00000, 0.90000, 0.00000);
    setHighlightColor(0.80000, 1.00000, 0.80000);
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 442));
    rm_obj_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 443));
    add_obj_to_inven(dude_obj, create_object_sid(315, 1, 2, -1));
    sayReply(-1, message_str(78, random(17, 19)));
    sayOption(message_str(78, 101), Node1);
    sayReplyFlags(2);
    sayOption(message_str(78, 100), Node_Exit);
    sayReplyFlags(0);
    sayOption(" ", Node_Exit);
end

