procedure start;
procedure global_check;
procedure combat_check;
procedure dialog_check;
procedure organizer_check;
procedure automap_check;
procedure combat_enter_check;

variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable cmbt_musique;
variable dialog_room;
variable mouse_1_is_pressed;
variable act_hnd;
variable rad_amount;


procedure start
begin
    set_global_script_type(1);
    set_global_script_repeat(1);
    call global_check();
end

procedure global_check
begin
    if (((get_game_mode bwand 64) != 0) and (cmbt_musique == 0) or (((get_game_mode bwand 64) == 0) and (cmbt_musique != 0))) then begin
        call combat_check();
    end
    if (((get_game_mode bwand 4) != 0) and (dialog_room == 0) or (((get_game_mode bwand 4) == 0) and (dialog_room != 0))) then begin
        call dialog_check();
    end
    if (global_var(6) == 2) then begin
        if ((get_mouse_x > ((get_screen_width / 2) - 52)) and (get_mouse_x < ((get_screen_width / 2) + 147)) and (get_mouse_y > (get_screen_height - 70)) and (get_mouse_y < get_screen_height)) then begin
            call combat_enter_check();
        end
        if (key_pressed(30)) then begin
            create_message_window(message_str(10, 802));
        end
    end
    if (global_var(67) == 0) then begin
        if ((get_mouse_x > ((get_screen_width / 2) + 205)) and (get_mouse_x < ((get_screen_width / 2) + 251)) and (get_mouse_y > (get_screen_height - 23)) and (get_mouse_y < (get_screen_height - 2))) then begin
            call organizer_check();
        end
        if (key_pressed(25) or key_pressed(44) and not(game_ui_is_disabled)) then begin
            create_message_window(message_str(10, 801));
        end
        if ((get_mouse_x > ((get_screen_width / 2) + 205)) and (get_mouse_x < ((get_screen_width / 2) + 251)) and (get_mouse_y > (get_screen_height - 60)) and (get_mouse_y < (get_screen_height - 39))) then begin
        end
        if (key_pressed(56) or key_pressed(184)) then begin
        end
        else begin
            if (key_pressed(15)) then begin
            end
        end
    end
    if (not(metarule(22, 0) == 1)) then begin
        if ((metarule(45, 0) >= 1064) or ((metarule(44, 0) > 468) and (metarule(45, 0) < 182) and (metarule(44, 0) < 690))) then begin
            if (game_time_in_seconds >= (global_var(366) + 50000)) then begin
                set_global_var(366, game_time_in_seconds);
                if (difficulty_level == 0) then begin
                    rad_amount := random(3, 4);
                end
                else begin
                    if (difficulty_level == 1) then begin
                        rad_amount := random(6, 8);
                    end
                    else begin
                        rad_amount := random(10, 15);
                    end
                end
                if ((obj_pid(critter_inven_obj(dude_obj, 0)) != 124) and (cur_map_index != 34) and (cur_map_index != 26)) then begin
                    radiation_inc(dude_obj, rad_amount);
                    if (get_critter_stat(dude_obj, 37) <= 300) then begin
                        display_msg(message_str(10, 854) + floor(rad_amount - (rad_amount * get_critter_stat(dude_obj, 31) / 100)));
                    end
                end
                if (get_critter_stat(dude_obj, 37) > 300) then begin
                    display_msg(message_str(10, 872) + get_critter_stat(dude_obj, 37) + message_str(10, 868));
                end
            end
        end
        else begin
            if ((metarule(44, 0) < 1030) and (metarule(45, 0) < 956)) then begin
                if (game_time_in_seconds >= (global_var(366) + 30000)) then begin
                    set_global_var(366, game_time_in_seconds);
                    if (difficulty_level == 0) then begin
                        rad_amount := random(3, 4);
                    end
                    else begin
                        if (difficulty_level == 1) then begin
                            rad_amount := random(6, 8);
                        end
                        else begin
                            rad_amount := random(10, 15);
                        end
                    end
                    if ((obj_pid(critter_inven_obj(dude_obj, 0)) != 124) and (cur_map_index != 34) and (cur_map_index != 26)) then begin
                        radiation_inc(dude_obj, rad_amount);
                        if (get_critter_stat(dude_obj, 37) <= 300) then begin
                            display_msg(message_str(10, 854) + floor(rad_amount - (rad_amount * get_critter_stat(dude_obj, 31) / 100)));
                        end
                    end
                    if (get_critter_stat(dude_obj, 37) > 300) then begin
                        display_msg(message_str(10, 872) + get_critter_stat(dude_obj, 37) + message_str(10, 868));
                    end
                end
            end
            else begin
                if (game_time_in_seconds >= (global_var(366) + 40000)) then begin
                    set_global_var(366, game_time_in_seconds);
                    if (difficulty_level == 0) then begin
                        rad_amount := random(3, 4);
                    end
                    else begin
                        if (difficulty_level == 1) then begin
                            rad_amount := random(6, 8);
                        end
                        else begin
                            rad_amount := random(10, 15);
                        end
                    end
                    if ((obj_pid(critter_inven_obj(dude_obj, 0)) != 124) and (cur_map_index != 34) and (cur_map_index != 26)) then begin
                        radiation_inc(dude_obj, rad_amount);
                        if (get_critter_stat(dude_obj, 37) <= 300) then begin
                            display_msg(message_str(10, 854) + floor(rad_amount - (rad_amount * get_critter_stat(dude_obj, 31) / 100)));
                        end
                    end
                    if (get_critter_stat(dude_obj, 37) > 300) then begin
                        display_msg(message_str(10, 872) + get_critter_stat(dude_obj, 37) + message_str(10, 868));
                    end
                end
            end
        end
    end
end

procedure combat_check
begin
    if (anim_busy(dude_obj) and (get_sfall_global_int(6) == 1)) then begin
        set_sfall_global(6, 1);
    end
    if (active_hand == 0) then begin
        act_hnd := 2;
    end
    else begin
        act_hnd := 1;
    end
    if ((art_anim(obj_art_fid(dude_obj)) == 45) or (art_anim(obj_art_fid(dude_obj)) == 46) and ((obj_pid(critter_inven_obj(dude_obj, act_hnd)) == 93) or (obj_pid(critter_inven_obj(dude_obj, act_hnd)) == 94)) and (get_sfall_global_int(6) == 0)) then begin
        if (get_critter_stat(dude_obj, 0) >= 9) then begin
            if (random(0, 100) <= 45) then begin
                set_sfall_global(6, 1);
                critter_injure(dude_obj, 32);
                display_msg(message_str(10, random(268, 269)));
                critter_dmg(dude_obj, random(5, 10), 0 bwor 256);
            end
        end
        else begin
            if (random(0, 100) <= 65) then begin
                set_sfall_global(6, 1);
                critter_injure(dude_obj, 32);
                display_msg(message_str(10, random(268, 269)));
                critter_dmg(dude_obj, random(10, 20), 0 bwor 256);
            end
        end
    end
end

procedure dialog_check
begin
    if ((get_screen_width == 800) and (get_screen_height == 600)) then begin
        if ((get_game_mode bwand 4) != 0) then begin
            if (dialog_room == 0) then begin
                dialog_room := 1;
                createWin("room_lft", 0, 0, 80, 500);
                selectWin("room_lft");
                displayGfx("PCX/room_lft.pcx", 0, 0, 80, 500);
                showWin;
                createWin("room_up", 80, 0, 640, 10);
                selectWin("room_up");
                displayGfx("PCX/room_up.pcx", 0, 0, 640, 10);
                showWin;
                createWin("room_rgt", 720, 0, 80, 500);
                selectWin("room_rgt");
                displayGfx("PCX/room_rgt.pcx", 0, 0, 80, 500);
                showWin;
                createWin("room_dwn", 80, 490, 640, 10);
                selectWin("room_dwn");
                displayGfx("PCX/room_dwn.pcx", 0, 0, 640, 10);
                showWin;
            end
        end
        else begin
            if (dialog_room != 0) then begin
                deleteWin("room_lft");
                deleteWin("room_up");
                deleteWin("room_rgt");
                deleteWin("room_dwn");
                dialog_room := 0;
            end
        end
    end
end

procedure organizer_check
begin
    if ((get_mouse_buttons == 1) and (mouse_1_is_pressed == 0)) then begin
        create_message_window(message_str(10, 801));
        mouse_1_is_pressed := 1;
    end
    if ((get_mouse_buttons == 0) and (mouse_1_is_pressed == 1)) then begin
        mouse_1_is_pressed := 0;
    end
end

procedure automap_check
begin
    if ((get_mouse_buttons == 1) and (mouse_1_is_pressed == 0)) then begin
        create_message_window(message_str(10, 800));
        mouse_1_is_pressed := 1;
    end
    if ((get_mouse_buttons == 0) and (mouse_1_is_pressed == 1)) then begin
        mouse_1_is_pressed := 0;
    end
end

procedure combat_enter_check
begin
    if ((get_mouse_buttons == 1) and (mouse_1_is_pressed == 0)) then begin
        create_message_window(message_str(10, 802));
        mouse_1_is_pressed := 1;
    end
    if ((get_mouse_buttons == 0) and (mouse_1_is_pressed == 1)) then begin
        mouse_1_is_pressed := 0;
    end
end

