variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;

procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure drop_p_proc;
procedure is_dropping_p_proc;
procedure pickup_p_proc;
procedure NoteBook_Start;
procedure NoteBook1_Start;
procedure NoteBook_End;
procedure vide;


procedure start
begin
end

procedure description_p_proc
begin
end

procedure look_at_p_proc
begin
end

procedure damage_p_proc
begin
end

procedure use_p_proc
begin
    if ((get_game_mode bwand 4096) != 0) then begin
        display_msg(message_str(12, random(10, 14)));
    end
    else begin
        animate_move_obj_to_tile(dude_obj, tile_num(dude_obj), 0 bwor 16);
        if (global_var(6) < 2) then begin
            call NoteBook_Start();
        end
        else begin
            call NoteBook1_Start();
        end
    end
end

procedure use_obj_on_p_proc
begin
end

procedure use_skill_on_p_proc
begin
end

procedure drop_p_proc
begin
end

procedure is_dropping_p_proc
begin
end

procedure pickup_p_proc
begin
end

procedure NoteBook_Start
begin
    createWin("NoteBook", (get_screen_width / 2) - 400, (get_screen_height / 2) - 300, 800, 500);
    selectWin("NoteBook");
    display("PCX/NoteBook.pcx");
    setFont(3);
    setTextColor(0.00000, 0.00000, 0.00000);
    format(" " + message_str(61, 100), 127, 60, 260, 20, 0);
    if (local_var(0) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("1) " + message_str(61, 101), 127, 90, 260, 20, 0);
                set_local_var(0, 101);
            end
            else begin
                format("1) " + message_str(61, 101) + message_str(61, 200), 127, 90, 260, 20, 0);
                set_local_var(0, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("1) " + message_str(61, 102), 127, 90, 260, 20, 0);
                    set_local_var(0, 102);
                end
                else begin
                    format("1) " + message_str(61, 102) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("1) " + message_str(61, 103), 127, 90, 260, 20, 0);
                        set_local_var(0, 103);
                    end
                    else begin
                        format("1) " + message_str(61, 103) + message_str(61, 200), 127, 90, 260, 20, 0);
                        set_local_var(0, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("1) " + message_str(61, 104), 127, 90, 260, 20, 0);
                            set_local_var(0, 104);
                        end
                        else begin
                            format("1) " + message_str(61, 104) + message_str(61, 200), 127, 90, 260, 20, 0);
                            set_local_var(0, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("1) " + message_str(61, 105), 127, 90, 260, 20, 0);
                                set_local_var(0, 105);
                            end
                            else begin
                                format("1) " + message_str(61, 105) + message_str(61, 200), 127, 90, 260, 20, 0);
                                set_local_var(0, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("1) " + message_str(61, 106), 127, 90, 260, 20, 0);
                                    set_local_var(0, 106);
                                end
                                else begin
                                    format("1) " + message_str(61, 106) + message_str(61, 200), 127, 90, 260, 20, 0);
                                    set_local_var(0, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("1) " + message_str(61, 107), 127, 90, 260, 20, 0);
                                        set_local_var(0, 107);
                                    end
                                    else begin
                                        format("1) " + message_str(61, 107) + message_str(61, 200), 127, 90, 260, 20, 0);
                                        set_local_var(0, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("1) " + message_str(61, 108), 127, 90, 260, 20, 0);
                                            set_local_var(0, 108);
                                        end
                                        else begin
                                            format("1) " + message_str(61, 108) + message_str(61, 200), 127, 90, 260, 20, 0);
                                            set_local_var(0, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("1) " + message_str(61, 109), 127, 90, 260, 20, 0);
                                                set_local_var(0, 109);
                                            end
                                            else begin
                                                format("1) " + message_str(61, 109) + message_str(61, 200), 127, 90, 260, 20, 0);
                                                set_local_var(0, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("1) " + message_str(61, 110), 127, 90, 260, 20, 0);
                                                    set_local_var(0, 110);
                                                end
                                                else begin
                                                    format("1) " + message_str(61, 110) + message_str(61, 200), 127, 90, 260, 20, 0);
                                                    set_local_var(0, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("1) " + message_str(61, 111), 127, 90, 260, 20, 0);
                                                        set_local_var(0, 111);
                                                    end
                                                    else begin
                                                        format("1) " + message_str(61, 111) + message_str(61, 200), 127, 90, 260, 20, 0);
                                                        set_local_var(0, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(0) > 1000) then begin
            format("1) " + message_str(61, local_var(0) / 10) + message_str(61, 200), 127, 90, 260, 20, 0);
        end
        else begin
            if (local_var(0) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("1) " + message_str(61, 101), 127, 90, 260, 20, 0);
                    set_local_var(0, 101);
                end
                else begin
                    format("1) " + message_str(61, 101) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1010);
                end
            end
            if (local_var(0) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("1) " + message_str(61, 102), 127, 90, 260, 20, 0);
                    set_local_var(0, 102);
                end
                else begin
                    format("1) " + message_str(61, 102) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1020);
                end
            end
            if (local_var(0) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("1) " + message_str(61, 103), 127, 90, 260, 20, 0);
                    set_local_var(0, 103);
                end
                else begin
                    format("1) " + message_str(61, 103) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1030);
                end
            end
            if (local_var(0) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("1) " + message_str(61, 104), 127, 90, 260, 20, 0);
                    set_local_var(0, 104);
                end
                else begin
                    format("1) " + message_str(61, 104) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1040);
                end
            end
            if (local_var(0) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("1) " + message_str(61, 105), 127, 90, 260, 20, 0);
                    set_local_var(0, 105);
                end
                else begin
                    format("1) " + message_str(61, 105) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1050);
                end
            end
            if (local_var(0) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("1) " + message_str(61, 106), 127, 90, 260, 20, 0);
                    set_local_var(0, 106);
                end
                else begin
                    format("1) " + message_str(61, 106) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1060);
                end
            end
            if (local_var(0) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("1) " + message_str(61, 107), 127, 90, 260, 20, 0);
                    set_local_var(0, 107);
                end
                else begin
                    format("1) " + message_str(61, 107) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1070);
                end
            end
            if (local_var(0) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("1) " + message_str(61, 108), 127, 90, 260, 20, 0);
                    set_local_var(0, 108);
                end
                else begin
                    format("1) " + message_str(61, 108) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1080);
                end
            end
            if (local_var(0) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("1) " + message_str(61, 109), 127, 90, 260, 20, 0);
                    set_local_var(0, 109);
                end
                else begin
                    format("1) " + message_str(61, 109) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1090);
                end
            end
            if (local_var(0) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("1) " + message_str(61, 110), 127, 90, 260, 20, 0);
                    set_local_var(0, 110);
                end
                else begin
                    format("1) " + message_str(61, 110) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1100);
                end
            end
            if (local_var(0) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("1) " + message_str(61, 111), 127, 90, 260, 20, 0);
                    set_local_var(0, 111);
                end
                else begin
                    format("1) " + message_str(61, 111) + message_str(61, 200), 127, 90, 260, 20, 0);
                    set_local_var(0, 1110);
                end
            end
        end
    end
    if (local_var(1) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("2) " + message_str(61, 101), 127, 120, 260, 20, 0);
                set_local_var(1, 101);
            end
            else begin
                format("2) " + message_str(61, 101) + message_str(61, 200), 127, 120, 260, 20, 0);
                set_local_var(1, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("2) " + message_str(61, 102), 127, 120, 260, 20, 0);
                    set_local_var(1, 102);
                end
                else begin
                    format("2) " + message_str(61, 102) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("2) " + message_str(61, 103), 127, 120, 260, 20, 0);
                        set_local_var(1, 103);
                    end
                    else begin
                        format("2) " + message_str(61, 103) + message_str(61, 200), 127, 120, 260, 20, 0);
                        set_local_var(1, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("2) " + message_str(61, 104), 127, 120, 260, 20, 0);
                            set_local_var(1, 104);
                        end
                        else begin
                            format("2) " + message_str(61, 104) + message_str(61, 200), 127, 120, 260, 20, 0);
                            set_local_var(1, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("2) " + message_str(61, 105), 127, 120, 260, 20, 0);
                                set_local_var(1, 105);
                            end
                            else begin
                                format("2) " + message_str(61, 105) + message_str(61, 200), 127, 120, 260, 20, 0);
                                set_local_var(1, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("2) " + message_str(61, 106), 127, 120, 260, 20, 0);
                                    set_local_var(1, 106);
                                end
                                else begin
                                    format("2) " + message_str(61, 106) + message_str(61, 200), 127, 120, 260, 20, 0);
                                    set_local_var(1, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("2) " + message_str(61, 107), 127, 120, 260, 20, 0);
                                        set_local_var(1, 107);
                                    end
                                    else begin
                                        format("2) " + message_str(61, 107) + message_str(61, 200), 127, 120, 260, 20, 0);
                                        set_local_var(1, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("2) " + message_str(61, 108), 127, 120, 260, 20, 0);
                                            set_local_var(1, 108);
                                        end
                                        else begin
                                            format("2) " + message_str(61, 108) + message_str(61, 200), 127, 120, 260, 20, 0);
                                            set_local_var(1, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("2) " + message_str(61, 109), 127, 120, 260, 20, 0);
                                                set_local_var(1, 109);
                                            end
                                            else begin
                                                format("2) " + message_str(61, 109) + message_str(61, 200), 127, 120, 260, 20, 0);
                                                set_local_var(1, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("2) " + message_str(61, 110), 127, 120, 260, 20, 0);
                                                    set_local_var(1, 110);
                                                end
                                                else begin
                                                    format("2) " + message_str(61, 110) + message_str(61, 200), 127, 120, 260, 20, 0);
                                                    set_local_var(1, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("2) " + message_str(61, 111), 127, 120, 260, 20, 0);
                                                        set_local_var(1, 111);
                                                    end
                                                    else begin
                                                        format("2) " + message_str(61, 111) + message_str(61, 200), 127, 120, 260, 20, 0);
                                                        set_local_var(1, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(1) > 1000) then begin
            format("2) " + message_str(61, local_var(1) / 10) + message_str(61, 200), 127, 120, 260, 20, 0);
        end
        else begin
            if (local_var(1) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("2) " + message_str(61, 101), 127, 120, 260, 20, 0);
                    set_local_var(1, 101);
                end
                else begin
                    format("2) " + message_str(61, 101) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1010);
                end
            end
            if (local_var(1) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("2) " + message_str(61, 102), 127, 120, 260, 20, 0);
                    set_local_var(1, 102);
                end
                else begin
                    format("2) " + message_str(61, 102) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1020);
                end
            end
            if (local_var(1) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("2) " + message_str(61, 103), 127, 120, 260, 20, 0);
                    set_local_var(1, 103);
                end
                else begin
                    format("2) " + message_str(61, 103) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1030);
                end
            end
            if (local_var(1) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("2) " + message_str(61, 104), 127, 120, 260, 20, 0);
                    set_local_var(1, 104);
                end
                else begin
                    format("2) " + message_str(61, 104) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1040);
                end
            end
            if (local_var(1) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("2) " + message_str(61, 105), 127, 120, 260, 20, 0);
                    set_local_var(1, 105);
                end
                else begin
                    format("2) " + message_str(61, 105) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1050);
                end
            end
            if (local_var(1) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("2) " + message_str(61, 106), 127, 120, 260, 20, 0);
                    set_local_var(1, 106);
                end
                else begin
                    format("2) " + message_str(61, 106) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1060);
                end
            end
            if (local_var(1) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("2) " + message_str(61, 107), 127, 120, 260, 20, 0);
                    set_local_var(1, 107);
                end
                else begin
                    format("2) " + message_str(61, 107) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1070);
                end
            end
            if (local_var(1) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("2) " + message_str(61, 108), 127, 120, 260, 20, 0);
                    set_local_var(1, 108);
                end
                else begin
                    format("2) " + message_str(61, 108) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1080);
                end
            end
            if (local_var(1) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("2) " + message_str(61, 109), 127, 120, 260, 20, 0);
                    set_local_var(1, 109);
                end
                else begin
                    format("2) " + message_str(61, 109) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1090);
                end
            end
            if (local_var(1) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("2) " + message_str(61, 110), 127, 120, 260, 20, 0);
                    set_local_var(1, 110);
                end
                else begin
                    format("2) " + message_str(61, 110) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1100);
                end
            end
            if (local_var(1) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("2) " + message_str(61, 111), 127, 120, 260, 20, 0);
                    set_local_var(1, 111);
                end
                else begin
                    format("2) " + message_str(61, 111) + message_str(61, 200), 127, 120, 260, 20, 0);
                    set_local_var(1, 1110);
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("3) " + message_str(61, 101), 127, 150, 260, 20, 0);
                set_local_var(2, 101);
            end
            else begin
                format("3) " + message_str(61, 101) + message_str(61, 200), 127, 150, 260, 20, 0);
                set_local_var(2, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("3) " + message_str(61, 102), 127, 150, 260, 20, 0);
                    set_local_var(2, 102);
                end
                else begin
                    format("3) " + message_str(61, 102) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("3) " + message_str(61, 103), 127, 150, 260, 20, 0);
                        set_local_var(2, 103);
                    end
                    else begin
                        format("3) " + message_str(61, 103) + message_str(61, 200), 127, 150, 260, 20, 0);
                        set_local_var(2, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("3) " + message_str(61, 104), 127, 150, 260, 20, 0);
                            set_local_var(2, 104);
                        end
                        else begin
                            format("3) " + message_str(61, 104) + message_str(61, 200), 127, 150, 260, 20, 0);
                            set_local_var(2, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("3) " + message_str(61, 105), 127, 150, 260, 20, 0);
                                set_local_var(2, 105);
                            end
                            else begin
                                format("3) " + message_str(61, 105) + message_str(61, 200), 127, 150, 260, 20, 0);
                                set_local_var(2, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("3) " + message_str(61, 106), 127, 150, 260, 20, 0);
                                    set_local_var(2, 106);
                                end
                                else begin
                                    format("3) " + message_str(61, 106) + message_str(61, 200), 127, 150, 260, 20, 0);
                                    set_local_var(2, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("3) " + message_str(61, 107), 127, 150, 260, 20, 0);
                                        set_local_var(2, 107);
                                    end
                                    else begin
                                        format("3) " + message_str(61, 107) + message_str(61, 200), 127, 150, 260, 20, 0);
                                        set_local_var(2, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("3) " + message_str(61, 108), 127, 150, 260, 20, 0);
                                            set_local_var(2, 108);
                                        end
                                        else begin
                                            format("3) " + message_str(61, 108) + message_str(61, 200), 127, 150, 260, 20, 0);
                                            set_local_var(2, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("3) " + message_str(61, 109), 127, 150, 260, 20, 0);
                                                set_local_var(2, 109);
                                            end
                                            else begin
                                                format("3) " + message_str(61, 109) + message_str(61, 200), 127, 150, 260, 20, 0);
                                                set_local_var(2, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("3) " + message_str(61, 110), 127, 150, 260, 20, 0);
                                                    set_local_var(2, 110);
                                                end
                                                else begin
                                                    format("3) " + message_str(61, 110) + message_str(61, 200), 127, 150, 260, 20, 0);
                                                    set_local_var(2, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("3) " + message_str(61, 111), 127, 150, 260, 20, 0);
                                                        set_local_var(2, 111);
                                                    end
                                                    else begin
                                                        format("3) " + message_str(61, 111) + message_str(61, 200), 127, 150, 260, 20, 0);
                                                        set_local_var(2, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(2) > 1000) then begin
            format("3) " + message_str(61, local_var(2) / 10) + message_str(61, 200), 127, 150, 260, 20, 0);
        end
        else begin
            if (local_var(2) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("3) " + message_str(61, 101), 127, 150, 260, 20, 0);
                    set_local_var(2, 101);
                end
                else begin
                    format("3) " + message_str(61, 101) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1010);
                end
            end
            if (local_var(2) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("3) " + message_str(61, 102), 127, 150, 260, 20, 0);
                    set_local_var(2, 102);
                end
                else begin
                    format("3) " + message_str(61, 102) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1020);
                end
            end
            if (local_var(2) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("3) " + message_str(61, 103), 127, 150, 260, 20, 0);
                    set_local_var(2, 103);
                end
                else begin
                    format("3) " + message_str(61, 103) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1030);
                end
            end
            if (local_var(2) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("3) " + message_str(61, 104), 127, 150, 260, 20, 0);
                    set_local_var(2, 104);
                end
                else begin
                    format("3) " + message_str(61, 104) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1040);
                end
            end
            if (local_var(2) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("3) " + message_str(61, 105), 127, 150, 260, 20, 0);
                    set_local_var(2, 105);
                end
                else begin
                    format("3) " + message_str(61, 105) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1050);
                end
            end
            if (local_var(2) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("3) " + message_str(61, 106), 127, 150, 260, 20, 0);
                    set_local_var(2, 106);
                end
                else begin
                    format("3) " + message_str(61, 106) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1060);
                end
            end
            if (local_var(2) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("3) " + message_str(61, 107), 127, 150, 260, 20, 0);
                    set_local_var(2, 107);
                end
                else begin
                    format("3) " + message_str(61, 107) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1070);
                end
            end
            if (local_var(2) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("3) " + message_str(61, 108), 127, 150, 260, 20, 0);
                    set_local_var(2, 108);
                end
                else begin
                    format("3) " + message_str(61, 108) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1080);
                end
            end
            if (local_var(2) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("3) " + message_str(61, 109), 127, 150, 260, 20, 0);
                    set_local_var(2, 109);
                end
                else begin
                    format("3) " + message_str(61, 109) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1090);
                end
            end
            if (local_var(2) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("3) " + message_str(61, 110), 127, 150, 260, 20, 0);
                    set_local_var(2, 110);
                end
                else begin
                    format("3) " + message_str(61, 110) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1100);
                end
            end
            if (local_var(2) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("3) " + message_str(61, 111), 127, 150, 260, 20, 0);
                    set_local_var(2, 111);
                end
                else begin
                    format("3) " + message_str(61, 111) + message_str(61, 200), 127, 150, 260, 20, 0);
                    set_local_var(2, 1110);
                end
            end
        end
    end
    if (local_var(3) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("4) " + message_str(61, 101), 127, 180, 260, 20, 0);
                set_local_var(3, 101);
            end
            else begin
                format("4) " + message_str(61, 101) + message_str(61, 200), 127, 180, 260, 20, 0);
                set_local_var(3, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("4) " + message_str(61, 102), 127, 180, 260, 20, 0);
                    set_local_var(3, 102);
                end
                else begin
                    format("4) " + message_str(61, 102) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("4) " + message_str(61, 103), 127, 180, 260, 20, 0);
                        set_local_var(3, 103);
                    end
                    else begin
                        format("4) " + message_str(61, 103) + message_str(61, 200), 127, 180, 260, 20, 0);
                        set_local_var(3, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("4) " + message_str(61, 104), 127, 180, 260, 20, 0);
                            set_local_var(3, 104);
                        end
                        else begin
                            format("4) " + message_str(61, 104) + message_str(61, 200), 127, 180, 260, 20, 0);
                            set_local_var(3, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("4) " + message_str(61, 105), 127, 180, 260, 20, 0);
                                set_local_var(3, 105);
                            end
                            else begin
                                format("4) " + message_str(61, 105) + message_str(61, 200), 127, 180, 260, 20, 0);
                                set_local_var(3, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("4) " + message_str(61, 106), 127, 180, 260, 20, 0);
                                    set_local_var(3, 106);
                                end
                                else begin
                                    format("4) " + message_str(61, 106) + message_str(61, 200), 127, 180, 260, 20, 0);
                                    set_local_var(3, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("4) " + message_str(61, 107), 127, 180, 260, 20, 0);
                                        set_local_var(3, 107);
                                    end
                                    else begin
                                        format("4) " + message_str(61, 107) + message_str(61, 200), 127, 180, 260, 20, 0);
                                        set_local_var(3, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("4) " + message_str(61, 108), 127, 180, 260, 20, 0);
                                            set_local_var(3, 108);
                                        end
                                        else begin
                                            format("4) " + message_str(61, 108) + message_str(61, 200), 127, 180, 260, 20, 0);
                                            set_local_var(3, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("4) " + message_str(61, 109), 127, 180, 260, 20, 0);
                                                set_local_var(3, 109);
                                            end
                                            else begin
                                                format("4) " + message_str(61, 109) + message_str(61, 200), 127, 180, 260, 20, 0);
                                                set_local_var(3, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("4) " + message_str(61, 110), 127, 180, 260, 20, 0);
                                                    set_local_var(3, 110);
                                                end
                                                else begin
                                                    format("4) " + message_str(61, 110) + message_str(61, 200), 127, 180, 260, 20, 0);
                                                    set_local_var(3, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("4) " + message_str(61, 111), 127, 180, 260, 20, 0);
                                                        set_local_var(3, 111);
                                                    end
                                                    else begin
                                                        format("4) " + message_str(61, 111) + message_str(61, 200), 127, 180, 260, 20, 0);
                                                        set_local_var(3, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(3) > 1000) then begin
            format("4) " + message_str(61, local_var(3) / 10) + message_str(61, 200), 127, 180, 260, 20, 0);
        end
        else begin
            if (local_var(3) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("4) " + message_str(61, 101), 127, 180, 260, 20, 0);
                    set_local_var(3, 101);
                end
                else begin
                    format("4) " + message_str(61, 101) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1010);
                end
            end
            if (local_var(3) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("4) " + message_str(61, 102), 127, 180, 260, 20, 0);
                    set_local_var(3, 102);
                end
                else begin
                    format("4) " + message_str(61, 102) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1020);
                end
            end
            if (local_var(3) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("4) " + message_str(61, 103), 127, 180, 260, 20, 0);
                    set_local_var(3, 103);
                end
                else begin
                    format("4) " + message_str(61, 103) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1030);
                end
            end
            if (local_var(3) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("4) " + message_str(61, 104), 127, 180, 260, 20, 0);
                    set_local_var(3, 104);
                end
                else begin
                    format("4) " + message_str(61, 104) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1040);
                end
            end
            if (local_var(3) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("4) " + message_str(61, 105), 127, 180, 260, 20, 0);
                    set_local_var(3, 105);
                end
                else begin
                    format("4) " + message_str(61, 105) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1050);
                end
            end
            if (local_var(3) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("4) " + message_str(61, 106), 127, 180, 260, 20, 0);
                    set_local_var(3, 106);
                end
                else begin
                    format("4) " + message_str(61, 106) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1060);
                end
            end
            if (local_var(3) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("4) " + message_str(61, 107), 127, 180, 260, 20, 0);
                    set_local_var(3, 107);
                end
                else begin
                    format("4) " + message_str(61, 107) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1070);
                end
            end
            if (local_var(3) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("4) " + message_str(61, 108), 127, 180, 260, 20, 0);
                    set_local_var(3, 108);
                end
                else begin
                    format("4) " + message_str(61, 108) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1080);
                end
            end
            if (local_var(3) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("4) " + message_str(61, 109), 127, 180, 260, 20, 0);
                    set_local_var(3, 109);
                end
                else begin
                    format("4) " + message_str(61, 109) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1090);
                end
            end
            if (local_var(3) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("4) " + message_str(61, 110), 127, 180, 260, 20, 0);
                    set_local_var(3, 110);
                end
                else begin
                    format("4) " + message_str(61, 110) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1100);
                end
            end
            if (local_var(3) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("4) " + message_str(61, 111), 127, 180, 260, 20, 0);
                    set_local_var(3, 111);
                end
                else begin
                    format("4) " + message_str(61, 111) + message_str(61, 200), 127, 180, 260, 20, 0);
                    set_local_var(3, 1110);
                end
            end
        end
    end
    if (local_var(4) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("5) " + message_str(61, 101), 127, 210, 260, 20, 0);
                set_local_var(4, 101);
            end
            else begin
                format("5) " + message_str(61, 101) + message_str(61, 200), 127, 210, 260, 20, 0);
                set_local_var(4, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("5) " + message_str(61, 102), 127, 210, 260, 20, 0);
                    set_local_var(4, 102);
                end
                else begin
                    format("5) " + message_str(61, 102) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("5) " + message_str(61, 103), 127, 210, 260, 20, 0);
                        set_local_var(4, 103);
                    end
                    else begin
                        format("5) " + message_str(61, 103) + message_str(61, 200), 127, 210, 260, 20, 0);
                        set_local_var(4, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("5) " + message_str(61, 104), 127, 210, 260, 20, 0);
                            set_local_var(4, 104);
                        end
                        else begin
                            format("5) " + message_str(61, 104) + message_str(61, 200), 127, 210, 260, 20, 0);
                            set_local_var(4, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("5) " + message_str(61, 105), 127, 210, 260, 20, 0);
                                set_local_var(4, 105);
                            end
                            else begin
                                format("5) " + message_str(61, 105) + message_str(61, 200), 127, 210, 260, 20, 0);
                                set_local_var(4, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("5) " + message_str(61, 106), 127, 210, 260, 20, 0);
                                    set_local_var(4, 106);
                                end
                                else begin
                                    format("5) " + message_str(61, 106) + message_str(61, 200), 127, 210, 260, 20, 0);
                                    set_local_var(4, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("5) " + message_str(61, 107), 127, 210, 260, 20, 0);
                                        set_local_var(4, 107);
                                    end
                                    else begin
                                        format("5) " + message_str(61, 107) + message_str(61, 200), 127, 210, 260, 20, 0);
                                        set_local_var(4, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("5) " + message_str(61, 108), 127, 210, 260, 20, 0);
                                            set_local_var(4, 108);
                                        end
                                        else begin
                                            format("5) " + message_str(61, 108) + message_str(61, 200), 127, 210, 260, 20, 0);
                                            set_local_var(4, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("5) " + message_str(61, 109), 127, 210, 260, 20, 0);
                                                set_local_var(4, 109);
                                            end
                                            else begin
                                                format("5) " + message_str(61, 109) + message_str(61, 200), 127, 210, 260, 20, 0);
                                                set_local_var(4, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("5) " + message_str(61, 110), 127, 210, 260, 20, 0);
                                                    set_local_var(4, 110);
                                                end
                                                else begin
                                                    format("5) " + message_str(61, 110) + message_str(61, 200), 127, 210, 260, 20, 0);
                                                    set_local_var(4, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("5) " + message_str(61, 111), 127, 210, 260, 20, 0);
                                                        set_local_var(4, 111);
                                                    end
                                                    else begin
                                                        format("5) " + message_str(61, 111) + message_str(61, 200), 127, 210, 260, 20, 0);
                                                        set_local_var(4, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(4) > 1000) then begin
            format("5) " + message_str(61, local_var(4) / 10) + message_str(61, 200), 127, 210, 260, 20, 0);
        end
        else begin
            if (local_var(4) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("5) " + message_str(61, 101), 127, 210, 260, 20, 0);
                    set_local_var(4, 101);
                end
                else begin
                    format("5) " + message_str(61, 101) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1010);
                end
            end
            if (local_var(4) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("5) " + message_str(61, 102), 127, 210, 260, 20, 0);
                    set_local_var(4, 102);
                end
                else begin
                    format("5) " + message_str(61, 102) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1020);
                end
            end
            if (local_var(4) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("5) " + message_str(61, 103), 127, 210, 260, 20, 0);
                    set_local_var(4, 103);
                end
                else begin
                    format("5) " + message_str(61, 103) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1030);
                end
            end
            if (local_var(4) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("5) " + message_str(61, 104), 127, 210, 260, 20, 0);
                    set_local_var(4, 104);
                end
                else begin
                    format("5) " + message_str(61, 104) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1040);
                end
            end
            if (local_var(4) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("5) " + message_str(61, 105), 127, 210, 260, 20, 0);
                    set_local_var(4, 105);
                end
                else begin
                    format("5) " + message_str(61, 105) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1050);
                end
            end
            if (local_var(4) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("5) " + message_str(61, 106), 127, 210, 260, 20, 0);
                    set_local_var(4, 106);
                end
                else begin
                    format("5) " + message_str(61, 106) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1060);
                end
            end
            if (local_var(4) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("5) " + message_str(61, 107), 127, 210, 260, 20, 0);
                    set_local_var(4, 107);
                end
                else begin
                    format("5) " + message_str(61, 107) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1070);
                end
            end
            if (local_var(4) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("5) " + message_str(61, 108), 127, 210, 260, 20, 0);
                    set_local_var(4, 108);
                end
                else begin
                    format("5) " + message_str(61, 108) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1080);
                end
            end
            if (local_var(4) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("5) " + message_str(61, 109), 127, 210, 260, 20, 0);
                    set_local_var(4, 109);
                end
                else begin
                    format("5) " + message_str(61, 109) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1090);
                end
            end
            if (local_var(4) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("5) " + message_str(61, 110), 127, 210, 260, 20, 0);
                    set_local_var(4, 110);
                end
                else begin
                    format("5) " + message_str(61, 110) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1100);
                end
            end
            if (local_var(4) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("5) " + message_str(61, 111), 127, 210, 260, 20, 0);
                    set_local_var(4, 111);
                end
                else begin
                    format("5) " + message_str(61, 111) + message_str(61, 200), 127, 210, 260, 20, 0);
                    set_local_var(4, 1110);
                end
            end
        end
    end
    if (local_var(5) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("6) " + message_str(61, 101), 127, 240, 260, 20, 0);
                set_local_var(5, 101);
            end
            else begin
                format("6) " + message_str(61, 101) + message_str(61, 200), 127, 240, 260, 20, 0);
                set_local_var(5, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("6) " + message_str(61, 102), 127, 240, 260, 20, 0);
                    set_local_var(5, 102);
                end
                else begin
                    format("6) " + message_str(61, 102) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("6) " + message_str(61, 103), 127, 240, 260, 20, 0);
                        set_local_var(5, 103);
                    end
                    else begin
                        format("6) " + message_str(61, 103) + message_str(61, 200), 127, 240, 260, 20, 0);
                        set_local_var(5, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("6) " + message_str(61, 104), 127, 240, 260, 20, 0);
                            set_local_var(5, 104);
                        end
                        else begin
                            format("6) " + message_str(61, 104) + message_str(61, 200), 127, 240, 260, 20, 0);
                            set_local_var(5, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("6) " + message_str(61, 105), 127, 240, 260, 20, 0);
                                set_local_var(5, 105);
                            end
                            else begin
                                format("6) " + message_str(61, 105) + message_str(61, 200), 127, 240, 260, 20, 0);
                                set_local_var(5, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("6) " + message_str(61, 106), 127, 240, 260, 20, 0);
                                    set_local_var(5, 106);
                                end
                                else begin
                                    format("6) " + message_str(61, 106) + message_str(61, 200), 127, 240, 260, 20, 0);
                                    set_local_var(5, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("6) " + message_str(61, 107), 127, 240, 260, 20, 0);
                                        set_local_var(5, 107);
                                    end
                                    else begin
                                        format("6) " + message_str(61, 107) + message_str(61, 200), 127, 240, 260, 20, 0);
                                        set_local_var(5, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("6) " + message_str(61, 108), 127, 240, 260, 20, 0);
                                            set_local_var(5, 108);
                                        end
                                        else begin
                                            format("6) " + message_str(61, 108) + message_str(61, 200), 127, 240, 260, 20, 0);
                                            set_local_var(5, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("6) " + message_str(61, 109), 127, 240, 260, 20, 0);
                                                set_local_var(5, 109);
                                            end
                                            else begin
                                                format("6) " + message_str(61, 109) + message_str(61, 200), 127, 240, 260, 20, 0);
                                                set_local_var(5, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("6) " + message_str(61, 110), 127, 240, 260, 20, 0);
                                                    set_local_var(5, 110);
                                                end
                                                else begin
                                                    format("6) " + message_str(61, 110) + message_str(61, 200), 127, 240, 260, 20, 0);
                                                    set_local_var(5, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("6) " + message_str(61, 111), 127, 240, 260, 20, 0);
                                                        set_local_var(5, 111);
                                                    end
                                                    else begin
                                                        format("6) " + message_str(61, 111) + message_str(61, 200), 127, 240, 260, 20, 0);
                                                        set_local_var(5, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(5) > 1000) then begin
            format("6) " + message_str(61, local_var(5) / 10) + message_str(61, 200), 127, 240, 260, 20, 0);
        end
        else begin
            if (local_var(5) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("6) " + message_str(61, 101), 127, 240, 260, 20, 0);
                    set_local_var(5, 101);
                end
                else begin
                    format("6) " + message_str(61, 101) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1010);
                end
            end
            if (local_var(5) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("6) " + message_str(61, 102), 127, 240, 260, 20, 0);
                    set_local_var(5, 102);
                end
                else begin
                    format("6) " + message_str(61, 102) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1020);
                end
            end
            if (local_var(5) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("6) " + message_str(61, 103), 127, 240, 260, 20, 0);
                    set_local_var(5, 103);
                end
                else begin
                    format("6) " + message_str(61, 103) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1030);
                end
            end
            if (local_var(5) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("6) " + message_str(61, 104), 127, 240, 260, 20, 0);
                    set_local_var(5, 104);
                end
                else begin
                    format("6) " + message_str(61, 104) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1040);
                end
            end
            if (local_var(5) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("6) " + message_str(61, 105), 127, 240, 260, 20, 0);
                    set_local_var(5, 105);
                end
                else begin
                    format("6) " + message_str(61, 105) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1050);
                end
            end
            if (local_var(5) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("6) " + message_str(61, 106), 127, 240, 260, 20, 0);
                    set_local_var(5, 106);
                end
                else begin
                    format("6) " + message_str(61, 106) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1060);
                end
            end
            if (local_var(5) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("6) " + message_str(61, 107), 127, 240, 260, 20, 0);
                    set_local_var(5, 107);
                end
                else begin
                    format("6) " + message_str(61, 107) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1070);
                end
            end
            if (local_var(5) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("6) " + message_str(61, 108), 127, 240, 260, 20, 0);
                    set_local_var(5, 108);
                end
                else begin
                    format("6) " + message_str(61, 108) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1080);
                end
            end
            if (local_var(5) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("6) " + message_str(61, 109), 127, 240, 260, 20, 0);
                    set_local_var(5, 109);
                end
                else begin
                    format("6) " + message_str(61, 109) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1090);
                end
            end
            if (local_var(5) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("6) " + message_str(61, 110), 127, 240, 260, 20, 0);
                    set_local_var(5, 110);
                end
                else begin
                    format("6) " + message_str(61, 110) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1100);
                end
            end
            if (local_var(5) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("6) " + message_str(61, 111), 127, 240, 260, 20, 0);
                    set_local_var(5, 111);
                end
                else begin
                    format("6) " + message_str(61, 111) + message_str(61, 200), 127, 240, 260, 20, 0);
                    set_local_var(5, 1110);
                end
            end
        end
    end
    if (local_var(6) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("7) " + message_str(61, 101), 127, 270, 260, 20, 0);
                set_local_var(6, 101);
            end
            else begin
                format("7) " + message_str(61, 101) + message_str(61, 200), 127, 270, 260, 20, 0);
                set_local_var(6, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("7) " + message_str(61, 102), 127, 270, 260, 20, 0);
                    set_local_var(6, 102);
                end
                else begin
                    format("7) " + message_str(61, 102) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("7) " + message_str(61, 103), 127, 270, 260, 20, 0);
                        set_local_var(6, 103);
                    end
                    else begin
                        format("7) " + message_str(61, 103) + message_str(61, 200), 127, 270, 260, 20, 0);
                        set_local_var(6, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("7) " + message_str(61, 104), 127, 270, 260, 20, 0);
                            set_local_var(6, 104);
                        end
                        else begin
                            format("7) " + message_str(61, 104) + message_str(61, 200), 127, 270, 260, 20, 0);
                            set_local_var(6, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("7) " + message_str(61, 105), 127, 270, 260, 20, 0);
                                set_local_var(6, 105);
                            end
                            else begin
                                format("7) " + message_str(61, 105) + message_str(61, 200), 127, 270, 260, 20, 0);
                                set_local_var(6, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("7) " + message_str(61, 106), 127, 270, 260, 20, 0);
                                    set_local_var(6, 106);
                                end
                                else begin
                                    format("7) " + message_str(61, 106) + message_str(61, 200), 127, 270, 260, 20, 0);
                                    set_local_var(6, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("7) " + message_str(61, 107), 127, 270, 260, 20, 0);
                                        set_local_var(6, 107);
                                    end
                                    else begin
                                        format("7) " + message_str(61, 107) + message_str(61, 200), 127, 270, 260, 20, 0);
                                        set_local_var(6, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("7) " + message_str(61, 108), 127, 270, 260, 20, 0);
                                            set_local_var(6, 108);
                                        end
                                        else begin
                                            format("7) " + message_str(61, 108) + message_str(61, 200), 127, 270, 260, 20, 0);
                                            set_local_var(6, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("7) " + message_str(61, 109), 127, 270, 260, 20, 0);
                                                set_local_var(6, 109);
                                            end
                                            else begin
                                                format("7) " + message_str(61, 109) + message_str(61, 200), 127, 270, 260, 20, 0);
                                                set_local_var(6, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("7) " + message_str(61, 110), 127, 270, 260, 20, 0);
                                                    set_local_var(6, 110);
                                                end
                                                else begin
                                                    format("7) " + message_str(61, 110) + message_str(61, 200), 127, 270, 260, 20, 0);
                                                    set_local_var(6, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("7) " + message_str(61, 111), 127, 270, 260, 20, 0);
                                                        set_local_var(6, 111);
                                                    end
                                                    else begin
                                                        format("7) " + message_str(61, 111) + message_str(61, 200), 127, 270, 260, 20, 0);
                                                        set_local_var(6, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(6) > 1000) then begin
            format("7) " + message_str(61, local_var(6) / 10) + message_str(61, 200), 127, 270, 260, 20, 0);
        end
        else begin
            if (local_var(6) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("7) " + message_str(61, 101), 127, 270, 260, 20, 0);
                    set_local_var(6, 101);
                end
                else begin
                    format("7) " + message_str(61, 101) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1010);
                end
            end
            if (local_var(6) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("7) " + message_str(61, 102), 127, 270, 260, 20, 0);
                    set_local_var(6, 102);
                end
                else begin
                    format("7) " + message_str(61, 102) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1020);
                end
            end
            if (local_var(6) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("7) " + message_str(61, 103), 127, 270, 260, 20, 0);
                    set_local_var(6, 103);
                end
                else begin
                    format("7) " + message_str(61, 103) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1030);
                end
            end
            if (local_var(6) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("7) " + message_str(61, 104), 127, 270, 260, 20, 0);
                    set_local_var(6, 104);
                end
                else begin
                    format("7) " + message_str(61, 104) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1040);
                end
            end
            if (local_var(6) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("7) " + message_str(61, 105), 127, 270, 260, 20, 0);
                    set_local_var(6, 105);
                end
                else begin
                    format("7) " + message_str(61, 105) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1050);
                end
            end
            if (local_var(6) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("7) " + message_str(61, 106), 127, 270, 260, 20, 0);
                    set_local_var(6, 106);
                end
                else begin
                    format("7) " + message_str(61, 106) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1060);
                end
            end
            if (local_var(6) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("7) " + message_str(61, 107), 127, 270, 260, 20, 0);
                    set_local_var(6, 107);
                end
                else begin
                    format("7) " + message_str(61, 107) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1070);
                end
            end
            if (local_var(6) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("7) " + message_str(61, 108), 127, 270, 260, 20, 0);
                    set_local_var(6, 108);
                end
                else begin
                    format("7) " + message_str(61, 108) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1080);
                end
            end
            if (local_var(6) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("7) " + message_str(61, 109), 127, 270, 260, 20, 0);
                    set_local_var(6, 109);
                end
                else begin
                    format("7) " + message_str(61, 109) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1090);
                end
            end
            if (local_var(6) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("7) " + message_str(61, 110), 127, 270, 260, 20, 0);
                    set_local_var(6, 110);
                end
                else begin
                    format("7) " + message_str(61, 110) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1100);
                end
            end
            if (local_var(6) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("7) " + message_str(61, 111), 127, 270, 260, 20, 0);
                    set_local_var(6, 111);
                end
                else begin
                    format("7) " + message_str(61, 111) + message_str(61, 200), 127, 270, 260, 20, 0);
                    set_local_var(6, 1110);
                end
            end
        end
    end
    if (local_var(7) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("8) " + message_str(61, 101), 127, 300, 260, 20, 0);
                set_local_var(7, 101);
            end
            else begin
                format("8) " + message_str(61, 101) + message_str(61, 200), 127, 300, 260, 20, 0);
                set_local_var(7, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("8) " + message_str(61, 102), 127, 300, 260, 20, 0);
                    set_local_var(7, 102);
                end
                else begin
                    format("8) " + message_str(61, 102) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("8) " + message_str(61, 103), 127, 300, 260, 20, 0);
                        set_local_var(7, 103);
                    end
                    else begin
                        format("8) " + message_str(61, 103) + message_str(61, 200), 127, 300, 260, 20, 0);
                        set_local_var(7, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("8) " + message_str(61, 104), 127, 300, 260, 20, 0);
                            set_local_var(7, 104);
                        end
                        else begin
                            format("8) " + message_str(61, 104) + message_str(61, 200), 127, 300, 260, 20, 0);
                            set_local_var(7, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("8) " + message_str(61, 105), 127, 300, 260, 20, 0);
                                set_local_var(7, 105);
                            end
                            else begin
                                format("8) " + message_str(61, 105) + message_str(61, 200), 127, 300, 260, 20, 0);
                                set_local_var(7, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("8) " + message_str(61, 106), 127, 300, 260, 20, 0);
                                    set_local_var(7, 106);
                                end
                                else begin
                                    format("8) " + message_str(61, 106) + message_str(61, 200), 127, 300, 260, 20, 0);
                                    set_local_var(7, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("8) " + message_str(61, 107), 127, 300, 260, 20, 0);
                                        set_local_var(7, 107);
                                    end
                                    else begin
                                        format("8) " + message_str(61, 107) + message_str(61, 200), 127, 300, 260, 20, 0);
                                        set_local_var(7, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("8) " + message_str(61, 108), 127, 300, 260, 20, 0);
                                            set_local_var(7, 108);
                                        end
                                        else begin
                                            format("8) " + message_str(61, 108) + message_str(61, 200), 127, 300, 260, 20, 0);
                                            set_local_var(7, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("8) " + message_str(61, 109), 127, 300, 260, 20, 0);
                                                set_local_var(7, 109);
                                            end
                                            else begin
                                                format("8) " + message_str(61, 109) + message_str(61, 200), 127, 300, 260, 20, 0);
                                                set_local_var(7, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("8) " + message_str(61, 110), 127, 300, 260, 20, 0);
                                                    set_local_var(7, 110);
                                                end
                                                else begin
                                                    format("8) " + message_str(61, 110) + message_str(61, 200), 127, 300, 260, 20, 0);
                                                    set_local_var(7, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("8) " + message_str(61, 111), 127, 300, 260, 20, 0);
                                                        set_local_var(7, 111);
                                                    end
                                                    else begin
                                                        format("8) " + message_str(61, 111) + message_str(61, 200), 127, 300, 260, 20, 0);
                                                        set_local_var(7, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(7) > 1000) then begin
            format("8) " + message_str(61, local_var(7) / 10) + message_str(61, 200), 127, 300, 260, 20, 0);
        end
        else begin
            if (local_var(7) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("8) " + message_str(61, 101), 127, 300, 260, 20, 0);
                    set_local_var(7, 101);
                end
                else begin
                    format("8) " + message_str(61, 101) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1010);
                end
            end
            if (local_var(7) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("8) " + message_str(61, 102), 127, 300, 260, 20, 0);
                    set_local_var(7, 102);
                end
                else begin
                    format("8) " + message_str(61, 102) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1020);
                end
            end
            if (local_var(7) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("8) " + message_str(61, 103), 127, 300, 260, 20, 0);
                    set_local_var(7, 103);
                end
                else begin
                    format("8) " + message_str(61, 103) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1030);
                end
            end
            if (local_var(7) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("8) " + message_str(61, 104), 127, 300, 260, 20, 0);
                    set_local_var(7, 104);
                end
                else begin
                    format("8) " + message_str(61, 104) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1040);
                end
            end
            if (local_var(7) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("8) " + message_str(61, 105), 127, 300, 260, 20, 0);
                    set_local_var(7, 105);
                end
                else begin
                    format("8) " + message_str(61, 105) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1050);
                end
            end
            if (local_var(7) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("8) " + message_str(61, 106), 127, 300, 260, 20, 0);
                    set_local_var(7, 106);
                end
                else begin
                    format("8) " + message_str(61, 106) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1060);
                end
            end
            if (local_var(7) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("8) " + message_str(61, 107), 127, 300, 260, 20, 0);
                    set_local_var(7, 107);
                end
                else begin
                    format("8) " + message_str(61, 107) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1070);
                end
            end
            if (local_var(7) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("8) " + message_str(61, 108), 127, 300, 260, 20, 0);
                    set_local_var(7, 108);
                end
                else begin
                    format("8) " + message_str(61, 108) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1080);
                end
            end
            if (local_var(7) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("8) " + message_str(61, 109), 127, 300, 260, 20, 0);
                    set_local_var(7, 109);
                end
                else begin
                    format("8) " + message_str(61, 109) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1090);
                end
            end
            if (local_var(7) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("8) " + message_str(61, 110), 127, 300, 260, 20, 0);
                    set_local_var(7, 110);
                end
                else begin
                    format("8) " + message_str(61, 110) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1100);
                end
            end
            if (local_var(7) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("8) " + message_str(61, 111), 127, 300, 260, 20, 0);
                    set_local_var(7, 111);
                end
                else begin
                    format("8) " + message_str(61, 111) + message_str(61, 200), 127, 300, 260, 20, 0);
                    set_local_var(7, 1110);
                end
            end
        end
    end
    if (local_var(8) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("9) " + message_str(61, 101), 127, 330, 260, 20, 0);
                set_local_var(8, 101);
            end
            else begin
                format("9) " + message_str(61, 101) + message_str(61, 200), 127, 330, 260, 20, 0);
                set_local_var(8, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("9) " + message_str(61, 102), 127, 330, 260, 20, 0);
                    set_local_var(8, 102);
                end
                else begin
                    format("9) " + message_str(61, 102) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("9) " + message_str(61, 103), 127, 330, 260, 20, 0);
                        set_local_var(8, 103);
                    end
                    else begin
                        format("9) " + message_str(61, 103) + message_str(61, 200), 127, 330, 260, 20, 0);
                        set_local_var(8, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("9) " + message_str(61, 104), 127, 330, 260, 20, 0);
                            set_local_var(8, 104);
                        end
                        else begin
                            format("9) " + message_str(61, 104) + message_str(61, 200), 127, 330, 260, 20, 0);
                            set_local_var(8, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("9) " + message_str(61, 105), 127, 330, 260, 20, 0);
                                set_local_var(8, 105);
                            end
                            else begin
                                format("9) " + message_str(61, 105) + message_str(61, 200), 127, 330, 260, 20, 0);
                                set_local_var(8, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("9) " + message_str(61, 106), 127, 330, 260, 20, 0);
                                    set_local_var(8, 106);
                                end
                                else begin
                                    format("9) " + message_str(61, 106) + message_str(61, 200), 127, 330, 260, 20, 0);
                                    set_local_var(8, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("9) " + message_str(61, 107), 127, 330, 260, 20, 0);
                                        set_local_var(8, 107);
                                    end
                                    else begin
                                        format("9) " + message_str(61, 107) + message_str(61, 200), 127, 330, 260, 20, 0);
                                        set_local_var(8, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("9) " + message_str(61, 108), 127, 330, 260, 20, 0);
                                            set_local_var(8, 108);
                                        end
                                        else begin
                                            format("9) " + message_str(61, 108) + message_str(61, 200), 127, 330, 260, 20, 0);
                                            set_local_var(8, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("9) " + message_str(61, 109), 127, 330, 260, 20, 0);
                                                set_local_var(8, 109);
                                            end
                                            else begin
                                                format("9) " + message_str(61, 109) + message_str(61, 200), 127, 330, 260, 20, 0);
                                                set_local_var(8, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("9) " + message_str(61, 110), 127, 330, 260, 20, 0);
                                                    set_local_var(8, 110);
                                                end
                                                else begin
                                                    format("9) " + message_str(61, 110) + message_str(61, 200), 127, 330, 260, 20, 0);
                                                    set_local_var(8, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("9) " + message_str(61, 111), 127, 330, 260, 20, 0);
                                                        set_local_var(8, 111);
                                                    end
                                                    else begin
                                                        format("9) " + message_str(61, 111) + message_str(61, 200), 127, 330, 260, 20, 0);
                                                        set_local_var(8, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(8) > 1000) then begin
            format("9) " + message_str(61, local_var(8) / 10) + message_str(61, 200), 127, 330, 260, 20, 0);
        end
        else begin
            if (local_var(8) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("9) " + message_str(61, 101), 127, 330, 260, 20, 0);
                    set_local_var(8, 101);
                end
                else begin
                    format("9) " + message_str(61, 101) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1010);
                end
            end
            if (local_var(8) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("9) " + message_str(61, 102), 127, 330, 260, 20, 0);
                    set_local_var(8, 102);
                end
                else begin
                    format("9) " + message_str(61, 102) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1020);
                end
            end
            if (local_var(8) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("9) " + message_str(61, 103), 127, 330, 260, 20, 0);
                    set_local_var(8, 103);
                end
                else begin
                    format("9) " + message_str(61, 103) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1030);
                end
            end
            if (local_var(8) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("9) " + message_str(61, 104), 127, 330, 260, 20, 0);
                    set_local_var(8, 104);
                end
                else begin
                    format("9) " + message_str(61, 104) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1040);
                end
            end
            if (local_var(8) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("9) " + message_str(61, 105), 127, 330, 260, 20, 0);
                    set_local_var(8, 105);
                end
                else begin
                    format("9) " + message_str(61, 105) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1050);
                end
            end
            if (local_var(8) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("9) " + message_str(61, 106), 127, 330, 260, 20, 0);
                    set_local_var(8, 106);
                end
                else begin
                    format("9) " + message_str(61, 106) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1060);
                end
            end
            if (local_var(8) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("9) " + message_str(61, 107), 127, 330, 260, 20, 0);
                    set_local_var(8, 107);
                end
                else begin
                    format("9) " + message_str(61, 107) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1070);
                end
            end
            if (local_var(8) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("9) " + message_str(61, 108), 127, 330, 260, 20, 0);
                    set_local_var(8, 108);
                end
                else begin
                    format("9) " + message_str(61, 108) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1080);
                end
            end
            if (local_var(8) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("9) " + message_str(61, 109), 127, 330, 260, 20, 0);
                    set_local_var(8, 109);
                end
                else begin
                    format("9) " + message_str(61, 109) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1090);
                end
            end
            if (local_var(8) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("9) " + message_str(61, 110), 127, 330, 260, 20, 0);
                    set_local_var(8, 110);
                end
                else begin
                    format("9) " + message_str(61, 110) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1100);
                end
            end
            if (local_var(8) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("9) " + message_str(61, 111), 127, 330, 260, 20, 0);
                    set_local_var(8, 111);
                end
                else begin
                    format("9) " + message_str(61, 111) + message_str(61, 200), 127, 330, 260, 20, 0);
                    set_local_var(8, 1110);
                end
            end
        end
    end
    if (local_var(9) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("10) " + message_str(61, 101), 127, 360, 260, 20, 0);
                set_local_var(9, 101);
            end
            else begin
                format("10) " + message_str(61, 101) + message_str(61, 200), 127, 360, 260, 20, 0);
                set_local_var(9, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("10) " + message_str(61, 102), 127, 360, 260, 20, 0);
                    set_local_var(9, 102);
                end
                else begin
                    format("10) " + message_str(61, 102) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("10) " + message_str(61, 103), 127, 360, 260, 20, 0);
                        set_local_var(9, 103);
                    end
                    else begin
                        format("10) " + message_str(61, 103) + message_str(61, 200), 127, 360, 260, 20, 0);
                        set_local_var(9, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("10) " + message_str(61, 104), 127, 360, 260, 20, 0);
                            set_local_var(9, 104);
                        end
                        else begin
                            format("10) " + message_str(61, 104) + message_str(61, 200), 127, 360, 260, 20, 0);
                            set_local_var(9, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("10) " + message_str(61, 105), 127, 360, 260, 20, 0);
                                set_local_var(9, 105);
                            end
                            else begin
                                format("10) " + message_str(61, 105) + message_str(61, 200), 127, 360, 260, 20, 0);
                                set_local_var(9, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("10) " + message_str(61, 106), 127, 360, 260, 20, 0);
                                    set_local_var(9, 106);
                                end
                                else begin
                                    format("10) " + message_str(61, 106) + message_str(61, 200), 127, 360, 260, 20, 0);
                                    set_local_var(9, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("10) " + message_str(61, 107), 127, 360, 260, 20, 0);
                                        set_local_var(9, 107);
                                    end
                                    else begin
                                        format("10) " + message_str(61, 107) + message_str(61, 200), 127, 360, 260, 20, 0);
                                        set_local_var(9, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("10) " + message_str(61, 108), 127, 360, 260, 20, 0);
                                            set_local_var(9, 108);
                                        end
                                        else begin
                                            format("10) " + message_str(61, 108) + message_str(61, 200), 127, 360, 260, 20, 0);
                                            set_local_var(9, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("10) " + message_str(61, 109), 127, 360, 260, 20, 0);
                                                set_local_var(9, 109);
                                            end
                                            else begin
                                                format("10) " + message_str(61, 109) + message_str(61, 200), 127, 360, 260, 20, 0);
                                                set_local_var(9, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("10) " + message_str(61, 110), 127, 360, 260, 20, 0);
                                                    set_local_var(9, 110);
                                                end
                                                else begin
                                                    format("10) " + message_str(61, 110) + message_str(61, 200), 127, 360, 260, 20, 0);
                                                    set_local_var(9, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("10) " + message_str(61, 111), 127, 360, 260, 20, 0);
                                                        set_local_var(9, 111);
                                                    end
                                                    else begin
                                                        format("10) " + message_str(61, 111) + message_str(61, 200), 127, 360, 260, 20, 0);
                                                        set_local_var(9, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(9) > 1000) then begin
            format("10) " + message_str(61, local_var(9) / 10) + message_str(61, 200), 127, 360, 260, 20, 0);
        end
        else begin
            if (local_var(9) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("10) " + message_str(61, 101), 127, 360, 260, 20, 0);
                    set_local_var(9, 101);
                end
                else begin
                    format("10) " + message_str(61, 101) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1010);
                end
            end
            if (local_var(9) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("10) " + message_str(61, 102), 127, 360, 260, 20, 0);
                    set_local_var(9, 102);
                end
                else begin
                    format("10) " + message_str(61, 102) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1020);
                end
            end
            if (local_var(9) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("10) " + message_str(61, 103), 127, 360, 260, 20, 0);
                    set_local_var(9, 103);
                end
                else begin
                    format("10) " + message_str(61, 103) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1030);
                end
            end
            if (local_var(9) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("10) " + message_str(61, 104), 127, 360, 260, 20, 0);
                    set_local_var(9, 104);
                end
                else begin
                    format("10) " + message_str(61, 104) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1040);
                end
            end
            if (local_var(9) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("10) " + message_str(61, 105), 127, 360, 260, 20, 0);
                    set_local_var(9, 105);
                end
                else begin
                    format("10) " + message_str(61, 105) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1050);
                end
            end
            if (local_var(9) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("10) " + message_str(61, 106), 127, 360, 260, 20, 0);
                    set_local_var(9, 106);
                end
                else begin
                    format("10) " + message_str(61, 106) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1060);
                end
            end
            if (local_var(9) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("10) " + message_str(61, 107), 127, 360, 260, 20, 0);
                    set_local_var(9, 107);
                end
                else begin
                    format("10) " + message_str(61, 107) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1070);
                end
            end
            if (local_var(9) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("10) " + message_str(61, 108), 127, 360, 260, 20, 0);
                    set_local_var(9, 108);
                end
                else begin
                    format("10) " + message_str(61, 108) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1080);
                end
            end
            if (local_var(9) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("10) " + message_str(61, 109), 127, 360, 260, 20, 0);
                    set_local_var(9, 109);
                end
                else begin
                    format("10) " + message_str(61, 109) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1090);
                end
            end
            if (local_var(9) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("10) " + message_str(61, 110), 127, 360, 260, 20, 0);
                    set_local_var(9, 110);
                end
                else begin
                    format("10) " + message_str(61, 110) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1100);
                end
            end
            if (local_var(9) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("10) " + message_str(61, 111), 127, 360, 260, 20, 0);
                    set_local_var(9, 111);
                end
                else begin
                    format("10) " + message_str(61, 111) + message_str(61, 200), 127, 360, 260, 20, 0);
                    set_local_var(9, 1110);
                end
            end
        end
    end
    if (local_var(10) == 0) then begin
        if ((local_var(11) == 0) and (global_var(27) != 0)) then begin
            if (global_var(27) == 1) then begin
                format("11) " + message_str(61, 101), 127, 390, 260, 20, 0);
                set_local_var(10, 101);
            end
            else begin
                format("11) " + message_str(61, 101) + message_str(61, 200), 127, 390, 260, 20, 0);
                set_local_var(10, 1010);
            end
            set_local_var(11, 1);
        end
        else begin
            if ((local_var(12) == 0) and (global_var(28) != 0)) then begin
                if (global_var(28) == 1) then begin
                    format("11) " + message_str(61, 102), 127, 390, 260, 20, 0);
                    set_local_var(10, 102);
                end
                else begin
                    format("11) " + message_str(61, 102) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1020);
                end
                set_local_var(12, 1);
            end
            else begin
                if ((local_var(13) == 0) and (global_var(29) != 0)) then begin
                    if (global_var(29) == 1) then begin
                        format("11) " + message_str(61, 103), 127, 390, 260, 20, 0);
                        set_local_var(10, 103);
                    end
                    else begin
                        format("11) " + message_str(61, 103) + message_str(61, 200), 127, 390, 260, 20, 0);
                        set_local_var(10, 1030);
                    end
                    set_local_var(13, 1);
                end
                else begin
                    if ((local_var(14) == 0) and (global_var(30) != 0)) then begin
                        if (global_var(30) == 1) then begin
                            format("11) " + message_str(61, 104), 127, 390, 260, 20, 0);
                            set_local_var(10, 104);
                        end
                        else begin
                            format("11) " + message_str(61, 104) + message_str(61, 200), 127, 390, 260, 20, 0);
                            set_local_var(10, 1040);
                        end
                        set_local_var(14, 1);
                    end
                    else begin
                        if ((local_var(15) == 0) and (global_var(31) != 0)) then begin
                            if (global_var(31) == 1) then begin
                                format("11) " + message_str(61, 105), 127, 390, 260, 20, 0);
                                set_local_var(10, 105);
                            end
                            else begin
                                format("11) " + message_str(61, 105) + message_str(61, 200), 127, 390, 260, 20, 0);
                                set_local_var(10, 1050);
                            end
                            set_local_var(15, 1);
                        end
                        else begin
                            if ((local_var(16) == 0) and (global_var(32) != 0)) then begin
                                if (global_var(32) == 1) then begin
                                    format("11) " + message_str(61, 106), 127, 390, 260, 20, 0);
                                    set_local_var(10, 106);
                                end
                                else begin
                                    format("11) " + message_str(61, 106) + message_str(61, 200), 127, 390, 260, 20, 0);
                                    set_local_var(10, 1060);
                                end
                                set_local_var(16, 1);
                            end
                            else begin
                                if ((local_var(17) == 0) and (global_var(33) != 0)) then begin
                                    if (global_var(33) == 1) then begin
                                        format("11) " + message_str(61, 107), 127, 390, 260, 20, 0);
                                        set_local_var(10, 107);
                                    end
                                    else begin
                                        format("11) " + message_str(61, 107) + message_str(61, 200), 127, 390, 260, 20, 0);
                                        set_local_var(10, 1070);
                                    end
                                    set_local_var(17, 1);
                                end
                                else begin
                                    if ((local_var(18) == 0) and (global_var(34) != 0)) then begin
                                        if (global_var(34) == 1) then begin
                                            format("11) " + message_str(61, 108), 127, 390, 260, 20, 0);
                                            set_local_var(10, 108);
                                        end
                                        else begin
                                            format("11) " + message_str(61, 108) + message_str(61, 200), 127, 390, 260, 20, 0);
                                            set_local_var(10, 1080);
                                        end
                                        set_local_var(18, 1);
                                    end
                                    else begin
                                        if ((local_var(19) == 0) and (global_var(35) != 0)) then begin
                                            if (global_var(35) == 1) then begin
                                                format("11) " + message_str(61, 109), 127, 390, 260, 20, 0);
                                                set_local_var(10, 109);
                                            end
                                            else begin
                                                format("11) " + message_str(61, 109) + message_str(61, 200), 127, 390, 260, 20, 0);
                                                set_local_var(10, 1090);
                                            end
                                            set_local_var(19, 1);
                                        end
                                        else begin
                                            if ((local_var(20) == 0) and (global_var(36) != 0)) then begin
                                                if (global_var(36) == 1) then begin
                                                    format("11) " + message_str(61, 110), 127, 390, 260, 20, 0);
                                                    set_local_var(10, 110);
                                                end
                                                else begin
                                                    format("11) " + message_str(61, 110) + message_str(61, 200), 127, 390, 260, 20, 0);
                                                    set_local_var(10, 1100);
                                                end
                                                set_local_var(20, 1);
                                            end
                                            else begin
                                                if ((local_var(21) == 0) and (global_var(46) != 0)) then begin
                                                    if (global_var(46) == 1) then begin
                                                        format("11) " + message_str(61, 111), 127, 390, 260, 20, 0);
                                                        set_local_var(10, 111);
                                                    end
                                                    else begin
                                                        format("11) " + message_str(61, 111) + message_str(61, 200), 127, 390, 260, 20, 0);
                                                        set_local_var(10, 1110);
                                                    end
                                                    set_local_var(21, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (local_var(10) > 1000) then begin
            format("11) " + message_str(61, local_var(10) / 10) + message_str(61, 200), 127, 390, 260, 20, 0);
        end
        else begin
            if (local_var(10) == 101) then begin
                if (global_var(27) == 1) then begin
                    format("11) " + message_str(61, 101), 127, 390, 260, 20, 0);
                    set_local_var(10, 101);
                end
                else begin
                    format("11) " + message_str(61, 101) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1010);
                end
            end
            if (local_var(10) == 102) then begin
                if (global_var(28) == 1) then begin
                    format("11) " + message_str(61, 102), 127, 390, 260, 20, 0);
                    set_local_var(10, 102);
                end
                else begin
                    format("11) " + message_str(61, 102) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1020);
                end
            end
            if (local_var(10) == 103) then begin
                if (global_var(29) == 1) then begin
                    format("11) " + message_str(61, 103), 127, 390, 260, 20, 0);
                    set_local_var(10, 103);
                end
                else begin
                    format("11) " + message_str(61, 103) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1030);
                end
            end
            if (local_var(10) == 104) then begin
                if (global_var(30) == 1) then begin
                    format("11) " + message_str(61, 104), 127, 390, 260, 20, 0);
                    set_local_var(10, 104);
                end
                else begin
                    format("11) " + message_str(61, 104) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1040);
                end
            end
            if (local_var(10) == 105) then begin
                if (global_var(31) == 1) then begin
                    format("11) " + message_str(61, 105), 127, 390, 260, 20, 0);
                    set_local_var(10, 105);
                end
                else begin
                    format("11) " + message_str(61, 105) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1050);
                end
            end
            if (local_var(10) == 106) then begin
                if (global_var(32) == 1) then begin
                    format("11) " + message_str(61, 106), 127, 390, 260, 20, 0);
                    set_local_var(10, 106);
                end
                else begin
                    format("11) " + message_str(61, 106) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1060);
                end
            end
            if (local_var(10) == 107) then begin
                if (global_var(33) == 1) then begin
                    format("11) " + message_str(61, 107), 127, 390, 260, 20, 0);
                    set_local_var(10, 107);
                end
                else begin
                    format("11) " + message_str(61, 107) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1070);
                end
            end
            if (local_var(10) == 108) then begin
                if (global_var(34) == 1) then begin
                    format("11) " + message_str(61, 108), 127, 390, 260, 20, 0);
                    set_local_var(10, 108);
                end
                else begin
                    format("11) " + message_str(61, 108) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1080);
                end
            end
            if (local_var(10) == 109) then begin
                if (global_var(35) == 1) then begin
                    format("11) " + message_str(61, 109), 127, 390, 260, 20, 0);
                    set_local_var(10, 109);
                end
                else begin
                    format("11) " + message_str(61, 109) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1090);
                end
            end
            if (local_var(10) == 110) then begin
                if (global_var(36) == 1) then begin
                    format("11) " + message_str(61, 110), 127, 390, 260, 20, 0);
                    set_local_var(10, 110);
                end
                else begin
                    format("11) " + message_str(61, 110) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1100);
                end
            end
            if (local_var(10) == 111) then begin
                if (global_var(46) == 1) then begin
                    format("11) " + message_str(61, 111), 127, 390, 260, 20, 0);
                    set_local_var(10, 111);
                end
                else begin
                    format("11) " + message_str(61, 111) + message_str(61, 200), 127, 390, 260, 20, 0);
                    set_local_var(10, 1110);
                end
            end
        end
    end
    showWin;
    addButton("BTN_exit", 657, 21, 60, 45);
    addButtonGfx("BTN_exit", "PCX/ntbkbck1.pcx", "PCX/ntbkbck1.pcx", "PCX/ntbkbck2.pcx");
    addButtonProc("BTN_exit", vide, vide, vide, NoteBook_End);
    addButton("BTN_last", 86, 434, 60, 45);
    addButtonGfx("BTN_last", "PCX/ntbklst1.pcx", "PCX/ntbklst1.pcx", "PCX/ntbklst2.pcx");
    addButtonProc("BTN_last", vide, vide, vide, vide);
    addButton("BTN_next", 657, 434, 60, 45);
    addButtonGfx("BTN_next", "PCX/ntbknxt1.pcx", "PCX/ntbknxt1.pcx", "PCX/ntbknxt2.pcx");
    addButtonProc("BTN_next", vide, vide, vide, vide);
    game_ui_disable;
    mouseShape("PCX/mouse2.pcx", 0, 0);
end

procedure NoteBook1_Start
begin
    createWin("NoteBook", (get_screen_width / 2) - 400, (get_screen_height / 2) - 300, 800, 500);
    selectWin("NoteBook");
    display("PCX/NoteBook2.pcx");
    setFont(3);
    setTextColor(0.00000, 0.00000, 0.00000);
    if (get_sfall_global_int(17) == 1) then begin
        format(" " + message_str(61, 201), 127, 60, 240, 40, 0);
    end
    if (get_sfall_global_int(18) == 1) then begin
        format(" " + message_str(61, 202), 127, 105, 240, 40, 0);
    end
    if (get_sfall_global_int(19) == 1) then begin
        format(" " + message_str(61, 203), 127, 150, 240, 40, 0);
    end
    if (get_sfall_global_int(20) == 1) then begin
        format(" " + message_str(61, 204), 127, 195, 240, 40, 0);
    end
    if (get_sfall_global_int(21) == 1) then begin
        format(" " + message_str(61, 205), 127, 240, 240, 40, 0);
    end
    if (get_sfall_global_int(22) == 1) then begin
        format(" " + message_str(61, 206), 127, 285, 240, 40, 0);
    end
    if (get_sfall_global_int(23) == 1) then begin
        format(" " + message_str(61, 207), 127, 330, 240, 40, 0);
    end
    if (get_sfall_global_int(29) == 1) then begin
        format(" " + message_str(61, 210), 435, 60, 240, 30, 0);
    end
    if (get_sfall_global_int(24) == 1) then begin
        format(" " + message_str(61, 211), 435, 90, 240, 45, 0);
    end
    if (get_sfall_global_int(25) == 1) then begin
        format(" " + message_str(61, 212), 435, 135, 240, 45, 0);
    end
    if (get_sfall_global_int(26) == 1) then begin
        format(" " + message_str(61, 213), 435, 180, 240, 45, 0);
    end
    if (get_sfall_global_int(27) == 1) then begin
        format(" " + message_str(61, 214), 435, 225, 240, 45, 0);
    end
    if (get_sfall_global_int(28) == 1) then begin
        format(" " + message_str(61, 215), 435, 270, 240, 45, 0);
    end
    showWin;
    addButton("BTN_exit", 657, 21, 60, 45);
    addButtonGfx("BTN_exit", "PCX/ntbkbck1.pcx", "PCX/ntbkbck1.pcx", "PCX/ntbkbck2.pcx");
    addButtonProc("BTN_exit", vide, vide, vide, NoteBook_End);
    addButton("BTN_last", 86, 434, 60, 45);
    addButtonGfx("BTN_last", "PCX/ntbklst1.pcx", "PCX/ntbklst1.pcx", "PCX/ntbklst2.pcx");
    addButtonProc("BTN_last", vide, vide, vide, vide);
    addButton("BTN_next", 657, 434, 60, 45);
    addButtonGfx("BTN_next", "PCX/ntbknxt1.pcx", "PCX/ntbknxt1.pcx", "PCX/ntbknxt2.pcx");
    addButtonProc("BTN_next", vide, vide, vide, vide);
    game_ui_disable;
    mouseShape("PCX/mouse2.pcx", 0, 0);
end

procedure NoteBook_End
begin
    deleteWin("NoteBook");
    game_ui_enable;
end

procedure vide
begin
end

