variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;
variable trading_container;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node999;
procedure Node998;
procedure NodeBarter;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(60, 70));
        set_local_var(5, random(40, 50));
        set_local_var(6, random(-30, 20));
        critter_add_trait(self_obj, 1, 6, 11);
        critter_add_trait(self_obj, 1, 5, 33);
        if (random(0, 100) <= 75) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(1, 40));
        end
        if (random(0, 100) <= 45) then begin
            add_obj_to_inven(self_obj, create_object_sid(415, 1, 2, -1));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(419, 1, 2, -1));
        end
        if (random(0, 100) <= 30) then begin
            add_obj_to_inven(self_obj, create_object_sid(434, 1, 2, -1));
        end
        if (random(0, 100) <= 20) then begin
            add_obj_to_inven(self_obj, create_object_sid(145, 1, 2, -1));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object_sid(223, 1, 2, -1));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object_sid(103, 1, 2, -1));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object_sid(67, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(226, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(410, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(433, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(423, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(323, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(239, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(443, 1, 2, -1));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(51) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(227, 2));
    end
    else begin
        display_msg(message_str(227, 4));
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(227, 1));
    end
    else begin
        display_msg(message_str(227, 3));
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    start_gdialog(227, self_obj, -1, -1, -1);
    gsay_start;
    if (local_var(7) == 0) then begin
        call Node001();
    end
    else begin
        call Node010();
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    set_global_var(118, global_var(118) bwor 4194304);
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 1);
        if ((51 == 50) or (51 == 59)) then begin
            set_global_var(51, global_var(51) - 3);
        end
        else begin
            set_global_var(51, global_var(51) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
end

procedure Node001
begin
    set_local_var(7, 1);
    already_talk := 1;
    gsay_reply(227, 10);
    gsay_option(227, 11, Node002, 50);
    gsay_option(227, 12, Node999, 50);
end

procedure Node002
begin
    gsay_reply(227, 20);
    gsay_option(227, 21, Node010, 50);
    gsay_option(227, 22, Node999, 50);
end

procedure Node010
begin
    if (already_talk == 0) then begin
        already_talk := 1;
        if (global_var(227) == 2) then begin
            gsay_reply(227, 1001);
        end
        else begin
            gsay_reply(227, 1002);
        end
    end
    else begin
        gsay_reply(227, 1003);
    end
    if (global_var(160) == 1) then begin
        gsay_option(227, 101, Node011, 50);
    end
    gsay_option(227, 102, Node013, 50);
    gsay_option(227, 103, Node014, 50);
    gsay_option(227, 104, Node023, 50);
    if ((global_var(158) == 1) or (global_var(159) == 1) and ((global_var(158) != 2) and (global_var(159) != 2))) then begin
        gsay_option(227, 105, Node024, 50);
    end
    gsay_option(227, 106, Node999, 50);
end

procedure Node011
begin
    gsay_reply(227, 110);
    gsay_option(227, 111, Node012, 50);
end

procedure Node012
begin
    set_global_var(229, 1);
    gsay_reply(227, 120);
    gsay_option(227, 121, Node010, 50);
    gsay_option(227, 122, Node999, 50);
end

procedure Node013
begin
    gsay_reply(227, 130);
    gsay_option(227, 131, Node010, 50);
    gsay_option(227, 132, Node999, 50);
end

procedure Node014
begin
    gsay_reply(227, 140);
    gsay_option(227, 141, Node015, 50);
    gsay_option(227, 142, Node010, 50);
end

procedure Node015
begin
    gsay_reply(227, 150);
    gsay_option(227, 151, Node016, 50);
    gsay_option(227, 152, Node010, 50);
end

procedure Node016
begin
    gsay_reply(227, 160);
    gsay_option(227, 161, Node017, 50);
    gsay_option(227, 162, Node010, 50);
end

procedure Node017
begin
    gsay_reply(227, 170);
    gsay_option(227, 171, Node018, 50);
    gsay_option(227, 172, Node010, 50);
end

procedure Node018
begin
    gsay_reply(227, 180);
    gsay_option(227, 181, Node019, 50);
    gsay_option(227, 182, Node010, 50);
end

procedure Node019
begin
    gsay_reply(227, 190);
    gsay_option(227, 191, Node020, 50);
    gsay_option(227, 192, Node010, 50);
end

procedure Node020
begin
    gsay_reply(227, 200);
    gsay_option(227, 201, Node021, 50);
    gsay_option(227, 202, Node010, 50);
end

procedure Node021
begin
    gsay_reply(227, 210);
    gsay_option(227, 211, Node022, 50);
    gsay_option(227, 212, Node010, 50);
end

procedure Node022
begin
    gsay_reply(227, 220);
    gsay_option(227, 221, Node010, 50);
    gsay_option(227, 222, Node999, 50);
end

procedure Node023
begin
    gsay_reply(227, 230);
    gsay_option(227, 231, Node010, 50);
end

procedure Node024
begin
    if (global_var(158) == 2) then begin
        gsay_reply(227, 2401);
    end
    else begin
        if (global_var(159) == 2) then begin
            gsay_reply(227, 2402);
        end
        else begin
            gsay_reply(227, 2403);
        end
    end
    if ((global_var(158) == 1) or (global_var(159) == 1) and ((global_var(158) != 2) and (global_var(159) != 2))) then begin
        gsay_option(227, 241, Node025, 50);
    end
    if ((global_var(158) == 1) and ((global_var(158) != 2) and (global_var(159) != 2))) then begin
        gsay_option(227, 242, Node026, 50);
    end
    if ((global_var(159) == 1) and ((global_var(158) != 2) and (global_var(159) != 2))) then begin
        gsay_option(227, 243, Node030, 50);
    end
    gsay_option(227, 244, Node010, 50);
end

procedure Node025
begin
    gsay_reply(227, 250);
    gsay_option(227, 251, Node024, 50);
    gsay_option(227, 252, Node010, 50);
end

procedure Node026
begin
    gsay_reply(227, 260);
    gsay_option(227, 261, Node027, 50);
    if (has_skill(dude_obj, 14) >= 65) then begin
        gsay_option(227, 262, Node028, 50);
    end
end

procedure Node027
begin
    gsay_reply(227, 270);
    gsay_option(227, 271, Node010, 50);
    gsay_option(227, 272, Node024, 50);
end

procedure Node028
begin
    gsay_reply(227, 280);
    gsay_option(227, 281, Node029, 50);
end

procedure Node029
begin
    set_global_var(230, 2);
    gsay_reply(227, 290);
    gsay_option(227, 291, Node010, 50);
end

procedure Node030
begin
    gsay_reply(227, 300);
    gsay_option(227, 301, Node027, 50);
    if (global_var(235) == 1) then begin
        gsay_option(227, 302, Node031, 50);
    end
end

procedure Node031
begin
    gsay_reply(227, 310);
    gsay_option(227, 311, Node032, 50);
end

procedure Node032
begin
    set_global_var(232, 1);
    gsay_reply(227, 320);
    gsay_option(227, 321, Node010, 50);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    set_map_var(0, 1);
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end

