procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node050;
procedure Node051;
procedure Node051a;
procedure Node052;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node999;
procedure Node998;
procedure NodeBarter;
procedure ItemQuest;

variable dude_objective_reputation;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;
variable trading_container;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(60, 70));
        set_local_var(5, random(40, 50));
        set_local_var(6, random(-30, 20));
        critter_add_trait(self_obj, 1, 6, 11);
        critter_add_trait(self_obj, 1, 5, 32);
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(234, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(235, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(236, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(297, 1, 2, -1), random(1, 2));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(51) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(218, 2));
    end
    else begin
        display_msg(message_str(218, 4));
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(218, 1));
    end
    else begin
        display_msg(message_str(218, 3));
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    start_gdialog(218, self_obj, -1, -1, -1);
    gsay_start;
    if (local_var(7) == 0) then begin
        call Node001();
    end
    else begin
        call Node010();
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    set_global_var(118, global_var(118) bwor 8192);
    if (global_var(155) == 1) then begin
        set_global_var(155, 0);
    end
    if (global_var(163) == 1) then begin
        set_global_var(163, 0);
    end
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 1);
        if ((51 == 50) or (51 == 59)) then begin
            set_global_var(51, global_var(51) - 3);
        end
        else begin
            set_global_var(51, global_var(51) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (not(tile_contains_obj_pid(1, 2, 250))) then begin
        trading_container := create_object_sid(250, 1, 2, -1);
    end
    else begin
        trading_container := tile_contains_pid_obj(1, 2, 250);
    end
    if (tile_num(self_obj) != local_var(3)) then begin
        move_to(self_obj, local_var(3), elevation(self_obj));
    end
    anim(self_obj, 1000, 4);
    if (days_since_visited > 4) then begin
        move_obj_inven_to_obj(self_obj, trading_container);
        add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(100, 500));
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(234, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(235, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(236, 1, 2, -1), random(1, 3));
        end
        if (random(0, 100) <= 80) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(297, 1, 2, -1), random(1, 3));
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
end

procedure Node001
begin
    set_local_var(7, 1);
    already_talk := 1;
    gsay_reply(218, 10);
    gsay_option(218, 11, Node002, 50);
    gsay_option(218, 12, Node006, 50);
    gsay_option(218, 13, Node008, 50);
end

procedure Node002
begin
    gsay_reply(218, 20);
    gsay_option(218, 21, Node003, 50);
    gsay_option(218, 22, Node005, 50);
    gsay_option(218, 23, Node008, 50);
end

procedure Node003
begin
    gsay_reply(218, 30);
    gsay_option(218, 31, Node005, 50);
    gsay_option(218, 32, Node006, 50);
    gsay_option(218, 33, Node004, 50);
end

procedure Node004
begin
    gsay_reply(218, 40);
    gsay_option(218, 41, Node010, 50);
    gsay_option(218, 42, Node006, 50);
    gsay_option(218, 43, Node007, 50);
end

procedure Node005
begin
    gsay_reply(218, 50);
    gsay_option(218, 51, Node010, 50);
    gsay_option(218, 52, Node006, 50);
    gsay_option(218, 53, Node007, 50);
end

procedure Node006
begin
    set_local_var(8, 1);
    gsay_reply(218, 60);
    gsay_option(218, 61, Node011, 50);
    gsay_option(218, 62, Node999, 50);
    gsay_option(218, 63, Node998, 50);
end

procedure Node007
begin
    set_local_var(8, 1);
    gsay_reply(218, 70);
    gsay_option(218, 71, Node999, 50);
    gsay_option(218, 72, Node998, 50);
    gsay_option(218, 73, Node998, 50);
end

procedure Node008
begin
    gsay_reply(218, 80);
    gsay_option(218, 81, Node009, 50);
    gsay_option(218, 82, Node006, 50);
    gsay_option(218, 83, Node007, 50);
end

procedure Node009
begin
    gsay_reply(218, 90);
    gsay_option(218, 91, Node010, 50);
    gsay_option(218, 92, Node006, 50);
    gsay_option(218, 93, Node007, 50);
end

procedure Node010
begin
    if (already_talk == 0) then begin
        already_talk := 1;
        if (global_var(227) == 2) then begin
            gsay_reply(218, 1001);
        end
        else begin
            if (local_var(8) == 1) then begin
                gsay_reply(218, 1002);
            end
            else begin
                gsay_reply(218, 1004);
            end
        end
    end
    else begin
        if (local_var(8) == 1) then begin
            gsay_reply(218, 1003);
        end
        else begin
            gsay_reply(218, 1005);
        end
    end
    if (local_var(8) == 1) then begin
        gsay_option(218, 101, Node012, 50);
    end
    gsay_option(218, 102, Node023, 50);
    gsay_option(218, 103, Node024, 50);
    gsay_option(218, 104, Node025, 50);
    gsay_option(218, 105, Node027, 50);
    gsay_option(218, 106, Node026, 50);
    if (global_var(163) == 1) then begin
        gsay_option(218, 107, Node054, 50);
    end
    if ((global_var(152) == 1) and (global_var(228) == 0)) then begin
        gsay_option(218, 108, Node059, 50);
    end
    gsay_option(218, 109, Node999, 50);
end

procedure Node011
begin
    set_local_var(8, 0);
    gsay_reply(218, 110);
    gsay_option(218, 111, Node010, 50);
    gsay_option(218, 112, Node999, 50);
end

procedure Node012
begin
    gsay_reply(218, 120);
    if (item_caps_total(dude_obj) >= 5) then begin
        gsay_option(218, 121, Node013, 50);
    end
    if (item_caps_total(dude_obj) >= 10) then begin
        gsay_option(218, 122, Node016, 50);
    end
    if (item_caps_total(dude_obj) >= 15) then begin
        gsay_option(218, 123, Node018, 50);
    end
    if (item_caps_total(dude_obj) >= 20) then begin
        gsay_option(218, 124, Node020, 50);
    end
    if (item_caps_total(dude_obj) >= 25) then begin
        gsay_option(218, 125, Node022, 50);
    end
    gsay_option(218, 126, Node999, 50);
end

procedure Node013
begin
    gsay_reply(218, 130);
    if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(dude_obj, 3) >= 9) or ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(dude_obj, 3) >= 10))) then begin
        gsay_option(218, 131, Node014, 50);
    end
    else begin
        gsay_option(218, 132, Node015, 50);
    end
end

procedure Node014
begin
    set_local_var(8, 0);
    item_caps_adjust(dude_obj, -5);
    gsay_reply(218, 140);
    gsay_option(218, 141, Node010, 50);
end

procedure Node015
begin
    gsay_reply(218, 150);
    gsay_option(218, 151, Node999, 50);
end

procedure Node016
begin
    gsay_reply(218, 160);
    if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(dude_obj, 3) >= 7) or ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(dude_obj, 3) >= 8))) then begin
        gsay_option(218, 161, Node017, 50);
    end
    else begin
        gsay_option(218, 162, Node015, 50);
    end
end

procedure Node017
begin
    set_local_var(8, 0);
    item_caps_adjust(dude_obj, -10);
    gsay_reply(218, 170);
    gsay_option(218, 171, Node010, 50);
end

procedure Node018
begin
    gsay_reply(218, 180);
    if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(dude_obj, 3) >= 5) or ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(dude_obj, 3) >= 6))) then begin
        gsay_option(218, 181, Node019, 50);
    end
    else begin
        gsay_option(218, 182, Node015, 50);
    end
end

procedure Node019
begin
    set_local_var(8, 0);
    item_caps_adjust(dude_obj, -15);
    gsay_reply(218, 190);
    gsay_option(218, 191, Node010, 50);
end

procedure Node020
begin
    gsay_reply(218, 200);
    if ((get_critter_stat(dude_obj, 34) == 0) and (get_critter_stat(dude_obj, 3) >= 3) or ((get_critter_stat(dude_obj, 34) == 1) and (get_critter_stat(dude_obj, 3) >= 4))) then begin
        gsay_option(218, 201, Node021, 50);
    end
    else begin
        gsay_option(218, 202, Node015, 50);
    end
end

procedure Node021
begin
    set_local_var(8, 0);
    item_caps_adjust(dude_obj, -20);
    gsay_reply(218, 210);
    gsay_option(218, 211, Node010, 50);
end

procedure Node022
begin
    set_local_var(8, 0);
    item_caps_adjust(dude_obj, -25);
    gsay_reply(218, 220);
    gsay_option(218, 221, Node010, 50);
end

procedure Node023
begin
    if (global_var(227) == 2) then begin
        gsay_reply(218, 2301);
    end
    else begin
        if (local_var(8) == 1) then begin
            gsay_reply(218, 2302);
        end
        else begin
            gsay_reply(218, 2303);
        end
    end
    if ((local_var(8) == 0) and (global_var(151) == 1)) then begin
        gsay_option(218, 231, Node038, 50);
    end
    if ((local_var(8) == 0) and (global_var(163) == 0)) then begin
        gsay_option(218, 232, Node049, 50);
    end
    if (local_var(8) == 0) then begin
        gsay_option(218, 233, Node037, 50);
    end
    gsay_option(218, 234, Node010, 50);
    gsay_option(218, 235, Node999, 50);
end

procedure Node024
begin
    if (global_var(227) == 2) then begin
        gsay_reply(218, 2401);
    end
    else begin
        if (local_var(8) == 0) then begin
            gsay_reply(218, 2402);
        end
        else begin
            gsay_reply(218, 2403);
        end
    end
    if (local_var(8) == 0) then begin
        gsay_option(218, 241, Node023, 50);
        gsay_option(218, 242, Node037, 50);
    end
    gsay_option(218, 243, Node010, 50);
    gsay_option(218, 244, Node999, 50);
end

procedure Node025
begin
    if (local_var(8) == 1) then begin
        gsay_reply(218, 2501);
    end
    else begin
        gsay_reply(218, 2502);
    end
    if (local_var(8) == 0) then begin
        gsay_option(218, 251, NodeBarter, 50);
    end
    gsay_option(218, 252, Node010, 50);
    gsay_option(218, 253, Node999, 50);
end

procedure Node026
begin
    if (local_var(8) == 1) then begin
        gsay_reply(218, 2601);
    end
    else begin
        gsay_reply(218, 2602);
    end
    if (local_var(8) == 0) then begin
        gsay_option(218, 261, Node037, 50);
        gsay_option(218, 262, Node057, 50);
        if (global_var(155) < 2) then begin
            gsay_option(218, 263, Node006, 50);
        end
    end
    gsay_option(218, 264, Node010, 50);
    gsay_option(218, 265, Node999, 50);
end

procedure Node027
begin
    if (local_var(8) == 1) then begin
        gsay_reply(218, 2701);
    end
    else begin
        gsay_reply(218, 2702);
    end
    if (local_var(8) == 0) then begin
        if (not(obj_carrying_pid_obj(dude_obj, 319))) then begin
            gsay_option(218, 271, Node028, 50);
        end
        else begin
            gsay_option(218, 272, Node029, 50);
        end
        gsay_option(218, 273, Node037, 50);
    end
    gsay_option(218, 274, Node010, 50);
    gsay_option(218, 275, Node061, 50);
    gsay_option(218, 276, Node999, 50);
end

procedure Node028
begin
    gsay_reply(218, 280);
    gsay_option(218, 281, Node999, 50);
    gsay_option(218, 282, Node010, 50);
end

procedure Node029
begin
    gsay_reply(218, 290);
    if (global_var(155) < 2) then begin
        gsay_option(218, 291, Node030, 50);
        gsay_option(218, 292, Node034, 50);
    end
    else begin
        gsay_option(218, 293, Node032, 50);
    end
    gsay_option(218, 294, Node010, 50);
    gsay_option(218, 295, Node999, 50);
end

procedure Node030
begin
    gsay_reply(218, 300);
    gsay_option(218, 301, Node031, 50);
    gsay_option(218, 302, Node034, 50);
    gsay_option(218, 303, Node010, 50);
    gsay_option(218, 304, Node999, 50);
end

procedure Node031
begin
    gsay_reply(218, 310);
    gsay_option(218, 311, Node034, 50);
    gsay_option(218, 312, Node010, 50);
    gsay_option(218, 313, Node999, 50);
end

procedure Node032
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(218, 3201);
    end
    else begin
        gsay_reply(218, 3202);
    end
    if (obj_carrying_pid_obj(dude_obj, 319)) then begin
        gsay_option(218, 321, Node033, 50);
    end
    gsay_option(218, 323, Node010, 50);
    gsay_option(218, 324, Node999, 50);
end

procedure Node033
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        item_caps_adjust(dude_obj, 60);
    end
    else begin
        item_caps_adjust(dude_obj, 45);
    end
    gsay_reply(218, 330);
    gsay_option(218, 331, ItemQuest, 50);
end

procedure Node034
begin
    gsay_reply(218, 340);
    if ((get_critter_stat(dude_obj, 34) == 0) and (has_skill(dude_obj, 14) >= 30) or ((get_critter_stat(dude_obj, 34) == 1) and (has_skill(dude_obj, 14) >= 40))) then begin
        gsay_option(218, 341, Node035, 50);
    end
    gsay_option(218, 342, Node010, 50);
end

procedure Node035
begin
    gsay_reply(218, 350);
    gsay_option(218, 351, Node036, 50);
end

procedure Node036
begin
    if (global_var(155) < 2) then begin
        add_obj_to_inven(dude_obj, create_object_sid(339, 1, 2, -1));
        set_global_var(155, 2);
        give_exp_points(floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 10);
    end
    gsay_reply(218, 360);
    gsay_option(218, 361, ItemQuest, 50);
end

procedure Node037
begin
    if (global_var(155) == 2) then begin
        gsay_reply(218, 3701);
    end
    else begin
        set_global_var(155, 1);
        gsay_reply(218, 3702);
    end
    if (global_var(151) == 1) then begin
        gsay_option(218, 371, Node038, 50);
    end
    if (global_var(155) < 2) then begin
        if ((get_critter_stat(dude_obj, 34) == 0) and (has_skill(dude_obj, 14) >= 55) or ((get_critter_stat(dude_obj, 34) == 1) and (has_skill(dude_obj, 14) >= 65))) then begin
            gsay_option(218, 372, Node039, 50);
        end
        if ((global_var(285) == 2) and (has_skill(dude_obj, 14) >= 20)) then begin
            gsay_option(218, 373, Node045, 50);
        end
        if (global_var(163) == 2) then begin
            gsay_option(218, 374, Node058, 50);
        end
    end
    gsay_option(218, 375, Node010, 50);
    gsay_option(218, 376, Node999, 50);
end

procedure Node038
begin
    gsay_reply(218, 380);
    gsay_option(218, 381, Node010, 50);
    gsay_option(218, 382, Node999, 50);
end

procedure Node039
begin
    gsay_reply(218, 390);
    gsay_option(218, 391, Node040, 50);
    gsay_option(218, 392, Node042, 50);
    gsay_option(218, 393, Node041, 50);
    gsay_option(218, 394, Node010, 50);
    gsay_option(218, 395, Node999, 50);
end

procedure Node040
begin
    gsay_reply(218, 400);
    gsay_option(218, 401, Node042, 50);
    gsay_option(218, 402, Node041, 50);
    gsay_option(218, 403, Node010, 50);
    gsay_option(218, 404, Node999, 50);
end

procedure Node041
begin
    gsay_reply(218, 410);
    gsay_option(218, 411, Node999, 50);
end

procedure Node042
begin
    gsay_reply(218, 420);
    if (item_caps_total(dude_obj) >= 1500) then begin
        gsay_option(218, 421, Node043, 50);
    end
    gsay_option(218, 422, Node041, 50);
end

procedure Node043
begin
    gsay_reply(218, 430);
    gsay_option(218, 431, Node044, 50);
    gsay_option(218, 432, Node999, 50);
end

procedure Node044
begin
    if (global_var(155) < 2) then begin
        add_obj_to_inven(dude_obj, create_object_sid(339, 1, 2, -1));
        set_global_var(155, 2);
        give_exp_points(floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 10);
        item_caps_adjust(dude_obj, -1500);
        item_caps_adjust(self_obj, 1500);
    end
    gsay_reply(218, 440);
    gsay_option(218, 441, Node999, 50);
end

procedure Node045
begin
    gsay_reply(218, 450);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_option(218, 451, Node046, 50);
    end
    else begin
        gsay_option(218, 452, Node047, 50);
    end
end

procedure Node046
begin
    if (global_var(155) < 2) then begin
        add_obj_to_inven(dude_obj, create_object_sid(339, 1, 2, -1));
        set_global_var(155, 2);
        give_exp_points(floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 10);
    end
    gsay_reply(218, 460);
    gsay_option(218, 461, Node999, 50);
end

procedure Node047
begin
    gsay_reply(218, 470);
    if (has_skill(dude_obj, 14) >= 40) then begin
        gsay_option(218, 471, Node048, 50);
    end
    gsay_option(218, 472, Node999, 50);
end

procedure Node048
begin
    if (global_var(155) < 2) then begin
        add_obj_to_inven(dude_obj, create_object_sid(339, 1, 2, -1));
        set_global_var(155, 2);
        give_exp_points(floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(863 / 5) + (get_critter_stat(dude_obj, 4) * floor(863 / 12)) + (get_critter_stat(dude_obj, 6) * floor(863 / 30)) + (floor(863 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 10);
    end
    gsay_reply(218, 480);
    gsay_option(218, 481, Node999, 50);
end

procedure Node049
begin
    gsay_reply(218, 490);
    gsay_option(218, 491, Node050, 50);
end

procedure Node050
begin
    gsay_reply(218, 500);
    gsay_option(218, 501, Node010, 50);
    if (global_var(285) == 2) then begin
        gsay_option(218, 502, Node051, 50);
    end
    if (global_var(285) == 3) then begin
        gsay_option(218, 503, Node052, 50);
    end
    if (global_var(285) == 1) then begin
        gsay_option(218, 504, Node053, 50);
    end
end

procedure Node051
begin
    gsay_reply(218, 510);
    gsay_option(218, 511, Node051a, 50);
    gsay_option(218, 512, Node010, 50);
end

procedure Node051a
begin
    if (global_var(163) == 0) then begin
        set_global_var(163, 1);
    end
    if (not(metarule(17, 7) == 1)) then begin
        mark_area_known(0, 7, 1);
    end
end

procedure Node052
begin
    gsay_reply(218, 520);
    gsay_option(218, 521, Node051a, 50);
    gsay_option(218, 522, Node010, 50);
end

procedure Node053
begin
    gsay_reply(218, 530);
    gsay_option(218, 531, Node051a, 50);
    gsay_option(218, 532, Node010, 50);
end

procedure Node054
begin
    gsay_reply(218, 540);
    if (obj_carrying_pid_obj(dude_obj, 318)) then begin
        gsay_option(218, 541, Node056, 50);
    end
    gsay_option(218, 542, Node055, 50);
    gsay_option(218, 543, Node010, 50);
end

procedure Node055
begin
    gsay_reply(218, 550);
    gsay_option(218, 551, Node999, 50);
end

procedure Node056
begin
    if (global_var(163) < 2) then begin
        set_global_var(163, 2);
        give_exp_points(floor(1380 / 5) + (get_critter_stat(dude_obj, 4) * floor(1380 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1380 / 30)) + (floor(1380 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(1380 / 5) + (get_critter_stat(dude_obj, 4) * floor(1380 / 12)) + (get_critter_stat(dude_obj, 6) * floor(1380 / 30)) + (floor(1380 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 3);
        add_mult_objs_to_inven(dude_obj, create_object_sid(235, 1, 2, -1), 3);
        item_caps_adjust(dude_obj, 100);
    end
    gsay_reply(218, 560);
    gsay_option(218, 561, ItemQuest, 50);
end

procedure Node057
begin
    gsay_reply(218, 570);
    gsay_option(218, 571, Node010, 50);
    gsay_option(218, 572, Node999, 50);
end

procedure Node058
begin
    if (global_var(155) < 2) then begin
        set_global_var(155, 2);
        give_exp_points(floor(575 / 5) + (get_critter_stat(dude_obj, 4) * floor(575 / 12)) + (get_critter_stat(dude_obj, 6) * floor(575 / 30)) + (floor(575 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(575 / 5) + (get_critter_stat(dude_obj, 4) * floor(575 / 12)) + (get_critter_stat(dude_obj, 6) * floor(575 / 30)) + (floor(575 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(51, global_var(51) + 2);
    end
    gsay_reply(218, 580);
    gsay_option(218, 581, Node999, 50);
end

procedure Node059
begin
    gsay_reply(218, 590);
    gsay_option(218, 591, Node060, 50);
end

procedure Node060
begin
    set_global_var(228, 1);
    gsay_reply(218, 600);
    gsay_option(218, 601, Node010, 50);
end

procedure Node061
begin
    gsay_reply(218, 610);
    gsay_option(218, 611, Node062, 50);
end

procedure Node062
begin
    mark_area_known(0, 10, 1);
    mark_area_known(0, 7, 1);
    gsay_reply(218, 620);
    gsay_option(218, 621, Node010, 50);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    set_map_var(0, 1);
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end

procedure ItemQuest
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    LVar0 := obj_carrying_pid_obj(dude_obj, 319);
    LVar1 := obj_carrying_pid_obj(dude_obj, 318);
    if (LVar0) then begin
        rm_obj_from_inven(dude_obj, LVar0);
        destroy_object(LVar0);
    end
    if (LVar1) then begin
        rm_obj_from_inven(dude_obj, LVar1);
        destroy_object(LVar1);
    end
end

