variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable z_weapon_class;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node999;
procedure NodeBarter;

variable max_distance;
variable barter_mod;
variable trading_container;
variable ungry_count1;
variable ungry_count2;
variable floater_is_called;
variable animation_is_called;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(7, has_trait(1, self_obj, 10));
        set_local_var(1, 1);
        set_local_var(4, random(70, 99));
        set_local_var(5, random(30, 80));
        set_local_var(6, random(-10, 10));
        critter_add_trait(self_obj, 1, 6, 8);
        critter_add_trait(self_obj, 1, 5, 21);
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(146, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(65, 1, 2, -1));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(108, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(139, 1, 2, -1));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(214, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(63, 1, 2, -1));
        end
        if (random(0, 100) <= 60) then begin
            add_obj_to_inven(self_obj, create_object_sid(67, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(132, 1, 2, -1));
        end
        if (random(0, 100) <= 50) then begin
            add_obj_to_inven(self_obj, create_object_sid(147, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(38, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(226, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(225, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(227, 1, 2, -1));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(2, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(5, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(7, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(9, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(14, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(33, 1, 2, -1), random(1, 3));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(25, 1, 2, -1), random(2, 6));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(20, 1, 2, -1), random(5, 40));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0) and (elevation(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(29, 76), 1);
    end
    if ((tile_num(self_obj) == local_var(3)) and (has_trait(1, self_obj, 10) != 0) and (anim_busy(self_obj) == 0)) then begin
        anim(self_obj, 1000, 0);
    end
    if ((ungry_count1 >= 10) or (ungry_count2 >= 10)) then begin
        ungry_count1 := 0;
        ungry_count2 := 0;
        set_local_var(2, 1);
    end
    if ((ungry_count1 >= 0) and (tile_distance(tile_num(self_obj), tile_num(dude_obj)) > 3)) then begin
        ungry_count1 := 0;
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(50) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(211, random(6, 9)));
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(211, random(1, 5)));
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
    script_overrides;
    ungry_count2 := ungry_count2 + random(2, 4);
    if (ungry_count2 <= 6) then begin
        float_msg(self_obj, message_str(211, random(25, 29)), 0);
    end
    else begin
        float_msg(self_obj, message_str(211, random(25, 29)), 2);
    end
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    start_gdialog(211, self_obj, -1, -1, -1);
    gsay_start;
    call Node001();
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 1);
        if ((50 == 50) or (50 == 59)) then begin
            set_global_var(50, global_var(50) - 3);
        end
        else begin
            set_global_var(50, global_var(50) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (not(tile_contains_obj_pid(1, 2, 250))) then begin
        trading_container := create_object_sid(250, 1, 2, -1);
    end
    else begin
        trading_container := tile_contains_pid_obj(1, 2, 250);
    end
    if ((random(0, 100) <= 60) and tile_contains_obj_pid(22294, 0, 16777339)) then begin
        move_to(self_obj, local_var(3), 0);
    end
    else begin
        move_to(self_obj, local_var(3), 1);
    end
    anim(self_obj, 1000, local_var(7));
    if (days_since_visited > 2) then begin
        move_obj_inven_to_obj(self_obj, trading_container);
        add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(10, 200));
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(146, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(65, 1, 2, -1));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(108, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(139, 1, 2, -1));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object_sid(214, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(63, 1, 2, -1));
        end
        if (random(0, 100) <= 60) then begin
            add_obj_to_inven(self_obj, create_object_sid(67, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(132, 1, 2, -1));
        end
        if (random(0, 100) <= 50) then begin
            add_obj_to_inven(self_obj, create_object_sid(147, 1, 2, -1));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(38, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(226, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(225, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(227, 1, 2, -1));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(2, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(5, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(7, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(9, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(14, 1, 2, -1), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(33, 1, 2, -1), random(1, 3));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(25, 1, 2, -1), random(2, 6));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(20, 1, 2, -1), random(5, 40));
        end
    end
    max_distance := 8;
    if (random(0, 100) <= 20) then begin
        metarule3(107, self_obj, 16777260, 0);
    end
    else begin
        if (random(0, 100) <= 25) then begin
            metarule3(107, self_obj, 16777271, 0);
        end
        else begin
            if (random(0, 100) <= 33) then begin
                metarule3(107, self_obj, 16777290, 0);
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777272, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777246, 0);
                end
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        if (tile_num(self_obj) == local_var(3)) then begin
            if (random(0, 100) <= 80) then begin
                if (random(0, 100) <= 60) then begin
                    float_msg(self_obj, message_str(211, random(1030, 1039)), 0);
                end
            end
            else begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(21501, random(0, 5), random(0, 4)), 0);
            end
        end
        else begin
            if (random(0, 100) <= 70) then begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(21501, random(0, 5), random(0, 7)), 0);
            end
            else begin
                animate_move_obj_to_tile(self_obj, local_var(3), 0);
            end
        end
        animation_is_called := 0;
    end
end

procedure Node001
begin
    gsay_reply(211, random(10, 12));
    gsay_option(211, random(13, 15), NodeBarter, 50);
    gsay_option(211, random(16, 18), Node999, 50);
end

procedure Node999
begin
    anim(self_obj, 1000, local_var(7));
end

procedure NodeBarter
begin
    barter_mod := 50 * (0 - 1);
    gdialog_mod_barter(barter_mod);
    call Node001();
end

