variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;
variable trading_container;
variable trading_container2;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure fight_for_vins1;
procedure fight_for_vins2;
procedure StenBeatCasper;
procedure Node999;
procedure Node998;
procedure NodeBarter;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(45, 55));
        set_local_var(5, random(55, 65));
        set_local_var(6, random(-20, 10));
        critter_add_trait(self_obj, 1, 6, 7);
        critter_add_trait(self_obj, 1, 5, 25);
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object_sid(438, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(238, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(213, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(233, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(420, 1, 2, -1));
        end
        if (random(0, 100) <= 9) then begin
            add_obj_to_inven(self_obj, create_object_sid(236, 1, 2, -1));
        end
        if (random(0, 100) <= 8) then begin
            add_obj_to_inven(self_obj, create_object_sid(218, 1, 2, -1));
        end
        if (random(0, 100) <= 6) then begin
            add_obj_to_inven(self_obj, create_object_sid(440, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(244, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(428, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(422, 1, 2, -1));
        end
        if (random(0, 100) <= 4) then begin
            add_obj_to_inven(self_obj, create_object_sid(423, 1, 2, -1));
        end
        if (random(0, 100) <= 3) then begin
            add_obj_to_inven(self_obj, create_object_sid(426, 1, 2, -1));
        end
        if (random(0, 100) <= 2) then begin
            add_obj_to_inven(self_obj, create_object_sid(433, 1, 2, -1));
        end
        if (random(0, 100) <= 2) then begin
            add_obj_to_inven(self_obj, create_object_sid(421, 1, 2, -1));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object_sid(110, 1, 2, -1));
            wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 110));
        end
        else begin
            add_obj_to_inven(self_obj, create_object_sid(65, 1, 2, -1));
            wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 65));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object_sid(438, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(238, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_mult_objs_to_inven(self_obj, create_object_sid(213, 1, 2, -1), random(1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(233, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(226, 1, 2, -1));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object_sid(420, 1, 2, -1));
        end
        if (random(0, 100) <= 9) then begin
            add_obj_to_inven(self_obj, create_object_sid(236, 1, 2, -1));
        end
        if (random(0, 100) <= 8) then begin
            add_obj_to_inven(self_obj, create_object_sid(218, 1, 2, -1));
        end
        if (random(0, 100) <= 6) then begin
            add_obj_to_inven(self_obj, create_object_sid(440, 1, 2, -1));
        end
        if (random(0, 100) <= 6) then begin
            add_obj_to_inven(self_obj, create_object_sid(106, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(412, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(428, 1, 2, -1));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object_sid(422, 1, 2, -1));
        end
        if (random(0, 100) <= 4) then begin
            add_obj_to_inven(self_obj, create_object_sid(423, 1, 2, -1));
        end
        if (random(0, 100) <= 3) then begin
            add_obj_to_inven(self_obj, create_object_sid(426, 1, 2, -1));
        end
        if (random(0, 100) <= 2) then begin
            add_obj_to_inven(self_obj, create_object_sid(433, 1, 2, -1));
        end
        if (random(0, 100) <= 2) then begin
            add_obj_to_inven(self_obj, create_object_sid(421, 1, 2, -1));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
end

procedure combat_p_proc
begin
    if ((global_var(324) == 3) and combat_is_initialized) then begin
        if (get_critter_stat(self_obj, 35) <= 12) then begin
            float_msg(self_obj, message_str(167, 8), 0);
            game_ui_disable;
            terminate_combat;
            add_timer_event(self_obj, 10, 4);
        end
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(170, 2));
    end
    else begin
        display_msg(message_str(170, 4));
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_msg(message_str(170, 1));
    end
    else begin
        display_msg(message_str(170, 3));
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    if (global_var(324) >= 4) then begin
        float_msg(self_obj, message_str(170, random(7, 9)), 0);
    end
    else begin
        start_gdialog(170, self_obj, -1, -1, -1);
        gsay_start;
        if (local_var(7) == 0) then begin
            call Node001();
        end
        else begin
            call Node010();
        end
        gsay_end;
        end_dialogue;
    end
end

procedure destroy_p_proc
begin
    set_global_var(69, global_var(69) bwor 33554432);
    if (global_var(324) == 3) then begin
        trading_container := tile_contains_pid_obj(111, 2, 250);
        trading_container2 := tile_contains_pid_obj(2, 2, 250);
        move_obj_inven_to_obj(trading_container, dude_obj);
        set_global_var(323, 1);
        fadeOut(800);
        move_to(dude_obj, 13690, 0);
        anim(dude_obj, 1000, 4);
        move_to(self_obj, 13692, 0);
        anim(self_obj, 1000, 1);
        set_global_var(324, 4);
        metarule3(108, tile_num(dude_obj), elevation(self_obj), 0);
        fadeIn(700);
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (not(metarule(22, 0)) == 1) then begin
        if (global_var(324) == 2) then begin
            game_ui_disable;
            if (not(tile_contains_obj_pid(111, 2, 250))) then begin
                trading_container := create_object_sid(250, 111, 2, -1);
            end
            else begin
                trading_container := tile_contains_pid_obj(111, 2, 250);
            end
            if (not(tile_contains_obj_pid(2, 2, 250))) then begin
                trading_container2 := create_object_sid(250, 2, 2, -1);
            end
            else begin
                trading_container2 := tile_contains_pid_obj(2, 2, 250);
            end
            move_obj_inven_to_obj(dude_obj, trading_container);
            move_obj_inven_to_obj(self_obj, trading_container2);
            move_to(self_obj, 10892, 0);
            anim(self_obj, 1000, 1);
            add_timer_event(self_obj, 10, 3);
        end
        if ((global_var(325) == 2) and (elevation(self_obj) == 2)) then begin
            set_global_var(325, 3);
            move_to(self_obj, local_var(3), 0);
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
    if (fixed_param == 3) then begin
        set_global_var(324, 3);
        float_msg(self_obj, message_str(170, 16), 0);
        game_ui_enable;
        critter_add_trait(self_obj, 1, 6, 28);
        attack_setup(self_obj, dude_obj);
    end
    if (fixed_param == 4) then begin
        trading_container := tile_contains_pid_obj(111, 2, 250);
        trading_container2 := tile_contains_pid_obj(2, 2, 250);
        move_obj_inven_to_obj(trading_container, dude_obj);
        move_obj_inven_to_obj(trading_container2, self_obj);
        set_global_var(323, 1);
        fadeOut(800);
        move_to(dude_obj, 13690, 0);
        anim(dude_obj, 1000, 4);
        move_to(self_obj, 13692, 0);
        anim(self_obj, 1000, 1);
        set_global_var(324, 4);
        critter_add_trait(self_obj, 1, 6, 7);
        metarule3(108, tile_num(dude_obj), elevation(self_obj), 0);
        fadeIn(700);
    end
    if (fixed_param == 5) then begin
        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), 1, random(25, 25)), 1);
        fadeOut(1000);
        move_to(self_obj, local_var(3), 2);
        set_global_var(325, 1);
        fadeIn(700);
    end
end

procedure Node001
begin
    already_talk := 1;
    gsay_reply(170, 10);
    if (get_critter_stat(dude_obj, 0) < 6) then begin
        gsay_option(170, 11, Node002, 50);
    end
    if (get_critter_stat(dude_obj, 0) >= 6) then begin
        gsay_option(170, 12, Node003, 50);
    end
    if ((has_skill(dude_obj, 14) >= 65) or (get_critter_stat(dude_obj, 4) > 7)) then begin
        gsay_option(170, 13, Node004, 50);
    end
    if ((has_skill(dude_obj, 10) > 80) or (get_critter_stat(dude_obj, 1) > 7)) then begin
        gsay_option(170, 14, Node005, 50);
    end
    gsay_option(170, 15, Node999, 50);
end

procedure Node002
begin
    gsay_reply(170, 20);
    gsay_option(170, 21, Node010, 50);
    gsay_option(170, 22, Node999, 50);
end

procedure Node003
begin
    gsay_reply(170, 30);
    gsay_option(170, 31, Node010, 50);
    gsay_option(170, 32, Node999, 50);
end

procedure Node004
begin
    gsay_reply(170, 40);
    gsay_option(170, 41, Node010, 50);
    gsay_option(170, 42, Node999, 50);
end

procedure Node005
begin
    gsay_reply(170, 50);
    if (get_critter_stat(dude_obj, 0) < 6) then begin
        gsay_option(170, 51, Node002, 50);
    end
    if (get_critter_stat(dude_obj, 0) >= 6) then begin
        gsay_option(170, 52, Node003, 50);
    end
    if ((has_skill(dude_obj, 14) >= 65) or (get_critter_stat(dude_obj, 4) > 7)) then begin
        gsay_option(170, 53, Node004, 50);
    end
    gsay_option(170, 55, Node999, 50);
end

procedure Node010
begin
    if (already_talk == 0) then begin
        already_talk := 1;
        gsay_reply(170, 100);
    end
    else begin
        gsay_reply(170, 101);
    end
    if ((global_var(136) == 1) and (global_var(285) == 1) and (local_var(8) == 0)) then begin
        gsay_option(170, 102, Node011, 50);
    end
    if ((global_var(136) == 1) and (global_var(285) == 1) and (local_var(8) == 0)) then begin
        gsay_option(170, 103, Node012, 50);
    end
    gsay_option(170, 104, Node015, 50);
    gsay_option(170, 105, Node016, 50);
    gsay_option(170, 106, Node017, 50);
    gsay_option(170, 107, Node018, 50);
    gsay_option(170, 108, Node019, 50);
    gsay_option(170, 109, Node999, 50);
end

procedure Node011
begin
    set_local_var(8, 1);
    gsay_reply(170, 110);
    gsay_option(170, 111, fight_for_vins1, 50);
    gsay_option(170, 112, fight_for_vins2, 50);
    gsay_option(170, 113, Node999, 50);
end

procedure Node012
begin
    set_local_var(8, 1);
    gsay_reply(170, 120);
    if (has_skill(dude_obj, 14) > 65) then begin
        gsay_option(170, 121, Node013, 50);
    end
    gsay_option(170, 122, Node014, 50);
end

procedure Node013
begin
    gsay_reply(170, 130);
    gsay_option(170, 131, StenBeatCasper, 50);
end

procedure Node014
begin
    gsay_reply(170, 140);
    gsay_option(170, 141, Node010, 50);
    gsay_option(170, 142, Node999, 50);
end

procedure Node015
begin
    gsay_reply(170, 150);
    gsay_option(170, 151, Node010, 50);
    gsay_option(170, 152, Node999, 50);
end

procedure Node016
begin
    gsay_reply(170, 160);
    gsay_option(170, 161, Node010, 50);
    gsay_option(170, 162, Node999, 50);
end

procedure Node017
begin
    gsay_reply(170, 170);
    gsay_option(170, 171, Node010, 50);
    gsay_option(170, 172, Node999, 50);
end

procedure Node018
begin
    gsay_reply(170, 180);
    gsay_option(170, 181, Node010, 50);
    gsay_option(170, 182, Node999, 50);
end

procedure Node019
begin
    gsay_reply(170, 190);
    gsay_option(170, 191, Node998, 50);
    gsay_option(170, 192, Node010, 50);
    gsay_option(170, 193, Node999, 50);
end

procedure fight_for_vins1
begin
    set_global_var(324, 3);
    critter_heal(self_obj, -10);
    display_msg(message_str(170, 5));
end

procedure fight_for_vins2
begin
    set_global_var(324, 3);
    critter_heal(self_obj, -1);
    display_msg(message_str(170, 6));
end

procedure StenBeatCasper
begin
    if (global_var(321) == 0) then begin
        give_exp_points(floor(500 / 5) + (get_critter_stat(dude_obj, 4) * floor(500 / 12)) + (get_critter_stat(dude_obj, 6) * floor(500 / 30)) + (floor(500 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(10, random(140, 143)) + (floor(500 / 5) + (get_critter_stat(dude_obj, 4) * floor(500 / 12)) + (get_critter_stat(dude_obj, 6) * floor(500 / 30)) + (floor(500 / 75) * (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)))) + message_str(10, 144));
        set_global_var(321, 1);
    end
    add_timer_event(self_obj, 8, 5);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    attack_setup(self_obj, dude_obj);
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end

