variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(7, has_trait(1, self_obj, 10));
        set_local_var(4, random(70, 80));
        set_local_var(5, random(30, 70));
        set_local_var(6, random(-10, 10));
        critter_add_trait(self_obj, 1, 6, random(29, 32));
        critter_add_trait(self_obj, 1, 5, 24);
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        add_timer_event(self_obj, random(100, 500), 1);
        animation_is_called := 1;
    end
    if ((float_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        add_timer_event(self_obj, random(100, 600), 2);
        float_is_called := 1;
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(52) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(147, random(6, 9)));
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(147, random(1, 5)));
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
    script_overrides;
    float_msg(self_obj, message_str(147, random(1040, 1049)), 2);
    set_local_var(6, local_var(6) - random(5, 10));
end

procedure talk_p_proc
begin
    if (global_var(0) > 0) then begin
        dude_objective_reputation := (global_var(52) * 30) + global_var(0) - (20 * global_var(1));
    end
    else begin
        dude_objective_reputation := (global_var(52) * 30) + global_var(0) - (20 * global_var(1));
    end
    if ((dude_objective_reputation + local_var(6)) >= 300) then begin
        self_subjective_reaction := 1;
    end
    else begin
        if (((dude_objective_reputation + local_var(6)) >= -300) and ((dude_objective_reputation + local_var(6)) < 300)) then begin
            self_subjective_reaction := 0;
        end
        else begin
            self_subjective_reaction := -1;
        end
    end
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
    end
    if (self_subjective_reaction == 1) then begin
        float_msg(self_obj, message_str(147, random(1000, 1009)), 3);
    end
    if (self_subjective_reaction == 0) then begin
        float_msg(self_obj, message_str(147, random(1010, 1019)), 0);
        set_local_var(6, local_var(6) - random(0, 5));
    end
    if (self_subjective_reaction == -1) then begin
        float_msg(self_obj, message_str(147, random(1020, 1029)), 2);
        set_local_var(2, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 1);
        if ((52 == 50) or (52 == 59)) then begin
            set_global_var(52, global_var(52) - 3);
        end
        else begin
            set_global_var(52, global_var(52) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(2, dude_obj, 13)) then begin
                if (global_var(81) < get_pc_stat(1)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(98, global_var(98) + 3);
                    end
                    else begin
                        set_global_var(98, global_var(98) + 1);
                    end
                    if (global_var(98) >= (2 * get_pc_stat(1))) then begin
                        set_global_var(98, 0);
                        set_global_var(81, global_var(81) + 1);
                        critter_mod_skill(dude_obj, 10, 1);
                        display_msg(message_str(10, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(0, dude_obj, 37) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(0, dude_obj, 33) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, 1)) == 245) or (obj_pid(critter_inven_obj(dude_obj, 2)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(10, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(10, random(206, 209)), 2);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(10, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(10, 204) + ((has_skill(dude_obj, 10) / 2) + (((3 * get_critter_stat(dude_obj, 5)) + (((get_critter_stat(dude_obj, 6) - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(10, 205));
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    move_to(self_obj, tile_num_in_direction(local_var(3), random(0, 5), random(0, 1)), elevation(self_obj));
    anim(self_obj, 1000, local_var(7));
    if (random(0, 100) <= 50) then begin
        if (random(0, 100) <= 50) then begin
            if (random(0, 100) <= 50) then begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777244, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777246, 0);
                end
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777250, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777251, 0);
                end
            end
        end
        else begin
            if (random(0, 100) <= 50) then begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777275, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777276, 0);
                end
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777277, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777281, 0);
                end
            end
        end
    end
    else begin
        if (random(0, 100) <= 50) then begin
            if (random(0, 100) <= 50) then begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777282, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777283, 0);
                end
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777282, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777281, 0);
                end
            end
        end
        else begin
            if (random(0, 100) <= 50) then begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777277, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777276, 0);
                end
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    metarule3(107, self_obj, 16777275, 0);
                end
                else begin
                    metarule3(107, self_obj, 16777251, 0);
                end
            end
        end
    end
    if (metarule(14, 0)) then begin
        if (random(1, 2) == 1) then begin
            if (random(0, 100) <= 40) then begin
                add_obj_to_inven(self_obj, create_object_sid(167, 1, 2, -1));
                add_mult_objs_to_inven(self_obj, create_object_sid(2, 1, 2, -1), random(21, 38));
            end
            else begin
                if (random(0, 100) <= 40) then begin
                    add_obj_to_inven(self_obj, create_object_sid(137, 1, 2, -1));
                end
                else begin
                    add_obj_to_inven(self_obj, create_object_sid(136, 1, 2, -1));
                end
                add_mult_objs_to_inven(self_obj, create_object_sid(21, 1, 2, -1), random(2, 4));
            end
            if (random(0, 100) <= 33) then begin
                add_obj_to_inven(self_obj, create_object_sid(109, 1, 2, -1));
            end
            else begin
                add_obj_to_inven(self_obj, create_object_sid(110, 1, 2, -1));
            end
            if (random(0, 100) <= 33) then begin
                add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(5, 20));
            end
            if (random(0, 100) <= 25) then begin
                add_mult_objs_to_inven(self_obj, create_object_sid(238, 1, 2, -1), random(2, 5));
            end
            if (random(0, 100) <= 15) then begin
                add_obj_to_inven(self_obj, create_object_sid(225, 1, 2, -1));
            end
            if (random(0, 100) <= 15) then begin
                add_obj_to_inven(self_obj, create_object_sid(227, 1, 2, -1));
            end
            if (random(0, 100) <= 10) then begin
                add_obj_to_inven(self_obj, create_object_sid(236, 1, 2, -1));
            end
            if (random(0, 100) <= 9) then begin
                add_obj_to_inven(self_obj, create_object_sid(39, 1, 2, -1));
            end
            if (random(0, 100) <= 8) then begin
                add_obj_to_inven(self_obj, create_object_sid(227, 1, 2, -1));
            end
            if (random(0, 100) <= 7) then begin
                add_obj_to_inven(self_obj, create_object_sid(239, 1, 2, -1));
            end
            if (random(0, 100) <= 6) then begin
                add_obj_to_inven(self_obj, create_object_sid(232, 1, 2, -1));
            end
        end
        else begin
            if (random(0, 100) <= 40) then begin
                add_obj_to_inven(self_obj, create_object_sid(164, 1, 2, -1));
                add_mult_objs_to_inven(self_obj, create_object_sid(2, 1, 2, -1), random(21, 38));
            end
            else begin
                if (random(0, 100) <= 40) then begin
                    add_obj_to_inven(self_obj, create_object_sid(150, 1, 2, -1));
                end
                else begin
                    add_obj_to_inven(self_obj, create_object_sid(159, 1, 2, -1));
                end
                add_mult_objs_to_inven(self_obj, create_object_sid(22, 1, 2, -1), random(2, 4));
            end
            if (random(0, 100) <= 33) then begin
                add_obj_to_inven(self_obj, create_object_sid(112, 1, 2, -1));
            end
            else begin
                add_obj_to_inven(self_obj, create_object_sid(109, 1, 2, -1));
            end
            if (random(0, 100) <= 33) then begin
                add_mult_objs_to_inven(self_obj, create_object_sid(41, 1, 2, -1), random(5, 20));
            end
            if (random(0, 100) <= 25) then begin
                add_mult_objs_to_inven(self_obj, create_object_sid(411, 1, 2, -1), random(3, 7));
            end
            if (random(0, 100) <= 10) then begin
                add_obj_to_inven(self_obj, create_object_sid(233, 1, 2, -1));
            end
            if (random(0, 100) <= 9) then begin
                add_obj_to_inven(self_obj, create_object_sid(243, 1, 2, -1));
            end
            if (random(0, 100) <= 8) then begin
                add_obj_to_inven(self_obj, create_object_sid(237, 1, 2, -1));
            end
            if (random(0, 100) <= 7) then begin
                add_obj_to_inven(self_obj, create_object_sid(234, 1, 2, -1));
            end
            if (random(0, 100) <= 6) then begin
                add_obj_to_inven(self_obj, create_object_sid(232, 1, 2, -1));
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized) and (anim_busy(self_obj) == 0)) then begin
        if (tile_distance(tile_num(self_obj), local_var(3)) > 1) then begin
            animate_move_obj_to_tile(self_obj, local_var(3), 0);
        end
        else begin
            anim(self_obj, 1000, local_var(7));
            reg_anim_func(2, self_obj);
            reg_anim_func(1, 1);
            if (random(0, 100) <= 50) then begin
                reg_anim_animate(self_obj, 16, -1);
            end
            else begin
                reg_anim_animate(self_obj, 17, -1);
            end
            reg_anim_func(3, 0);
        end
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_msg(self_obj, message_str(147, random(10, 19)), 0);
        float_is_called := 0;
    end
end

