procedure start;


procedure start
begin
    variable LVar0 := 0;
    if (script_action == 15) then begin
        LVar0 := create_object_sid(4, 0, 0, -1);
        add_obj_to_inven(dude_obj, LVar0);
        LVar0 := create_object_sid(18, 0, 0, -1);
        add_obj_to_inven(dude_obj, LVar0);
        LVar0 := create_object_sid(31, 0, 0, -1);
        add_obj_to_inven(dude_obj, LVar0);
        LVar0 := create_object_sid(40, 0, 0, -1);
        add_obj_to_inven(dude_obj, LVar0);
    end
    else begin
        if (script_action == 16) then begin
        end
        else begin
            if (script_action == 23) then begin
                if (elevation(dude_obj) == 0) then begin
                    set_light_level(1);
                end
                else begin
                    set_light_level(100);
                end
            end
            else begin
                if (script_action == 22) then begin
                end
            end
        end
    end
end

