/*******************************************************
*      Some unreferenced imported varables found.      *
*      Because of it it is impossible to specify       *
*      the real names of global variables.             *
*******************************************************/

variable GVar0;
variable GVar1;
variable GVar2;

procedure start;
procedure talk_p_proc;
procedure go_inside;
procedure PeasantD00;
procedure PeasantD01;
procedure PeasantD02;
procedure PeasantD03;
procedure PeasantD04;

/* ?import? variable hostile; */
/* ?import? variable armed; */
/* ?import? variable initialized; */

import variable dog_is_angry;

/* ?import? variable growling; */

import variable smartass;
import variable smartass2;


procedure start
begin
    if (not(GVar2)) then begin
        critter_add_trait(self_obj, 1, 6, 5);
        GVar2 := 1;
    end
    else begin
        if (script_action == 11) then begin
            call talk_p_proc();
        end
        else begin
            if ((script_action == 21) or (script_action == 3)) then begin
                script_overrides;
                display_msg(message_str(375, 100));
            end
            else begin
                if (script_action == 4) then begin
                    attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
                end
                else begin
                    if (script_action == 12) then begin
                        if (smartass2) then begin
                            call PeasantD00();
                        end
                        if (not(dog_is_angry)) then begin
                            call go_inside();
                        end
                    end
                    else begin
                        if (script_action == 8) then begin
                            if (action_being_used == 14) then begin
                                dialogue_system_enter;
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure talk_p_proc
begin
    if (global_var(5)) then begin
        call PeasantD02();
    end
    else begin
        if (not(dog_is_angry)) then begin
            call PeasantD04();
        end
        else begin
            if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
                call PeasantD01();
            end
            else begin
                call PeasantD03();
            end
        end
    end
end

procedure go_inside
begin
    animate_move_obj_to_tile(self_obj, 15283, 0);
end

procedure PeasantD00
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    LVar0 := random(1, 3);
    if (LVar0 == 1) then begin
        LVar1 := message_str(375, 101);
    end
    else begin
        if (LVar0 == 2) then begin
            LVar1 := message_str(375, 102);
        end
        else begin
            set_global_var(187, 1);
            LVar1 := message_str(375, 103);
        end
    end
    if (dog_is_angry) then begin
        float_msg(self_obj, LVar1, 3);
    end
    smartass2 := 0;
end

procedure PeasantD01
begin
    if (dog_is_angry) then begin
        float_msg(self_obj, message_str(375, 104), 3);
    end
end

procedure PeasantD02
begin
    if (dog_is_angry) then begin
        float_msg(self_obj, message_str(375, 105), 3);
    end
end

procedure PeasantD03
begin
    float_msg(self_obj, message_str(375, 106), 3);
    smartass := 1;
end

procedure PeasantD04
begin
    float_msg(self_obj, message_str(375, 107), 3);
end

