procedure start;
procedure critter_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure flee_dude;

variable dude_attacked_guards;
variable dude_attacked_raiders;
variable initialized;
variable raiders_left;
variable rewarded;
variable scared;

import variable random_seed_1;
import variable random_seed_2;
import variable random_seed_3;


procedure start
begin
    if (not(initialized)) then begin
        critter_add_trait(self_obj, 1, 6, 35);
        critter_add_trait(self_obj, 1, 5, 50);
        scared := global_var(334);
        initialized := 1;
    end
    else begin
        if (script_action == 12) then begin
            call critter_p_proc();
        end
        else begin
            if (script_action == 14) then begin
                call damage_p_proc();
            end
            else begin
                if (script_action == 18) then begin
                    call destroy_p_proc();
                end
                else begin
                    if (script_action == 4) then begin
                        call pickup_p_proc();
                    end
                    else begin
                        if (script_action == 11) then begin
                            call talk_p_proc();
                        end
                    end
                end
            end
        end
    end
end

procedure critter_p_proc
begin
    if (scared and (tile_distance_objs(dude_obj, self_obj) < 8)) then begin
        call flee_dude();
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        scared := 1;
        set_global_var(334, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
            set_global_var(156, 1);
            set_global_var(157, 0);
        end
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
            set_global_var(157, 1);
            set_global_var(156, 0);
        end
        set_global_var(159, global_var(159) + 1);
        if ((global_var(159) % 2) == 0) then begin
            set_global_var(155, global_var(155) - 1);
        end
    end
end

procedure pickup_p_proc
begin
    scared := 1;
    set_global_var(334, 1);
end

procedure talk_p_proc
begin
    raiders_left := random_seed_1;
    dude_attacked_raiders := random_seed_2;
    dude_attacked_guards := random_seed_3;
    if (scared) then begin
        float_msg(self_obj, message_str(753, 104), 2);
    end
    else begin
        if ((raiders_left == 0) and dude_attacked_raiders) then begin
            if (rewarded) then begin
                float_msg(self_obj, message_str(753, 101), 4);
            end
            else begin
                if (get_critter_stat(dude_obj, 34) == 0) then begin
                    float_msg(self_obj, message_str(753, 106), 4);
                end
                else begin
                    float_msg(self_obj, message_str(753, 107), 4);
                end
                rewarded := 1;
                move_obj_inven_to_obj(self_obj, dude_obj);
                set_global_var(155, global_var(155) + 3);
                give_exp_points(50);
                display_msg(message_str(753, 106));
            end
        end
        else begin
            if (dude_attacked_guards) then begin
                float_msg(self_obj, message_str(753, 103), 2);
            end
            else begin
                if (raiders_left != 0) then begin
                    if (random(0, 1)) then begin
                        float_msg(self_obj, message_str(753, 105), 3);
                    end
                    else begin
                        float_msg(self_obj, message_str(753, 102), 3);
                    end
                end
            end
        end
    end
end

procedure flee_dude
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    while (LVar1 < 5) do begin
        if (tile_distance(tile_num(dude_obj), tile_num_in_direction(tile_num(self_obj), LVar1, 3)) > LVar2) then begin
            LVar0 := tile_num_in_direction(tile_num(self_obj), LVar1, 3);
            LVar2 := tile_distance(tile_num(dude_obj), LVar0);
        end
        LVar1 := LVar1 + 1;
    end
    animate_move_obj_to_tile(self_obj, LVar0, 1);
end

