procedure start;


procedure start
begin
    if ((script_action == 21) or (script_action == 3)) then begin
        script_overrides;
        display_msg(message_str(334, 100));
    end
    else begin
        if (script_action == 4) then begin
            if (local_var(0) == 0) then begin
                script_overrides;
                display_msg(message_str(334, 101));
            end
        end
        else begin
            if (script_action == 8) then begin
                if (action_being_used == 9) then begin
                    if (is_success(roll_vs_skill(dude_obj, 9, -15))) then begin
                        set_local_var(0, 1);
                        display_msg(message_str(334, 102));
                    end
                    else begin
                        display_msg(message_str(334, 103));
                    end
                end
                else begin
                    if (action_being_used == 12) then begin
                        if (is_success(roll_vs_skill(dude_obj, 12, -5))) then begin
                            set_local_var(0, 1);
                            display_msg(message_str(334, 104));
                        end
                        else begin
                            display_msg(message_str(334, 105));
                        end
                    end
                    else begin
                        display_msg(message_str(334, 106));
                    end
                end
            end
        end
    end
end

