procedure start;
procedure use_p_proc;
procedure pickup_p_proc;


procedure start
begin
    if (script_action == 6) then begin
        call use_p_proc();
    end
    else begin
        if (script_action == 4) then begin
            call pickup_p_proc();
        end
    end
end

procedure use_p_proc
begin
    script_overrides;
    display_msg(message_str(766, 176));
end

procedure pickup_p_proc
begin
    script_overrides;
    display_msg(message_str(766, 176));
end

