procedure start;
procedure Do_Dialogue;
procedure bob0;
procedure bob1;
procedure bob2;
procedure bob3;
procedure bob4;
procedure bob5;
procedure bob6;
procedure bob7;
procedure bob8;
procedure bob9;
procedure bob10;
procedure bob11;
procedure bob12;
procedure bob13;
procedure bob14;
procedure bob15;
procedure bob16;
procedure bobend;
procedure combat;
procedure damage_p_proc;
procedure destroy_p_proc;

variable Herebefore;
variable Days;
variable Met_Casino;
variable Has_Weapon;


procedure start
begin
    if ((script_action == 21) or (script_action == 3)) then begin
        script_overrides;
        display_msg(message_str(341, 100));
    end
    else begin
        if (script_action == 18) then begin
            if (source_obj == dude_obj) then begin
                if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
                    set_global_var(156, 1);
                    set_global_var(157, 0);
                end
                if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
                    set_global_var(157, 1);
                    set_global_var(156, 0);
                end
                set_global_var(159, global_var(159) + 1);
                if ((global_var(159) % 2) == 0) then begin
                    set_global_var(155, global_var(155) - 1);
                end
            end
        end
        else begin
            if (script_action == 11) then begin
                call Do_Dialogue();
            end
            else begin
                if (script_action == 15) then begin
                    if (((game_time / (10 * 60 * 60 * 24)) - Days) >= 7) then begin
                        kill_critter(self_obj, 0);
                    end
                end
            end
        end
    end
end

procedure Do_Dialogue
begin
    if ((Has_Weapon == 0) and ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3))) then begin
        Has_Weapon := 1;
        start_gdialog(341, self_obj, 4, -1, -1);
        gsay_start;
        call bob0();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (Met_Casino) then begin
            call bob9();
        end
        else begin
            if (Herebefore) then begin
                start_gdialog(341, self_obj, 4, -1, -1);
                gsay_start;
                call bob13();
                gsay_end;
                end_dialogue;
            end
            else begin
                Herebefore := 1;
                Days := game_time / (10 * 60 * 60 * 24);
                start_gdialog(341, self_obj, 4, -1, -1);
                gsay_start;
                call bob10();
                gsay_end;
                end_dialogue;
            end
        end
    end
end

procedure bob0
begin
    gsay_reply(341, 101);
    giq_option(-3, 341, 102, bob1, 50);
    giq_option(4, 341, 103, bob2, 50);
    giq_option(4, 341, 104, bob3, 50);
    giq_option(5, 341, 105, bob3, 50);
end

procedure bob1
begin
    gsay_message(341, 106, 50);
end

procedure bob2
begin
    gsay_message(341, 107, 50);
end

procedure bob3
begin
    gsay_reply(341, 108);
    giq_option(4, 341, 109, bob4, 50);
    giq_option(6, 341, 110, bob5, 50);
end

procedure bob4
begin
    if (obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) then begin
        gsay_message(341, message_str(341, 111) + obj_pid(critter_inven_obj(dude_obj, 1)) + message_str(341, 112), 50);
    end
    else begin
        gsay_message(341, message_str(341, 113) + obj_pid(critter_inven_obj(dude_obj, 2)) + message_str(341, 114), 50);
    end
end

procedure bob5
begin
    gsay_reply(341, 115);
    giq_option(6, 341, 116, bob6, 50);
    giq_option(6, 341, 117, bob7, 50);
    giq_option(6, 341, 118, bob8, 50);
    giq_option(6, 341, 119, bobend, 50);
end

procedure bob6
begin
    gsay_reply(341, 120);
    giq_option(6, 341, 121, bob7, 50);
    giq_option(6, 341, 122, bob8, 50);
    giq_option(6, 341, 123, bobend, 50);
end

procedure bob7
begin
    gsay_reply(341, 124);
    giq_option(6, 341, 125, bob6, 50);
    giq_option(6, 341, 126, bob8, 50);
    giq_option(6, 341, 127, bobend, 50);
end

procedure bob8
begin
    gsay_reply(341, 128);
    giq_option(6, 341, 129, bob6, 50);
    giq_option(6, 341, 130, bob7, 50);
    giq_option(6, 341, 131, bobend, 50);
end

procedure bob9
begin
    float_msg(self_obj, message_str(341, 132), 0);
end

procedure bob10
begin
    gsay_reply(341, 133);
    giq_option(-3, 341, 134, bob1, 50);
    giq_option(4, 341, 135, bob2, 50);
    giq_option(4, 341, 136, bob11, 50);
    giq_option(5, 341, 137, bob5, 50);
end

procedure bob11
begin
    gsay_reply(341, 138);
    giq_option(4, 341, 139, bobend, 50);
    giq_option(6, 341, 140, bob12, 50);
end

procedure bob12
begin
    gsay_reply(341, 141);
    giq_option(6, 341, 142, bob6, 50);
    giq_option(6, 341, 143, bob7, 50);
    giq_option(6, 341, 144, bob8, 50);
    giq_option(6, 341, 145, bobend, 50);
end

procedure bob13
begin
    gsay_reply(341, 146);
    giq_option(-3, 341, 147, bob1, 50);
    giq_option(4, 341, 148, bob14, 50);
    giq_option(4, 341, 149, bob15, 50);
    giq_option(6, 341, 150, bob16, 50);
end

procedure bob14
begin
    gsay_message(341, 151, 50);
end

procedure bob15
begin
    gsay_message(341, 152, 50);
end

procedure bob16
begin
    gsay_reply(341, 153);
    giq_option(6, 341, 154, bob6, 50);
    giq_option(6, 341, 155, bob7, 50);
    giq_option(6, 341, 156, bob8, 50);
    giq_option(6, 341, 157, bobend, 50);
end

procedure bobend
begin
end

procedure combat
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(247, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(247, 1);
        if (source_obj == dude_obj) then begin
            if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
                set_global_var(156, 1);
                set_global_var(157, 0);
            end
            if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
                set_global_var(157, 1);
                set_global_var(156, 0);
            end
            set_global_var(159, global_var(159) + 1);
            if ((global_var(159) % 2) == 0) then begin
                set_global_var(155, global_var(155) - 1);
            end
        end
    end
end

