procedure start;
procedure dead00;


procedure start
begin
    variable LVar0 := 0;
    if (script_action == 3) then begin
        script_overrides;
        call dead00();
    end
    else begin
        if (script_action == 21) then begin
            script_overrides;
            display_msg(message_str(83, 100));
        end
    end
end

procedure dead00
begin
    if (is_success(do_check(dude_obj, 4, 0))) then begin
        display_msg(message_str(83, 101));
    end
end

