procedure start;
procedure do_dialogue;
procedure timeforwhat;
procedure genericend;
procedure genericcbt;
procedure generic00;
procedure generic01;
procedure generic02;
procedure generic03;

variable prev_tile;
variable new_tile;
variable loopcount;
variable noevent;
variable rndx;
variable rndy;
variable rndz;
variable dist;
variable curtime;
variable prevtime;
variable hostile;
variable SET;
variable MUTANTS;
variable MAXLEASH := 9;
variable DAY;
variable initialized;


procedure start
begin
    if (not(initialized)) then begin
        if (local_var(0) == 0) then begin
            set_local_var(0, 1);
        end
        critter_add_trait(self_obj, 1, 6, 32);
        initialized := 1;
    end
    curtime := DAY;
    if (prevtime != curtime) then begin
        noevent := curtime;
        prevtime := curtime;
        animate_move_obj_to_tile(self_obj, local_var(0), 0);
    end
    if (script_action == 22) then begin
        call timeforwhat();
    end
    else begin
        if (script_action == 11) then begin
            call do_dialogue();
        end
        else begin
            if (script_action == 4) then begin
                hostile := 1;
            end
            else begin
                if (script_action == 12) then begin
                    if (hostile) then begin
                        hostile := 0;
                        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
                    end
                    else begin
                        loopcount := loopcount + 1;
                        if (loopcount > 40) then begin
                            loopcount := 0;
                            if (noevent == 0) then begin
                                noevent := 1;
                                rndx := 5 + random(1, 10);
                                add_timer_event(self_obj, game_ticks(rndx), 0);
                            end
                        end
                    end
                end
                else begin
                    if (script_action == 18) then begin
                        if (source_obj == dude_obj) then begin
                            if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
                                set_global_var(156, 1);
                                set_global_var(157, 0);
                            end
                            if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
                                set_global_var(157, 1);
                                set_global_var(156, 0);
                            end
                            set_global_var(160, global_var(160) + 1);
                            if ((global_var(160) % 6) == 0) then begin
                                set_global_var(155, global_var(155) + 1);
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    start_gdialog(84, self_obj, 4, -1, -1);
    gsay_start;
    if (hostile) then begin
        call generic01();
    end
    else begin
        call generic00();
    end
    gsay_end;
    end_dialogue;
end

procedure timeforwhat
begin
    noevent := curtime;
    rndy := random(1, 6);
    if (rndy > 1) then begin
        dist := 2;
    end
    if (rndy > 5) then begin
        dist := 3;
    end
    rndz := random(0, 5);
    prev_tile := tile_num(self_obj);
    new_tile := tile_num_in_direction(prev_tile, rndz, dist);
    if (tile_distance(local_var(0), new_tile) < MAXLEASH) then begin
        animate_move_obj_to_tile(self_obj, new_tile, 0);
    end
end

procedure genericend
begin
end

procedure genericcbt
begin
end

procedure generic00
begin
    rndx := random(1, 7);
    if (rndx == 1) then begin
        gsay_message(84, 100, 50);
    end
    if (rndx == 2) then begin
        gsay_message(84, 101, 50);
    end
    if (rndx == 3) then begin
        gsay_message(84, 102, 50);
    end
    if (rndx == 4) then begin
        gsay_message(84, 103, 50);
    end
    if (rndx == 5) then begin
        gsay_message(84, 104, 50);
    end
    if (rndx == 6) then begin
        call generic02();
    end
    if (rndx == 7) then begin
        call generic03();
    end
end

procedure generic01
begin
    rndx := random(1, 4);
    if (rndx == 1) then begin
        gsay_message(84, 105, 50);
    end
    if (rndx == 2) then begin
        gsay_message(84, 106, 50);
    end
    if (rndx == 3) then begin
        gsay_message(84, 107, 50);
    end
    if (rndx == 4) then begin
        gsay_message(84, 108, 50);
    end
end

procedure generic02
begin
    if (SET == 0) then begin
        rndx := random(1, 2);
        if (rndx == 1) then begin
            gsay_message(84, 109, 50);
        end
        if (rndx == 2) then begin
            gsay_message(84, 110, 50);
        end
    end
    else begin
        gsay_message(84, 111, 50);
    end
end

procedure generic03
begin
    if (MUTANTS == 0) then begin
        rndx := random(1, 2);
        if (rndx == 1) then begin
            gsay_message(84, 112, 50);
        end
        if (rndx == 2) then begin
            gsay_message(84, 113, 50);
        end
    end
    else begin
        gsay_message(84, 114, 50);
    end
end

