procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure timed_event_p_proc;
procedure talk_p_proc;
procedure show_true_name;
procedure show_false_name;
procedure Michelle00;
procedure Michelle01;
procedure Michelle02;
procedure Michelle03;
procedure Michelle04;
procedure Michelle05;
procedure Michelle06;
procedure Michelle07;
procedure Michelle08;
procedure Michelle09;
procedure Michelle10;
procedure Michelle11;
procedure Michelle12;
procedure Michelle13;
procedure Michelle14;
procedure Michelle15;
procedure Michelle16;
procedure Michelle17;
procedure MichelleCombat;
procedure MichelleEnd;

variable hostile;
variable initialized;


procedure start
begin
    if (not(initialized)) then begin
        critter_add_trait(self_obj, 1, 6, 47);
        critter_add_trait(self_obj, 1, 5, 27);
        initialized := 1;
    end
    else begin
        if (script_action == 12) then begin
            call critter_p_proc();
        end
        else begin
            if (script_action == 18) then begin
                call destroy_p_proc();
            end
            else begin
                if (script_action == 21) then begin
                    call look_at_p_proc();
                end
                else begin
                    if (script_action == 4) then begin
                        call pickup_p_proc();
                    end
                    else begin
                        if (script_action == 11) then begin
                            call talk_p_proc();
                        end
                        else begin
                            if (script_action == 22) then begin
                                call timed_event_p_proc();
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj) and (global_var(136) < 41)) then begin
        hostile := 1;
    end
    if (hostile) then begin
        hostile := 0;
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure destroy_p_proc
begin
    set_global_var(136, global_var(136) - 1);
    if (source_obj == dude_obj) then begin
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
            set_global_var(156, 1);
            set_global_var(157, 0);
        end
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
            set_global_var(157, 1);
            set_global_var(156, 0);
        end
        set_global_var(159, global_var(159) + 1);
        if ((global_var(159) % 2) == 0) then begin
            set_global_var(155, global_var(155) - 1);
        end
    end
end

procedure look_at_p_proc
begin
    if (((global_var(135) == 2) or get_critter_stat(dude_obj, 6)) > 6) then begin
        call show_true_name();
    end
    else begin
        if (get_critter_stat(dude_obj, 6) < 4) then begin
            call show_false_name();
        end
        else begin
            if (get_critter_stat(dude_obj, 4) < 5) then begin
                call show_false_name();
            end
            else begin
                if (random(0, 1)) then begin
                    call show_false_name();
                end
                else begin
                    call show_true_name();
                end
            end
        end
    end
end

procedure pickup_p_proc
begin
    hostile := 1;
end

procedure timed_event_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        hostile := 1;
    end
end

procedure talk_p_proc
begin
    start_gdialog(283, self_obj, 4, -1, -1);
    gsay_start;
    set_local_var(0, 1);
    if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
        call Michelle15();
    end
    else begin
        if (global_var(135) == 1) then begin
            call Michelle16();
        end
        else begin
            if (global_var(135) == 2) then begin
                call Michelle17();
            end
            else begin
                call Michelle00();
            end
        end
    end
    gsay_end;
    end_dialogue;
end

procedure show_true_name
begin
    script_overrides;
    if (local_var(0)) then begin
        display_msg(message_str(283, 100));
    end
    else begin
        display_msg(message_str(283, 103));
    end
end

procedure show_false_name
begin
    script_overrides;
    display_msg(message_str(283, random(104, 110)));
end

procedure Michelle00
begin
    gsay_reply(283, 111);
    giq_option(-3, 283, 112, Michelle01, 50);
    giq_option(4, 283, 113, Michelle02, 50);
    giq_option(5, 283, 114, Michelle09, 50);
    giq_option(4, 283, 115, MichelleCombat, 50);
end

procedure Michelle01
begin
    gsay_reply(283, 116);
    giq_option(-3, 283, 117, MichelleCombat, 50);
    giq_option(-3, 283, 118, MichelleEnd, 50);
end

procedure Michelle02
begin
    gsay_reply(283, 119);
    giq_option(4, 283, 120, Michelle03, 50);
    giq_option(5, 283, 121, Michelle04, 50);
    giq_option(5, 283, 122, Michelle08, 50);
    giq_option(4, 283, 123, MichelleCombat, 50);
end

procedure Michelle03
begin
    gsay_message(283, 124, 50);
    call MichelleCombat();
end

procedure Michelle04
begin
    gsay_reply(283, 125);
    giq_option(5, 283, 126, Michelle05, 50);
    giq_option(5, 283, 127, Michelle06, 50);
    giq_option(7, 283, 128, Michelle07, 50);
end

procedure Michelle05
begin
    gsay_reply(283, 129);
    giq_option(5, 283, 130, MichelleEnd, 50);
    giq_option(5, 283, 131, MichelleEnd, 50);
end

procedure Michelle06
begin
    gsay_message(283, 132, 50);
    call MichelleCombat();
end

procedure Michelle07
begin
    gsay_message(283, 133, 50);
    call MichelleCombat();
end

procedure Michelle08
begin
    gsay_message(283, 134, 50);
    call MichelleCombat();
end

procedure Michelle09
begin
    gsay_reply(283, 135);
    giq_option(5, 283, 136, Michelle10, 50);
    giq_option(5, 283, 137, Michelle11, 50);
    giq_option(5, 283, 138, Michelle04, 50);
    giq_option(5, 283, 139, Michelle12, 50);
    giq_option(5, 283, 140, MichelleCombat, 50);
end

procedure Michelle10
begin
    gsay_message(283, 141, 50);
    call MichelleCombat();
end

procedure Michelle11
begin
    gsay_message(283, message_str(283, 142) + " " + message_str(283, 143), 50);
    call MichelleCombat();
end

procedure Michelle12
begin
    gsay_reply(283, 144);
    giq_option(5, 283, 145, Michelle13, 50);
    giq_option(5, 283, 146, Michelle14, 50);
    giq_option(5, 283, 147, MichelleCombat, 50);
end

procedure Michelle13
begin
    gsay_message(283, 148, 50);
end

procedure Michelle14
begin
    gsay_message(283, 149, 50);
    call MichelleCombat();
end

procedure Michelle15
begin
    gsay_message(283, 150, 50);
    add_timer_event(self_obj, game_ticks(10), 1);
end

procedure Michelle16
begin
    gsay_message(283, 151, 50);
end

procedure Michelle17
begin
    gsay_message(283, 152, 50);
end

procedure MichelleCombat
begin
    hostile := 1;
end

procedure MichelleEnd
begin
end

