import variable Manhole_Pointer_Top;
import variable Use_Manhole_Top;
import variable Manhole_Pointer_Middle;
import variable Use_Manhole_Middle;
import variable Manhole_Pointer_Bottom;
import variable Use_Manhole_Bottom;

procedure start;


procedure start
begin
    if (script_action == 6) then begin
        script_overrides;
        add_timer_event(self_obj, 2, 1);
        Use_Manhole_Bottom := 1;
    end
    else begin
        if (script_action == 22) then begin
            move_to(dude_obj, 22698, 0);
        end
    end
end

