import variable Use_Manhole_Bottom;

procedure start;


procedure start
begin
    if (script_action == 6) then begin
        script_overrides;
        Use_Manhole_Bottom := 1;
        add_timer_event(self_obj, 7, 1);
    end
    else begin
        if (script_action == 22) then begin
            move_to(dude_obj, 26857, 1);
        end
    end
    if (source_obj == dude_obj) then begin
        anim(source_obj, 0, 0);
    end
end

