procedure start;
procedure do_dialogue;
procedure Wife01;
procedure Wife02;
procedure Wife03;
procedure Wife00n;
procedure WifeEnd;
procedure critter_p_proc;
procedure talk_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;
procedure damage_p_proc;

variable HOSTILE;
variable Only_Once := 1;


procedure start
begin
    if (Only_Once) then begin
        Only_Once := 0;
        critter_add_trait(self_obj, 1, 6, 2);
        critter_add_trait(self_obj, 1, 5, 6);
    end
    if (script_action == 12) then begin
        call critter_p_proc();
    end
    else begin
        if (script_action == 11) then begin
            call talk_p_proc();
        end
        else begin
            if (script_action == 4) then begin
                call pickup_p_proc();
            end
            else begin
                if (script_action == 18) then begin
                    call destroy_p_proc();
                end
                else begin
                    if (script_action == 14) then begin
                        call damage_p_proc();
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    if ((game_time_hour >= 1900) or (game_time_hour < 600)) then begin
        call Wife00n();
    end
    else begin
        start_gdialog(119, self_obj, 4, -1, -1);
        gsay_start;
        call Wife01();
        gsay_end;
        end_dialogue;
    end
end

procedure Wife01
begin
    gsay_reply(119, 100);
    giq_option(4, 119, 101, Wife02, 50);
    giq_option(4, 119, 107, WifeEnd, 50);
    giq_option(-3, 119, 102, Wife03, 50);
end

procedure Wife02
begin
    gsay_message(119, 103, 50);
end

procedure Wife03
begin
    gsay_message(119, 104, 50);
end

procedure Wife00n
begin
    float_msg(self_obj, message_str(119, 105), 8);
end

procedure WifeEnd
begin
end

procedure critter_p_proc
begin
    if (map_var(2) == 1) then begin
        set_local_var(0, local_var(0) + 1);
        set_map_var(2, 0);
        if (local_var(0) < 3) then begin
            float_msg(self_obj, message_str(129, 308), 2);
        end
        else begin
            HOSTILE := 1;
        end
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (global_var(246) == 1) then begin
            HOSTILE := 1;
        end
    end
    if (HOSTILE) then begin
        HOSTILE := 0;
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure talk_p_proc
begin
    call do_dialogue();
end

procedure pickup_p_proc
begin
    HOSTILE := 1;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(246, 1);
    end
    if (source_obj == dude_obj) then begin
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(159) > (2 * global_var(160))) or (global_var(156) == 1))) then begin
            set_global_var(156, 1);
            set_global_var(157, 0);
        end
        if (((global_var(160) + global_var(159)) >= 25) and ((global_var(160) > (3 * global_var(159))) or (global_var(157) == 1))) then begin
            set_global_var(157, 1);
            set_global_var(156, 0);
        end
        set_global_var(159, global_var(159) + 1);
        if ((global_var(159) % 2) == 0) then begin
            set_global_var(155, global_var(155) - 1);
        end
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(246, 1);
    end
end

