variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);

variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node998;
procedure Node999;
procedure Node999_float;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure combat_p_proc;

import variable Map_event;

variable after_combat_dialog;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj) and (obj_is_visible_flag(self_obj) == 1)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if ((obj_is_visible_flag(self_obj) == 1) and (after_combat_dialog == 1) and (obj_can_see_obj(self_obj, dude_obj) or (tile_distance(tile_num(self_obj), dude_tile) < 10)) and ((local_var(6) bwand 128) == 0)) then begin
        set_local_var(6, local_var(6) bwor 128);
        after_combat_dialog := 0;
        dialogue_system_enter;
    end
    if ((obj_is_visible_flag(self_obj) == 0) and (global_var(GVAR_AQE_QUEST_ELISA_1) == 3) and (dude_elevation == 1) and ((local_var(6) bwand 512) == 0)) then begin
        if (tile_in_tile_rect(16318, 16311, 17718, 17711, dude_tile) and (dude_elevation == 1) and ((local_var(6) bwand 512) == 0)) then begin
            add_timer_event(Map_event, game_ticks(0), 20);
            set_local_var(6, local_var(6) bwor 512);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
    end
end

procedure talk_p_proc
begin
    if (global_var(GVAR_AQE_QUEST_ELISA_2) == 3) then begin
        float_msg(self_obj, mstr(random(301, 305)), FLOAT_MSG_YELLOW);
    end
    else begin
        anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
        start_gdialog(116, self_obj, 4, -1, -1);
        gsay_start;
        if ((local_var(5) == 1) and not((local_var(6) bwand 64) == 0) and not((local_var(6) bwand 128) == 0)) then begin
            call Node1250();
        end
        else begin
            if (not((local_var(6) bwand 32) == 0)) then begin
                call Node1200();
            end
            else begin
                if (local_var(5) == 1) then begin
                    call Node1150();
                end
                else begin
                    call Node500();
                end
            end
        end
        gsay_end;
        end_dialogue;
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_TOWN_REP_ALBUQUERQUE, global_var(GVAR_TOWN_REP_ALBUQUERQUE) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 0);
        debug_msg("Player gains " + 0 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(4) == 1) then begin
        set_global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT, global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT) bwor 4);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_mstr(150);
    end
    else begin
        display_mstr(100);
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_mstr(250);
    end
    else begin
        display_mstr(200);
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 43);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_TOUGH_GUARD_NO_TALKING);
    if (not(is_loading_game)) then begin
        if (global_var(GVAR_AQE_QUEST_ELISA_2) == 2) then begin
            if (obj_is_visible_flag(self_obj) == 0) then begin
                set_obj_visibility(self_obj, 0);
            end
        end
        else begin
            if (global_var(GVAR_AQE_QUEST_ELISA_2) == 3) then begin
                destroy_object(self_obj);
            end
            else begin
                if (obj_is_visible_flag(self_obj) == 1) then begin
                    set_obj_visibility(self_obj, 1);
                end
            end
        end
    end
end

procedure Node998
begin
    set_local_var(4, 1);
    if ((local_var(6) bwand 256) == 0) then begin
        float_msg(self_obj, mstr(306), FLOAT_MSG_RED);
        set_local_var(6, local_var(6) bwor 256);
    end
end

procedure Node999
begin
    anim(self_obj, 1000, 3);
end

procedure Node999_float
begin
    float_msg(self_obj, mstr(300), FLOAT_MSG_YELLOW);
end

procedure Node500
begin
    Reply(500);
    giq_option(4, NAME, 501, Node600, NEUTRAL_REACTION);
    giq_option(-3, NAME, 502, Node550, NEUTRAL_REACTION);
end

procedure Node550
begin
    if (dude_gender == 0) then begin
        Reply(550);
    end
    else begin
        Reply(551);
    end
    giq_option(-3, NAME, 552, Node999, NEUTRAL_REACTION);
end

procedure Node600
begin
    Reply(600);
    set_local_var(5, 1);
    giq_option(4, NAME, 601, Node650, NEUTRAL_REACTION);
    giq_option(4, NAME, 602, Node750, NEUTRAL_REACTION);
end

procedure Node650
begin
    Reply(650);
    set_local_var(6, local_var(6) bwor 1);
    giq_option(4, NAME, 651, Node700, NEUTRAL_REACTION);
end

procedure Node700
begin
    Reply(700);
    if ((local_var(6) bwand 2) == 0) then begin
        giq_option(4, NAME, 701, Node750, NEUTRAL_REACTION);
    end
    if (((local_var(6) bwand 4) == 0) and not((local_var(6) bwand 2) == 0)) then begin
        giq_option(5, NAME, 702, Node800, NEUTRAL_REACTION);
    end
    if ((dude_strength > 8) or (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_bruiser) and (dude_strength > 5))) then begin
        giq_option(4, NAME, 703, Node900, NEUTRAL_REACTION);
    end
    else begin
        if (((local_var(6) bwand 16) == 0) and not((local_var(6) bwand 2) == 0)) then begin
            giq_option(4, NAME, 703, Node950, NEUTRAL_REACTION);
        end
    end
    if (not((local_var(6) bwand 2) == 0)) then begin
        giq_option(4, NAME, 704, Node1050, NEUTRAL_REACTION);
    end
    if ((dude_skill(SKILL_SPEECH) > 70) and not((local_var(6) bwand 8) == 0)) then begin
        giq_option(4, NAME, 705, Node900, NEUTRAL_REACTION);
    end
    if (not((local_var(6) bwand 2) == 0)) then begin
        giq_option(4, NAME, 706, Node1000, NEUTRAL_REACTION);
    end
end

procedure Node750
begin
    Reply(750);
    set_local_var(6, local_var(6) bwor 2);
    if ((local_var(6) bwand 1) == 0) then begin
        giq_option(4, NAME, 751, Node650, NEUTRAL_REACTION);
    end
    if (((local_var(6) bwand 4) == 0) and not((local_var(6) bwand 2) == 0)) then begin
        giq_option(5, NAME, 752, Node800, NEUTRAL_REACTION);
    end
    if ((dude_strength > 8) or (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_bruiser) and (dude_strength > 5))) then begin
        giq_option(4, NAME, 753, Node900, NEUTRAL_REACTION);
    end
    else begin
        if (((local_var(6) bwand 16) == 0) and not((local_var(6) bwand 2) == 0)) then begin
            giq_option(4, NAME, 753, Node950, NEUTRAL_REACTION);
        end
    end
    giq_option(4, NAME, 754, Node1050, NEUTRAL_REACTION);
    giq_option(4, NAME, 755, Node1000, NEUTRAL_REACTION);
end

procedure Node800
begin
    Reply(800);
    set_local_var(6, local_var(6) bwor 4);
    giq_option(5, NAME, 801, Node850, NEUTRAL_REACTION);
end

procedure Node850
begin
    if (dude_gender == 0) then begin
        Reply(850);
    end
    else begin
        Reply(851);
    end
    set_local_var(6, local_var(6) bwor 8);
    if (dude_skill(SKILL_SPEECH) > 70) then begin
        giq_option(4, NAME, 852, Node900, NEUTRAL_REACTION);
    end
    if ((local_var(6) bwand 1) == 0) then begin
        giq_option(4, NAME, 853, Node650, NEUTRAL_REACTION);
    end
    if ((dude_strength > 8) or (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_bruiser) and (dude_strength > 5))) then begin
        giq_option(4, NAME, 854, Node900, NEUTRAL_REACTION);
    end
    else begin
        if (((local_var(6) bwand 16) == 0) and not((local_var(6) bwand 2) == 0)) then begin
            giq_option(4, NAME, 854, Node950, NEUTRAL_REACTION);
        end
    end
    giq_option(4, NAME, 855, Node1050, NEUTRAL_REACTION);
    giq_option(4, NAME, 856, Node1000, NEUTRAL_REACTION);
end

procedure Node900
begin
    Reply(900);
    set_global_var(GVAR_AQE_QUEST_ELISA_2, 3);
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        set_global_var(GVAR_PTR_LYSTRA_REACTIONS_2, global_var(GVAR_PTR_LYSTRA_REACTIONS_2) bwor 32);
    end
    giq_option(4, NAME, 901, Node999_float, NEUTRAL_REACTION);
end

procedure Node950
begin
    Reply(950);
    set_local_var(6, local_var(6) bwor 16);
    if ((local_var(6) bwand 1) == 0) then begin
        giq_option(4, NAME, 951, Node650, NEUTRAL_REACTION);
    end
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(5, NAME, 952, Node800, NEUTRAL_REACTION);
    end
    if ((dude_skill(SKILL_SPEECH) > 70) and not((local_var(6) bwand 8) == 0)) then begin
        giq_option(4, NAME, 954, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 953, Node1050, NEUTRAL_REACTION);
    giq_option(4, NAME, 955, Node1000, NEUTRAL_REACTION);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 956, Node998, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 957, Node998, NEUTRAL_REACTION);
    end
end

procedure Node1000
begin
    if (dude_gender == 0) then begin
        Reply(1000);
    end
    else begin
        Reply(1001);
    end
    set_local_var(6, local_var(6) bwor 64);
    if ((local_var(6) bwand 1) == 0) then begin
        giq_option(4, NAME, 1002, Node650, NEUTRAL_REACTION);
    end
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(5, NAME, 1003, Node800, NEUTRAL_REACTION);
    end
    if ((dude_strength > 8) or (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_bruiser) and (dude_strength > 5))) then begin
        giq_option(4, NAME, 1004, Node900, NEUTRAL_REACTION);
    end
    else begin
        if (((local_var(6) bwand 16) == 0) and not((local_var(6) bwand 2) == 0)) then begin
            giq_option(4, NAME, 1004, Node950, NEUTRAL_REACTION);
        end
    end
    if ((dude_skill(SKILL_SPEECH) > 70) and not((local_var(6) bwand 8) == 0)) then begin
        giq_option(4, NAME, 1006, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1005, Node1050, NEUTRAL_REACTION);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1007, Node999, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 1008, Node998, NEUTRAL_REACTION);
    end
end

procedure Node1050
begin
    if (dude_gender == 0) then begin
        Reply(1050);
    end
    else begin
        Reply(1051);
    end
    set_local_var(6, local_var(6) bwor 32);
    if (item_caps_total(dude_obj) >= 400) then begin
        giq_option(4, NAME, 1052, Node1100, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1053, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 1054, Node998, NEUTRAL_REACTION);
end

procedure Node1100
begin
    Reply(1100);
    set_global_var(GVAR_AQE_QUEST_ELISA_2, 3);
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        set_global_var(GVAR_PTR_LYSTRA_REACTIONS_2, global_var(GVAR_PTR_LYSTRA_REACTIONS_2) bwor 32);
    end
    item_caps_adjust(dude_obj, -400);
    item_caps_adjust(self_obj, 400);
    giq_option(4, NAME, 1101, Node999_float, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1102, Node999_float, NEUTRAL_REACTION);
end

procedure Node1150
begin
    if (dude_gender == 0) then begin
        Reply(1150);
    end
    else begin
        Reply(1151);
    end
    if ((local_var(6) bwand 1) == 0) then begin
        giq_option(4, NAME, 1152, Node650, NEUTRAL_REACTION);
    end
    if ((local_var(6) bwand 4) == 0) then begin
        giq_option(5, NAME, 1153, Node800, NEUTRAL_REACTION);
    end
    if ((dude_strength > 8) or (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_bruiser) and (dude_strength > 5))) then begin
        giq_option(4, NAME, 1154, Node900, NEUTRAL_REACTION);
    end
    else begin
        if (((local_var(6) bwand 16) == 0) and not((local_var(6) bwand 2) == 0)) then begin
            giq_option(4, NAME, 1154, Node950, NEUTRAL_REACTION);
        end
    end
    if ((dude_skill(SKILL_SPEECH) > 70) and not((local_var(6) bwand 8) == 0)) then begin
        giq_option(4, NAME, 1156, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1155, Node1050, NEUTRAL_REACTION);
    giq_option(4, NAME, 1157, Node1000, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1158, Node999, NEUTRAL_REACTION);
end

procedure Node1200
begin
    Reply(1200);
    if (item_caps_total(dude_obj) >= 400) then begin
        giq_option(4, NAME, 1201, Node1100, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1202, Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1203, Node999, NEUTRAL_REACTION);
end

procedure Node1250
begin
    Reply(1250);
    giq_option(4, NAME, 1251, Node900, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1252, Node900, NEUTRAL_REACTION);
    giq_option(4, NAME, 1253, Node998, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1254, Node998, NEUTRAL_REACTION);
end

procedure combat_p_proc
begin
    if ((get_critter_stat(self_obj, STAT_current_hp) <= 20) and (local_var(4) == 1) and (local_var(5) == 1) and ((local_var(6) bwand 128) == 0) and not((local_var(6) bwand 64) == 0)) then begin
        set_local_var(4, 0);
        if (obj_can_see_obj(self_obj, dude_obj) or (tile_distance(tile_num(self_obj), dude_tile) < 10)) then begin
            after_combat_dialog := 1;
        end
        terminate_combat;
    end
end
