variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure combat_p_proc;
procedure timed_event_p_proc;

import variable Map_event;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((obj_is_visible_flag(self_obj) == 1) and (dude_elevation == 0) and (local_var(4) != 1) and (global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 2) and tile_in_tile_rect(14735, 14717, 17935, 17917, dude_tile)) then begin
        explosion(15528, 0, 100);
        critter_heal(self_obj, -15);
        add_timer_event(Map_event, game_ticks(0), 7);
        set_local_var(6, game_time);
        set_local_var(4, 1);
    end
    if ((obj_is_visible_flag(self_obj) == 1) and (local_var(5) != 1) and (dude_elevation == 1) and (tile_distance(tile_num(self_obj), dude_tile) < 7) and not(combat_is_initialized)) then begin
        anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
        float_msg(self_obj, mstr(400 + (dude_gender == 1)), FLOAT_MSG_RED);
        set_local_var(5, 1);
        set_global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT, 3);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if ((obj_is_visible_flag(self_obj) == 1) and (local_var(5) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if ((global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) >= 2) and (((game_time - global_var(GVAR_AQE_BENICIO_TIME_LIMIT)) > (60 * (60 * 10) * 4)) or (((game_time - local_var(6)) > (60 * 10 * 60)) and (local_var(4) == 1)))) then begin
        set_global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT, global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT) bwor 2);
        destroy_object(self_obj);
    end
end

procedure pickup_p_proc
begin
end

procedure talk_p_proc
begin
end

procedure destroy_p_proc
begin
    if ((global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 2) and (dude_elevation == 1)) then begin
        set_global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT, 3);
    end
    if ((global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 3) and ((game_time - global_var(GVAR_AQE_BENICIO_TIME_LIMIT)) <= (60 * (60 * 10) * 4)) and ((game_time - local_var(6)) <= (60 * 10 * 60))) then begin
        set_global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT, global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT) bwor 1);
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0) and (global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 3) and ((global_var(GVAR_AQE_ALBUQ_EMPEROR_EVENTS_NEXT) bwand 1) != 0)) then begin
        if (combat_is_initialized == 1) then begin
            terminate_combat;
        end
        add_timer_event(party_member_obj(16777814), 1, 27);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(200);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if ((global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 2) and (dude_elevation == 1)) then begin
        set_global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT, 3);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 282);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_IMPERIAL_SOLDIER_NO_TALKING);
    if (global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 1) then begin
        destroy_object(self_obj);
    end
    if (not(is_loading_game)) then begin
        if (global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 2) then begin
            if (obj_is_visible_flag(self_obj) == 0) then begin
                set_obj_visibility(self_obj, 0);
            end
            add_timer_event(self_obj, game_ticks(random(2, 4)), 1);
        end
        else begin
            if (obj_is_visible_flag(self_obj) == 1) then begin
                set_obj_visibility(self_obj, 1);
            end
        end
    end
end

procedure map_exit_p_proc
begin
    float_msg_clear(self_obj);
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        if ((obj_is_visible_flag(self_obj) == 1) and (local_var(5) != 1) and (dude_elevation == 1)) then begin
            float_msg(self_obj, mstr(400 + (dude_gender == 1)), FLOAT_MSG_RED);
            set_local_var(5, 1);
            set_global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT, 3);
        end
        if ((obj_is_visible_flag(self_obj) == 1) and (dude_elevation == 0) and (local_var(4) != 1) and (global_var(GVAR_AQE_QUEST_ANONYM_2_FIGHT) == 2) and tile_in_tile_rect(14735, 14717, 17935, 17917, dude_tile)) then begin
            critter_heal(self_obj, -15);
            explosion(15528, 0, 100);
            add_timer_event(Map_event, game_ticks(0), 7);
            set_local_var(6, game_time);
            set_local_var(4, 1);
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if ((dude_elevation == 1) and (obj_is_visible_flag(self_obj) == 1) and not(combat_is_initialized)) then begin
            float_msg(self_obj, mstr(random(300, 304)), FLOAT_MSG_YELLOW);
        end
        add_timer_event(self_obj, game_ticks(random(3, 5)), 1);
    end
end
