variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure combat_p_proc;
procedure push_p_proc;

import variable Map_event;
import variable Falber_obj;
import variable Doktor1_obj;
import variable Doktor2_obj;
import variable Doktor3_obj;
import variable Doktor4_obj;
import variable Doktor5_obj;
import variable EmperorSoldier1_obj;
import variable EmperorSoldier2_obj;
import variable EmperorSoldier3_obj;
import variable EmperorSoldier4_obj;
import variable EmperorSoldier5_obj;

variable probability;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure map_enter_p_proc
begin
    if (global_var(GVAR_AQE_ENEMY_EMPEROR) == 1) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 282);
    end
    else begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
    end
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_IMPERIAL_SOLDIER_NO_TALKING);
    if (local_var(4) == 1) then begin
        EmperorSoldier1_obj := self_obj;
    end
    if (local_var(4) == 2) then begin
        EmperorSoldier2_obj := self_obj;
    end
    if (local_var(4) == 3) then begin
        EmperorSoldier3_obj := self_obj;
    end
    if (local_var(4) == 4) then begin
        EmperorSoldier4_obj := self_obj;
    end
    if (local_var(4) == 5) then begin
        EmperorSoldier5_obj := self_obj;
    end
end

procedure map_exit_p_proc
begin
    destroy_object(self_obj);
end

procedure critter_p_proc
begin
    if ((global_var(GVAR_AQE_ENEMY_EMPEROR) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if ((map_var(0) bwand 256) != 0) then begin
        destroy_object(self_obj);
    end
    if ((global_var(GVAR_AQ_ENEMY_HOSPITAL) == 1) and (global_var(GVAR_AQ_QUEST_TRIBE_HELP_REVEGE) != 4)) then begin
        if (tile_distance_objs(self_obj, dude_obj) > 10) then begin
            if (tile_distance_objs(self_obj, dude_obj) > (10 * 2)) then begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 5), 1);
            end
            else begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 5), 0);
            end
        end
    end
    if (local_var(5) == 0) then begin
        set_local_var(5, tile_num(self_obj));
        if (local_var(5) == 29098) then begin
            set_local_var(4, 1);
        end
        if (local_var(5) == 29701) then begin
            set_local_var(4, 2);
        end
        if (local_var(5) == 29102) then begin
            set_local_var(4, 3);
        end
        if (local_var(5) == 29904) then begin
            set_local_var(4, 4);
        end
        if (local_var(5) == 30100) then begin
            set_local_var(4, 5);
        end
        call map_enter_p_proc();
    end
    if ((global_var(GVAR_AQ_QUEST_TRIBE_HELP_REVEGE) == 4) and not(combat_is_initialized) and not((map_var(0) bwand 128) != 0)) then begin
        set_map_var(0, map_var(0) bwor 128);
        add_timer_event(Map_event, game_ticks(0), 3);
    end
    if ((global_var(GVAR_AQ_ENEMY_HOSPITAL) == 1) and (global_var(GVAR_AQ_QUEST_TRIBE_HELP_REVEGE) == 3)) then begin
        if ((Doktor1_obj != -1) and obj_can_see_obj(self_obj, Doktor1_obj)) then begin
            attack(Doktor1_obj);
        end
        if ((Doktor2_obj != -1) and obj_can_see_obj(self_obj, Doktor2_obj)) then begin
            attack(Doktor2_obj);
        end
        if ((Doktor3_obj != -1) and obj_can_see_obj(self_obj, Doktor3_obj)) then begin
            attack(Doktor3_obj);
        end
        if ((Doktor4_obj != -1) and obj_can_see_obj(self_obj, Doktor4_obj)) then begin
            attack(Doktor4_obj);
        end
        if ((Doktor5_obj != -1) and obj_can_see_obj(self_obj, Doktor5_obj)) then begin
            attack(Doktor5_obj);
        end
        if ((Falber_obj != -1) and obj_can_see_obj(self_obj, Falber_obj)) then begin
            attack(Falber_obj);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_AQE_ENEMY_EMPEROR, 1);
    end
end

procedure talk_p_proc
begin
end

procedure destroy_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(200);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_FRIENDLY_FIRE, global_var(GVAR_FRIENDLY_FIRE) + 1);
        if ((global_var(GVAR_FRIENDLY_FIRE) > 3) and (global_var(GVAR_AQE_ENEMY_EMPEROR) == 0)) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 282);
            set_global_var(GVAR_AQE_ENEMY_EMPEROR, 1);
        end
    end
end

procedure combat_p_proc
begin
    if (global_var(GVAR_AQE_ENEMY_EMPEROR) == 1) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 282);
    end
end

procedure push_p_proc
begin
end
