variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure Create_Fight_From_Primitives;
procedure Create_Fight_From_Hospital;

export variable Map_event;
export variable Hunters;
export variable Givers;
export variable Stunned;
export variable lovec1_obj;
export variable lovec2_obj;
export variable lovec3_obj;

variable sequence;
variable primitiv1;
variable primitiv2;
variable primitiv3;
variable primitiv4;
variable primitiv5;
variable primitiv6;
variable zoldak1;
variable zoldak2;
variable zoldak3;
variable zoldak4;
variable zoldak5;
variable zoldak6;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Map_event := self_obj;
end

procedure map_enter_p_proc
begin
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 40);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(100 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 40);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(100 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 40);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 40);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
    if (not(is_loading_game)) then begin
        if (map_first_run) then begin
            wm_area_set_pos(28, random(520, 580), random(680, 750));
            game_time_advance(8 * (60 * (60 * 10)));
            if (global_var(GVAR_AQ_QUEST_TRIBE_HUNTINGS) == 7) then begin
                call Create_Fight_From_Primitives();
                move_to(dude_obj, 20679, 0);
                anim(dude_obj, 1000, 3);
                if (party_member_obj(16777729) != 0) then begin
                    if (party_member_obj(16777729) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777729))) then begin
                            critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                    if (party_member_obj(16777779) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777779))) then begin
                            critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                    if (party_member_obj(16777811) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777811))) then begin
                            critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777812) != 0) then begin
                    if (party_member_obj(16777812) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777812))) then begin
                            critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                    if (party_member_obj(16777814) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777814))) then begin
                            critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777748) != 0) then begin
                    if (party_member_obj(16777748) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777748))) then begin
                            critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778017) != 0) then begin
                    if (party_member_obj(16778017) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778017))) then begin
                            critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778016) != 0) then begin
                    if (party_member_obj(16778016) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778016))) then begin
                            critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778049) != 0) then begin
                    if (party_member_obj(16778049) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778049))) then begin
                            critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778050) != 0) then begin
                    if (party_member_obj(16778050) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778050))) then begin
                            critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778051) != 0) then begin
                    if (party_member_obj(16778051) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778051))) then begin
                            critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777293) != 0) then begin
                    if (party_member_obj(16777293) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777293))) then begin
                            critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777729) != 0) then begin
                    anim(party_member_obj(16777729), 1000, 3);
                end
                if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                    anim(party_member_obj(16777779), 1000, 3);
                end
                if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                    anim(party_member_obj(16777811), 1000, 3);
                end
                if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                    anim(party_member_obj(16777814), 1000, 3);
                end
                if (party_member_obj(16778017) != 0) then begin
                    anim(party_member_obj(16778017), 1000, 3);
                end
                if (party_member_obj(16778016) != 0) then begin
                    anim(party_member_obj(16778016), 1000, 3);
                end
                if (party_member_obj(16778049) != 0) then begin
                    anim(party_member_obj(16778049), 1000, 3);
                end
                if (party_member_obj(16778050) != 0) then begin
                    anim(party_member_obj(16778050), 1000, 3);
                end
                if (party_member_obj(16778051) != 0) then begin
                    anim(party_member_obj(16778051), 1000, 3);
                end
                if (party_member_obj(16777812) != 0) then begin
                    anim(party_member_obj(16777812), 1000, 3);
                end
                add_timer_event(self_obj, game_ticks(0), 2);
                script_overrides;
                display_mstr(101);
            end
            else begin
                set_global_var(GVAR_AQ_HUNTINGS_RESULTS, 6);
                set_global_var(GVAR_AQ_HOSPITAL_GIVERS_STATUS, 0);
                call Create_Fight_From_Hospital();
                move_to(dude_obj, 17305, 0);
                anim(dude_obj, 1000, 1);
                if (party_member_obj(16777729) != 0) then begin
                    if (party_member_obj(16777729) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777729))) then begin
                            critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                    if (party_member_obj(16777779) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777779))) then begin
                            critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                    if (party_member_obj(16777811) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777811))) then begin
                            critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777812) != 0) then begin
                    if (party_member_obj(16777812) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777812))) then begin
                            critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                    if (party_member_obj(16777814) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777814))) then begin
                            critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777748) != 0) then begin
                    if (party_member_obj(16777748) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777748))) then begin
                            critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778017) != 0) then begin
                    if (party_member_obj(16778017) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778017))) then begin
                            critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778016) != 0) then begin
                    if (party_member_obj(16778016) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778016))) then begin
                            critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778049) != 0) then begin
                    if (party_member_obj(16778049) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778049))) then begin
                            critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778050) != 0) then begin
                    if (party_member_obj(16778050) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778050))) then begin
                            critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16778051) != 0) then begin
                    if (party_member_obj(16778051) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16778051))) then begin
                            critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777293) != 0) then begin
                    if (party_member_obj(16777293) != 0) then begin
                        if (obj_is_visible_flag(party_member_obj(16777293))) then begin
                            critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 4), dude_elevation);
                        end
                    end
                end
                if (party_member_obj(16777729) != 0) then begin
                    anim(party_member_obj(16777729), 1000, 1);
                end
                if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                    anim(party_member_obj(16777779), 1000, 1);
                end
                if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                    anim(party_member_obj(16777811), 1000, 1);
                end
                if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                    anim(party_member_obj(16777814), 1000, 1);
                end
                if (party_member_obj(16778017) != 0) then begin
                    anim(party_member_obj(16778017), 1000, 1);
                end
                if (party_member_obj(16778016) != 0) then begin
                    anim(party_member_obj(16778016), 1000, 1);
                end
                if (party_member_obj(16778049) != 0) then begin
                    anim(party_member_obj(16778049), 1000, 1);
                end
                if (party_member_obj(16778050) != 0) then begin
                    anim(party_member_obj(16778050), 1000, 1);
                end
                if (party_member_obj(16778051) != 0) then begin
                    anim(party_member_obj(16778051), 1000, 1);
                end
                if (party_member_obj(16777812) != 0) then begin
                    anim(party_member_obj(16777812), 1000, 1);
                end
                if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND)) == 601) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND)) == 601)) then begin
                end
                else begin
                    if (obj_is_carrying_obj_pid(dude_obj, 601)) then begin
                        wield_obj_critter(dude_obj, obj_carrying_pid_obj(dude_obj, 601));
                    end
                end
                add_timer_event(self_obj, game_ticks(0), 1);
                script_overrides;
                display_mstr(100);
            end
        end
    end
end

procedure map_update_p_proc
begin
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 40);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(100 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 40);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(100 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 40);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 40);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(100 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
end

procedure map_exit_p_proc
begin
    if (global_var(GVAR_AQ_QUEST_HOSPITAL_HUNTINGS) == 7) then begin
        if ((global_var(GVAR_AQ_HOSPITAL_GIVERS_STATUS) < 6) and (CUR_MAP_ALB_NEM1)) then begin
            set_global_var(GVAR_AQE_DIRECTIONS_SETUP, global_var(GVAR_AQE_DIRECTIONS_SETUP) bwor 32768);
        end
        if ((global_var(GVAR_AQ_HOSPITAL_GIVERS_STATUS) < 14) and (CUR_MAP_ALB_NEM2)) then begin
            set_global_var(GVAR_AQE_DIRECTIONS_SETUP, global_var(GVAR_AQE_DIRECTIONS_SETUP) bwor 32768);
        end
        if ((global_var(GVAR_AQ_HOSPITAL_GIVERS_STATUS) < 16) and (CUR_MAP_ALB_NEM3)) then begin
            set_global_var(GVAR_AQE_DIRECTIONS_SETUP, global_var(GVAR_AQE_DIRECTIONS_SETUP) bwor 32768);
        end
        if ((global_var(GVAR_AQ_HOSPITAL_GIVERS_STATUS) < 5) and (CUR_MAP_ALB_NEM4)) then begin
            set_global_var(GVAR_AQE_DIRECTIONS_SETUP, global_var(GVAR_AQE_DIRECTIONS_SETUP) bwor 32768);
        end
    end
    if (global_var(GVAR_AQ_QUEST_TRIBE_HUNTINGS) == 7) then begin
        set_global_var(GVAR_AQ_QUEST_TRIBE_HUNTINGS, 8);
    end
    if ((global_var(GVAR_AQ_QUEST_HOSPITAL_HUNTINGS) == 7) and (global_var(GVAR_AQ_HUNTINGS_RESULTS) > 0)) then begin
        set_global_var(GVAR_AQ_QUEST_HOSPITAL_HUNTINGS, 8);
    end
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 16));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 32));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 64));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 128));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 256));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 512));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 4194304));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 8388608));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 16777216));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 1));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 2));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 4));
    set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwand (-1 - 8));
    set_global_var(GVAR_FRIENDLY_FIRE, 0);
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (fixed_param == 1) then begin
            sequence := sequence + 1;
        end
        if (sequence == 1) then begin
            tile_set_center(16900);
            game_ui_disable;
            add_timer_event(self_obj, game_ticks(1), 1);
        end
        if (sequence == 2) then begin
            reg_anim_func(2, primitiv1);
            reg_anim_func(2, primitiv2);
            reg_anim_func(2, primitiv3);
            reg_anim_func(2, primitiv4);
            reg_anim_func(2, primitiv5);
            reg_anim_func(2, primitiv6);
            animate_move_obj_to_tile(primitiv1, 17700, 0);
            animate_move_obj_to_tile(primitiv2, 17697, 0);
            animate_move_obj_to_tile(primitiv3, 17700, 0);
            animate_move_obj_to_tile(primitiv4, 17697, 0);
            animate_move_obj_to_tile(primitiv5, 17700, 0);
            animate_move_obj_to_tile(primitiv6, 17697, 0);
            add_timer_event(self_obj, game_ticks(2), 1);
        end
        if (sequence == 3) then begin
            game_ui_enable;
            set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwor 1);
            add_timer_event(self_obj, 5, 1);
        end
        if ((sequence == 4) and not(combat_is_initialized)) then begin
            if (not(combat_is_initialized)) then begin
                attack_setup(zoldak1, primitiv1);
            end
        end
    end
    if (fixed_param == 2) then begin
        if (fixed_param == 2) then begin
            sequence := sequence + 1;
        end
        if (sequence == 1) then begin
            tile_set_center(21085);
            game_ui_disable;
            add_timer_event(self_obj, game_ticks(1), 2);
        end
        if (sequence == 2) then begin
            reg_anim_func(2, primitiv1);
            reg_anim_func(2, primitiv2);
            reg_anim_func(2, primitiv3);
            animate_move_obj_to_tile(primitiv1, 21690, 0);
            animate_move_obj_to_tile(primitiv2, 22492, 0);
            animate_move_obj_to_tile(primitiv3, 22292, 0);
            animate_move_obj_to_tile(dude_obj, 22093, 0);
            add_timer_event(self_obj, game_ticks(2), 2);
        end
        if (sequence == 3) then begin
            game_ui_enable;
            set_global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS, global_var(GVAR_AQ_HOSPITAL_ATTACKERS_STATUS) bwor 1);
        end
    end
end

procedure Create_Fight_From_Primitives
begin
    primitiv1 := create_object_sid(16777917, 20477, 0, SCRIPT_ADIVLV);
    primitiv2 := create_object_sid(16777917, 21077, 0, SCRIPT_ADIVLV);
    primitiv3 := create_object_sid(16777917, 20675, 0, SCRIPT_ADIVLV);
    zoldak1 := create_object_sid(16777928, 19683, 0, SCRIPT_ANEMNUNT);
    zoldak2 := create_object_sid(16777928, 19485, 0, SCRIPT_ANEMNUNT);
    zoldak3 := create_object_sid(16777929, 18883, 0, SCRIPT_ANEMNUNT);
    zoldak4 := create_object_sid(16777928, 18283, 0, SCRIPT_ANEMNUNT);
    zoldak5 := create_object_sid(16777928, 18685, 0, SCRIPT_ANEMNUNT);
    zoldak6 := create_object_sid(16777929, 18285, 0, SCRIPT_ANEMNUNT);
    anim(zoldak1, 1000, 2);
    anim(zoldak2, 1000, 2);
    anim(zoldak3, 1000, 2);
    anim(zoldak4, 1000, 2);
    anim(zoldak5, 1000, 2);
    anim(zoldak6, 1000, 2);
    anim(primitiv1, 1000, 3);
    anim(primitiv2, 1000, 3);
    anim(primitiv3, 1000, 3);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak1, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak2, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak3, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak4, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak5, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak6, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak1, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak2, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak3, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak4, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak5, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak6, restock_obj, 1);
    wield_obj_critter(zoldak1, obj_carrying_pid_obj(zoldak1, 601));
    wield_obj_critter(zoldak2, obj_carrying_pid_obj(zoldak2, 601));
    wield_obj_critter(zoldak3, obj_carrying_pid_obj(zoldak3, 601));
    wield_obj_critter(zoldak4, obj_carrying_pid_obj(zoldak4, 601));
    wield_obj_critter(zoldak5, obj_carrying_pid_obj(zoldak5, 601));
    wield_obj_critter(zoldak6, obj_carrying_pid_obj(zoldak6, 601));
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv1, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv2, restock_obj, 1);
    restock_obj := create_object(565, 0, 0);
    add_mult_objs_to_inven(primitiv2, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv3, restock_obj, 1);
    wield_obj_critter(primitiv1, obj_carrying_pid_obj(primitiv1, 280));
    wield_obj_critter(primitiv2, obj_carrying_pid_obj(primitiv2, 280));
    wield_obj_critter(primitiv3, obj_carrying_pid_obj(primitiv3, 280));
end

procedure Create_Fight_From_Hospital
begin
    primitiv1 := create_object_sid(16777917, 16300, 0, SCRIPT_ANEMNUNT);
    primitiv2 := create_object_sid(16777917, 15498, 0, SCRIPT_ANEMNUNT);
    primitiv3 := create_object_sid(16777917, 14698, 0, SCRIPT_ANEMNUNT);
    primitiv4 := create_object_sid(16777917, 14895, 0, SCRIPT_ANEMNUNT);
    primitiv5 := create_object_sid(16777917, 15501, 0, SCRIPT_ANEMNUNT);
    primitiv6 := create_object_sid(16777917, 16297, 0, SCRIPT_ANEMNUNT);
    zoldak1 := create_object_sid(16777928, 16908, 0, SCRIPT_ASBERLOV);
    zoldak2 := create_object_sid(16777928, 16508, 0, SCRIPT_ASBERLOV);
    zoldak3 := create_object_sid(16777929, 16906, 0, SCRIPT_ASBERLOV);
    anim(zoldak1, 1000, 1);
    anim(zoldak2, 1000, 1);
    anim(zoldak3, 1000, 1);
    anim(primitiv1, 1000, 2);
    anim(primitiv2, 1000, 2);
    anim(primitiv3, 1000, 2);
    anim(primitiv4, 1000, 2);
    anim(primitiv5, 1000, 2);
    anim(primitiv6, 1000, 2);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak1, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak2, restock_obj, 1);
    restock_obj := create_object(601, 0, 0);
    add_mult_objs_to_inven(zoldak3, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak1, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak2, restock_obj, 1);
    restock_obj := create_object(40, 0, 0);
    add_mult_objs_to_inven(zoldak3, restock_obj, 1);
    restock_obj := create_object(38, 0, 0);
    add_mult_objs_to_inven(zoldak1, restock_obj, 1);
    restock_obj := create_object(38, 0, 0);
    add_mult_objs_to_inven(zoldak2, restock_obj, 1);
    restock_obj := create_object(38, 0, 0);
    add_mult_objs_to_inven(zoldak3, restock_obj, 1);
    wield_obj_critter(zoldak1, obj_carrying_pid_obj(zoldak1, 601));
    wield_obj_critter(zoldak2, obj_carrying_pid_obj(zoldak2, 601));
    wield_obj_critter(zoldak3, obj_carrying_pid_obj(zoldak3, 601));
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv1, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv2, restock_obj, 1);
    restock_obj := create_object(565, 0, 0);
    add_mult_objs_to_inven(primitiv2, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv3, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv4, restock_obj, 1);
    restock_obj := create_object(565, 0, 0);
    add_mult_objs_to_inven(primitiv4, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv5, restock_obj, 1);
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(primitiv6, restock_obj, 1);
    wield_obj_critter(primitiv1, obj_carrying_pid_obj(primitiv1, 280));
    wield_obj_critter(primitiv2, obj_carrying_pid_obj(primitiv2, 280));
    wield_obj_critter(primitiv3, obj_carrying_pid_obj(primitiv3, 280));
    wield_obj_critter(primitiv4, obj_carrying_pid_obj(primitiv4, 280));
    wield_obj_critter(primitiv5, obj_carrying_pid_obj(primitiv5, 280));
    wield_obj_critter(primitiv6, obj_carrying_pid_obj(primitiv6, 280));
end
