variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure Generate_publikum;
procedure Generate_BIG_Rocks;

export variable Map_event;
export variable Guardian_obj;
export variable V16door_obj;
export variable MH_elevator;
export variable ElevatorGuardian_obj;
export variable Sebastian_obj;
export variable speech_listener1;
export variable speech_listener2;
export variable speech_listener3;
export variable speech_listener4;
export variable speech_listener5;
export variable speech_listener6;
export variable speech_listener7;
export variable speech_listener8;
export variable hunter_guard1;
export variable hunter_guard2;
export variable locker_guard1;
export variable locker_guard2;
export variable coridor_guard1;
export variable coridor_guard2;
export variable alien1_obj;
export variable alien2_obj;
export variable alien3_obj;
export variable alien4_obj;
export variable alien5_obj;
export variable alien6_obj;
export variable alien7_obj;

variable removable_wall;
variable sequence;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Map_event := self_obj;
end

procedure map_enter_p_proc
begin
    set_light_level(100);
    if (not(is_loading_game)) then begin
        if (((global_var(GVAR_AQ_ALBUQ_EVENTS) bwand 268435456) != 0) and not((map_var(0) bwand 2) != 0)) then begin
            call Generate_BIG_Rocks();
            set_map_var(0, map_var(0) bwor 2);
            if ((global_var(GVAR_AQ_ALBUQ_EVENTS) bwand 536870912) != 0) then begin
                explosion(10503, 0, 5);
                set_global_var(GVAR_AQ_ENEMY_HUNTERS, 1);
            end
        end
        if (global_var(GVAR_AQ_MUTANT_HUNTERS_CANDIDATE) == 4) then begin
            move_to(dude_obj, 17912, 0);
            anim(dude_obj, 1000, 5);
            if (party_member_obj(16777729) != 0) then begin
                if (party_member_obj(16777729) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777729))) then begin
                        critter_attempt_placement(party_member_obj(16777729), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                if (party_member_obj(16777779) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777779))) then begin
                        critter_attempt_placement(party_member_obj(16777779), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                if (party_member_obj(16777811) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777811))) then begin
                        critter_attempt_placement(party_member_obj(16777811), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16777812) != 0) then begin
                if (party_member_obj(16777812) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777812))) then begin
                        critter_attempt_placement(party_member_obj(16777812), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                if (party_member_obj(16777814) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777814))) then begin
                        critter_attempt_placement(party_member_obj(16777814), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16777748) != 0) then begin
                if (party_member_obj(16777748) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777748))) then begin
                        critter_attempt_placement(party_member_obj(16777748), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16778017) != 0) then begin
                if (party_member_obj(16778017) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16778017))) then begin
                        critter_attempt_placement(party_member_obj(16778017), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16778016) != 0) then begin
                if (party_member_obj(16778016) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16778016))) then begin
                        critter_attempt_placement(party_member_obj(16778016), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16778049) != 0) then begin
                if (party_member_obj(16778049) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16778049))) then begin
                        critter_attempt_placement(party_member_obj(16778049), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16778050) != 0) then begin
                if (party_member_obj(16778050) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16778050))) then begin
                        critter_attempt_placement(party_member_obj(16778050), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16778051) != 0) then begin
                if (party_member_obj(16778051) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16778051))) then begin
                        critter_attempt_placement(party_member_obj(16778051), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16777293) != 0) then begin
                if (party_member_obj(16777293) != 0) then begin
                    if (obj_is_visible_flag(party_member_obj(16777293))) then begin
                        critter_attempt_placement(party_member_obj(16777293), tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 3), dude_elevation);
                    end
                end
            end
            if (party_member_obj(16777729) != 0) then begin
                anim(party_member_obj(16777729), 1000, 5);
            end
            if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
                anim(party_member_obj(16777779), 1000, 5);
            end
            if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
                anim(party_member_obj(16777811), 1000, 5);
            end
            if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
                anim(party_member_obj(16777814), 1000, 5);
            end
            if (party_member_obj(16778017) != 0) then begin
                anim(party_member_obj(16778017), 1000, 5);
            end
            if (party_member_obj(16778016) != 0) then begin
                anim(party_member_obj(16778016), 1000, 5);
            end
            if (party_member_obj(16778049) != 0) then begin
                anim(party_member_obj(16778049), 1000, 5);
            end
            if (party_member_obj(16778050) != 0) then begin
                anim(party_member_obj(16778050), 1000, 5);
            end
            if (party_member_obj(16778051) != 0) then begin
                anim(party_member_obj(16778051), 1000, 5);
            end
            if (party_member_obj(16777812) != 0) then begin
                anim(party_member_obj(16777812), 1000, 5);
            end
            add_timer_event(self_obj, game_ticks(0), 1);
        end
    end
end

procedure map_update_p_proc
begin
    set_light_level(100);
end

procedure map_exit_p_proc
begin
    if ((global_var(GVAR_AQ_MUTANT_HUNTERS_CANDIDATE) == 4) and (global_var(GVAR_AQ_ENEMY_HUNTERS) == 1)) then begin
        set_global_var(GVAR_AQ_MUTANT_HUNTERS_CANDIDATE, 2);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        tile_set_center(16709);
    end
    if (fixed_param == 2) then begin
        set_global_var(GVAR_AQ_MUTANT_HUNTERS_CANDIDATE, 5);
        destroy_object(speech_listener1);
        destroy_object(speech_listener2);
        destroy_object(speech_listener3);
        destroy_object(speech_listener4);
        destroy_object(speech_listener5);
        destroy_object(speech_listener6);
        destroy_object(speech_listener7);
        destroy_object(speech_listener8);
        destroy_object(Sebastian_obj);
        game_ui_enable;
        load_map(23, 0);
    end
end

procedure Generate_publikum
begin
end

procedure Generate_BIG_Rocks
begin
    removable_wall := tile_contains_pid_obj(9101, 0, 50331840);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9301, 0, 50331840);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9501, 0, 50331841);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9701, 0, 50331842);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9901, 0, 50331843);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10101, 0, 50331844);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9306, 0, 50331880);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9506, 0, 50331881);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9706, 0, 50331881);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(9906, 0, 50331878);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10106, 0, 50331879);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(11101, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(11103, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10902, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10904, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(11105, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10904, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10301, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10303, 0, 83886103);
    destroy_object(removable_wall);
    removable_wall := tile_contains_pid_obj(10305, 0, 83886103);
    destroy_object(removable_wall);
    create_object(67108980, 10106, 0);
    create_object(67108980, 9706, 0);
    create_object(67108980, 9306, 0);
    create_object(67108980, 8906, 0);
    create_object(67108980, 10104, 0);
    create_object(67108980, 9704, 0);
    create_object(67108980, 9304, 0);
    create_object(67108980, 8904, 0);
    create_object(50331867, 9901, 0);
    create_object(50331866, 9702, 0);
    create_object(50331865, 9903, 0);
    create_object(50331864, 9703, 0);
    create_object(50331883, 9905, 0);
    create_object(33554512, 10904, 0);
    create_object(33554511, 10902, 0);
    create_object(33554513, 10503, 0);
    create_object(33554513, 10704, 0);
    create_object(33554499, 11105, 0);
    create_object(33554499, 10904, 0);
    create_object(33554499, 11103, 0);
    create_object(33554499, 10902, 0);
    create_object(33554499, 10905, 0);
    create_object(33554499, 10704, 0);
    create_object(33554499, 10903, 0);
    create_object(33554499, 10702, 0);
end
