variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure map_enter_p_proc;
procedure critter_p_proc;
procedure damage_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure combat_p_proc;

variable Projed_smycku;
variable probability;
variable DO_FLOAT_PST := 9;
variable pojistka;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 267);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_TOUGH_GUARD_NO_TALKING);
    if (local_var(5) == 0) then begin
        set_local_var(5, tile_num(self_obj));
    end
    if ((global_var(GVAR_AQ_ALBUQ_DEATHS) bwand 2) != 0) then begin
        destroy_object(self_obj);
    end
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) or (global_var(GVAR_AQ_ENEMY_PRISTEH) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if (((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) and obj_can_see_obj(self_obj, dude_obj) and not((map_var(0) bwand 131072) != 0)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if (((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) and ((map_var(0) bwand 131072) != 0) and (global_var(GVAR_AQ_ENEMY_PRISTEH) == 0) and not(combat_is_initialized)) then begin
        critter_stop_attacking(self_obj);
    end
    if (((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) and (local_var(5) != tile_num(self_obj)) and (global_var(GVAR_AQ_ENEMY_PRISTEH) == 0) and not(combat_is_initialized)) then begin
        if (obj_on_screen(self_obj) == 0) then begin
            move_to(self_obj, local_var(5), elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, local_var(5), 1);
        end
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_AQ_ALBUQ_SPEECHES, global_var(GVAR_AQ_ALBUQ_SPEECHES) bwor 1048576);
        probability := random(0, 15);
        if ((probability >= 15) and not(critter_is_fleeing(self_obj))) then begin
            if ((local_var(4) == 1) and (get_critter_stat(self_obj, STAT_current_hp) > 0) and obj_can_see_obj(self_obj, dude_obj)) then begin
                float_msg(self_obj, mstr(403), FLOAT_MSG_RED);
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_AQ_ALBUQ_SPEECHES, global_var(GVAR_AQ_ALBUQ_SPEECHES) bwor 1048576);
        set_local_var(4, 1);
    end
end

procedure talk_p_proc
begin
    if ((local_var(4) == 1) or ((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) or (global_var(GVAR_AQ_ENEMY_PRISTEH) == 1)) then begin
        Projed_smycku := 1;
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
    end
    if ((dude_elevation == 1) and (global_var(GVAR_AQ_QUEST_BRING_VEX_HEAD) != 2) and (Projed_smycku == 0)) then begin
        if (dude_gender == 0) then begin
            float_msg(self_obj, mstr(random(318, 319)), FLOAT_MSG_YELLOW);
        end
        if (dude_gender == 1) then begin
            float_msg(self_obj, mstr(random(319, 320)), FLOAT_MSG_YELLOW);
        end
        Projed_smycku := 1;
    end
    if (Projed_smycku == 0) then begin
        while (Projed_smycku == 0) do begin
            probability := random(0, 12);
            if ((party_member_obj(16777812) != 0) and (probability >= DO_FLOAT_PST) and (Projed_smycku == 0)) then begin
                if (self_gender == 0) then begin
                    float_msg(self_obj, mstr(random(314, 316)), FLOAT_MSG_YELLOW);
                end
                if (self_gender == 1) then begin
                    float_msg(self_obj, mstr(random(315, 317)), FLOAT_MSG_YELLOW);
                end
                Projed_smycku := 1;
            end
            probability := random(0, 12);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_AQ_MUTANT_HUNTER) == 1) and (global_var(GVAR_AQ_QUEST_BRING_VEX_HEAD) != 2)) then begin
                float_msg(self_obj, mstr(random(311, 313)), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_AQ_QUEST_KILL_WILLIAM_WIFE) == 3)) then begin
                if ((global_var(GVAR_AQ_ALBUQ_DEATHS) bwand 4) != 0) then begin
                    float_msg(self_obj, mstr(309), FLOAT_MSG_YELLOW);
                end
                if ((global_var(GVAR_AQ_ALBUQ_DEATHS) bwand 8) != 0) then begin
                    float_msg(self_obj, mstr(310), FLOAT_MSG_YELLOW);
                end
                Projed_smycku := 1;
            end
            probability := random(0, 18);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_AQ_QUEST_BRING_VEX_HEAD) == 2)) then begin
                if (dude_gender == 0) then begin
                    float_msg(self_obj, mstr(random(305, 307)), FLOAT_MSG_YELLOW);
                end
                if (dude_gender == 1) then begin
                    float_msg(self_obj, mstr(random(306, 307)), FLOAT_MSG_YELLOW);
                end
                Projed_smycku := 1;
            end
            probability := random(0, 13);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_AQ_QUEST_BRING_VEX_HEAD) != 2)) then begin
                if ((global_var(GVAR_AQ_ALBUQ_DEATHS) bwand 16) != 0) then begin
                    float_msg(self_obj, mstr(random(300, 302)), FLOAT_MSG_YELLOW);
                end
                else begin
                    float_msg(self_obj, mstr(random(300, 304)), FLOAT_MSG_YELLOW);
                end
                Projed_smycku := 1;
            end
            pojistka := pojistka + 1;
            probability := random(0, 11);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) or (pojistka > 4)) then begin
                float_msg(self_obj, mstr(304), FLOAT_MSG_YELLOW);
                pojistka := 0;
                Projed_smycku := 1;
            end
        end
    end
    Projed_smycku := 0;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_TOWN_REP_ALBUQUERQUE, global_var(GVAR_TOWN_REP_ALBUQUERQUE) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_ALBUQUERQUE, global_var(GVAR_TOWN_REP_ALBUQUERQUE) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    if ((global_var(GVAR_AQ_QUEST_KILL_WILLIAM_WIFE) == 1) or (global_var(GVAR_AQ_QUEST_KILL_WILLIAM_WIFE) == 2)) then begin
        set_map_var(0, map_var(0) bwor 16384);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_mstr(200);
    end
    else begin
        display_mstr(201);
    end
end

procedure use_skill_on_p_proc
begin
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        if ((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) then begin
            probability := random(0, 12);
            if ((probability >= 12) and not(critter_is_fleeing(self_obj))) then begin
                if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj) and (dude_gender == 0)) then begin
                    float_msg(self_obj, mstr(random(400, 401)), FLOAT_MSG_RED);
                end
                if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj) and (dude_gender == 1)) then begin
                    float_msg(self_obj, mstr(random(401, 402)), FLOAT_MSG_RED);
                end
            end
        end
        if (obj_can_see_obj(self_obj, dude_obj) and not((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) and (global_var(GVAR_AQ_ENEMY_PRISTEH) == 1) and not((map_var(0) bwand 131072) != 0)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack(dude_obj);
            end
        end
    end
    if ((global_var(GVAR_AQ_QUEST_KILL_WILLIAM_WIFE) == 1) or (global_var(GVAR_AQ_QUEST_KILL_WILLIAM_WIFE) == 2) and ((global_var(GVAR_AQ_ALBUQ_SPEECHES) bwand 1048576) != 0) and tile_in_tile_rect(11144, 11111, 15944, 15911, dude_tile) and (global_var(GVAR_AQ_ENEMY_PRISTEH) == 0) and (global_var(GVAR_AQ_ENEMY_VEX) == 0) and (global_var(GVAR_AQ_ENEMY_HUNTERS) == 0) and not((map_var(0) bwand 131072) != 0)) then begin
        if (tile_in_tile_rect(11144, 11111, 15944, 15911, tile_num(self_obj))) then begin
            if (tile_in_tile_rect(13722, 13717, 16722, 16717, tile_num(self_obj))) then begin
                set_map_var(0, map_var(0) bwor 1048576);
            end
            else begin
                if (tile_in_tile_rect(13748, 13723, 16748, 16723, tile_num(self_obj))) then begin
                    set_map_var(0, map_var(0) bwor 2097152);
                end
                else begin
                    set_map_var(0, map_var(0) bwor 524288);
                end
            end
            set_map_var(0, map_var(0) bwor 131072);
            terminate_combat;
        end
    end
end
