variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);

variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure timed_event_p_proc;

variable Projed_smycku;
variable probability;
variable DO_FLOAT_PST := 9;
variable pojistka;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 1) or (global_var(GVAR_ENEMY_CORATH) == 1) or (global_var(GVAR_C_ENEMY_OBYVAT) == 1) or (global_var(GVAR_C_ENEMY_UNCLE) == 1) or (global_var(GVAR_C_ENEMY_NESTOR) == 1) or ((global_var(GVAR_C_CORATH_STATUS) bwand 8192) != 0) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (dude_gender == 0) then begin
            float_msg(self_obj, mstr(400), FLOAT_MSG_RED);
        end
        if (dude_gender == 1) then begin
            float_msg(self_obj, mstr(401), FLOAT_MSG_RED);
        end
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if (local_var(5) == 1) then begin
        if ((game_time_hour < 800) or (2000 < game_time_hour) and (tile_num(self_obj) != 19749) and (art_anim(obj_art_fid(self_obj)) != 1)) then begin
            animate_move_obj_to_tile(self_obj, 19749, 0);
        end
        if ((game_time_hour < 800) or (2000 < game_time_hour) and (tile_num(self_obj) == 19749) and obj_is_visible_flag(self_obj)) then begin
            set_obj_visibility(self_obj, 1);
        end
        if ((game_time_hour >= 800) and (2000 >= game_time_hour) and (tile_num(self_obj) != 21117) and (art_anim(obj_art_fid(self_obj)) != 1)) then begin
            if (not(obj_is_visible_flag(self_obj))) then begin
                set_obj_visibility(self_obj, 0);
            end
            animate_move_obj_to_tile(self_obj, 21117, 0);
        end
        if ((game_time_hour >= 800) and (2000 >= game_time_hour) and (tile_num(self_obj) == 21117) and (obj_get_rot(self_obj) != 1)) then begin
            anim(self_obj, 1000, 1);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(GVAR_ENEMY_CORATH, 1);
        float_msg(self_obj, mstr(403), FLOAT_MSG_RED);
    end
end

procedure talk_p_proc
begin
    if (Projed_smycku == 0) then begin
        while (Projed_smycku == 0) do begin
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= (DO_FLOAT_PST - 2)) and (party_member_obj(16777812) != 0)) then begin
                float_msg(self_obj, mstr(312), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= (DO_FLOAT_PST - 2)) and (party_member_obj(16777812) != 0)) then begin
                float_msg(self_obj, mstr(311), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_C_STRIKE_IN_MINE) == 3)) then begin
                float_msg(self_obj, mstr(310), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(GVAR_C_CORATH_STATUS) bwand 131072) != 0)) then begin
                float_msg(self_obj, mstr(309), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_NESTOR_LEAVED_CORATH) == 1)) then begin
                float_msg(self_obj, mstr(308), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_C_QUEST_MURDERS) != 3) and (global_var(GVAR_C_QUEST_CHADWIC_WANT_SUZAN) != 3) and not((global_var(GVAR_C_RING_VICTORIES) bwand 1024) != 0) and not((global_var(GVAR_C_CORATH_STATUS) bwand 65536) != 0)) then begin
                float_msg(self_obj, mstr(313), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_C_QUEST_MURDERS) == 3)) then begin
                float_msg(self_obj, mstr(307), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and (global_var(GVAR_C_QUEST_MURDERS) == 3)) then begin
                float_msg(self_obj, mstr(306), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, mstr(305), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, mstr(304), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(GVAR_C_QUEST_MURDERS) != 3) or ((global_var(GVAR_C_QUEST_UNCLE_Q1) == 4) or ((global_var(GVAR_C_CORATH_STATUS) bwand 1024) != 0) and ((global_var(GVAR_C_QUEST_UNCLE_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 3))) or ((global_var(GVAR_C_QUEST_NESTOR_Q1) == 5) or ((global_var(GVAR_C_CORATH_STATUS) bwand 16384) != 0) and ((global_var(GVAR_C_QUEST_NESTOR_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 2))))) then begin
                float_msg(self_obj, mstr(303), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(GVAR_C_QUEST_MURDERS) != 3) or ((global_var(GVAR_C_QUEST_UNCLE_Q1) == 4) or ((global_var(GVAR_C_CORATH_STATUS) bwand 1024) != 0) and ((global_var(GVAR_C_QUEST_UNCLE_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 3))) or ((global_var(GVAR_C_QUEST_NESTOR_Q1) == 5) or ((global_var(GVAR_C_CORATH_STATUS) bwand 16384) != 0) and ((global_var(GVAR_C_QUEST_NESTOR_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 2))))) then begin
                float_msg(self_obj, mstr(302), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST)) then begin
                float_msg(self_obj, mstr(301), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            probability := random(0, 10);
            if ((Projed_smycku == 0) and (probability >= DO_FLOAT_PST) and ((global_var(GVAR_C_QUEST_MURDERS) != 3) or ((global_var(GVAR_C_QUEST_UNCLE_Q1) == 4) or ((global_var(GVAR_C_CORATH_STATUS) bwand 1024) != 0) and ((global_var(GVAR_C_QUEST_UNCLE_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 3))) or ((global_var(GVAR_C_QUEST_NESTOR_Q1) == 5) or ((global_var(GVAR_C_CORATH_STATUS) bwand 16384) != 0) and ((global_var(GVAR_C_QUEST_NESTOR_Q2) == 3) or (global_var(GVAR_C_STRIKE_IN_MINE) == 2))))) then begin
                float_msg(self_obj, mstr(300), FLOAT_MSG_YELLOW);
                Projed_smycku := 1;
            end
            pojistka := pojistka + 1;
            if ((Projed_smycku == 0) and (pojistka > 4)) then begin
                float_msg(self_obj, mstr(random(304, 305)), FLOAT_MSG_YELLOW);
                pojistka := 0;
                Projed_smycku := 1;
            end
        end
    end
    Projed_smycku := 0;
end

procedure destroy_p_proc
begin
    if (cur_map_index != MAP_CORATH3) then begin
        if (source_obj == dude_obj) then begin
            set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
            if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 1);
                set_global_var(GVAR_BERSERKER_REPUTATION, 0);
            end
            if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
                if (source_obj == dude_obj) then begin
                    set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                    set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                    debug_msg("Player gains " + -15 + " Karma Points.");
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                    set_global_var(GVAR_KARMA_DEFENDER, 0);
                    set_global_var(GVAR_KARMA_WANDERER, 0);
                    set_global_var(GVAR_KARMA_BETRAYER, 0);
                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                        set_global_var(GVAR_KARMA_WANDERER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                            end
                                            else begin
                                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                                end
                                                else begin
                                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    set_global_var(GVAR_TOWN_REP_CORATH, global_var(GVAR_TOWN_REP_CORATH) + -8);
                    debug_msg("Added " + -8 + " to Town Rep");
                end
            end
            if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
                set_global_var(GVAR_BERSERKER_REPUTATION, 1);
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
            end
            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
            debug_msg("Player gains " + -10 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            set_global_var(GVAR_TOWN_REP_CORATH, global_var(GVAR_TOWN_REP_CORATH) + -5);
            debug_msg("Added " + -5 + " to Town Rep");
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_mstr(200);
    end
    else begin
        display_mstr(201);
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 1);
        set_global_var(GVAR_ENEMY_CORATH, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 254);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_TOUGH_GUARD);
    if (map_first_run and (CUR_MAP_CORATH2)) then begin
        if (tile_num(self_obj) == 21117) then begin
            set_local_var(5, 1);
        end
    end
end

procedure combat_p_proc
begin
    if (fixed_param == 4) then begin
        probability := random(0, 10);
        if ((probability >= 10) and not(critter_is_fleeing(self_obj))) then begin
            if ((local_var(4) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
                float_msg(self_obj, mstr(402), FLOAT_MSG_RED);
            end
        end
    end
    if (global_var(GVAR_C_ENEMY_OBYVAT) == 1) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 243);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 10) then begin
        float_msg(self_obj, mstr(403), FLOAT_MSG_RED);
        display_mstr(450);
        set_local_var(4, 1);
        set_global_var(GVAR_ENEMY_CORATH, 1);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
end
