procedure start;

variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable Finding_New_Tile;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure destroy_p_proc;
procedure critter_p_proc;
procedure map_enter_p_proc;


procedure start
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 142);
end

procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure destroy_p_proc
begin
    if ((global_var(GVAR_KARAVAN_ROUTES_COMMAND_BITS) bwand 1) != 0) then begin
        set_global_var(GVAR_KARAVAN_ATACKERS_COUNTER, global_var(GVAR_KARAVAN_ATACKERS_COUNTER) - 1);
    end
    if (CUR_MAP_BHRNDDST) then begin
        set_map_var(1, map_var(1) - 1);
    end
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj) and not((global_var(GVAR_KARAVAN_ROUTES_COMMAND_BITS) bwand 1) != 0)) then begin
        attack(dude_obj);
    end
    if (obj_can_see_obj(self_obj, dude_obj) and ((global_var(GVAR_KARAVAN_ROUTES_COMMAND_BITS) bwand 1) != 0) and ((global_var(GVAR_KARAVAN_ROUTES_COMMAND_BITS) bwand 8388608) != 0)) then begin
        attack(dude_obj);
    end
end

procedure map_enter_p_proc
begin
    if (not(is_loading_game)) then begin
        if (elevation(self_obj) == 0) then begin
            if (global_var(GVAR_ENC_NUMBERS_ANIMALS) >= 10) then begin
                destroy_object(self_obj);
            end
            else begin
                set_global_var(GVAR_ENC_NUMBERS_ANIMALS, global_var(GVAR_ENC_NUMBERS_ANIMALS) + 1);
            end
        end
        if ((global_var(GVAR_CARAVANS_RANDOM_ECCS) bwand 1) != 0) then begin
            critter_attempt_placement(self_obj, tile_num(self_obj), 1);
        end
    end
end
