variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure map_update_p_proc;

import variable Guard_5;
import variable Guard_6;
import variable Guard_8;
import variable Elev_door_L4;
import variable Elev_door_L5;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    if (elevation(self_obj) == 0) then begin
        Elev_door_L4 := self_obj;
    end
    if ((elevation(self_obj) == 1) and (tile_num(self_obj) == 15072)) then begin
        Elev_door_L5 := self_obj;
    end
end

procedure use_p_proc
begin
    if (elevation(self_obj) == 0) then begin
        if (Guard_5 and (global_var(GVAR_G_ELEV35_ACCESS) == 0) and ((global_var(GVAR_ENEMY_OBRODA) == 0) or not(combat_is_initialized))) then begin
            script_overrides;
            add_timer_event(Guard_5, 0, 10);
        end
    end
    if ((elevation(self_obj) == 1) and (tile_num(self_obj) == 15072)) then begin
        if (Guard_6 and (global_var(GVAR_G_ELEV35_ACCESS) == 0) and ((global_var(GVAR_ENEMY_OBRODA) == 0) or not(combat_is_initialized))) then begin
            script_overrides;
            add_timer_event(Guard_6, 0, 10);
        end
    end
    if ((elevation(self_obj) == 1) and (tile_num(self_obj) == 22664)) then begin
        if (Guard_8 and (map_var(8) == 0) and ((global_var(GVAR_ENEMY_OBRODA) == 0) or not(combat_is_initialized))) then begin
            script_overrides;
            add_timer_event(Guard_8, 0, 10);
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(SCRIPT_GELVDR13, 102));
end

procedure description_p_proc
begin
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 9) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_GELVDR13, 101));
    end
end

procedure use_obj_on_p_proc
begin
    if ((obj_pid(obj_being_used_with) == 411) or (obj_pid(obj_being_used_with) == 77)) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_GELVDR13, 101));
    end
end

procedure map_update_p_proc
begin
    if ((elevation(self_obj) == 1) and (tile_num(self_obj) == 22664) and (tile_distance_objs(self_obj, dude_obj) > 6) and obj_is_open(self_obj)) then begin
        obj_close(self_obj);
    end
    if ((elevation(self_obj) == 2) and (tile_distance_objs(self_obj, dude_obj) > 6) and obj_is_open(self_obj)) then begin
        obj_close(self_obj);
    end
end
