variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node998;
procedure Node999;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;
procedure Node1400;
procedure Node1450;
procedure Node1500;
procedure Node1550;
procedure Node1600;
procedure Node1650;
procedure Node1700;
procedure Node1750;
procedure Node1800;
procedure Node1850;
procedure Node1900;
procedure Node1950;
procedure Node2000;
procedure Node2050;
procedure Node2100;
procedure Node2150;
procedure Node2200;
procedure Node2250;
procedure Node2300;
procedure Node2350;
procedure Node2400;
procedure Node2450;
procedure Node2500;
procedure Node2550;

variable projed_smycku;

import variable Johnatan_box;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777958) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777958)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777957) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777957)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778018) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778018)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(4) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        float_msg(self_obj, mstr(400), FLOAT_MSG_RED);
        set_local_var(4, 1);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if (map_var(0) == 1) then begin
        if (obj_can_see_obj(self_obj, dude_obj) or obj_can_hear_obj(self_obj, dude_obj)) then begin
            float_msg(self_obj, mstr(400), FLOAT_MSG_RED);
            attack(dude_obj);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 2);
    end
end

procedure talk_p_proc
begin
    anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
    anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
    if ((global_var(GVAR_QUEST_JOHNATAN_CAVE) == 0) and (local_var(5) != 1)) then begin
        start_gdialog(1376, self_obj, 4, -1, -1);
        gsay_start;
        call Node500();
        gsay_end;
        end_dialogue;
        projed_smycku := 1;
    end
    if ((local_var(5) == 1) and (projed_smycku == 0) and ((global_var(GVAR_QUEST_JOHNATAN_CAVE) == 0) or (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 3))) then begin
        start_gdialog(1376, self_obj, 4, -1, -1);
        gsay_start;
        call Node1650();
        gsay_end;
        end_dialogue;
        projed_smycku := 1;
    end
    if ((local_var(5) == 1) and (projed_smycku == 0) and ((global_var(GVAR_QUEST_JOHNATAN_CAVE) == 1) or (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2))) then begin
        start_gdialog(1376, self_obj, 4, -1, -1);
        gsay_start;
        if (local_var(8) != 1) then begin
            call Node1900();
        end
        else begin
            call Node2200();
        end
        gsay_end;
        end_dialogue;
        projed_smycku := 1;
    end
    projed_smycku := 0;
end

procedure destroy_p_proc
begin
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
    debug_msg("Player gains " + -10 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_mstr(150);
    end
    else begin
        display_mstr(100);
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(5) == 1) then begin
        display_mstr(250);
    end
    else begin
        display_mstr(200);
    end
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, 2);
        set_map_var(0, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 231);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS_NO_TALKING);
end

procedure Node998
begin
    set_local_var(4, 2);
end

procedure Node999
begin
    anim(self_obj, 1000, 3);
end

procedure Node500
begin
    Reply(500);
    giq_option(4, NAME, mstr(501) + dude_name, Node550, NEUTRAL_REACTION);
    if (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) then begin
        giq_option(4, NAME, 502, Node800, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 503, Node999, NEUTRAL_REACTION);
    if ((dude_gender == 0) and obj_is_carrying_obj_pid(dude_obj, 98) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(-3, NAME, 504, Node2250, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and obj_is_carrying_obj_pid(dude_obj, 98) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(-3, NAME, 505, Node2250, NEUTRAL_REACTION);
    end
    giq_option(-3, NAME, 506, Node999, NEUTRAL_REACTION);
end

procedure Node550
begin
    Reply(550);
    set_local_var(5, 1);
    giq_option(8, NAME, 551, Node650, NEUTRAL_REACTION);
    giq_option(4, NAME, 552, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 553, Node750, NEUTRAL_REACTION);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 554, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 555, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 556, Node999, NEUTRAL_REACTION);
end

procedure Node600
begin
    Reply(600);
    giq_option(8, NAME, 601, Node650, NEUTRAL_REACTION);
    giq_option(4, NAME, 602, Node750, NEUTRAL_REACTION);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 603, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 604, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 605, Node999, NEUTRAL_REACTION);
end

procedure Node650
begin
    Reply(650);
    giq_option(4, NAME, 651, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 652, Node700, NEUTRAL_REACTION);
    giq_option(4, NAME, 653, Node750, NEUTRAL_REACTION);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 654, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 655, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 656, Node999, NEUTRAL_REACTION);
end

procedure Node700
begin
    Reply(700);
    giq_option(4, NAME, 701, Node750, NEUTRAL_REACTION);
    giq_option(4, NAME, 702, Node600, NEUTRAL_REACTION);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 703, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 704, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 705, Node999, NEUTRAL_REACTION);
end

procedure Node750
begin
    Reply(750);
    giq_option(8, NAME, 751, Node650, NEUTRAL_REACTION);
    giq_option(4, NAME, 752, Node600, NEUTRAL_REACTION);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 753, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1) and (local_var(6) != 1)) then begin
        giq_option(4, NAME, 754, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 755, Node999, NEUTRAL_REACTION);
end

procedure Node800
begin
    Reply(800);
    set_local_var(5, 1);
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 801, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 802, Node900, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 803, Node999, NEUTRAL_REACTION);
end

procedure Node850
begin
    Reply(850);
    set_local_var(6, 1);
    if (obj_is_carrying_obj_pid(dude_obj, 98)) then begin
        giq_option(4, NAME, 851, Node1000, NEUTRAL_REACTION);
    end
    if (not(obj_is_carrying_obj_pid(dude_obj, 98))) then begin
        giq_option(4, NAME, 852, Node950, NEUTRAL_REACTION);
    end
end

procedure Node900
begin
    Reply(900);
    set_local_var(6, 1);
    if (obj_is_carrying_obj_pid(dude_obj, 98)) then begin
        giq_option(4, NAME, 901, Node1000, NEUTRAL_REACTION);
    end
    if (not(obj_is_carrying_obj_pid(dude_obj, 98))) then begin
        giq_option(4, NAME, 902, Node950, NEUTRAL_REACTION);
    end
end

procedure Node950
begin
    Reply(950);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 951, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 952, Node1200, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 953, Node999, NEUTRAL_REACTION);
end

procedure Node1000
begin
    Reply(1000);
    giq_option(4, NAME, 400 + mstr(1001), Node1050, NEUTRAL_REACTION);
    if (dude_skill(SKILL_BARTER) <= 50) then begin
        giq_option(4, NAME, 600 + mstr(1002), Node1100, NEUTRAL_REACTION);
    end
    if (dude_skill(SKILL_BARTER) > 50) then begin
        giq_option(4, NAME, 600 + mstr(1002), Node1150, NEUTRAL_REACTION);
    end
end

procedure Node1050
begin
    Reply(1050);
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 98);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 98);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 98);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 98)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 98);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    restock_obj := create_object(98, 0, 0);
    add_mult_objs_to_inven(self_obj, restock_obj, 1);
    set_global_var(GVAR_QUEST_S_CHARLIE_JUNK, 2);
    item_caps_adjust(dude_obj, 400);
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1051, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1052, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1053, Node1350, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1054, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1100
begin
    Reply(mstr(1100) + 600 + mstr(1101) + 400 + mstr(1102));
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 98);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 98);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 98);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 98)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 98);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    restock_obj := create_object(98, 0, 0);
    add_mult_objs_to_inven(self_obj, restock_obj, 1);
    set_global_var(GVAR_QUEST_S_CHARLIE_JUNK, 2);
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    item_caps_adjust(dude_obj, 400);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1103, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1104, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1105, Node1350, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1106, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1150
begin
    Reply(1150);
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 98);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 98);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 98);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 98)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 98);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    restock_obj := create_object(98, 0, 0);
    add_mult_objs_to_inven(self_obj, restock_obj, 1);
    set_global_var(GVAR_QUEST_S_CHARLIE_JUNK, 2);
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    item_caps_adjust(dude_obj, 600);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1151, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1152, Node1200, NEUTRAL_REACTION);
    end
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1153, Node1350, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1154, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1200
begin
    Reply(1200);
    giq_option(4, NAME, 1201, Node1250, NEUTRAL_REACTION);
    giq_option(4, NAME, 1202, Node1300, NEUTRAL_REACTION);
    if (global_var(GVAR_QUEST_S_CHARLIE_JUNK) != 2) then begin
        giq_option(4, NAME, 1203, Node999, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1203, Node1350, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1204, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1250
begin
    Reply(1250);
    giq_option(4, NAME, 1251, Node1300, NEUTRAL_REACTION);
    if (global_var(GVAR_QUEST_S_CHARLIE_JUNK) != 2) then begin
        giq_option(4, NAME, 1252, Node999, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1252, Node1350, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1253, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1300
begin
    Reply(1300);
    giq_option(4, NAME, 1301, Node1250, NEUTRAL_REACTION);
    if (global_var(GVAR_QUEST_S_CHARLIE_JUNK) != 2) then begin
        giq_option(4, NAME, 1302, Node999, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1302, Node1350, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2)) then begin
        giq_option(4, NAME, 1303, Node1400, NEUTRAL_REACTION);
    end
end

procedure Node1350
begin
    Reply(1350);
    giq_option(4, NAME, 1351, Node1450, NEUTRAL_REACTION);
end

procedure Node1400
begin
    Reply(1400);
    giq_option(4, NAME, 1401, Node1450, NEUTRAL_REACTION);
end

procedure Node1450
begin
    Reply(1450);
    giq_option(4, NAME, 1451, Node1500, NEUTRAL_REACTION);
end

procedure Node1500
begin
    Reply(1500);
    giq_option(4, NAME, 1501, Node1550, NEUTRAL_REACTION);
    giq_option(4, NAME, 1502, Node1600, NEUTRAL_REACTION);
end

procedure Node1550
begin
    Reply(1550);
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 1);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(4, NAME, 1551, Node999, NEUTRAL_REACTION);
end

procedure Node1600
begin
    Reply(1600);
    set_local_var(7, 1);
    giq_option(4, NAME, 1601, Node999, NEUTRAL_REACTION);
end

procedure Node1650
begin
    Reply(1650);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1651, Node1700, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1652, Node1700, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 2) then begin
        giq_option(4, NAME, 1653, Node1750, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (local_var(6) != 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 1654, Node850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (local_var(6) != 1) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 1655, Node900, NEUTRAL_REACTION);
    end
    if ((local_var(6) == 1) and obj_is_carrying_obj_pid(dude_obj, 98) and (global_var(GVAR_QUEST_S_CHARLIE_JUNK) == 1)) then begin
        giq_option(4, NAME, 1656, Node1000, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 0) and (local_var(7) == 1)) then begin
        giq_option(4, NAME, 1657, Node1850, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 0) and (local_var(7) == 1)) then begin
        giq_option(4, NAME, 1658, Node1850, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1659, Node999, NEUTRAL_REACTION);
    if ((global_var(GVAR_QUEST_JOHNATAN_CAVE) == 0) and (local_var(7) == 1)) then begin
        giq_option(-3, NAME, 1660, Node2450, NEUTRAL_REACTION);
    end
    giq_option(-3, NAME, 1661, Node999, NEUTRAL_REACTION);
end

procedure Node1700
begin
    Reply(1700);
    giq_option(8, NAME, 1701, Node650, NEUTRAL_REACTION);
    giq_option(4, NAME, 1702, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 1703, Node750, NEUTRAL_REACTION);
    giq_option(4, NAME, 1704, Node999, NEUTRAL_REACTION);
end

procedure Node1750
begin
    Reply(1750);
    giq_option(4, NAME, 1751, Node1800, NEUTRAL_REACTION);
    giq_option(4, NAME, 1752, Node999, NEUTRAL_REACTION);
end

procedure Node1800
begin
    Reply(1800);
    giq_option(4, NAME, 1801, Node1750, NEUTRAL_REACTION);
    giq_option(4, NAME, 1802, Node999, NEUTRAL_REACTION);
end

procedure Node1850
begin
    Reply(1850);
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 1);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(4, NAME, 1851, Node999, NEUTRAL_REACTION);
end

procedure Node1900
begin
    Reply(1900);
    if ((dude_gender == 0) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 1)) then begin
        giq_option(4, NAME, 1901, Node1950, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 1)) then begin
        giq_option(4, NAME, 1902, Node2000, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2) and obj_carrying_pid_obj(Johnatan_box, 560) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 0)) then begin
        giq_option(4, NAME, 1903, Node2050, NEUTRAL_REACTION);
    end
    if ((dude_gender == 0) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2) and not(obj_carrying_pid_obj(Johnatan_box, 560)) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 0)) then begin
        giq_option(4, NAME, 1903, Node2100, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2) and obj_carrying_pid_obj(Johnatan_box, 560) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 0)) then begin
        giq_option(4, NAME, 1904, Node2050, NEUTRAL_REACTION);
    end
    if ((dude_gender == 1) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2) and not(obj_carrying_pid_obj(Johnatan_box, 560)) and (global_var(GVAR_HOLODISK_MB_LEVEL_2) == 0)) then begin
        giq_option(4, NAME, 1904, Node2100, NEUTRAL_REACTION);
    end
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 1905, Node1700, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 1906, Node1700, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1907, Node1750, NEUTRAL_REACTION);
    giq_option(4, NAME, 1908, Node999, NEUTRAL_REACTION);
    if (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2) then begin
        giq_option(-3, NAME, 1909, Node2500, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 1) then begin
        giq_option(-3, NAME, 1910, Node999, NEUTRAL_REACTION);
    end
end

procedure Node1950
begin
    Reply(1950);
    if (obj_carrying_pid_obj(Johnatan_box, 560) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 1951, Node2050, NEUTRAL_REACTION);
    end
    if (not(obj_carrying_pid_obj(Johnatan_box, 560)) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 1952, Node2100, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 1) then begin
        giq_option(4, NAME, 1953, Node2150, NEUTRAL_REACTION);
    end
end

procedure Node2000
begin
    Reply(2000);
    if (obj_carrying_pid_obj(Johnatan_box, 560) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 2001, Node2050, NEUTRAL_REACTION);
    end
    if (not(obj_carrying_pid_obj(Johnatan_box, 560)) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 2002, Node2100, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 1) then begin
        giq_option(4, NAME, 2003, Node2150, NEUTRAL_REACTION);
    end
end

procedure Node2050
begin
    Reply(mstr(2050) + 2000 + mstr(2051));
    set_local_var(8, 8);
    item_caps_adjust(dude_obj, 2000);
    removed_qty := obj_is_carrying_obj_pid(Johnatan_box, 560);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(Johnatan_box, 560);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(Johnatan_box, 560);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(Johnatan_box, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(Johnatan_box, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(Johnatan_box, restock_obj);
                    add_obj_to_inven(Johnatan_box, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(Johnatan_box, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(Johnatan_box, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(Johnatan_box);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(Johnatan_box, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(Johnatan_box, 560)) do begin
                restock_obj := obj_carrying_pid_obj(Johnatan_box, 560);
                rm_obj_from_inven(Johnatan_box, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    restock_obj := create_object(560, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 3);
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 20);
    debug_msg("Player gains " + 20 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    give_exp_points(2000);
    display_msg(g_mstr(100) + 2000 + g_mstr(101));
    giq_option(4, NAME, 2052, Node2550, NEUTRAL_REACTION);
    giq_option(4, NAME, 2053, Node999, NEUTRAL_REACTION);
end

procedure Node2100
begin
    Reply(mstr(2100) + 2000 + mstr(2101));
    set_local_var(8, 8);
    item_caps_adjust(dude_obj, 2000);
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 3);
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 20);
    debug_msg("Player gains " + 20 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    give_exp_points(2000);
    display_msg(g_mstr(100) + 2000 + g_mstr(101));
    giq_option(4, NAME, 2102, Node2550, NEUTRAL_REACTION);
    giq_option(4, NAME, 2103, Node999, NEUTRAL_REACTION);
end

procedure Node2150
begin
    Reply(2150);
    set_local_var(8, 1);
    giq_option(4, NAME, 2151, Node999, NEUTRAL_REACTION);
end

procedure Node2200
begin
    Reply(2200);
    if (obj_carrying_pid_obj(Johnatan_box, 560) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 2201, Node2050, NEUTRAL_REACTION);
    end
    if (not(obj_carrying_pid_obj(Johnatan_box, 560)) and (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 2)) then begin
        giq_option(4, NAME, 2202, Node2100, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_QUEST_JOHNATAN_CAVE) == 1) then begin
        giq_option(4, NAME, 2203, Node999, NEUTRAL_REACTION);
    end
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 2204, Node1700, NEUTRAL_REACTION);
    end
    if (dude_gender == 1) then begin
        giq_option(4, NAME, 2205, Node1700, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 2206, Node1750, NEUTRAL_REACTION);
end

procedure Node2250
begin
    Reply(mstr(2250) + 400 + mstr(2251));
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 98);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 98);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 98);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 98)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 98);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    restock_obj := create_object(98, 0, 0);
    add_mult_objs_to_inven(self_obj, restock_obj, 1);
    set_global_var(GVAR_QUEST_S_CHARLIE_JUNK, 2);
    item_caps_adjust(dude_obj, 400);
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    set_local_var(5, 1);
    giq_option(-3, NAME, 2252, Node2300, NEUTRAL_REACTION);
end

procedure Node2300
begin
    Reply(2301);
    set_local_var(7, 1);
    giq_option(-3, NAME, 2302, Node2350, NEUTRAL_REACTION);
    giq_option(-3, NAME, 2303, Node999, NEUTRAL_REACTION);
end

procedure Node2350
begin
    Reply(2350);
    giq_option(-3, NAME, 2351, Node2400, NEUTRAL_REACTION);
end

procedure Node2400
begin
    Reply(2400);
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 1);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(-3, NAME, 2401, Node999, NEUTRAL_REACTION);
end

procedure Node2450
begin
    Reply(2451);
    set_local_var(7, 1);
    giq_option(-3, NAME, 2452, Node2350, NEUTRAL_REACTION);
    giq_option(-3, NAME, 2453, Node999, NEUTRAL_REACTION);
end

procedure Node2500
begin
    Reply(mstr(2500) + 2000 + mstr(2501));
    set_global_var(GVAR_QUEST_JOHNATAN_CAVE, 3);
    item_caps_adjust(dude_obj, 2000);
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 20);
    debug_msg("Player gains " + 20 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    give_exp_points(2000);
    display_msg(g_mstr(100) + 2000 + g_mstr(101));
    giq_option(-3, NAME, 2502, Node999, NEUTRAL_REACTION);
end

procedure Node2550
begin
    Reply(2550);
    giq_option(4, NAME, 2551, Node999, NEUTRAL_REACTION);
end
