variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure Node998;
procedure Node999;
procedure Node999noise;
procedure Node999poison;
procedure Node500;
procedure Node550;
procedure Node600;
procedure Node650;
procedure Node700;
procedure Node750;
procedure Node800;
procedure Node850;
procedure Node900;
procedure Node950;
procedure Node1000;
procedure Node1050;
procedure Node1100;
procedure Node1150;
procedure Node1200;
procedure Node1250;
procedure Node1300;
procedure Node1350;

import variable Carpenter_Bruce;
import variable Carpenter_cook;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777294) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777294)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
    Carpenter_cook := self_obj;
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
    if (global_var(GVAR_ENEMY_SEDIT) == 1) then begin
        if (obj_can_see_obj(self_obj, dude_obj) or obj_can_hear_obj(self_obj, dude_obj)) then begin
            attack(dude_obj);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (local_var(15) != 1) then begin
        if (global_var(GVAR_QUEST_S_DAVID_KIDNAP_INVESTIGATION) == 2) then begin
            anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
            start_gdialog(1347, self_obj, 4, -1, -1);
            gsay_start;
            if (local_var(6) != 1) then begin
                call Node500();
            end
            else begin
                call Node1000();
            end
            gsay_end;
            end_dialogue;
        end
        else begin
            if ((global_var(GVAR_QUEST_S_MIMI_GOLD) == 1) and (dude_iq > 6) and (item_caps_total(dude_obj) >= 50) and (local_var(14) != 1)) then begin
                anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
                anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
                start_gdialog(1347, self_obj, 4, -1, -1);
                gsay_start;
                call Node1050();
                gsay_end;
                end_dialogue;
            end
            else begin
                if (global_var(GVAR_QUEST_S_DAVID_KIDNAP_INVESTIGATION) > 2) then begin
                    if (global_var(GVAR_QUEST_S_DAVID_KIDNAP_INVESTIGATION) == 8) then begin
                        float_msg(self_obj, mstr(random(312, 316)), FLOAT_MSG_YELLOW);
                    end
                    else begin
                        float_msg(self_obj, mstr(random(312, 315)), FLOAT_MSG_YELLOW);
                    end
                end
                else begin
                    if (local_var(13) != 1) then begin
                        if ((global_var(GVAR_QUEST_S_TYLER_SHERIFF) == 1) and (local_var(16) != 1)) then begin
                            anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
                            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
                            start_gdialog(1347, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node1250();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            if (local_var(16) == 1) then begin
                                float_msg(self_obj, mstr(random(312, 314)), FLOAT_MSG_YELLOW);
                            end
                            else begin
                                float_msg(self_obj, mstr(random(300, 305)), FLOAT_MSG_YELLOW);
                            end
                        end
                    end
                    else begin
                        float_msg(self_obj, mstr(random(306, 311)), FLOAT_MSG_YELLOW);
                    end
                end
            end
        end
        set_local_var(4, 1);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(200);
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        restock_obj := create_object(537, 0, 0);
        add_mult_objs_to_inven(Carpenter_Bruce, restock_obj, 1);
        removed_qty := obj_is_carrying_obj_pid(Carpenter_Bruce, 536);
        if (1 < removed_qty) then begin
            removed_qty := 1;
        end
        if (removed_qty > 0) then begin
            restock_obj := obj_carrying_pid_obj(Carpenter_Bruce, 536);
            if (obj_type(self_obj) == 1) then begin
                restock_obj := obj_carrying_pid_obj(Carpenter_Bruce, 536);
                if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                    if (obj_item_subtype(critter_inven_obj(Carpenter_Bruce, INVEN_TYPE_WORN)) == 0) then begin
                        restock_obj := critter_inven_obj(Carpenter_Bruce, INVEN_TYPE_WORN);
                        debug_msg("armour pid == " + obj_pid(restock_obj));
                        rm_obj_from_inven(Carpenter_Bruce, restock_obj);
                        add_obj_to_inven(Carpenter_Bruce, restock_obj);
                    end
                end
                else begin
                    if ((critter_inven_obj(Carpenter_Bruce, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(Carpenter_Bruce, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                        inven_unwield(Carpenter_Bruce);
                    end
                end
            end
            restock_amt := rm_mult_objs_from_inven(Carpenter_Bruce, restock_obj, removed_qty);
            if (restock_amt == 0) then begin
                toRemove_qty := 1;
                while ((toRemove_qty > 0) and obj_carrying_pid_obj(Carpenter_Bruce, 536)) do begin
                    restock_obj := obj_carrying_pid_obj(Carpenter_Bruce, 536);
                    rm_obj_from_inven(Carpenter_Bruce, restock_obj);
                    destroy_object(restock_obj);
                    toRemove_qty := toRemove_qty - 1;
                end
            end
            else begin
                destroy_object(restock_obj);
            end
        end
        restock_obj := 0;
        restock_amt := 0;
    end
    if (fixed_param == 10) then begin
        anim(self_obj, 1000, 0);
        set_local_var(15, 0);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 212);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS_NO_TALKING);
    if (not(is_loading_game)) then begin
        if (local_var(15) == 1) then begin
            set_local_var(15, 0);
        end
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
        set_global_var(GVAR_ENEMY_SEDIT, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_TOWN_REP_SEDIT, global_var(GVAR_TOWN_REP_SEDIT) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_SEDIT, global_var(GVAR_TOWN_REP_SEDIT) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    anim(self_obj, 1000, 0);
end

procedure Node999noise
begin
    set_local_var(15, 1);
    anim(self_obj, 1000, 5);
    add_timer_event(Carpenter_Bruce, 1, 12);
end

procedure Node999poison
begin
    set_local_var(16, 1);
    anim(self_obj, 1000, 5);
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 537);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 537);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 537);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        if (restock_amt == 0) then begin
            toRemove_qty := 1;
            while ((toRemove_qty > 0) and obj_carrying_pid_obj(dude_obj, 537)) do begin
                restock_obj := obj_carrying_pid_obj(dude_obj, 537);
                rm_obj_from_inven(dude_obj, restock_obj);
                destroy_object(restock_obj);
                toRemove_qty := toRemove_qty - 1;
            end
        end
        else begin
            destroy_object(restock_obj);
        end
    end
    restock_obj := 0;
    restock_amt := 0;
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 2);
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    float_msg(self_obj, mstr(317), FLOAT_MSG_YELLOW);
    add_timer_event(self_obj, game_ticks(10), 1);
end

procedure Node500
begin
    if (local_var(13) != 1) then begin
        Reply(500);
    end
    else begin
        Reply(501);
    end
    giq_option(4, NAME, 502, Node550, NEUTRAL_REACTION);
    giq_option(4, NAME, 503, Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, 504, Node999, NEUTRAL_REACTION);
end

procedure Node550
begin
    Reply(550);
    giq_option(4, NAME, 551, Node600, NEUTRAL_REACTION);
end

procedure Node600
begin
    Reply(600);
    set_local_var(6, 1);
    if (local_var(7) != 1) then begin
        giq_option(4, NAME, 601, Node650, NEUTRAL_REACTION);
    end
    if (local_var(8) != 1) then begin
        giq_option(4, NAME, 602, Node700, NEUTRAL_REACTION);
    end
    if (local_var(9) != 1) then begin
        giq_option(4, NAME, 603, Node750, NEUTRAL_REACTION);
    end
    if (local_var(10) != 1) then begin
        giq_option(4, NAME, 604, Node850, NEUTRAL_REACTION);
    end
    if (local_var(11) != 1) then begin
        giq_option(4, NAME, 605, Node900, NEUTRAL_REACTION);
    end
    if ((dude_iq < 7) and (local_var(12) != 1)) then begin
        giq_option(4, NAME, 606, Node950, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 607, Node999, NEUTRAL_REACTION);
end

procedure Node650
begin
    Reply(650);
    set_local_var(7, 1);
    giq_option(4, NAME, 651, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 652, Node999, NEUTRAL_REACTION);
end

procedure Node700
begin
    Reply(700);
    set_local_var(8, 1);
    giq_option(4, NAME, 701, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 702, Node999, NEUTRAL_REACTION);
end

procedure Node750
begin
    Reply(750);
    set_local_var(9, 1);
    giq_option(6, NAME, 751, Node800, NEUTRAL_REACTION);
    giq_option(4, NAME, 752, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 753, Node999, NEUTRAL_REACTION);
end

procedure Node800
begin
    Reply(800);
    giq_option(4, NAME, 801, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 802, Node999, NEUTRAL_REACTION);
end

procedure Node850
begin
    Reply(850);
    set_local_var(10, 1);
    giq_option(4, NAME, 851, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 852, Node999, NEUTRAL_REACTION);
end

procedure Node900
begin
    Reply(900);
    set_local_var(11, 1);
    giq_option(4, NAME, 901, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 902, Node999, NEUTRAL_REACTION);
end

procedure Node950
begin
    Reply(950);
    set_local_var(12, 1);
    giq_option(4, NAME, 951, Node999, NEUTRAL_REACTION);
end

procedure Node1000
begin
    Reply(1000);
    giq_option(4, NAME, 1001, Node600, NEUTRAL_REACTION);
    giq_option(4, NAME, 1002, Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, 1003, Node999, NEUTRAL_REACTION);
end

procedure Node1050
begin
    Reply(random(1050, 1055));
    if (dude_skill(SKILL_SPEECH) > 60) then begin
        giq_option(4, NAME, 1056, Node1150, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 1056, Node1100, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1057, Node999, NEUTRAL_REACTION);
end

procedure Node1100
begin
    Reply(1100);
    set_local_var(14, 1);
    giq_option(4, NAME, 1101, Node999, NEUTRAL_REACTION);
end

procedure Node1150
begin
    Reply(1150);
    set_local_var(14, 1);
    giq_option(4, NAME, 1151, Node1200, NEUTRAL_REACTION);
end

procedure Node1200
begin
    if (dude_gender == 0) then begin
        Reply(1200);
    end
    if (dude_gender == 1) then begin
        Reply(1201);
    end
    set_local_var(13, 1);
    item_caps_adjust(dude_obj, -50);
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 2);
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    giq_option(4, NAME, 1202, Node999noise, NEUTRAL_REACTION);
end

procedure Node1250
begin
    Reply(1250);
    if ((dude_skill(SKILL_SPEECH) >= 100) and obj_carrying_pid_obj(dude_obj, 537)) then begin
        giq_option(4, NAME, 1251 + (dude_gender == 1), Node1300, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 1253, Node999, NEUTRAL_REACTION);
end

procedure Node1300
begin
    Reply(1300);
    giq_option(4, NAME, 1301, Node1350, NEUTRAL_REACTION);
end

procedure Node1350
begin
    Reply(1350);
    giq_option(4, NAME, 1351, Node999poison, NEUTRAL_REACTION);
end
