variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable lPartyWornArmor;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable toRemove_qty;

procedure div(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure damage_p_proc;
procedure combat_p_proc;
procedure destroy_p_proc;
procedure push_p_proc;

variable talking_float;
variable dialog_loop;
variable loop_numbers;
variable leaving;
variable temp_critter;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777729) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777729)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777779) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 32) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777779)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777811) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 64) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777811)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777812) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777812)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777813) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777813)) <= 5) then begin
            return 1;
        end
    end
    if ((party_member_obj(16777814) != 0) and ((global_var(GVAR_PTR_PARTY_MEMBER_ACTIONS) bwand 128) == 0)) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777814)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777748) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777748)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777293) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777293)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778017) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778017)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778016) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778016)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778049) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778049)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778050) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778050)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16778051) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16778051)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure div(variable arg0, variable arg1)
begin
    if (0 > arg0) then begin
        return -(-arg0 / arg1);
    end
    return arg0 / arg1;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
    if ((global_var(GVAR_ENEMY_SEDIT) == 1) and (cur_map_index != MAP_SED_ZTR)) then begin
        if (obj_can_see_obj(self_obj, dude_obj) or obj_can_hear_obj(self_obj, dude_obj)) then begin
            attack(dude_obj);
        end
    end
    if ((global_var(GVAR_ENEMY_LOST_QUARTER) > 2) and (CUR_MAP_SED_ZTR)) then begin
        if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                global_temp := (global_temp + 1) % 6;
                while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                    debug_msg("flee loop: rot == " + global_temp);
                    animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                    global_temp := (global_temp + 1) % 6;
                end
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if ((CUR_MAP_SED_ZTR) and ((global_var(GVAR_ENEMY_RODRIGUES) == 1) or (global_var(GVAR_ENEMY_LOST_QUARTER) > 0))) then begin
        if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                global_temp := (global_temp + 1) % 6;
                while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                    debug_msg("flee loop: rot == " + global_temp);
                    animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                    global_temp := (global_temp + 1) % 6;
                end
            end
        end
    end
    else begin
        if (party_member_obj(16777812) != 0) then begin
            if (dude_gender == 0) then begin
                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(350, 356)), FLOAT_MSG_YELLOW);
            end
            if (dude_gender == 1) then begin
                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(352, 358)), FLOAT_MSG_YELLOW);
            end
        end
        else begin
            if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 3) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 348) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 349) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 232)) then begin
                if (self_gender == 0) then begin
                    float_msg(self_obj, message_str(SCRIPT_SOBYV, random(340, 345)), FLOAT_MSG_YELLOW);
                end
                if (self_gender == 1) then begin
                    float_msg(self_obj, message_str(SCRIPT_SOBYV, random(341, 346)), FLOAT_MSG_YELLOW);
                end
            end
            else begin
                while (dialog_loop == 0) do begin
                    talking_float := random(0, 24);
                    loop_numbers := loop_numbers + 1;
                    if ((talking_float >= 0) and (talking_float <= 5) or (loop_numbers == 7)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(300, 305)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float == 6) and (CUR_MAP_SED_MHUB)) then begin
                        if (self_gender == 0) then begin
                            float_msg(self_obj, message_str(SCRIPT_SOBYV, 306), FLOAT_MSG_YELLOW);
                        end
                        if (self_gender == 1) then begin
                            float_msg(self_obj, message_str(SCRIPT_SOBYV, 326), FLOAT_MSG_YELLOW);
                        end
                        dialog_loop := 1;
                    end
                    if ((talking_float == 7) and (cur_map_index != MAP_SED_MHUB) and (global_var(GVAR_QUEST_S_MIMI_CARAVAN) != 3) and (global_var(GVAR_QUEST_S_RODRIGUES_GHOULS) < 2)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, 307), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 8) and (talking_float <= 9) and (global_var(GVAR_QUEST_S_TYLER_SHERIFF) != 3)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(308, 309)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float == 10) and ((global_var(GVAR_QUEST_S_DAVID_KIDNAP_INVESTIGATION) >= 1) or (global_var(GVAR_QUEST_A_DAVID_KIDNAP_COMPLICITY) >= 4))) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, 310), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 11) and (talking_float <= 12) and (global_var(GVAR_SEDIT_TYLER_IS_SHERIFF) == 1)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(311, 312)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 13) and (talking_float <= 14) and (global_var(GVAR_QUEST_S_MIMI_RODRIGUES) == 3)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(313, 314)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float == 15) and (cur_map_index != MAP_SED_MHUB) and (global_var(GVAR_QUEST_S_MIMI_CARAVAN) == 3)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, 315), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float == 16) and (cur_map_index != MAP_SED_MHUB) and (global_var(GVAR_QUEST_S_RODRIGUES_GHOULS) == 3)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, 316), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 17) and (talking_float <= 18) and (global_var(GVAR_QUEST_S_KEVIN_MEETING) == 3)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(317, 318)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 19) and (talking_float <= 20) and (global_var(GVAR_QUEST_S_NICOL_CRATER) == 4)) then begin
                        float_msg(self_obj, message_str(SCRIPT_SOBYV, random(319, 320)), FLOAT_MSG_YELLOW);
                        dialog_loop := 1;
                    end
                    if ((talking_float >= 21) and (talking_float <= 24) and (global_var(GVAR_NEW_RENO_PRIZEFIGHTER) == 1)) then begin
                        if (self_gender == 0) then begin
                            if (dude_gender == 0) then begin
                                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(321, 324)), FLOAT_MSG_YELLOW);
                            end
                            if (dude_gender == 1) then begin
                                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(322, 325)), FLOAT_MSG_YELLOW);
                            end
                        end
                        if (self_gender == 1) then begin
                            if (dude_gender == 0) then begin
                                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(327, 331)), FLOAT_MSG_YELLOW);
                            end
                            if (dude_gender == 1) then begin
                                float_msg(self_obj, message_str(SCRIPT_SOBYV, random(329, 331)), FLOAT_MSG_YELLOW);
                            end
                        end
                        dialog_loop := 1;
                    end
                end
                dialog_loop := 0;
                loop_numbers := 0;
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_msg(message_str(SCRIPT_SOBYV, 100));
    end
    if (self_gender == 1) then begin
        display_msg(message_str(SCRIPT_SOBYV, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (self_gender == 0) then begin
        display_msg(message_str(SCRIPT_SOBYV, 200));
    end
    if (self_gender == 1) then begin
        display_msg(message_str(SCRIPT_SOBYV, 201));
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (not(anim_busy(self_obj)) and (obj_is_visible_flag(self_obj) == 1)) then begin
            reg_anim_func(2, self_obj);
            reg_anim_func(1, 1);
            animate_move_obj_to_tile(self_obj, tile_num_in_direction(local_var(6), random(0, 5), random(1, 5)), 0);
            reg_anim_func(3, 0);
        end
        rm_fixed_timer_event(self_obj, 1);
        add_timer_event(self_obj, game_ticks(random(15, 30)), 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 212);
    if (CUR_MAP_SED_ZTR) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_WIMPY_PEASANT);
    end
    else begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS);
    end
    if (not(is_loading_game)) then begin
        if (local_var(6) == 0) then begin
            set_local_var(6, tile_num(self_obj));
        end
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        anim(self_obj, 1000, random(0, 5));
        reg_anim_func(3, 0);
        if ((obj_is_visible_flag(self_obj) == 0) and (random(1, 5) == 5)) then begin
            set_obj_visibility(self_obj, 0);
        end
    end
    rm_fixed_timer_event(self_obj, 1);
    add_timer_event(self_obj, game_ticks(random(15, 30)), 1);
end

procedure map_exit_p_proc
begin
    if ((global_var(GVAR_SEDIT_DEAD_GANGSTERS) == 2) and (CUR_MAP_SED_ZTR)) then begin
        leaving := 1;
        destroy_object(self_obj);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (CUR_MAP_SED_ZTR) then begin
            set_global_var(GVAR_ENEMY_RODRIGUES, 1);
            if (global_var(GVAR_ENEMY_LOST_QUARTER) < 3) then begin
                set_global_var(GVAR_ENEMY_LOST_QUARTER, global_var(GVAR_ENEMY_LOST_QUARTER) + 1);
            end
        end
        else begin
            set_global_var(GVAR_ENEMY_SEDIT, 1);
        end
    end
end

procedure combat_p_proc
begin
    if ((fixed_param == 4) and (CUR_MAP_SED_ZTR) and ((global_var(GVAR_ENEMY_RODRIGUES) == 1) or (global_var(GVAR_ENEMY_LOST_QUARTER) > 0))) then begin
        critter_set_flee_state(self_obj, 1);
    end
end

procedure destroy_p_proc
begin
    if (CUR_MAP_SED_ZTR) then begin
        if (leaving != 1) then begin
            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
            debug_msg("Player gains " + -10 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (source_obj == dude_obj) then begin
            set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
            if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 1);
                set_global_var(GVAR_BERSERKER_REPUTATION, 0);
            end
            if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
                if (source_obj == dude_obj) then begin
                    set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                    set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                    debug_msg("Player gains " + -15 + " Karma Points.");
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                    set_global_var(GVAR_KARMA_DEFENDER, 0);
                    set_global_var(GVAR_KARMA_WANDERER, 0);
                    set_global_var(GVAR_KARMA_BETRAYER, 0);
                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                        set_global_var(GVAR_KARMA_WANDERER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                            end
                                            else begin
                                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                                end
                                                else begin
                                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    set_global_var(GVAR_TOWN_REP_SEDIT, global_var(GVAR_TOWN_REP_SEDIT) + -8);
                    debug_msg("Added " + -8 + " to Town Rep");
                end
            end
            if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
                set_global_var(GVAR_BERSERKER_REPUTATION, 1);
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
            end
            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
            debug_msg("Player gains " + -10 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            set_global_var(GVAR_TOWN_REP_SEDIT, global_var(GVAR_TOWN_REP_SEDIT) + -5);
            debug_msg("Added " + -5 + " to Town Rep");
        end
    end
    if (leaving != 1) then begin
        temp_critter := create_object_sid(obj_pid(self_obj), 0, 0, SCRIPT_SOBYV);
        set_obj_visibility(temp_critter, 1);
        move_to(temp_critter, local_var(6), elevation(self_obj));
    end
end

procedure push_p_proc
begin
end
