#ifndef __MAPS__
#define __MAPS__

// Generated automagically from Olympus2207.zip/data/maps.txt //

#define MAP_CITY1         (85)
#define MAP_CITY2         (86)
#define MAP_CITY3         (87)
#define MAP_COAST1        (88)
#define MAP_COAST2        (89)
#define MAP_DESERT1       (070)
#define MAP_DESERT10      (79)
#define MAP_DESERT2       (71)
#define MAP_DESERT3       (72)
#define MAP_DESERT4       (73)
#define MAP_DESERT5       (74)
#define MAP_DESERT6       (75)
#define MAP_DESERT7       (76)
#define MAP_DESERT8       (77)
#define MAP_DESERT9       (78)
#define MAP_FR2ND         (090)
#define MAP_FRHOUSE       (47)
#define MAP_LVCAVE        (37)
#define MAP_LVENTER       (32)
#define MAP_LVFILTER      (36)
#define MAP_LVROOMS       (34)
#define MAP_LVTECH        (35)
#define MAP_LVTRADE       (33)
#define MAP_MEADOW1       (080)
#define MAP_MEADOW2       (81)
#define MAP_MEADOW3       (82)
#define MAP_MEADOW4       (83)
#define MAP_MEADOW5       (84)
#define MAP_MOUNT1        (91)
#define MAP_MOUNT10       (100)
#define MAP_MOUNT2        (92)
#define MAP_MOUNT3        (93)
#define MAP_MOUNT4        (94)
#define MAP_MOUNT5        (95)
#define MAP_MOUNT6        (96)
#define MAP_MOUNT7        (97)
#define MAP_MOUNT8        (98)
#define MAP_MOUNT9        (99)
#define MAP_NW2FLOOR      (29)
#define MAP_NWBASE        (030)
#define MAP_NWENTER       (27)
#define MAP_NWSHOP        (28)
#define MAP_NWYARD        (31)
#define MAP_OACAVE        (46)
#define MAP_OAENTER       (44)
#define MAP_OAMAIN        (45)
#define MAP_OLENGNR       (59)
#define MAP_OLENTER       (55)
#define MAP_OLFINAL       (65)
#define MAP_OLHITECH      (62)
#define MAP_OLHORTON      (56)
#define MAP_OLORGNIC      (57)
#define MAP_OLPHYSIC      (61)
#define MAP_OLSERVER      (63)
#define MAP_OLSPAWN       (58)
#define MAP_OLTERASS      (060)
#define MAP_OLTOP         (64)
#define MAP_PNCITY01      (15)
#define MAP_PNCITY02      (16)
#define MAP_PNHALL        (14)
#define MAP_PNPASS        (12)
#define MAP_PNPLTFRM      (13)
#define MAP_PNUNDER       (17)
#define MAP_PSHOSPIT      (103)
#define MAP_PSMARKET      (102)
#define MAP_RBARENA       (39)
#define MAP_RBARENAF      (040)
#define MAP_RBFABRIC      (41)
#define MAP_RBFERM        (43)
#define MAP_RBMAIN        (38)
#define MAP_RBUNDER       (42)
#define MAP_RSCITY        (54)
#define MAP_RSENTER       (53)
#define MAP_SJBARAKS      (21)
#define MAP_SJBUNKER      (24)
#define MAP_SJCAVE        (26)
#define MAP_SJENTER       (18)
#define MAP_SJLABS        (23)
#define MAP_SJMAIN1       (19)
#define MAP_SJMAIN2       (101)
#define MAP_SJPLATO       (25)
#define MAP_SJREPAIR      (020)
#define MAP_SJSTORE       (22)
#define MAP_SPBIOLAB      (104)
#define MAP_SPCHIMER      (68)
#define MAP_SPHUNT        (67)
#define MAP_SPMEADOW      (69)
#define MAP_SPTROSTN      (66)
#define MAP_SPXBNDTS      (114)
#define MAP_SPXLMNRS      (113)
#define MAP_SXDREDD       (108)
#define MAP_SXELY         (110)
#define MAP_SXFIRFLY      (105)
#define MAP_SXMAX         (107)
#define MAP_SXROAD        (106)
#define MAP_SXSTRING      (112)
#define MAP_SXTANK        (109)
#define MAP_SXTOWN        (111)
#define MAP_TARCHIST      (9)
#define MAP_TAREXIT       (010)
#define MAP_TARTAR02      (11)
#define MAP_TARTAR03      (1)
#define MAP_TARTAR11      (2)
#define MAP_TARTAR12      (3)
#define MAP_TARTAR13      (4)
#define MAP_TARTAR22      (5)
#define MAP_TARTAR23      (6)
#define MAP_TARTAR32      (7)
#define MAP_TARTAR33      (8)
#define MAP_TIENTER       (050)
#define MAP_TISHOP        (51)
#define MAP_TIUNDER       (52)
#define MAP_WBBUNKER      (49)
#define MAP_WBENTER       (48)
#define MAP_02TEST        (0)
//
#define CUR_MAP_CITY1     (cur_map_index == MAP_CITY1)
#define CUR_MAP_CITY2     (cur_map_index == MAP_CITY2)
#define CUR_MAP_CITY3     (cur_map_index == MAP_CITY3)
#define CUR_MAP_COAST1    (cur_map_index == MAP_COAST1)
#define CUR_MAP_COAST2    (cur_map_index == MAP_COAST2)
#define CUR_MAP_DESERT1   (cur_map_index == MAP_DESERT1)
#define CUR_MAP_DESERT10  (cur_map_index == MAP_DESERT10)
#define CUR_MAP_DESERT2   (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT3   (cur_map_index == MAP_DESERT3)
#define CUR_MAP_DESERT4   (cur_map_index == MAP_DESERT4)
#define CUR_MAP_DESERT5   (cur_map_index == MAP_DESERT5)
#define CUR_MAP_DESERT6   (cur_map_index == MAP_DESERT6)
#define CUR_MAP_DESERT7   (cur_map_index == MAP_DESERT7)
#define CUR_MAP_DESERT8   (cur_map_index == MAP_DESERT8)
#define CUR_MAP_DESERT9   (cur_map_index == MAP_DESERT9)
#define CUR_MAP_FR2ND     (cur_map_index == MAP_FR2ND)
#define CUR_MAP_FRHOUSE   (cur_map_index == MAP_FRHOUSE)
#define CUR_MAP_LVCAVE    (cur_map_index == MAP_LVCAVE)
#define CUR_MAP_LVENTER   (cur_map_index == MAP_LVENTER)
#define CUR_MAP_LVFILTER  (cur_map_index == MAP_LVFILTER)
#define CUR_MAP_LVROOMS   (cur_map_index == MAP_LVROOMS)
#define CUR_MAP_LVTECH    (cur_map_index == MAP_LVTECH)
#define CUR_MAP_LVTRADE   (cur_map_index == MAP_LVTRADE)
#define CUR_MAP_MEADOW1   (cur_map_index == MAP_MEADOW1)
#define CUR_MAP_MEADOW2   (cur_map_index == MAP_MEADOW2)
#define CUR_MAP_MEADOW3   (cur_map_index == MAP_MEADOW3)
#define CUR_MAP_MEADOW4   (cur_map_index == MAP_MEADOW4)
#define CUR_MAP_MEADOW5   (cur_map_index == MAP_MEADOW5)
#define CUR_MAP_MOUNT1    (cur_map_index == MAP_MOUNT1)
#define CUR_MAP_MOUNT10   (cur_map_index == MAP_MOUNT10)
#define CUR_MAP_MOUNT2    (cur_map_index == MAP_MOUNT2)
#define CUR_MAP_MOUNT3    (cur_map_index == MAP_MOUNT3)
#define CUR_MAP_MOUNT4    (cur_map_index == MAP_MOUNT4)
#define CUR_MAP_MOUNT5    (cur_map_index == MAP_MOUNT5)
#define CUR_MAP_MOUNT6    (cur_map_index == MAP_MOUNT6)
#define CUR_MAP_MOUNT7    (cur_map_index == MAP_MOUNT7)
#define CUR_MAP_MOUNT8    (cur_map_index == MAP_MOUNT8)
#define CUR_MAP_MOUNT9    (cur_map_index == MAP_MOUNT9)
#define CUR_MAP_NW2FLOOR  (cur_map_index == MAP_NW2FLOOR)
#define CUR_MAP_NWBASE    (cur_map_index == MAP_NWBASE)
#define CUR_MAP_NWENTER   (cur_map_index == MAP_NWENTER)
#define CUR_MAP_NWSHOP    (cur_map_index == MAP_NWSHOP)
#define CUR_MAP_NWYARD    (cur_map_index == MAP_NWYARD)
#define CUR_MAP_OACAVE    (cur_map_index == MAP_OACAVE)
#define CUR_MAP_OAENTER   (cur_map_index == MAP_OAENTER)
#define CUR_MAP_OAMAIN    (cur_map_index == MAP_OAMAIN)
#define CUR_MAP_OLENGNR   (cur_map_index == MAP_OLENGNR)
#define CUR_MAP_OLENTER   (cur_map_index == MAP_OLENTER)
#define CUR_MAP_OLFINAL   (cur_map_index == MAP_OLFINAL)
#define CUR_MAP_OLHITECH  (cur_map_index == MAP_OLHITECH)
#define CUR_MAP_OLHORTON  (cur_map_index == MAP_OLHORTON)
#define CUR_MAP_OLORGNIC  (cur_map_index == MAP_OLORGNIC)
#define CUR_MAP_OLPHYSIC  (cur_map_index == MAP_OLPHYSIC)
#define CUR_MAP_OLSERVER  (cur_map_index == MAP_OLSERVER)
#define CUR_MAP_OLSPAWN   (cur_map_index == MAP_OLSPAWN)
#define CUR_MAP_OLTERASS  (cur_map_index == MAP_OLTERASS)
#define CUR_MAP_OLTOP     (cur_map_index == MAP_OLTOP)
#define CUR_MAP_PNCITY01  (cur_map_index == MAP_PNCITY01)
#define CUR_MAP_PNCITY02  (cur_map_index == MAP_PNCITY02)
#define CUR_MAP_PNHALL    (cur_map_index == MAP_PNHALL)
#define CUR_MAP_PNPASS    (cur_map_index == MAP_PNPASS)
#define CUR_MAP_PNPLTFRM  (cur_map_index == MAP_PNPLTFRM)
#define CUR_MAP_PNUNDER   (cur_map_index == MAP_PNUNDER)
#define CUR_MAP_PSHOSPIT  (cur_map_index == MAP_PSHOSPIT)
#define CUR_MAP_PSMARKET  (cur_map_index == MAP_PSMARKET)
#define CUR_MAP_RBARENA   (cur_map_index == MAP_RBARENA)
#define CUR_MAP_RBARENAF  (cur_map_index == MAP_RBARENAF)
#define CUR_MAP_RBFABRIC  (cur_map_index == MAP_RBFABRIC)
#define CUR_MAP_RBFERM    (cur_map_index == MAP_RBFERM)
#define CUR_MAP_RBMAIN    (cur_map_index == MAP_RBMAIN)
#define CUR_MAP_RBUNDER   (cur_map_index == MAP_RBUNDER)
#define CUR_MAP_RSCITY    (cur_map_index == MAP_RSCITY)
#define CUR_MAP_RSENTER   (cur_map_index == MAP_RSENTER)
#define CUR_MAP_SJBARAKS  (cur_map_index == MAP_SJBARAKS)
#define CUR_MAP_SJBUNKER  (cur_map_index == MAP_SJBUNKER)
#define CUR_MAP_SJCAVE    (cur_map_index == MAP_SJCAVE)
#define CUR_MAP_SJENTER   (cur_map_index == MAP_SJENTER)
#define CUR_MAP_SJLABS    (cur_map_index == MAP_SJLABS)
#define CUR_MAP_SJMAIN1   (cur_map_index == MAP_SJMAIN1)
#define CUR_MAP_SJMAIN2   (cur_map_index == MAP_SJMAIN2)
#define CUR_MAP_SJPLATO   (cur_map_index == MAP_SJPLATO)
#define CUR_MAP_SJREPAIR  (cur_map_index == MAP_SJREPAIR)
#define CUR_MAP_SJSTORE   (cur_map_index == MAP_SJSTORE)
#define CUR_MAP_SPBIOLAB  (cur_map_index == MAP_SPBIOLAB)
#define CUR_MAP_SPCHIMER  (cur_map_index == MAP_SPCHIMER)
#define CUR_MAP_SPHUNT    (cur_map_index == MAP_SPHUNT)
#define CUR_MAP_SPMEADOW  (cur_map_index == MAP_SPMEADOW)
#define CUR_MAP_SPTROSTN  (cur_map_index == MAP_SPTROSTN)
#define CUR_MAP_SPXBNDTS  (cur_map_index == MAP_SPXBNDTS)
#define CUR_MAP_SPXLMNRS  (cur_map_index == MAP_SPXLMNRS)
#define CUR_MAP_SXDREDD   (cur_map_index == MAP_SXDREDD)
#define CUR_MAP_SXELY     (cur_map_index == MAP_SXELY)
#define CUR_MAP_SXFIRFLY  (cur_map_index == MAP_SXFIRFLY)
#define CUR_MAP_SXMAX     (cur_map_index == MAP_SXMAX)
#define CUR_MAP_SXROAD    (cur_map_index == MAP_SXROAD)
#define CUR_MAP_SXSTRING  (cur_map_index == MAP_SXSTRING)
#define CUR_MAP_SXTANK    (cur_map_index == MAP_SXTANK)
#define CUR_MAP_SXTOWN    (cur_map_index == MAP_SXTOWN)
#define CUR_MAP_TARCHIST  (cur_map_index == MAP_TARCHIST)
#define CUR_MAP_TAREXIT   (cur_map_index == MAP_TAREXIT)
#define CUR_MAP_TARTAR02  (cur_map_index == MAP_TARTAR02)
#define CUR_MAP_TARTAR03  (cur_map_index == MAP_TARTAR03)
#define CUR_MAP_TARTAR11  (cur_map_index == MAP_TARTAR11)
#define CUR_MAP_TARTAR12  (cur_map_index == MAP_TARTAR12)
#define CUR_MAP_TARTAR13  (cur_map_index == MAP_TARTAR13)
#define CUR_MAP_TARTAR22  (cur_map_index == MAP_TARTAR22)
#define CUR_MAP_TARTAR23  (cur_map_index == MAP_TARTAR23)
#define CUR_MAP_TARTAR32  (cur_map_index == MAP_TARTAR32)
#define CUR_MAP_TARTAR33  (cur_map_index == MAP_TARTAR33)
#define CUR_MAP_TIENTER   (cur_map_index == MAP_TIENTER)
#define CUR_MAP_TISHOP    (cur_map_index == MAP_TISHOP)
#define CUR_MAP_TIUNDER   (cur_map_index == MAP_TIUNDER)
#define CUR_MAP_WBBUNKER  (cur_map_index == MAP_WBBUNKER)
#define CUR_MAP_WBENTER   (cur_map_index == MAP_WBENTER)
#define CUR_MAP_02TEST    (cur_map_index == MAP_02TEST)

#endif // __MAPS__ //
