#ifndef __MAPS__
#define __MAPS__

// Generated automagically from DemoInFO2.zip/data/MAPS.TXT //

#define MAP_ARBRIDGE      (5)
#define MAP_ARCAVES       (3)
#define MAP_ARDEAD        (127)
#define MAP_ARGARDEN      (35)
#define MAP_ARTEMPLE      (126)
#define MAP_ARVILLAG      (4)
#define MAP_BHRNDDST      (94)
#define MAP_BHRNDMNT      (95)
#define MAP_BROKEN1       (78)
#define MAP_BROKEN2       (79)
#define MAP_CARDESRT      (53)
#define MAP_CAVE0         (69)
#define MAP_CAVE1         (070)
#define MAP_CAVE2         (71)
#define MAP_CAVE3         (72)
#define MAP_CAVE4         (73)
#define MAP_CAVE5         (080)
#define MAP_CAVE6         (119)
#define MAP_CAVE7         (120)
#define MAP_CITY1         (68)
#define MAP_CITY2         (125)
#define MAP_CITY3         (141)
#define MAP_CITY4         (142)
#define MAP_CITY5         (143)
#define MAP_CITY6         (144)
#define MAP_CITY7         (145)
#define MAP_CITY8         (146)
#define MAP_COAST1        (76)
#define MAP_COAST10       (110)
#define MAP_COAST11       (111)
#define MAP_COAST2        (77)
#define MAP_COAST3        (85)
#define MAP_COAST4        (86)
#define MAP_COAST5        (87)
#define MAP_COAST6        (88)
#define MAP_COAST7        (89)
#define MAP_COAST8        (090)
#define MAP_COAST9        (91)
#define MAP_DENBUS1       (6)
#define MAP_DENBUS2       (7)
#define MAP_DENRES1       (8)
#define MAP_DEPOLV1       (27)
#define MAP_DEPOLVA       (28)
#define MAP_DEPOLVB       (29)
#define MAP_DESERT1       (0)
#define MAP_DESERT2       (1)
#define MAP_DESERT3       (2)
#define MAP_DESERT4       (81)
#define MAP_DESERT5       (82)
#define MAP_DESERT6       (83)
#define MAP_DESERT7       (84)
#define MAP_DESERT8       (113)
#define MAP_DESERT9       (114)
#define MAP_DESRT10       (115)
#define MAP_DESRT11       (116)
#define MAP_DESRT12       (117)
#define MAP_DNSLVRUN      (52)
#define MAP_DSRT13        (118)
#define MAP_ENCDET        (128)
#define MAP_ENCDOCK       (129)
#define MAP_ENCFITE       (130)
#define MAP_ENCGD         (131)
#define MAP_ENCPRES       (132)
#define MAP_ENCRCTR       (133)
#define MAP_ENCTRP        (134)
#define MAP_GAMMOVIE      (149)
#define MAP_GECKJUNK      (33)
#define MAP_GECKPWPL      (32)
#define MAP_GECKSETL      (31)
#define MAP_GECKTUNL      (34)
#define MAP_GSTCAV1       (25)
#define MAP_GSTCAV2       (26)
#define MAP_GSTFARM       (24)
#define MAP_JUNKDEMO      (151)
#define MAP_KLACANYN      (48)
#define MAP_KLADWTWN      (9)
#define MAP_KLAGRAZ       (14)
#define MAP_KLAMALL       (010)
#define MAP_KLARATCV      (11)
#define MAP_KLATOXCV      (12)
#define MAP_KLATRAP       (13)
#define MAP_MBASE12       (49)
#define MAP_MBASE34       (050)
#define MAP_MBCLOSE       (51)
#define MAP_MODBRAH       (020)
#define MAP_MODGARD       (21)
#define MAP_MODINN        (19)
#define MAP_MODMAIN       (18)
#define MAP_MODSHIT       (22)
#define MAP_MODWELL       (23)
#define MAP_MOUNTN1       (74)
#define MAP_MOUNTN2       (75)
#define MAP_MOUNTN3       (121)
#define MAP_MOUNTN4       (122)
#define MAP_MOUNTN5       (123)
#define MAP_MOUNTN6       (124)
#define MAP_NAVARRO       (109)
#define MAP_NCR1          (42)
#define MAP_NCR2          (43)
#define MAP_NCR3          (44)
#define MAP_NCR4          (45)
#define MAP_NCRENT        (46)
#define MAP_NCREX         (47)
#define MAP_NEWR1         (54)
#define MAP_NEWR2         (55)
#define MAP_NEWR3         (56)
#define MAP_NEWR4         (57)
#define MAP_NEWRBA        (61)
#define MAP_NEWRCS        (58)
#define MAP_NEWRGO        (59)
#define MAP_NEWRST        (060)
#define MAP_NEWRVB        (147)
#define MAP_RAIDERS1      (92)
#define MAP_RAIDERS2      (93)
#define MAP_REDDOWN       (64)
#define MAP_REDDTUN       (66)
#define MAP_REDMENT       (65)
#define MAP_REDMTUN       (67)
#define MAP_REDWAME       (62)
#define MAP_REDWAN1       (63)
#define MAP_RNDBESS       (150)
#define MAP_RNDBHEAD      (98)
#define MAP_RNDBRIDG      (101)
#define MAP_RNDCAFE       (102)
#define MAP_RNDEXCOW      (108)
#define MAP_RNDFORVR      (105)
#define MAP_RNDHOLY1      (103)
#define MAP_RNDHOLY2      (104)
#define MAP_RNDPARIH      (107)
#define MAP_RNDSHUTL      (99)
#define MAP_RNDTINWD      (97)
#define MAP_RNDTOXIC      (106)
#define MAP_RNDUVILG      (100)
#define MAP_RNDWHALE      (96)
#define MAP_SFCHINA       (137)
#define MAP_SFCHINA2      (148)
#define MAP_SFDOCK        (136)
#define MAP_SFELRONB      (140)
#define MAP_SFSHUTL1      (138)
#define MAP_SFSHUTL2      (139)
#define MAP_SFTANKER      (135)
#define MAP_V13ENT        (41)
#define MAP_V15ENT        (37)
#define MAP_V15ENTB       (38)
#define MAP_V15SENT       (39)
#define MAP_VAULT13       (040)
#define MAP_VAULT15       (36)
#define MAP_VCTYCOCL      (17)
#define MAP_VCTYCTYD      (15)
#define MAP_VCTYDWTN      (16)
#define MAP_VCTYVLT       (030)
#define MAP_07DESERT      (112)
//
#define CUR_MAP_ARBRIDGE  (cur_map_index == MAP_ARBRIDGE)
#define CUR_MAP_ARCAVES   (cur_map_index == MAP_ARCAVES)
#define CUR_MAP_ARDEAD    (cur_map_index == MAP_ARDEAD)
#define CUR_MAP_ARGARDEN  (cur_map_index == MAP_ARGARDEN)
#define CUR_MAP_ARTEMPLE  (cur_map_index == MAP_ARTEMPLE)
#define CUR_MAP_ARVILLAG  (cur_map_index == MAP_ARVILLAG)
#define CUR_MAP_BHRNDDST  (cur_map_index == MAP_BHRNDDST)
#define CUR_MAP_BHRNDMNT  (cur_map_index == MAP_BHRNDMNT)
#define CUR_MAP_BROKEN1   (cur_map_index == MAP_BROKEN1)
#define CUR_MAP_BROKEN2   (cur_map_index == MAP_BROKEN2)
#define CUR_MAP_CARDESRT  (cur_map_index == MAP_CARDESRT)
#define CUR_MAP_CAVE0     (cur_map_index == MAP_CAVE0)
#define CUR_MAP_CAVE1     (cur_map_index == MAP_CAVE1)
#define CUR_MAP_CAVE2     (cur_map_index == MAP_CAVE2)
#define CUR_MAP_CAVE3     (cur_map_index == MAP_CAVE3)
#define CUR_MAP_CAVE4     (cur_map_index == MAP_CAVE4)
#define CUR_MAP_CAVE5     (cur_map_index == MAP_CAVE5)
#define CUR_MAP_CAVE6     (cur_map_index == MAP_CAVE6)
#define CUR_MAP_CAVE7     (cur_map_index == MAP_CAVE7)
#define CUR_MAP_CITY1     (cur_map_index == MAP_CITY1)
#define CUR_MAP_CITY2     (cur_map_index == MAP_CITY2)
#define CUR_MAP_CITY3     (cur_map_index == MAP_CITY3)
#define CUR_MAP_CITY4     (cur_map_index == MAP_CITY4)
#define CUR_MAP_CITY5     (cur_map_index == MAP_CITY5)
#define CUR_MAP_CITY6     (cur_map_index == MAP_CITY6)
#define CUR_MAP_CITY7     (cur_map_index == MAP_CITY7)
#define CUR_MAP_CITY8     (cur_map_index == MAP_CITY8)
#define CUR_MAP_COAST1    (cur_map_index == MAP_COAST1)
#define CUR_MAP_COAST10   (cur_map_index == MAP_COAST10)
#define CUR_MAP_COAST11   (cur_map_index == MAP_COAST11)
#define CUR_MAP_COAST2    (cur_map_index == MAP_COAST2)
#define CUR_MAP_COAST3    (cur_map_index == MAP_COAST3)
#define CUR_MAP_COAST4    (cur_map_index == MAP_COAST4)
#define CUR_MAP_COAST5    (cur_map_index == MAP_COAST5)
#define CUR_MAP_COAST6    (cur_map_index == MAP_COAST6)
#define CUR_MAP_COAST7    (cur_map_index == MAP_COAST7)
#define CUR_MAP_COAST8    (cur_map_index == MAP_COAST8)
#define CUR_MAP_COAST9    (cur_map_index == MAP_COAST9)
#define CUR_MAP_DENBUS1   (cur_map_index == MAP_DENBUS1)
#define CUR_MAP_DENBUS2   (cur_map_index == MAP_DENBUS2)
#define CUR_MAP_DENRES1   (cur_map_index == MAP_DENRES1)
#define CUR_MAP_DEPOLV1   (cur_map_index == MAP_DEPOLV1)
#define CUR_MAP_DEPOLVA   (cur_map_index == MAP_DEPOLVA)
#define CUR_MAP_DEPOLVB   (cur_map_index == MAP_DEPOLVB)
#define CUR_MAP_DESERT1   (cur_map_index == MAP_DESERT1)
#define CUR_MAP_DESERT2   (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT3   (cur_map_index == MAP_DESERT3)
#define CUR_MAP_DESERT4   (cur_map_index == MAP_DESERT4)
#define CUR_MAP_DESERT5   (cur_map_index == MAP_DESERT5)
#define CUR_MAP_DESERT6   (cur_map_index == MAP_DESERT6)
#define CUR_MAP_DESERT7   (cur_map_index == MAP_DESERT7)
#define CUR_MAP_DESERT8   (cur_map_index == MAP_DESERT8)
#define CUR_MAP_DESERT9   (cur_map_index == MAP_DESERT9)
#define CUR_MAP_DESRT10   (cur_map_index == MAP_DESRT10)
#define CUR_MAP_DESRT11   (cur_map_index == MAP_DESRT11)
#define CUR_MAP_DESRT12   (cur_map_index == MAP_DESRT12)
#define CUR_MAP_DNSLVRUN  (cur_map_index == MAP_DNSLVRUN)
#define CUR_MAP_DSRT13    (cur_map_index == MAP_DSRT13)
#define CUR_MAP_ENCDET    (cur_map_index == MAP_ENCDET)
#define CUR_MAP_ENCDOCK   (cur_map_index == MAP_ENCDOCK)
#define CUR_MAP_ENCFITE   (cur_map_index == MAP_ENCFITE)
#define CUR_MAP_ENCGD     (cur_map_index == MAP_ENCGD)
#define CUR_MAP_ENCPRES   (cur_map_index == MAP_ENCPRES)
#define CUR_MAP_ENCRCTR   (cur_map_index == MAP_ENCRCTR)
#define CUR_MAP_ENCTRP    (cur_map_index == MAP_ENCTRP)
#define CUR_MAP_GAMMOVIE  (cur_map_index == MAP_GAMMOVIE)
#define CUR_MAP_GECKJUNK  (cur_map_index == MAP_GECKJUNK)
#define CUR_MAP_GECKPWPL  (cur_map_index == MAP_GECKPWPL)
#define CUR_MAP_GECKSETL  (cur_map_index == MAP_GECKSETL)
#define CUR_MAP_GECKTUNL  (cur_map_index == MAP_GECKTUNL)
#define CUR_MAP_GSTCAV1   (cur_map_index == MAP_GSTCAV1)
#define CUR_MAP_GSTCAV2   (cur_map_index == MAP_GSTCAV2)
#define CUR_MAP_GSTFARM   (cur_map_index == MAP_GSTFARM)
#define CUR_MAP_JUNKDEMO  (cur_map_index == MAP_JUNKDEMO)
#define CUR_MAP_KLACANYN  (cur_map_index == MAP_KLACANYN)
#define CUR_MAP_KLADWTWN  (cur_map_index == MAP_KLADWTWN)
#define CUR_MAP_KLAGRAZ   (cur_map_index == MAP_KLAGRAZ)
#define CUR_MAP_KLAMALL   (cur_map_index == MAP_KLAMALL)
#define CUR_MAP_KLARATCV  (cur_map_index == MAP_KLARATCV)
#define CUR_MAP_KLATOXCV  (cur_map_index == MAP_KLATOXCV)
#define CUR_MAP_KLATRAP   (cur_map_index == MAP_KLATRAP)
#define CUR_MAP_MBASE12   (cur_map_index == MAP_MBASE12)
#define CUR_MAP_MBASE34   (cur_map_index == MAP_MBASE34)
#define CUR_MAP_MBCLOSE   (cur_map_index == MAP_MBCLOSE)
#define CUR_MAP_MODBRAH   (cur_map_index == MAP_MODBRAH)
#define CUR_MAP_MODGARD   (cur_map_index == MAP_MODGARD)
#define CUR_MAP_MODINN    (cur_map_index == MAP_MODINN)
#define CUR_MAP_MODMAIN   (cur_map_index == MAP_MODMAIN)
#define CUR_MAP_MODSHIT   (cur_map_index == MAP_MODSHIT)
#define CUR_MAP_MODWELL   (cur_map_index == MAP_MODWELL)
#define CUR_MAP_MOUNTN1   (cur_map_index == MAP_MOUNTN1)
#define CUR_MAP_MOUNTN2   (cur_map_index == MAP_MOUNTN2)
#define CUR_MAP_MOUNTN3   (cur_map_index == MAP_MOUNTN3)
#define CUR_MAP_MOUNTN4   (cur_map_index == MAP_MOUNTN4)
#define CUR_MAP_MOUNTN5   (cur_map_index == MAP_MOUNTN5)
#define CUR_MAP_MOUNTN6   (cur_map_index == MAP_MOUNTN6)
#define CUR_MAP_NAVARRO   (cur_map_index == MAP_NAVARRO)
#define CUR_MAP_NCR1      (cur_map_index == MAP_NCR1)
#define CUR_MAP_NCR2      (cur_map_index == MAP_NCR2)
#define CUR_MAP_NCR3      (cur_map_index == MAP_NCR3)
#define CUR_MAP_NCR4      (cur_map_index == MAP_NCR4)
#define CUR_MAP_NCRENT    (cur_map_index == MAP_NCRENT)
#define CUR_MAP_NCREX     (cur_map_index == MAP_NCREX)
#define CUR_MAP_NEWR1     (cur_map_index == MAP_NEWR1)
#define CUR_MAP_NEWR2     (cur_map_index == MAP_NEWR2)
#define CUR_MAP_NEWR3     (cur_map_index == MAP_NEWR3)
#define CUR_MAP_NEWR4     (cur_map_index == MAP_NEWR4)
#define CUR_MAP_NEWRBA    (cur_map_index == MAP_NEWRBA)
#define CUR_MAP_NEWRCS    (cur_map_index == MAP_NEWRCS)
#define CUR_MAP_NEWRGO    (cur_map_index == MAP_NEWRGO)
#define CUR_MAP_NEWRST    (cur_map_index == MAP_NEWRST)
#define CUR_MAP_NEWRVB    (cur_map_index == MAP_NEWRVB)
#define CUR_MAP_RAIDERS1  (cur_map_index == MAP_RAIDERS1)
#define CUR_MAP_RAIDERS2  (cur_map_index == MAP_RAIDERS2)
#define CUR_MAP_REDDOWN   (cur_map_index == MAP_REDDOWN)
#define CUR_MAP_REDDTUN   (cur_map_index == MAP_REDDTUN)
#define CUR_MAP_REDMENT   (cur_map_index == MAP_REDMENT)
#define CUR_MAP_REDMTUN   (cur_map_index == MAP_REDMTUN)
#define CUR_MAP_REDWAME   (cur_map_index == MAP_REDWAME)
#define CUR_MAP_REDWAN1   (cur_map_index == MAP_REDWAN1)
#define CUR_MAP_RNDBESS   (cur_map_index == MAP_RNDBESS)
#define CUR_MAP_RNDBHEAD  (cur_map_index == MAP_RNDBHEAD)
#define CUR_MAP_RNDBRIDG  (cur_map_index == MAP_RNDBRIDG)
#define CUR_MAP_RNDCAFE   (cur_map_index == MAP_RNDCAFE)
#define CUR_MAP_RNDEXCOW  (cur_map_index == MAP_RNDEXCOW)
#define CUR_MAP_RNDFORVR  (cur_map_index == MAP_RNDFORVR)
#define CUR_MAP_RNDHOLY1  (cur_map_index == MAP_RNDHOLY1)
#define CUR_MAP_RNDHOLY2  (cur_map_index == MAP_RNDHOLY2)
#define CUR_MAP_RNDPARIH  (cur_map_index == MAP_RNDPARIH)
#define CUR_MAP_RNDSHUTL  (cur_map_index == MAP_RNDSHUTL)
#define CUR_MAP_RNDTINWD  (cur_map_index == MAP_RNDTINWD)
#define CUR_MAP_RNDTOXIC  (cur_map_index == MAP_RNDTOXIC)
#define CUR_MAP_RNDUVILG  (cur_map_index == MAP_RNDUVILG)
#define CUR_MAP_RNDWHALE  (cur_map_index == MAP_RNDWHALE)
#define CUR_MAP_SFCHINA   (cur_map_index == MAP_SFCHINA)
#define CUR_MAP_SFCHINA2  (cur_map_index == MAP_SFCHINA2)
#define CUR_MAP_SFDOCK    (cur_map_index == MAP_SFDOCK)
#define CUR_MAP_SFELRONB  (cur_map_index == MAP_SFELRONB)
#define CUR_MAP_SFSHUTL1  (cur_map_index == MAP_SFSHUTL1)
#define CUR_MAP_SFSHUTL2  (cur_map_index == MAP_SFSHUTL2)
#define CUR_MAP_SFTANKER  (cur_map_index == MAP_SFTANKER)
#define CUR_MAP_V13ENT    (cur_map_index == MAP_V13ENT)
#define CUR_MAP_V15ENT    (cur_map_index == MAP_V15ENT)
#define CUR_MAP_V15ENTB   (cur_map_index == MAP_V15ENTB)
#define CUR_MAP_V15SENT   (cur_map_index == MAP_V15SENT)
#define CUR_MAP_VAULT13   (cur_map_index == MAP_VAULT13)
#define CUR_MAP_VAULT15   (cur_map_index == MAP_VAULT15)
#define CUR_MAP_VCTYCOCL  (cur_map_index == MAP_VCTYCOCL)
#define CUR_MAP_VCTYCTYD  (cur_map_index == MAP_VCTYCTYD)
#define CUR_MAP_VCTYDWTN  (cur_map_index == MAP_VCTYDWTN)
#define CUR_MAP_VCTYVLT   (cur_map_index == MAP_VCTYVLT)
#define CUR_MAP_07DESERT  (cur_map_index == MAP_07DESERT)

#endif // __MAPS__ //
