#ifndef __MAPS__
#define __MAPS__

// Generated automagically from MegaMod.zip/data/MAPS.TXT //

#define MAP_A10            (198)
#define MAP_A12            (179)
#define MAP_ABANDON1       (250)
#define MAP_ABANDON2       (251)
#define MAP_ABANDON3       (252)
#define MAP_ABBASEM        (181)
#define MAP_ABBEY          (155)
#define MAP_ABBEY          (230)
#define MAP_ABBEY1         (180)
#define MAP_ABUNDGR        (182)
#define MAP_ADITUMB        (210)
#define MAP_ADITUMC        (209)
#define MAP_ARBRIDGE       (5)
#define MAP_ARCAVES        (3)
#define MAP_ARDEAD         (127)
#define MAP_ARGARDEN       (35)
#define MAP_ARTEMPLE       (126)
#define MAP_ARVILLAG       (4)
#define MAP_B21            (157)
#define MAP_BASED          (172)
#define MAP_BASEDVX        (212)
#define MAP_BAZE           (189)
#define MAP_BHRNDDST       (94)
#define MAP_BHRNDMNT       (95)
#define MAP_BREAKDWN       (249)
#define MAP_BRHDHLP        (241)
#define MAP_BROHD12        (239)
#define MAP_BROHD121       (214)
#define MAP_BROHD1K        (188)
#define MAP_BROHD34        (240)
#define MAP_BROHD341       (215)
#define MAP_BROHDENT       (238)
#define MAP_BROHDENT1      (213)
#define MAP_BROKEN1        (78)
#define MAP_BROKEN2        (79)
#define MAP_CARDESRT       (53)
#define MAP_CAVE0          (69)
#define MAP_CAVE1          (070)
#define MAP_CAVE2          (71)
#define MAP_CAVE3          (72)
#define MAP_CAVE4          (73)
#define MAP_CAVE5          (080)
#define MAP_CAVE6          (119)
#define MAP_CAVE7          (120)
#define MAP_CITY1          (68)
#define MAP_CITY2          (125)
#define MAP_CITY3          (141)
#define MAP_CITY4          (142)
#define MAP_CITY5          (143)
#define MAP_CITY6          (144)
#define MAP_CITY7          (145)
#define MAP_CITY8          (146)
#define MAP_CITYCH3        (229)
#define MAP_CITYCHS        (228)
#define MAP_CITYCHST       (227)
#define MAP_COAST1         (76)
#define MAP_COAST10        (110)
#define MAP_COAST11        (111)
#define MAP_COAST2         (77)
#define MAP_COAST3         (85)
#define MAP_COAST4         (86)
#define MAP_COAST5         (87)
#define MAP_COAST6         (88)
#define MAP_COAST7         (89)
#define MAP_COAST8         (090)
#define MAP_COAST9         (91)
#define MAP_COLLY          (220)
#define MAP_COLLY1         (221)
#define MAP_COMHOUSE       (222)
#define MAP_CRISICAV       (205)
#define MAP_CRISIENT       (202)
#define MAP_CRISIVT        (203)
#define MAP_CRSNMAIN       (232)
#define MAP_DENBUS1        (6)
#define MAP_DENBUS2        (7)
#define MAP_DENRES1        (8)
#define MAP_DEPOLV1        (27)
#define MAP_DEPOLVA        (28)
#define MAP_DEPOLVB        (29)
#define MAP_DESERT1        (0)
#define MAP_DESERT2        (1)
#define MAP_DESERT2        (247)
#define MAP_DESERT2        (248)
#define MAP_DESERT3        (2)
#define MAP_DESERT4        (81)
#define MAP_DESERT5        (82)
#define MAP_DESERT6        (83)
#define MAP_DESERT7        (84)
#define MAP_DESERT8        (113)
#define MAP_DESERT9        (114)
#define MAP_DESRT10        (115)
#define MAP_DESRT11        (116)
#define MAP_DESRT12        (117)
#define MAP_DNSLVRUN       (52)
#define MAP_DSRT13         (118)
#define MAP_EASTER         (171)
#define MAP_ENCDET         (128)
#define MAP_ENCDOCK        (129)
#define MAP_ENCFITE        (130)
#define MAP_ENCFT2         (244)
#define MAP_ENCGD          (131)
#define MAP_ENCPRES        (132)
#define MAP_ENCRCTR        (133)
#define MAP_ENCTRP         (134)
#define MAP_ENCVERT        (243)
#define MAP_EPA2           (236)
#define MAP_EPAENT         (242)
#define MAP_EPALVL2        (237)
#define MAP_EPAMAIN        (153)
#define MAP_EPAMAIN1       (184)
#define MAP_EPAMAIN2       (185)
#define MAP_EPASL          (177)
#define MAP_EPAWRHSE       (154)
#define MAP_EPAX           (151)
#define MAP_GAMMOVIE       (149)
#define MAP_GCENCLEN       (183)
#define MAP_GECKJUNK       (33)
#define MAP_GECKPWPL       (32)
#define MAP_GECKSETL       (31)
#define MAP_GECKTUNL       (34)
#define MAP_GLOW12         (166)
#define MAP_GLOW34         (165)
#define MAP_GLOWENT        (167)
#define MAP_GSTCAV1        (25)
#define MAP_GSTCAV2        (26)
#define MAP_GSTFARM        (24)
#define MAP_HAB1           (206)
#define MAP_HAB2           (207)
#define MAP_HABOLDTN       (211)
#define MAP_HABWATER       (208)
#define MAP_HISTORY1       (193)
#define MAP_HUBSTASH       (178)
#define MAP_JENFARM7       (160)
#define MAP_KLACANYN       (48)
#define MAP_KLACVENT       (161)
#define MAP_KLADWTWN       (9)
#define MAP_KLAGRAZ        (14)
#define MAP_KLAMALL        (010)
#define MAP_KLARATCV       (11)
#define MAP_KLATOXCV       (12)
#define MAP_KLATRAP        (13)
#define MAP_LAGUNRUN       (201)
#define MAP_LARIPPER       (200)
#define MAP_LARS1          (195)
#define MAP_LARS2          (196)
#define MAP_LARS2          (233)
#define MAP_LARS3          (197)
#define MAP_LARS3          (234)
#define MAP_LARSSCRP       (235)
#define MAP_MBASE12        (49)
#define MAP_MBASE34        (050)
#define MAP_MBCLOSE        (51)
#define MAP_MERCHANT       (174)
#define MAP_MIRAGE         (199)
#define MAP_MODBRAH        (020)
#define MAP_MODGARD        (21)
#define MAP_MODINN         (19)
#define MAP_MODMAIN        (18)
#define MAP_MODOCT         (223)
#define MAP_MODOCT2        (224)
#define MAP_MODOCT3        (225)
#define MAP_MODOCT4        (226)
#define MAP_MODSHIT        (22)
#define MAP_MODWELL        (23)
#define MAP_MOUNTN1        (74)
#define MAP_MOUNTN2        (75)
#define MAP_MOUNTN3        (121)
#define MAP_MOUNTN4        (122)
#define MAP_MOUNTN5        (123)
#define MAP_MOUNTN6        (124)
#define MAP_NAVARRO        (109)
#define MAP_NCR1           (42)
#define MAP_NCR2           (43)
#define MAP_NCR3           (44)
#define MAP_NCR4           (45)
#define MAP_NCRENT         (46)
#define MAP_NCREX          (47)
#define MAP_NECHALL        (191)
#define MAP_NECHOTEL       (192)
#define MAP_NECRNCR        (190)
#define MAP_NEWR1          (54)
#define MAP_NEWR2          (55)
#define MAP_NEWR3          (56)
#define MAP_NEWR4          (57)
#define MAP_NEWRBA         (61)
#define MAP_NEWRCS         (58)
#define MAP_NEWRGO         (59)
#define MAP_NEWRST         (060)
#define MAP_NEWRVB         (147)
#define MAP_PRIMIT         (231)
#define MAP_RAIDERS1       (92)
#define MAP_RAIDERS2       (93)
#define MAP_REDDOWN        (64)
#define MAP_REDDTUN        (66)
#define MAP_REDMENT        (65)
#define MAP_REDMTUN        (67)
#define MAP_REDWAME        (62)
#define MAP_REDWAN1        (63)
#define MAP_RNDBD          (152)
#define MAP_RNDBD          (159)
#define MAP_RNDBESS        (150)
#define MAP_RNDBHEAD       (98)
#define MAP_RNDBRIDG       (101)
#define MAP_RNDCAFE        (102)
#define MAP_RNDEXCOW       (108)
#define MAP_RNDFORVR       (105)
#define MAP_RNDHOLY1       (103)
#define MAP_RNDHOLY2       (104)
#define MAP_RNDMDDG        (158)
#define MAP_RNDMSTR        (216)
#define MAP_RNDPARIH       (107)
#define MAP_RNDPOSTM       (164)
#define MAP_RNDSHUTL       (99)
#define MAP_RNDTINWD       (97)
#define MAP_RNDTOXIC       (106)
#define MAP_RNDUVILG       (100)
#define MAP_RNDWHALE       (96)
#define MAP_SAFEHS1        (168)
#define MAP_SAFEHS2        (169)
#define MAP_SAFEHS3        (170)
#define MAP_SCRAPT         (162)
#define MAP_SFCHINA        (137)
#define MAP_SFCHINA2       (148)
#define MAP_SFDOCK         (136)
#define MAP_SFELRONB       (140)
#define MAP_SFSHENG        (186)
#define MAP_SFSHUTL1       (138)
#define MAP_SFSHUTL2       (139)
#define MAP_SFSUB          (176)
#define MAP_SFTANKER       (135)
#define MAP_SLVCAMP        (254)
#define MAP_SLVVAULT       (246)
#define MAP_SOUZNIKI       (245)
#define MAP_TPMBAR         (187)
#define MAP_TRIBE01        (163)
#define MAP_TRIBE02        (253)
#define MAP_TRIBE2         (255)
#define MAP_TRUCK          (156)
#define MAP_V13ENT         (41)
#define MAP_V14ENT         (218)
#define MAP_V15ENT         (37)
#define MAP_V15ENTB        (38)
#define MAP_V15SENT        (39)
#define MAP_VAULT13        (040)
#define MAP_VAULT14        (217)
#define MAP_VAULT14B       (219)
#define MAP_VAULT15        (36)
#define MAP_VCTYCOCL       (17)
#define MAP_VCTYCTYD       (15)
#define MAP_VCTYDWTN       (16)
#define MAP_VCTYVLT        (030)
#define MAP_VILL           (173)
#define MAP_VILMERCH       (175)
#define MAP_VLT23BOS       (204)
#define MAP_XABMYR01       (194)
#define MAP_07DESERT       (112)
//
#define CUR_MAP_A10        (cur_map_index == MAP_A10)
#define CUR_MAP_A12        (cur_map_index == MAP_A12)
#define CUR_MAP_ABANDON1   (cur_map_index == MAP_ABANDON1)
#define CUR_MAP_ABANDON2   (cur_map_index == MAP_ABANDON2)
#define CUR_MAP_ABANDON3   (cur_map_index == MAP_ABANDON3)
#define CUR_MAP_ABBASEM    (cur_map_index == MAP_ABBASEM)
#define CUR_MAP_ABBEY      (cur_map_index == MAP_ABBEY)
#define CUR_MAP_ABBEY      (cur_map_index == MAP_ABBEY)
#define CUR_MAP_ABBEY1     (cur_map_index == MAP_ABBEY1)
#define CUR_MAP_ABUNDGR    (cur_map_index == MAP_ABUNDGR)
#define CUR_MAP_ADITUMB    (cur_map_index == MAP_ADITUMB)
#define CUR_MAP_ADITUMC    (cur_map_index == MAP_ADITUMC)
#define CUR_MAP_ARBRIDGE   (cur_map_index == MAP_ARBRIDGE)
#define CUR_MAP_ARCAVES    (cur_map_index == MAP_ARCAVES)
#define CUR_MAP_ARDEAD     (cur_map_index == MAP_ARDEAD)
#define CUR_MAP_ARGARDEN   (cur_map_index == MAP_ARGARDEN)
#define CUR_MAP_ARTEMPLE   (cur_map_index == MAP_ARTEMPLE)
#define CUR_MAP_ARVILLAG   (cur_map_index == MAP_ARVILLAG)
#define CUR_MAP_B21        (cur_map_index == MAP_B21)
#define CUR_MAP_BASED      (cur_map_index == MAP_BASED)
#define CUR_MAP_BASEDVX    (cur_map_index == MAP_BASEDVX)
#define CUR_MAP_BAZE       (cur_map_index == MAP_BAZE)
#define CUR_MAP_BHRNDDST   (cur_map_index == MAP_BHRNDDST)
#define CUR_MAP_BHRNDMNT   (cur_map_index == MAP_BHRNDMNT)
#define CUR_MAP_BREAKDWN   (cur_map_index == MAP_BREAKDWN)
#define CUR_MAP_BRHDHLP    (cur_map_index == MAP_BRHDHLP)
#define CUR_MAP_BROHD12    (cur_map_index == MAP_BROHD12)
#define CUR_MAP_BROHD121   (cur_map_index == MAP_BROHD121)
#define CUR_MAP_BROHD1K    (cur_map_index == MAP_BROHD1K)
#define CUR_MAP_BROHD34    (cur_map_index == MAP_BROHD34)
#define CUR_MAP_BROHD341   (cur_map_index == MAP_BROHD341)
#define CUR_MAP_BROHDENT   (cur_map_index == MAP_BROHDENT)
#define CUR_MAP_BROHDENT1  (cur_map_index == MAP_BROHDENT1)
#define CUR_MAP_BROKEN1    (cur_map_index == MAP_BROKEN1)
#define CUR_MAP_BROKEN2    (cur_map_index == MAP_BROKEN2)
#define CUR_MAP_CARDESRT   (cur_map_index == MAP_CARDESRT)
#define CUR_MAP_CAVE0      (cur_map_index == MAP_CAVE0)
#define CUR_MAP_CAVE1      (cur_map_index == MAP_CAVE1)
#define CUR_MAP_CAVE2      (cur_map_index == MAP_CAVE2)
#define CUR_MAP_CAVE3      (cur_map_index == MAP_CAVE3)
#define CUR_MAP_CAVE4      (cur_map_index == MAP_CAVE4)
#define CUR_MAP_CAVE5      (cur_map_index == MAP_CAVE5)
#define CUR_MAP_CAVE6      (cur_map_index == MAP_CAVE6)
#define CUR_MAP_CAVE7      (cur_map_index == MAP_CAVE7)
#define CUR_MAP_CITY1      (cur_map_index == MAP_CITY1)
#define CUR_MAP_CITY2      (cur_map_index == MAP_CITY2)
#define CUR_MAP_CITY3      (cur_map_index == MAP_CITY3)
#define CUR_MAP_CITY4      (cur_map_index == MAP_CITY4)
#define CUR_MAP_CITY5      (cur_map_index == MAP_CITY5)
#define CUR_MAP_CITY6      (cur_map_index == MAP_CITY6)
#define CUR_MAP_CITY7      (cur_map_index == MAP_CITY7)
#define CUR_MAP_CITY8      (cur_map_index == MAP_CITY8)
#define CUR_MAP_CITYCH3    (cur_map_index == MAP_CITYCH3)
#define CUR_MAP_CITYCHS    (cur_map_index == MAP_CITYCHS)
#define CUR_MAP_CITYCHST   (cur_map_index == MAP_CITYCHST)
#define CUR_MAP_COAST1     (cur_map_index == MAP_COAST1)
#define CUR_MAP_COAST10    (cur_map_index == MAP_COAST10)
#define CUR_MAP_COAST11    (cur_map_index == MAP_COAST11)
#define CUR_MAP_COAST2     (cur_map_index == MAP_COAST2)
#define CUR_MAP_COAST3     (cur_map_index == MAP_COAST3)
#define CUR_MAP_COAST4     (cur_map_index == MAP_COAST4)
#define CUR_MAP_COAST5     (cur_map_index == MAP_COAST5)
#define CUR_MAP_COAST6     (cur_map_index == MAP_COAST6)
#define CUR_MAP_COAST7     (cur_map_index == MAP_COAST7)
#define CUR_MAP_COAST8     (cur_map_index == MAP_COAST8)
#define CUR_MAP_COAST9     (cur_map_index == MAP_COAST9)
#define CUR_MAP_COLLY      (cur_map_index == MAP_COLLY)
#define CUR_MAP_COLLY1     (cur_map_index == MAP_COLLY1)
#define CUR_MAP_COMHOUSE   (cur_map_index == MAP_COMHOUSE)
#define CUR_MAP_CRISICAV   (cur_map_index == MAP_CRISICAV)
#define CUR_MAP_CRISIENT   (cur_map_index == MAP_CRISIENT)
#define CUR_MAP_CRISIVT    (cur_map_index == MAP_CRISIVT)
#define CUR_MAP_CRSNMAIN   (cur_map_index == MAP_CRSNMAIN)
#define CUR_MAP_DENBUS1    (cur_map_index == MAP_DENBUS1)
#define CUR_MAP_DENBUS2    (cur_map_index == MAP_DENBUS2)
#define CUR_MAP_DENRES1    (cur_map_index == MAP_DENRES1)
#define CUR_MAP_DEPOLV1    (cur_map_index == MAP_DEPOLV1)
#define CUR_MAP_DEPOLVA    (cur_map_index == MAP_DEPOLVA)
#define CUR_MAP_DEPOLVB    (cur_map_index == MAP_DEPOLVB)
#define CUR_MAP_DESERT1    (cur_map_index == MAP_DESERT1)
#define CUR_MAP_DESERT2    (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT2    (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT2    (cur_map_index == MAP_DESERT2)
#define CUR_MAP_DESERT3    (cur_map_index == MAP_DESERT3)
#define CUR_MAP_DESERT4    (cur_map_index == MAP_DESERT4)
#define CUR_MAP_DESERT5    (cur_map_index == MAP_DESERT5)
#define CUR_MAP_DESERT6    (cur_map_index == MAP_DESERT6)
#define CUR_MAP_DESERT7    (cur_map_index == MAP_DESERT7)
#define CUR_MAP_DESERT8    (cur_map_index == MAP_DESERT8)
#define CUR_MAP_DESERT9    (cur_map_index == MAP_DESERT9)
#define CUR_MAP_DESRT10    (cur_map_index == MAP_DESRT10)
#define CUR_MAP_DESRT11    (cur_map_index == MAP_DESRT11)
#define CUR_MAP_DESRT12    (cur_map_index == MAP_DESRT12)
#define CUR_MAP_DNSLVRUN   (cur_map_index == MAP_DNSLVRUN)
#define CUR_MAP_DSRT13     (cur_map_index == MAP_DSRT13)
#define CUR_MAP_EASTER     (cur_map_index == MAP_EASTER)
#define CUR_MAP_ENCDET     (cur_map_index == MAP_ENCDET)
#define CUR_MAP_ENCDOCK    (cur_map_index == MAP_ENCDOCK)
#define CUR_MAP_ENCFITE    (cur_map_index == MAP_ENCFITE)
#define CUR_MAP_ENCFT2     (cur_map_index == MAP_ENCFT2)
#define CUR_MAP_ENCGD      (cur_map_index == MAP_ENCGD)
#define CUR_MAP_ENCPRES    (cur_map_index == MAP_ENCPRES)
#define CUR_MAP_ENCRCTR    (cur_map_index == MAP_ENCRCTR)
#define CUR_MAP_ENCTRP     (cur_map_index == MAP_ENCTRP)
#define CUR_MAP_ENCVERT    (cur_map_index == MAP_ENCVERT)
#define CUR_MAP_EPA2       (cur_map_index == MAP_EPA2)
#define CUR_MAP_EPAENT     (cur_map_index == MAP_EPAENT)
#define CUR_MAP_EPALVL2    (cur_map_index == MAP_EPALVL2)
#define CUR_MAP_EPAMAIN    (cur_map_index == MAP_EPAMAIN)
#define CUR_MAP_EPAMAIN1   (cur_map_index == MAP_EPAMAIN1)
#define CUR_MAP_EPAMAIN2   (cur_map_index == MAP_EPAMAIN2)
#define CUR_MAP_EPASL      (cur_map_index == MAP_EPASL)
#define CUR_MAP_EPAWRHSE   (cur_map_index == MAP_EPAWRHSE)
#define CUR_MAP_EPAX       (cur_map_index == MAP_EPAX)
#define CUR_MAP_GAMMOVIE   (cur_map_index == MAP_GAMMOVIE)
#define CUR_MAP_GCENCLEN   (cur_map_index == MAP_GCENCLEN)
#define CUR_MAP_GECKJUNK   (cur_map_index == MAP_GECKJUNK)
#define CUR_MAP_GECKPWPL   (cur_map_index == MAP_GECKPWPL)
#define CUR_MAP_GECKSETL   (cur_map_index == MAP_GECKSETL)
#define CUR_MAP_GECKTUNL   (cur_map_index == MAP_GECKTUNL)
#define CUR_MAP_GLOW12     (cur_map_index == MAP_GLOW12)
#define CUR_MAP_GLOW34     (cur_map_index == MAP_GLOW34)
#define CUR_MAP_GLOWENT    (cur_map_index == MAP_GLOWENT)
#define CUR_MAP_GSTCAV1    (cur_map_index == MAP_GSTCAV1)
#define CUR_MAP_GSTCAV2    (cur_map_index == MAP_GSTCAV2)
#define CUR_MAP_GSTFARM    (cur_map_index == MAP_GSTFARM)
#define CUR_MAP_HAB1       (cur_map_index == MAP_HAB1)
#define CUR_MAP_HAB2       (cur_map_index == MAP_HAB2)
#define CUR_MAP_HABOLDTN   (cur_map_index == MAP_HABOLDTN)
#define CUR_MAP_HABWATER   (cur_map_index == MAP_HABWATER)
#define CUR_MAP_HISTORY1   (cur_map_index == MAP_HISTORY1)
#define CUR_MAP_HUBSTASH   (cur_map_index == MAP_HUBSTASH)
#define CUR_MAP_JENFARM7   (cur_map_index == MAP_JENFARM7)
#define CUR_MAP_KLACANYN   (cur_map_index == MAP_KLACANYN)
#define CUR_MAP_KLACVENT   (cur_map_index == MAP_KLACVENT)
#define CUR_MAP_KLADWTWN   (cur_map_index == MAP_KLADWTWN)
#define CUR_MAP_KLAGRAZ    (cur_map_index == MAP_KLAGRAZ)
#define CUR_MAP_KLAMALL    (cur_map_index == MAP_KLAMALL)
#define CUR_MAP_KLARATCV   (cur_map_index == MAP_KLARATCV)
#define CUR_MAP_KLATOXCV   (cur_map_index == MAP_KLATOXCV)
#define CUR_MAP_KLATRAP    (cur_map_index == MAP_KLATRAP)
#define CUR_MAP_LAGUNRUN   (cur_map_index == MAP_LAGUNRUN)
#define CUR_MAP_LARIPPER   (cur_map_index == MAP_LARIPPER)
#define CUR_MAP_LARS1      (cur_map_index == MAP_LARS1)
#define CUR_MAP_LARS2      (cur_map_index == MAP_LARS2)
#define CUR_MAP_LARS2      (cur_map_index == MAP_LARS2)
#define CUR_MAP_LARS3      (cur_map_index == MAP_LARS3)
#define CUR_MAP_LARS3      (cur_map_index == MAP_LARS3)
#define CUR_MAP_LARSSCRP   (cur_map_index == MAP_LARSSCRP)
#define CUR_MAP_MBASE12    (cur_map_index == MAP_MBASE12)
#define CUR_MAP_MBASE34    (cur_map_index == MAP_MBASE34)
#define CUR_MAP_MBCLOSE    (cur_map_index == MAP_MBCLOSE)
#define CUR_MAP_MERCHANT   (cur_map_index == MAP_MERCHANT)
#define CUR_MAP_MIRAGE     (cur_map_index == MAP_MIRAGE)
#define CUR_MAP_MODBRAH    (cur_map_index == MAP_MODBRAH)
#define CUR_MAP_MODGARD    (cur_map_index == MAP_MODGARD)
#define CUR_MAP_MODINN     (cur_map_index == MAP_MODINN)
#define CUR_MAP_MODMAIN    (cur_map_index == MAP_MODMAIN)
#define CUR_MAP_MODOCT     (cur_map_index == MAP_MODOCT)
#define CUR_MAP_MODOCT2    (cur_map_index == MAP_MODOCT2)
#define CUR_MAP_MODOCT3    (cur_map_index == MAP_MODOCT3)
#define CUR_MAP_MODOCT4    (cur_map_index == MAP_MODOCT4)
#define CUR_MAP_MODSHIT    (cur_map_index == MAP_MODSHIT)
#define CUR_MAP_MODWELL    (cur_map_index == MAP_MODWELL)
#define CUR_MAP_MOUNTN1    (cur_map_index == MAP_MOUNTN1)
#define CUR_MAP_MOUNTN2    (cur_map_index == MAP_MOUNTN2)
#define CUR_MAP_MOUNTN3    (cur_map_index == MAP_MOUNTN3)
#define CUR_MAP_MOUNTN4    (cur_map_index == MAP_MOUNTN4)
#define CUR_MAP_MOUNTN5    (cur_map_index == MAP_MOUNTN5)
#define CUR_MAP_MOUNTN6    (cur_map_index == MAP_MOUNTN6)
#define CUR_MAP_NAVARRO    (cur_map_index == MAP_NAVARRO)
#define CUR_MAP_NCR1       (cur_map_index == MAP_NCR1)
#define CUR_MAP_NCR2       (cur_map_index == MAP_NCR2)
#define CUR_MAP_NCR3       (cur_map_index == MAP_NCR3)
#define CUR_MAP_NCR4       (cur_map_index == MAP_NCR4)
#define CUR_MAP_NCRENT     (cur_map_index == MAP_NCRENT)
#define CUR_MAP_NCREX      (cur_map_index == MAP_NCREX)
#define CUR_MAP_NECHALL    (cur_map_index == MAP_NECHALL)
#define CUR_MAP_NECHOTEL   (cur_map_index == MAP_NECHOTEL)
#define CUR_MAP_NECRNCR    (cur_map_index == MAP_NECRNCR)
#define CUR_MAP_NEWR1      (cur_map_index == MAP_NEWR1)
#define CUR_MAP_NEWR2      (cur_map_index == MAP_NEWR2)
#define CUR_MAP_NEWR3      (cur_map_index == MAP_NEWR3)
#define CUR_MAP_NEWR4      (cur_map_index == MAP_NEWR4)
#define CUR_MAP_NEWRBA     (cur_map_index == MAP_NEWRBA)
#define CUR_MAP_NEWRCS     (cur_map_index == MAP_NEWRCS)
#define CUR_MAP_NEWRGO     (cur_map_index == MAP_NEWRGO)
#define CUR_MAP_NEWRST     (cur_map_index == MAP_NEWRST)
#define CUR_MAP_NEWRVB     (cur_map_index == MAP_NEWRVB)
#define CUR_MAP_PRIMIT     (cur_map_index == MAP_PRIMIT)
#define CUR_MAP_RAIDERS1   (cur_map_index == MAP_RAIDERS1)
#define CUR_MAP_RAIDERS2   (cur_map_index == MAP_RAIDERS2)
#define CUR_MAP_REDDOWN    (cur_map_index == MAP_REDDOWN)
#define CUR_MAP_REDDTUN    (cur_map_index == MAP_REDDTUN)
#define CUR_MAP_REDMENT    (cur_map_index == MAP_REDMENT)
#define CUR_MAP_REDMTUN    (cur_map_index == MAP_REDMTUN)
#define CUR_MAP_REDWAME    (cur_map_index == MAP_REDWAME)
#define CUR_MAP_REDWAN1    (cur_map_index == MAP_REDWAN1)
#define CUR_MAP_RNDBD      (cur_map_index == MAP_RNDBD)
#define CUR_MAP_RNDBD      (cur_map_index == MAP_RNDBD)
#define CUR_MAP_RNDBESS    (cur_map_index == MAP_RNDBESS)
#define CUR_MAP_RNDBHEAD   (cur_map_index == MAP_RNDBHEAD)
#define CUR_MAP_RNDBRIDG   (cur_map_index == MAP_RNDBRIDG)
#define CUR_MAP_RNDCAFE    (cur_map_index == MAP_RNDCAFE)
#define CUR_MAP_RNDEXCOW   (cur_map_index == MAP_RNDEXCOW)
#define CUR_MAP_RNDFORVR   (cur_map_index == MAP_RNDFORVR)
#define CUR_MAP_RNDHOLY1   (cur_map_index == MAP_RNDHOLY1)
#define CUR_MAP_RNDHOLY2   (cur_map_index == MAP_RNDHOLY2)
#define CUR_MAP_RNDMDDG    (cur_map_index == MAP_RNDMDDG)
#define CUR_MAP_RNDMSTR    (cur_map_index == MAP_RNDMSTR)
#define CUR_MAP_RNDPARIH   (cur_map_index == MAP_RNDPARIH)
#define CUR_MAP_RNDPOSTM   (cur_map_index == MAP_RNDPOSTM)
#define CUR_MAP_RNDSHUTL   (cur_map_index == MAP_RNDSHUTL)
#define CUR_MAP_RNDTINWD   (cur_map_index == MAP_RNDTINWD)
#define CUR_MAP_RNDTOXIC   (cur_map_index == MAP_RNDTOXIC)
#define CUR_MAP_RNDUVILG   (cur_map_index == MAP_RNDUVILG)
#define CUR_MAP_RNDWHALE   (cur_map_index == MAP_RNDWHALE)
#define CUR_MAP_SAFEHS1    (cur_map_index == MAP_SAFEHS1)
#define CUR_MAP_SAFEHS2    (cur_map_index == MAP_SAFEHS2)
#define CUR_MAP_SAFEHS3    (cur_map_index == MAP_SAFEHS3)
#define CUR_MAP_SCRAPT     (cur_map_index == MAP_SCRAPT)
#define CUR_MAP_SFCHINA    (cur_map_index == MAP_SFCHINA)
#define CUR_MAP_SFCHINA2   (cur_map_index == MAP_SFCHINA2)
#define CUR_MAP_SFDOCK     (cur_map_index == MAP_SFDOCK)
#define CUR_MAP_SFELRONB   (cur_map_index == MAP_SFELRONB)
#define CUR_MAP_SFSHENG    (cur_map_index == MAP_SFSHENG)
#define CUR_MAP_SFSHUTL1   (cur_map_index == MAP_SFSHUTL1)
#define CUR_MAP_SFSHUTL2   (cur_map_index == MAP_SFSHUTL2)
#define CUR_MAP_SFSUB      (cur_map_index == MAP_SFSUB)
#define CUR_MAP_SFTANKER   (cur_map_index == MAP_SFTANKER)
#define CUR_MAP_SLVCAMP    (cur_map_index == MAP_SLVCAMP)
#define CUR_MAP_SLVVAULT   (cur_map_index == MAP_SLVVAULT)
#define CUR_MAP_SOUZNIKI   (cur_map_index == MAP_SOUZNIKI)
#define CUR_MAP_TPMBAR     (cur_map_index == MAP_TPMBAR)
#define CUR_MAP_TRIBE01    (cur_map_index == MAP_TRIBE01)
#define CUR_MAP_TRIBE02    (cur_map_index == MAP_TRIBE02)
#define CUR_MAP_TRIBE2     (cur_map_index == MAP_TRIBE2)
#define CUR_MAP_TRUCK      (cur_map_index == MAP_TRUCK)
#define CUR_MAP_V13ENT     (cur_map_index == MAP_V13ENT)
#define CUR_MAP_V14ENT     (cur_map_index == MAP_V14ENT)
#define CUR_MAP_V15ENT     (cur_map_index == MAP_V15ENT)
#define CUR_MAP_V15ENTB    (cur_map_index == MAP_V15ENTB)
#define CUR_MAP_V15SENT    (cur_map_index == MAP_V15SENT)
#define CUR_MAP_VAULT13    (cur_map_index == MAP_VAULT13)
#define CUR_MAP_VAULT14    (cur_map_index == MAP_VAULT14)
#define CUR_MAP_VAULT14B   (cur_map_index == MAP_VAULT14B)
#define CUR_MAP_VAULT15    (cur_map_index == MAP_VAULT15)
#define CUR_MAP_VCTYCOCL   (cur_map_index == MAP_VCTYCOCL)
#define CUR_MAP_VCTYCTYD   (cur_map_index == MAP_VCTYCTYD)
#define CUR_MAP_VCTYDWTN   (cur_map_index == MAP_VCTYDWTN)
#define CUR_MAP_VCTYVLT    (cur_map_index == MAP_VCTYVLT)
#define CUR_MAP_VILL       (cur_map_index == MAP_VILL)
#define CUR_MAP_VILMERCH   (cur_map_index == MAP_VILMERCH)
#define CUR_MAP_VLT23BOS   (cur_map_index == MAP_VLT23BOS)
#define CUR_MAP_XABMYR01   (cur_map_index == MAP_XABMYR01)
#define CUR_MAP_07DESERT   (cur_map_index == MAP_07DESERT)

#endif // __MAPS__ //
