variable ProtoOfItemGiven;
variable ValueOfRollCheck;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure EvaluateKarma;
procedure CheckRep;

variable lock_event;

procedure critter_p_proc;
procedure timed_event_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure pickup_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure map_enter_p_proc;
procedure Node000;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node999;
procedure NodeCombat;
procedure talk_p_proc;
procedure start;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure EvaluateKarma
begin
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure CheckRep
begin
    if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
        set_global_var(2, 1);
        set_global_var(3, 0);
    end
    if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
        set_global_var(3, 1);
        set_global_var(2, 0);
    end
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((global_var(7) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if (lock_event == 0) then begin
        lock_event := 1;
        add_timer_event(self_obj, random(7, 10) * 10, 0);
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 0) and (local_var(18) != 0)) then begin
        animate_move_obj_to_tile(self_obj, tile_num_in_direction(local_var(18), random(0, 5), random(1, 2)), 0);
        lock_event := 0;
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(214, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(214, 101));
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(16, 3);
        set_local_var(5, 2);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(7, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(0, global_var(0) - 15);
        call EvaluateKarma();
        set_global_var(47, global_var(47) - 25);
        set_global_var(7, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 1);
    critter_add_trait(self_obj, 1, 5, 178);
end

procedure Node000
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 200);
    end
    else begin
        gsay_reply(214, 201);
    end
    set_local_var(11, 1);
    giq_option(1, 214, 202, "Node001", 50);
end

procedure Node001
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 203);
    end
    else begin
        gsay_reply(214, 204);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 214, 205, "Node999", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 214, 206, "Node999", 50);
    end
    if ((global_var(697) == 1) and (global_var(183) == 2) and (local_var(12) == 0) and (local_var(13) == 0)) then begin
        if (local_var(14) == 1) then begin
            giq_option(4, 214, 207, "Node007", 50);
        end
        else begin
            giq_option(4, 214, 207, "Node004", 50);
        end
    end
    if ((local_var(13) == 1) and (local_var(12) == 0) and (obj_is_carrying_obj_pid(dude_obj, 612) >= 1)) then begin
        giq_option(4, 214, 208, "Node011", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(-3, 214, 209, "Node002", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(-3, 214, 210, "Node002", 50);
    end
    if ((global_var(697) == 1) and (global_var(183) == 2) and (local_var(12) == 0) and (local_var(13) == 0)) then begin
        if (local_var(14) == 1) then begin
            giq_option(-3, 214, 211, "Node007", 50);
        end
        else begin
            giq_option(-3, 214, 211, "Node004", 50);
        end
    end
    if ((local_var(13) == 1) and (local_var(12) == 0) and (obj_is_carrying_obj_pid(dude_obj, 612) >= 1)) then begin
        giq_option(-3, 214, 212, "Node011", 50);
    end
    giq_option(-3, 214, 213, "Node999", 50);
end

procedure Node002
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 214);
    end
    else begin
        gsay_reply(214, 215);
    end
    giq_option(1, 214, 216, "Node999", 50);
end

procedure Node003
begin
    gsay_reply(214, 217);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 214, 218, "Node999", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 214, 219, "Node999", 50);
    end
    if ((global_var(697) == 1) and (global_var(183) == 2) and (local_var(12) == 0) and (local_var(13) == 0)) then begin
        if (local_var(14) == 1) then begin
            giq_option(4, 214, 220, "Node007", 50);
        end
        else begin
            giq_option(4, 214, 220, "Node004", 50);
        end
    end
    if ((local_var(13) == 1) and (local_var(12) == 0) and (obj_is_carrying_obj_pid(dude_obj, 612) >= 1)) then begin
        giq_option(4, 214, 221, "Node011", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(-3, 214, 222, Node002, 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(-3, 214, 223, Node002, 50);
    end
    if ((global_var(697) == 1) and (global_var(183) == 2) and (local_var(12) == 0) and (local_var(13) == 0)) then begin
        if (local_var(14) == 1) then begin
            giq_option(-3, 214, 224, "Node007", 50);
        end
        else begin
            giq_option(-3, 214, 224, "Node004", 50);
        end
    end
    if ((local_var(13) == 1) and (local_var(12) == 0) and (obj_is_carrying_obj_pid(dude_obj, 612) >= 1)) then begin
        giq_option(-3, 214, 225, "Node011", 50);
    end
    giq_option(-3, 214, 226, "Node999", 50);
end

procedure Node004
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 227);
    end
    else begin
        gsay_reply(214, 228);
    end
    giq_option(4, 214, 229, "Node005", 50);
    giq_option(4, 214, 230, "Node010", 50);
    giq_option(4, 214, 231, "Node999", 50);
    giq_option(-3, 214, 232, "Node005", 50);
    giq_option(-3, 214, 233, "Node010", 50);
    giq_option(-3, 214, 234, "Node999", 50);
end

procedure Node005
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 235);
    end
    else begin
        gsay_reply(214, 236);
    end
    giq_option(4, 214, 237, "Node006", 50);
    giq_option(4, 214, 238, "Node010", 50);
    giq_option(-3, 214, 239, "Node006", 50);
    giq_option(-3, 214, 240, "Node010", 50);
end

procedure Node006
begin
    set_local_var(14, 1);
    gsay_reply(214, 241);
    if (has_skill(dude_obj, 14) >= 80) then begin
        giq_option(4, 214, 242, "Node008", 50);
    end
    giq_option(1, 214, 243, "Node999", 50);
end

procedure Node007
begin
    gsay_reply(214, 244);
    giq_option(1, 214, 245, "Node999", 50);
end

procedure Node008
begin
    gsay_reply(214, 246);
    giq_option(1, 214, 247, "Node009", 50);
end

procedure Node009
begin
    add_mult_objs_to_inven(dude_obj, create_object_sid(278, 0, 0, -1), 1);
    set_local_var(12, 1);
    gsay_reply(214, 248);
    giq_option(1, 214, 249, "Node999", 50);
end

procedure Node010
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 250);
    end
    else begin
        gsay_reply(214, 251);
    end
    set_local_var(13, 1);
    if (obj_is_carrying_obj_pid(dude_obj, 612) >= 1) then begin
        giq_option(1, 214, 252, "Node011", 50);
    end
    giq_option(1, 214, 253, "Node999", 50);
end

procedure Node011
begin
    set_local_var(12, 1);
    rm_mult_objs_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 612), 1);
    add_mult_objs_to_inven(dude_obj, create_object_sid(278, 0, 0, -1), 1);
    give_exp_points(50);
    display_msg(message_str(14, 100) + 50 + message_str(14, 101));
    gsay_reply(214, 254);
    giq_option(1, 214, 255, "Node999", 50);
end

procedure Node012
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, message_str(214, 256) + obj_name(dude_obj) + message_str(214, 364));
    end
    else begin
        gsay_reply(214, message_str(214, 256) + obj_name(dude_obj) + message_str(214, 366));
    end
    giq_option(4, 214, 258, "Node013", 50);
    if ((get_critter_stat(dude_obj, 34) == 0) and (global_var(641) == 0)) then begin
        giq_option(4, 214, 259, "Node015", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 214, 260, "Node014", 50);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and (global_var(641) == 0)) then begin
        giq_option(4, 214, 261, "Node015", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 214, 262, "Node014", 50);
    end
    giq_option(4, 214, 263, "Node999", 50);
    if (global_var(641) == 0) then begin
        giq_option(-3, 214, 264, "Node015", 50);
    end
    giq_option(-3, 214, 265, "Node999", 50);
end

procedure Node013
begin
    gsay_reply(214, 266);
    if ((get_critter_stat(dude_obj, 34) == 0) and (global_var(641) == 0)) then begin
        giq_option(4, 214, 267, "Node015", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(4, 214, 268, "Node014", 50);
    end
    if ((get_critter_stat(dude_obj, 34) == 1) and (global_var(641) == 0)) then begin
        giq_option(4, 214, 269, "Node015", 50);
    end
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        giq_option(4, 214, 270, "Node014", 50);
    end
    giq_option(1, 214, 271, "Node999", 50);
end

procedure Node014
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 272);
    end
    else begin
        gsay_reply(214, 273);
    end
    set_local_var(16, local_var(16) + 2);
    giq_option(1, 214, 274, "Node999", 50);
end

procedure Node015
begin
    gsay_reply(214, 275);
    giq_option(4, 214, 276, "Node016", 50);
    giq_option(1, 214, 277, "Node017", 50);
end

procedure Node016
begin
    gsay_reply(214, 278);
    giq_option(1, 214, 279, "Node017", 50);
    giq_option(1, 214, 280, "Node999", 50);
end

procedure Node017
begin
    gsay_reply(214, 281);
    giq_option(4, 214, 282, "Node018", 50);
    giq_option(-3, 214, 283, "Node018", 50);
end

procedure Node018
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 284);
    end
    else begin
        gsay_reply(214, 285);
    end
    set_local_var(16, local_var(16) + 1);
    giq_option(4, 214, 286, "Node019", 50);
    giq_option(4, 214, 287, "Node020", 50);
    if (local_var(15) == 0) then begin
        giq_option(4, 214, 288, "Node031", 50);
    end
    giq_option(-3, 214, 289, "Node019", 50);
    giq_option(-3, 214, 290, "Node020", 50);
end

procedure Node019
begin
    gsay_reply(214, 291);
    giq_option(4, 214, 292, Node019, 50);
    giq_option(4, 214, 293, "Node020", 50);
    if (local_var(15) == 0) then begin
        giq_option(4, 214, 294, "Node031", 50);
    end
    giq_option(-3, 214, 295, Node019, 50);
    giq_option(-3, 214, 296, "Node020", 50);
    giq_option(1, 214, 297, "Node999", 50);
end

procedure Node020
begin
    gsay_reply(214, 298);
    giq_option(4, 214, 299, "Node021", 50);
    if (local_var(15) == 0) then begin
        giq_option(4, 214, 300, "Node031", 50);
    end
    giq_option(4, 214, 301, "Node999", 50);
    giq_option(-3, 214, 302, "Node021", 50);
    giq_option(-3, 214, 303, "Node999", 50);
end

procedure Node021
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 304);
    end
    else begin
        gsay_reply(214, 305);
    end
    set_local_var(16, 3);
    giq_option(4, 214, 306, "Node999", 50);
    giq_option(-3, 214, 307, "Node999", 50);
    if ((get_critter_stat(dude_obj, 0) + get_critter_stat(dude_obj, 2) + get_critter_stat(dude_obj, 5)) >= 20) then begin
        giq_option(1, 214, 308, "Node023", 50);
    end
    else begin
        giq_option(1, 214, 308, "Node022", 50);
    end
end

procedure Node022
begin
    gsay_reply(214, 309);
    giq_option(1, 214, 310, "NodeCombat", 50);
end

procedure Node023
begin
    gsay_reply(214, 311);
    giq_option(4, 214, 312, "Node024", 50);
    giq_option(-3, 214, 313, "Node024", 50);
end

procedure Node024
begin
    set_local_var(17, local_var(17) + 1);
    gfade_out(3);
    gfade_in(3);
    gsay_reply(214, 314);
    if (local_var(17) >= 3) then begin
        giq_option(4, 214, 315, "Node025", 50);
    end
    else begin
        giq_option(4, 214, 315, Node024, 50);
    end
    if (local_var(17) >= 3) then begin
        giq_option(-3, 214, 316, "Node025", 50);
    end
    else begin
        giq_option(-3, 214, 316, Node024, 50);
    end
end

procedure Node025
begin
    gfade_out(3);
    gfade_in(3);
    gsay_reply(214, 317);
    giq_option(4, 214, 318, "Node026", 50);
    giq_option(-3, 214, 319, "Node026", 50);
end

procedure Node026
begin
    gfade_out(3);
    gfade_in(3);
    gsay_reply(214, 320);
    giq_option(4, 214, 321, "Node027", 50);
    giq_option(-3, 214, 322, "Node027", 50);
end

procedure Node027
begin
    gsay_reply(214, 323);
    giq_option(4, 214, 324, "Node028", 50);
    giq_option(-3, 214, 325, "Node028", 50);
end

procedure Node028
begin
    set_global_var(641, 1);
    gsay_reply(214, 326);
    giq_option(4, 214, 327, "Node029", 50);
    giq_option(-3, 214, 328, "Node029", 50);
end

procedure Node029
begin
    gsay_reply(214, 329);
    giq_option(4, 214, 330, "Node030", 50);
    giq_option(-3, 214, 331, "Node030", 50);
end

procedure Node030
begin
    gsay_reply(214, 332);
    giq_option(1, 214, 333, "Node999", 50);
end

procedure Node031
begin
    gsay_reply(214, 334);
    giq_option(1, 214, 335, Node020, 50);
    giq_option(1, 214, 336, "Node033", 50);
    giq_option(1, 214, 337, "Node034", 50);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(1, 214, 338, "Node035", 50);
    end
    else begin
        giq_option(1, 214, 368, "Node035", 50);
    end
    giq_option(1, 214, 339, "Node032", 50);
end

procedure Node032
begin
    gsay_reply(214, 340);
    giq_option(1, 214, 341, "Node036", 50);
    giq_option(1, 214, 342, "Node038", 50);
    giq_option(1, 214, 343, "Node037", 50);
    giq_option(1, 214, 344, Node031, 50);
end

procedure Node033
begin
    set_global_var(641, 1);
    gsay_reply(214, 345);
    giq_option(1, 214, 346, "Node999", 50);
end

procedure Node034
begin
    set_local_var(15, 1);
    gsay_reply(214, 347);
    giq_option(1, 214, 348, "Node999", 50);
end

procedure Node035
begin
    set_local_var(15, 1);
    gsay_reply(214, 349);
    giq_option(1, 214, 350, "Node999", 50);
end

procedure Node036
begin
    set_local_var(15, 1);
    gsay_reply(214, 351);
    giq_option(1, 214, 352, "Node999", 50);
end

procedure Node037
begin
    set_local_var(15, 1);
    gsay_reply(214, 353);
    giq_option(1, 214, 354, "Node999", 50);
end

procedure Node038
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 355);
    end
    else begin
        gsay_reply(214, 356);
    end
    set_local_var(15, 1);
    giq_option(1, 214, 357, "Node999", 50);
end

procedure Node039
begin
    gsay_reply(214, 358);
    giq_option(1, 214, 359, "Node999", 50);
end

procedure Node040
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(214, 360);
    end
    else begin
        gsay_reply(214, 361);
    end
    giq_option(1, 214, 362, "Node999", 50);
end

procedure Node999
begin
end

procedure NodeCombat
begin
    set_local_var(5, 2);
end

procedure talk_p_proc
begin
    if (get_critter_stat(dude_obj, 4) == 1) then begin
        start_gdialog(214, self_obj, 4, -1, -1);
        gsay_start;
        call Node040();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (global_var(640) == 0) then begin
            if (local_var(11) == 0) then begin
                start_gdialog(214, self_obj, 4, -1, -1);
                gsay_start;
                call Node000();
                gsay_end;
                end_dialogue;
            end
            else begin
                start_gdialog(214, self_obj, 4, -1, -1);
                gsay_start;
                call Node003();
                gsay_end;
                end_dialogue;
            end
        end
        else begin
            if (global_var(640) == 1) then begin
                if (local_var(16) < 3) then begin
                    start_gdialog(214, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node012();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    start_gdialog(214, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node039();
                    gsay_end;
                    end_dialogue;
                end
            end
            else begin
                if (local_var(16) < 3) then begin
                    start_gdialog(214, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node003();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    start_gdialog(214, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node039();
                    gsay_end;
                    end_dialogue;
                end
            end
        end
    end
end

procedure start
begin
    if (local_var(18) == 0) then begin
        set_local_var(18, tile_num(self_obj));
    end
end

