/*******************************************************
*      Some unreferenced imported varables found.      *
*      Because of it it is impossible to specify       *
*      the real names of global variables.             *
*******************************************************/

variable GVar0;
variable GVar1 := 1;
variable GVar2;
variable GVar3;
variable GVar4;
variable GVar5;
variable GVar6 := 50;
variable GVar7 := 2;
variable GVar8;
variable GVar9;
variable GVar10;
variable GVar11;
variable GVar12;
variable GVar13;
variable GVar14;
variable GVar15;
variable GVar16;
variable GVar17;

/* ?import? variable SVar01; */
/* ?import? variable SVar02; */
/* ?import? variable SVar03; */
/* ?import? variable SVar04; */
/* ?import? variable SVar05; */
/* ?import? variable SVar06; */
/* ?import? variable SVar07; */
/* ?import? variable SVar08; */
/* ?import? variable SVar09; */
/* ?import? variable SVar10; */
/* ?import? variable SVar11; */
/* ?import? variable SVar12; */
/* ?import? variable SVar13; */
/* ?import? variable SVar14; */
/* ?import? variable SVar15; */
/* ?import? variable SVar16; */
/* ?import? variable SVar17; */
/* ?import? variable SVar18; */
/* ?import? variable GVar0; */
/* ?import? variable GVar1; */
/* ?import? variable GVar2; */
/* ?import? variable GVar3; */
/* ?import? variable GVar4; */
/* ?import? variable GVar5; */
/* ?import? variable GVar6; */
/* ?import? variable GVar7; */
/* ?import? variable GVar8; */
/* ?import? variable GVar9; */
/* ?import? variable GVar10; */
/* ?import? variable GVar11; */
/* ?import? variable complain; */
/* ?import? variable exit_line; */

procedure start;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure critter_p_proc;
procedure timed_event_p_proc;
procedure destroy_p_proc;
procedure description_p_proc;
procedure do_dialogue;
procedure Node999;
procedure Node000;
procedure Node000a;
procedure Node000b;
procedure Node001;
procedure Node001_1;
procedure Node002;
procedure Node002a;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node007a;
procedure Node008;
procedure Node008_1;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node017a;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node025_1;
procedure Node025a;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node026a;
procedure bakacombat;
procedure Critter_Action;
procedure Start_War;

/* ?import? variable shout_once; */
/* ?import? variable Scouted_Crypts; */
/* ?import? variable broken_gen; */

import variable skippy_talk;

/* ?import? variable know_power; */

import variable know_fools;

/* ?import? variable Know_Crypts; */

import variable Crypt_Pointer;
import variable Fool_Pointer;
import variable Phrax_Pointer;
import variable Rock_Pointer;
import variable Fool_Taunt;
import variable Crypt_Taunt;

/* ?import? variable Fool_Counter; */
/* ?import? variable Crypt_Counter; */

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

/* ?import? variable team_do_once; */
/* ?import? variable ai_do_once; */
/* ?import? variable scouted; */


procedure start
begin
    set_local_var(2, 1);
    Fool_Pointer := self_obj;
    if (local_var(0) == 0) then begin
        critter_add_trait(self_obj, 1, 6, 135);
        critter_add_trait(self_obj, 1, 5, 22);
        set_map_var(6, map_var(6) + 1);
        set_local_var(0, 1);
    end
end

procedure talk_p_proc
begin
    if (map_var(7) == 0) then begin
        float_msg(self_obj, message_str(414, 172), 0);
    end
    else begin
        call do_dialogue();
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (know_fools == 1) then begin
        display_msg(message_str(414, 101));
    end
    else begin
        display_msg(message_str(414, 100));
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        party_remove(self_obj);
        critter_add_trait(self_obj, 1, 6, 135);
        set_map_var(11, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure critter_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (map_var(11) == 1) then begin
        if (has_trait(1, self_obj, 6) == 0) then begin
            party_remove(self_obj);
            critter_add_trait(self_obj, 1, 6, 135);
        end
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        set_map_var(11, 2);
    end
    if ((local_var(2) == 1) and (map_var(11) == 1)) then begin
        critter_add_trait(self_obj, 1, 6, 135);
        critter_add_trait(self_obj, 1, 5, 22);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((map_var(2) >= 1) and (tile_num(self_obj) != 27504)) then begin
        if (GVar12 == 0) then begin
            GVar12 := 1;
            float_msg(self_obj, message_str(964, random(10300, 1310)), 6);
        end
        animate_move_obj_to_tile(self_obj, 27504, 0);
    end
    else begin
        if ((map_var(2) >= 1) and (tile_num(self_obj) == 27504)) then begin
            if (has_trait(1, self_obj, 6) == 0) then begin
                party_remove(self_obj);
            end
            critter_add_trait(self_obj, 1, 6, 135);
            set_obj_visibility(self_obj, 1);
        end
        else begin
            if ((map_var(5) == 2) and (tile_num(self_obj) != 19305) and not(map_var(2) >= 1)) then begin
                if (has_trait(1, self_obj, 6) == 0) then begin
                    party_remove(self_obj);
                end
                critter_add_trait(self_obj, 1, 6, 135);
                animate_move_obj_to_tile(self_obj, 19305, 0);
            end
        end
    end
    if (map_var(5) == 3) then begin
        attack_complex(Crypt_Pointer, 0, 1, 0, 0, 30000, 0, 0);
    end
    Fool_Pointer := self_obj;
    LVar0 := (self_obj == Fool_Pointer) or (self_obj == Crypt_Pointer) or (self_obj == Phrax_Pointer) or (self_obj == Rock_Pointer);
    if (GVar4 and Crypt_Taunt) then begin
        Crypt_Taunt := 0;
        if (random(1, 5) == 1) then begin
            float_msg(self_obj, message_str(964, random(10100, 10113)), -1);
        end
    end
    if (GVar5 and Fool_Taunt) then begin
        Fool_Taunt := 0;
        if (random(1, 5) == 1) then begin
            float_msg(self_obj, message_str(964, random(10200, 10218)), -1);
        end
    end
    if ((map_var(5) == 1) and (tile_num(self_obj) != 20725)) then begin
        if (global_var(805) == 1) then begin
            critter_add_trait(self_obj, 1, 6, 0);
        end
        animate_move_obj_to_tile(self_obj, 20725, 0);
        if (GVar14 == 0) then begin
            add_timer_event(self_obj, game_ticks(20), 1);
            GVar14 := 1;
        end
    end
    else begin
        if ((tile_num(self_obj) == 20725) and (GVar14 == 0)) then begin
            GVar14 := 1;
        end
    end
    return 0;
    LVar0 := 0;
    LVar1 := 0;
end

procedure timed_event_p_proc
begin
    variable LVar0 := 0;
    if (fixed_param == 1) then begin
        Fool_Taunt := 1;
        float_msg(self_obj, message_str(964, random(10100, 10115)), -1);
        if (LVar0 == 0) then begin
            add_timer_event(self_obj, 100, 2);
        end
    end
    else begin
        if (fixed_param == 2) then begin
            if (map_var(5) == 1) then begin
                set_map_var(5, 3);
            end
        end
        else begin
            if (fixed_param == 3) then begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
    return 0;
    LVar0 := 0;
end

procedure destroy_p_proc
begin
    set_map_var(6, map_var(6) - 1);
    if ((map_var(6) == 0) or (map_var(7) == 0)) then begin
        set_map_var(5, 2);
    end
    if (source_obj == dude_obj) then begin
        set_global_var(4, global_var(4) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(808, global_var(808) + -5);
                debug_msg("Added " + -5 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(808, global_var(808) + 3);
        debug_msg("Added " + 3 + " to Town Rep");
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(414, 101));
end

procedure do_dialogue
begin
    start_gdialog(414, self_obj, 4, -1, -1);
    gsay_start;
    if (map_var(12) == 1) then begin
        call Node000();
    end
    else begin
        if (map_var(13) == 1) then begin
            if (local_var(4) == 0) then begin
                call Node022();
            end
            else begin
                if ((map_var(4) == 2) and (local_var(4) == 1)) then begin
                    call Node026();
                end
            end
        end
        else begin
            if (GVar0 == 0) then begin
                call Node006();
            end
            else begin
                call Node012();
            end
        end
    end
    gsay_end;
    end_dialogue;
end

procedure Node999
begin
end

procedure Node000
begin
    gsay_reply(414, 102);
    giq_option(4, 414, 103, Node000a, 50);
    giq_option(4, 414, 104, Node003, 50);
    giq_option(4, 414, 105, Node000b, 50);
end

procedure Node000a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
        call Node002();
    end
    else begin
        call Node001();
    end
end

procedure Node000b
begin
    add_timer_event(self_obj, game_ticks(20), 2);
end

procedure Node001
begin
    gsay_reply(414, 106);
    giq_option(4, 414, 164, Node001_1, 50);
end

procedure Node001_1
begin
    gsay_reply(414, 174);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node002
begin
    gsay_reply(414, 107);
    giq_option(4, 414, 164, Node002a, 50);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node002a
begin
    gsay_reply(414, 173);
    set_global_var(805, 1);
    set_global_var(804, 1);
    set_map_var(13, 1);
    set_map_var(12, 0);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node003
begin
    gsay_reply(414, 108);
    giq_option(4, 414, 109, bakacombat, 50);
    giq_option(4, 414, 110, Node005, 50);
    giq_option(4, 414, 111, Node004, 50);
    if (get_critter_stat(dude_obj, 4) >= 0) then begin
        call Node999();
    end
end

procedure Node004
begin
    gsay_reply(414, 112);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node005
begin
    gsay_reply(414, 113);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node006
begin
    gsay_reply(414, 114);
    giq_option(4, 414, 115, Node007, 50);
    giq_option(4, 414, 116, Node005, 50);
    giq_option(4, 414, 117, Node009, 50);
end

procedure Node007
begin
    gsay_reply(414, 118);
    giq_option(4, 414, 164, Node007a, 50);
    giq_option(4, 414, 171, Node999, 50);
end

procedure Node007a
begin
    gsay_reply(414, 172);
    giq_option(4, 414, 119, Node008, 50);
    giq_option(4, 414, 171, Node999, 50);
end

procedure Node008
begin
    gsay_reply(414, 120);
    giq_option(4, 414, 179, Node008_1, 50);
    giq_option(4, 414, 178, Node999, 50);
end

procedure Node008_1
begin
    gsay_reply(414, 175);
    set_global_var(805, 1);
    set_map_var(13, 1);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node009
begin
    gsay_reply(414, 121);
    giq_option(4, 414, 122, Node010, 50);
    giq_option(4, 414, 123, Node011, 50);
end

procedure Node010
begin
    gsay_reply(414, 124);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node011
begin
    gsay_reply(414, 125);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node012
begin
    gsay_reply(414, 126);
    giq_option(4, 414, 127, Node013, 50);
    giq_option(4, 414, 128, Node017, 50);
    giq_option(4, 414, 168, Node999, 50);
end

procedure Node013
begin
    gsay_reply(414, 129);
    giq_option(4, 414, 130, Node014, 50);
    giq_option(4, 414, 131, Node015, 50);
    giq_option(4, 414, 132, Node016, 50);
    giq_option(4, 414, 170, Node999, 50);
end

procedure Node014
begin
    gsay_reply(414, 133);
    set_map_var(13, 1);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node015
begin
    gsay_reply(414, 134);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node016
begin
    gsay_reply(414, 135);
    skippy_talk := 1;
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node017
begin
    gsay_reply(414, 136);
    giq_option(4, 414, 164, Node017a, 50);
end

procedure Node017a
begin
    gsay_reply(414, 176);
    giq_option(4, 414, 137, Node018, 50);
    giq_option(4, 414, 138, Node999, 50);
end

procedure Node018
begin
    gsay_reply(414, 139);
    giq_option(4, 414, 140, Node019, 50);
    giq_option(4, 414, 141, Node999, 50);
end

procedure Node019
begin
    gsay_reply(414, 142);
    giq_option(4, 414, 143, Node020, 50);
    giq_option(4, 414, 144, Node021, 50);
end

procedure Node020
begin
    gsay_reply(414, 145);
    set_map_var(13, 1);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node021
begin
    gsay_reply(414, 146);
    giq_option(4, 414, 163, bakacombat, 50);
end

procedure Node022
begin
    set_local_var(4, 1);
    gsay_reply(414, 147);
    giq_option(4, 414, 148, Node023, 50);
    giq_option(4, 414, 149, Node024, 50);
    giq_option(4, 414, 150, Node029, 50);
end

procedure Node023
begin
    gsay_reply(414, 151);
    giq_option(4, 414, 152, Node024, 50);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node024
begin
    gsay_reply(414, 153);
    giq_option(4, 414, 154, Node025, 50);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node025
begin
    gsay_reply(414, 155);
    giq_option(4, 414, 164, Node025_1, 50);
end

procedure Node025_1
begin
    gsay_reply(414, 177);
    giq_option(4, 414, 156, Node025a, 50);
end

procedure Node025a
begin
    call Node999();
end

procedure Node026
begin
    gsay_reply(414, 157);
    giq_option(4, 414, 158, Node026a, 50);
    giq_option(4, 414, 159, Node027, 50);
end

procedure Node027
begin
    gsay_reply(414, 160);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node028
begin
    gsay_reply(414, 161);
    set_map_var(5, 1);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node029
begin
    gsay_reply(414, 162);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node030
begin
    gsay_reply(414, 169);
    giq_option(4, 414, 163, Node999, 50);
end

procedure Node026a
begin
    if (map_var(4) == 2) then begin
        call Node028();
    end
    else begin
        call Node030();
    end
end

procedure bakacombat
begin
    add_timer_event(self_obj, 15, 3);
end

procedure Critter_Action
begin
end

procedure Start_War
begin
    if (fixed_param == 1) then begin
        Fool_Taunt := 1;
        float_msg(self_obj, message_str(1488, random(10100, 10115)), -1);
        add_timer_event(self_obj, 200, 2);
    end
    else begin
        if (fixed_param == 2) then begin
            attack_complex(Crypt_Pointer, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure get_reaction
begin
    if (not(GVar8)) then begin
        GVar8 := 1;
        GVar6 := GVar6 + ((get_critter_stat(dude_obj, 3) - 5) * 5);
        if (GVar9) then begin
            GVar6 := GVar6 - map_var(8);
        end
        else begin
            GVar6 := GVar6 + map_var(8);
        end
        if (global_var(1) > 2) then begin
            GVar6 := GVar6 - 30;
        end
        if ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) then begin
            GVar6 := GVar6 + 20;
        end
        if ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1)) then begin
            GVar6 := GVar6 - 20;
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (GVar6 < 24) then begin
        GVar7 := 1;
    end
    else begin
        if (GVar6 < 74) then begin
            GVar7 := 2;
        end
        else begin
            GVar7 := 3;
        end
    end
end

procedure LevelToReact
begin
    if (GVar7 == 1) then begin
        GVar6 := random(1, 24);
    end
    else begin
        if (GVar7 == 2) then begin
            GVar6 := random(25, 74);
        end
        else begin
            GVar6 := random(75, 100);
        end
    end
end

procedure UpReact
begin
    GVar6 := GVar6 + 10;
    call ReactToLevel();
end

procedure DownReact
begin
    GVar6 := GVar6 - 10;
    call ReactToLevel();
end

procedure BottomReact
begin
    GVar7 := 1;
    GVar6 := 1;
end

procedure TopReact
begin
    GVar6 := 100;
    GVar7 := 3;
end

procedure BigUpReact
begin
    GVar6 := GVar6 + 25;
    call ReactToLevel();
end

procedure BigDownReact
begin
    GVar6 := GVar6 - 25;
    call ReactToLevel();
end

procedure UpReactLevel
begin
    GVar7 := GVar7 + 1;
    if (GVar7 > 3) then begin
        GVar7 := 3;
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    GVar7 := GVar7 - 1;
    if (GVar7 < 1) then begin
        GVar7 := 1;
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    variable LVar0 := 0;
    LVar0 := random(1, 6);
    if (LVar0 == 1) then begin
        GVar13 := "Thanks, bye.";
    end
    if (LVar0 == 2) then begin
        GVar13 := "Okay, thanks.";
    end
    if (LVar0 == 3) then begin
        GVar13 := "Hmm. Bye.";
    end
    if (LVar0 == 4) then begin
        GVar13 := "See ya.";
    end
    if (LVar0 == 5) then begin
        GVar13 := "Thanks.";
    end
    if (LVar0 == 6) then begin
        GVar13 := "Okay, bye.";
    end
    return 0;
    LVar0 := 0;
end

