procedure start;
procedure pickup_p_proc;
procedure critter_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure talk_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node999;
procedure destroy_p_proc;


procedure start
begin
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) or (global_var(1098) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(1677, 100));
    end
    else begin
        display_msg(message_str(1677, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1677, 102));
end

procedure damage_p_proc
begin
    set_global_var(1098, 1);
end

procedure map_enter_p_proc
begin
    set_local_var(0, tile_num(self_obj));
    set_local_var(1, has_trait(1, self_obj, 10));
end

procedure talk_p_proc
begin
    if (global_var(1074) > 3) then begin
        float_msg(self_obj, message_str(1677, 1200), 8);
    end
    else begin
        start_gdialog(1677, self_obj, -1, -1, -1);
        gsay_start;
        set_local_var(4, 1);
        if ((global_var(1074) > 0) and (global_var(1074) < 4)) then begin
            call Node006();
        end
        else begin
            call Node001();
        end
        gsay_end;
        end_dialogue;
    end
end

procedure Node001
begin
    gsay_reply(1677, 200);
    gsay_option(1677, 210, Node002, -1);
    gsay_option(1677, 211, Node003, -1);
    gsay_option(1677, 212, Node005, -1);
    gsay_option(1677, 213, Node004, -1);
    gsay_option(1677, 214, Node999, -1);
end

procedure Node002
begin
    gsay_reply(1677, 300);
    gsay_option(1677, 211, Node003, -1);
    gsay_option(1677, 212, Node005, -1);
    gsay_option(1677, 213, Node004, -1);
    gsay_option(1677, 214, Node999, -1);
end

procedure Node003
begin
    gsay_reply(1677, 400);
    gsay_option(1677, 210, Node002, -1);
    gsay_option(1677, 212, Node005, -1);
    gsay_option(1677, 213, Node004, -1);
    gsay_option(1677, 214, Node999, -1);
end

procedure Node004
begin
    gsay_reply(1677, 500);
    gsay_option(1677, 210, Node002, -1);
    gsay_option(1677, 211, Node003, -1);
    gsay_option(1677, 212, Node005, -1);
    gsay_option(1677, 214, Node999, -1);
end

procedure Node005
begin
    set_global_var(1074, 1);
    gsay_message(1677, 600, 49);
end

procedure Node006
begin
    gsay_reply(1677, 700);
    if (global_var(1074) == 3) then begin
        gsay_option(1677, 710, Node007, -1);
    end
    gsay_option(1677, 214, Node999, -1);
end

procedure Node007
begin
    set_global_var(1074, 4);
    mark_area_known(0, 83, 1);
    gsay_message(1677, 800, 49);
end

procedure Node999
begin
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                if ((cur_map_index == 236) or (cur_map_index == 242)) then begin
                    set_global_var(1061, global_var(1061) + -8);
                end
                else begin
                    set_global_var(1062, global_var(1062) + -8);
                end
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if ((cur_map_index == 236) or (cur_map_index == 242)) then begin
            set_global_var(1061, global_var(1061) + -5);
        end
        else begin
            set_global_var(1062, global_var(1062) + -5);
        end
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

