variable global_temp;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure check_hearing;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node12a;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node18a;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node998;
procedure Node999;

import variable doctor_ptr;

variable Only_Once;
variable said_intruder;

procedure Node023;


procedure start
begin
    doctor_ptr := self_obj;
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (local_var(5) == 2) then begin
            set_local_var(5, 1);
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
        else begin
            if (global_var(511) > 0) then begin
                if (said_intruder == 0) then begin
                    call Node022();
                end
            end
            else begin
                if ((metarule(16, 0) - 1 - (party_member_obj(16777687) != 0)) >= 1) then begin
                    call Node021();
                end
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (global_var(511) > 0) then begin
        call Node022();
    end
    else begin
        if ((metarule(16, 0) - 1 - (party_member_obj(16777687) != 0)) >= 1) then begin
            call Node021();
        end
        else begin
            if ((obj_pid(critter_inven_obj(dude_obj, 0)) != 3) and (obj_pid(critter_inven_obj(dude_obj, 0)) != 232) and (obj_pid(critter_inven_obj(dude_obj, 0)) != 348) and (obj_pid(critter_inven_obj(dude_obj, 0)) != 349)) then begin
                call Node020();
            end
            else begin
                if (local_var(4) == 0) then begin
                    set_local_var(4, 1);
                    start_gdialog(1058, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node001();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    start_gdialog(1058, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node015();
                    gsay_end;
                    end_dialogue;
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    set_map_var(11, 1);
    set_global_var(701, 1);
    if (source_obj == dude_obj) then begin
        display_msg(message_str(1058, 800));
        give_exp_points(1000);
        display_msg(message_str(14, 100) + 1000 + message_str(14, 101));
        set_global_var(0, global_var(0) + 20);
        debug_msg("Player gains " + 20 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (source_obj == dude_obj) then begin
            set_global_var(4, global_var(4) + 1);
            if (metarule(51, self_obj) == 2) then begin
                if (source_obj == dude_obj) then begin
                    set_global_var(2, 0);
                    set_global_var(1, global_var(1) + 1);
                    set_global_var(0, global_var(0) + -15);
                    debug_msg("Player gains " + -15 + " Karma Points.");
                    set_global_var(37, 0);
                    set_global_var(38, 0);
                    set_global_var(39, 0);
                    set_global_var(40, 0);
                    set_global_var(41, 0);
                    set_global_var(42, 0);
                    set_global_var(43, 0);
                    set_global_var(44, 0);
                    set_global_var(45, 0);
                    if (global_var(0) >= 1000) then begin
                        set_global_var(37, 1);
                    end
                    else begin
                        if (global_var(0) >= 750) then begin
                            set_global_var(38, 1);
                        end
                        else begin
                            if (global_var(0) >= 500) then begin
                                set_global_var(39, 1);
                            end
                            else begin
                                if (global_var(0) >= 250) then begin
                                    set_global_var(40, 1);
                                end
                                else begin
                                    if (global_var(0) > -250) then begin
                                        set_global_var(41, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -500) then begin
                                            set_global_var(42, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -750) then begin
                                                set_global_var(43, 1);
                                            end
                                            else begin
                                                if (global_var(0) > -1000) then begin
                                                    set_global_var(44, 1);
                                                end
                                                else begin
                                                    set_global_var(45, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    set_global_var(628, global_var(628) + -8);
                    debug_msg("Added " + -8 + " to Town Rep");
                end
            end
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
                set_global_var(3, 1);
                set_global_var(2, 0);
            end
            if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
                set_global_var(2, 1);
                set_global_var(3, 0);
            end
            set_global_var(0, global_var(0) + 5);
            debug_msg("Player gains " + 5 + " Karma Points.");
            set_global_var(37, 0);
            set_global_var(38, 0);
            set_global_var(39, 0);
            set_global_var(40, 0);
            set_global_var(41, 0);
            set_global_var(42, 0);
            set_global_var(43, 0);
            set_global_var(44, 0);
            set_global_var(45, 0);
            if (global_var(0) >= 1000) then begin
                set_global_var(37, 1);
            end
            else begin
                if (global_var(0) >= 750) then begin
                    set_global_var(38, 1);
                end
                else begin
                    if (global_var(0) >= 500) then begin
                        set_global_var(39, 1);
                    end
                    else begin
                        if (global_var(0) >= 250) then begin
                            set_global_var(40, 1);
                        end
                        else begin
                            if (global_var(0) > -250) then begin
                                set_global_var(41, 1);
                            end
                            else begin
                                if (global_var(0) > -500) then begin
                                    set_global_var(42, 1);
                                end
                                else begin
                                    if (global_var(0) > -750) then begin
                                        set_global_var(43, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -1000) then begin
                                            set_global_var(44, 1);
                                        end
                                        else begin
                                            set_global_var(45, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            set_global_var(628, global_var(628) + 2);
            debug_msg("Added " + 2 + " to Town Rep");
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        set_local_var(7, 1);
        display_msg(message_str(1058, 100));
    end
    else begin
        display_msg(message_str(1058, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1058, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (has_trait(1, self_obj, 6) != 153) then begin
            if (not(tile_in_tile_rect(15320, 15308, 20520, 20508, tile_num(self_obj)))) then begin
                critter_add_trait(self_obj, 1, 6, 153);
                set_global_var(511, 1);
            end
        end
        set_local_var(5, 2);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    doctor_ptr := self_obj;
    critter_add_trait(self_obj, 1, 6, 3);
    critter_add_trait(self_obj, 1, 5, 33);
end

procedure map_update_p_proc
begin
    doctor_ptr := self_obj;
end

procedure check_hearing
begin
    if ((tile_distance(tile_num(self_obj), 17315) < 8) or (tile_distance(tile_num(self_obj), 19315) < 8)) then begin
    end
    else begin
        set_global_var(511, 1);
    end
end

procedure Node001
begin
    gsay_reply(1058, 103);
    giq_option(-3, 1058, 104, Node002, 50);
    giq_option(-3, 1058, 105, Node999, 50);
    giq_option(4, 1058, 201, Node002, 50);
    giq_option(4, 1058, 202, Node999, 50);
end

procedure Node002
begin
    if (local_var(14) == 0) then begin
        set_local_var(14, 1);
        gsay_reply(1058, 106);
    end
    else begin
        gsay_reply(1058, 107);
    end
    if (local_var(8) == 0) then begin
        giq_option(-3, 1058, 108, Node003, 50);
    end
    if (local_var(9) == 0) then begin
        giq_option(-3, 1058, 109, Node004, 50);
    end
    if (local_var(10) == 0) then begin
        giq_option(-3, 1058, 110, Node006, 50);
    end
    if (local_var(11) == 0) then begin
        giq_option(-3, 1058, 111, Node007, 50);
    end
    if (local_var(12) == 0) then begin
        giq_option(-3, 1058, 112, Node008, 50);
    end
    if (local_var(13) == 0) then begin
        giq_option(-3, 1058, 113, Node018, 50);
    end
    giq_option(-3, 1058, 114, Node999, 50);
    if (local_var(8) == 0) then begin
        giq_option(4, 1058, 115, Node003, 50);
    end
    if (local_var(9) == 0) then begin
        giq_option(4, 1058, 116, Node004, 50);
    end
    if (local_var(10) == 0) then begin
        giq_option(4, 1058, 117, Node006, 50);
    end
    if (local_var(11) == 0) then begin
        giq_option(4, 1058, 118, Node007, 50);
    end
    if (local_var(12) == 0) then begin
        giq_option(4, 1058, 119, Node008, 50);
    end
    if (local_var(13) == 0) then begin
        giq_option(4, 1058, 120, Node018, 50);
    end
    giq_option(4, 1058, 121, Node999, 50);
end

procedure Node003
begin
    set_local_var(8, 1);
    gsay_reply(1058, 122);
    giq_option(-3, 1058, 123, Node002, 50);
    giq_option(4, 1058, 124, Node002, 50);
end

procedure Node004
begin
    set_local_var(9, 1);
    gsay_reply(1058, 125);
    giq_option(-3, 1058, 126, Node005, 50);
    giq_option(4, 1058, 127, Node005, 50);
end

procedure Node005
begin
    gsay_reply(1058, 128);
    giq_option(-3, 1058, 129, Node002, 50);
    giq_option(4, 1058, 130, Node002, 50);
end

procedure Node006
begin
    set_local_var(10, 1);
    gsay_reply(1058, 131);
    giq_option(-3, 1058, 132, Node002, 50);
    giq_option(4, 1058, 133, Node002, 50);
end

procedure Node007
begin
    set_local_var(11, 1);
    if (get_critter_stat(dude_obj, 4) < 4) then begin
        gsay_reply(1058, 134);
    end
    else begin
        gsay_reply(1058, 135);
    end
    giq_option(-3, 1058, 136, Node002, 50);
    giq_option(4, 1058, 137, Node002, 50);
end

procedure Node008
begin
    set_map_var(4, 1);
    set_local_var(12, 1);
    gsay_reply(1058, 138);
    giq_option(-3, 1058, 139, Node009, 50);
    giq_option(4, 1058, 140, Node010, 50);
end

procedure Node009
begin
    gsay_reply(1058, 141);
    giq_option(-3, 1058, 142, Node010, 50);
end

procedure Node010
begin
    gsay_reply(1058, 143);
    giq_option(-3, 1058, 144, Node011, 50);
    giq_option(4, 1058, 145, Node011, 50);
end

procedure Node011
begin
    gsay_reply(1058, 146);
    giq_option(1, 1058, 147, Node012, 50);
end

procedure Node012
begin
    gsay_reply(1058, 148);
    giq_option(1, 1058, 200, Node12a, 50);
end

procedure Node12a
begin
    gsay_reply(1058, 149);
    giq_option(-3, 1058, 150, Node013, 50);
    giq_option(4, 1058, 151, Node013, 50);
end

procedure Node013
begin
    if (global_var(554) < 2) then begin
        set_global_var(554, 1);
    end
    set_map_var(4, 1);
    gsay_reply(1058, 152);
    giq_option(-3, 1058, 153, Node002, 50);
    giq_option(-3, 1058, 154, Node014, 50);
    giq_option(-3, 1058, 155, Node017, 50);
    giq_option(4, 1058, 156, Node017, 50);
    giq_option(4, 1058, 157, Node002, 50);
    giq_option(4, 1058, 158, Node014, 50);
end

procedure Node014
begin
    gsay_reply(1058, 159);
    giq_option(-3, 1058, 160, Node002, 50);
    giq_option(-3, 1058, 161, Node998, 51);
    giq_option(4, 1058, 162, Node002, 50);
    giq_option(4, 1058, 163, Node998, 51);
end

procedure Node015
begin
    gsay_reply(1058, 164);
    if (map_var(4) == 1) then begin
        giq_option(-3, 1058, 165, Node016, 50);
    end
    giq_option(-3, 1058, 166, Node002, 50);
    giq_option(-3, 1058, 167, Node999, 50);
    if (map_var(4) == 1) then begin
        giq_option(4, 1058, 168, Node016, 50);
    end
    giq_option(4, 1058, 169, Node002, 50);
    giq_option(4, 1058, 170, Node999, 50);
end

procedure Node016
begin
    gsay_reply(1058, 171);
    giq_option(-3, 1058, 172, Node999, 50);
    giq_option(-3, 1058, 173, Node998, 51);
    giq_option(4, 1058, 174, Node999, 50);
    giq_option(4, 1058, 175, Node998, 51);
end

procedure Node017
begin
    gsay_reply(1058, 176);
    giq_option(1, 1058, 177, Node999, 50);
end

procedure Node018
begin
    if (global_var(513) == 0) then begin
        set_global_var(513, 1);
    end
    set_local_var(13, 1);
    gsay_reply(1058, 178);
    giq_option(1, 1058, 200, Node18a, 50);
end

procedure Node18a
begin
    gsay_reply(1058, 179);
    giq_option(-3, 1058, 180, Node002, 50);
    giq_option(-3, 1058, 181, Node019, 50);
    giq_option(4, 1058, 182, Node002, 50);
    giq_option(4, 1058, 183, Node019, 50);
end

procedure Node019
begin
    gsay_reply(1058, 184);
    giq_option(-3, 1058, 185, Node002, 50);
    giq_option(4, 1058, 186, Node002, 50);
end

procedure Node020
begin
    float_msg(self_obj, message_str(1058, random(187, 189)), 8);
end

procedure Node021
begin
    if (has_trait(1, self_obj, 6) == 153) then begin
        set_global_var(511, 1);
    end
    float_msg(self_obj, message_str(1058, random(190, 192)), 8);
end

procedure Node022
begin
    said_intruder := 1;
    float_msg(self_obj, message_str(1058, random(193, 195)), 8);
end

procedure Node998
begin
    set_local_var(5, 2);
    if (has_trait(1, self_obj, 6) == 153) then begin
        set_global_var(511, 1);
    end
end

procedure Node999
begin
end

procedure Node023
begin
    float_msg(self_obj, message_str(1058, random(196, 198)), 8);
end

