variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable caught_thief;
variable the_follow_obj;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure use_p_proc;
procedure push_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node998;
procedure Node996;
procedure Node995;

variable sex_cost;

procedure Node999;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj) and ((local_var(0) bwand 2) != 0)) then begin
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
    else begin
        if (tile_num(self_obj) != local_var(2)) then begin
            animate_move_obj_to_tile(self_obj, local_var(2), 0);
        end
        else begin
            if (has_trait(1, self_obj, 10) != local_var(3)) then begin
                anim(self_obj, 1000, local_var(3));
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure talk_p_proc
begin
    script_overrides;
    sex_cost := (11 - get_critter_stat(dude_obj, 3)) * 100 * (1 + (metarule(16, 0) - 1)) / (1 + ((((local_var(1) < game_time) and (local_var(1) != 0)) == 0) and is_success(do_check(dude_obj, 6, 0))));
    if (((local_var(1) < game_time) and (local_var(1) != 0)) == 0) then begin
        set_local_var(1, 0);
        set_local_var(1, game_time + (24 * (60 * (60 * 10))));
    end
    if (in_dialog == 0) then begin
        in_dialog := 1;
        start_gdialog(54, self_obj, 4, -1, -1);
        gsay_start;
        call Node995();
        gsay_end;
        end_dialogue;
        in_dialog := 0;
    end
    else begin
        call Node995();
    end
    set_local_var(0, local_var(0) bwor 1);
end

procedure destroy_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(54, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(54, 150));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure map_enter_p_proc
begin
    if (metarule(22, 0) == 0) then begin
        if ((global_var(445) bwand 2) != 0) then begin
            destroy_object(self_obj);
        end
        if (metarule(14, 0)) then begin
            critter_add_trait(self_obj, 1, 6, 16);
            critter_add_trait(self_obj, 1, 5, 14);
            set_local_var(2, tile_num(self_obj));
        end
    end
end

procedure use_p_proc
begin
    float_msg(self_obj, message_str(54, 222), 8);
end

procedure push_p_proc
begin
    if (tile_num(self_obj) == local_var(2)) then begin
        script_overrides;
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 4) then begin
        start_gdialog(54, self_obj, 4, -1, -1);
        gsay_start;
        if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) >= 9) then begin
            call Node009();
        end
        else begin
            if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) >= 7) then begin
                call Node010();
            end
            else begin
                if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) >= 5) then begin
                    call Node011();
                end
                else begin
                    call Node012();
                end
            end
        end
        gsay_end;
        end_dialogue;
    end
end

procedure Node001
begin
    gsay_reply(54, 153);
    giq_option(4, 54, 154, Node999, 50);
    giq_option(4, 54, 155, Node999, 50);
    giq_option(-3, 54, 156, Node999, 50);
end

procedure Node002
begin
    gsay_reply(54, 157);
    giq_option(6, 54, 158, Node006, 50);
    giq_option(4, 54, 159, Node006, 50);
    giq_option(4, 54, 160, Node999, 50);
    giq_option(-3, 54, 161, Node006, 50);
end

procedure Node003
begin
    gsay_reply(54, 162);
    giq_option(4, 54, 163, Node006, 50);
    giq_option(4, 54, 164, Node006, 50);
    giq_option(4, 54, 165, Node007, 50);
    giq_option(-3, 54, 166, Node004, 50);
end

procedure Node004
begin
    gsay_reply(54, 167);
    giq_option(-3, 54, 168, Node006, 50);
    giq_option(-3, 54, 169, Node006, 50);
    giq_option(-3, 54, 170, Node999, 50);
end

procedure Node005
begin
    gsay_reply(54, 171);
    giq_option(6, 54, 172, Node006, 50);
    giq_option(4, 54, 173, Node006, 50);
    giq_option(4, 54, 174, Node007, 50);
end

procedure Node006
begin
    gsay_reply(54, message_str(54, 213) + sex_cost + message_str(54, 214));
    giq_option(1, 54, 176, Node996, 50);
    giq_option(1, 54, 177, Node007, 50);
end

procedure Node007
begin
    gsay_reply(54, 178);
    giq_option(4, 54, 179, Node999, 50);
    giq_option(4, 54, 180, Node999, 50);
    giq_option(-3, 54, 181, Node999, 50);
end

procedure Node008
begin
    gsay_reply(54, 182);
    giq_option(4, 54, 183, Node999, 50);
    giq_option(4, 54, 184, Node007, 50);
    giq_option(-3, 54, 185, Node999, 50);
end

procedure Node009
begin
    gsay_reply(54, 186);
    giq_option(4, 54, 187, Node013, 50);
    giq_option(4, 54, 188, Node013, 50);
    giq_option(4, 54, 189, Node013, 50);
    giq_option(-3, 54, 190, Node013, 50);
end

procedure Node010
begin
    gsay_reply(54, 191);
    giq_option(4, 54, 192, Node013, 50);
    giq_option(4, 54, 193, Node013, 50);
    giq_option(4, 54, 194, Node014, 50);
    giq_option(-3, 54, 195, Node013, 50);
end

procedure Node011
begin
    gsay_reply(54, 196);
    giq_option(4, 54, 197, Node007, 50);
    giq_option(4, 54, 198, Node999, 50);
    giq_option(4, 54, 199, Node013, 50);
    giq_option(-3, 54, 200, Node999, 50);
end

procedure Node012
begin
    if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) > 2) then begin
        gsay_reply(54, 201);
    end
    else begin
        gsay_reply(54, 230);
    end
    giq_option(4, 54, 202, Node007, 50);
    giq_option(4, 54, 203, Node007, 50);
    giq_option(4, 54, 204, Node999, 50);
    giq_option(-3, 54, 205, Node999, 50);
end

procedure Node013
begin
    gsay_reply(54, 206);
    giq_option(4, 54, 207, Node999, 50);
    giq_option(4, 54, 208, Node007, 50);
    giq_option(-3, 54, 209, Node999, 50);
end

procedure Node014
begin
    gsay_reply(54, 210);
    giq_option(4, 54, 211, Node999, 50);
    giq_option(-3, 54, 212, Node999, 50);
end

procedure Node998
begin
    set_local_var(0, local_var(0) bwor 2);
end

procedure Node996
begin
    if (item_caps_total(dude_obj) >= sex_cost) then begin
        gfade_out(10);
        game_time_advance(get_critter_stat(dude_obj, 2) * random(4, 8) * (60 * 10));
        set_global_var(194, global_var(194) + (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) * 1));
        if (global_var(358) >= 9) then begin
            set_global_var(588, 1);
        end
        if (((((get_critter_stat(dude_obj, 3) * 50) + (get_critter_stat(dude_obj, 2) * 25) + (get_critter_stat(dude_obj, 5) * 13) + (get_critter_stat(dude_obj, 0) * 12)) / 100) + (has_trait(0, dude_obj, 94) * 2) + has_trait(2, dude_obj, 13) + (((global_var(194) >= 100) or (global_var(232) > 0)) * 2 * (dude_obj == dude_obj))) >= 9) then begin
            set_global_var(589, 1);
        end
        set_global_var(358, global_var(358) + 1);
        item_caps_adjust(self_obj, sex_cost);
        item_caps_adjust(dude_obj, -sex_cost);
        critter_attempt_placement(self_obj, 12908, elevation(self_obj));
        move_to(self_obj, tile_num(self_obj), elevation(self_obj));
        critter_attempt_placement(dude_obj, 12707, elevation(self_obj));
        move_to(dude_obj, tile_num(dude_obj), elevation(self_obj));
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), tile_num(dude_obj)));
        anim(dude_obj, 1000, rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)));
        metarule3(100, self_obj, 4, 0);
        add_timer_event(self_obj, game_ticks(1), 4);
        gfade_in(10);
    end
    else begin
        call Node008();
    end
end

procedure Node995
begin
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        call Node001();
    end
    else begin
        if ((metarule(16, 0) - 1) > 0) then begin
            call Node002();
        end
        else begin
            if (get_critter_stat(dude_obj, 3) > 8) then begin
                call Node003();
            end
            else begin
                if (get_critter_stat(dude_obj, 4) < 4) then begin
                    call Node004();
                end
                else begin
                    if (get_critter_stat(dude_obj, 0) > 7) then begin
                        call Node005();
                    end
                    else begin
                        call Node006();
                    end
                end
            end
        end
    end
end

procedure Node999
begin
end

