variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;
variable caught_thief;
variable the_follow_obj;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;

import variable vic_door_guard_obj;
import variable vic_door_obj;

variable door_was_locked;

procedure Node990;
procedure Node989;
procedure Node988;
procedure Node987;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    vic_door_guard_obj := self_obj;
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (((local_var(4) bwand 2) != 0) or ((global_var(446) bwand 16777216) != 0)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
    else begin
        if (tile_num(self_obj) != local_var(7)) then begin
            animate_move_obj_to_tile(self_obj, local_var(7), 0);
        end
        else begin
            if (has_trait(1, self_obj, 10) != local_var(8)) then begin
                anim(self_obj, 1000, local_var(8));
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure talk_p_proc
begin
    if (((local_var(4) bwand 2) != 0) or ((global_var(446) bwand 16777216) != 0)) then begin
        call Node021();
    end
    else begin
        if ((global_var(445) bwand 134217728) != 0) then begin
            call Node026();
        end
        else begin
            if (in_dialog == 0) then begin
                in_dialog := 1;
                start_gdialog(914, self_obj, 4, -1, -1);
                gsay_start;
                call Node004();
                gsay_end;
                end_dialogue;
                in_dialog := 0;
            end
            else begin
                call Node004();
            end
        end
    end
    set_local_var(4, local_var(4) bwor 1);
end

procedure destroy_p_proc
begin
    vic_door_guard_obj := 0;
    if (source_obj == dude_obj) then begin
        set_global_var(4, global_var(4) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) - -15);
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        set_global_var(0, global_var(0) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(914, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(914, 150));
    set_local_var(4, local_var(4) bwor 4);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, local_var(4) bwor 8);
        set_local_var(4, local_var(4) bwor 2);
        set_global_var(446, global_var(446) bwor 16777216);
    end
end

procedure map_enter_p_proc
begin
    vic_door_guard_obj := self_obj;
    if (metarule(22, 0) == 0) then begin
        if (metarule(14, 0)) then begin
            critter_add_trait(self_obj, 1, 6, 12);
            critter_add_trait(self_obj, 1, 5, 16);
            set_local_var(7, tile_num(self_obj));
            set_local_var(8, has_trait(1, self_obj, 10));
        end
        if (tile_num(self_obj) != local_var(7)) then begin
            critter_attempt_placement(self_obj, local_var(7), elevation(self_obj));
        end
        if (has_trait(1, self_obj, 10) != local_var(8)) then begin
            anim(self_obj, 1000, local_var(8));
        end
    end
end

procedure map_exit_p_proc
begin
end

procedure timed_event_p_proc
begin
    if (fixed_param == 0) then begin
    end
    else begin
        if (fixed_param == 6) then begin
            call Node001();
        end
        else begin
            if (fixed_param == 7) then begin
                call Node002();
            end
            else begin
                if (fixed_param == 9) then begin
                    call Node003();
                end
            end
        end
    end
end

procedure Node998
begin
    set_local_var(4, local_var(4) bwor 2);
    set_global_var(446, global_var(446) bwor 16777216);
end

procedure Node999
begin
end

procedure Node001
begin
    if ((local_var(4) bwand 512) != 0) then begin
        float_msg(self_obj, message_str(914, 201), 8);
        call Node998();
    end
    else begin
        float_msg(self_obj, message_str(914, 200), 8);
        set_local_var(4, local_var(4) bwor 512);
    end
end

procedure Node002
begin
    float_msg(self_obj, message_str(914, local_var(5)), 8);
    if (local_var(5) < 2) then begin
        set_local_var(5, local_var(5) + 1);
    end
end

procedure Node003
begin
    float_msg(self_obj, message_str(914, 220), 8);
end

procedure Node004
begin
    if (global_var(11) == 1) then begin
        gsay_reply(914, 231 + ((local_var(4) bwand 1024) != 0));
        set_local_var(4, local_var(4) bwor 1024);
        giq_option(4, 914, 236, Node999, 50);
    end
    else begin
        gsay_reply(914, 230);
        giq_option(4, 914, 235, Node999, 50);
        giq_option(-3, 914, 237, Node020, 50);
    end
    if (global_var(452) == 2) then begin
        giq_option(4, 914, 234, Node005, 50);
        giq_option(-3, 914, 238, Node015, 50);
    end
    else begin
        giq_option(4, 914, 233, Node005, 50);
    end
    giq_option(-3, 914, 239, Node014, 50);
    giq_option(-3, 914, 240, Node014, 50);
end

procedure Node005
begin
    if ((local_var(4) bwand 2048) != 0) then begin
        gsay_reply(914, 254);
    end
    else begin
        set_local_var(4, local_var(4) bwor 2048);
        if (global_var(452) == 2) then begin
            gsay_reply(914, 250 + (global_var(11) == 1));
        end
        else begin
            gsay_reply(914, 252 + (global_var(11) == 1));
        end
    end
    if (2 > global_var(452)) then begin
        set_global_var(452, 2);
    end
    giq_option(4, 914, 255, Node010, 50);
    if (((global_var(445) bwand 32768) != 0) == 0) then begin
        giq_option(4, 914, 256, Node010, 50);
    end
    if ((global_var(457) == 2) == 0) then begin
        giq_option(4, 914, 257, Node990, 50);
    end
    else begin
        if (vic_door_obj != 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                giq_option(4, 914, 260, Node009, 50);
            end
        end
    end
    if (metarule(40, 13) or (has_skill(dude_obj, 13) >= 60)) then begin
        giq_option(4, 914, 258, Node017, 49);
    end
    if (metarule(40, 12) or (has_skill(dude_obj, 12) >= 60)) then begin
        giq_option(4, 914, 259, Node017, 49);
    end
    giq_option(4, 914, 261, Node999, 50);
end

procedure Node006
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            metarule3(100, self_obj, 9, 0);
            add_timer_event(self_obj, 1, 9);
        end
    end
    if (global_var(457) == 1) then begin
        item_caps_adjust(dude_obj, -300);
        if (2 > global_var(457)) then begin
            set_global_var(457, 2);
        end
        gsay_reply(914, 275);
    end
    else begin
        gsay_reply(914, 276);
    end
    if (2 > global_var(457)) then begin
        set_global_var(457, 2);
    end
    set_global_var(445, global_var(445) bwor 32768);
    giq_option(4, 914, 277, Node999, 50);
end

procedure Node007
begin
    gsay_reply(914, 285 + ((global_var(446) bwand 4194304) != 0));
    if (((global_var(445) bwand 32768) != 0) == 0) then begin
        giq_option(4, 914, 287, Node010, 50);
    end
    if ((global_var(457) == 2) == 0) then begin
        giq_option(4, 914, 257, Node990, 50);
    end
    giq_option(4, 914, 290, Node999, 50);
end

procedure Node008
begin
    if (2 > global_var(457)) then begin
        set_global_var(457, 2);
    end
    gsay_reply(914, 295 + ((global_var(11) == 1) == 0));
    if (vic_door_obj != 0) then begin
        if (obj_is_locked(vic_door_obj)) then begin
            giq_option(4, 914, 297, Node009, 50);
        end
    end
    giq_option(4, 914, 298, Node999, 50);
end

procedure Node009
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            metarule3(100, self_obj, 9, 0);
            add_timer_event(self_obj, 1, 9);
        end
    end
    if (2 > global_var(457)) then begin
        set_global_var(457, 2);
    end
    gsay_reply(914, 305);
    giq_option(4, 914, 306, Node999, 50);
end

procedure Node010
begin
    gsay_reply(914, 310);
    giq_option(4, 914, 311, Node012, 50);
    giq_option(4, 914, 312, Node011, 50);
    giq_option(4, 914, 313, Node999, 50);
end

procedure Node011
begin
    gsay_reply(914, 320);
    giq_option(4, 914, 321, Node999, 51);
    giq_option(4, 914, 322, Node999, 49);
end

procedure Node012
begin
    gsay_reply(914, 330 + (get_critter_stat(dude_obj, 34) == 1));
    giq_option(4, 914, 332, Node013, 50);
    giq_option(4, 914, 333, Node999, 50);
end

procedure Node013
begin
    gsay_reply(914, 340);
    giq_option(4, 914, 341, Node999, 50);
end

procedure Node014
begin
    gsay_reply(914, 350);
    giq_option(-3, 914, 351, Node999, 50);
end

procedure Node015
begin
    gsay_reply(914, 360 + (global_var(11) == 1));
    giq_option(-3, 914, 362, Node016, 49);
    giq_option(-3, 914, 363, Node014, 50);
    giq_option(-3, 914, 364, Node999, 50);
end

procedure Node016
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            metarule3(100, self_obj, 9, 0);
            add_timer_event(self_obj, 1, 9);
        end
    end
    gsay_reply(914, 370 + door_was_locked);
    if (2 > global_var(457)) then begin
        set_global_var(457, 2);
    end
    giq_option(-3, 914, 372, Node999, 50);
end

procedure Node017
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            metarule3(100, self_obj, 9, 0);
            add_timer_event(self_obj, 1, 9);
        end
    end
    gsay_reply(914, 380);
    giq_option(4, 914, 381, Node999, 50);
end

procedure Node018
begin
    if (global_var(457) == 1) then begin
        gsay_reply(914, 392);
        if (item_caps_total(dude_obj) >= 300) then begin
            giq_option(4, 914, 395, Node006, 50);
        end
        giq_option(4, 914, 396, Node999, 50);
    end
    else begin
        if ((local_var(4) bwand 4096) != 0) then begin
            gsay_reply(914, 391);
            if (global_var(457) == 0) then begin
                giq_option(4, 914, 394, Node022, 50);
            end
        end
        else begin
            set_local_var(4, local_var(4) bwor 4096);
            gsay_reply(914, 390);
            if (global_var(457) == 0) then begin
                giq_option(4, 914, 393, Node022, 50);
            end
        end
    end
    if (((global_var(445) bwand 32768) != 0) == 0) then begin
        giq_option(4, 914, 397, Node010, 50);
    end
    giq_option(4, 914, 398, Node999, 50);
end

procedure Node019
begin
    if (local_var(6) <= 2) then begin
        gsay_reply(914, 410 + local_var(6));
        set_local_var(6, local_var(6) + 1);
        giq_option(4, 914, 414, Node999, 50);
    end
    else begin
        gsay_reply(914, 413);
        door_was_locked := 0;
        if (vic_door_obj != 0) then begin
            if (obj_is_open(vic_door_obj) == 0) then begin
                if (obj_is_locked(vic_door_obj)) then begin
                    door_was_locked := 1;
                    obj_unlock(vic_door_obj);
                end
                obj_open(vic_door_obj);
                metarule3(100, self_obj, 9, 0);
                add_timer_event(self_obj, 1, 9);
            end
        end
        if (2 > global_var(457)) then begin
            set_global_var(457, 2);
        end
        giq_option(4, 914, 415, Node999, 50);
    end
end

procedure Node020
begin
    if ((local_var(4) bwand 8192) != 0) then begin
        gsay_reply(914, 432);
    end
    else begin
        set_local_var(4, local_var(4) bwor 8192);
        gsay_reply(914, 430 + (get_critter_stat(dude_obj, 34) == 1));
    end
    giq_option(-3, 914, 433, Node014, 50);
    giq_option(-3, 914, 434, Node999, 50);
    giq_option(-3, 914, 435, Node999, 50);
end

procedure Node021
begin
    float_msg(self_obj, message_str(914, 450 + (get_critter_stat(dude_obj, 34) == 1)), 8);
    call Node998();
end

procedure Node022
begin
    gsay_reply(914, 460);
    giq_option(4, 914, 461, Node989, 50);
    giq_option(4, 914, 462, Node988, 50);
    giq_option(4, 914, 463, Node999, 50);
end

procedure Node023
begin
    if (1 > global_var(457)) then begin
        set_global_var(457, 1);
    end
    gsay_reply(914, 470);
    giq_option(4, 914, 471, Node024, 50);
    giq_option(4, 914, 472, Node987, 51);
    if (item_caps_total(dude_obj) >= 300) then begin
        giq_option(4, 914, 473, Node006, 50);
    end
    giq_option(4, 914, 474, Node999, 50);
end

procedure Node024
begin
    gsay_reply(914, 480);
    giq_option(4, 914, 481, Node999, 50);
    giq_option(4, 914, 482, Node999, 51);
end

procedure Node025
begin
    if ((local_var(4) bwand 16384) != 0) then begin
        if (3 > global_var(457)) then begin
            set_global_var(457, 3);
        end
        gsay_reply(914, 491);
    end
    else begin
        set_local_var(4, local_var(4) bwor 16384);
        gsay_reply(914, 490);
    end
    giq_option(4, 914, 492, Node999, 50);
end

procedure Node026
begin
    if (((global_var(445) bwand 32) != 0) == 0) then begin
        float_msg(self_obj, message_str(914, random(503, 504)), 8);
    end
    else begin
        if (global_var(11) == 1) then begin
            float_msg(self_obj, message_str(914, random(505, 507)), 8);
        end
        else begin
            float_msg(self_obj, message_str(914, random(500, 502)), 8);
        end
    end
end

procedure Node990
begin
    if ((global_var(11) == 1) or (global_var(457) == 2)) then begin
        call Node009();
    end
    else begin
        if ((global_var(446) bwand 4194304) != 0) then begin
            call Node008();
        end
        else begin
            if (global_var(457) == 3) then begin
                call Node019();
            end
            else begin
                call Node018();
            end
        end
    end
end

procedure Node989
begin
    if (metarule(40, 13) or is_success(roll_vs_skill(dude_obj, 14, -10))) then begin
        if (2 > global_var(457)) then begin
            set_global_var(457, 2);
        end
        call Node006();
    end
    else begin
        call Node025();
    end
end

procedure Node988
begin
    if (is_success(roll_vs_skill(dude_obj, 15, -20))) then begin
        call Node023();
    end
    else begin
        call Node025();
    end
end

procedure Node987
begin
    if (3 > global_var(457)) then begin
        set_global_var(457, 3);
    end
    call Node024();
end

