variable SVar3;
variable SVar5 := 50;
variable SVar6 := 2;
variable SVar7;
variable SVar8;
variable SVar9;

procedure start;
procedure damage_p_proc;
procedure talk_p_proc;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure do_dialogue;
procedure run_away;
procedure weapon_check;
procedure go_forward;
procedure Node999;
procedure Node000;
procedure Node001;
procedure Node002;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;

import variable dog_is_angry;
import variable Phil_approaches;
import variable growling;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;

variable known;


procedure start
begin
    if (local_var(0) == 0) then begin
        set_local_var(0, 1);
        critter_add_trait(self_obj, 1, 6, 184);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure talk_p_proc
begin
    call do_dialogue();
end

procedure critter_p_proc
begin
    if (fixed_param == 2) then begin
        float_msg(self_obj, message_str(1493, 102), 0);
    end
    if (dog_is_angry == 0) then begin
        animate_move_obj_to_tile(self_obj, 15686, 0);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(808, global_var(808) + -5);
                debug_msg("Added " + -5 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -5);
        debug_msg("Player gains " + -5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(808, global_var(808) + -3);
        debug_msg("Added " + -3 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (known == 1) then begin
        display_msg(message_str(1493, 101));
    end
    else begin
        display_msg(message_str(1493, 100));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1493, 100));
end

procedure do_dialogue
begin
    call weapon_check();
    if (dog_is_angry and (map_var(0) == 1)) then begin
        call Node001();
    end
    else begin
        if (not(dog_is_angry)) then begin
            call Node009();
        end
        else begin
            if (map_var(0) == 0) then begin
                start_gdialog(1493, self_obj, 4, -1, -1);
                gsay_start;
                call Node002();
                gsay_end;
                end_dialogue;
            end
            else begin
                call Node008();
            end
        end
    end
end

procedure run_away
begin
    float_msg(self_obj, message_str(1493, 124), 0);
    animate_move_obj_to_tile(self_obj, 16892, 1);
    growling := 0;
    add_timer_event(self_obj, game_ticks(random(10, 30)), 1);
end

procedure weapon_check
begin
    if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
        SVar3 := 1;
    end
    else begin
        SVar3 := 0;
    end
end

procedure go_forward
begin
    Phil_approaches := 1;
    animate_move_obj_to_tile(self_obj, 16886, 0);
end

procedure Node999
begin
end

procedure Node000
begin
    float_msg(self_obj, message_str(1493, 103), 0);
end

procedure Node001
begin
    float_msg(self_obj, message_str(1493, 104), 0);
end

procedure Node002
begin
    set_map_var(0, 1);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1493, message_str(1493, 105) + message_str(1493, 107));
    end
    else begin
        gsay_reply(1493, message_str(1493, 106) + message_str(1493, 107));
    end
    giq_option(4, 1493, 108, Node004, 50);
    giq_option(4, 1493, 109, Node999, 50);
    giq_option(4, 1493, 110, Node005, 50);
    giq_option(4, 1493, 111, Node004, 50);
end

procedure Node004
begin
    gsay_reply(1493, 113);
    giq_option(4, 1493, 114, Node999, 50);
    giq_option(4, 1493, 115, Node005, 50);
end

procedure Node005
begin
    gsay_reply(1493, 116);
    giq_option(4, 1493, 117, Node999, 50);
    giq_option(4, 1493, 118, Node006, 50);
    giq_option(4, 1493, 119, Node007, 50);
end

procedure Node006
begin
    gsay_reply(1493, 120);
    giq_option(4, 1493, 122, Node007, 50);
end

procedure Node007
begin
    gsay_reply(1493, 123);
    giq_option(4, 1493, 125, Node999, 50);
end

procedure Node008
begin
    float_msg(self_obj, message_str(1493, 126), 0);
end

procedure Node009
begin
    float_msg(self_obj, message_str(1493, 127), 0);
end

procedure get_reaction
begin
    if (not(SVar7)) then begin
        SVar7 := 1;
        SVar5 := SVar5 + ((get_critter_stat(dude_obj, 3) - 5) * 5);
        if (not(SVar8 == 1)) then begin
            SVar5 := SVar5 - global_var(808);
        end
        else begin
            SVar5 := SVar5 + global_var(808);
        end
        if (global_var(1) > 2) then begin
            SVar5 := SVar5 - 30;
        end
        if ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) then begin
            SVar5 := SVar5 + 20;
        end
        if ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1)) then begin
            SVar5 := SVar5 - 20;
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (SVar5 < 24) then begin
        SVar6 := 1;
    end
    else begin
        if (SVar5 < 74) then begin
            SVar6 := 2;
        end
        else begin
            SVar6 := 3;
        end
    end
end

procedure LevelToReact
begin
    if (SVar6 == 1) then begin
        SVar5 := random(1, 24);
    end
    else begin
        if (SVar6 == 2) then begin
            SVar5 := random(25, 74);
        end
        else begin
            SVar5 := random(75, 100);
        end
    end
end

procedure UpReact
begin
    SVar5 := SVar5 + 10;
    call ReactToLevel();
end

procedure DownReact
begin
    SVar5 := SVar5 - 10;
    call ReactToLevel();
end

procedure BottomReact
begin
    SVar6 := 1;
    SVar5 := 1;
end

procedure TopReact
begin
    SVar5 := 100;
    SVar6 := 3;
end

procedure BigUpReact
begin
    SVar5 := SVar5 + 25;
    call ReactToLevel();
end

procedure BigDownReact
begin
    SVar5 := SVar5 - 25;
    call ReactToLevel();
end

procedure UpReactLevel
begin
    SVar6 := SVar6 + 1;
    if (SVar6 > 3) then begin
        SVar6 := 3;
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    SVar6 := SVar6 - 1;
    if (SVar6 < 1) then begin
        SVar6 := 1;
    end
    call LevelToReact();
end

