variable SVar1;
variable SVar2;
variable SVar3;

procedure start;
procedure damage_p_proc;
procedure look_at_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure do_dialogue;
procedure go_inside;
procedure weapon_check;
procedure PeasantD00;
procedure PeasantD01;
procedure PeasantD02;
procedure PeasantD03;
procedure PeasantD04;

import variable dog_is_angry;
import variable smartass;
import variable smartass2;


procedure start
begin
    if (not(local_var(0))) then begin
        critter_add_trait(self_obj, 1, 6, 184);
        set_local_var(0, 1);
        add_timer_event(self_obj, 50, 1);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure look_at_proc
begin
    script_overrides;
    display_msg(message_str(1492, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1492, 100));
end

procedure timed_event_p_proc
begin
    if (dog_is_angry) then begin
        if (fixed_param == 1) then begin
            call PeasantD00();
            add_timer_event(self_obj, 100, 1);
        end
    end
end

procedure critter_p_proc
begin
    if (not(dog_is_angry)) then begin
        call go_inside();
    end
end

procedure talk_p_proc
begin
    call weapon_check();
    if (not(dog_is_angry)) then begin
        call PeasantD04();
    end
    else begin
        if (dog_is_angry) then begin
            call PeasantD02();
        end
        else begin
            if (SVar2) then begin
                call PeasantD01();
            end
            else begin
                call PeasantD03();
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(808, global_var(808) + -5);
                debug_msg("Added " + -5 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -5);
        debug_msg("Player gains " + -5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(808, global_var(808) + -5);
        debug_msg("Added " + -4 + " to Town Rep");
    end
end

procedure do_dialogue
begin
end

procedure go_inside
begin
    animate_move_obj_to_tile(self_obj, 15283, 0);
end

procedure weapon_check
begin
    if ((obj_item_subtype(critter_inven_obj(dude_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(dude_obj, 2)) == 3)) then begin
        SVar2 := 1;
    end
    else begin
        SVar2 := 0;
    end
end

procedure PeasantD00
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    LVar0 := random(1, 3);
    if (LVar0 == 1) then begin
        LVar1 := message_str(1492, 101);
    end
    else begin
        if (LVar0 == 2) then begin
            LVar1 := message_str(1492, 102);
        end
        else begin
            LVar1 := message_str(1492, 103);
        end
    end
    if (dog_is_angry) then begin
        float_msg(self_obj, LVar1, 0);
    end
    smartass2 := 0;
    return 0;
    LVar0 := 0;
    LVar1 := 0;
end

procedure PeasantD01
begin
    if (dog_is_angry) then begin
        float_msg(self_obj, message_str(1492, 104), 0);
    end
end

procedure PeasantD02
begin
    if (dog_is_angry) then begin
        float_msg(self_obj, message_str(1492, 105), 0);
    end
end

procedure PeasantD03
begin
    float_msg(self_obj, message_str(1492, 106), 0);
    smartass := 1;
end

procedure PeasantD04
begin
    float_msg(self_obj, message_str(1492, 107), 0);
end

