procedure checkPartyMembersNearDoor;

variable tmp_gen_rep;
variable global_temp;

procedure start;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure Node999;
procedure Node998;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure critter_p_proc;
procedure timed_event_p_proc;
procedure pickup_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777874) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777874)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777875) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777875)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777876) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777876)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777801) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777801)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777762) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777762)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777859) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777859)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(2069, 100));
    end
    else begin
        display_msg(message_str(2069, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(2069, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (local_var(5) == 0) then begin
        set_map_var(0, 1);
        set_local_var(5, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(4, global_var(4) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        set_global_var(0, global_var(0) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        tmp_gen_rep := global_var(0);
        if (has_trait(0, dude_obj, 95)) then begin
            tmp_gen_rep := global_var(0) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
    start_gdialog(2069, self_obj, 4, -1, -1);
    gsay_start;
    if (local_var(4) == 0) then begin
        call Node001();
        set_local_var(4, 1);
    end
    else begin
        call Node008();
    end
    gsay_end;
    end_dialogue;
end

procedure Node999
begin
end

procedure Node998
begin
    set_map_var(0, 1);
    set_local_var(5, 1);
end

procedure Node001
begin
    gsay_reply(2069, 200);
    giq_option(4, 2069, 201, Node002, 50);
    giq_option(4, 2069, 202, Node003, 50);
end

procedure Node002
begin
    gsay_reply(2069, 210);
    giq_option(4, 2069, 220, Node004, 50);
    giq_option(4, 2069, 221, Node999, 50);
end

procedure Node003
begin
    gsay_reply(2069, 211);
    giq_option(4, 2069, 220, Node004, 50);
    giq_option(4, 2069, 221, Node999, 50);
end

procedure Node004
begin
    gsay_reply(2069, 230);
    giq_option(4, 2069, 240, Node005, 50);
end

procedure Node005
begin
    gsay_reply(2069, 241);
    giq_option(4, 2069, 242, Node006, 50);
    giq_option(4, 2069, 243, Node999, 50);
end

procedure Node006
begin
    set_local_var(7, 1);
    gsay_reply(2069, 250);
    giq_option(4, 2069, 251, Node007, 50);
end

procedure Node007
begin
    gsay_reply(2069, 252);
    giq_option(4, 2069, 260, Node999, 50);
end

procedure Node008
begin
    gsay_reply(2069, 300);
    if (local_var(7) == 0) then begin
        giq_option(4, 2069, 270, Node006, 50);
    end
    giq_option(4, 2069, 301, Node999, 50);
end

procedure critter_p_proc
begin
    if (((global_var(361) bwand 262144) != 0) or (map_var(0) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure timed_event_p_proc
begin
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_map_var(0, 1);
    end
end

