procedure start;
procedure use_p_proc;
procedure pickup_p_proc;
procedure Tamper_Proc;

import variable guard2_obj;
import variable object_tamper;
import variable guard1a_obj;
import variable guard1b_obj;
import variable guard1c_obj;


procedure start
begin
end

procedure use_p_proc
begin
    call Tamper_Proc();
end

procedure pickup_p_proc
begin
    call Tamper_Proc();
end

procedure Tamper_Proc
begin
    if (elevation(dude_obj) == 0) then begin
        if (has_trait(1, guard1a_obj, 666) and (tile_distance(tile_num(guard1a_obj), tile_num(dude_obj)) < 8)) then begin
            script_overrides;
            add_timer_event(guard1a_obj, 5, 2);
        end
        else begin
            if (has_trait(1, guard1b_obj, 666) and (tile_distance(tile_num(guard1c_obj), tile_num(dude_obj)) < 7)) then begin
                script_overrides;
                add_timer_event(guard1c_obj, 5, 2);
            end
            else begin
                if (has_trait(1, guard1c_obj, 666) and (tile_distance(tile_num(guard1b_obj), tile_num(dude_obj)) < 12)) then begin
                    script_overrides;
                    add_timer_event(guard1b_obj, 5, 2);
                end
            end
        end
    end
    else begin
        if (has_trait(1, guard2_obj, 666)) then begin
            script_overrides;
            object_tamper := 2;
            add_timer_event(guard2_obj, 5, 5);
        end
    end
end

