procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure timed_event_p_proc;


procedure start
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(1133, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1133, 101));
end

procedure map_enter_p_proc
begin
    reg_anim_func(1, 1);
    reg_anim_animate_forever(self_obj, 0);
    reg_anim_func(3, 0);
    add_timer_event(self_obj, 1, 1);
end

procedure map_update_p_proc
begin
    if (combat_is_initialized == 0) then begin
        reg_anim_func(1, 1);
        reg_anim_animate_forever(self_obj, 0);
        reg_anim_func(3, 0);
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if ((anim_busy(self_obj) == 0) and (combat_is_initialized == 0)) then begin
            reg_anim_func(1, 1);
            reg_anim_animate_forever(self_obj, 0);
            reg_anim_func(3, 0);
        end
        add_timer_event(self_obj, 1, 1);
    end
end

