procedure start;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node999;


procedure start
begin
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(1629, 100));
end

procedure description_p_proc
begin
    script_overrides;
    if (map_var(2) > 0) then begin
        start_gdialog(1629, self_obj, -1, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
    end
    else begin
        display_msg(message_str(1629, 100));
    end
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
end

procedure Node001
begin
    gsay_reply(1629, 101);
    giq_option(4, 1629, 110, Node002, 50);
    giq_option(4, 1629, 111, Node003, 50);
    giq_option(4, 1629, 112, Node004, 50);
    giq_option(4, 1629, 113, Node999, 50);
end

procedure Node002
begin
    gsay_reply(1629, 200);
    giq_option(4, 1629, 201, Node001, 50);
end

procedure Node003
begin
    if (get_critter_stat(dude_obj, 1) > 4) then begin
        gsay_reply(1629, 302);
        if (map_var(2) == 1) then begin
            set_map_var(2, 2);
        end
        display_msg(message_str(1629, 303));
    end
    else begin
        gsay_reply(1629, 300);
    end
    giq_option(4, 1629, 201, Node001, 50);
end

procedure Node004
begin
    if (get_critter_stat(dude_obj, 1) > 6) then begin
        gsay_reply(1629, 401);
        set_map_var(4, map_var(4) bwor 8);
    end
    else begin
        gsay_reply(1629, 400);
    end
    giq_option(4, 1629, 201, Node001, 50);
end

procedure Node999
begin
end

