variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure checkLoadConditions;
procedure checkNextDay;

variable Only_Once;
variable Node1Rep;

procedure timed_event_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (has_trait(1, self_obj, 666)) then begin
        if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
            set_local_var(5, 1);
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(tile_num(dude_obj), tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num(dude_obj), tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    Evil_Critter := 0;
    if (cur_map_index == 233) then begin
        start_gdialog(1645, self_obj, 4, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
        set_local_var(4, 1);
    end
    else begin
        if (cur_map_index == 0) then begin
            call Node002();
        end
        else begin
            if ((cur_map_index == 0) and ((global_var(1087) bwand 8) != 0)) then begin
                call Node007();
            end
        end
    end
    if (((global_var(1087) bwand 16) != 0) and not((global_var(1087) bwand 8) != 0)) then begin
        set_global_var(270, 13);
        set_global_var(282, 1);
        set_global_var(277, 1);
        LVar1 := 7 - metarule(16, 0);
        set_global_var(279, LVar1);
        set_global_var(273, LVar1);
        set_global_var(281, 10);
        set_global_var(276, 10);
        set_global_var(280, 1);
        set_global_var(274, 1);
        LVar0 := random(1, 4);
        set_global_var(283, LVar0);
        set_global_var(275, LVar0);
        set_global_var(271, 4);
        load_map(94, 7);
    end
    return 0;
    LVar0 := 0;
    LVar1 := 0;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) - -15);
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(1645, 100));
    end
    else begin
        display_msg(message_str(1645, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1645, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, 1, 6, 0);
    critter_add_trait(self_obj, 1, 5, 22);
    if (metarule(22, 0) == 0) then begin
        call checkLoadConditions();
    end
end

procedure combat_p_proc
begin
    if (not(has_trait(1, self_obj, 666))) then begin
        script_overrides;
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    Node1Rep := Node1Rep + 1;
    if (Node1Rep == 1) then begin
        gsay_reply(1645, 103);
        giq_option(1, 1645, 105, Node003, 50);
        giq_option(1, 1645, 106, Node004, 50);
    end
    else begin
        call Node005();
    end
end

procedure Node002
begin
    float_msg(self_obj, message_str(1645, 107 + random(0, 2)), 0);
end

procedure Node003
begin
    set_global_var(1087, global_var(1087) bwor 16);
    set_global_var(1087, global_var(1087) bwor 512);
    gsay_reply(1645, 110);
    giq_option(0, 1645, message_str(14, 350), Node999, 50);
end

procedure Node004
begin
    gsay_reply(1645, 111);
    giq_option(0, 1645, message_str(14, 350), Node999, 50);
end

procedure Node005
begin
    gsay_reply(1645, 112);
    giq_option(0, 1645, message_str(14, 350), Node999, 50);
end

procedure Node006
begin
    variable LVar0 := 0;
    if ((global_var(1087) bwand 32) != 0) then begin
        LVar0 := 0;
        gsay_reply(1645, 113);
    end
    else begin
        if ((global_var(1087) bwand 64) != 0) then begin
            LVar0 := 50;
            gsay_reply(1645, 114);
        end
        else begin
            if ((global_var(1087) bwand 128) != 0) then begin
                LVar0 := 100;
                gsay_reply(1645, 115);
            end
            else begin
                if ((global_var(1087) bwand 256) != 0) then begin
                    LVar0 := 150;
                    gsay_reply(1645, 116);
                end
            end
        end
    end
    set_global_var(1087, global_var(1087) bwor 8);
    item_caps_adjust(dude_obj, LVar0 * (1 + ((party_member_obj(16777376) != 0) + (party_member_obj(16777305) != 0) + (party_member_obj(16777313) != 0) + (party_member_obj(16777378) != 0) + (party_member_obj(16777379) != 0) + (party_member_obj(16777380) != 0))));
    giq_option(0, 1645, message_str(14, 350), Node999, 50);
    return 0;
    LVar0 := 0;
end

procedure Node007
begin
    float_msg(self_obj, message_str(1645, 117), 0);
end

procedure checkLoadConditions
begin
    if (cur_map_index == 157) then begin
        if (not((global_var(1087) bwand 8) != 0) and ((global_var(1087) bwand 4) != 0) and not((global_var(1087) bwand 2) != 0)) then begin
            if ((get_day >= 11) and (get_day <= 12)) then begin
                set_obj_visibility(self_obj, 0);
                set_local_var(7, 1);
            end
        end
        else begin
            set_obj_visibility(self_obj, 1);
            set_local_var(7, 0);
        end
    end
    else begin
        if (cur_map_index == 46) then begin
            if (not((global_var(1087) bwand 8) != 0) and ((global_var(1087) bwand 512) != 0)) then begin
                set_obj_visibility(self_obj, 0);
                set_local_var(7, 1);
                dialogue_system_enter;
            end
            else begin
                set_obj_visibility(self_obj, 1);
                set_local_var(7, 0);
            end
        end
    end
end

procedure checkNextDay
begin
    variable LVar0 := 0;
    LVar0 := get_day;
    if ((LVar0 >= 11) and (LVar0 <= 12)) then begin
        return 1;
    end
    else begin
        if (LVar0 > 12) then begin
            set_global_var(1087, global_var(1087) bwor 2);
        end
    end
    return 0;
    return 0;
    LVar0 := 0;
end

procedure timed_event_p_proc
begin
end

