variable global_temp;
variable in_dialog;
variable amt_ower;
variable temp_item;
variable itul;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node997;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node010a;
procedure Node011;
procedure Node012;
procedure Node013;
procedure leyla_gone;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039a;
procedure Node039b;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node042a;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node047;
procedure Node048;
procedure Node049;
procedure Node049a;
procedure Node050;
procedure Node050a;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node053a;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node057;
procedure Node058;
procedure Node059;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure Node066;
procedure Node067;
procedure Node068;
procedure Node069;
procedure Node070;
procedure Node071;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node075;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node079;
procedure Node080;
procedure Node081;
procedure Node082;
procedure Node083;
procedure Node084;
procedure Node085;
procedure Node086;
procedure Node087;
procedure Node088;
procedure Node089;
procedure Node090;
procedure Node091;
procedure Node092;
procedure Node093;
procedure Node094;
procedure Node095;
procedure Node096;
procedure Node097;
procedure Node098;
procedure Node099;
procedure Node100;
procedure Node101;
procedure Node102;
procedure Node103;
procedure Node104;
procedure Node105;
procedure Node106;
procedure Node107;
procedure Node108;
procedure Node109;
procedure Node110;
procedure Node111;
procedure Node112;
procedure Node113;
procedure Node114;
procedure final;
procedure Node115;
procedure Node116;
procedure Node117;
procedure Node118;
procedure Node119;
procedure Node120;
procedure Node121;
procedure Node122;
procedure Node123;
procedure Node124;
procedure Node125;
procedure Node126;
procedure Node200;
procedure Node201;
procedure Node202;
procedure Node203;
procedure Node204;
procedure Node205;
procedure Node206;
procedure Node207;
procedure Node208;
procedure Node209;
procedure Node210;
procedure Node211;
procedure Node212;
procedure Node213;
procedure Node214;
procedure Node215;
procedure Node216;
procedure Node217;
procedure Node218;
procedure Node219;
procedure Node220;
procedure Node221;
procedure Node222;
procedure Node223;
procedure Node224;
procedure solo_fight;
procedure revenge;
procedure set_holy_anger;
procedure holy_anger;

export variable leyla_point;


procedure start
begin
    leyla_point := self_obj;
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
    end
    if ((local_var(5) == 1) or (global_var(829) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if (((local_var(8) bwand 2048) != 0) and (((local_var(8) bwand 4096) != 0) == 0)) then begin
        gfade_out(1);
        critter_attempt_placement(self_obj, 15084, elevation(self_obj));
        anim(self_obj, 1000, 2);
        critter_attempt_placement(dude_obj, 15284, elevation(self_obj));
        anim(dude_obj, 1000, 5);
        metarule3(108, 16685, 0, 0);
        gfade_in(1);
        set_local_var(8, local_var(8) bwor 4096);
        if (in_dialog == 0) then begin
            in_dialog := 1;
            start_gdialog(28, self_obj, 4, -1, -1);
            gsay_start;
            call Node011();
            gsay_end;
            end_dialogue;
            in_dialog := 0;
        end
        else begin
            call Node011();
        end
    end
    if (((local_var(8) bwand 4096) != 0) and (((local_var(8) bwand 8192) != 0) == 0)) then begin
        gfade_out(1);
        game_time_advance(600 * random(15, 40));
        gfade_in(1);
        if (in_dialog == 0) then begin
            in_dialog := 1;
            start_gdialog(28, self_obj, 4, -1, -1);
            gsay_start;
            call Node013();
            gsay_end;
            end_dialogue;
            in_dialog := 0;
        end
        else begin
            call Node013();
        end
    end
    if (((global_var(830) bwand 1048576) != 0) and (tile_num(self_obj) == 15084)) then begin
        gfade_out(1);
        critter_attempt_placement(self_obj, 20672, elevation(self_obj));
        anim(self_obj, 1000, 2);
        set_global_var(829, 1);
        gfade_in(1);
    end
    if (((local_var(8) bwand 65536) != 0) and (tile_num(self_obj) == 15084)) then begin
        gfade_out(1);
        critter_attempt_placement(self_obj, 20672, elevation(self_obj));
        anim(self_obj, 1000, 2);
        gfade_in(1);
    end
    if ((global_var(830) bwand 536870912) != 0) then begin
        kill_critter(self_obj, 49);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if ((global_var(830) bwand 8) != 0) then begin
        call Node126();
    end
    else begin
        if (global_var(834) > 0) then begin
            call final();
        end
        else begin
            if ((local_var(8) bwand 16384) != 0) then begin
                call holy_anger();
            end
            else begin
                if ((local_var(8) bwand 65536) != 0) then begin
                    if (in_dialog == 0) then begin
                        in_dialog := 1;
                        start_gdialog(28, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node058();
                        gsay_end;
                        end_dialogue;
                        in_dialog := 0;
                    end
                    else begin
                        call Node058();
                    end
                end
                else begin
                    if ((local_var(8) bwand 8192) != 0) then begin
                        if (in_dialog == 0) then begin
                            in_dialog := 1;
                            start_gdialog(28, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node013();
                            gsay_end;
                            end_dialogue;
                            in_dialog := 0;
                        end
                        else begin
                            call Node013();
                        end
                    end
                    else begin
                        if (local_var(10) == 2) then begin
                            if (in_dialog == 0) then begin
                                in_dialog := 1;
                                start_gdialog(28, self_obj, 4, -1, -1);
                                gsay_start;
                                call Node113();
                                gsay_end;
                                end_dialogue;
                                in_dialog := 0;
                            end
                            else begin
                                call Node113();
                            end
                        end
                        else begin
                            if ((global_var(830) bwand 4) != 0) then begin
                                if (local_var(10) > 0) then begin
                                    if (in_dialog == 0) then begin
                                        in_dialog := 1;
                                        start_gdialog(28, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node093();
                                        gsay_end;
                                        end_dialogue;
                                        in_dialog := 0;
                                    end
                                    else begin
                                        call Node093();
                                    end
                                end
                                else begin
                                    if (in_dialog == 0) then begin
                                        in_dialog := 1;
                                        start_gdialog(28, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node083();
                                        gsay_end;
                                        end_dialogue;
                                        in_dialog := 0;
                                    end
                                    else begin
                                        call Node083();
                                    end
                                end
                            end
                            else begin
                                if ((local_var(7) > 0) and (local_var(10) == 1)) then begin
                                    if (in_dialog == 0) then begin
                                        in_dialog := 1;
                                        start_gdialog(28, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node032();
                                        gsay_end;
                                        end_dialogue;
                                        in_dialog := 0;
                                    end
                                    else begin
                                        call Node032();
                                    end
                                end
                                else begin
                                    if (in_dialog == 0) then begin
                                        in_dialog := 1;
                                        start_gdialog(28, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node001();
                                        gsay_end;
                                        end_dialogue;
                                        in_dialog := 0;
                                    end
                                    else begin
                                        call Node001();
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    set_global_var(830, global_var(830) bwor 536870912);
    if (source_obj == dude_obj) then begin
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + 0);
        debug_msg("Player gains " + 0 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(6) == 0) then begin
        set_local_var(6, 1);
        display_msg(message_str(28, 100));
    end
    else begin
        display_msg(message_str(28, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(28, 105));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((local_var(8) bwand 32768) != 0) == 0) then begin
            set_global_var(829, 1);
        end
        set_local_var(5, 1);
    end
end

procedure map_enter_p_proc
begin
    if (metarule(14, 0)) then begin
        if (metarule(22, 0)) then begin
            critter_add_trait(self_obj, 1, 5, 22);
            critter_mod_skill(self_obj, 4, 20);
            critter_mod_skill(self_obj, 3, 20);
        end
    end
    if (((local_var(8) bwand 8192) != 0) and (((local_var(8) bwand 65536) != 0) == 0)) then begin
    end
    else begin
        if (tile_num(self_obj) != 20672) then begin
            critter_attempt_placement(self_obj, 20672, elevation(self_obj));
            anim(self_obj, 1000, 2);
            critter_add_trait(self_obj, 1, 6, 5);
            set_local_var(8, local_var(8) bwand (-1 - 32768));
        end
    end
end

procedure Node997
begin
    set_local_var(5, 0);
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    set_local_var(10, 1);
    set_local_var(7, 1);
    if ((global_var(830) bwand 2) != 0) then begin
        gsay_reply(28, message_str(28, 201));
    end
    else begin
        gsay_reply(28, message_str(28, 200));
    end
    giq_option(4, 28, 202, Node002, 50);
    giq_option(4, 28, message_str(28, 203) + obj_name(dude_obj) + message_str(28, 204), Node022, 50);
    if ((global_var(830) bwand 2) != 0) then begin
        giq_option(4, 28, 205, Node014, 50);
    end
    giq_option(4, 28, 206, Node027, 50);
end

procedure Node002
begin
    gsay_reply(28, message_str(28, 210));
    giq_option(4, 28, 211, Node003, 50);
    giq_option(4, 28, 212, Node999, 50);
end

procedure Node003
begin
    gsay_reply(28, message_str(28, 220));
    giq_option(4, 28, 221, Node004, 50);
    giq_option(4, 28, 222, Node004, 50);
    giq_option(4, 28, 223, Node023, 50);
    giq_option(4, 28, 224, Node999, 50);
end

procedure Node004
begin
    gsay_reply(28, message_str(28, 230));
    giq_option(4, 28, 231, Node005, 50);
    if (obj_is_carrying_obj_pid(dude_obj, 314) + obj_is_carrying_obj_pid(dude_obj, 315) + obj_is_carrying_obj_pid(dude_obj, 316)) then begin
        giq_option(4, 28, 232, Node007, 50);
    end
    giq_option(4, 28, 233, Node999, 50);
end

procedure Node005
begin
    gsay_message(28, message_str(28, 240), 50);
    call Node006();
end

procedure Node006
begin
    gsay_reply(28, message_str(28, 250));
    giq_option(4, 28, 251, Node030, 50);
    giq_option(4, 28, 252, Node999, 50);
end

procedure Node007
begin
    gsay_reply(28, message_str(28, 260));
    giq_option(4, 28, 261, Node008, 50);
    giq_option(4, 28, 262, Node017, 50);
end

procedure Node008
begin
    amt_ower := 1;
    if ((obj_is_carrying_obj_pid(dude_obj, 314) + obj_is_carrying_obj_pid(dude_obj, 315) + obj_is_carrying_obj_pid(dude_obj, 316)) > 0) then begin
        while (amt_ower > 0) do begin
            if (obj_is_carrying_obj_pid(dude_obj, 314) > 0) then begin
                temp_item := obj_carrying_pid_obj(dude_obj, 314);
            end
            else begin
                if (obj_is_carrying_obj_pid(dude_obj, 315) > 0) then begin
                    temp_item := obj_carrying_pid_obj(dude_obj, 315);
                end
                else begin
                    if (obj_is_carrying_obj_pid(dude_obj, 316) > 0) then begin
                        temp_item := obj_carrying_pid_obj(dude_obj, 316);
                    end
                end
            end
            itul := rm_mult_objs_from_inven(dude_obj, temp_item, 1);
            amt_ower := amt_ower - 1;
        end
    end
    gsay_reply(28, message_str(28, 270));
    giq_option(4, 28, 271, Node009, 50);
    giq_option(4, 28, 272, Node009, 50);
end

procedure Node009
begin
    gsay_reply(28, message_str(28, 280));
    giq_option(4, 28, 281, Node010, 50);
    giq_option(4, 28, 282, Node010, 50);
    giq_option(4, 28, 283, Node010, 50);
end

procedure Node010
begin
    gsay_reply(28, message_str(28, 290));
    giq_option(4, 28, 291, Node010a, 50);
    giq_option(4, 28, 292, Node010a, 50);
end

procedure Node010a
begin
    set_local_var(8, local_var(8) bwor 2048);
end

procedure Node011
begin
    gsay_reply(28, message_str(28, 300));
    giq_option(4, 28, 301, Node012, 50);
    giq_option(4, 28, 302, Node012, 50);
end

procedure Node012
begin
    if ((obj_is_carrying_obj_pid(self_obj, 314) + obj_is_carrying_obj_pid(self_obj, 315) + obj_is_carrying_obj_pid(self_obj, 316)) > 0) then begin
        gsay_message(28, message_str(28, 310) + message_str(28, 311) + message_str(28, 312), 50);
    end
    else begin
        gsay_message(28, message_str(28, 310) + message_str(28, 312), 50);
    end
end

procedure Node013
begin
    display_msg(message_str(28, 3000));
    give_exp_points(350);
    set_local_var(8, local_var(8) bwor 8192);
    if (((global_var(830) bwand 2) != 0) or ((global_var(830) bwand 256) != 0) or (get_critter_stat(dude_obj, 3) > 6)) then begin
        set_local_var(8, local_var(8) bwor 131072);
    end
    gsay_reply(28, message_str(28, 320));
    giq_option(4, 28, 321, Node053, 50);
    giq_option(4, 28, 324, Node052, 50);
    giq_option(4, 28, 322, Node033, 50);
    giq_option(4, 28, 323, leyla_gone, 50);
end

procedure leyla_gone
begin
    set_local_var(8, local_var(8) bwor 65536);
end

procedure Node014
begin
    gsay_reply(28, message_str(28, 330));
    giq_option(4, 28, 331, Node015, 50);
    giq_option(4, 28, 332, Node017, 50);
end

procedure Node015
begin
    gsay_reply(28, message_str(28, 340));
    giq_option(4, 28, 341, Node016, 50);
end

procedure Node016
begin
    gsay_reply(28, message_str(28, 350));
    giq_option(4, 28, 351, Node007, 50);
    giq_option(4, 28, 352, Node999, 50);
end

procedure Node017
begin
    gsay_reply(28, message_str(28, 360));
    giq_option(4, 28, 361, Node020, 50);
    giq_option(4, 28, 362, Node019, 50);
    giq_option(4, 28, 363, Node018, 50);
end

procedure Node018
begin
    gsay_reply(28, message_str(28, 370));
    giq_option(4, 28, 371, Node999, 50);
end

procedure Node019
begin
    gsay_reply(28, message_str(28, 380));
    giq_option(4, 28, 381, set_holy_anger, 50);
    giq_option(4, 28, 382, set_holy_anger, 50);
end

procedure Node020
begin
    gsay_reply(28, message_str(28, 390));
    giq_option(4, 28, 391, Node021, 50);
    giq_option(4, 28, 392, set_holy_anger, 50);
end

procedure Node021
begin
    gsay_message(28, message_str(28, 400), 50);
    call Node998();
end

procedure Node022
begin
    if ((global_var(830) bwand 2) != 0) then begin
        gsay_reply(28, message_str(28, 411));
    end
    else begin
        gsay_reply(28, message_str(28, 410));
    end
    giq_option(4, 28, 412, Node027, 50);
    giq_option(4, 28, 413, Node023, 50);
    giq_option(4, 28, 414, Node999, 50);
end

procedure Node023
begin
    gsay_reply(28, message_str(28, 420));
    giq_option(4, 28, 421, Node024, 50);
    giq_option(4, 28, 422, Node999, 50);
end

procedure Node024
begin
    gsay_reply(28, message_str(28, 430));
    giq_option(4, 28, 431, Node025, 50);
    giq_option(4, 28, 432, Node999, 50);
end

procedure Node025
begin
    gsay_reply(28, message_str(28, 440));
    giq_option(4, 28, 441, Node026, 50);
    giq_option(4, 28, 442, Node999, 50);
end

procedure Node026
begin
    gsay_reply(28, message_str(28, 450));
    giq_option(4, 28, 451, Node999, 50);
    giq_option(4, 28, 452, Node999, 50);
    giq_option(4, 28, 453, Node999, 50);
end

procedure Node027
begin
    gsay_reply(28, message_str(28, 460));
    giq_option(4, 28, 461, Node028, 50);
    if (obj_is_carrying_obj_pid(dude_obj, 314) + obj_is_carrying_obj_pid(dude_obj, 315) + obj_is_carrying_obj_pid(dude_obj, 316)) then begin
        giq_option(4, 28, 462, Node008, 50);
    end
    giq_option(4, 28, 463, Node023, 50);
end

procedure Node028
begin
    gsay_reply(28, message_str(28, 470));
    giq_option(4, 28, 471, Node029, 50);
end

procedure Node029
begin
    gsay_reply(28, message_str(28, 480));
    giq_option(4, 28, 481, Node999, 50);
    giq_option(4, 28, 482, Node999, 50);
end

procedure Node030
begin
    gsay_reply(28, message_str(28, 490));
    giq_option(4, 28, 491, Node031, 50);
    giq_option(4, 28, 492, Node017, 50);
    giq_option(4, 28, 493, Node999, 50);
end

procedure Node031
begin
    gsay_reply(28, message_str(28, 500));
    giq_option(4, 28, 501, Node999, 50);
end

procedure Node032
begin
    gsay_reply(28, message_str(28, random(510, 513)));
    giq_option(4, 28, random(514, 517), Node999, 50);
end

procedure Node033
begin
    gsay_reply(28, message_str(28, 520));
    giq_option(4, 28, 521, Node036, 50);
    giq_option(4, 28, 522, Node034, 50);
end

procedure Node034
begin
    gsay_reply(28, message_str(28, 530));
    giq_option(4, 28, 531, Node035, 50);
end

procedure Node035
begin
    set_local_var(8, local_var(8) bwor 65536);
    gsay_reply(28, message_str(28, 540));
    giq_option(4, 28, 541, Node999, 50);
    giq_option(4, 28, 542, Node999, 50);
end

procedure Node036
begin
    set_local_var(5, 1);
    gsay_reply(28, message_str(28, 550));
    giq_option(4, 28, 551, Node049, 50);
    giq_option(4, 28, 552, Node042, 50);
    giq_option(4, 28, 553, Node037, 50);
end

procedure Node037
begin
    gsay_reply(28, message_str(28, 560));
    giq_option(4, 28, 561, Node038, 50);
    giq_option(4, 28, 562, revenge, 50);
end

procedure Node038
begin
    display_msg(message_str(28, 3002));
    give_exp_points(300);
    gsay_reply(28, message_str(28, 570));
    giq_option(4, 28, 571, Node039a, 50);
    giq_option(4, 28, 572, Node039b, 50);
end

procedure Node039a
begin
    gsay_reply(28, message_str(28, 580));
    giq_option(4, 28, 582, Node040, 50);
    if (get_critter_stat(dude_obj, 1) > 5) then begin
        giq_option(4, 28, 583, Node041, 50);
    end
end

procedure Node039b
begin
    gsay_reply(28, message_str(28, 581));
    giq_option(4, 28, 582, Node040, 50);
    if (get_critter_stat(dude_obj, 1) > 5) then begin
        giq_option(4, 28, 583, Node041, 50);
    end
end

procedure Node040
begin
    critter_dmg(dude_obj, get_critter_stat(dude_obj, 35) - 6, 0);
    gsay_reply(28, message_str(28, 590));
    giq_option(4, 28, 591, solo_fight, 50);
end

procedure Node041
begin
    gsay_reply(28, message_str(28, 600));
    giq_option(4, 28, 601, solo_fight, 50);
end

procedure Node042
begin
    if (((global_var(830) bwand 4) != 0) or (has_skill(dude_obj, 14) >= 47)) then begin
        call Node042a();
    end
    else begin
        call Node044();
    end
end

procedure Node042a
begin
    gsay_reply(28, message_str(28, 610));
    giq_option(4, 28, 611, Node043, 50);
end

procedure Node043
begin
    set_global_var(0, global_var(0) + -15);
    debug_msg("Player gains " + -15 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    display_msg(message_str(28, 3001));
    give_exp_points(300);
    set_global_var(830, global_var(830) bwor 536870912);
    gsay_reply(28, message_str(28, 620));
    giq_option(4, 28, 621, Node997, 50);
    giq_option(4, 28, 622, Node997, 50);
    giq_option(4, 28, 623, Node997, 50);
end

procedure Node044
begin
    gsay_reply(28, message_str(28, 630));
    giq_option(4, 28, 631, Node046, 50);
    giq_option(4, 28, 632, Node045, 50);
end

procedure Node045
begin
    gsay_reply(28, message_str(28, 640));
    giq_option(4, 28, 641, revenge, 50);
    giq_option(4, 28, 642, revenge, 50);
end

procedure Node046
begin
    gsay_reply(28, message_str(28, 650));
    giq_option(4, 28, 651, Node047, 50);
    giq_option(4, 28, 652, Node048, 50);
end

procedure Node047
begin
    gsay_reply(28, message_str(28, 660));
    giq_option(4, 28, 661, solo_fight, 50);
end

procedure Node048
begin
    gsay_reply(28, message_str(28, 670));
    giq_option(4, 28, 671, solo_fight, 50);
end

procedure Node049
begin
    gsay_reply(28, message_str(28, 680));
    giq_option(4, 28, 681, Node049a, 50);
    giq_option(4, 28, 682, Node045, 50);
end

procedure Node049a
begin
    variable LVar0 := 0;
    LVar0 := 2 + random(1, 8);
    if (LVar0 > get_critter_stat(dude_obj, 0)) then begin
        call Node051();
    end
    else begin
        call Node050();
    end
    return 0;
    LVar0 := 0;
end

procedure Node050
begin
    gsay_reply(28, message_str(28, 690));
    giq_option(4, 28, 691, Node050a, 50);
    giq_option(4, 28, 692, Node045, 50);
end

procedure Node050a
begin
    variable LVar0 := 0;
    LVar0 := 3 + random(1, 6);
    if (LVar0 > get_critter_stat(dude_obj, 0)) then begin
        call Node038();
    end
    else begin
        call Node042();
    end
    return 0;
    LVar0 := 0;
end

procedure Node051
begin
    gsay_reply(28, message_str(28, 700));
    giq_option(4, 28, 701, solo_fight, 50);
end

procedure Node052
begin
    set_local_var(8, local_var(8) bwand (-1 - 131072));
    set_local_var(8, local_var(8) bwor 65536);
    gsay_reply(28, message_str(28, 710));
    giq_option(4, 28, 711, Node999, 50);
    giq_option(4, 28, 712, Node999, 50);
    giq_option(4, 28, 713, Node999, 50);
end

procedure Node053
begin
    set_local_var(8, local_var(8) bwor 65536);
    gsay_reply(28, message_str(28, 720));
    giq_option(4, 28, 721, Node054, 50);
    giq_option(4, 28, 722, Node053a, 50);
    giq_option(4, 28, 723, Node999, 50);
end

procedure Node053a
begin
    if (((local_var(8) bwand 131072) != 0) or (has_skill(dude_obj, 14) >= 48)) then begin
        call Node057();
    end
    else begin
        call Node056();
    end
end

procedure Node054
begin
    gsay_reply(28, message_str(28, 730));
    giq_option(4, 28, 731, Node055, 50);
    giq_option(4, 28, 732, Node999, 50);
end

procedure Node055
begin
    gsay_reply(28, message_str(28, 740));
    giq_option(4, 28, 741, Node999, 50);
    giq_option(4, 28, 742, Node999, 50);
    giq_option(4, 28, 743, Node999, 50);
end

procedure Node056
begin
    gsay_reply(28, message_str(28, 750));
    giq_option(4, 28, 751, Node999, 50);
end

procedure Node057
begin
    gsay_reply(28, message_str(28, 760));
    giq_option(4, 28, 761, Node200, 50);
end

procedure Node058
begin
    if (local_var(9) == 2) then begin
        gsay_reply(28, message_str(28, 769));
    end
    else begin
        if ((local_var(8) bwand 131072) != 0) then begin
            gsay_reply(28, message_str(28, 773));
        end
        else begin
            gsay_reply(28, message_str(28, random(770, 772)));
        end
    end
    giq_option(4, 28, 774, Node200, 50);
    if (local_var(9) == 0) then begin
        giq_option(4, 28, 775, Node059, 50);
    end
    if (local_var(9) == 1) then begin
        if ((local_var(8) bwand 131072) != 0) then begin
            giq_option(4, 28, 776, Node066, 50);
        end
        else begin
            giq_option(4, 28, 776, Node068, 50);
        end
    end
    if (local_var(9) == 2) then begin
        giq_option(4, 28, 777, Node071, 50);
    end
    giq_option(4, 28, 778, Node999, 50);
end

procedure Node059
begin
    set_local_var(9, 1);
    gsay_reply(28, message_str(28, 780));
    giq_option(4, 28, 781, Node060, 50);
    giq_option(4, 28, 782, Node064, 50);
end

procedure Node060
begin
    gsay_reply(28, message_str(28, 790));
    if ((local_var(8) bwand 131072) != 0) then begin
        giq_option(4, 28, 791, Node062, 50);
    end
    giq_option(4, 28, 792, Node061, 50);
    giq_option(4, 28, 793, Node999, 50);
end

procedure Node061
begin
    gsay_reply(28, message_str(28, 800));
    giq_option(4, 28, 801, Node999, 50);
end

procedure Node062
begin
    gsay_reply(28, message_str(28, 810));
    giq_option(4, 28, 811, Node063, 50);
    giq_option(4, 28, 812, Node999, 50);
end

procedure Node063
begin
    gsay_reply(28, message_str(28, 820));
    giq_option(4, 28, 821, Node999, 50);
end

procedure Node064
begin
    set_local_var(8, local_var(8) bwor 16384);
    gsay_reply(28, message_str(28, 830));
    giq_option(4, 28, 831, Node999, 50);
    giq_option(4, 28, 832, Node065, 50);
end

procedure Node065
begin
    gsay_reply(28, message_str(28, 840));
    if ((global_var(830) bwand 4) != 0) then begin
        giq_option(7, 28, 841, Node072, 50);
    end
    if ((global_var(830) bwand 4) != 0) then begin
        giq_option(4, 28, 842, Node072, 50);
    end
    else begin
        giq_option(4, 28, 842, Node075, 50);
    end
    giq_option(4, 28, 843, Node998, 50);
end

procedure Node066
begin
    set_local_var(8, local_var(8) bwand (-1 - 131072));
    gsay_reply(28, message_str(28, 850));
    giq_option(4, 28, 851, Node067, 50);
    giq_option(4, 28, 852, Node999, 50);
end

procedure Node067
begin
    gsay_reply(28, message_str(28, 860));
    giq_option(4, 28, 861, Node999, 50);
end

procedure Node068
begin
    set_local_var(9, 2);
    gsay_reply(28, message_str(28, 870));
    giq_option(4, 28, 871, Node069, 50);
    giq_option(4, 28, 872, Node999, 50);
    giq_option(4, 28, 873, Node999, 50);
end

procedure Node069
begin
    gsay_reply(28, message_str(28, 880));
    giq_option(4, 28, 881, Node070, 50);
    giq_option(4, 28, 882, Node999, 50);
end

procedure Node070
begin
    gsay_reply(28, message_str(28, 890));
    giq_option(4, 28, 891, Node999, 50);
    giq_option(4, 28, 892, Node999, 50);
end

procedure Node071
begin
    gsay_reply(28, message_str(28, 900));
    giq_option(4, 28, 901, set_holy_anger, 50);
    giq_option(4, 28, 902, Node065, 50);
end

procedure Node072
begin
    set_local_var(5, 1);
    set_local_var(8, local_var(8) bwor 16384);
    gsay_reply(28, message_str(28, 910));
    if (has_skill(dude_obj, 14) >= 56) then begin
        giq_option(6, 28, 911, Node076, 50);
    end
    giq_option(5, 28, 912, Node077, 50);
    giq_option(4, 28, 913, Node073, 50);
end

procedure Node073
begin
    gsay_reply(28, message_str(28, 920));
    giq_option(4, 28, 921, Node074, 50);
end

procedure Node074
begin
    gsay_reply(28, message_str(28, 930));
    giq_option(4, 28, 931, Node998, 50);
end

procedure Node075
begin
    gsay_reply(28, message_str(28, 940));
    giq_option(4, 28, 941, Node998, 50);
end

procedure Node076
begin
    gsay_reply(28, message_str(28, 950));
    giq_option(4, 28, 951, Node082, 50);
end

procedure Node077
begin
    gsay_reply(28, message_str(28, 960));
    giq_option(4, 28, 961, Node078, 50);
end

procedure Node078
begin
    gsay_reply(28, message_str(28, 970));
    if (has_skill(dude_obj, 14) >= 36) then begin
        giq_option(4, 28, 971, Node079, 50);
    end
    giq_option(4, 28, 972, Node080, 50);
    giq_option(4, 28, 973, Node081, 50);
end

procedure Node079
begin
    gsay_reply(28, message_str(28, 980));
    giq_option(4, 28, 921, Node082, 50);
end

procedure Node080
begin
    gsay_reply(28, message_str(28, 990));
    giq_option(4, 28, 921, Node081, 50);
end

procedure Node081
begin
    gsay_reply(28, message_str(28, 1000));
    giq_option(4, 28, 1001, Node998, 50);
end

procedure Node082
begin
    display_msg(message_str(28, 3003));
    give_exp_points(200);
    gsay_reply(28, message_str(28, 1010));
    giq_option(4, 28, 1011, Node999, 50);
end

procedure Node083
begin
    set_local_var(10, 2);
    gsay_reply(28, message_str(28, 1020));
    if (has_skill(dude_obj, 14) >= 42) then begin
        giq_option(5, 28, 1021, Node090, 50);
    end
    if (obj_is_carrying_obj_pid(dude_obj, 314) + obj_is_carrying_obj_pid(dude_obj, 315) + obj_is_carrying_obj_pid(dude_obj, 316)) then begin
        giq_option(4, 28, 1022, Node008, 50);
    end
    giq_option(4, 28, 1023, Node084, 50);
    giq_option(4, 28, 1024, Node017, 50);
end

procedure Node084
begin
    gsay_reply(28, message_str(28, 1030));
    if ((obj_is_carrying_obj_pid(dude_obj, 106) + obj_is_carrying_obj_pid(dude_obj, 124) + obj_is_carrying_obj_pid(dude_obj, 125) + obj_is_carrying_obj_pid(dude_obj, 310) + obj_is_carrying_obj_pid(dude_obj, 311) + obj_is_carrying_obj_pid(dude_obj, 469)) > 2) then begin
        giq_option(4, 28, 1031, Node086, 50);
    end
    giq_option(4, 28, 1032, Node085, 50);
    giq_option(4, 28, 1033, Node999, 50);
end

procedure Node085
begin
    gsay_reply(28, message_str(28, 1040));
    giq_option(4, 28, 1041, Node999, 50);
    giq_option(4, 28, 1042, Node999, 50);
end

procedure Node086
begin
    amt_ower := 3;
    if ((obj_is_carrying_obj_pid(dude_obj, 106) + obj_is_carrying_obj_pid(dude_obj, 124) + obj_is_carrying_obj_pid(dude_obj, 125) + obj_is_carrying_obj_pid(dude_obj, 310) + obj_is_carrying_obj_pid(dude_obj, 311) + obj_is_carrying_obj_pid(dude_obj, 469)) > 0) then begin
        while (amt_ower > 0) do begin
            if (obj_is_carrying_obj_pid(dude_obj, 106) > 0) then begin
                temp_item := obj_carrying_pid_obj(dude_obj, 106);
            end
            else begin
                if (obj_is_carrying_obj_pid(dude_obj, 124) > 0) then begin
                    temp_item := obj_carrying_pid_obj(dude_obj, 124);
                end
                else begin
                    if (obj_is_carrying_obj_pid(dude_obj, 125) > 0) then begin
                        temp_item := obj_carrying_pid_obj(dude_obj, 125);
                    end
                    else begin
                        if (obj_is_carrying_obj_pid(dude_obj, 310) > 0) then begin
                            temp_item := obj_carrying_pid_obj(dude_obj, 310);
                        end
                        else begin
                            if (obj_is_carrying_obj_pid(dude_obj, 311) > 0) then begin
                                temp_item := obj_carrying_pid_obj(dude_obj, 311);
                            end
                            else begin
                                if (obj_is_carrying_obj_pid(dude_obj, 311) > 0) then begin
                                    temp_item := obj_carrying_pid_obj(dude_obj, 311);
                                end
                            end
                        end
                    end
                end
            end
            itul := rm_mult_objs_from_inven(dude_obj, temp_item, 1);
            add_mult_objs_to_inven(self_obj, temp_item, 1);
            amt_ower := amt_ower - 1;
        end
    end
    gsay_reply(28, message_str(28, 1050));
    giq_option(4, 28, 1051, Node087, 50);
    giq_option(4, 28, 1052, Node088, 50);
    giq_option(4, 28, 1053, Node999, 50);
end

procedure Node087
begin
    set_local_var(8, local_var(8) bwor 131072);
    gsay_reply(28, message_str(28, 1060));
    giq_option(4, 28, 1061, Node094, 50);
    giq_option(4, 28, 1062, Node999, 50);
end

procedure Node088
begin
    gsay_reply(28, message_str(28, 1070));
    giq_option(4, 28, 1071, Node089, 50);
    giq_option(4, 28, 1072, Node999, 50);
end

procedure Node089
begin
    gsay_reply(28, message_str(28, 1080));
    giq_option(4, 28, 1081, set_holy_anger, 50);
end

procedure Node090
begin
    gsay_reply(28, message_str(28, 1090));
    giq_option(4, 28, 1091, Node092, 50);
    giq_option(4, 28, 1092, Node091, 50);
end

procedure Node091
begin
    gsay_reply(28, message_str(28, 1100));
    giq_option(4, 28, 1101, Node999, 50);
end

procedure Node092
begin
    gsay_reply(28, message_str(28, 1110));
    giq_option(4, 28, 1111, Node094, 50);
end

procedure Node093
begin
    set_local_var(10, 2);
    gsay_reply(28, message_str(28, 1120 + ((global_var(830) bwand 2) != 0)));
    giq_option(4, 28, 1122, Node094, 50);
    if ((obj_is_carrying_obj_pid(dude_obj, 314) + obj_is_carrying_obj_pid(dude_obj, 315) + obj_is_carrying_obj_pid(dude_obj, 316)) > 0) then begin
        giq_option(4, 28, 1123, Node008, 50);
    end
end

procedure Node094
begin
    gsay_reply(28, message_str(28, 1130));
    giq_option(4, 28, 1131, Node104, 50);
    giq_option(4, 28, 1133, Node095, 50);
    if ((get_critter_stat(dude_obj, 0) + get_critter_stat(dude_obj, 2)) > 12) then begin
        giq_option(4, 28, 1134, Node110, 50);
    end
    else begin
        giq_option(4, 28, 1134, Node111, 50);
    end
end

procedure Node095
begin
    gsay_reply(28, message_str(28, 1140));
    giq_option(4, 28, 1141, Node096, 50);
    giq_option(5, 28, 1142, Node099, 50);
    giq_option(4, 28, 1143, Node999, 50);
end

procedure Node096
begin
    gsay_reply(28, message_str(28, 1150));
    giq_option(4, 28, 1151, Node097, 50);
end

procedure Node097
begin
    gsay_reply(28, message_str(28, 1160));
    giq_option(4, 28, 1161, Node098, 50);
end

procedure Node098
begin
    gsay_reply(28, message_str(28, 1170));
    giq_option(4, 28, 1171, Node999, 50);
end

procedure Node099
begin
    gsay_reply(28, message_str(28, 1180));
    giq_option(6, 28, 1181, Node100, 50);
    giq_option(4, 28, 1182, Node103, 50);
end

procedure Node100
begin
    gsay_reply(28, message_str(28, 1190));
    giq_option(4, 28, 1191, Node101, 50);
end

procedure Node101
begin
    gsay_reply(28, message_str(28, 1200));
    if (((local_var(8) bwand 131072) != 0) and (has_skill(dude_obj, 14) >= 40) or (has_skill(dude_obj, 14) >= 55) or (get_critter_stat(dude_obj, 3) > 7)) then begin
        giq_option(4, 28, 1201, Node010, 50);
    end
    else begin
        giq_option(4, 28, 1201, Node102, 50);
    end
    giq_option(4, 28, 1202, Node999, 50);
end

procedure Node102
begin
    gsay_reply(28, message_str(28, 1210));
    giq_option(4, 28, 1211, Node999, 50);
end

procedure Node103
begin
    gsay_reply(28, message_str(28, 1220));
    giq_option(4, 28, 1221, Node999, 50);
end

procedure Node104
begin
    gsay_reply(28, message_str(28, 1230));
    if ((((global_var(830) bwand 2) != 0) + ((global_var(830) bwand 256) != 0) + get_critter_stat(dude_obj, 3)) > 7) then begin
        giq_option(4, 28, 1231, Node010, 50);
    end
    giq_option(4, 28, 1232, Node108, 50);
    if ((global_var(830) bwand 256) != 0) then begin
        giq_option(4, 28, 1233, Node106, 50);
    end
    else begin
        giq_option(4, 28, 1233, Node105, 50);
    end
end

procedure Node105
begin
    gsay_reply(28, message_str(28, 1240));
    giq_option(4, 28, 1241, set_holy_anger, 50);
end

procedure Node106
begin
    gsay_reply(28, message_str(28, 1250));
    giq_option(4, 28, 1251, Node107, 50);
end

procedure Node107
begin
    gsay_reply(28, message_str(28, 1260));
    giq_option(4, 28, 1261, Node011, 50);
end

procedure Node108
begin
    gsay_reply(28, message_str(28, 1270));
    giq_option(4, 28, 1271, Node109, 50);
    giq_option(4, 28, 1272, Node999, 50);
end

procedure Node109
begin
    gsay_reply(28, message_str(28, 1280));
    giq_option(4, 28, 1281, Node999, 50);
end

procedure Node110
begin
    gsay_reply(28, message_str(28, 1290));
    giq_option(4, 28, 1291, Node011, 50);
end

procedure Node111
begin
    gsay_reply(28, message_str(28, 1300));
    giq_option(4, 28, 1301, Node112, 50);
    giq_option(4, 28, 1302, Node999, 50);
end

procedure Node112
begin
    gsay_reply(28, message_str(28, 1310));
    giq_option(4, 28, 1311, Node999, 50);
end

procedure Node113
begin
    gsay_reply(28, message_str(28, 1320));
    giq_option(4, 28, 1321, Node200, 50);
    giq_option(4, 28, 1322, Node114, 50);
    giq_option(4, 28, 1323, Node999, 50);
end

procedure Node114
begin
    gsay_reply(28, message_str(28, random(1330, 1332)));
    giq_option(4, 28, 1333, Node999, 50);
end

procedure final
begin
    if (global_var(834) == 5) then begin
        call Node115();
    end
    else begin
        if (global_var(834) == 1) then begin
            call Node116();
        end
        else begin
            if ((global_var(834) == 2) or (global_var(834) == 3)) then begin
                if (in_dialog == 0) then begin
                    in_dialog := 1;
                    start_gdialog(28, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node117();
                    gsay_end;
                    end_dialogue;
                    in_dialog := 0;
                end
                else begin
                    call Node117();
                end
            end
            else begin
                if (in_dialog == 0) then begin
                    in_dialog := 1;
                    start_gdialog(28, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node121();
                    gsay_end;
                    end_dialogue;
                    in_dialog := 0;
                end
                else begin
                    call Node121();
                end
            end
        end
    end
end

procedure Node115
begin
    float_msg(self_obj, message_str(28, random(1340, 1345)), 2);
end

procedure Node116
begin
    float_msg(self_obj, message_str(28, random(1350, 1355)), 2);
end

procedure Node117
begin
    gsay_reply(28, message_str(28, 1360));
    giq_option(4, 28, 1361, Node118, 50);
    giq_option(4, 28, 1362, Node119, 50);
    giq_option(4, 28, 1363, Node120, 50);
    giq_option(4, 28, 1364, Node999, 50);
end

procedure Node118
begin
    gsay_reply(28, message_str(28, 1370));
    giq_option(4, 28, 1373, Node124, 50);
end

procedure Node119
begin
    gsay_reply(28, message_str(28, 1371));
    giq_option(4, 28, 1373, Node124, 50);
end

procedure Node120
begin
    gsay_reply(28, message_str(28, 1372));
    giq_option(4, 28, 1374, Node124, 50);
end

procedure Node121
begin
    gsay_reply(28, message_str(28, 1380));
    giq_option(4, 28, 1381, Node122, 50);
end

procedure Node122
begin
    gsay_reply(28, message_str(28, 1390));
    giq_option(4, 28, 1391, Node123, 50);
end

procedure Node123
begin
    gsay_reply(28, message_str(28, 1400));
    giq_option(4, 28, 1401, Node124, 50);
    giq_option(4, 28, 1402, Node125, 50);
end

procedure Node124
begin
    gsay_reply(28, message_str(28, random(1410, 1412)));
    giq_option(4, 28, 1413, Node999, 50);
    giq_option(4, 28, 1414, Node999, 50);
end

procedure Node125
begin
    gsay_message(28, message_str(28, 1420), 50);
end

procedure Node126
begin
    float_msg(self_obj, message_str(28, random(150, 152)), 2);
end

procedure Node200
begin
    gsay_reply(28, message_str(28, random(2000, 2001)));
    if ((local_var(9) < 2) and (((local_var(8) bwand 4096) != 0) or ((global_var(830) bwand 2) != 0) or ((global_var(830) bwand 256) != 0))) then begin
        giq_option(4, 28, 2003, Node203, 50);
        giq_option(4, 28, 2004, Node208, 50);
        giq_option(4, 28, 2005, Node211, 50);
    end
    else begin
        giq_option(4, 28, 2003, Node202, 50);
        giq_option(4, 28, 2004, Node207, 50);
        giq_option(4, 28, 2005, Node210, 50);
    end
    if ((local_var(8) bwand 4096) != 0) then begin
        if ((local_var(9) < 2) and (has_skill(dude_obj, 14) >= 53)) then begin
            giq_option(4, 28, 2006, Node214, 50);
        end
        else begin
            giq_option(4, 28, 2006, Node201, 50);
        end
        if ((local_var(8) bwand 262144) != 0) then begin
            if ((local_var(9) < 2) and (has_skill(dude_obj, 14) >= 78)) then begin
                giq_option(4, 28, 2007, Node219, 50);
            end
            else begin
                giq_option(4, 28, 2007, Node201, 50);
            end
        end
        if ((global_var(831) bwand 128) != 0) then begin
            if (local_var(9) < 2) then begin
                giq_option(4, 28, 2008, Node221, 50);
                giq_option(4, 28, 2009, Node222, 50);
            end
            else begin
                giq_option(4, 28, 2008, Node201, 50);
                giq_option(4, 28, 2009, Node201, 50);
            end
        end
    end
    giq_option(4, 28, 2011, Node999, 50);
end

procedure Node201
begin
    gsay_reply(28, message_str(28, random(2020, 2021)));
    giq_option(4, 28, 2022, Node200, 50);
    giq_option(4, 28, 2023, Node999, 50);
end

procedure Node202
begin
    gsay_reply(28, message_str(28, 2030));
    giq_option(4, 28, 2031, Node200, 50);
    giq_option(4, 28, 2032, Node999, 50);
end

procedure Node203
begin
    gsay_reply(28, message_str(28, 2040));
    giq_option(4, 28, 2041, Node204, 50);
    giq_option(4, 28, 2042, Node205, 50);
    giq_option(4, 28, 2043, Node206, 50);
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node204
begin
    if (global_var(837) == 3) then begin
        gsay_reply(28, message_str(28, 2050) + message_str(28, 2051));
    end
    else begin
        gsay_reply(28, message_str(28, 2051));
    end
    giq_option(4, 28, 2042, Node205, 50);
    giq_option(4, 28, 2043, Node206, 50);
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node205
begin
    gsay_reply(28, message_str(28, 2060));
    giq_option(4, 28, 2041, Node204, 50);
    giq_option(4, 28, 2043, Node206, 50);
    giq_option(4, 28, 2061, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node206
begin
    gsay_reply(28, message_str(28, 2070));
    giq_option(4, 28, 2041, Node204, 50);
    giq_option(4, 28, 2042, Node205, 50);
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node207
begin
    gsay_reply(28, message_str(28, 2080));
    giq_option(4, 28, 2081, Node200, 50);
    giq_option(4, 28, 2082, Node999, 50);
end

procedure Node208
begin
    gsay_reply(28, message_str(28, 2090));
    giq_option(4, 28, 2091, Node209, 50);
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node209
begin
    gsay_reply(28, message_str(28, 2100));
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node210
begin
    gsay_reply(28, message_str(28, 2110));
    giq_option(4, 28, 2111, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node211
begin
    gsay_reply(28, message_str(28, 2120));
    giq_option(4, 28, 2121, Node212, 50);
    giq_option(4, 28, 2122, Node200, 50);
    giq_option(4, 28, 2123, Node999, 50);
end

procedure Node212
begin
    gsay_reply(28, message_str(28, 2130));
    giq_option(4, 28, 2131, Node213, 50);
    giq_option(4, 28, 2044, Node200, 50);
    giq_option(4, 28, 2045, Node999, 50);
end

procedure Node213
begin
    gsay_reply(28, message_str(28, 2140));
    giq_option(4, 28, 2141, Node200, 50);
    giq_option(4, 28, 2142, Node999, 50);
end

procedure Node214
begin
    if (((global_var(831) bwand 64) != 0) == 0) then begin
        set_global_var(831, global_var(831) bwor 64);
        display_msg(message_str(28, 3004));
        give_exp_points(100);
    end
    gsay_reply(28, message_str(28, 2150));
    giq_option(4, 28, 2151, Node215, 50);
    giq_option(4, 28, 2152, Node200, 50);
    giq_option(4, 28, 2153, Node999, 50);
end

procedure Node215
begin
    gsay_reply(28, message_str(28, 2160));
    giq_option(4, 28, 2161, Node216, 50);
end

procedure Node216
begin
    gsay_reply(28, message_str(28, 2170));
    if (has_skill(dude_obj, 14) >= 78) then begin
        giq_option(4, 28, 2171, Node219, 50);
    end
    else begin
        giq_option(4, 28, 2171, Node217, 50);
    end
    if ((has_skill(dude_obj, 14) >= 88) or (get_critter_stat(dude_obj, 6) > 8)) then begin
        giq_option(6, 28, 2172, Node218, 50);
    end
end

procedure Node217
begin
    set_local_var(8, local_var(8) bwor 262144);
    gsay_reply(28, message_str(28, 2180));
    giq_option(4, 28, 2181, Node200, 50);
    giq_option(4, 28, 2182, Node999, 50);
end

procedure Node218
begin
    gsay_reply(28, message_str(28, 2190));
    giq_option(4, 28, 2191, Node220, 50);
end

procedure Node219
begin
    gsay_reply(28, message_str(28, 2200));
    giq_option(4, 28, 2201, Node220, 50);
end

procedure Node220
begin
    display_msg(message_str(28, 3005));
    give_exp_points(200);
    set_global_var(831, global_var(831) bwor 128);
    set_local_var(8, local_var(8) bwand (-1 - 262144));
    gsay_reply(28, message_str(28, 2210));
    giq_option(4, 28, 2211, Node221, 50);
end

procedure Node221
begin
    gsay_reply(28, message_str(28, 2220));
    giq_option(4, 28, 2221, Node200, 50);
    giq_option(4, 28, 2222, Node999, 50);
end

procedure Node222
begin
    gsay_reply(28, message_str(28, 2230));
    giq_option(4, 28, 2231, Node223, 50);
    giq_option(4, 28, 2232, Node224, 50);
    giq_option(4, 28, 2233, Node200, 50);
    giq_option(4, 28, 2234, Node999, 50);
end

procedure Node223
begin
    gsay_reply(28, message_str(28, 2240));
    giq_option(4, 28, 2241, Node200, 50);
    giq_option(4, 28, 2242, Node999, 50);
end

procedure Node224
begin
    gsay_reply(28, message_str(28, 2250));
    giq_option(4, 28, 2251, Node200, 50);
    giq_option(4, 28, 2252, Node999, 50);
end

procedure solo_fight
begin
    set_local_var(8, local_var(8) bwor 32768);
    critter_add_trait(self_obj, 1, 6, 16);
    call Node998();
end

procedure revenge
begin
    set_global_var(830, global_var(830) bwor 1048576);
    call Node997();
end

procedure set_holy_anger
begin
    set_local_var(8, local_var(8) bwor 16384);
end

procedure holy_anger
begin
    float_msg(self_obj, message_str(28, 1989 + random(1, 5)), 2);
end

