procedure checkPartyMembersNearDoor;

variable range_perks;
variable math;

procedure start;
procedure critter_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure node000;
procedure node001;
procedure node002;
procedure node003;
procedure node004;
procedure node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node999;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(79) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(79)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(165) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(165)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(191) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(191)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(195) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(195)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(196) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(196)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(197) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(197)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(265) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(265)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(384) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(384)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(0) == 0) then begin
        display_msg(message_str(964, 11100));
    end
    else begin
        if (local_var(0) == 1) then begin
            display_msg(message_str(964, 11102));
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(964, 11101));
end

procedure pickup_p_proc
begin
    script_overrides;
    float_msg(self_obj, message_str(964, 11114), -2);
end

procedure talk_p_proc
begin
    if (global_var(767) == 0) then begin
        start_gdialog(964, self_obj, 4, -1, -1);
        gsay_start;
        call Node006();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (global_var(767) == 1) then begin
            start_gdialog(964, self_obj, 4, -1, -1);
            gsay_start;
            call Node007();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(767) == 2) then begin
                start_gdialog(964, self_obj, 4, -1, -1);
                gsay_start;
                call Node008();
                gsay_end;
                end_dialogue;
            end
            else begin
                if (global_var(767) == 3) then begin
                    start_gdialog(964, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node009();
                    gsay_end;
                    end_dialogue;
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    add_obj_to_inven(self_obj, create_object_sid(674, 0, 0, -1));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
end

procedure node000
begin
    gsay_reply(964, 11104);
    gsay_option(964, 11121, node001, 49);
    gsay_option(964, random(11115, 11118), Node999, 50);
end

procedure node001
begin
    gsay_reply(964, 11105);
    gsay_option(964, 11122, node002, 50);
end

procedure node002
begin
    gsay_reply(964, 11106);
    gsay_option(964, 11123, node003, 50);
end

procedure node003
begin
    gsay_reply(964, 11107);
    gsay_option(964, 11124, node004, 50);
end

procedure node004
begin
    gsay_reply(964, 11108);
    add_obj_to_inven(dude_obj, create_object_sid(674, 0, 0, -1));
    set_global_var(767, 1);
    gsay_option(964, 11119, Node999, 50);
end

procedure node005
begin
    gsay_reply(964, 11111);
    add_mult_objs_to_inven(dude_obj, create_object_sid(755, 0, 0, -1), 3);
    add_mult_objs_to_inven(dude_obj, create_object_sid(759, 0, 0, -1), 5);
    give_exp_points(3000);
    set_global_var(767, 3);
    gsay_option(964, 11126, Node999, 50);
end

procedure Node006
begin
    gsay_reply(964, 11103);
    gsay_option(964, 11120, node000, 50);
    gsay_option(964, random(11115, 11118), Node999, 50);
    set_local_var(0, 1);
end

procedure Node007
begin
    gsay_reply(964, 11110);
    gsay_option(964, random(11115, 11118), Node999, 50);
end

procedure Node008
begin
    gsay_reply(964, 11109);
    gsay_option(964, 11125, node005, 50);
end

procedure Node009
begin
    gsay_reply(964, random(11113, 11114));
    gsay_option(964, random(11115, 11118), Node999, 50);
end

procedure Node999
begin
end

