variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node008a;
procedure Node008b;
procedure Node008c;
procedure Node009a;
procedure Node003a;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node009;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(1802, 100));
    end
    else begin
        display_msg(message_str(1802, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1802, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
    if (global_var(1010) == 0) then begin
        if (local_var(4) == 2) then begin
            float_msg(self_obj, message_str(1802, 105), 0);
        end
        else begin
            start_gdialog(1802, self_obj, 4, -1, -1);
            gsay_start;
            call Node001();
            gsay_end;
            end_dialogue;
        end
    end
    else begin
        if (local_var(4) == 2) then begin
            start_gdialog(1802, self_obj, 4, -1, -1);
            gsay_start;
            call Node004();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (local_var(4) == 3) then begin
                start_gdialog(1802, self_obj, 4, -1, -1);
                gsay_start;
                call Node013();
                gsay_end;
                end_dialogue;
            end
            else begin
                start_gdialog(1802, self_obj, 4, -1, -1);
                gsay_start;
                call Node010();
                gsay_end;
                end_dialogue;
            end
        end
    end
end

procedure Node001
begin
    gsay_reply(1802, 106);
    giq_option(4, 1802, 107, Node002, 50);
end

procedure Node002
begin
    gsay_reply(1802, 108);
    giq_option(4, 1802, 109, Node003, 50);
    giq_option(4, 1802, 110, Node003a, 50);
end

procedure Node003
begin
    gsay_reply(1802, 111);
    giq_option(4, 1802, 112, Node003a, 50);
end

procedure Node004
begin
    gsay_reply(1802, 113);
    giq_option(4, 1802, 114, Node005, 50);
end

procedure Node005
begin
    gsay_reply(1802, 115);
    giq_option(4, 1802, 116, Node006, 50);
end

procedure Node006
begin
    gsay_reply(1802, 117);
    giq_option(4, 1802, 118, Node007, 50);
end

procedure Node007
begin
    gsay_reply(1802, 119);
    if (has_skill(dude_obj, 14) >= 100) then begin
        giq_option(4, 1802, 120, Node008, 50);
    end
    if (has_skill(dude_obj, 14) < 100) then begin
        giq_option(4, 1802, 121, Node009, 50);
    end
end

procedure Node008
begin
    gsay_reply(1802, 122);
    if (item_caps_total(dude_obj) > 1500) then begin
        giq_option(4, 1802, 123, Node008b, 50);
    end
    giq_option(4, 1802, 124, Node008a, 50);
end

procedure Node008a
begin
    set_local_var(4, 3);
end

procedure Node008b
begin
    gsay_reply(1802, 125);
    giq_option(4, 1802, 126, Node008c, 50);
    item_caps_adjust(self_obj, 1500);
    item_caps_adjust(dude_obj, -1500);
end

procedure Node008c
begin
    set_global_var(1010, 2);
    gfade_out(10 * 6);
    game_ui_disable;
    move_to(self_obj, 16674, 2);
    game_ui_enable;
    gfade_in(10 * 6);
end

procedure Node009a
begin
    gsay_reply(1802, 125);
    giq_option(4, 1802, 126, Node008c, 50);
    item_caps_adjust(self_obj, 2000);
    item_caps_adjust(dude_obj, -2000);
end

procedure Node003a
begin
    set_local_var(4, 2);
end

procedure Node010
begin
    gsay_reply(1802, 130);
    giq_option(4, 1802, message_str(1802, 131) + obj_name(dude_obj) + message_str(1802, 132), Node011, 50);
end

procedure Node011
begin
    gsay_reply(1802, 133);
    giq_option(4, 1802, 134, Node012, 50);
end

procedure Node012
begin
    gsay_reply(1802, 135);
    if (has_skill(dude_obj, 14) >= 100) then begin
        giq_option(4, 1802, 136, Node008, 50);
    end
    if (has_skill(dude_obj, 14) < 100) then begin
        giq_option(4, 1802, 137, Node009, 50);
    end
end

procedure Node013
begin
    gsay_reply(1802, 138);
    if ((has_skill(dude_obj, 14) < 100) and (item_caps_total(dude_obj) > 2000)) then begin
        giq_option(4, 1802, 139, Node009a, 50);
    end
    if ((has_skill(dude_obj, 14) >= 100) and (item_caps_total(dude_obj) > 1500)) then begin
        giq_option(4, 1802, 140, Node012, 50);
    end
    giq_option(4, 1802, 141, Node999, 50);
end

procedure Node009
begin
    gsay_reply(1802, 127);
    if (item_caps_total(dude_obj) > 2000) then begin
        giq_option(4, 1802, 128, Node009a, 50);
    end
    giq_option(4, 1802, 129, Node008a, 50);
end

procedure timed_event_p_proc
begin
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    debug_msg("LVAR_Herebefore == " + local_var(4));
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
    end
end

