variable in_dialog;

procedure start;
procedure critter_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure wield_spear_p_proc;
procedure Node009;

variable WIELD_Once;

import variable WARRIOR_obj;

procedure timed_event_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure Node999;
procedure Node990;


procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (global_var(11) == 1) then begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
        else begin
            if (global_var(1121) == 1) then begin
                attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
            end
        end
    end
    if ((global_var(1127) == 3) and obj_can_see_obj(self_obj, dude_obj)) then begin
        if (in_dialog == 0) then begin
            in_dialog := 1;
            start_gdialog(2299, self_obj, 4, -1, -1);
            gsay_start;
            call Node006();
            gsay_end;
            end_dialogue;
            in_dialog := 0;
        end
        else begin
            call Node006();
        end
    end
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(2299, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(2299, 101));
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    set_global_var(1121, 1);
    attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
end

procedure map_enter_p_proc
begin
    call wield_spear_p_proc();
    critter_add_trait(self_obj, 1, 6, 214);
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
    if ((global_var(1127) > 4) and (global_var(1127) < 8)) then begin
        if (global_var(494) == 8) then begin
            float_msg(self_obj, message_str(2299, random(500, 501)), 8);
        end
        else begin
            start_gdialog(2299, self_obj, 4, -1, -1);
            gsay_start;
            call Node009();
            gsay_end;
            end_dialogue;
        end
    end
    else begin
        if (global_var(1127) == 0) then begin
            start_gdialog(2299, self_obj, 4, -1, -1);
            gsay_start;
            call Node001();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(1127) < 5) then begin
                start_gdialog(2299, self_obj, 4, -1, -1);
                gsay_start;
                call Node004();
                gsay_end;
                end_dialogue;
            end
            else begin
                start_gdialog(2299, self_obj, 4, -1, -1);
                gsay_start;
                call Node001();
                gsay_end;
                end_dialogue;
            end
        end
    end
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
    end
end

procedure Node001
begin
    if (local_var(4) == 0) then begin
        gsay_reply(2299, 200);
        giq_option(4, 2299, 201, Node002, 50);
    end
    else begin
        gsay_reply(2299, 206);
        giq_option(4, 2299, 207, Node999, 50);
    end
end

procedure Node002
begin
    gsay_reply(2299, 202);
    giq_option(4, 2299, 203, Node003, 50);
end

procedure Node003
begin
    gsay_reply(2299, 204);
    giq_option(4, 2299, 205, Node999, 50);
end

procedure Node004
begin
    if (local_var(4) == 0) then begin
        gsay_reply(2299, 200);
    end
    else begin
        gsay_reply(2299, 206);
    end
    if (global_var(1127) == 1) then begin
        giq_option(4, 2299, 208, Node005, 50);
    end
    else begin
        giq_option(4, 2299, 207, Node999, 50);
    end
end

procedure Node005
begin
    gsay_reply(2299, 209);
    giq_option(4, 2299, 210, Node990, 50);
end

procedure Node006
begin
    gsay_reply(2299, 300);
    giq_option(4, 2299, 301, Node007, 50);
end

procedure Node007
begin
    gsay_reply(2299, 302);
    giq_option(4, 2299, 303, Node008, 50);
end

procedure Node008
begin
    set_global_var(1127, 4);
    move_to(WARRIOR_obj, 18517, 1);
    load_map(163, 0);
end

procedure wield_spear_p_proc
begin
    if (WIELD_Once == 0) then begin
        wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 280));
        WIELD_Once := 1;
    end
end

procedure Node009
begin
    if (local_var(7) == 0) then begin
        set_local_var(7, 1);
        gsay_reply(2299, 400);
        giq_option(4, 2299, 401, Node999, 50);
    end
    else begin
        gsay_reply(2299, 402);
        giq_option(4, 2299, 403, Node999, 50);
    end
end

procedure timed_event_p_proc
begin
end

procedure destroy_p_proc
begin
    destroy_object(tile_contains_pid_obj(17311, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17110, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17309, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17308, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17507, 0, 33554499));
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(65, global_var(65) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(65, global_var(65) - 10);
    set_global_var(1121, 1);
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(1121, 1);
    end
end

procedure Node999
begin
end

procedure Node990
begin
    destroy_object(tile_contains_pid_obj(17311, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17110, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17309, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17308, 0, 33554499));
    destroy_object(tile_contains_pid_obj(17507, 0, 33554499));
end

