variable tmp_gen_rep;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;

procedure start;
procedure combat_p_proc;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure wield_spear_p_proc;

variable In_Timed_Event;
variable STEAL_Once;
variable WIELD_Once;

procedure timed_event_p_proc;
procedure pickup_p_proc;


procedure start
begin
    if (local_var(7) == 0) then begin
        set_local_var(7, tile_num(self_obj));
    end
end

procedure combat_p_proc
begin
    if (global_var(1121) == 1) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        tmp_gen_rep := global_var(0);
        if (has_trait(0, dude_obj, 95)) then begin
            tmp_gen_rep := global_var(0) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(65, global_var(65) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(65, global_var(65) - 10);
    set_global_var(1121, 1);
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj) and (global_var(11) == 1)) then begin
        float_msg(self_obj, message_str(2286, 210), 8);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if ((random(0, 100) == 1) and (In_Timed_Event == 0) and not(combat_is_initialized)) then begin
        In_Timed_Event := 1;
        add_timer_event(self_obj, game_ticks(random(5, 9)), 1);
    end
    if ((global_var(1121) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
    if (global_var(1120) == 2) then begin
        call wield_spear_p_proc();
    end
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(2286, 100));
    end
    else begin
        display_msg(message_str(2286, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(2286, 102));
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    set_global_var(1121, 1);
    attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, 1, 6, 214);
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
    end
    if (global_var(494) == 8) then begin
        float_msg(self_obj, message_str(2286, random(300, 301)), 8);
    end
    else begin
        if ((global_var(860) > 1) or (global_var(1120) == 2) or (global_var(1124) == 3) or (global_var(1123) >= 3)) then begin
            float_msg(self_obj, message_str(2286, random(204, 208)), 9);
        end
        else begin
            float_msg(self_obj, message_str(2286, random(200, 203)), 2);
        end
    end
end

procedure wield_spear_p_proc
begin
    if (WIELD_Once == 0) then begin
        wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 7));
        WIELD_Once := 1;
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (tile_distance(tile_num(self_obj), local_var(7)) < 10) then begin
            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), random(0, 5), random(3, 7)), 0);
        end
        else begin
            animate_move_obj_to_tile(self_obj, tile_num_in_direction(local_var(7), random(0, 5), random(3, 7)), 0);
        end
        In_Timed_Event := 0;
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(1121, 1);
    end
end

