variable tmp_gen_rep;

procedure start;
procedure use_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;
procedure drop_p_proc;
procedure Node999;
procedure Node900;
procedure Node001;
procedure Node002;
procedure Node003;
procedure look_at_p_proc;
procedure description_p_proc;
procedure Node004;


procedure start
begin
end

procedure use_p_proc
begin
    if (not(combat_is_initialized)) then begin
        start_gdialog(2457, self_obj, 4, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
    end
end

procedure pickup_p_proc
begin
    if (not(combat_is_initialized)) then begin
        start_gdialog(2457, self_obj, 4, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
    end
    script_overrides;
end

procedure destroy_p_proc
begin
end

procedure drop_p_proc
begin
end

procedure Node999
begin
end

procedure Node900
begin
    if (message_str(1517, 100) != 0) then begin
        if (party_member_obj(16777376) != 0) then begin
            call Node004();
        end
        else begin
            if ((get_critter_stat(dude_obj, 1) > 8) or has_trait(0, dude_obj, 107) or has_trait(0, dude_obj, 17) or has_trait(0, dude_obj, 32) or (has_skill(dude_obj, 12) > 69) or (has_skill(dude_obj, 7) > 84) or (has_skill(dude_obj, 6) > 99)) then begin
                call Node003();
            end
            else begin
                call Node002();
            end
        end
    end
end

procedure Node001
begin
    gsay_reply(2457, 200);
    giq_option(4, 2457, 201, Node900, 50);
    giq_option(4, 2457, 202, Node999, 50);
end

procedure Node002
begin
    gsay_reply(2457, 203);
    giq_option(4, 2457, 204, Node999, 50);
end

procedure Node003
begin
    set_map_var(2, 1);
    gsay_reply(2457, 205);
    giq_option(4, 2457, 206, Node999, 50);
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(2457, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(2457, 101 + map_var(2)));
end

procedure Node004
begin
    set_map_var(2, 1);
    gsay_reply(1517, 207);
    giq_option(4, 1517, 206, Node999, 50);
end

