variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure getTimeBit;
procedure start;
procedure map_enter_p_proc;
procedure critter_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777703) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777703)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure getTimeBit
begin
    variable LVar0 := 0;
    LVar0 := game_time_hour;
    if ((LVar0 >= 100) and (LVar0 <= 159)) then begin
        return 1;
    end
    if ((LVar0 >= 200) and (LVar0 <= 259)) then begin
        return 2;
    end
    if ((LVar0 >= 300) and (LVar0 <= 359)) then begin
        return 4;
    end
    if ((LVar0 >= 400) and (LVar0 <= 459)) then begin
        return 8;
    end
    if ((LVar0 >= 500) and (LVar0 <= 559)) then begin
        return 16;
    end
    if ((LVar0 >= 600) and (LVar0 <= 659)) then begin
        return 32;
    end
    if ((LVar0 >= 700) and (LVar0 <= 759)) then begin
        return 64;
    end
    if ((LVar0 >= 800) and (LVar0 <= 859)) then begin
        return 128;
    end
    if ((LVar0 >= 900) and (LVar0 <= 959)) then begin
        return 256;
    end
    if ((LVar0 >= 1000) and (LVar0 <= 1059)) then begin
        return 512;
    end
    if ((LVar0 >= 1100) and (LVar0 <= 1159)) then begin
        return 1024;
    end
    if ((LVar0 >= 1200) and (LVar0 <= 1259)) then begin
        return 2048;
    end
    if ((LVar0 >= 1300) and (LVar0 <= 1359)) then begin
        return 4096;
    end
    if ((LVar0 >= 1400) and (LVar0 <= 1459)) then begin
        return 8192;
    end
    if ((LVar0 >= 1500) and (LVar0 <= 1559)) then begin
        return 16384;
    end
    if ((LVar0 >= 1600) and (LVar0 <= 1659)) then begin
        return 32768;
    end
    if ((LVar0 >= 1700) and (LVar0 <= 1759)) then begin
        return 65536;
    end
    if ((LVar0 >= 1800) and (LVar0 <= 1859)) then begin
        return 131072;
    end
    if ((LVar0 >= 1900) and (LVar0 <= 1959)) then begin
        return 262144;
    end
    if ((LVar0 >= 2000) and (LVar0 <= 2059)) then begin
        return 524288;
    end
    if ((LVar0 >= 2100) and (LVar0 <= 2159)) then begin
        return 1048576;
    end
    if ((LVar0 >= 2200) and (LVar0 <= 2259)) then begin
        return 2097152;
    end
    if ((LVar0 >= 2300) and (LVar0 <= 2359)) then begin
        return 4194304;
    end
    if ((LVar0 >= 2400) and (LVar0 <= 2459)) then begin
        return 8388608;
    end
    return 0;
    LVar0 := 0;
end

procedure start
begin
end

procedure map_enter_p_proc
begin
    if ((cur_map_index == 78) and (global_var(776) == 0)) then begin
        set_obj_visibility(self_obj, 1);
    end
    else begin
        if ((cur_map_index == 78) and (global_var(776) == 5)) then begin
            set_obj_visibility(self_obj, 1);
        end
        else begin
            if ((cur_map_index == 78) and ((global_var(776) == 1) or (global_var(776) == 2) or (global_var(776) == 3))) then begin
                set_obj_visibility(self_obj, 0);
            end
            else begin
                if ((cur_map_index == 79) and not(global_var(776) == 5)) then begin
                    set_obj_visibility(self_obj, 1);
                end
                else begin
                    if ((cur_map_index == 79) and (global_var(776) == 5)) then begin
                        set_obj_visibility(self_obj, 0);
                    end
                end
            end
        end
    end
end

procedure critter_p_proc
begin
    if ((local_var(1) == 0) and (global_var(776) == 0) and (tile_distance_objs(self_obj, dude_obj) <= 5) and (has_trait(1, self_obj, 666) == 1)) then begin
        call talk_p_proc();
    end
    else begin
        if ((local_var(1) == 2) and (tile_distance_objs(self_obj, dude_obj) <= 5) and (has_trait(1, self_obj, 666) == 1)) then begin
            attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
        end
    end
end

procedure talk_p_proc
begin
    set_local_var(0, 1);
    if (global_var(776) == 0) then begin
        start_gdialog(1590, self_obj, 4, -1, -1);
        gsay_start;
        call Node001();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (global_var(776) == 1) then begin
            start_gdialog(1590, self_obj, 4, -1, -1);
            gsay_start;
            call Node009();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(776) == 2) then begin
                start_gdialog(1590, self_obj, 4, -1, -1);
                gsay_start;
                call Node013();
                gsay_end;
                end_dialogue;
            end
            else begin
                if ((global_var(776) == 3) or (global_var(776) == 4)) then begin
                    start_gdialog(1590, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node014();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    if (global_var(776) == 5) then begin
                        start_gdialog(1590, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node017();
                        gsay_end;
                        end_dialogue;
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(0) == 0) then begin
        display_msg(message_str(1590, 100));
    end
    else begin
        display_msg(message_str(1590, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(1590, 102));
end

procedure Node998
begin
    set_local_var(1, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1590, 103);
    end
    else begin
        gsay_reply(1590, 150);
    end
    giq_option(3, 1590, 104, Node002, 50);
    giq_option(3, 1590, 105, Node998, 51);
    giq_option(-3, 1590, 106, Node007, 51);
end

procedure Node002
begin
    gsay_reply(1590, 107);
    giq_option(3, 1590, 108, Node003, 50);
    giq_option(3, 1590, 109, Node004, 50);
end

procedure Node003
begin
    gsay_reply(1590, 111);
    giq_option(3, 1590, 113, Node005, 50);
end

procedure Node004
begin
    gsay_reply(1590, 112);
    giq_option(3, 1590, 113, Node005, 50);
end

procedure Node005
begin
    gsay_reply(1590, 114);
    giq_option(3, 1590, 115, Node006, 50);
    giq_option(3, 1590, 120, Node008, 50);
    giq_option(3, 1590, 116, Node998, 51);
end

procedure Node006
begin
    gsay_reply(1590, 117);
    giq_option(3, 1590, 118, Node007, 50);
end

procedure Node007
begin
    gfade_out(600);
    set_global_var(776, 1);
    set_obj_visibility(tile_contains_pid_obj(18729, 1, 16777472), 1);
    set_global_var(0, global_var(0) + 5);
    debug_msg("Player gains " + 5 + " Karma Points.");
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    give_exp_points(500);
    display_msg(message_str(1590, 119));
    gfade_in(600);
end

procedure Node008
begin
    gsay_reply(1590, 121);
    giq_option(3, 1590, 122, Node007, 50);
end

procedure Node009
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1590, 123);
    end
    else begin
        gsay_reply(1590, 124);
    end
    giq_option(3, 1590, 125, Node010, 50);
    giq_option(3, 1590, 126, Node999, 50);
    giq_option(-3, 1590, 106, Node999, 51);
end

procedure Node010
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1590, 127);
    end
    else begin
        gsay_reply(1590, 128);
    end
    giq_option(3, 1590, 129, Node012, 50);
    giq_option(3, 1590, 130, Node011, 49);
    giq_option(3, 1590, 146, Node018, 51);
end

procedure Node011
begin
    set_global_var(776, 3);
    gsay_reply(1590, 131);
    giq_option(1, 1590, 155, Node999, 50);
end

procedure Node012
begin
    set_global_var(776, 2);
    gsay_reply(1590, 132);
    giq_option(1, 1590, 155, Node999, 50);
end

procedure Node013
begin
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        gsay_reply(1590, 133);
    end
    else begin
        gsay_reply(1590, 134);
    end
    giq_option(3, 1590, 135, Node011, 50);
    if (get_critter_stat(dude_obj, 34) == 0) then begin
        giq_option(3, 1590, 136, Node999, 50);
    end
    else begin
        giq_option(3, 1590, 137, Node999, 50);
    end
end

procedure Node014
begin
    gsay_reply(1590, 138);
    if (global_var(776) == 4) then begin
        giq_option(3, 1590, 140, Node015, 50);
    end
    giq_option(3, 1590, 139, Node999, 50);
end

procedure Node015
begin
    gsay_reply(1590, 141);
    giq_option(3, 1590, 142, Node016, 50);
end

procedure Node016
begin
    gfade_out(600);
    set_global_var(776, 5);
    set_obj_visibility(self_obj, 1);
    give_exp_points(500);
    display_msg(message_str(1590, 143));
    gfade_in(600);
end

procedure Node017
begin
    gsay_reply(1590, 144);
    giq_option(3, 1590, 145, Node999, 50);
end

procedure Node018
begin
    gsay_reply(1590, 147);
    giq_option(3, 1590, 149, Node011, 49);
    giq_option(3, 1590, 148, Node012, 51);
end

