variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node010a;
procedure Node010b;
procedure Node011;
procedure Node011a;
procedure Node012;
procedure Node013;
procedure Node013a;
procedure Node014;
procedure Node014a;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;

variable From_28;
variable DayPass_KickOutObj;
variable DayPass_KickOutCount;
variable CitizenPapers_KickOutObj;
variable CitizenPapers_KickOutCount;
variable KickOutTemp;
variable Only_Once;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) or (global_var(137) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack_complex(dude_obj, 0, 1, 0, 0, 30000, 0, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 2;
    Karma_Perception := 10;
    From_28 := 0;
    set_global_var(37, 0);
    set_global_var(38, 0);
    set_global_var(39, 0);
    set_global_var(40, 0);
    set_global_var(41, 0);
    set_global_var(42, 0);
    set_global_var(43, 0);
    set_global_var(44, 0);
    set_global_var(45, 0);
    if (global_var(0) >= 1000) then begin
        set_global_var(37, 1);
    end
    else begin
        if (global_var(0) >= 750) then begin
            set_global_var(38, 1);
        end
        else begin
            if (global_var(0) >= 500) then begin
                set_global_var(39, 1);
            end
            else begin
                if (global_var(0) >= 250) then begin
                    set_global_var(40, 1);
                end
                else begin
                    if (global_var(0) > -250) then begin
                        set_global_var(41, 1);
                    end
                    else begin
                        if (global_var(0) > -500) then begin
                            set_global_var(42, 1);
                        end
                        else begin
                            if (global_var(0) > -750) then begin
                                set_global_var(43, 1);
                            end
                            else begin
                                if (global_var(0) > -1000) then begin
                                    set_global_var(44, 1);
                                end
                                else begin
                                    set_global_var(45, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (get_critter_stat(dude_obj, 3) - get_critter_stat(self_obj, 3)) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(50) >= 0) then begin
        reaction_bonus_town_rep := global_var(50) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(50) / 2);
    end
    if (has_trait(2, dude_obj, 13)) then begin
        if (get_critter_stat(dude_obj, 34) == get_critter_stat(self_obj, 34)) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(37) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(38) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(39) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(40) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(41) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(42) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(43) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(44) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(11) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(11) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(11) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(0, dude_obj, 10));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(1) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if ((game_time_hour > 200) and (game_time_hour < 700)) then begin
        float_msg(self_obj, message_str(956, 245), 8);
    end
    else begin
        if (global_var(494) == 8) then begin
            start_gdialog(956, self_obj, 4, -1, -1);
            gsay_start;
            call Node008();
            gsay_end;
            end_dialogue;
        end
        else begin
            if ((party_member_obj(16777377) != 0) and (global_var(79) != 5)) then begin
                call Node005();
            end
            else begin
                if ((party_member_obj(16777323) != 0) and (global_var(79) != 5)) then begin
                    call Node006();
                end
                else begin
                    if ((game_time_hour <= 600) or (game_time_hour >= 1800)) then begin
                        call Node007();
                    end
                    else begin
                        start_gdialog(956, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node010();
                        gsay_end;
                        end_dialogue;
                    end
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(5, global_var(5) + 1);
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(4) > (3 * global_var(5))) or (global_var(2) == 1)) and (global_var(1) == 0)) then begin
            set_global_var(2, 1);
            set_global_var(3, 0);
        end
        if (metarule(51, self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(2, 0);
                set_global_var(1, global_var(1) + 1);
                set_global_var(0, global_var(0) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(37, 0);
                set_global_var(38, 0);
                set_global_var(39, 0);
                set_global_var(40, 0);
                set_global_var(41, 0);
                set_global_var(42, 0);
                set_global_var(43, 0);
                set_global_var(44, 0);
                set_global_var(45, 0);
                if (global_var(0) >= 1000) then begin
                    set_global_var(37, 1);
                end
                else begin
                    if (global_var(0) >= 750) then begin
                        set_global_var(38, 1);
                    end
                    else begin
                        if (global_var(0) >= 500) then begin
                            set_global_var(39, 1);
                        end
                        else begin
                            if (global_var(0) >= 250) then begin
                                set_global_var(40, 1);
                            end
                            else begin
                                if (global_var(0) > -250) then begin
                                    set_global_var(41, 1);
                                end
                                else begin
                                    if (global_var(0) > -500) then begin
                                        set_global_var(42, 1);
                                    end
                                    else begin
                                        if (global_var(0) > -750) then begin
                                            set_global_var(43, 1);
                                        end
                                        else begin
                                            if (global_var(0) > -1000) then begin
                                                set_global_var(44, 1);
                                            end
                                            else begin
                                                set_global_var(45, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(50, global_var(50) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(4) + global_var(5)) >= 25) and ((global_var(5) > (2 * global_var(4))) or (global_var(3) == 1))) then begin
            set_global_var(3, 1);
            set_global_var(2, 0);
        end
        set_global_var(0, global_var(0) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(37, 0);
        set_global_var(38, 0);
        set_global_var(39, 0);
        set_global_var(40, 0);
        set_global_var(41, 0);
        set_global_var(42, 0);
        set_global_var(43, 0);
        set_global_var(44, 0);
        set_global_var(45, 0);
        if (global_var(0) >= 1000) then begin
            set_global_var(37, 1);
        end
        else begin
            if (global_var(0) >= 750) then begin
                set_global_var(38, 1);
            end
            else begin
                if (global_var(0) >= 500) then begin
                    set_global_var(39, 1);
                end
                else begin
                    if (global_var(0) >= 250) then begin
                        set_global_var(40, 1);
                    end
                    else begin
                        if (global_var(0) > -250) then begin
                            set_global_var(41, 1);
                        end
                        else begin
                            if (global_var(0) > -500) then begin
                                set_global_var(42, 1);
                            end
                            else begin
                                if (global_var(0) > -750) then begin
                                    set_global_var(43, 1);
                                end
                                else begin
                                    if (global_var(0) > -1000) then begin
                                        set_global_var(44, 1);
                                    end
                                    else begin
                                        set_global_var(45, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(50, global_var(50) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(message_str(956, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(956, 101));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
        set_global_var(137, 1);
        set_global_var(79, 6);
        set_global_var(50, global_var(50) + -30);
        set_global_var(81, 0);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    From_28 := 0;
    critter_add_trait(self_obj, 1, 6, 26);
    critter_add_trait(self_obj, 1, 5, 33);
    if (not(metarule(22, 0))) then begin
        if ((game_time_hour > 200) and (game_time_hour < 700)) then begin
            move_to(self_obj, 25721, 0);
            critter_attempt_placement(self_obj, 25721, 0);
            anim(self_obj, 1000, 3);
            add_timer_event(self_obj, game_ticks(random(30, 40)), 1);
        end
        else begin
            move_to(self_obj, 20717, 0);
            critter_attempt_placement(self_obj, 20717, 0);
            anim(self_obj, 1000, 3);
            add_timer_event(self_obj, game_ticks(random(30, 40)), 1);
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        if (not(combat_is_initialized)) then begin
            if ((game_time_hour > 200) and (game_time_hour < 700)) then begin
                float_msg(self_obj, message_str(956, 245), 8);
            end
            else begin
                if (global_var(494) == 8) then begin
                    call Node002();
                end
                else begin
                    if ((game_time_hour > 600) and (game_time_hour < 1800) and (global_var(79) == 5)) then begin
                        call Node003();
                    end
                    else begin
                        if ((game_time_hour > 600) and (game_time_hour < 1800) and (party_member_obj(16777377) != 0)) then begin
                            call Node005();
                        end
                        else begin
                            if ((game_time_hour > 600) and (game_time_hour < 1800) and (party_member_obj(16777323) != 0)) then begin
                                call Node006();
                            end
                            else begin
                                if ((game_time_hour > 600) and (game_time_hour < 1800) and (global_var(79) == 4)) then begin
                                    call Node004();
                                end
                            end
                        end
                    end
                end
            end
        end
        add_timer_event(self_obj, game_ticks(random(30, 40)), 1);
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
end

procedure Node002
begin
    float_msg(self_obj, message_str(956, random(104, 106)), 8);
end

procedure Node003
begin
    float_msg(self_obj, message_str(956, random(107, 108)), 8);
end

procedure Node004
begin
    float_msg(self_obj, message_str(956, random(109, 110)), 8);
end

procedure Node005
begin
    float_msg(self_obj, message_str(956, 111), 8);
    call Node998();
end

procedure Node006
begin
    float_msg(self_obj, message_str(956, 110), 8);
    call Node998();
end

procedure Node007
begin
    float_msg(self_obj, message_str(956, 113 + local_var(7)), 8);
    if (local_var(7) < 2) then begin
        set_local_var(7, local_var(7) + 1);
    end
end

procedure Node008
begin
    gsay_reply(956, 116);
    giq_option(-3, 956, 117, Node009, 51);
    giq_option(-3, 956, 118, Node999, 50);
    giq_option(4, 956, 119, Node012, 50);
    giq_option(4, 956, 120, Node024, 50);
    giq_option(4, 956, 121, Node999, 50);
end

procedure Node009
begin
    gsay_reply(956, 122);
    giq_option(-3, 956, 123, Node999, 50);
    giq_option(-3, 956, 124, Node999, 50);
end

procedure Node010
begin
    if (global_var(79) == 5) then begin
        gsay_reply(956, 125);
    end
    else begin
        if (global_var(79) == 4) then begin
            gsay_reply(956, 126);
        end
        else begin
            gsay_reply(956, 127);
        end
    end
    giq_option(-3, 956, 128, Node010a, 51);
    giq_option(-3, 956, 129, Node999, 50);
    giq_option(4, 956, 130, Node012, 50);
    giq_option(4, 956, 131, Node010b, 50);
    giq_option(4, 956, 132, Node999, 50);
end

procedure Node010a
begin
    if ((global_var(79) == 5) or (global_var(79) == 4)) then begin
        call Node009();
    end
    else begin
        call Node011();
    end
end

procedure Node010b
begin
    if ((global_var(79) == 5) or (global_var(79) == 4) or (global_var(494) == 8)) then begin
        call Node024();
    end
    else begin
        call Node023();
    end
end

procedure Node011
begin
    gsay_reply(956, 133);
    giq_option(-3, 956, 134, Node011a, 50);
    giq_option(-3, 956, 135, Node999, 50);
end

procedure Node011a
begin
    set_global_var(79, 6);
    set_global_var(81, 0);
    set_global_var(86, 0);
    DayPass_KickOutCount := obj_is_carrying_obj_pid(dude_obj, 255);
    if (DayPass_KickOutCount > 0) then begin
        DayPass_KickOutObj := obj_carrying_pid_obj(dude_obj, 255);
        KickOutTemp := rm_mult_objs_from_inven(dude_obj, DayPass_KickOutObj, DayPass_KickOutCount);
        destroy_object(DayPass_KickOutObj);
    end
    CitizenPapers_KickOutCount := obj_is_carrying_obj_pid(dude_obj, 256);
    if (CitizenPapers_KickOutCount > 0) then begin
        CitizenPapers_KickOutObj := obj_carrying_pid_obj(dude_obj, 256);
        KickOutTemp := rm_mult_objs_from_inven(dude_obj, CitizenPapers_KickOutObj, CitizenPapers_KickOutCount);
        destroy_object(CitizenPapers_KickOutObj);
    end
    set_global_var(50, global_var(50) + -30);
    load_map(15, 0);
end

procedure Node012
begin
    if ((global_var(81) == 0) and not(global_var(494) == 8)) then begin
        gsay_reply(956, message_str(956, 136) + " " + message_str(956, 137));
    end
    else begin
        gsay_reply(956, 137);
    end
    giq_option(4, 956, 138, Node014, 50);
    giq_option(4, 956, 139, Node022, 50);
    giq_option(4, 956, 140, Node013, 50);
    giq_option(4, 956, 141, Node010b, 50);
    giq_option(4, 956, 142, Node999, 50);
end

procedure Node013
begin
    if ((global_var(79) == 5) or (global_var(79) == 4) or (global_var(494) == 8) and (get_critter_stat(dude_obj, 34) == 0)) then begin
        gsay_reply(956, message_str(956, 143) + " " + message_str(956, 145));
    end
    else begin
        if ((global_var(79) == 5) or (global_var(79) == 4) or (global_var(494) == 8) and (get_critter_stat(dude_obj, 34) == 1)) then begin
            gsay_reply(956, message_str(956, 144) + " " + message_str(956, 145));
        end
        else begin
            gsay_reply(956, 145);
        end
    end
    if (item_caps_total(dude_obj) >= 5) then begin
        giq_option(4, 956, 146, Node013a, 50);
        giq_option(4, 956, 147, Node013a, 50);
        giq_option(4, 956, 148, Node013a, 50);
    end
    giq_option(4, 956, 149, Node014, 50);
    giq_option(4, 956, 150, Node010b, 50);
    if (item_caps_total(dude_obj) < 5) then begin
        giq_option(4, 956, 151, Node999, 50);
    end
    else begin
        giq_option(4, 956, 152, Node999, 50);
    end
end

procedure Node013a
begin
    item_caps_adjust(dude_obj, -5);
    critter_heal(dude_obj, 1);
    gfade_out(600);
    game_time_advance(60 * 10 * 3);
    gfade_in(600);
    call Node015();
end

procedure Node014
begin
    gsay_reply(956, 153);
    if (has_skill(dude_obj, 12) >= 75) then begin
        giq_option(4, 956, 154, Node017, 50);
    end
    giq_option(4, 956, 155, Node022, 50);
    giq_option(4, 956, 156, Node013, 50);
    if (item_caps_total(dude_obj) >= 20) then begin
        giq_option(4, 956, 157, Node014a, 50);
    end
    giq_option(4, 956, 158, Node010b, 50);
    if (item_caps_total(dude_obj) < 20) then begin
        giq_option(4, 956, 159, Node999, 50);
    end
    else begin
        giq_option(4, 956, 160, Node999, 50);
    end
end

procedure Node014a
begin
    item_caps_adjust(dude_obj, -20);
    critter_heal(dude_obj, 3);
    gfade_out(600);
    game_time_advance(60 * 10 * 3);
    gfade_in(600);
    call Node016();
end

procedure Node015
begin
    gsay_reply(956, 161);
    giq_option(4, 956, 162, Node013, 50);
    giq_option(4, 956, 163, Node014, 50);
    giq_option(4, 956, 164, Node010b, 50);
    giq_option(4, 956, 165, Node999, 50);
end

procedure Node016
begin
    set_local_var(8, local_var(8) + 1);
    if ((local_var(8) == 100) and (get_critter_stat(dude_obj, 6) > 8)) then begin
        if (get_critter_stat(dude_obj, 6) == 9) then begin
            critter_add_trait(dude_obj, 0, 108, 1);
        end
        else begin
            if (get_critter_stat(dude_obj, 6) == 10) then begin
                critter_add_trait(dude_obj, 0, 109, 1);
            end
        end
        gsay_reply(956, 166);
        giq_option(4, 956, 170, Node999, 50);
    end
    else begin
        if ((local_var(8) == 100) and (get_critter_stat(dude_obj, 6) < 3)) then begin
            if (get_critter_stat(dude_obj, 6) == 2) then begin
                critter_add_trait(dude_obj, 0, 110, 1);
            end
            else begin
                if (get_critter_stat(dude_obj, 6) == 1) then begin
                    critter_add_trait(dude_obj, 0, 111, 1);
                end
            end
            gsay_reply(956, 167);
            giq_option(4, 956, 169, Node999, 50);
        end
        else begin
            gsay_reply(956, 168);
        end
    end
    giq_option(4, 956, 171, Node013, 50);
    if (item_caps_total(dude_obj) >= 20) then begin
        giq_option(4, 956, 172, Node014a, 50);
    end
    if (has_skill(dude_obj, 12) >= 75) then begin
        giq_option(4, 956, 173, Node017, 50);
    end
    giq_option(4, 956, 174, Node010b, 50);
    giq_option(4, 956, 175, Node999, 50);
end

procedure Node017
begin
    gsay_reply(956, 176);
    giq_option(4, 956, 177, Node018, 50);
    giq_option(4, 956, 178, Node022, 50);
    giq_option(4, 956, 179, Node013, 50);
    if (item_caps_total(dude_obj) >= 20) then begin
        giq_option(4, 956, 180, Node014a, 50);
    end
    giq_option(4, 956, 181, Node010b, 50);
    giq_option(4, 956, 182, Node999, 50);
end

procedure Node018
begin
    gsay_reply(956, 183);
    if (get_critter_stat(dude_obj, 4) == 4) then begin
        giq_option(4, 956, 184, Node019, 50);
    end
    giq_option(4, 956, 185, Node020, 50);
    giq_option(4, 956, 186, Node010b, 50);
    giq_option(4, 956, 187, Node999, 50);
end

procedure Node019
begin
    gsay_reply(956, 188);
    giq_option(4, 956, 189, Node020, 50);
    giq_option(4, 956, 190, Node010b, 50);
    giq_option(4, 956, 191, Node999, 50);
end

procedure Node020
begin
    gsay_reply(956, 192);
    if (get_critter_stat(dude_obj, 4) == 4) then begin
        giq_option(4, 956, 193, Node021, 50);
    end
    giq_option(4, 956, 194, Node010b, 50);
    giq_option(4, 956, 195, Node999, 50);
end

procedure Node021
begin
    gsay_reply(956, 196);
    giq_option(4, 956, 197, Node010b, 50);
    giq_option(4, 956, 198, Node999, 50);
end

procedure Node022
begin
    if ((global_var(81) == 0) and not(global_var(494) == 8)) then begin
        gsay_reply(956, message_str(956, 199) + " " + message_str(956, 200));
    end
    else begin
        gsay_reply(956, 199);
    end
    giq_option(4, 956, 201, Node013, 50);
    giq_option(4, 956, 202, Node014, 50);
    giq_option(4, 956, 203, Node010b, 50);
    if ((global_var(81) == 0) and not(global_var(494) == 8)) then begin
        giq_option(4, 956, 204, Node999, 50);
    end
    else begin
        giq_option(4, 956, 205, Node999, 50);
    end
end

procedure Node023
begin
    gsay_reply(956, 206);
    giq_option(4, 956, 207, Node012, 50);
    giq_option(4, 956, 208, Node029, 50);
    giq_option(4, 956, 209, Node999, 50);
end

procedure Node024
begin
    if ((global_var(494) == 8) and (get_critter_stat(dude_obj, 34) == 0)) then begin
        gsay_reply(956, 210);
    end
    else begin
        if ((global_var(494) == 8) and (get_critter_stat(dude_obj, 34) == 1)) then begin
            gsay_reply(956, 211);
        end
        else begin
            if (global_var(79) == 5) then begin
                gsay_reply(956, 212);
            end
            else begin
                if (global_var(79) == 4) then begin
                    gsay_reply(956, 213);
                end
            end
        end
    end
    giq_option(4, 956, 214, Node025, 50);
    giq_option(4, 956, 215, Node028, 50);
    giq_option(4, 956, 216, Node012, 50);
    giq_option(4, 956, 217, Node999, 50);
end

procedure Node025
begin
    gsay_reply(956, 218);
    giq_option(4, 956, 219, Node026, 50);
    giq_option(4, 956, 220, Node028, 50);
    giq_option(4, 956, 221, Node012, 50);
    giq_option(4, 956, 222, Node999, 50);
end

procedure Node026
begin
    gsay_reply(956, 223);
    giq_option(4, 956, 224, Node027, 50);
    giq_option(4, 956, 225, Node028, 50);
    giq_option(4, 956, 226, Node012, 50);
    giq_option(4, 956, 227, Node999, 50);
end

procedure Node027
begin
    gsay_reply(956, 228);
    giq_option(4, 956, 229, Node010b, 50);
    giq_option(4, 956, 230, Node012, 50);
    giq_option(4, 956, 231, Node999, 50);
end

procedure Node028
begin
    From_28 := 1;
    gsay_reply(956, 232);
    giq_option(4, 956, 233, Node029, 51);
    giq_option(4, 956, 234, Node030, 50);
    giq_option(4, 956, 235, Node012, 50);
    giq_option(4, 956, 236, Node999, 50);
end

procedure Node029
begin
    if (get_critter_stat(dude_obj, 34) == 1) then begin
        gsay_reply(956, 237);
    end
    else begin
        gsay_reply(956, 238);
    end
    if (From_28 == 1) then begin
        From_28 := 0;
        giq_option(4, 956, 239, Node030, 50);
    end
    giq_option(4, 956, 240, Node012, 50);
    giq_option(4, 956, 241, Node999, 50);
end

procedure Node030
begin
    gsay_reply(956, 242);
    giq_option(4, 956, 243, Node012, 50);
    giq_option(4, 956, 244, Node999, 50);
end

