variable global_temp;
variable restock_obj;

procedure start;
procedure use_p_proc;
procedure talk_p_proc;
procedure look_p_proc;
procedure description_p_proc;
procedure Node001;
procedure Node001a;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node018a;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node034a;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node999;
procedure Node998;


procedure start
begin
end

procedure use_p_proc
begin
    variable LVar0 := 0;
    if (get_critter_stat(source_obj, 4) < 4) then begin
        if (source_obj == dude_obj) then begin
            display_msg(message_str(160, 102));
        end
        else begin
            display_msg(obj_name(source_obj) + message_str(160, 250));
        end
    end
    else begin
        dialogue_system_enter;
    end
    return 0;
    LVar0 := 0;
end

procedure talk_p_proc
begin
    if (global_var(604) == 2) then begin
        start_gdialog(160, self_obj, 4, 19, 21);
        gsay_start;
        call Node003();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (map_var(76) == 1) then begin
            start_gdialog(160, self_obj, 4, 19, 21);
            gsay_start;
            call Node007();
            gsay_end;
            end_dialogue;
        end
        else begin
            if ((global_var(152) == 1) and (global_var(604) == 1)) then begin
                start_gdialog(160, self_obj, 4, 19, 21);
                gsay_start;
                call Node011();
                gsay_end;
                end_dialogue;
            end
            else begin
                if ((global_var(152) == 1) and (global_var(604) == 2)) then begin
                    start_gdialog(160, self_obj, 4, 19, 21);
                    gsay_start;
                    call Node002();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    if (global_var(152) == 1) then begin
                        start_gdialog(160, self_obj, 4, 19, 21);
                        gsay_start;
                        call Node001();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if (local_var(1) == 1) then begin
                            start_gdialog(160, self_obj, 4, 19, 21);
                            gsay_start;
                            call Node006();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            if (global_var(604) == 1) then begin
                                start_gdialog(160, self_obj, 4, 19, 21);
                                gsay_start;
                                call Node011();
                                gsay_end;
                                end_dialogue;
                            end
                            else begin
                                if (global_var(604) == 2) then begin
                                    start_gdialog(160, self_obj, 4, 19, 21);
                                    gsay_start;
                                    call Node002();
                                    gsay_end;
                                    end_dialogue;
                                end
                                else begin
                                    start_gdialog(160, self_obj, 4, 19, 21);
                                    gsay_start;
                                    call Node004();
                                    gsay_end;
                                    end_dialogue;
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_p_proc
begin
    script_overrides;
    display_msg(message_str(160, 100));
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(160, 101));
end

procedure Node001
begin
    gsay_reply(160, message_str(160, 103));
    giq_option(4, 160, 107, Node010, 50);
    giq_option(4, 160, 108, Node010, 50);
    giq_option(4, 160, 109, Node001a, 50);
    giq_option(4, 160, 111, Node998, 50);
end

procedure Node001a
begin
    set_global_var(604, 1);
    call Node011();
end

procedure Node002
begin
    gsay_reply(160, message_str(160, 113));
    giq_option(4, 160, 118, Node999, 50);
end

procedure Node003
begin
    gsay_reply(160, message_str(160, 120));
    giq_option(4, 160, 412, Node034a, 50);
    giq_option(4, 160, 111, Node999, 50);
end

procedure Node004
begin
    if (local_var(3) == 0) then begin
        set_local_var(3, 1);
        gsay_reply(160, message_str(160, 126));
    end
    else begin
        gsay_reply(160, 129);
    end
    giq_option(4, 160, 130, Node012, 50);
    giq_option(4, 160, 131, Node020, 50);
    giq_option(4, 160, 132, Node021, 50);
    giq_option(4, 160, 133, Node022, 50);
    giq_option(4, 160, 135, Node999, 50);
end

procedure Node005
begin
    gsay_reply(160, 136);
    giq_option(4, 160, 137, Node012, 50);
    giq_option(4, 160, 138, Node020, 50);
    giq_option(4, 160, 139, Node021, 50);
    giq_option(4, 160, 140, Node022, 50);
    giq_option(4, 160, 141, Node999, 50);
end

procedure Node006
begin
    gsay_reply(160, 143);
    giq_option(4, 160, 144, Node999, 50);
end

procedure Node007
begin
    gsay_reply(160, message_str(160, 146) + message_str(160, 147));
    giq_option(4, 160, 149, Node999, 50);
end

procedure Node010
begin
    gsay_reply(160, 150);
    giq_option(4, 160, 151, Node001a, 50);
    giq_option(4, 160, 152, Node998, 50);
end

procedure Node011
begin
    if ((global_var(604) == 1) and (global_var(152) == 1)) then begin
        set_map_var(25, 1);
        set_map_var(26, 1);
        set_map_var(27, 0);
    end
    gsay_reply(160, message_str(160, 153));
end

procedure Node012
begin
    gsay_reply(160, 162);
    giq_option(4, 160, 163, Node013, 50);
    giq_option(4, 160, 164, Node018, 50);
    giq_option(4, 160, 165, Node016, 50);
    giq_option(4, 160, 166, Node023, 50);
end

procedure Node013
begin
    gsay_reply(160, 167);
    giq_option(4, 160, 168, Node014, 50);
    giq_option(8, 160, 169, Node025, 50);
    giq_option(4, 160, 170, Node024, 50);
end

procedure Node014
begin
    gsay_reply(160, 171);
    giq_option(4, 160, 172, Node015, 50);
    giq_option(4, 160, 173, Node024, 50);
end

procedure Node015
begin
    gsay_reply(160, message_str(160, 174) + message_str(160, 175));
    giq_option(4, 160, 176, Node016, 50);
    giq_option(4, 160, 177, Node024, 50);
    giq_option(4, 160, 178, Node024, 50);
end

procedure Node016
begin
    set_global_var(604, 1);
    gsay_reply(160, message_str(160, 179));
    giq_option(4, 160, 183, Node017, 50);
    giq_option(4, 160, 184, Node999, 50);
end

procedure Node017
begin
    set_map_var(25, 0);
    set_map_var(26, 0);
    set_map_var(27, 0);
    set_global_var(154, 0);
    gsay_reply(160, message_str(160, 185));
    giq_option(4, 160, 188, Node999, 50);
end

procedure Node018
begin
    gsay_reply(160, message_str(160, 189));
    if (has_skill(dude_obj, 14) > 75) then begin
        giq_option(4, 160, 194, Node019, 50);
    end
    giq_option(4, 160, 195, Node018a, 50);
end

procedure Node018a
begin
    set_global_var(152, 1);
    call Node998();
end

procedure Node019
begin
    gsay_reply(160, message_str(160, 196));
    giq_option(4, 160, 201, Node013, 50);
    giq_option(4, 160, 202, Node016, 50);
    giq_option(4, 160, 203, Node023, 50);
end

procedure Node020
begin
    gsay_reply(160, 204);
    giq_option(8, 160, 400, Node030, 50);
    giq_option(4, 160, 205, Node005, 50);
    giq_option(4, 160, 206, Node999, 50);
end

procedure Node021
begin
    gsay_reply(160, 207);
    giq_option(4, 160, 205, Node005, 50);
    giq_option(4, 160, 206, Node999, 50);
end

procedure Node022
begin
    gsay_reply(160, message_str(160, 210));
    giq_option(4, 160, 212, Node012, 50);
    giq_option(4, 160, 213, Node999, 50);
end

procedure Node023
begin
    set_global_var(604, 1);
    gsay_reply(160, message_str(160, 214));
    giq_option(4, 160, 220, Node999, 50);
end

procedure Node024
begin
    set_local_var(1, 1);
    gsay_reply(160, message_str(160, 221) + message_str(160, 222));
    giq_option(4, 160, 223, Node999, 50);
end

procedure Node025
begin
    gsay_reply(160, message_str(160, 224) + message_str(160, 225));
    giq_option(4, 160, 226, Node026, 50);
end

procedure Node026
begin
    gsay_reply(160, 227);
    giq_option(4, 160, 228, Node016, 50);
    giq_option(4, 160, 229, Node024, 50);
end

procedure Node030
begin
    gsay_reply(160, 401);
    giq_option(4, 160, 402, Node031, 50);
    giq_option(4, 160, 403, Node005, 50);
end

procedure Node031
begin
    gsay_reply(160, 404);
    giq_option(4, 160, 405, Node032, 50);
end

procedure Node032
begin
    gsay_reply(160, 406);
    giq_option(4, 160, 407, Node033, 50);
end

procedure Node033
begin
    gsay_reply(160, 408);
    giq_option(4, 160, 409, Node034, 50);
end

procedure Node034
begin
    gsay_reply(160, 410);
    giq_option(4, 160, 411, Node005, 50);
    giq_option(4, 160, 412, Node034a, 50);
end

procedure Node034a
begin
    variable LVar0 := 0;
    LVar0 := roll_vs_skill(dude_obj, 12, -80);
    if (is_success(LVar0)) then begin
        call Node036();
    end
    else begin
        call Node035();
    end
    return 0;
    LVar0 := 0;
end

procedure Node035
begin
    set_map_var(25, 1);
    set_map_var(26, 1);
    set_map_var(27, 1);
    set_global_var(152, 1);
    set_global_var(151, 1);
    set_global_var(154, 1);
    gsay_reply(160, 413);
    giq_option(4, 160, 414, Node999, 50);
end

procedure Node036
begin
    gsay_reply(160, 415);
    giq_option(4, 160, 416, Node037, 50);
    giq_option(4, 160, 417, Node039, 50);
    giq_option(4, 160, 418, Node042, 50);
    giq_option(4, 160, 419, Node999, 50);
end

procedure Node037
begin
    gsay_reply(160, 420);
    if (global_var(658) == 0) then begin
        giq_option(4, 160, 421, Node038, 50);
    end
    giq_option(4, 160, 422, Node036, 50);
end

procedure Node038
begin
    set_global_var(658, 1);
    restock_obj := create_object_sid(766, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    gsay_reply(160, 423);
    giq_option(4, 160, 424, Node036, 50);
end

procedure Node039
begin
    gsay_reply(160, 425);
    if (global_var(660) == 0) then begin
        giq_option(4, 160, 426, Node040, 50);
    end
    giq_option(4, 160, 427, Node036, 50);
end

procedure Node040
begin
    gsay_reply(160, 428);
    giq_option(4, 160, 429, Node041, 50);
    giq_option(4, 160, 430, Node036, 50);
end

procedure Node041
begin
    game_time_advance(2 * (60 * (60 * 10)));
    set_global_var(660, 1);
    restock_obj := create_object_sid(765, 0, 0, -1);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    gsay_reply(160, 431);
    giq_option(4, 160, 432, Node036, 50);
end

procedure Node042
begin
    gsay_reply(160, 433);
    giq_option(4, 160, 434, Node036, 50);
end

procedure Node999
begin
end

procedure Node998
begin
    set_global_var(154, 1);
    set_map_var(27, 1);
    set_map_var(77, 1);
    set_global_var(152, 1);
end

