variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node003a;
procedure Node003b;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node006a;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Enc001;
procedure Enc002;
procedure Enc003;
procedure Enc004;
procedure Enc005;
procedure Enc005a;
procedure Enc006;
procedure Enc007;
procedure Enc008;
procedure Enc008a;
procedure Enc009;
procedure Enc010;
procedure Enc011;
procedure Enc012;
procedure Enc013;
procedure Enc013a;

variable Only_Once;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
    if (global_var(GVAR_ENEMY_ARROYO) == 1) then begin
        attack(dude_obj);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 1;
    Karma_Perception := 10;
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (dude_charisma - self_charisma) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(GVAR_TOWN_REP_ARROYO) >= 0) then begin
        reaction_bonus_town_rep := global_var(GVAR_TOWN_REP_ARROYO) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(GVAR_TOWN_REP_ARROYO) / 2);
    end
    if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
        if (dude_gender == self_gender) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(GVAR_CHILDKILLER_REPUTATION) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    set_global_var(GVAR_TALKED_TO_ELDER, 1);
    if (CUR_MAP_ARVILLAG) then begin
        if (global_var(GVAR_FIND_VIC) == 0) then begin
            set_global_var(GVAR_FIND_VIC, 1);
        end
        if (local_var(5)) then begin
            call Node014();
            call Node998();
        end
        else begin
            if ((game_time / (10 * 60 * 60 * 24)) > 360) then begin
                start_gdialog(11, self_obj, 4, 3, 19);
                gsay_start;
                call Node020();
                gsay_end;
                end_dialogue;
            end
            else begin
                if ((game_time / (10 * 60 * 60 * 24)) > 270) then begin
                    start_gdialog(11, self_obj, 4, 3, 19);
                    gsay_start;
                    call Node019();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    if ((game_time / (10 * 60 * 60 * 24)) > 180) then begin
                        start_gdialog(11, self_obj, 4, 3, 19);
                        gsay_start;
                        call Node018();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if ((game_time / (10 * 60 * 60 * 24)) > 90) then begin
                            start_gdialog(11, self_obj, 4, 3, 19);
                            gsay_start;
                            call Node017();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            if (dude_iq < 4) then begin
                                start_gdialog(11, self_obj, 4, 3, 19);
                                gsay_start;
                                call Node002();
                                gsay_end;
                                end_dialogue;
                            end
                            else begin
                                if (local_var(1) < 0) then begin
                                    start_gdialog(11, self_obj, 4, 3, 19);
                                    gsay_start;
                                    call Node003();
                                    gsay_end;
                                    end_dialogue;
                                end
                                else begin
                                    if (local_var(4) == 0) then begin
                                        set_local_var(4, 1);
                                        start_gdialog(11, self_obj, 4, 3, 19);
                                        gsay_start;
                                        call Node001();
                                        gsay_end;
                                        end_dialogue;
                                    end
                                    else begin
                                        start_gdialog(11, self_obj, 4, 3, 19);
                                        gsay_start;
                                        call Node004();
                                        gsay_end;
                                        end_dialogue;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        set_global_var(GVAR_ENCLAVE_ELDER, 1);
        if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 349) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 232)) then begin
            start_gdialog(11, self_obj, 4, 3, 15);
            gsay_start;
            call Enc002();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (local_var(1) < 0) then begin
                start_gdialog(11, self_obj, 4, 3, 15);
                gsay_start;
                call Enc009();
                gsay_end;
                end_dialogue;
            end
            else begin
                if (local_var(11) == 0) then begin
                    set_local_var(11, local_var(11) + 1);
                    start_gdialog(11, self_obj, 4, 3, 15);
                    gsay_start;
                    call Enc001();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    start_gdialog(11, self_obj, 4, 3, 15);
                    gsay_start;
                    call Enc010();
                    gsay_end;
                    end_dialogue;
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - -15);
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(GVAR_TOWN_REP_ARROYO, global_var(GVAR_TOWN_REP_ARROYO) - 50);
    set_global_var(GVAR_ENEMY_ARROYO, 1);
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(9) == 0) then begin
        set_local_var(9, local_var(9) + 1);
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(102);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
        set_global_var(GVAR_ENEMY_ARROYO, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 1);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_ARROYO_ELDER);
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    Reply(103);
    giq_option(4, NAME, 104, Node006, BAD_REACTION);
    giq_option(4, NAME, 105, Node015, GOOD_REACTION);
    giq_option(4, NAME, 106, Node008, NEUTRAL_REACTION);
end

procedure Node002
begin
    variable LVar0 := 0;
    if (local_var(8) == 0) then begin
        set_local_var(8, 1);
        LVar0 := create_object(267, 0, 0);
        if (2 > global_var(GVAR_DEN_VIC_KNOWN)) then begin
            set_global_var(GVAR_DEN_VIC_KNOWN, 2);
        end
        add_mult_objs_to_inven(dude_obj, LVar0, 1);
        if (global_var(GVAR_FIND_VIC) == 0) then begin
            set_global_var(GVAR_FIND_VIC, 1);
        end
        Reply(107);
    end
    else begin
        Reply(112);
    end
    giq_option(-3, NAME, 113, Node016, NEUTRAL_REACTION);
end

procedure Node003
begin
    Reply(114);
    if (local_var(7)) then begin
        giq_option(4, NAME, 115, Node003a, GOOD_REACTION);
    end
    giq_option(4, NAME, 116, Node003b, BAD_REACTION);
end

procedure Node003a
begin
    if (dude_skill(SKILL_SPEECH) > 45) then begin
        set_local_var(3, local_var(3) + 20);
        set_local_var(0, local_var(0) + 20);
        if (local_var(0) <= -75) then begin
            set_local_var(1, -4);
        end
        else begin
            if (local_var(0) <= -50) then begin
                set_local_var(1, -3);
            end
            else begin
                if (local_var(0) <= -25) then begin
                    set_local_var(1, -2);
                end
                else begin
                    if (local_var(0) <= -10) then begin
                        set_local_var(1, -1);
                    end
                    else begin
                        if (local_var(0) <= 10) then begin
                            set_local_var(1, 0);
                        end
                        else begin
                            if (local_var(0) <= 25) then begin
                                set_local_var(1, 1);
                            end
                            else begin
                                if (local_var(0) <= 50) then begin
                                    set_local_var(1, 2);
                                end
                                else begin
                                    if (local_var(0) <= 75) then begin
                                        set_local_var(1, 3);
                                    end
                                    else begin
                                        set_local_var(1, 4);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (dude_charisma > 7) then begin
            set_local_var(3, local_var(3) + 10);
            set_local_var(0, local_var(0) + 10);
            if (local_var(0) <= -75) then begin
                set_local_var(1, -4);
            end
            else begin
                if (local_var(0) <= -50) then begin
                    set_local_var(1, -3);
                end
                else begin
                    if (local_var(0) <= -25) then begin
                        set_local_var(1, -2);
                    end
                    else begin
                        if (local_var(0) <= -10) then begin
                            set_local_var(1, -1);
                        end
                        else begin
                            if (local_var(0) <= 10) then begin
                                set_local_var(1, 0);
                            end
                            else begin
                                if (local_var(0) <= 25) then begin
                                    set_local_var(1, 1);
                                end
                                else begin
                                    if (local_var(0) <= 50) then begin
                                        set_local_var(1, 2);
                                    end
                                    else begin
                                        if (local_var(0) <= 75) then begin
                                            set_local_var(1, 3);
                                        end
                                        else begin
                                            set_local_var(1, 4);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure Node003b
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure Node004
begin
    Reply(117);
    if (town_known(11) != MARK_STATE_UNKNOWN) then begin
        giq_option(4, NAME, 118, Node005, NEUTRAL_REACTION);
    end
    if (local_var(7) == 0) then begin
        giq_option(4, NAME, 119, Node015, NEUTRAL_REACTION);
        giq_option(4, NAME, 121, Node013, BAD_REACTION);
    end
    else begin
        giq_option(4, NAME, 120, Node009, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 122, Node007, BAD_REACTION);
    giq_option(4, NAME, 123, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    Reply(124);
    giq_option(4, NAME, 125, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 126, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    Reply(127);
    giq_option(4, NAME, 128, Node015, NEUTRAL_REACTION);
    giq_option(4, NAME, 129, Node006a, BAD_REACTION);
    giq_option(4, NAME, 130, Node013, BAD_REACTION);
end

procedure Node006a
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node008();
end

procedure Node007
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (2 > global_var(GVAR_DEN_VIC_KNOWN)) then begin
        set_global_var(GVAR_DEN_VIC_KNOWN, 2);
    end
    if (global_var(GVAR_FIND_VIC) == 0) then begin
        set_global_var(GVAR_FIND_VIC, 1);
    end
    Reply(131);
    giq_option(4, NAME, 133, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 134, Node016, NEUTRAL_REACTION);
end

procedure Node008
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    Reply(135);
    giq_option(4, NAME, 136, Node999, NEUTRAL_REACTION);
end

procedure Node009
begin
    if (local_var(10) == 0) then begin
        set_local_var(10, local_var(10) + 1);
        Reply(137);
    end
    else begin
        Reply(138);
    end
    giq_option(4, NAME, 139, Node010, NEUTRAL_REACTION);
    if (local_var(7)) then begin
        giq_option(4, NAME, 140, Node011, NEUTRAL_REACTION);
        giq_option(4, NAME, 141, Node012, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 142, Node999, NEUTRAL_REACTION);
end

procedure Node010
begin
    Reply(143);
    giq_option(4, NAME, 144, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 145, Node016, NEUTRAL_REACTION);
end

procedure Node011
begin
    if (town_known(2) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 2 + ")");
        mark_area_known(MARK_TYPE_TOWN, 2, MARK_STATE_KNOWN);
    end
    Reply(146);
    giq_option(4, NAME, 147, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 148, Node016, NEUTRAL_REACTION);
end

procedure Node012
begin
    Reply(149);
    giq_option(4, NAME, 150, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 151, Node016, NEUTRAL_REACTION);
end

procedure Node013
begin
    set_local_var(3, local_var(3) + -20);
    set_local_var(0, local_var(0) + -20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    Reply(152);
    giq_option(4, NAME, 153, Node999, BAD_REACTION);
    giq_option(4, NAME, 154, Node015, NEUTRAL_REACTION);
end

procedure Node014
begin
    float_msg(self_obj, mstr(random(155, 158)), FLOAT_MSG_YELLOW);
end

procedure Node015
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    LVar1 := item_caps_total(self_obj);
    item_caps_adjust(self_obj, -LVar1);
    item_caps_adjust(dude_obj, LVar1);
    LVar0 := create_object(267, 0, 0);
    add_mult_objs_to_inven(dude_obj, LVar0, 1);
    if (global_var(GVAR_FIND_VIC) == 0) then begin
        set_global_var(GVAR_FIND_VIC, 1);
    end
    set_local_var(7, 1);
    Reply(159);
    if (2 > global_var(GVAR_DEN_VIC_KNOWN)) then begin
        set_global_var(GVAR_DEN_VIC_KNOWN, 2);
    end
    giq_option(4, NAME, 160, Node007, BAD_REACTION);
    giq_option(4, NAME, 161, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 162, Node016, NEUTRAL_REACTION);
end

procedure Node016
begin
    if (2 > global_var(GVAR_DEN_VIC_KNOWN)) then begin
        set_global_var(GVAR_DEN_VIC_KNOWN, 2);
    end
    if (global_var(GVAR_FIND_VIC) == 0) then begin
        set_global_var(GVAR_FIND_VIC, 1);
    end
    gsay_message(NAME, 163, NEUTRAL_REACTION);
end

procedure Node017
begin
    Reply(164);
    giq_option(-3, NAME, 165, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 166, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 167, Node999, GOOD_REACTION);
    giq_option(4, NAME, 168, Node003, BAD_REACTION);
end

procedure Node018
begin
    Reply(169);
    giq_option(-3, NAME, 170, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 171, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 172, Node999, GOOD_REACTION);
    giq_option(4, NAME, 173, Node003, BAD_REACTION);
end

procedure Node019
begin
    Reply(174);
    giq_option(-3, NAME, 175, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 176, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 177, Node999, GOOD_REACTION);
    giq_option(4, NAME, 178, Node003, BAD_REACTION);
end

procedure Node020
begin
    Reply(179);
    giq_option(-3, NAME, 180, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 181, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 182, Node999, GOOD_REACTION);
    giq_option(4, NAME, 183, Node003, BAD_REACTION);
end

procedure Enc001
begin
    Reply(200);
    giq_option(-3, NAME, 201, Enc003, NEUTRAL_REACTION);
    giq_option(4, NAME, 202, Enc004, NEUTRAL_REACTION);
    giq_option(4, NAME, 203, Enc005, NEUTRAL_REACTION);
end

procedure Enc002
begin
    Reply(204);
    giq_option(-3, NAME, 205, Enc001, NEUTRAL_REACTION);
    giq_option(4, NAME, 206, Enc001, NEUTRAL_REACTION);
    giq_option(4, NAME, 207, Enc008, BAD_REACTION);
end

procedure Enc003
begin
    Reply(208);
    giq_option(-3, NAME, 209, Node999, NEUTRAL_REACTION);
end

procedure Enc004
begin
    Reply(210);
    giq_option(4, NAME, 211, Enc006, NEUTRAL_REACTION);
end

procedure Enc005
begin
    Reply(212);
    giq_option(4, NAME, 213, Enc005a, NEUTRAL_REACTION);
end

procedure Enc005a
begin
    Reply(214);
    giq_option(4, NAME, 215, Enc013, NEUTRAL_REACTION);
    giq_option(4, NAME, 216, Enc007, NEUTRAL_REACTION);
    giq_option(4, NAME, 217, Enc007, NEUTRAL_REACTION);
end

procedure Enc006
begin
    Reply(218);
    giq_option(4, NAME, 219, Enc005, NEUTRAL_REACTION);
    giq_option(4, NAME, 220, Enc007, NEUTRAL_REACTION);
end

procedure Enc007
begin
    Reply(221);
    giq_option(4, NAME, 222, Node999, NEUTRAL_REACTION);
end

procedure Enc008
begin
    Reply(223);
    giq_option(4, NAME, 224, Enc005, NEUTRAL_REACTION);
    giq_option(4, NAME, 225, Enc008a, BAD_REACTION);
end

procedure Enc008a
begin
    set_local_var(3, local_var(3) + -20);
    set_local_var(0, local_var(0) + -20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure Enc009
begin
    gsay_message(NAME, 226, NEUTRAL_REACTION);
end

procedure Enc010
begin
    Reply(227);
    giq_option(-3, NAME, 228, Enc011, NEUTRAL_REACTION);
    giq_option(4, NAME, 229, Enc012, NEUTRAL_REACTION);
    giq_option(4, NAME, 230, Node999, NEUTRAL_REACTION);
end

procedure Enc011
begin
    gsay_message(NAME, 231, NEUTRAL_REACTION);
end

procedure Enc012
begin
    Reply(232);
    giq_option(4, NAME, 233, Node999, NEUTRAL_REACTION);
end

procedure Enc013
begin
    Reply(234);
    giq_option(4, NAME, 235, Enc013a, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Enc013a, NEUTRAL_REACTION);
end

procedure Enc013a
begin
    Reply(237);
    giq_option(4, NAME, 238, Enc007, NEUTRAL_REACTION);
    giq_option(4, NAME, 239, Enc004, NEUTRAL_REACTION);
end
