procedure start;


procedure start
begin
    if (script_action == spatial_proc) then begin
        if (obj_type(source_obj) == dude_obj) then begin
            if (local_var(4) == 0) then begin
                if (dude_iq > 6) then begin
                    display_msg(message_str(SCRIPT_GSTCAV1, 100));
                end
                else begin
                    display_msg(message_str(SCRIPT_GSTCAV1, 101));
                end
                set_local_var(4, 1);
            end
        end
    end
end
