procedure start;
procedure do_dialogue;
procedure social_skills;
procedure dane00;
procedure dane01;
procedure dane02;
procedure dane03;
procedure dane04;
procedure dane05;
procedure dane06;
procedure dane07;
procedure dane08;
procedure dane09;
procedure dane10;
procedure dane11;
procedure dane12;
procedure dane13;
procedure dane14;
procedure dane15;
procedure dane16;
procedure dane17;
procedure dane18;
procedure dane19;
procedure dane20;
procedure dane21;
procedure dane22;
procedure dane23;
procedure dane24;
procedure danemore;
procedure danereturn;

variable hostile;
variable Only_Once := 1;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;


procedure start
begin
    if (Only_Once) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 20);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PARTY_MACRAE_AGGRESSIVE);
        Only_Once := 0;
    end
    if (script_action == talk_proc) then begin
        call do_dialogue();
    end
    else begin
        if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
            script_overrides;
            display_msg(message_str(SCRIPT_ECMUTPAT, 100));
        end
        else begin
            if (script_action == pickup_proc) then begin
                hostile := 1;
            end
            else begin
                if (script_action == destroy_proc) then begin
                    if (source_obj == dude_obj) then begin
                        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
                            set_global_var(GVAR_SIERRA_LOCKOUT, 1);
                            set_global_var(GVAR_SIERRA_PASSWORD, 0);
                        end
                        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
                            set_global_var(GVAR_SIERRA_PASSWORD, 1);
                            set_global_var(GVAR_SIERRA_LOCKOUT, 0);
                        end
                        set_global_var(GVAR_GECKO_SKEETER_PART, global_var(GVAR_GECKO_SKEETER_PART) + 1);
                        if ((global_var(GVAR_GECKO_SKEETER_PART) % 6) == 0) then begin
                            set_global_var(GVAR_BRAIN_BOT_BRAIN, global_var(GVAR_BRAIN_BOT_BRAIN) + 1);
                        end
                    end
                end
                else begin
                    if (script_action == critter_proc) then begin
                        if (hostile) then begin
                            hostile := 0;
                            attack(dude_obj);
                        end
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    call get_reaction();
    start_dialogue(self_obj, 4);
    gsay_start;
    if (local_var(6) == 0) then begin
        call dane00();
    end
    else begin
        if (local_var(7) == 0) then begin
            call dane01();
        end
        else begin
            if (local_var(8) == 0) then begin
                call dane02();
            end
            else begin
                if (local_var(9) == 0) then begin
                    call dane03();
                end
                else begin
                    if (local_var(10) == 0) then begin
                        call dane04();
                    end
                    else begin
                        if (local_var(11) == 0) then begin
                            call dane05();
                        end
                        else begin
                            if (local_var(12) == 0) then begin
                                call dane06();
                            end
                            else begin
                                if (local_var(13) == 0) then begin
                                    call dane07();
                                end
                                else begin
                                    if (local_var(14) == 0) then begin
                                        call dane08();
                                    end
                                    else begin
                                        if (local_var(15) == 0) then begin
                                            call dane09();
                                        end
                                        else begin
                                            if (local_var(16) == 0) then begin
                                                call dane10();
                                            end
                                            else begin
                                                if (local_var(17) == 0) then begin
                                                    call dane11();
                                                end
                                                else begin
                                                    if (local_var(18) == 0) then begin
                                                        call dane12();
                                                    end
                                                    else begin
                                                        if (local_var(19) == 0) then begin
                                                            call dane13();
                                                        end
                                                        else begin
                                                            if (local_var(20) == 0) then begin
                                                                call dane14();
                                                            end
                                                            else begin
                                                                if (local_var(21) == 0) then begin
                                                                    call dane15();
                                                                end
                                                                else begin
                                                                    if (local_var(22) == 0) then begin
                                                                        call dane16();
                                                                    end
                                                                    else begin
                                                                        if (local_var(23) == 0) then begin
                                                                            call dane17();
                                                                        end
                                                                        else begin
                                                                            if (local_var(24) == 0) then begin
                                                                                call dane18();
                                                                            end
                                                                            else begin
                                                                                if (local_var(25) == 0) then begin
                                                                                    call dane19();
                                                                                end
                                                                                else begin
                                                                                    if (local_var(26) == 0) then begin
                                                                                        call dane20();
                                                                                    end
                                                                                    else begin
                                                                                        if (local_var(5) == 1) then begin
                                                                                            call dane24();
                                                                                        end
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    gsay_end;
    end_dialogue;
end

procedure social_skills
begin
    script_overrides;
    call get_reaction();
    call do_dialogue();
end

procedure dane00
begin
    set_local_var(6, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 101);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 102);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 103, NEUTRAL_REACTION);
end

procedure dane01
begin
    set_local_var(7, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 104);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 105);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 106, NEUTRAL_REACTION);
end

procedure dane02
begin
    set_local_var(8, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 107);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 108);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 109);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 110, NEUTRAL_REACTION);
end

procedure dane03
begin
    set_local_var(9, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 111);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 112);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 113, NEUTRAL_REACTION);
end

procedure dane04
begin
    set_local_var(10, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 114);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 115);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 116);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 117, NEUTRAL_REACTION);
end

procedure dane05
begin
    set_local_var(11, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 118);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 119);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 120, NEUTRAL_REACTION);
end

procedure dane06
begin
    set_local_var(12, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 121);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 122);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 123);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 124, NEUTRAL_REACTION);
end

procedure dane07
begin
    set_local_var(13, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 125);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 126);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 127, NEUTRAL_REACTION);
end

procedure dane08
begin
    set_local_var(14, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 128);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 129);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 130);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 131, NEUTRAL_REACTION);
end

procedure dane09
begin
    set_local_var(15, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 132);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 133);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 134);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 135, NEUTRAL_REACTION);
end

procedure dane10
begin
    set_local_var(16, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 136);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 137);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 138, NEUTRAL_REACTION);
end

procedure dane11
begin
    set_local_var(17, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 139);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 140);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 141);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 142, NEUTRAL_REACTION);
end

procedure dane12
begin
    set_local_var(18, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 143);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 144);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 145);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 146, NEUTRAL_REACTION);
end

procedure dane13
begin
    set_local_var(19, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 147);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 148);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 149);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 150);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 151, NEUTRAL_REACTION);
end

procedure dane14
begin
    set_local_var(20, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 152);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 153);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 154);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 155, NEUTRAL_REACTION);
end

procedure dane15
begin
    set_local_var(21, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 156);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 157);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 158, NEUTRAL_REACTION);
end

procedure dane16
begin
    gsay_reply(SCRIPT_ECMUTPAT, 159);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 160);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 161);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 162);
    giq_option(7, SCRIPT_ECMUTPAT, 163, dane17, NEUTRAL_REACTION);
    giq_option(7, SCRIPT_ECMUTPAT, 164, dane18, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_ECMUTPAT, 165, dane19, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_ECMUTPAT, 166, dane20, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_ECMUTPAT, 167, dane21, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_ECMUTPAT, 168, dane22, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_ECMUTPAT, 169, dane23, NEUTRAL_REACTION);
end

procedure dane17
begin
    gsay_reply(SCRIPT_ECMUTPAT, 170);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 171);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 172);
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
        gsay_reply(SCRIPT_ECMUTPAT, 173);
        giq_option(7, SCRIPT_ECMUTPAT, 174, dane18, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 175, dane19, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 176, dane20, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 177, dane21, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 178, dane22, NEUTRAL_REACTION);
    end
    else begin
        call danemore();
        gsay_message(SCRIPT_ECMUTPAT, 179, NEUTRAL_REACTION);
    end
end

procedure dane18
begin
    gsay_reply(SCRIPT_ECMUTPAT, 180);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 181);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 182);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 183);
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
        gsay_reply(SCRIPT_ECMUTPAT, 184);
        giq_option(7, SCRIPT_ECMUTPAT, 185, dane18, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 186, dane19, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 187, dane20, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 188, dane21, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 189, dane22, NEUTRAL_REACTION);
    end
    else begin
        call danemore();
        gsay_message(SCRIPT_ECMUTPAT, 190, NEUTRAL_REACTION);
    end
end

procedure dane19
begin
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
        gsay_reply(SCRIPT_ECMUTPAT, 191);
        giq_option(7, SCRIPT_ECMUTPAT, 192, dane18, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 193, dane19, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 194, dane20, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 195, dane21, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 196, dane22, NEUTRAL_REACTION);
    end
    else begin
        gsay_message(SCRIPT_ECMUTPAT, 197, NEUTRAL_REACTION);
    end
end

procedure dane20
begin
    gsay_reply(SCRIPT_ECMUTPAT, 198);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 199);
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
        giq_option(7, SCRIPT_ECMUTPAT, 200, dane19, NEUTRAL_REACTION);
        giq_option(7, SCRIPT_ECMUTPAT, 201, dane18, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 202, dane19, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 203, dane21, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 204, dane22, NEUTRAL_REACTION);
        giq_option(-3, SCRIPT_ECMUTPAT, 205, dane23, NEUTRAL_REACTION);
    end
    else begin
        call danemore();
        gsay_message(SCRIPT_ECMUTPAT, 206, NEUTRAL_REACTION);
    end
end

procedure dane21
begin
    gsay_reply(SCRIPT_ECMUTPAT, 207);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 208);
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
        giq_option(7, SCRIPT_ECMUTPAT, 209, dane19, NEUTRAL_REACTION);
        giq_option(7, SCRIPT_ECMUTPAT, 210, dane18, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 211, dane19, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 212, dane20, NEUTRAL_REACTION);
        giq_option(4, SCRIPT_ECMUTPAT, 213, dane22, NEUTRAL_REACTION);
        giq_option(-3, SCRIPT_ECMUTPAT, 214, dane23, NEUTRAL_REACTION);
    end
    else begin
        call danemore();
        gsay_message(SCRIPT_ECMUTPAT, 215, NEUTRAL_REACTION);
    end
end

procedure dane22
begin
    set_local_var(5, 1);
    gsay_reply(SCRIPT_ECMUTPAT, 216);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 217);
    call danemore();
    gsay_reply(SCRIPT_ECMUTPAT, 218);
    call danemore();
    gsay_message(SCRIPT_ECMUTPAT, 219, NEUTRAL_REACTION);
end

procedure dane23
begin
    set_local_var(5, 1);
    gsay_message(SCRIPT_ECMUTPAT, 220, NEUTRAL_REACTION);
end

procedure dane24
begin
    gsay_message(SCRIPT_ECMUTPAT, 221, NEUTRAL_REACTION);
end

procedure danemore
begin
    giq_option(1, SCRIPT_ECMUTPAT, 222, danereturn, NEUTRAL_REACTION);
end

procedure danereturn
begin
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_BRAIN_BOT_BRAIN) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        if (global_var(GVAR_GECKO_ECON_DISK) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_BSCOMP3, random(100, 105));
end
