variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;
variable caught_thief;
variable the_follow_obj;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;

import variable den_mom_box_obj;
import variable generic_temp_box;

procedure Node990;
procedure Node989;
procedure Node987;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(4) bwand 2) != 0) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack(dude_obj);
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure talk_p_proc
begin
    if ((global_var(GVAR_DEN_SMITTY_DELIVER) == 1) and (((game_time > global_var(GVAR_SMITTY_DELIVER_TIME)) and (global_var(GVAR_SMITTY_DELIVER_TIME) != 0)) == 0)) then begin
        call Node019();
    end
    else begin
        move_obj_inven_to_obj(self_obj, generic_temp_box);
        move_obj_inven_to_obj(den_mom_box_obj, self_obj);
        start_gdialog(55, self_obj, 4, -1, -1);
        gsay_start;
        if (dude_is_stupid) then begin
            call Node001();
        end
        else begin
            if (global_var(GVAR_DEN_SMITTY_DELIVER) == 3) then begin
                call Node020();
            end
            else begin
                call Node013();
            end
        end
        gsay_end;
        end_dialogue;
        move_obj_inven_to_obj(self_obj, den_mom_box_obj);
        move_obj_inven_to_obj(generic_temp_box, self_obj);
        set_local_var(4, local_var(4) bwor 1);
    end
end

procedure destroy_p_proc
begin
    if (((global_var(GVAR_DEN_FLAG_1) bwand 64) != 0) == 0) then begin
        set_global_var(GVAR_TOWN_REP_THE_DEN, global_var(GVAR_TOWN_REP_THE_DEN) + 1);
        if ((tile_contains_pid_obj(26686, 0, 33555587) == 0) and (tile_contains_pid_obj(26686, 0, 33555588) == 0)) then begin
            global_temp := create_object_sid(33555587, 0, 0, SCRIPT_ZICLOSED);
            set_obj_visibility(global_temp, 1);
            move_to(global_temp, 26686, 0);
        end
        debug_msg("created out of business @ tile == " + 26686 + " / elevation == " + 0);
    end
    set_global_var(GVAR_DEN_FLAG_1, global_var(GVAR_DEN_FLAG_1) bwor 64);
    move_obj_inven_to_obj(den_mom_box_obj, self_obj);
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - -15);
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(151 - ((local_var(4) bwand 1) != 0));
    set_local_var(4, local_var(4) bwor 4);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 524288);
        set_local_var(4, local_var(4) bwor 8);
        set_local_var(4, local_var(4) bwor 2);
    end
end

procedure map_enter_p_proc
begin
    if (is_loading_game == 0) then begin
        if (map_first_run) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 9);
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS);
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 0) then begin
        if (combat_is_initialized == 0) then begin
        end
    end
end

procedure Node998
begin
    set_local_var(4, local_var(4) bwor 2);
end

procedure Node999
begin
end

procedure Node001
begin
    Reply(200 + ((local_var(4) bwand 1) != 0));
    giq_option(1, NAME, mstr(202) + dude_name, Node002, NEUTRAL_REACTION);
    giq_option(1, NAME, 203, Node999, NEUTRAL_REACTION);
end

procedure Node002
begin
    if ((game_time >= local_var(5)) and (local_var(5) != 0)) then begin
        Reply(220);
        giq_option(1, NAME, 223, Node999, GOOD_REACTION);
    end
    else begin
        Reply(mstr(221) + dude_name + mstr(222));
        giq_option(1, NAME, 224, Node003, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 225, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    Reply(240);
    giq_option(1, NAME, 241, Node990, GOOD_REACTION);
    giq_option(1, NAME, 242, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    Reply(250 + ((local_var(4) bwand 512) != 0));
    set_local_var(4, local_var(4) bwor 512);
    giq_option(4, NAME, 252, Node005, NEUTRAL_REACTION);
    giq_option(4, NAME, 253, Node006, NEUTRAL_REACTION);
    giq_option(4, NAME, 254, Node006, NEUTRAL_REACTION);
end

procedure Node005
begin
    Reply(270);
    giq_option(4, NAME, 271, Node006, NEUTRAL_REACTION);
end

procedure Node006
begin
    Reply(280);
    if (item_caps_total(dude_obj) < 10) then begin
        giq_option(4, NAME, 281, Node013, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 282, Node989, GOOD_REACTION);
        giq_option(4, NAME, 283, Node989, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 284, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 285, Node999, NEUTRAL_REACTION);
end

procedure Node007
begin
    Reply(300);
    giq_option(4, NAME, 301, Node004, GOOD_REACTION);
    giq_option(4, NAME, 302, Node013, GOOD_REACTION);
    giq_option(4, NAME, 303, Node999, GOOD_REACTION);
end

procedure Node008
begin
    Reply(320);
    giq_option(4, NAME, 321, Node012, GOOD_REACTION);
    giq_option(4, NAME, 322, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 323, Node999, BAD_REACTION);
end

procedure Node009
begin
    Reply(random(340, 358));
    giq_option(1, NAME, 360, Node004, GOOD_REACTION);
end

procedure Node010
begin
    Reply(375);
    giq_option(1, NAME, 376, Node989, GOOD_REACTION);
end

procedure Node011
begin
    Reply(385);
    giq_option(1, NAME, 386, Node999, GOOD_REACTION);
end

procedure Node012
begin
    if (1 == 3) then begin
        if (global_var(GVAR_DEN_SMITTY_DELIVER) < 3) then begin
            display_msg(message_str(SCRIPT_DENBUS1, 1200));
            give_exp_points(150);
            display_msg(g_mstr(100) + 150 + g_mstr(101));
            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 10);
            debug_msg("Player gains " + 10 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (1 == 1) then begin
            if (global_var(GVAR_SMITTY_DELIVER_TIME) == 0) then begin
                set_global_var(GVAR_SMITTY_DELIVER_TIME, game_time + (24 * (60 * (60 * 10))));
            end
        end
    end
    if (global_var(GVAR_DEN_SMITTY_DELIVER) < 1) then begin
        set_global_var(GVAR_DEN_SMITTY_DELIVER, 1);
    end
    restock_obj := create_object(468, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    Reply(395);
    giq_option(4, NAME, 396, Node999, GOOD_REACTION);
end

procedure Node013
begin
    if ((global_var(GVAR_DEN_SMITTY_DELIVER) == 2) or ((global_var(GVAR_DEN_SMITTY_DELIVER) == 1) and ((game_time > global_var(GVAR_SMITTY_DELIVER_TIME)) and (global_var(GVAR_SMITTY_DELIVER_TIME) != 0)))) then begin
        if (2 == 3) then begin
            if (global_var(GVAR_DEN_SMITTY_DELIVER) < 3) then begin
                display_msg(message_str(SCRIPT_DENBUS1, 1200));
                give_exp_points(150);
                display_msg(g_mstr(100) + 150 + g_mstr(101));
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 10);
                debug_msg("Player gains " + 10 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        else begin
            if (2 == 1) then begin
                if (global_var(GVAR_SMITTY_DELIVER_TIME) == 0) then begin
                    set_global_var(GVAR_SMITTY_DELIVER_TIME, game_time + (24 * (60 * (60 * 10))));
                end
            end
        end
        if (global_var(GVAR_DEN_SMITTY_DELIVER) < 2) then begin
            set_global_var(GVAR_DEN_SMITTY_DELIVER, 2);
        end
        Reply(405);
    end
    else begin
        Reply(406 + ((local_var(4) bwand 1) != 0));
    end
    giq_option(4, NAME, 408, Node014, NEUTRAL_REACTION);
    if ((global_var(GVAR_DEN_ANNA_LOCKET_PIP) == 2) == 0) then begin
        if (((global_var(GVAR_DEN_FLAG_3) bwand 2) != 0) and (((global_var(GVAR_DEN_FLAG_1) bwand --2147483648) != 0) == 0)) then begin
            giq_option(4, NAME, 600, Node021, NEUTRAL_REACTION);
        end
    end
    if ((global_var(GVAR_DEN_VIC_KNOWN) == 2) and (((global_var(GVAR_DEN_FLAG_1) bwand 32) != 0) == 0) and (((global_var(GVAR_DEN_FLAG_1) bwand 524288) != 0) == 0) and (((global_var(GVAR_DEN_FLAG_1) bwand 134217728) != 0) == 0)) then begin
        giq_option(4, NAME, 409, Node016, NEUTRAL_REACTION);
    end
    if ((((global_var(GVAR_DEN_FLAG_2) bwand 262144) != 0) == 0) and (global_var(GVAR_DEN_SMITTY_DELIVER) == 0)) then begin
        giq_option(4, NAME, 410, Node008, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 411, Node009, NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(425);
    giq_option(4, NAME, 426, Node015, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(435);
    giq_option(4, NAME, 436, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 437, Node999, NEUTRAL_REACTION);
end

procedure Node016
begin
    if (town_known(4) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 4 + ")");
        mark_area_known(MARK_TYPE_TOWN, 4, MARK_STATE_KNOWN);
    end
    Reply(445);
    giq_option(4, NAME, 446, Node017, NEUTRAL_REACTION);
    giq_option(4, NAME, 447, Node999, NEUTRAL_REACTION);
end

procedure Node017
begin
    Reply(455);
    giq_option(4, NAME, 456, Node018, NEUTRAL_REACTION);
    giq_option(4, NAME, 457, Node999, GOOD_REACTION);
end

procedure Node018
begin
    Reply(465 + ((global_var(GVAR_DEN_FLAG_1) bwand 1) != 0));
    giq_option(4, NAME, 467, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 468, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    float_msg(self_obj, mstr(random(475, 479)), FLOAT_MSG_YELLOW);
end

procedure Node020
begin
    Reply(485);
    giq_option(4, NAME, 486, Node987, GOOD_REACTION);
    giq_option(4, NAME, 487, Node999, BAD_REACTION);
end

procedure Node021
begin
    Reply(500);
    giq_option(5, NAME, 501, Node022, NEUTRAL_REACTION);
    giq_option(4, NAME, 502, Node023, NEUTRAL_REACTION);
    giq_option(4, NAME, 503, Node999, NEUTRAL_REACTION);
end

procedure Node022
begin
    Reply(520);
    giq_option(4, NAME, 521, Node023, NEUTRAL_REACTION);
    giq_option(4, NAME, 522, Node999, NEUTRAL_REACTION);
end

procedure Node023
begin
    Reply(540);
    giq_option(4, NAME, 541, Node024, NEUTRAL_REACTION);
    giq_option(4, NAME, 542, Node999, NEUTRAL_REACTION);
end

procedure Node024
begin
    set_global_var(GVAR_DEN_FLAG_3, global_var(GVAR_DEN_FLAG_3) bwor 8192);
    debug_msg("set_mom_fingered_joey");
    Reply(560);
    giq_option(4, NAME, 561, Node025, NEUTRAL_REACTION);
    giq_option(4, NAME, 562, Node025, NEUTRAL_REACTION);
    giq_option(4, NAME, 563, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 564, Node999, NEUTRAL_REACTION);
end

procedure Node025
begin
    Reply(580);
    giq_option(4, NAME, 581, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 582, Node999, NEUTRAL_REACTION);
end

procedure Node990
begin
    if (item_caps_total(dude_obj) > 10) then begin
        item_caps_adjust(dude_obj, -5);
    end
    else begin
        if (item_caps_total(dude_obj) > 0) then begin
            item_caps_adjust(dude_obj, -1);
        end
    end
    call Node010();
end

procedure Node989
begin
    set_local_var(5, game_time + (24 * (60 * (60 * 10))));
    set_global_var(GVAR_BUST_SKEEVE, global_var(GVAR_BUST_SKEEVE) + 1);
    if (global_var(GVAR_BUST_SKEEVE) < 0) then begin
        set_global_var(GVAR_BUST_SKEEVE, 0);
    end
    else begin
        if (global_var(GVAR_BUST_SKEEVE) > (100 + (2 * (dude_endurance - 10)))) then begin
            set_global_var(GVAR_BUST_SKEEVE, 100 + (2 * (dude_endurance - 10)));
        end
    end
    gfade_out(10);
    game_time_advance(random(5, 20) * (60 * 10));
    critter_heal(dude_obj, random(2, 8));
    gfade_in(10);
    if (dude_is_stupid) then begin
        call Node011();
    end
    else begin
        item_caps_adjust(dude_obj, -10);
        call Node007();
    end
end

procedure Node987
begin
    set_local_var(5, game_time + (24 * (60 * (60 * 10))));
    set_global_var(GVAR_BUST_SKEEVE, global_var(GVAR_BUST_SKEEVE) + 1);
    if (global_var(GVAR_BUST_SKEEVE) < 0) then begin
        set_global_var(GVAR_BUST_SKEEVE, 0);
    end
    else begin
        if (global_var(GVAR_BUST_SKEEVE) > (100 + (2 * (dude_endurance - 10)))) then begin
            set_global_var(GVAR_BUST_SKEEVE, 100 + (2 * (dude_endurance - 10)));
        end
    end
    gfade_out(10);
    game_time_advance(random(15, 45) * (60 * 10));
    critter_heal(dude_obj, random(5, 20));
    if (4 == 3) then begin
        if (global_var(GVAR_DEN_SMITTY_DELIVER) < 3) then begin
            display_msg(message_str(SCRIPT_DENBUS1, 1200));
            give_exp_points(150);
            display_msg(g_mstr(100) + 150 + g_mstr(101));
            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 10);
            debug_msg("Player gains " + 10 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (4 == 1) then begin
            if (global_var(GVAR_SMITTY_DELIVER_TIME) == 0) then begin
                set_global_var(GVAR_SMITTY_DELIVER_TIME, game_time + (24 * (60 * (60 * 10))));
            end
        end
    end
    if (global_var(GVAR_DEN_SMITTY_DELIVER) < 4) then begin
        set_global_var(GVAR_DEN_SMITTY_DELIVER, 4);
    end
    gfade_in(10);
    call Node007();
end
