variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable caught_thief;
variable the_follow_obj;
variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure map_update_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure destroy_p_proc;
procedure use_obj_on_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure map_update_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 134217728);
    if ((global_var(GVAR_DEN_FLAG_2) bwand 268435456) != 0) then begin
        display_mstr(102);
    end
    else begin
        if (global_var(GVAR_QUEST_MAGGIE_STILL) == 1) then begin
            display_mstr(101);
        end
        else begin
            display_mstr(100);
        end
    end
end

procedure description_p_proc
begin
    script_overrides;
    set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 134217728);
    if ((global_var(GVAR_DEN_FLAG_2) bwand 268435456) != 0) then begin
        display_mstr(102);
    end
    else begin
        if ((global_var(GVAR_QUEST_MAGGIE_STILL) == 0) == 0) then begin
            display_mstr(101);
        end
        else begin
            display_mstr(100);
        end
    end
end

procedure damage_p_proc
begin
    if (((global_var(GVAR_DEN_FLAG_2) bwand 268435456) != 0) == 0) then begin
        gfade_out(10);
        if (global_var(GVAR_QUEST_MAGGIE_STILL) == 2) then begin
            if (3 > global_var(GVAR_QUEST_MAGGIE_STILL)) then begin
                set_global_var(GVAR_QUEST_MAGGIE_STILL, 3);
            end
            debug_msg("set_still_quest(" + 3 + ") == " + global_var(GVAR_QUEST_MAGGIE_STILL));
        end
        set_global_var(GVAR_DEN_FLAG_3, global_var(GVAR_DEN_FLAG_3) bwor 2048);
        set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 268435456);
        display_mstr(102);
        anim(self_obj, 1010, 1);
        gfade_in(10);
    end
end

procedure map_enter_p_proc
begin
    if ((global_var(GVAR_DEN_FLAG_2) bwand 268435456) != 0) then begin
        anim(self_obj, 1010, 1);
    end
    else begin
        anim(self_obj, 1010, 0);
    end
end

procedure destroy_p_proc
begin
end

procedure use_obj_on_p_proc
begin
    if ((obj_pid(obj_being_used_with) == 384) or (obj_pid(obj_being_used_with) == 20) or (obj_pid(obj_being_used_with) == 75)) then begin
        gfade_out(10);
        if (global_var(GVAR_QUEST_MAGGIE_STILL) == 2) then begin
            if (3 > global_var(GVAR_QUEST_MAGGIE_STILL)) then begin
                set_global_var(GVAR_QUEST_MAGGIE_STILL, 3);
            end
            debug_msg("set_still_quest(" + 3 + ") == " + global_var(GVAR_QUEST_MAGGIE_STILL));
        end
        set_global_var(GVAR_DEN_FLAG_3, global_var(GVAR_DEN_FLAG_3) bwor 2048);
        set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 268435456);
        display_mstr(102);
        anim(self_obj, 1010, 1);
        gfade_in(10);
    end
end
