variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure use_obj_on_p_proc;
procedure push_p_proc;
procedure combat_p_proc;
procedure Node1000;
procedure Node1001;
procedure Node1002;
procedure Node1003;
procedure Node1004;
procedure Node1005;
procedure Node1006;
procedure Node1100;
procedure Node998;
procedure Node999;

variable Only_Once;
variable doWalking;
variable add_party_check;
variable tmp_add;

procedure timed_event_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    variable LVar0 := 0;
    if (party_member_obj(16777600) != 0) then begin
        if (((local_var(9) != 0) == 0) and ((global_var(GVAR_PARTY_NO_FOLLOW) != 0) == 0)) then begin
            if (local_var(10) == 0) then begin
                set_local_var(10, 6);
            end
            if (tile_distance_objs(self_obj, dude_obj) > (3 * local_var(10) / 2)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    dest_tile := tile_num_in_direction(tile_num_in_direction(dude_tile, rotation_to_tile(dude_tile, tile_num(self_obj)), local_var(10)), random(0, 5), random(0, 2));
                    if (tile_distance_objs(self_obj, dude_obj) > (3 * local_var(10) / 2 * 2)) then begin
                        animate_move_obj_to_tile(self_obj, dest_tile, 1);
                    end
                    else begin
                        animate_move_obj_to_tile(self_obj, dest_tile, 0);
                    end
                end
                else begin
                    if (tile_distance(tile_num(self_obj), dude_tile) < tile_distance(tile_num(self_obj), dest_tile)) then begin
                        reg_anim_func(2, self_obj);
                    end
                end
            end
        end
        if ((dude_luck > (1 + has_trait(TRAIT_TRAIT, self_obj, TRAIT_gifted))) and (local_var(7) == 0)) then begin
            if ((local_var(7) < 10) and (local_var(7) != 0)) then begin
                set_local_var(7, local_var(7) + dude_luck - 1);
            end
            else begin
                set_local_var(7, dude_luck);
            end
            LVar0 := 1 - dude_luck;
            if (has_trait(TRAIT_TRAIT, self_obj, TRAIT_gifted)) then begin
                LVar0 := LVar0 + 1;
            end
            debug_msg("ECPARIA: luck adjust " + LVar0);
            set_critter_stat(dude_obj, STAT_lu, LVar0);
            debug_msg("ECPARIA: dude's luck wasn't 1: true value: " + local_var(7));
            debug_msg("ECPARIA: dude_luck: " + dude_luck);
        end
    end
    else begin
        if (add_party_check < game_time) then begin
            if (obj_can_see_obj(self_obj, dude_obj)) then begin
                if (not(is_success(do_check(dude_obj, 6, 0)))) then begin
                    debug_msg("ECPARIAH: added self to party");
                    tmp_add := 1;
                    display_mstr(103);
                    if (not(critter_state(self_obj) bwand 1)) then begin
                        if ((critter_state(self_obj) bwand 1) == 0) then begin
                            if (local_var(10) == 0) then begin
                                set_local_var(10, 6);
                            end
                            set_local_var(9, 0);
                            if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) != 0) then begin
                                set_local_var(11, has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM));
                            end
                            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
                            party_add(self_obj);
                        end
                        debug_msg("join party: " + self_name);
                        critter_add_trait(dude_obj, TRAIT_PERK, PERK_jinxed_perk, 1);
                    end
                end
                else begin
                    add_party_check := game_time + (10 * 10);
                end
            end
        end
        else begin
            if (doWalking < game_time) then begin
                reg_anim_func(2, self_obj);
                reg_anim_func(1, 1);
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_obj, random(0, 5), random(5, 10)), 0);
                reg_anim_func(3, 0);
                doWalking := game_time + (10 * random(1, 30));
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    add_party_check := game_time;
    set_local_var(4, 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - -15);
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    critter_add_trait(dude_obj, TRAIT_PERK, PERK_jinxed_perk, 0);
    if (local_var(7)) then begin
        debug_msg("ECPARIAH: setting luck back to : " + local_var(7));
        if (local_var(7) > 10) then begin
            set_local_var(7, 10);
        end
        set_critter_stat(dude_obj, STAT_lu, local_var(7) - (1 + has_trait(TRAIT_TRAIT, self_obj, TRAIT_gifted)));
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(102);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (not(anim_busy(self_obj))) then begin
            if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                    animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                    global_temp := (global_temp + 1) % 6;
                    while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                        debug_msg("flee loop: rot == " + global_temp);
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                    end
                end
            end
        end
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    if ((CUR_MAP_MODINN) or (CUR_MAP_V15ENT) or (CUR_MAP_V15ENTB)) then begin
        if ((elevation(self_obj) != dude_elevation) and (local_var(9) != 0)) then begin
            move_to(self_obj, tile_num(self_obj), dude_elevation);
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
    end
    else begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 80);
    end
end

procedure map_update_p_proc
begin
    if (combat_is_initialized == 0) then begin
        if (anim_busy(self_obj) == 0) then begin
            if (obj_in_party(self_obj)) then begin
                if (chem_use_level(self_obj) == 1) then begin
                    if ((100 * get_critter_stat(self_obj, STAT_current_hp) / get_critter_stat(self_obj, STAT_max_hp)) <= 60) then begin
                        global_temp := 1;
                        if (obj_is_carrying_obj_pid(self_obj, 144)) then begin
                            if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                gfade_out(600);
                                if (0 > 0) then begin
                                    game_time_advance(0);
                                end
                                gfade_in(600);
                            end
                            PartyHealingItem := obj_carrying_pid_obj(self_obj, 144);
                            use_obj_on_obj(PartyHealingItem, self_obj);
                            debug_msg(self_name + " used super stimpak.");
                        end
                        else begin
                            if (obj_is_carrying_obj_pid(self_obj, 40)) then begin
                                if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                    gfade_out(600);
                                    if (0 > 0) then begin
                                        game_time_advance(0);
                                    end
                                    gfade_in(600);
                                end
                                use_obj_on_obj(obj_carrying_pid_obj(self_obj, 40), self_obj);
                                debug_msg(self_name + " used stimpak.");
                            end
                            else begin
                                if (obj_is_carrying_obj_pid(self_obj, 273)) then begin
                                    if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                        gfade_out(600);
                                        if (0 > 0) then begin
                                            game_time_advance(0);
                                        end
                                        gfade_in(600);
                                    end
                                    use_obj_on_obj(obj_carrying_pid_obj(self_obj, 273), self_obj);
                                    debug_msg(self_name + " used healing powder.");
                                end
                                else begin
                                    if (obj_is_carrying_obj_pid(self_obj, 91)) then begin
                                        if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                            gfade_out(600);
                                            if (0 > 0) then begin
                                                game_time_advance(0);
                                            end
                                            gfade_in(600);
                                        end
                                        use_obj_on_obj(obj_carrying_pid_obj(self_obj, 91), self_obj);
                                        debug_msg(self_name + " used doctor's bag kit.");
                                    end
                                    else begin
                                        if (obj_is_carrying_obj_pid(self_obj, 47)) then begin
                                            if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                gfade_out(600);
                                                if (0 > 0) then begin
                                                    game_time_advance(0);
                                                end
                                                gfade_in(600);
                                            end
                                            use_obj_on_obj(obj_carrying_pid_obj(self_obj, 47), self_obj);
                                            debug_msg(self_name + " used First Aid kit.");
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                else begin
                    if (chem_use_level(self_obj) == 2) then begin
                        if ((100 * get_critter_stat(self_obj, STAT_current_hp) / get_critter_stat(self_obj, STAT_max_hp)) <= 30) then begin
                            global_temp := 1;
                            if (obj_is_carrying_obj_pid(self_obj, 144)) then begin
                                if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                    gfade_out(600);
                                    if (0 > 0) then begin
                                        game_time_advance(0);
                                    end
                                    gfade_in(600);
                                end
                                PartyHealingItem := obj_carrying_pid_obj(self_obj, 144);
                                use_obj_on_obj(PartyHealingItem, self_obj);
                                debug_msg(self_name + " used super stimpak.");
                            end
                            else begin
                                if (obj_is_carrying_obj_pid(self_obj, 40)) then begin
                                    if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                        gfade_out(600);
                                        if (0 > 0) then begin
                                            game_time_advance(0);
                                        end
                                        gfade_in(600);
                                    end
                                    use_obj_on_obj(obj_carrying_pid_obj(self_obj, 40), self_obj);
                                    debug_msg(self_name + " used stimpak.");
                                end
                                else begin
                                    if (obj_is_carrying_obj_pid(self_obj, 273)) then begin
                                        if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                            gfade_out(600);
                                            if (0 > 0) then begin
                                                game_time_advance(0);
                                            end
                                            gfade_in(600);
                                        end
                                        use_obj_on_obj(obj_carrying_pid_obj(self_obj, 273), self_obj);
                                        debug_msg(self_name + " used healing powder.");
                                    end
                                    else begin
                                        if (obj_is_carrying_obj_pid(self_obj, 91)) then begin
                                            if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                gfade_out(600);
                                                if (0 > 0) then begin
                                                    game_time_advance(0);
                                                end
                                                gfade_in(600);
                                            end
                                            use_obj_on_obj(obj_carrying_pid_obj(self_obj, 91), self_obj);
                                            debug_msg(self_name + " used doctor's bag kit.");
                                        end
                                        else begin
                                            if (obj_is_carrying_obj_pid(self_obj, 47)) then begin
                                                if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                    gfade_out(600);
                                                    if (0 > 0) then begin
                                                        game_time_advance(0);
                                                    end
                                                    gfade_in(600);
                                                end
                                                use_obj_on_obj(obj_carrying_pid_obj(self_obj, 47), self_obj);
                                                debug_msg(self_name + " used First Aid kit.");
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    else begin
                        if (chem_use_level(self_obj) == 3) then begin
                            if ((100 * get_critter_stat(self_obj, STAT_current_hp) / get_critter_stat(self_obj, STAT_max_hp)) <= 50) then begin
                                global_temp := 1;
                                if (obj_is_carrying_obj_pid(self_obj, 144)) then begin
                                    if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                        gfade_out(600);
                                        if (0 > 0) then begin
                                            game_time_advance(0);
                                        end
                                        gfade_in(600);
                                    end
                                    PartyHealingItem := obj_carrying_pid_obj(self_obj, 144);
                                    use_obj_on_obj(PartyHealingItem, self_obj);
                                    debug_msg(self_name + " used super stimpak.");
                                end
                                else begin
                                    if (obj_is_carrying_obj_pid(self_obj, 40)) then begin
                                        if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                            gfade_out(600);
                                            if (0 > 0) then begin
                                                game_time_advance(0);
                                            end
                                            gfade_in(600);
                                        end
                                        use_obj_on_obj(obj_carrying_pid_obj(self_obj, 40), self_obj);
                                        debug_msg(self_name + " used stimpak.");
                                    end
                                    else begin
                                        if (obj_is_carrying_obj_pid(self_obj, 273)) then begin
                                            if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                gfade_out(600);
                                                if (0 > 0) then begin
                                                    game_time_advance(0);
                                                end
                                                gfade_in(600);
                                            end
                                            use_obj_on_obj(obj_carrying_pid_obj(self_obj, 273), self_obj);
                                            debug_msg(self_name + " used healing powder.");
                                        end
                                        else begin
                                            if (obj_is_carrying_obj_pid(self_obj, 91)) then begin
                                                if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                    gfade_out(600);
                                                    if (0 > 0) then begin
                                                        game_time_advance(0);
                                                    end
                                                    gfade_in(600);
                                                end
                                                use_obj_on_obj(obj_carrying_pid_obj(self_obj, 91), self_obj);
                                                debug_msg(self_name + " used doctor's bag kit.");
                                            end
                                            else begin
                                                if (obj_is_carrying_obj_pid(self_obj, 47)) then begin
                                                    if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                        gfade_out(600);
                                                        if (0 > 0) then begin
                                                            game_time_advance(0);
                                                        end
                                                        gfade_in(600);
                                                    end
                                                    use_obj_on_obj(obj_carrying_pid_obj(self_obj, 47), self_obj);
                                                    debug_msg(self_name + " used First Aid kit.");
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                        else begin
                            if (chem_use_level(self_obj) == 4) then begin
                                if ((100 * get_critter_stat(self_obj, STAT_current_hp) / get_critter_stat(self_obj, STAT_max_hp)) <= 50) then begin
                                    global_temp := 1;
                                    if (obj_is_carrying_obj_pid(self_obj, 144)) then begin
                                        if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                            gfade_out(600);
                                            if (0 > 0) then begin
                                                game_time_advance(0);
                                            end
                                            gfade_in(600);
                                        end
                                        PartyHealingItem := obj_carrying_pid_obj(self_obj, 144);
                                        use_obj_on_obj(PartyHealingItem, self_obj);
                                        debug_msg(self_name + " used super stimpak.");
                                    end
                                    else begin
                                        if (obj_is_carrying_obj_pid(self_obj, 40)) then begin
                                            if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                gfade_out(600);
                                                if (0 > 0) then begin
                                                    game_time_advance(0);
                                                end
                                                gfade_in(600);
                                            end
                                            use_obj_on_obj(obj_carrying_pid_obj(self_obj, 40), self_obj);
                                            debug_msg(self_name + " used stimpak.");
                                        end
                                        else begin
                                            if (obj_is_carrying_obj_pid(self_obj, 273)) then begin
                                                if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                    gfade_out(600);
                                                    if (0 > 0) then begin
                                                        game_time_advance(0);
                                                    end
                                                    gfade_in(600);
                                                end
                                                use_obj_on_obj(obj_carrying_pid_obj(self_obj, 273), self_obj);
                                                debug_msg(self_name + " used healing powder.");
                                            end
                                            else begin
                                                if (obj_is_carrying_obj_pid(self_obj, 91)) then begin
                                                    if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                        gfade_out(600);
                                                        if (0 > 0) then begin
                                                            game_time_advance(0);
                                                        end
                                                        gfade_in(600);
                                                    end
                                                    use_obj_on_obj(obj_carrying_pid_obj(self_obj, 91), self_obj);
                                                    debug_msg(self_name + " used doctor's bag kit.");
                                                end
                                                else begin
                                                    if (obj_is_carrying_obj_pid(self_obj, 47)) then begin
                                                        if ((global_temp == 0) and (combat_is_initialized == 0)) then begin
                                                            gfade_out(600);
                                                            if (0 > 0) then begin
                                                                game_time_advance(0);
                                                            end
                                                            gfade_in(600);
                                                        end
                                                        use_obj_on_obj(obj_carrying_pid_obj(self_obj, 47), self_obj);
                                                        debug_msg(self_name + " used First Aid kit.");
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure use_obj_on_p_proc
begin
end

procedure push_p_proc
begin
end

procedure combat_p_proc
begin
    if (not(critter_is_fleeing(self_obj))) then begin
        critter_set_flee_state(self_obj, 1);
    end
end

procedure Node1000
begin
end

procedure Node1001
begin
end

procedure Node1002
begin
end

procedure Node1003
begin
end

procedure Node1004
begin
end

procedure Node1005
begin
end

procedure Node1006
begin
end

procedure Node1100
begin
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure timed_event_p_proc
begin
end
