procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure talk_p_proc;
procedure Scout0;
procedure Scout1;
procedure Scout2;
procedure Scout3;
procedure Scout4;
procedure Scout5;
procedure Scout6;
procedure Scout7;
procedure Scout8;
procedure Scout9;
procedure Scout10;
procedure Scout11;
procedure Scout12;
procedure Scout13;
procedure Scout14;
procedure Scout15;
procedure Scout16;
procedure Scout16a;
procedure Scout17;
procedure Scout18;
procedure Scout19;
procedure Scout20;
procedure Scout21;
procedure Scout22;
procedure Scout23;
procedure combat;
procedure ScoutEnd;
procedure flee_dude;

variable hostile;
variable initialized;

import variable removal_ptr;

procedure damage_p_proc;


procedure start
begin
    if (not(initialized)) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 46);
        if (global_var(GVAR_MODOC_JONNY_HOME) == 2) then begin
            if (random(0, 1)) then begin
                kill_critter(self_obj, 59);
            end
            else begin
                kill_critter(self_obj, 57);
            end
        end
        initialized := 1;
    end
    else begin
        if (script_action == critter_proc) then begin
            call critter_p_proc();
        end
        else begin
            if (script_action == destroy_proc) then begin
                call destroy_p_proc();
            end
            else begin
                if (script_action == look_at_proc) then begin
                    call look_at_p_proc();
                end
                else begin
                    if (script_action == talk_proc) then begin
                        call talk_p_proc();
                    end
                end
            end
        end
    end
end

procedure critter_p_proc
begin
    if (map_var(1) == 1) then begin
        animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_tile, random(0, 6), random(3, 7)), 0);
    end
    else begin
        if ((map_var(1) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
            hostile := 1;
        end
    end
    if (global_var(GVAR_MODOC_JONNY_HOME) == 2) then begin
        removal_ptr := self_obj;
    end
    if (hostile) then begin
        hostile := 0;
        attack(dude_obj);
    end
    else begin
        if (local_var(1) or global_var(GVAR_NCR_SNUFF_BISHOP)) then begin
            if (tile_distance_objs(self_obj, dude_obj) < 8) then begin
                call flee_dude();
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_NCR_SNUFF_BISHOP, 1);
    end
    if (source_obj == dude_obj) then begin
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
            set_global_var(GVAR_SIERRA_LOCKOUT, 1);
            set_global_var(GVAR_SIERRA_PASSWORD, 0);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
            set_global_var(GVAR_SIERRA_PASSWORD, 1);
            set_global_var(GVAR_SIERRA_LOCKOUT, 0);
        end
        set_global_var(GVAR_GECKO_REQ_FORM, global_var(GVAR_GECKO_REQ_FORM) + 1);
        if ((global_var(GVAR_GECKO_REQ_FORM) % 2) == 0) then begin
            set_global_var(GVAR_BRAIN_BOT_BRAIN, global_var(GVAR_BRAIN_BOT_BRAIN) - 1);
        end
    end
end

procedure look_at_p_proc
begin
    if (local_var(0) == 0) then begin
        if (self_gender == 0) then begin
            set_local_var(0, random(100, 104));
        end
        else begin
            set_local_var(0, random(105, 109));
        end
    end
    script_overrides;
    display_msg(message_str(SCRIPT_WTPLTRP1, local_var(0)));
end

procedure talk_p_proc
begin
    script_overrides;
    if (local_var(1) or global_var(GVAR_NCR_SNUFF_BISHOP)) then begin
        float_msg(self_obj, message_str(SCRIPT_VCMOORE, random(100, 105)), FLOAT_MSG_NORMAL);
    end
    else begin
        start_gdialog(263, self_obj, 4, -1, -1);
        gsay_start;
        if (global_var(GVAR_MUTATE_WHEN) == 1) then begin
            call Scout16();
        end
        else begin
            if (global_var(GVAR_MUTATE_WHEN) == 2) then begin
                call Scout22();
            end
            else begin
                call Scout0();
            end
        end
        gsay_end;
        end_dialogue;
    end
end

procedure Scout0
begin
    gsay_reply(SCRIPT_WTPLTRP1, 110);
    giq_option(-3, SCRIPT_WTPLTRP1, 111, Scout1, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 112) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_WTPLTRP1, 113), Scout4, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 114) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_WTPLTRP1, 115), combat, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 116, Scout11, NEUTRAL_REACTION);
end

procedure Scout1
begin
    gsay_reply(SCRIPT_WTPLTRP1, 117);
    giq_option(-3, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 118) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_WTPLTRP1, 119), combat, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 120) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_WTPLTRP1, 121), Scout2, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 122), combat, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_WTPLTRP1, message_str(SCRIPT_WTPLTRP1, 123) + proto_data(obj_pid(dude_obj), 1) + message_str(SCRIPT_WTPLTRP1, 124), Scout3, NEUTRAL_REACTION);
end

procedure Scout2
begin
    gsay_message(SCRIPT_WTPLTRP1, 125, NEUTRAL_REACTION);
end

procedure Scout3
begin
    gsay_message(SCRIPT_WTPLTRP1, 126, NEUTRAL_REACTION);
end

procedure Scout4
begin
    gsay_reply(SCRIPT_WTPLTRP1, 127);
    giq_option(4, SCRIPT_WTPLTRP1, 128, Scout5, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 129, combat, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 130, Scout6, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 131, Scout10, NEUTRAL_REACTION);
end

procedure Scout5
begin
    gsay_message(SCRIPT_WTPLTRP1, 132, NEUTRAL_REACTION);
end

procedure Scout6
begin
    gsay_reply(SCRIPT_WTPLTRP1, 133);
    giq_option(4, SCRIPT_WTPLTRP1, 134, Scout5, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 135, Scout7, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 136, Scout9, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 137, Scout8, NEUTRAL_REACTION);
end

procedure Scout7
begin
    gsay_reply(SCRIPT_WTPLTRP1, 138);
    giq_option(4, SCRIPT_WTPLTRP1, 139, Scout5, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 140, Scout8, NEUTRAL_REACTION);
end

procedure Scout8
begin
    gsay_message(SCRIPT_WTPLTRP1, 141, NEUTRAL_REACTION);
end

procedure Scout9
begin
    gsay_reply(SCRIPT_WTPLTRP1, 142);
    giq_option(4, SCRIPT_WTPLTRP1, 143, ScoutEnd, NEUTRAL_REACTION);
end

procedure Scout10
begin
    gsay_reply(SCRIPT_WTPLTRP1, 144);
    giq_option(4, SCRIPT_WTPLTRP1, 145, Scout5, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 146, Scout8, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 147, Scout6, NEUTRAL_REACTION);
end

procedure Scout11
begin
    gsay_reply(SCRIPT_WTPLTRP1, 148);
    giq_option(6, SCRIPT_WTPLTRP1, 149, ScoutEnd, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 150, Scout12, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 151, Scout15, NEUTRAL_REACTION);
end

procedure Scout12
begin
    gsay_reply(SCRIPT_WTPLTRP1, 152);
    giq_option(6, SCRIPT_WTPLTRP1, 153, ScoutEnd, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 154, Scout13, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 155, Scout14, NEUTRAL_REACTION);
end

procedure Scout13
begin
    gsay_reply(SCRIPT_WTPLTRP1, 156);
    giq_option(6, SCRIPT_WTPLTRP1, 157, ScoutEnd, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 158, combat, NEUTRAL_REACTION);
end

procedure Scout14
begin
    gsay_message(SCRIPT_WTPLTRP1, 159, NEUTRAL_REACTION);
end

procedure Scout15
begin
    gsay_reply(SCRIPT_WTPLTRP1, 160);
    giq_option(6, SCRIPT_WTPLTRP1, 161, ScoutEnd, NEUTRAL_REACTION);
end

procedure Scout16
begin
    gsay_reply(SCRIPT_WTPLTRP1, 162);
    giq_option(4, SCRIPT_WTPLTRP1, 163, Scout17, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 164, Scout19, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_WTPLTRP1, 165, Scout16a, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_WTPLTRP1, 111, Scout1, NEUTRAL_REACTION);
end

procedure Scout16a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, -10))) then begin
        call Scout20();
    end
    else begin
        call Scout21();
    end
end

procedure Scout17
begin
    gsay_reply(SCRIPT_WTPLTRP1, 166);
    giq_option(4, SCRIPT_WTPLTRP1, 167, Scout18, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 168, ScoutEnd, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WTPLTRP1, 169, combat, NEUTRAL_REACTION);
end

procedure Scout18
begin
    gsay_reply(SCRIPT_WTPLTRP1, 170);
    giq_option(4, SCRIPT_WTPLTRP1, 171, ScoutEnd, NEUTRAL_REACTION);
end

procedure Scout19
begin
    gsay_message(SCRIPT_WTPLTRP1, 172, NEUTRAL_REACTION);
    call combat();
end

procedure Scout20
begin
    gsay_message(SCRIPT_WTPLTRP1, 173, NEUTRAL_REACTION);
end

procedure Scout21
begin
    gsay_message(SCRIPT_WTPLTRP1, 174, NEUTRAL_REACTION);
    call combat();
end

procedure Scout22
begin
    gsay_reply(SCRIPT_WTPLTRP1, 175);
    giq_option(4, SCRIPT_WTPLTRP1, 176, ScoutEnd, NEUTRAL_REACTION);
    if (global_var(GVAR_MUTATE) == 0) then begin
        giq_option(4, SCRIPT_WTPLTRP1, 177, Scout23, NEUTRAL_REACTION);
    end
    giq_option(-3, SCRIPT_WTPLTRP1, 111, Scout1, NEUTRAL_REACTION);
end

procedure Scout23
begin
    variable LVar0 := 0;
    LVar0 := 4 * 3600;
    set_global_var(GVAR_MUTATE, 1);
    gsay_reply(SCRIPT_WTPLTRP1, 178);
    game_time_advance(game_ticks(LVar0));
    gfade_out(400);
    gfade_in(400);
    giq_option(4, SCRIPT_WTPLTRP1, 179, ScoutEnd, NEUTRAL_REACTION);
end

procedure combat
begin
    hostile := 1;
end

procedure ScoutEnd
begin
end

procedure flee_dude
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    while (LVar1 < 5) do begin
        if (tile_distance(dude_tile, tile_num_in_direction(tile_num(self_obj), LVar1, 3)) > LVar2) then begin
            LVar0 := tile_num_in_direction(tile_num(self_obj), LVar1, 3);
            LVar2 := tile_distance(dude_tile, LVar0);
        end
        LVar1 := LVar1 + 1;
    end
    animate_move_obj_to_tile(self_obj, LVar0, 1);
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(1, 1);
    end
end
