procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure talk_p_proc;
procedure Jason01;
procedure Jason02;
procedure Jason03;
procedure Jason04;
procedure Jason05;
procedure Jason06;
procedure Jason07;
procedure Jason08;
procedure Jason09;
procedure Jason10;
procedure Jason11;
procedure Jason12;
procedure Jason13;
procedure Jason14;
procedure Jason15;
procedure Jason16;
procedure Jason17;
procedure Jason18;
procedure Jason19;
procedure Jason20;
procedure Jason21;
procedure Jason22;
procedure Jason23;
procedure follow_player;

variable following;
variable initialized;


procedure start
begin
    if (not(initialized)) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 49);
        initialized := 1;
    end
    else begin
        if (script_action == critter_proc) then begin
            call critter_p_proc();
        end
        else begin
            if (script_action == destroy_proc) then begin
                call destroy_p_proc();
            end
            else begin
                if (script_action == look_at_proc) then begin
                    call look_at_p_proc();
                end
                else begin
                    if (script_action == talk_proc) then begin
                        call talk_p_proc();
                    end
                end
            end
        end
    end
end

procedure critter_p_proc
begin
    if (following) then begin
        call follow_player();
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
            set_global_var(GVAR_SIERRA_LOCKOUT, 1);
            set_global_var(GVAR_SIERRA_PASSWORD, 0);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
            set_global_var(GVAR_SIERRA_PASSWORD, 1);
            set_global_var(GVAR_SIERRA_LOCKOUT, 0);
        end
        set_global_var(GVAR_GECKO_REQ_FORM, global_var(GVAR_GECKO_REQ_FORM) + 1);
        if ((global_var(GVAR_GECKO_REQ_FORM) % 2) == 0) then begin
            set_global_var(GVAR_BRAIN_BOT_BRAIN, global_var(GVAR_BRAIN_BOT_BRAIN) - 1);
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (not(local_var(1))) then begin
        display_msg(message_str(SCRIPT_SIFFIELD, 101));
    end
    else begin
        display_msg(message_str(SCRIPT_SIFFIELD, 100));
    end
end

procedure talk_p_proc
begin
    start_gdialog(382, self_obj, 4, -1, -1);
    gsay_start;
    if (CUR_MAP_NCR4) then begin
        if (following) then begin
            call Jason23();
        end
        else begin
            call Jason19();
        end
    end
    if (local_var(0)) then begin
        call Jason18();
    end
    else begin
        if (local_var(1)) then begin
            call Jason16();
        end
        else begin
            call Jason01();
        end
    end
    gsay_end;
    end_dialogue;
end

procedure Jason01
begin
    gsay_reply(SCRIPT_SIFFIELD, 102);
    giq_option(4, SCRIPT_SIFFIELD, 103, Jason05, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 104, Jason13, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 105, Jason08, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 106, Jason07, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_SIFFIELD, 107, Jason02, NEUTRAL_REACTION);
end

procedure Jason02
begin
    gsay_message(SCRIPT_SIFFIELD, 108, NEUTRAL_REACTION);
end

procedure Jason03
begin
    gsay_message(SCRIPT_SIFFIELD, 109, NEUTRAL_REACTION);
    gsay_message(SCRIPT_SIFFIELD, 110, NEUTRAL_REACTION);
end

procedure Jason04
begin
    gsay_message(SCRIPT_SIFFIELD, 111, NEUTRAL_REACTION);
    gsay_message(SCRIPT_SIFFIELD, 112, NEUTRAL_REACTION);
end

procedure Jason05
begin
    gsay_reply(SCRIPT_SIFFIELD, 113);
    giq_option(4, SCRIPT_SIFFIELD, 114, Jason06, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 115, Jason14, NEUTRAL_REACTION);
end

procedure Jason06
begin
    gsay_reply(SCRIPT_SIFFIELD, 116);
    giq_option(4, SCRIPT_SIFFIELD, 117, Jason07, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 118, Jason08, NEUTRAL_REACTION);
    giq_option(6, SCRIPT_SIFFIELD, 119, Jason15, NEUTRAL_REACTION);
end

procedure Jason07
begin
    gsay_reply(SCRIPT_SIFFIELD, 120);
    giq_option(4, SCRIPT_SIFFIELD, 121, Jason12, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 122, Jason08, NEUTRAL_REACTION);
end

procedure Jason08
begin
    gsay_reply(SCRIPT_SIFFIELD, 123);
    giq_option(4, SCRIPT_SIFFIELD, 124, Jason12, NEUTRAL_REACTION);
end

procedure Jason09
begin
    gsay_reply(SCRIPT_SIFFIELD, 125);
    giq_option(4, SCRIPT_SIFFIELD, 126, Jason10, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 127, Jason11, NEUTRAL_REACTION);
end

procedure Jason10
begin
    gsay_message(SCRIPT_SIFFIELD, 128, NEUTRAL_REACTION);
end

procedure Jason11
begin
    gsay_message(SCRIPT_SIFFIELD, 129, NEUTRAL_REACTION);
end

procedure Jason12
begin
    gsay_message(SCRIPT_SIFFIELD, 130, NEUTRAL_REACTION);
end

procedure Jason13
begin
    gsay_message(SCRIPT_SIFFIELD, 131, NEUTRAL_REACTION);
    set_local_var(0, 1);
end

procedure Jason14
begin
    gsay_message(SCRIPT_SIFFIELD, 132, NEUTRAL_REACTION);
    call Jason10();
end

procedure Jason15
begin
    gsay_message(SCRIPT_SIFFIELD, 133, NEUTRAL_REACTION);
    call Jason11();
end

procedure Jason16
begin
    gsay_reply(SCRIPT_SIFFIELD, 134);
    giq_option(4, SCRIPT_SIFFIELD, 135, Jason08, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 136, Jason17, NEUTRAL_REACTION);
end

procedure Jason17
begin
    gsay_message(SCRIPT_SIFFIELD, 137, NEUTRAL_REACTION);
end

procedure Jason18
begin
    gsay_message(SCRIPT_SIFFIELD, 138, NEUTRAL_REACTION);
end

procedure Jason19
begin
    gsay_reply(SCRIPT_SIFFIELD, 139);
    giq_option(-3, SCRIPT_SIFFIELD, 140, Jason20, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 141, Jason20, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 142, Jason21, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 143, Jason22, NEUTRAL_REACTION);
end

procedure Jason20
begin
    gsay_message(SCRIPT_SIFFIELD, 144, NEUTRAL_REACTION);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
    following := 1;
end

procedure Jason21
begin
    gsay_message(SCRIPT_SIFFIELD, 145, NEUTRAL_REACTION);
end

procedure Jason22
begin
    gsay_reply(SCRIPT_SIFFIELD, 146);
    giq_option(4, SCRIPT_SIFFIELD, 147, Jason20, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_SIFFIELD, 148, Jason21, NEUTRAL_REACTION);
end

procedure Jason23
begin
    gsay_message(SCRIPT_SIFFIELD, 149, NEUTRAL_REACTION);
end

procedure follow_player
begin
    if (tile_distance_objs(self_obj, dude_obj) > 7) then begin
        animate_move_obj_to_tile(self_obj, dude_tile, 1);
    end
    else begin
        if (tile_distance_objs(self_obj, dude_obj) > 3) then begin
            animate_move_obj_to_tile(self_obj, dude_tile, 0);
        end
        else begin
            animate_move_obj_to_tile(self_obj, tile_num(self_obj), 0);
        end
    end
end
