variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure destroy_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure look_at_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure use_skill_on_p_proc
begin
end

procedure use_p_proc
begin
end

procedure damage_p_proc
begin
    variable LVar0 := 0;
    if (((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 1) != 0) == 0) then begin
        if (source_obj != 0) then begin
            debug_msg(" obj_pid(source_obj) == " + obj_pid(source_obj));
            if (weapon_dmg_type(source_obj) == 6) then begin
                LVar0 := 1;
            end
        end
        if (target_obj != 0) then begin
            debug_msg(" obj_pid(target_obj) == " + obj_pid(target_obj));
            if (weapon_dmg_type(target_obj) == 6) then begin
                LVar0 := 1;
            end
        end
        if (LVar0) then begin
            set_global_var(GVAR_MODOC_GENERIC_FLAG_1, global_var(GVAR_MODOC_GENERIC_FLAG_1) bwor 1);
            debug_msg("setting set_shitter_blown");
            if ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 16777216) != 0) then begin
                debug_msg("doing leaving_shitter");
                set_global_var(GVAR_MODOC_GENERIC_FLAG_1, global_var(GVAR_MODOC_GENERIC_FLAG_1) bwor 33554432);
                gfade_out(5);
                fade_out;
                if (obj_is_visible_flag(self_obj) == 1) then begin
                    set_obj_visibility(self_obj, 1);
                end
                if (local_var(0) == 0) then begin
                    set_local_var(0, 1);
                    display_mstr(200);
                    give_exp_points(500);
                    display_msg(g_mstr(100) + 500 + g_mstr(101));
                end
                fade_in;
            end
            else begin
                debug_msg("doing death_explostion");
                add_timer_event(self_obj, 0 * 6, 0);
                add_timer_event(self_obj, 1 * 6, 1);
                add_timer_event(self_obj, 2 * 6, 2);
                add_timer_event(self_obj, 3 * 6, 3);
                add_timer_event(self_obj, 4 * 6, 4);
                add_timer_event(self_obj, 5 * 6, 5);
                add_timer_event(self_obj, 6 * 6, 6);
                add_timer_event(self_obj, 7 * 6, 7);
            end
        end
    end
end

procedure map_enter_p_proc
begin
    if (is_loading_game == 0) then begin
        if ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 1) != 0) then begin
            if (500 != 0) then begin
                if (local_var(0) == 0) then begin
                    set_local_var(0, 1);
                    give_exp_points(500);
                    display_msg(g_mstr(100) + 500 + g_mstr(101));
                end
            end
            destroy_object(self_obj);
        end
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 0) then begin
    end
    else begin
        if (fixed_param == 1) then begin
            if (combat_is_initialized == 0) then begin
                terminate_combat;
            end
            explosion(20698, dude_elevation, 10000);
        end
        else begin
            if (fixed_param == 2) then begin
                if (combat_is_initialized == 0) then begin
                    terminate_combat;
                end
                explosion(20102, dude_elevation, 10000);
            end
            else begin
                if (fixed_param == 3) then begin
                    if (combat_is_initialized == 0) then begin
                        terminate_combat;
                    end
                    explosion(21495, dude_elevation, 10000);
                end
                else begin
                    if (fixed_param == 4) then begin
                        if (combat_is_initialized == 0) then begin
                            terminate_combat;
                        end
                        explosion(21298, dude_elevation, 10000);
                    end
                    else begin
                        if (fixed_param == 5) then begin
                            if (combat_is_initialized == 0) then begin
                                terminate_combat;
                            end
                            explosion(20303, dude_elevation, 10000);
                        end
                        else begin
                            if (fixed_param == 6) then begin
                                if (combat_is_initialized == 0) then begin
                                    terminate_combat;
                                end
                                explosion(21102, dude_elevation, 10000);
                            end
                            else begin
                                if (fixed_param == 7) then begin
                                    if (combat_is_initialized == 0) then begin
                                        terminate_combat;
                                    end
                                    explosion(dude_tile, dude_elevation, 10000);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
end
