procedure Start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure talk_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure Smitty01;
procedure Smitty02;
procedure Smitty03;
procedure Smitty04;
procedure Smitty05;
procedure Smitty06;
procedure Smitty07;
procedure Smitty08;
procedure Smitty09;
procedure Smitty10;
procedure Smitty11;
procedure Smitty12;
procedure Smitty14;
procedure Smitty14a;
procedure Smitty15;
procedure SmittyEnd;

variable Initialize := 1;
variable DisplayMessage := 100;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;


procedure Start
begin
    if (Initialize) then begin
        if (obj_is_carrying_obj_pid(self_obj, 41) == 0) then begin
            item_caps_adjust(self_obj, random(500, 750));
        end
        if ((global_var(GVAR_SPECIAL_ENCOUNTER_GUARDIAN) == 9103) or (global_var(GVAR_SPECIAL_ENCOUNTER_GUARDIAN) == 9102)) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
        end
        else begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 49);
        end
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BRAHMIN);
        Initialize := 0;
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(SCRIPT_WSFELD3B, 100));
    end
    else begin
        display_msg(message_str(SCRIPT_WSFELD3B, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(SCRIPT_WSFELD3B, 100));
    end
    else begin
        display_msg(message_str(SCRIPT_WSFELD3B, 101));
    end
end

procedure talk_p_proc
begin
    if (global_var(GVAR_SALVATORE_WARNINGS) == 1) then begin
        float_msg(self_obj, message_str(SCRIPT_VCMOORE, random(100, 105)), FLOAT_MSG_RED);
    end
    else begin
        if ((local_var(4) == 1) and (dude_iq < 4)) then begin
            float_msg(self_obj, message_str(SCRIPT_WSFELD3B, 117), FLOAT_MSG_NORMAL);
        end
        else begin
            if (local_var(5) == 2) then begin
                float_msg(self_obj, message_str(SCRIPT_WSFELD3B, 131), FLOAT_MSG_NORMAL);
            end
            else begin
                call get_reaction();
                start_gdialog(250, self_obj, -1, -1, -1);
                gsay_start;
                if (global_var(GVAR_VAULT_GET_LYNETTE_REWARD) == 9303) then begin
                    call Smitty11();
                end
                else begin
                    if (global_var(GVAR_VAULT_GET_LYNETTE_REWARD) == 9304) then begin
                        if (local_var(5) == 0) then begin
                            call Smitty12();
                        end
                        else begin
                            if (local_var(5) == 9307) then begin
                                if (obj_is_carrying_obj_pid(dude_obj, 15)) then begin
                                    call Smitty14();
                                end
                                else begin
                                    call Smitty15();
                                end
                            end
                        end
                    end
                    else begin
                        if (local_var(1) < 2) then begin
                            DisplayMessage := 103;
                            call Smitty01();
                        end
                        else begin
                            DisplayMessage := 102;
                            call Smitty01();
                        end
                    end
                end
                gsay_end;
                end_dialogue;
            end
        end
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_SALVATORE_WARNINGS, 1);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 49);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_SALVATORE_WARNINGS, 1);
        if (source_obj == dude_obj) then begin
            if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
                set_global_var(GVAR_SIERRA_LOCKOUT, 1);
                set_global_var(GVAR_SIERRA_PASSWORD, 0);
            end
            if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
                set_global_var(GVAR_SIERRA_PASSWORD, 1);
                set_global_var(GVAR_SIERRA_LOCKOUT, 0);
            end
            set_global_var(GVAR_GECKO_REQ_FORM, global_var(GVAR_GECKO_REQ_FORM) + 1);
            if ((global_var(GVAR_GECKO_REQ_FORM) % 2) == 0) then begin
                set_global_var(GVAR_BRAIN_BOT_BRAIN, global_var(GVAR_BRAIN_BOT_BRAIN) - 1);
            end
        end
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 49);
    end
end

procedure pickup_p_proc
begin
    set_global_var(GVAR_SALVATORE_WARNINGS, 1);
end

procedure Smitty01
begin
    gsay_reply(SCRIPT_WSFELD3B, DisplayMessage);
    DisplayMessage := 112;
    if (local_var(4) == 0) then begin
        giq_option(4, SCRIPT_WSFELD3B, 104, Smitty03, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_VAULT_GET_LYNETTE_REWARD) < 9303) and (global_var(GVAR_VAULT_GET_LYNETTE_REWARD) > 2)) then begin
        giq_option(4, SCRIPT_WSFELD3B, 105, Smitty10, NEUTRAL_REACTION);
    end
    giq_option(4, SCRIPT_WSFELD3B, 106, Smitty02, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WSFELD3B, 107, Smitty04, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_WSFELD3B, 108, Smitty06, NEUTRAL_REACTION);
    giq_option(-3, SCRIPT_WSFELD3B, 109, Smitty05, NEUTRAL_REACTION);
end

procedure Smitty02
begin
    DisplayMessage := 110;
    call Smitty01();
end

procedure Smitty03
begin
    set_local_var(4, 1);
    DisplayMessage := 111;
    call Smitty01();
end

procedure Smitty04
begin
    gsay_reply(SCRIPT_WSFELD3B, DisplayMessage);
    giq_option(1, SCRIPT_WSFELD3B, 113, Smitty07, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_WSFELD3B, 114, Smitty08, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_WSFELD3B, 115, Smitty09, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_WSFELD3B, 116, Smitty06, NEUTRAL_REACTION);
end

procedure Smitty05
begin
    set_local_var(4, 1);
    gsay_message(SCRIPT_WSFELD3B, 117, NEUTRAL_REACTION);
end

procedure Smitty06
begin
    gsay_message(SCRIPT_WSFELD3B, 118, NEUTRAL_REACTION);
end

procedure Smitty07
begin
    DisplayMessage := 119;
    call Smitty04();
end

procedure Smitty08
begin
    DisplayMessage := 120;
    call Smitty04();
end

procedure Smitty09
begin
    DisplayMessage := 121;
    call Smitty04();
end

procedure Smitty10
begin
    gsay_message(SCRIPT_WSFELD3B, 122, NEUTRAL_REACTION);
    gfade_out(600);
    game_time_advance(10 * 60 * 60);
    gfade_in(600);
    set_global_var(GVAR_VAULT_GET_LYNETTE_REWARD, 9303);
    gsay_message(SCRIPT_WSFELD3B, 123, NEUTRAL_REACTION);
end

procedure Smitty11
begin
    gsay_message(SCRIPT_WSFELD3B, 124, NEUTRAL_REACTION);
end

procedure Smitty12
begin
    gsay_message(SCRIPT_WSFELD3B, 125, NEUTRAL_REACTION);
    set_local_var(5, 9307);
    if (obj_is_carrying_obj_pid(dude_obj, 15)) then begin
        call Smitty14();
    end
end

procedure Smitty14
begin
    gsay_reply(SCRIPT_WSFELD3B, 127);
    giq_option(1, SCRIPT_WSFELD3B, 126, Smitty14a, NEUTRAL_REACTION);
end

procedure Smitty14a
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    gsay_message(SCRIPT_WSFELD3B, 128, NEUTRAL_REACTION);
    LVar1 := create_object(42, 0, 0);
    move_obj_inven_to_obj(dude_obj, LVar1);
    move_obj_inven_to_obj(LVar1, dude_obj);
    LVar0 := obj_carrying_pid_obj(dude_obj, 15);
    rm_obj_from_inven(dude_obj, LVar0);
    destroy_object(LVar0);
    destroy_object(LVar1);
    gfade_out(600);
    game_time_advance(10 * 60 * 60 * 2);
    gfade_in(600);
    gsay_message(SCRIPT_WSFELD3B, 129, NEUTRAL_REACTION);
    LVar0 := create_object(233, 0, 0);
    add_obj_to_inven(dude_obj, LVar0);
    set_local_var(5, 2);
end

procedure Smitty15
begin
    gsay_message(SCRIPT_WSFELD3B, 130, NEUTRAL_REACTION);
end

procedure SmittyEnd
begin
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_BRAIN_BOT_BRAIN) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        if (global_var(GVAR_GECKO_ECON_DISK) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_BSCOMP3, random(100, 105));
end
