variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure critter_p_proc;
procedure talk_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure timed_event_p_proc;
procedure RepairRequest;
procedure PickupRequest;
procedure RepairTravel;
procedure ReplaceBot;
procedure PrepareBot;
procedure Repair1;
procedure Repair2;
procedure Repair3;
procedure Repair4;
procedure Repair5;
procedure Repair6;
procedure Travel1;
procedure Travel2;
procedure Travel3;
procedure Travel4;
procedure Travel5;
procedure Travel6;
procedure FindElevator;
procedure GetMeHome;
procedure GetRobotHome;
procedure FindBotElevator;

variable Repair_Bot;
variable In_Timed_Event;
variable Elevator_Tile;
variable Tile1;
variable Bot;
variable Bot_Elevation;
variable Bot_Tile;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    if (local_var(9) == 0) then begin
        set_local_var(9, tile_num(self_obj));
    end
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 53);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_REPAIR_BOT);
end

procedure critter_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if ((local_var(1) == 0) and ((tile_num(self_obj) == local_var(9)) and (map_var(0) > 0))) then begin
        set_local_var(10, 0);
        if (local_var(11) == 0) then begin
            set_local_var(11, 1);
            add_timer_event(self_obj, game_ticks(random(3, 7)), 3);
        end
    end
    else begin
        if ((local_var(1) == 0) and (tile_num(self_obj) != local_var(9))) then begin
            debug_msg("Current Tile == " + tile_num(self_obj) + ". Home Tile == " + local_var(9));
            call GetMeHome();
        end
        else begin
            if ((local_var(1) != 0) and (local_var(6) == 0)) then begin
                call RepairTravel();
            end
            else begin
                if ((tile_num(self_obj) == local_var(9)) and (local_var(1) != 0)) then begin
                    call PrepareBot();
                end
                else begin
                    if (local_var(10) == 1) then begin
                        call GetMeHome();
                    end
                end
            end
        end
    end
    LVar1 := get_critter_stat(self_obj, STAT_current_hp);
    LVar0 := get_critter_stat(self_obj, STAT_max_hp);
    if (local_var(7) == 0) then begin
        if (LVar0 > LVar1) then begin
            set_local_var(7, 1);
            add_timer_event(self_obj, 20, 1);
        end
    end
end

procedure talk_p_proc
begin
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure combat_p_proc
begin
end

procedure damage_p_proc
begin
    if (local_var(7) == 0) then begin
        set_local_var(7, 1);
        add_timer_event(self_obj, 20, 1);
    end
end

procedure destroy_p_proc
begin
    if (local_var(1) == 1) then begin
        set_map_var(1, 5);
    end
    else begin
        if (local_var(1) == 2) then begin
            set_map_var(2, 5);
        end
        else begin
            if (local_var(1) == 3) then begin
                set_map_var(3, 5);
            end
            else begin
                if (local_var(1) == 4) then begin
                    set_map_var(4, 5);
                end
                else begin
                    if (local_var(1) == 5) then begin
                        set_map_var(5, 5);
                    end
                    else begin
                        if (local_var(1) == 6) then begin
                            set_map_var(6, 5);
                        end
                        else begin
                            if (map_var(1) == 0) then begin
                                set_map_var(1, 5);
                            end
                            else begin
                                if (map_var(2) == 0) then begin
                                    set_map_var(2, 5);
                                end
                                else begin
                                    if (map_var(3) == 0) then begin
                                        set_map_var(3, 5);
                                    end
                                    else begin
                                        if (map_var(4) == 0) then begin
                                            set_map_var(4, 5);
                                        end
                                        else begin
                                            if (map_var(5) == 0) then begin
                                                set_map_var(5, 5);
                                            end
                                            else begin
                                                if (map_var(6) == 0) then begin
                                                    set_map_var(6, 5);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_map_var(0, map_var(0) - 1);
end

procedure timed_event_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (fixed_param == 1) then begin
        LVar1 := get_critter_stat(self_obj, STAT_current_hp);
        LVar0 := get_critter_stat(self_obj, STAT_max_hp);
        if (LVar0 > LVar1) then begin
            critter_heal(self_obj, 1);
        end
        set_local_var(7, 0);
    end
    if (fixed_param == 2) then begin
        debug_msg("In Timed Event");
        call GetRobotHome();
        In_Timed_Event := 0;
    end
    if (fixed_param == 3) then begin
        set_local_var(11, 0);
        call RepairRequest();
    end
end

procedure RepairRequest
begin
    if (local_var(1) == 0) then begin
        if (map_var(1) == 1) then begin
            set_map_var(0, map_var(0) - 1);
            set_map_var(1, 2);
            set_local_var(1, 1);
            debug_msg("Sending Repair Bot " + local_var(1) + ".");
        end
        else begin
            if (map_var(2) == 1) then begin
                set_map_var(0, map_var(0) - 1);
                set_map_var(2, 2);
                set_local_var(1, 2);
                debug_msg("Sending Repair Bot " + local_var(1) + ".");
            end
            else begin
                if (map_var(3) == 1) then begin
                    set_map_var(0, map_var(0) - 1);
                    set_map_var(3, 2);
                    set_local_var(1, 3);
                    debug_msg("Sending Repair Bot " + local_var(1) + ".");
                end
                else begin
                    if (map_var(4) == 1) then begin
                        set_map_var(0, map_var(0) - 1);
                        set_map_var(4, 2);
                        set_local_var(1, 4);
                        debug_msg("Sending Repair Bot " + local_var(1) + ".");
                    end
                    else begin
                        if (map_var(5) == 1) then begin
                            set_map_var(0, map_var(0) - 1);
                            set_map_var(5, 2);
                            set_local_var(1, 5);
                            debug_msg("Sending Repair Bot " + local_var(1) + ".");
                        end
                        else begin
                            if (map_var(6) == 1) then begin
                                set_map_var(0, map_var(0) - 1);
                                set_map_var(6, 2);
                                set_local_var(1, 6);
                                debug_msg("Sending Repair Bot " + local_var(1) + ".");
                            end
                            else begin
                                call PickupRequest();
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure PickupRequest
begin
    if (local_var(1) == 0) then begin
        if (map_var(1) == 3) then begin
            set_map_var(0, map_var(0) - 1);
            set_map_var(1, 4);
            set_local_var(1, 1);
            debug_msg("Sending Repair Bot " + local_var(1) + ".");
        end
        else begin
            if (map_var(2) == 3) then begin
                set_map_var(0, map_var(0) - 1);
                set_map_var(2, 4);
                set_local_var(1, 2);
                debug_msg("Sending Repair Bot " + local_var(1) + ".");
            end
            else begin
                if (map_var(3) == 3) then begin
                    set_map_var(0, map_var(0) - 1);
                    set_map_var(3, 4);
                    set_local_var(1, 3);
                    debug_msg("Sending Repair Bot " + local_var(1) + ".");
                end
                else begin
                    if (map_var(4) == 3) then begin
                        set_map_var(0, map_var(0) - 1);
                        set_map_var(4, 4);
                        set_local_var(1, 4);
                        debug_msg("Sending Repair Bot " + local_var(1) + ".");
                    end
                    else begin
                        if (map_var(5) == 3) then begin
                            set_map_var(0, map_var(0) - 1);
                            set_map_var(5, 4);
                            set_local_var(1, 5);
                            debug_msg("Sending Repair Bot " + local_var(1) + ".");
                        end
                        else begin
                            if (map_var(6) == 3) then begin
                                set_map_var(0, map_var(0) - 1);
                                set_map_var(6, 4);
                                set_local_var(1, 6);
                                debug_msg("Sending Repair Bot " + local_var(1) + ".");
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure RepairTravel
begin
    if (local_var(1) == 1) then begin
        call Repair1();
    end
    else begin
        if (local_var(1) == 2) then begin
            call Repair2();
        end
        else begin
            if (local_var(1) == 3) then begin
                call Repair3();
            end
            else begin
                if (local_var(1) == 4) then begin
                    call Repair4();
                end
                else begin
                    if (local_var(1) == 5) then begin
                        call Repair5();
                    end
                    else begin
                        if (local_var(1) == 6) then begin
                            call Repair6();
                        end
                    end
                end
            end
        end
    end
end

procedure ReplaceBot
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (local_var(1) == 1) then begin
        debug_msg("Need to Make new bot " + local_var(1));
        LVar0 := create_object_sid(map_var(19), 0, 0, SCRIPT_WCSECBOT);
        LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
        critter_attempt_placement(LVar0, LVar1, 1);
        debug_msg("Created Bot 1.");
        set_map_var(1, 0);
        set_local_var(1, 0);
        set_local_var(6, 0);
        Bot_Elevation := map_var(7);
        Bot_Tile := map_var(13);
        call GetRobotHome();
    end
    else begin
        if (local_var(1) == 2) then begin
            debug_msg("Need to Make new bot " + local_var(1));
            LVar0 := create_object_sid(map_var(20), 0, 0, SCRIPT_WCSECBOT);
            LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
            critter_attempt_placement(LVar0, LVar1, 1);
            debug_msg("Created Bot 2.");
            set_map_var(1, 0);
            set_local_var(1, 0);
            set_local_var(6, 0);
            Bot_Elevation := map_var(8);
            Bot_Tile := map_var(14);
            call GetRobotHome();
        end
        else begin
            if (local_var(1) == 3) then begin
                debug_msg("Need to Make new bot " + local_var(1));
                LVar0 := create_object_sid(map_var(21), 0, 0, SCRIPT_WCSECBOT);
                LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
                critter_attempt_placement(LVar0, LVar1, 1);
                debug_msg("Created Bot 3.");
                set_map_var(3, 0);
                set_local_var(1, 0);
                set_local_var(6, 0);
                Bot_Elevation := map_var(9);
                Bot_Tile := map_var(15);
                call GetRobotHome();
            end
            else begin
                if (local_var(1) == 4) then begin
                    debug_msg("Need to Make new bot " + local_var(1));
                    LVar0 := create_object_sid(map_var(22), 0, 0, SCRIPT_WCSECBOT);
                    LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
                    critter_attempt_placement(LVar0, LVar1, 1);
                    debug_msg("Created Bot 4.");
                    set_map_var(4, 0);
                    set_local_var(1, 0);
                    set_local_var(6, 0);
                    Bot_Elevation := map_var(10);
                    Bot_Tile := map_var(16);
                    call GetRobotHome();
                end
                else begin
                    if (local_var(1) == 5) then begin
                        debug_msg("Need to Make new bot " + local_var(1));
                        LVar0 := create_object_sid(map_var(23), 0, 0, SCRIPT_WCSECBOT);
                        LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
                        critter_attempt_placement(LVar0, LVar1, 1);
                        debug_msg("Created Bot 5.");
                        set_map_var(5, 0);
                        set_local_var(1, 0);
                        set_local_var(6, 0);
                        Bot_Elevation := map_var(11);
                        Bot_Tile := map_var(17);
                        call GetRobotHome();
                    end
                    else begin
                        if (local_var(1) == 6) then begin
                            debug_msg("Need to Make new bot " + local_var(1));
                            LVar0 := create_object_sid(map_var(24), 0, 0, SCRIPT_WCSECBOT);
                            LVar1 := tile_num_in_direction(tile_num(self_obj), random(3, 5), 2);
                            critter_attempt_placement(LVar0, LVar1, 1);
                            debug_msg("Created Bot 6.");
                            set_map_var(6, 0);
                            set_local_var(1, 0);
                            set_local_var(6, 0);
                            Bot_Elevation := map_var(12);
                            Bot_Tile := map_var(18);
                            call GetRobotHome();
                        end
                    end
                end
            end
        end
    end
end

procedure PrepareBot
begin
    if (local_var(1) == 1) then begin
        set_map_var(1, 0);
        set_local_var(1, 0);
        set_local_var(6, 0);
        if (map_var(7) == 0) then begin
            if ((map_var(19) == 16777293) or (map_var(19) == 16777294)) then begin
                set_map_var(59, map_var(59) + 1);
            end
            else begin
                if (map_var(19) == 16777291) then begin
                    set_map_var(60, map_var(60) + 1);
                end
                else begin
                    set_map_var(61, map_var(61) + 1);
                end
            end
        end
        else begin
            if (map_var(7) == 1) then begin
                if ((map_var(19) == 16777293) or (map_var(19) == 16777294)) then begin
                    set_map_var(62, map_var(62) + 1);
                end
                else begin
                    if (map_var(19) == 16777291) then begin
                        set_map_var(63, map_var(63) + 1);
                    end
                    else begin
                        set_map_var(64, map_var(64) + 1);
                    end
                end
            end
            else begin
                if ((map_var(19) == 16777293) or (map_var(19) == 16777294)) then begin
                    set_map_var(65, map_var(65) + 1);
                end
                else begin
                    if (map_var(19) == 16777291) then begin
                        set_map_var(66, map_var(66) + 1);
                    end
                    else begin
                        set_map_var(67, map_var(67) + 1);
                    end
                end
            end
        end
        debug_msg("Add Robot to Queue");
    end
    else begin
        if (local_var(1) == 2) then begin
            set_map_var(1, 0);
            set_local_var(1, 0);
            set_local_var(6, 0);
            if (map_var(8) == 0) then begin
                if ((map_var(20) == 16777293) or (map_var(20) == 16777294)) then begin
                    set_map_var(59, map_var(59) + 1);
                end
                else begin
                    if (map_var(20) == 16777291) then begin
                        set_map_var(60, map_var(60) + 1);
                    end
                    else begin
                        set_map_var(61, map_var(61) + 1);
                    end
                end
            end
            else begin
                if (map_var(8) == 1) then begin
                    if ((map_var(20) == 16777293) or (map_var(20) == 16777294)) then begin
                        set_map_var(62, map_var(62) + 1);
                    end
                    else begin
                        if (map_var(20) == 16777291) then begin
                            set_map_var(63, map_var(63) + 1);
                        end
                        else begin
                            set_map_var(64, map_var(64) + 1);
                        end
                    end
                end
                else begin
                    if ((map_var(20) == 16777293) or (map_var(20) == 16777294)) then begin
                        set_map_var(65, map_var(65) + 1);
                    end
                    else begin
                        if (map_var(20) == 16777291) then begin
                            set_map_var(66, map_var(66) + 1);
                        end
                        else begin
                            set_map_var(67, map_var(67) + 1);
                        end
                    end
                end
            end
            debug_msg("Add Robot to Queue");
        end
        else begin
            if (local_var(1) == 3) then begin
                set_map_var(3, 0);
                set_local_var(1, 0);
                set_local_var(6, 0);
                if (map_var(9) == 0) then begin
                    if ((map_var(21) == 16777293) or (map_var(21) == 16777294)) then begin
                        set_map_var(59, map_var(59) + 1);
                    end
                    else begin
                        if (map_var(21) == 16777291) then begin
                            set_map_var(60, map_var(60) + 1);
                        end
                        else begin
                            set_map_var(61, map_var(61) + 1);
                        end
                    end
                end
                else begin
                    if (map_var(9) == 1) then begin
                        if ((map_var(21) == 16777293) or (map_var(21) == 16777294)) then begin
                            set_map_var(62, map_var(62) + 1);
                        end
                        else begin
                            if (map_var(21) == 16777291) then begin
                                set_map_var(63, map_var(63) + 1);
                            end
                            else begin
                                set_map_var(64, map_var(64) + 1);
                            end
                        end
                    end
                    else begin
                        if ((map_var(21) == 16777293) or (map_var(21) == 16777294)) then begin
                            set_map_var(65, map_var(65) + 1);
                        end
                        else begin
                            if (map_var(21) == 16777291) then begin
                                set_map_var(66, map_var(66) + 1);
                            end
                            else begin
                                set_map_var(67, map_var(67) + 1);
                            end
                        end
                    end
                end
                debug_msg("Add Robot to Queue");
            end
            else begin
                if (local_var(1) == 4) then begin
                    set_map_var(4, 0);
                    set_local_var(1, 0);
                    set_local_var(6, 0);
                    if (map_var(10) == 0) then begin
                        if ((map_var(22) == 16777293) or (map_var(22) == 16777294)) then begin
                            set_map_var(59, map_var(59) + 1);
                        end
                        else begin
                            if (map_var(22) == 16777291) then begin
                                set_map_var(60, map_var(60) + 1);
                            end
                            else begin
                                set_map_var(61, map_var(61) + 1);
                            end
                        end
                    end
                    else begin
                        if (map_var(10) == 1) then begin
                            if ((map_var(22) == 16777293) or (map_var(22) == 16777294)) then begin
                                set_map_var(62, map_var(62) + 1);
                            end
                            else begin
                                if (map_var(22) == 16777291) then begin
                                    set_map_var(63, map_var(63) + 1);
                                end
                                else begin
                                    set_map_var(64, map_var(64) + 1);
                                end
                            end
                        end
                        else begin
                            if ((map_var(22) == 16777293) or (map_var(22) == 16777294)) then begin
                                set_map_var(65, map_var(65) + 1);
                            end
                            else begin
                                if (map_var(22) == 16777291) then begin
                                    set_map_var(66, map_var(66) + 1);
                                end
                                else begin
                                    set_map_var(67, map_var(67) + 1);
                                end
                            end
                        end
                    end
                    debug_msg("Add Robot to Queue");
                end
                else begin
                    if (local_var(1) == 5) then begin
                        set_map_var(5, 0);
                        set_local_var(1, 0);
                        set_local_var(6, 0);
                        if (map_var(11) == 0) then begin
                            if ((map_var(23) == 16777293) or (map_var(23) == 16777294)) then begin
                                set_map_var(59, map_var(59) + 1);
                            end
                            else begin
                                if (map_var(23) == 16777291) then begin
                                    set_map_var(60, map_var(60) + 1);
                                end
                                else begin
                                    set_map_var(61, map_var(61) + 1);
                                end
                            end
                        end
                        else begin
                            if (map_var(11) == 1) then begin
                                if ((map_var(23) == 16777293) or (map_var(23) == 16777294)) then begin
                                    set_map_var(62, map_var(62) + 1);
                                end
                                else begin
                                    if (map_var(23) == 16777291) then begin
                                        set_map_var(63, map_var(63) + 1);
                                    end
                                    else begin
                                        set_map_var(64, map_var(64) + 1);
                                    end
                                end
                            end
                            else begin
                                if ((map_var(23) == 16777293) or (map_var(23) == 16777294)) then begin
                                    set_map_var(65, map_var(65) + 1);
                                end
                                else begin
                                    if (map_var(23) == 16777291) then begin
                                        set_map_var(66, map_var(66) + 1);
                                    end
                                    else begin
                                        set_map_var(67, map_var(67) + 1);
                                    end
                                end
                            end
                        end
                        debug_msg("Add Robot to Queue");
                    end
                    else begin
                        if (local_var(1) == 6) then begin
                            set_map_var(6, 0);
                            set_local_var(1, 0);
                            set_local_var(6, 0);
                            if (map_var(12) == 0) then begin
                                if ((map_var(24) == 16777293) or (map_var(24) == 16777294)) then begin
                                    set_map_var(59, map_var(59) + 1);
                                end
                                else begin
                                    if (map_var(24) == 16777291) then begin
                                        set_map_var(60, map_var(60) + 1);
                                    end
                                    else begin
                                        set_map_var(61, map_var(61) + 1);
                                    end
                                end
                            end
                            else begin
                                if (map_var(12) == 1) then begin
                                    if ((map_var(24) == 16777293) or (map_var(24) == 16777294)) then begin
                                        set_map_var(62, map_var(62) + 1);
                                    end
                                    else begin
                                        if (map_var(24) == 16777291) then begin
                                            set_map_var(63, map_var(63) + 1);
                                        end
                                        else begin
                                            set_map_var(64, map_var(64) + 1);
                                        end
                                    end
                                end
                                else begin
                                    if ((map_var(24) == 16777293) or (map_var(24) == 16777294)) then begin
                                        set_map_var(65, map_var(65) + 1);
                                    end
                                    else begin
                                        if (map_var(24) == 16777291) then begin
                                            set_map_var(66, map_var(66) + 1);
                                        end
                                        else begin
                                            set_map_var(67, map_var(67) + 1);
                                        end
                                    end
                                end
                            end
                            debug_msg("Add Robot to Queue");
                        end
                    end
                end
            end
        end
    end
end

procedure Repair1
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(13)) < 2) and (elevation(self_obj) == map_var(7))) then begin
        if (tile_contains_obj_pid(map_var(13), map_var(7), map_var(19))) then begin
            Bot := tile_contains_pid_obj(map_var(13), map_var(7), map_var(19));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(1) == 4) then begin
                destroy_object(Bot);
                LVar3 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar3, 1);
                set_map_var(1, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 1");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    critter_heal(Bot, 1);
                    Repair_Bot := 0;
                end
                if (map_var(29) != 0) then begin
                    LVar2 := create_object(map_var(28), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar2, map_var(29));
                    set_map_var(29, 0);
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(1, 0);
                    debug_msg("Bot completely repaired.");
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel1();
    end
end

procedure Repair2
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(14)) < 2) and (elevation(self_obj) == map_var(8))) then begin
        if (tile_contains_obj_pid(map_var(14), map_var(8), map_var(20))) then begin
            Bot := tile_contains_pid_obj(map_var(14), map_var(8), map_var(20));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(2) == 4) then begin
                destroy_object(Bot);
                LVar3 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar3, 1);
                set_map_var(2, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 2");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    critter_heal(Bot, 1);
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    Repair_Bot := 0;
                end
                if (map_var(31) != 0) then begin
                    LVar2 := create_object(map_var(30), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar2, map_var(31));
                    set_map_var(31, 0);
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(2, 0);
                    debug_msg("Bot completely repaired.");
                    set_local_var(1, 0);
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel2();
    end
end

procedure Repair3
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(15)) < 2) and (elevation(self_obj) == map_var(9))) then begin
        if (tile_contains_obj_pid(map_var(15), map_var(9), map_var(21))) then begin
            Bot := tile_contains_pid_obj(map_var(15), map_var(9), map_var(21));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(3) == 4) then begin
                destroy_object(Bot);
                LVar3 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar3, 1);
                set_map_var(1, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 3");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    critter_heal(Bot, 1);
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    Repair_Bot := 0;
                end
                if (map_var(33) != 0) then begin
                    LVar2 := create_object(map_var(32), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar2, map_var(33));
                    set_map_var(33, 0);
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(3, 0);
                    debug_msg("Bot completely repaired.");
                    set_local_var(1, 0);
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel3();
    end
end

procedure Repair4
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(16)) < 2) and (elevation(self_obj) == map_var(10))) then begin
        if (tile_contains_obj_pid(map_var(16), map_var(10), map_var(22))) then begin
            Bot := tile_contains_pid_obj(map_var(16), map_var(10), map_var(22));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(4) == 4) then begin
                destroy_object(Bot);
                LVar3 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar3, 1);
                set_map_var(4, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 4");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    critter_heal(Bot, 1);
                    Repair_Bot := 0;
                end
                if (map_var(35) != 0) then begin
                    LVar2 := create_object(map_var(34), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar2, map_var(35));
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    set_map_var(35, 0);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(4, 0);
                    debug_msg("Bot completely repaired.");
                    set_local_var(1, 0);
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel4();
    end
end

procedure Repair5
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(17)) < 2) and (elevation(self_obj) == map_var(11))) then begin
        if (tile_contains_obj_pid(map_var(17), map_var(11), map_var(23))) then begin
            Bot := tile_contains_pid_obj(map_var(17), map_var(11), map_var(23));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(5) == 4) then begin
                destroy_object(Bot);
                LVar2 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar2, 1);
                set_map_var(5, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 5");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    critter_heal(Bot, 1);
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    Repair_Bot := 0;
                end
                if (map_var(37) != 0) then begin
                    LVar3 := create_object(map_var(36), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar3, map_var(37));
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    set_map_var(37, 0);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(5, 0);
                    debug_msg("Bot completely repaired.");
                    set_local_var(1, 0);
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel5();
    end
end

procedure Repair6
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if ((tile_distance(tile_num(self_obj), map_var(18)) < 2) and (elevation(self_obj) == map_var(12))) then begin
        if (tile_contains_obj_pid(map_var(18), map_var(12), map_var(24))) then begin
            Bot := tile_contains_pid_obj(map_var(18), map_var(12), map_var(24));
            LVar0 := get_critter_stat(Bot, STAT_max_hp);
            LVar1 := get_critter_stat(Bot, STAT_current_hp);
            if (map_var(6) == 4) then begin
                destroy_object(Bot);
                LVar2 := create_object(269, 0, 0);
                add_mult_objs_to_inven(self_obj, LVar2, 1);
                set_map_var(6, 6);
                debug_msg("Bot being reclaimed for metal.");
                call GetMeHome();
                debug_msg("Make Me Move 6");
                set_local_var(6, 1);
            end
            else begin
                Repair_Bot := Repair_Bot + 1;
                if (Repair_Bot == 5) then begin
                    critter_heal(Bot, 1);
                    float_msg(self_obj, g_mstr(9002), FLOAT_MSG_GREEN);
                    Repair_Bot := 0;
                end
                if (map_var(39) != 0) then begin
                    LVar3 := create_object(map_var(38), 0, 0);
                    add_mult_objs_to_inven(Bot, LVar3, map_var(39));
                    set_map_var(39, 0);
                    float_msg(self_obj, g_mstr(9001), FLOAT_MSG_GREEN);
                    debug_msg("Bot Rearmed.");
                end
                if ((LVar0 == LVar1) or (critter_state(Bot) == 1)) then begin
                    set_local_var(1, 0);
                    set_map_var(6, 0);
                    debug_msg("Bot completely repaired.");
                    set_local_var(1, 0);
                    float_msg(self_obj, g_mstr(9000), FLOAT_MSG_GREEN);
                    set_map_var(0, map_var(0) + 1);
                    call GetMeHome();
                end
            end
        end
        else begin
            if (local_var(12) == 0) then begin
                set_local_var(12, game_time);
            end
            else begin
                if ((game_time - local_var(12)) > (2 * (60 * 10))) then begin
                    call GetMeHome();
                end
            end
        end
    end
    else begin
        call Travel6();
    end
end

procedure Travel1
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(7)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(13), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure Travel2
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(8)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(14), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure Travel3
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(9)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(15), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure Travel4
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(10)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(16), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure Travel5
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(11)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(17), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure Travel6
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if (elevation(self_obj) != map_var(12)) then begin
        call FindElevator();
        if (tile_num(self_obj) != Elevator_Tile) then begin
            animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
        end
        else begin
            if (map_var(7) == 0) then begin
                move_to(self_obj, 20517, 0);
            end
            else begin
                if (map_var(7) == 1) then begin
                    move_to(self_obj, 19724, 1);
                end
                else begin
                    move_to(self_obj, 21135, 2);
                end
            end
        end
    end
    else begin
        LVar1 := tile_num_in_direction(map_var(18), random(0, 5), 1);
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, LVar1, elevation(self_obj));
        end
        else begin
            animate_move_obj_to_tile(self_obj, LVar1, 0);
        end
    end
end

procedure FindElevator
begin
    if (elevation(self_obj) == 0) then begin
        Elevator_Tile := 20517;
    end
    else begin
        if (elevation(self_obj) == 1) then begin
            Elevator_Tile := 19724;
        end
        else begin
            Elevator_Tile := 21135;
        end
    end
end

procedure GetMeHome
begin
    set_local_var(10, 0);
    set_local_var(12, 0);
    debug_msg("Trying to go Home");
    if (elevation(self_obj) != 1) then begin
        call FindElevator();
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, 19724, 1);
        end
        else begin
            if (tile_num(self_obj) != Elevator_Tile) then begin
                animate_move_obj_to_tile(self_obj, Elevator_Tile, 0);
            end
            else begin
                if (1 == 0) then begin
                    move_to(self_obj, 20517, 0);
                end
                else begin
                    if (1 == 1) then begin
                        move_to(self_obj, 19724, 1);
                    end
                    else begin
                        move_to(self_obj, 21135, 2);
                    end
                end
            end
        end
    end
    else begin
        if (elevation(self_obj) != dude_elevation) then begin
            move_to(self_obj, local_var(9), 1);
        end
        else begin
            animate_move_obj_to_tile(self_obj, local_var(9), 0);
        end
    end
end

procedure GetRobotHome
begin
    if (elevation(Bot) != Bot_Elevation) then begin
        call FindBotElevator();
        if (tile_num(Bot) != Elevator_Tile) then begin
            animate_move_obj_to_tile(Bot, Elevator_Tile, 0);
        end
        else begin
            if (Bot_Elevation == 0) then begin
                move_to(Bot, 20517, 0);
            end
            else begin
                if (Bot_Elevation == 1) then begin
                    move_to(Bot, 19724, 1);
                end
                else begin
                    move_to(Bot, 21135, 2);
                end
            end
        end
    end
    else begin
        animate_move_obj_to_tile(Bot, Bot_Tile, 0);
        debug_msg("Send New Bot home.");
    end
end

procedure FindBotElevator
begin
    if (elevation(Bot) == 0) then begin
        Elevator_Tile := 20517;
    end
    else begin
        if (elevation(Bot) == 1) then begin
            Elevator_Tile := 19724;
        end
        else begin
            Elevator_Tile := 21135;
        end
    end
end
