procedure Start;
procedure look_at_p_proc;
procedure description_p_proc;
procedure talk_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure Zack00;
procedure Zack01;
procedure Zack02;
procedure Zack03;
procedure Zack04;
procedure Zack05;
procedure ZackYes;
procedure ZackNo;
procedure ZackBarter;
procedure ZackEnd;

import variable Locker_Ptr;

variable Initialize := 1;
variable BarterMod := -10;
variable DisplayMessage;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;


procedure Start
begin
    if (Initialize) then begin
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 48);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BRAIN_MOLE_RAT);
        Initialize := 0;
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(SCRIPT_ZISLOTS, 100));
    end
    else begin
        display_msg(message_str(SCRIPT_ZISLOTS, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(4) == 1) then begin
        display_msg(message_str(SCRIPT_ZISLOTS, 100));
    end
    else begin
        display_msg(message_str(SCRIPT_ZISLOTS, 101));
    end
end

procedure talk_p_proc
begin
    if (global_var(GVAR_SPECIAL_ENCOUNTER_CAFE) == 1) then begin
        float_msg(self_obj, message_str(SCRIPT_VCMOORE, random(100, 105)), FLOAT_MSG_RED);
    end
    else begin
        BarterMod := -10;
        move_obj_inven_to_obj(Locker_Ptr, self_obj);
        item_caps_adjust(self_obj, 3000 + random(1, 1000));
        call get_reaction();
        start_gdialog(377, self_obj, -1, -1, -1);
        gsay_start;
        if (local_var(5) == 2) then begin
            BarterMod := 15;
        end
        else begin
            if (local_var(5) == 1) then begin
                BarterMod := 5;
            end
            else begin
                BarterMod := -10;
            end
        end
        gdialog_set_barter_mod(BarterMod);
        if (local_var(4) == 0) then begin
            call Zack00();
        end
        else begin
            call Zack01();
        end
        gsay_end;
        end_dialogue;
        item_caps_adjust(self_obj, -item_caps_total(self_obj));
        move_obj_inven_to_obj(self_obj, Locker_Ptr);
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_SPECIAL_ENCOUNTER_CAFE, 1);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_SPECIAL_ENCOUNTER_CAFE, 1);
        if (source_obj == dude_obj) then begin
            if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
                set_global_var(GVAR_SIERRA_LOCKOUT, 1);
                set_global_var(GVAR_SIERRA_PASSWORD, 0);
            end
            if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
                set_global_var(GVAR_SIERRA_PASSWORD, 1);
                set_global_var(GVAR_SIERRA_LOCKOUT, 0);
            end
            set_global_var(GVAR_GECKO_REQ_FORM, global_var(GVAR_GECKO_REQ_FORM) + 1);
            if ((global_var(GVAR_GECKO_REQ_FORM) % 2) == 0) then begin
                set_global_var(GVAR_BRAIN_BOT_BRAIN, global_var(GVAR_BRAIN_BOT_BRAIN) - 1);
            end
        end
    end
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (global_var(GVAR_SPECIAL_ENCOUNTER_CAFE) == 1) then begin
            attack(dude_obj);
        end
    end
end

procedure pickup_p_proc
begin
    set_global_var(GVAR_SPECIAL_ENCOUNTER_CAFE, 1);
end

procedure Zack00
begin
    gsay_reply(SCRIPT_ZISLOTS, 102);
    giq_option(1, SCRIPT_ZISLOTS, 104, ZackBarter, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZISLOTS, 103, Zack02, NEUTRAL_REACTION);
    if (local_var(5) == 0) then begin
        DisplayMessage := 117;
        giq_option(1, SCRIPT_ZISLOTS, 105, Zack04, NEUTRAL_REACTION);
    end
    else begin
        if (local_var(5) == 1) then begin
            DisplayMessage := 123;
            giq_option(1, SCRIPT_ZISLOTS, 122, Zack05, NEUTRAL_REACTION);
        end
    end
    giq_option(1, SCRIPT_ZISLOTS, 107, ZackEnd, NEUTRAL_REACTION);
end

procedure Zack01
begin
    gsay_reply(SCRIPT_ZISLOTS, 106);
    giq_option(1, SCRIPT_ZISLOTS, 104, ZackBarter, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZISLOTS, 103, Zack02, NEUTRAL_REACTION);
    if (local_var(5) == 0) then begin
        DisplayMessage := 117;
        giq_option(1, SCRIPT_ZISLOTS, 105, Zack04, NEUTRAL_REACTION);
    end
    else begin
        if (local_var(5) == 1) then begin
            DisplayMessage := 123;
            giq_option(1, SCRIPT_ZISLOTS, 122, Zack05, NEUTRAL_REACTION);
        end
    end
    giq_option(1, SCRIPT_ZISLOTS, 107, ZackEnd, NEUTRAL_REACTION);
end

procedure Zack02
begin
    gsay_reply(SCRIPT_ZISLOTS, 114);
    giq_option(1, SCRIPT_ZISLOTS, 115, Zack03, NEUTRAL_REACTION);
end

procedure Zack03
begin
    gsay_reply(SCRIPT_ZISLOTS, 111);
    giq_option(1, SCRIPT_ZISLOTS, 113, ZackBarter, NEUTRAL_REACTION);
end

procedure Zack04
begin
    if (global_var(GVAR_NCR_BISHOP_PRICE) == 9250) then begin
        BarterMod := 15;
        set_local_var(5, 2);
        call ZackYes();
    end
    else begin
        if (global_var(GVAR_SPECIAL_ENCOUNTER_HOLY1) == 9201) then begin
            BarterMod := 5;
            set_local_var(5, 1);
            call ZackYes();
        end
        else begin
            BarterMod := -10;
            call ZackNo();
        end
    end
end

procedure Zack05
begin
    if (global_var(GVAR_NCR_BISHOP_PRICE) == 9250) then begin
        BarterMod := 0;
        set_local_var(5, 2);
        call ZackYes();
    end
    else begin
        call ZackNo();
    end
end

procedure ZackYes
begin
    gsay_reply(SCRIPT_ZISLOTS, 116);
    giq_option(1, SCRIPT_ZISLOTS, 120, ZackBarter, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZISLOTS, 121, ZackEnd, NEUTRAL_REACTION);
end

procedure ZackNo
begin
    gsay_reply(SCRIPT_ZISLOTS, DisplayMessage);
    giq_option(1, SCRIPT_ZISLOTS, 119, ZackBarter, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZISLOTS, 107, ZackEnd, NEUTRAL_REACTION);
end

procedure ZackBarter
begin
    gdialog_mod_barter(BarterMod);
    gsay_message(SCRIPT_ZISLOTS, 108, NEUTRAL_REACTION);
end

procedure ZackEnd
begin
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_BRAIN_BOT_BRAIN) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_BRAIN_BOT_BRAIN));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_BRAIN_BOT_BRAIN));
            end
        end
        if (global_var(GVAR_GECKO_ECON_DISK) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GECKO_REQ_FORM))) or (global_var(GVAR_SIERRA_PASSWORD) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_GECKO_SKEETER_PART) + global_var(GVAR_GECKO_REQ_FORM)) >= 25) and ((global_var(GVAR_GECKO_REQ_FORM) > (2 * global_var(GVAR_GECKO_SKEETER_PART))) or (global_var(GVAR_SIERRA_LOCKOUT) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_BSCOMP3, random(100, 105));
end
