variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;
variable trading_container;
variable punches;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node038a;
procedure Node039;
procedure Node040;
procedure Node041;
procedure Node999;
procedure Node998;
procedure NodeBarter;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(70, 80));
        set_local_var(5, random(30, 40));
        set_local_var(6, random(-30, 20));
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 11);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GENTLEMAN_COWARD);
        if (random(0, 100) <= 75) then begin
            add_mult_objs_to_inven(self_obj, create_object(41, 1, 2), random(1, 40));
        end
        if (random(0, 100) <= 45) then begin
            add_obj_to_inven(self_obj, create_object(415, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(419, 1, 2));
        end
        if (random(0, 100) <= 30) then begin
            add_obj_to_inven(self_obj, create_object(434, 1, 2));
        end
        if (random(0, 100) <= 20) then begin
            add_obj_to_inven(self_obj, create_object(145, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(223, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(39, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(82, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(228, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(410, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(431, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(110, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(323, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(239, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(235, 1, 2));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(GVAR_TOWN_REP_GECKO) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_mstr(2);
    end
    else begin
        display_mstr(4);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_mstr(1);
    end
    else begin
        display_mstr(3);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (local_var(7) == 1) then begin
        if (not(anim_busy(self_obj))) then begin
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
        end
    end
    start_gdialog(222, self_obj, 4, 9, -1);
    gsay_start;
    if (local_var(9) == 1) then begin
        call Node039();
    end
    else begin
        if (local_var(7) == 0) then begin
            call Node001();
        end
        else begin
            call Node010();
        end
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    set_global_var(GVAR_MODOC_TOOL_FLAG, global_var(GVAR_MODOC_TOOL_FLAG) bwor 32768);
    if (global_var(GVAR_DEN_SMITTY_PART) == 1) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 0);
    end
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
        if ((51 == 50) or (51 == 59)) then begin
            set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) - 3);
        end
        else begin
            set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
                if (global_var(GVAR_VAULT_CITIZENSHIP) < get_pc_stat(PCSTAT_level)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 3);
                    end
                    else begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 1);
                    end
                    if (global_var(GVAR_QUEST_FIND_THOMAS) >= (2 * get_pc_stat(PCSTAT_level))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, 0);
                        set_global_var(GVAR_VAULT_CITIZENSHIP, global_var(GVAR_VAULT_CITIZENSHIP) + 1);
                        critter_mod_skill(dude_obj, SKILL_STEAL, 1);
                        display_msg(message_str(SCRIPT_STTEXT, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(TRAIT_PERK, dude_obj, PERK_pickpocket) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(TRAIT_PERK, dude_obj, PERK_master_thief) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND)) == 245) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(SCRIPT_STTEXT, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((dude_luck - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(SCRIPT_STTEXT, random(206, 209)), FLOAT_MSG_RED);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(SCRIPT_STTEXT, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_STTEXT, 204) + ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(SCRIPT_STTEXT, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (tile_num(self_obj) != local_var(3)) then begin
        move_to(self_obj, local_var(3), elevation(self_obj));
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
    if (fixed_param == 3) then begin
        fadeOut(700);
        move_to(self_obj, 15688, elevation(self_obj));
        anim(self_obj, 1000, 2);
        move_to(dude_obj, 15888, elevation(self_obj));
        anim(dude_obj, 1000, 5);
        fadeIn(700);
        add_timer_event(self_obj, random(15, 20), 4);
    end
    if (fixed_param == 4) then begin
        punches := punches + 1;
        play_sfx("HMXXXXAQ");
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 16, -1);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 2, 5);
        if (punches < 3) then begin
            add_timer_event(self_obj, random(15, 20), 4);
        end
        else begin
            add_timer_event(self_obj, 15, 6);
        end
    end
    if (fixed_param == 5) then begin
        play_sfx("HMXXXXAP");
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 14, -1);
        reg_anim_func(3, 0);
    end
    if (fixed_param == 6) then begin
        set_local_var(9, 1);
        dialogue_system_enter;
    end
end

procedure Node001
begin
    set_local_var(7, 1);
    already_talk := 1;
    Reply(10);
    giq_option(1, NAME, 11, Node002, BAD_REACTION);
    giq_option(1, NAME, 12, Node003, NEUTRAL_REACTION);
    giq_option(1, NAME, 13, Node004, GOOD_REACTION);
end

procedure Node002
begin
    Reply(20);
    giq_option(1, NAME, 21, Node005, BAD_REACTION);
    giq_option(1, NAME, 22, Node006, NEUTRAL_REACTION);
    giq_option(1, NAME, 23, Node004, GOOD_REACTION);
end

procedure Node003
begin
    Reply(30);
    giq_option(1, NAME, 31, Node005, BAD_REACTION);
    giq_option(1, NAME, 32, Node006, NEUTRAL_REACTION);
    giq_option(1, NAME, 33, Node004, GOOD_REACTION);
end

procedure Node004
begin
    Reply(40);
    giq_option(1, NAME, 41, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 42, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
    Reply(50);
    giq_option(1, NAME, 51, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 52, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    Reply(60);
    giq_option(1, NAME, 61, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 62, Node999, NEUTRAL_REACTION);
end

procedure Node010
begin
    if (already_talk == 0) then begin
        already_talk := 1;
        if (global_var(GVAR_NCR_ENCLAVE_INFO) == 2) then begin
            Reply(1001);
        end
        else begin
            Reply(1003);
        end
    end
    else begin
        Reply(1002);
    end
    giq_option(1, NAME, 101, Node024, NEUTRAL_REACTION);
    giq_option(1, NAME, 102, Node013, NEUTRAL_REACTION);
    giq_option(1, NAME, 103, Node014, NEUTRAL_REACTION);
    if (global_var(GVAR_GECKO_SKEETER_PART) == 1) then begin
        giq_option(1, NAME, 104, Node011, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_DEN_SMITTY_PART) == 1) then begin
        giq_option(1, NAME, 105, Node029, GOOD_REACTION);
    end
    if (global_var(GVAR_SIERRA_BASE_ENEMY) == 1) then begin
        giq_option(1, NAME, 106, Node041, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 107, Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    Reply(110);
    giq_option(1, NAME, 111, Node012, NEUTRAL_REACTION);
end

procedure Node012
begin
    Reply(120);
    giq_option(1, NAME, 121, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 122, Node999, NEUTRAL_REACTION);
end

procedure Node013
begin
    Reply(130);
    giq_option(1, NAME, 131, Node014, NEUTRAL_REACTION);
    giq_option(1, NAME, 132, Node010, NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(140);
    if (global_var(GVAR_SIERRA_BASE_ALERT) == 1) then begin
        giq_option(1, NAME, 141, Node015, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_DEN_SMITTY_PART) == 0) then begin
        giq_option(1, NAME, 142, Node026, BAD_REACTION);
    end
    giq_option(1, NAME, 143, Node016, NEUTRAL_REACTION);
    giq_option(1, NAME, 144, Node025, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(150);
    giq_option(1, NAME, 151, Node999, NEUTRAL_REACTION);
    giq_option(1, NAME, 152, Node010, NEUTRAL_REACTION);
end

procedure Node016
begin
    Reply(160);
    giq_option(1, NAME, 161, Node017, NEUTRAL_REACTION);
    giq_option(1, NAME, 162, Node010, NEUTRAL_REACTION);
end

procedure Node017
begin
    Reply(170);
    giq_option(1, NAME, 171, Node018, BAD_REACTION);
    giq_option(1, NAME, 172, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 173, Node025, NEUTRAL_REACTION);
end

procedure Node018
begin
    if (dude_skill(SKILL_SPEECH) < 40) then begin
        Reply(1801);
    end
    else begin
        Reply(1802);
    end
    giq_option(1, NAME, 181, Node010, NEUTRAL_REACTION);
    if (dude_skill(SKILL_SPEECH) >= 40) then begin
        giq_option(1, NAME, 182, Node022, NEUTRAL_REACTION);
        giq_option(1, NAME, 183, Node021, GOOD_REACTION);
        giq_option(1, NAME, 184, Node019, BAD_REACTION);
    end
    giq_option(1, NAME, 185, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    Reply(190);
    giq_option(1, NAME, 191, Node020, BAD_REACTION);
    giq_option(1, NAME, 192, Node010, GOOD_REACTION);
    giq_option(1, NAME, 193, Node999, NEUTRAL_REACTION);
end

procedure Node020
begin
    Reply(200);
    giq_option(1, NAME, 201, Node998, NEUTRAL_REACTION);
end

procedure Node021
begin
    Reply(210);
    giq_option(1, NAME, 211, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 212, Node999, NEUTRAL_REACTION);
end

procedure Node022
begin
    Reply(220);
    giq_option(1, NAME, 221, Node023, BAD_REACTION);
end

procedure Node023
begin
    Reply(230);
    giq_option(1, NAME, 231, Node010, GOOD_REACTION);
    giq_option(1, NAME, 232, Node999, NEUTRAL_REACTION);
end

procedure Node024
begin
    if (global_var(GVAR_NCR_ENCLAVE_INFO) == 2) then begin
        Reply(2401);
    end
    else begin
        Reply(2402);
    end
    giq_option(1, NAME, 241, Node025, NEUTRAL_REACTION);
end

procedure Node025
begin
    Reply(250);
    giq_option(1, NAME, 251, Node010, NEUTRAL_REACTION);
end

procedure Node026
begin
    Reply(260);
    giq_option(1, NAME, 261, Node027, NEUTRAL_REACTION);
end

procedure Node027
begin
    Reply(270);
    giq_option(1, NAME, 271, Node028, BAD_REACTION);
end

procedure Node028
begin
    if ((global_var(GVAR_MODOC_TOOL_FLAG) bwand 2097152) != 0) then begin
        Reply(2801);
    end
    else begin
        if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
            Reply(2802);
        end
        else begin
            Reply(2803);
        end
    end
    if ((global_var(GVAR_DEN_SMITTY_PART) == 0) and not((global_var(GVAR_MODOC_TOOL_FLAG) bwand 2097152) != 0)) then begin
        giq_option(1, NAME, 281, Node040, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 282, Node999, NEUTRAL_REACTION);
end

procedure Node029
begin
    Reply(290);
    if ((global_var(GVAR_MODOC_TOOL_FLAG) bwand 2097152) != 0) then begin
        giq_option(1, NAME, 291, Node030, NEUTRAL_REACTION);
    end
    else begin
        if (global_var(GVAR_ENEMY_GECKO) == 1) then begin
            giq_option(1, NAME, 292, Node031, GOOD_REACTION);
        end
        if ((global_var(GVAR_GECKO_COOLANT) == 1) and (global_var(GVAR_NCR_POWERPLANT) == 1)) then begin
            giq_option(1, NAME, 293, Node032, GOOD_REACTION);
        end
    end
    if (not(global_var(GVAR_MODOC_TOOL_FLAG) bwand 2097152) != 0) then begin
        giq_option(1, NAME, 294, Node033, BAD_REACTION);
        if (global_var(GVAR_NCR_HENRY_HYPO) == 0) then begin
            giq_option(1, NAME, 295, Node035, NEUTRAL_REACTION);
        end
    end
    giq_option(1, NAME, 296, Node010, NEUTRAL_REACTION);
    if ((global_var(GVAR_NCR_HENRY_HYPO) == 1) and (global_var(GVAR_NCR_PLAYER_RANGER) == 1) and (not(global_var(GVAR_MODOC_TOOL_FLAG) bwand 2097152) != 0)) then begin
        giq_option(1, NAME, 297, Node036, NEUTRAL_REACTION);
    end
end

procedure Node030
begin
    variable LVar0 := 0;
    if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 2);
        give_exp_points(floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) + 1);
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 80);
        if (obj_carrying_pid_obj(self_obj, 130)) then begin
            LVar0 := 1;
            rm_obj_from_inven(self_obj, obj_carrying_pid_obj(self_obj, 130));
            add_obj_to_inven(dude_obj, create_object(130, 1, 2));
        end
    end
    if (LVar0 == 1) then begin
        Reply(300);
    end
    else begin
        Reply(302);
    end
    giq_option(1, NAME, 301, Node999, NEUTRAL_REACTION);
end

procedure Node031
begin
    variable LVar0 := 0;
    if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 2);
        give_exp_points(floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) + 3);
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 25);
        if (obj_carrying_pid_obj(self_obj, 130)) then begin
            LVar0 := 1;
            rm_obj_from_inven(self_obj, obj_carrying_pid_obj(self_obj, 130));
            add_obj_to_inven(dude_obj, create_object(130, 1, 2));
        end
    end
    if (LVar0 == 1) then begin
        Reply(310);
    end
    else begin
        Reply(302);
    end
    giq_option(1, NAME, 311, Node999, NEUTRAL_REACTION);
end

procedure Node032
begin
    variable LVar0 := 0;
    if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 2);
        give_exp_points(floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) + 3);
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 25);
        if (obj_carrying_pid_obj(self_obj, 130)) then begin
            LVar0 := 1;
            rm_obj_from_inven(self_obj, obj_carrying_pid_obj(self_obj, 130));
            add_obj_to_inven(dude_obj, create_object(130, 1, 2));
        end
    end
    if (LVar0 == 1) then begin
        Reply(300);
    end
    else begin
        Reply(302);
    end
    giq_option(1, NAME, 321, Node999, NEUTRAL_REACTION);
end

procedure Node033
begin
    Reply(330);
    if (global_var(GVAR_NEW_RENO_WRIGHT_FLAGS) == 2) then begin
        giq_option(1, NAME, 331, Node034, GOOD_REACTION);
    end
    giq_option(1, NAME, 332, Node999, NEUTRAL_REACTION);
end

procedure Node034
begin
    if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 2);
        give_exp_points(floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) + 3);
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 40);
        add_obj_to_inven(dude_obj, create_object(130, 1, 2));
    end
    Reply(340);
    giq_option(1, NAME, 341, Node999, NEUTRAL_REACTION);
end

procedure Node035
begin
    Reply(350);
    giq_option(1, NAME, 351, Node037, NEUTRAL_REACTION);
end

procedure Node036
begin
    if (global_var(GVAR_DEN_SMITTY_PART) != 2) then begin
        set_global_var(GVAR_DEN_SMITTY_PART, 2);
        give_exp_points(floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1208 / 5) + (dude_iq * floor(1208 / 12)) + (dude_luck * floor(1208 / 30)) + (floor(1208 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) + 5);
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 60);
        add_obj_to_inven(dude_obj, create_object(130, 1, 2));
    end
    Reply(360);
    giq_option(1, NAME, 361, Node999, NEUTRAL_REACTION);
end

procedure Node037
begin
    Reply(370);
    if (dude_skill(SKILL_SPEECH) >= 90) then begin
        giq_option(1, NAME, 371, Node038, BAD_REACTION);
    end
    giq_option(1, NAME, 372, Node999, NEUTRAL_REACTION);
end

procedure Node038
begin
    Reply(380);
    giq_option(1, NAME, 381, Node038a, NEUTRAL_REACTION);
end

procedure Node038a
begin
    add_timer_event(self_obj, 7, 3);
    game_ui_disable;
end

procedure Node039
begin
    set_local_var(9, 0);
    game_ui_enable;
    set_global_var(GVAR_NCR_HENRY_HYPO, 1);
    Reply(390);
    giq_option(1, NAME, 391, Node999, NEUTRAL_REACTION);
end

procedure Node040
begin
    set_global_var(GVAR_DEN_SMITTY_PART, 1);
    Reply(400);
    giq_option(1, NAME, 401, Node999, NEUTRAL_REACTION);
end

procedure Node041
begin
    set_global_var(GVAR_NCR_WESTIN_SEED, global_var(GVAR_NCR_WESTIN_SEED) + 1);
    Reply(410);
    giq_option(1, NAME, 411, Node010, NEUTRAL_REACTION);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    if (CUR_MAP_LVTRADE) then begin
        set_map_var(0, 1);
    end
    else begin
        set_local_var(2, 1);
    end
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end
