variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable animation_is_called;
variable float_is_called;
variable already_talk;
variable trading_container;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node012a;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure NodeDieEmily;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node999;
procedure Node998;
procedure NodeBarter;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(70, 80));
        set_local_var(5, random(60, 70));
        set_local_var(6, random(-30, 20));
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 11);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GENTLEMAN_COWARD);
        if (random(0, 100) <= 75) then begin
            add_mult_objs_to_inven(self_obj, create_object(41, 1, 2), random(1, 40));
        end
        if (random(0, 100) <= 45) then begin
            add_obj_to_inven(self_obj, create_object(415, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(419, 1, 2));
        end
        if (random(0, 100) <= 30) then begin
            add_obj_to_inven(self_obj, create_object(434, 1, 2));
        end
        if (random(0, 100) <= 20) then begin
            add_obj_to_inven(self_obj, create_object(145, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(223, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(39, 1, 2));
        end
        if (random(0, 100) <= 15) then begin
            add_obj_to_inven(self_obj, create_object(82, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(228, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(410, 1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(431, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(110, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(323, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(239, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(235, 1, 2));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(15, 30), 1);
    end
    if (float_is_called == 0) then begin
        float_is_called := 1;
        add_timer_event(self_obj, random(1000, 1000), 2);
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(GVAR_TOWN_REP_GECKO) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_mstr(2);
    end
    else begin
        display_mstr(4);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(7) == 0) then begin
        display_mstr(1);
    end
    else begin
        display_mstr(3);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
end

procedure talk_p_proc
begin
    if (local_var(7) == 1) then begin
        if (not(anim_busy(self_obj))) then begin
            anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
        end
    end
    start_gdialog(230, self_obj, -1, -1, -1);
    gsay_start;
    if (local_var(7) == 0) then begin
        call Node001();
    end
    else begin
        call Node010();
    end
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    set_global_var(GVAR_MODOC_TOOL_FLAG, global_var(GVAR_MODOC_TOOL_FLAG) bwor 33554432);
    if ((global_var(GVAR_GECKO_ANKH) == 1) and ((global_var(GVAR_NEW_RENO_MCGEE_SEED) == 2) or (global_var(GVAR_NEW_RENO_MCGEE_SEED) == 1))) then begin
        set_global_var(GVAR_GECKO_ANKH, 0);
    end
    if ((global_var(GVAR_SIERRA_PASSWORD) == 1) and ((global_var(GVAR_NEW_RENO_MCGEE_SEED) == 2) or (global_var(GVAR_NEW_RENO_MCGEE_SEED) == 1))) then begin
        set_global_var(GVAR_SIERRA_PASSWORD, 0);
    end
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
        if ((51 == 50) or (51 == 59)) then begin
            set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) - 3);
        end
        else begin
            set_global_var(GVAR_TOWN_REP_GECKO, global_var(GVAR_TOWN_REP_GECKO) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
                if (global_var(GVAR_VAULT_CITIZENSHIP) < get_pc_stat(PCSTAT_level)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 3);
                    end
                    else begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 1);
                    end
                    if (global_var(GVAR_QUEST_FIND_THOMAS) >= (2 * get_pc_stat(PCSTAT_level))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, 0);
                        set_global_var(GVAR_VAULT_CITIZENSHIP, global_var(GVAR_VAULT_CITIZENSHIP) + 1);
                        critter_mod_skill(dude_obj, SKILL_STEAL, 1);
                        display_msg(message_str(SCRIPT_STTEXT, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(TRAIT_PERK, dude_obj, PERK_pickpocket) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(TRAIT_PERK, dude_obj, PERK_master_thief) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND)) == 245) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(SCRIPT_STTEXT, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((dude_luck - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(SCRIPT_STTEXT, random(206, 209)), FLOAT_MSG_RED);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(SCRIPT_STTEXT, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_STTEXT, 204) + ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(SCRIPT_STTEXT, 205));
    end
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (not(is_loading_game == 1)) then begin
        if (tile_num(self_obj) != local_var(3)) then begin
            move_to(self_obj, local_var(3), elevation(self_obj));
        end
        if (global_var(GVAR_GECKO_ANKH) == 3) then begin
            critter_heal(self_obj, -100);
            if ((global_var(GVAR_GECKO_ANKH) == 1) and ((global_var(GVAR_NEW_RENO_MCGEE_SEED) == 2) or (global_var(GVAR_NEW_RENO_MCGEE_SEED) == 1))) then begin
                set_global_var(GVAR_GECKO_ANKH, 0);
            end
            if ((global_var(GVAR_SIERRA_PASSWORD) == 1) and ((global_var(GVAR_NEW_RENO_MCGEE_SEED) == 2) or (global_var(GVAR_NEW_RENO_MCGEE_SEED) == 1))) then begin
                set_global_var(GVAR_SIERRA_PASSWORD, 0);
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized)) then begin
        float_is_called := 0;
    end
end

procedure Node001
begin
    set_local_var(7, 1);
    already_talk := 1;
    Reply(10);
    giq_option(1, NAME, 11, Node002, NEUTRAL_REACTION);
    giq_option(1, NAME, 12, Node003, NEUTRAL_REACTION);
    giq_option(1, NAME, 13, Node004, NEUTRAL_REACTION);
end

procedure Node002
begin
    Reply(20);
    giq_option(1, NAME, 21, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 22, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    Reply(30);
    giq_option(1, NAME, 31, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 32, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    Reply(40);
    giq_option(1, NAME, 41, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 42, Node999, NEUTRAL_REACTION);
end

procedure Node010
begin
    if (already_talk == 0) then begin
        already_talk := 1;
        if (global_var(GVAR_NCR_ENCLAVE_INFO) == 2) then begin
            Reply(1001);
        end
        else begin
            Reply(1003);
        end
    end
    else begin
        Reply(1002);
    end
    if (global_var(GVAR_GECKO_SKEETER_PART) == 1) then begin
        giq_option(1, NAME, 101, Node011, NEUTRAL_REACTION);
    end
    if (not(global_var(GVAR_NEW_RENO_MCGEE_SEED) == 4)) then begin
        giq_option(1, NAME, 102, Node012, NEUTRAL_REACTION);
        giq_option(1, NAME, 103, Node019, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 109, Node012a, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_GECKO_ANKH) == 1) or ((global_var(GVAR_MODOC_TOOL_FLAG) bwand 16777216) != 0)) then begin
        giq_option(1, NAME, 104, Node020, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_SIERRA_BASE_ENEMY) == 1) and (global_var(GVAR_NEW_RENO_MCGEE_KNOWN) == 0) and (global_var(GVAR_GECKO_ANKH) == 2)) then begin
        giq_option(1, NAME, 105, Node028, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_GECKO_ANKH) == 2) and (global_var(GVAR_SIERRA_PASSWORD) == 0)) then begin
        giq_option(1, NAME, 106, Node029, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_GECKO_ANKH) == 2) and (global_var(GVAR_NCR_GENERIC_STATE) >= 15) and (global_var(GVAR_8_BALL_TRASH_SECRET) == 2) and (global_var(GVAR_SIERRA_PASSWORD) != 2)) then begin
        giq_option(1, NAME, 107, Node034, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 108, Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    Reply(110);
    giq_option(1, NAME, 111, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 112, Node999, NEUTRAL_REACTION);
end

procedure Node012
begin
    Reply(120);
    giq_option(1, NAME, 121, Node013, NEUTRAL_REACTION);
end

procedure Node012a
begin
    Reply(122);
    giq_option(1, NAME, 123, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 124, Node999, NEUTRAL_REACTION);
end

procedure Node013
begin
    Reply(130);
    giq_option(1, NAME, 131, Node014, NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(140);
    giq_option(1, NAME, 141, Node015, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(150);
    if ((global_var(GVAR_GECKO_ANKH) == 0) and not((global_var(GVAR_MODOC_TOOL_FLAG) bwand 16777216) != 0)) then begin
        giq_option(1, NAME, 151, Node016, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 152, Node010, NEUTRAL_REACTION);
end

procedure Node016
begin
    Reply(160);
    giq_option(1, NAME, 161, Node017, NEUTRAL_REACTION);
    giq_option(1, NAME, 162, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 163, Node999, NEUTRAL_REACTION);
end

procedure Node017
begin
    Reply(170);
    giq_option(1, NAME, 171, Node018, NEUTRAL_REACTION);
    giq_option(1, NAME, 172, Node010, NEUTRAL_REACTION);
    giq_option(1, NAME, 173, Node999, NEUTRAL_REACTION);
end

procedure Node018
begin
    if (global_var(GVAR_GECKO_ANKH) == 0) then begin
        set_global_var(GVAR_GECKO_ANKH, 1);
    end
    Reply(180);
    giq_option(1, NAME, 181, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    Reply(190);
    if (global_var(GVAR_GECKO_ANKH) == 0) then begin
        giq_option(1, NAME, 191, Node016, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 192, Node010, NEUTRAL_REACTION);
end

procedure Node020
begin
    if ((global_var(GVAR_GECKO_ANKH) == 2) or ((global_var(GVAR_MODOC_TOOL_FLAG) bwand 16777216) != 0)) then begin
        Reply(2002);
    end
    else begin
        Reply(2001);
    end
    if (not((global_var(GVAR_MODOC_TOOL_FLAG) bwand 16777216) != 0)) then begin
        if (global_var(GVAR_GECKO_ANKH) == 1) then begin
            giq_option(1, NAME, 201, Node021, NEUTRAL_REACTION);
        end
        if ((global_var(GVAR_GECKO_ANKH) == 1) and (dude_skill(SKILL_SPEECH) >= 35)) then begin
            giq_option(1, NAME, 202, Node022, NEUTRAL_REACTION);
        end
    end
    giq_option(1, NAME, 203, Node010, NEUTRAL_REACTION);
    if ((global_var(GVAR_NEW_RENO_MCGEE_SEED) == 1) or (global_var(GVAR_NEW_RENO_MCGEE_SEED) == 2) or ((global_var(GVAR_MODOC_TOOL_FLAG) bwand 16777216) != 0)) then begin
        giq_option(1, NAME, 204, Node025, NEUTRAL_REACTION);
    end
end

procedure Node021
begin
    Reply(210);
    giq_option(1, NAME, 211, Node010, NEUTRAL_REACTION);
end

procedure Node022
begin
    Reply(220);
    if (dude_skill(SKILL_SPEECH) >= 65) then begin
        giq_option(1, NAME, 221, Node023, NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 222, Node010, NEUTRAL_REACTION);
end

procedure Node023
begin
    Reply(230);
    giq_option(1, NAME, 231, Node010, NEUTRAL_REACTION);
    if (dude_skill(SKILL_SPEECH) >= 95) then begin
        giq_option(1, NAME, 232, Node024, NEUTRAL_REACTION);
    end
end

procedure Node024
begin
    set_global_var(GVAR_NEW_RENO_MCGEE_SEED, 4);
    if (global_var(GVAR_GECKO_ANKH) < 2) then begin
        set_global_var(GVAR_GECKO_ANKH, 2);
        give_exp_points(floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 10);
    end
    Reply(240);
    giq_option(1, NAME, 241, NodeDieEmily, NEUTRAL_REACTION);
end

procedure NodeDieEmily
begin
    fadeOut(700);
    move_to(self_obj, 16324, elevation(self_obj));
    set_local_var(3, 16324);
    anim(self_obj, 1000, 4);
    fadeIn(700);
end

procedure Node025
begin
    Reply(250);
    giq_option(1, NAME, 251, Node026, NEUTRAL_REACTION);
    giq_option(1, NAME, 252, Node027, NEUTRAL_REACTION);
end

procedure Node026
begin
    if (global_var(GVAR_GECKO_ANKH) < 2) then begin
        set_global_var(GVAR_GECKO_ANKH, 2);
        give_exp_points(floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 10);
    end
    Reply(260);
    giq_option(1, NAME, 261, Node999, NEUTRAL_REACTION);
end

procedure Node027
begin
    if (global_var(GVAR_GECKO_ANKH) < 2) then begin
        set_global_var(GVAR_GECKO_ANKH, 2);
        give_exp_points(floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1380 / 5) + (dude_iq * floor(1380 / 12)) + (dude_luck * floor(1380 / 30)) + (floor(1380 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 10);
    end
    set_global_var(GVAR_NCR_ENCLAVE_INFO, 2);
    set_global_var(GVAR_KARMA_LIVOS_BOSS, 1);
    Reply(270);
    giq_option(1, NAME, 271, Node999, NEUTRAL_REACTION);
end

procedure Node028
begin
    set_global_var(GVAR_NCR_WESTIN_SEED, 1);
    Reply(280);
    giq_option(1, NAME, 281, Node010, NEUTRAL_REACTION);
end

procedure Node029
begin
    set_global_var(GVAR_SIERRA_PASSWORD, 1);
    Reply(290);
    giq_option(1, NAME, 291, Node030, NEUTRAL_REACTION);
end

procedure Node030
begin
    Reply(300);
    if (not(global_var(GVAR_NEW_RENO_WRIGHT_FLAGS) == 1)) then begin
        if (dude_gender == 0) then begin
            giq_option(1, NAME, 301, Node999, NEUTRAL_REACTION);
        end
        else begin
            giq_option(1, NAME, 302, Node031, NEUTRAL_REACTION);
        end
    end
    else begin
        if (dude_gender == 1) then begin
            giq_option(1, NAME, 303, Node032, NEUTRAL_REACTION);
        end
        else begin
            giq_option(1, NAME, 304, Node033, NEUTRAL_REACTION);
        end
    end
end

procedure Node031
begin
    item_caps_adjust(dude_obj, 100);
    Reply(310);
    giq_option(1, NAME, 311, Node999, NEUTRAL_REACTION);
end

procedure Node032
begin
    item_caps_adjust(dude_obj, 100);
    add_obj_to_inven(dude_obj, create_object(87, 1, 2));
    Reply(320);
    giq_option(1, NAME, 321, Node999, NEUTRAL_REACTION);
end

procedure Node033
begin
    add_obj_to_inven(dude_obj, create_object(87, 1, 2));
    Reply(330);
    giq_option(1, NAME, 331, Node999, NEUTRAL_REACTION);
end

procedure Node034
begin
    if (global_var(GVAR_SIERRA_PASSWORD) != 2) then begin
        set_global_var(GVAR_SIERRA_PASSWORD, 2);
        give_exp_points(floor(1553 / 5) + (dude_iq * floor(1553 / 12)) + (dude_luck * floor(1553 / 30)) + (floor(1553 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4))));
        display_msg(message_str(SCRIPT_STTEXT, random(140, 143)) + (floor(1553 / 5) + (dude_iq * floor(1553 / 12)) + (dude_luck * floor(1553 / 30)) + (floor(1553 / 75) * (((dude_luck - 4) * 4) - (difficulty_level * 4)))) + message_str(SCRIPT_STTEXT, 144));
        add_obj_to_inven(dude_obj, create_object(304, 1, 2));
    end
    Reply(340);
    giq_option(1, NAME, 341, Node999, NEUTRAL_REACTION);
end

procedure Node999
begin
    already_talk := 0;
end

procedure Node998
begin
    already_talk := 0;
    if (CUR_MAP_LVTRADE) then begin
        set_map_var(0, 1);
    end
    else begin
        set_local_var(2, 1);
    end
end

procedure NodeBarter
begin
    gdialog_mod_barter(-(dude_objective_reputation + local_var(6)));
    call Node010();
end
