variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable z_weapon_class;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node001;
procedure Node999;
procedure NodeBarter;

variable max_distance;
variable barter_mod;
variable trading_container;
variable ungry_count1;
variable ungry_count2;
variable floater_is_called;
variable animation_is_called;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(7, obj_get_rot(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(70, 99));
        set_local_var(5, random(30, 80));
        set_local_var(6, random(-10, 10));
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 8);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_SEARCHER);
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(146, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(65, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(108, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(139, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(214, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(63, 1, 2));
        end
        if (random(0, 100) <= 60) then begin
            add_obj_to_inven(self_obj, create_object(67, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(132, 1, 2));
        end
        if (random(0, 100) <= 50) then begin
            add_obj_to_inven(self_obj, create_object(147, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(38, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(226, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(225, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(227, 1, 2));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(2, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(5, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(7, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(9, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(14, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(33, 1, 2), random(1, 3));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(25, 1, 2), random(2, 6));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(20, 1, 2), random(5, 40));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0) and (elevation(self_obj) == 0)) then begin
        animation_is_called := 1;
        add_timer_event(self_obj, random(29, 76), 1);
    end
    if ((tile_num(self_obj) == local_var(3)) and (obj_get_rot(self_obj) != 0) and (anim_busy(self_obj) == 0)) then begin
        anim(self_obj, 1000, 0);
    end
    if ((ungry_count1 >= 10) or (ungry_count2 >= 10)) then begin
        ungry_count1 := 0;
        ungry_count2 := 0;
        set_local_var(2, 1);
    end
    if ((ungry_count1 >= 0) and (tile_distance(tile_num(self_obj), dude_tile) > 3)) then begin
        ungry_count1 := 0;
    end
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(2) == 1) or (global_var(GVAR_TOWN_REP_VAULT_CITY) <= -31)) then begin
            set_local_var(2, 0);
            attack_setup(self_obj, dude_obj);
        end
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(random(6, 9));
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(random(1, 5));
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
    script_overrides;
    ungry_count2 := ungry_count2 + random(2, 4);
    if (ungry_count2 <= 6) then begin
        float_msg(self_obj, mstr(random(25, 29)), FLOAT_MSG_NORMAL);
    end
    else begin
        float_msg(self_obj, mstr(random(25, 29)), FLOAT_MSG_RED);
    end
end

procedure talk_p_proc
begin
    if (not(anim_busy(self_obj))) then begin
        anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
    end
    start_gdialog(211, self_obj, -1, -1, -1);
    gsay_start;
    call Node001();
    gsay_end;
    end_dialogue;
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
        if ((50 == 50) or (50 == 59)) then begin
            set_global_var(GVAR_TOWN_REP_VAULT_CITY, global_var(GVAR_TOWN_REP_VAULT_CITY) - 3);
        end
        else begin
            set_global_var(GVAR_TOWN_REP_VAULT_CITY, global_var(GVAR_TOWN_REP_VAULT_CITY) - 6);
        end
    end
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
                if (global_var(GVAR_VAULT_CITIZENSHIP) < get_pc_stat(PCSTAT_level)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 3);
                    end
                    else begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 1);
                    end
                    if (global_var(GVAR_QUEST_FIND_THOMAS) >= (2 * get_pc_stat(PCSTAT_level))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, 0);
                        set_global_var(GVAR_VAULT_CITIZENSHIP, global_var(GVAR_VAULT_CITIZENSHIP) + 1);
                        critter_mod_skill(dude_obj, SKILL_STEAL, 1);
                        display_msg(message_str(SCRIPT_STTEXT, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(TRAIT_PERK, dude_obj, PERK_pickpocket) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(TRAIT_PERK, dude_obj, PERK_master_thief) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND)) == 245) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(SCRIPT_STTEXT, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((dude_luck - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(SCRIPT_STTEXT, random(206, 209)), FLOAT_MSG_RED);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(SCRIPT_STTEXT, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_STTEXT, 204) + ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(SCRIPT_STTEXT, 205));
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    if (not(tile_contains_obj_pid(1, 2, 250))) then begin
        trading_container := create_object(250, 1, 2);
    end
    else begin
        trading_container := tile_contains_pid_obj(1, 2, 250);
    end
    if ((random(0, 100) <= 60) and tile_contains_obj_pid(22294, 0, 16777339)) then begin
        move_to(self_obj, local_var(3), 0);
    end
    else begin
        move_to(self_obj, local_var(3), 1);
    end
    anim(self_obj, 1000, local_var(7));
    if (days_since_visited > 2) then begin
        move_obj_inven_to_obj(self_obj, trading_container);
        add_mult_objs_to_inven(self_obj, create_object(41, 1, 2), random(10, 200));
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(146, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(65, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(108, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(139, 1, 2));
        end
        if (random(0, 100) <= 40) then begin
            add_obj_to_inven(self_obj, create_object(214, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(63, 1, 2));
        end
        if (random(0, 100) <= 60) then begin
            add_obj_to_inven(self_obj, create_object(67, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(132, 1, 2));
        end
        if (random(0, 100) <= 50) then begin
            add_obj_to_inven(self_obj, create_object(147, 1, 2));
        end
        else begin
            add_obj_to_inven(self_obj, create_object(38, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(226, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(225, 1, 2));
        end
        if (random(0, 100) <= 33) then begin
            add_obj_to_inven(self_obj, create_object(227, 1, 2));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(2, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(5, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(7, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(9, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(14, 1, 2), random(5, 40));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(33, 1, 2), random(1, 3));
        end
        if (random(0, 100) <= 50) then begin
            add_mult_objs_to_inven(self_obj, create_object(25, 1, 2), random(2, 6));
        end
        if (random(0, 100) <= 70) then begin
            add_mult_objs_to_inven(self_obj, create_object(20, 1, 2), random(5, 40));
        end
    end
    max_distance := 8;
    if (random(0, 100) <= 20) then begin
        art_change_fid_num(self_obj, 16777260);
    end
    else begin
        if (random(0, 100) <= 25) then begin
            art_change_fid_num(self_obj, 16777271);
        end
        else begin
            if (random(0, 100) <= 33) then begin
                art_change_fid_num(self_obj, 16777290);
            end
            else begin
                if (random(0, 100) <= 50) then begin
                    art_change_fid_num(self_obj, 16777272);
                end
                else begin
                    art_change_fid_num(self_obj, 16777246);
                end
            end
        end
    end
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        if (tile_num(self_obj) == local_var(3)) then begin
            if (random(0, 100) <= 80) then begin
                if (random(0, 100) <= 60) then begin
                    float_msg(self_obj, mstr(random(1030, 1039)), FLOAT_MSG_NORMAL);
                end
            end
            else begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(21501, random(0, 5), random(0, 4)), 0);
            end
        end
        else begin
            if (random(0, 100) <= 70) then begin
                animate_move_obj_to_tile(self_obj, tile_num_in_direction(21501, random(0, 5), random(0, 7)), 0);
            end
            else begin
                animate_move_obj_to_tile(self_obj, local_var(3), 0);
            end
        end
        animation_is_called := 0;
    end
end

procedure Node001
begin
    Reply(random(10, 12));
    giq_option(1, NAME, random(13, 15), NodeBarter, NEUTRAL_REACTION);
    giq_option(1, NAME, random(16, 18), Node999, NEUTRAL_REACTION);
end

procedure Node999
begin
    anim(self_obj, 1000, local_var(7));
end

procedure NodeBarter
begin
    barter_mod := 50 * (0 - 1);
    gdialog_mod_barter(barter_mod);
    call Node001();
end
