variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;

procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure map_exit_p_proc;
procedure talk_p_proc;
procedure timed_event_p_proc;
procedure switch_comp;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node999;


procedure start
begin
end

procedure description_p_proc
begin
end

procedure look_at_p_proc
begin
end

procedure damage_p_proc
begin
end

procedure use_p_proc
begin
    script_overrides;
    dialogue_system_enter;
end

procedure use_obj_on_p_proc
begin
    if (obj_pid(obj_being_used_with) == 332) then begin
        set_local_var(1, 1);
        dialogue_system_enter;
    end
end

procedure use_skill_on_p_proc
begin
end

procedure map_enter_p_proc
begin
    add_timer_event(self_obj, 10, 1);
end

procedure map_update_p_proc
begin
end

procedure map_exit_p_proc
begin
end

procedure talk_p_proc
begin
    if ((obj_pid(self_obj) == 33557087) or (obj_pid(self_obj) == 33557082) or (obj_pid(self_obj) == 33557089) or (obj_pid(self_obj) == 33557084)) then begin
        display_msg(message_str(SCRIPT_OLZSOLPN, 37));
        set_local_var(1, 0);
    end
    else begin
        start_gdialog(458, self_obj, -1, -1, -1);
        gsay_start;
        if ((local_var(1) == 1) and (tile_num(self_obj) == 24689)) then begin
            if (global_var(GVAR_JET_CARAVAN) == 1) then begin
                call Node002();
            end
            else begin
                call Node010();
            end
        end
        else begin
            call Node001();
        end
        gsay_end;
        end_dialogue;
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        call switch_comp();
        add_timer_event(self_obj, 10, 1);
    end
end

procedure switch_comp
begin
    if ((global_var(GVAR_MEDICINE_CARAVAN) == 0) and (map_var(1) == 0)) then begin
        if ((obj_pid(self_obj) == 33557086) or (obj_pid(self_obj) == 33557083) or (obj_pid(self_obj) == 33557088) or (obj_pid(self_obj) == 33557085) and (elevation(self_obj) == 1)) then begin
            move_to(self_obj, tile_num(self_obj), 0);
        end
        else begin
            if ((obj_pid(self_obj) == 33557087) or (obj_pid(self_obj) == 33557082) or (obj_pid(self_obj) == 33557089) or (obj_pid(self_obj) == 33557084) and (elevation(self_obj) == 0)) then begin
                move_to(self_obj, tile_num(self_obj), 1);
            end
        end
    end
    else begin
        if ((obj_pid(self_obj) == 33557086) or (obj_pid(self_obj) == 33557083) or (obj_pid(self_obj) == 33557088) or (obj_pid(self_obj) == 33557085) and (elevation(self_obj) == 0)) then begin
            move_to(self_obj, tile_num(self_obj), 1);
        end
        else begin
            if ((obj_pid(self_obj) == 33557087) or (obj_pid(self_obj) == 33557082) or (obj_pid(self_obj) == 33557089) or (obj_pid(self_obj) == 33557084) and (elevation(self_obj) == 1)) then begin
                move_to(self_obj, tile_num(self_obj), 0);
            end
        end
    end
end

procedure Node001
begin
    gsay_reply(SCRIPT_OLZSOLPN, 28);
    giq_option(1, SCRIPT_OLZSOLPN, 29, Node999, NEUTRAL_REACTION);
end

procedure Node002
begin
    gsay_reply(SCRIPT_OLZSOLPN, 30);
    giq_option(1, SCRIPT_OLZSOLPN, 31, Node003, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 32, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    if (global_var(GVAR_JET_CARAVAN) == 1) then begin
        set_global_var(GVAR_JET_CARAVAN, 0);
    end
    gsay_reply(SCRIPT_OLZSOLPN, 33);
    giq_option(1, SCRIPT_OLZSOLPN, 101, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 34, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    gsay_reply(SCRIPT_OLZSOLPN, 35);
    giq_option(1, SCRIPT_OLZSOLPN, 36, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
end

procedure Node010
begin
    gsay_reply(SCRIPT_OLZSOLPN, 100);
    giq_option(1, SCRIPT_OLZSOLPN, 101, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 102, Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    gsay_reply(SCRIPT_OLZSOLPN, 110);
    giq_option(1, SCRIPT_OLZSOLPN, 111, Node012, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 112, Node013, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 113, Node014, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 114, Node015, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 115, Node999, NEUTRAL_REACTION);
end

procedure Node012
begin
    gsay_reply(SCRIPT_OLZSOLPN, 120);
    giq_option(1, SCRIPT_OLZSOLPN, 121, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 122, Node999, NEUTRAL_REACTION);
end

procedure Node013
begin
    gsay_reply(SCRIPT_OLZSOLPN, 130);
    giq_option(1, SCRIPT_OLZSOLPN, 131, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 132, Node999, NEUTRAL_REACTION);
end

procedure Node014
begin
    gsay_reply(SCRIPT_OLZSOLPN, 140);
    giq_option(1, SCRIPT_OLZSOLPN, 141, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 142, Node999, NEUTRAL_REACTION);
end

procedure Node015
begin
    gsay_reply(SCRIPT_OLZSOLPN, 150);
    giq_option(1, SCRIPT_OLZSOLPN, 151, Node011, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_OLZSOLPN, 152, Node999, NEUTRAL_REACTION);
end

procedure Node999
begin
end
