variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;

procedure start;
procedure description_p_proc;
procedure look_at_p_proc;
procedure damage_p_proc;
procedure use_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure timed_event_p_proc;


procedure start
begin
end

procedure description_p_proc
begin
    script_overrides;
    if (map_var(0) == 0) then begin
        display_mstr(3);
    end
    else begin
        display_mstr(4);
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (map_var(0) == 0) then begin
        display_mstr(1);
    end
    else begin
        display_mstr(2);
    end
end

procedure damage_p_proc
begin
end

procedure use_p_proc
begin
    script_overrides;
    if (map_var(0) == 0) then begin
        if ((global_var(GVAR_NEW_RENO_WRIGHT_FLAGS) == 3) and (global_var(GVAR_MUTATE) == 1)) then begin
            display_mstr(7);
            set_map_var(0, 1);
            set_local_var(1, 1);
        end
        else begin
            display_mstr(random(5, 6));
        end
    end
    else begin
        display_mstr(8);
    end
end

procedure use_obj_on_p_proc
begin
    display_msg(message_str(SCRIPT_STTEXT, random(60, 69)));
end

procedure use_skill_on_p_proc
begin
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
end

procedure timed_event_p_proc
begin
end
