variable dude_objective_reputation;
variable self_subjective_reaction;
variable z_critter_search;
variable critter_is_detected;
variable detected_critter;
variable persuade_chance;
variable steal_perk;
variable steal_gloves;
variable max_distance;
variable animation_is_called;
variable distance_to_walk;
variable run_to_dude;

procedure start;
procedure critter_p_proc;
procedure combat_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;
procedure pickup_p_proc;
procedure push_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;


procedure start
begin
    if (local_var(1) == 0) then begin
        set_local_var(3, tile_num(self_obj));
        set_local_var(1, 1);
        set_local_var(4, random(40, 60));
        set_local_var(5, random(0, 100));
        set_local_var(6, random(-10, 10));
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 13);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_MAN_WEAK);
        max_distance := random(15, 20);
        if (random(0, 100) <= 15) then begin
            add_mult_objs_to_inven(self_obj, create_object(41, 1, 2), random(1, 10));
        end
        if (random(0, 100) <= 5) then begin
            add_mult_objs_to_inven(self_obj, create_object(220, 1, 2), random(1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_mult_objs_to_inven(self_obj, create_object(217, 1, 2), random(1, 2));
        end
        if (random(0, 100) <= 10) then begin
            add_obj_to_inven(self_obj, create_object(36, 1, 2));
        end
        if (random(0, 100) <= 9) then begin
            add_obj_to_inven(self_obj, create_object(65, 1, 2));
        end
        if (random(0, 100) <= 7) then begin
            add_obj_to_inven(self_obj, create_object(71, 1, 2));
        end
        if (random(0, 100) <= 6) then begin
            add_obj_to_inven(self_obj, create_object(138, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(47, 1, 2));
        end
        if (random(0, 100) <= 5) then begin
            add_obj_to_inven(self_obj, create_object(420, 1, 2));
        end
        if (random(0, 100) <= 4) then begin
            add_obj_to_inven(self_obj, create_object(243, 1, 2));
        end
        if (random(0, 100) <= 3) then begin
            add_obj_to_inven(self_obj, create_object(423, 1, 2));
        end
        if (random(0, 100) <= 2) then begin
            add_obj_to_inven(self_obj, create_object(426, 1, 2));
        end
        if (random(0, 100) <= 1) then begin
            add_obj_to_inven(self_obj, create_object(110, 1, 2));
        end
        if (random(0, 100) <= 1) then begin
            add_obj_to_inven(self_obj, create_object(421, 1, 2));
        end
        if (random(0, 100) <= 1) then begin
            add_obj_to_inven(self_obj, create_object(427, 1, 2));
        end
        if (random(0, 100) <= 1) then begin
            add_obj_to_inven(self_obj, create_object(77, 1, 2));
        end
    end
end

procedure critter_p_proc
begin
    if ((animation_is_called == 0) and (anim_busy(self_obj) == 0) and not(obj_can_see_obj(self_obj, dude_obj))) then begin
        animation_is_called := 1;
        if (random(0, 100) <= 50) then begin
            add_timer_event(self_obj, random(1, 100), 1);
        end
        else begin
            add_timer_event(self_obj, random(1, 30), 2);
        end
    end
    if (obj_can_see_obj(self_obj, dude_obj) and (local_var(2) == 1)) then begin
        set_local_var(2, 0);
        attack_setup(self_obj, dude_obj);
    end
    if ((tile_distance(tile_num(self_obj), dude_tile) <= 1) and (run_to_dude == 1)) then begin
        float_msg(self_obj, mstr(random(1010, 1019)), FLOAT_MSG_NORMAL);
        run_to_dude := 0;
    end
end

procedure combat_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(random(6, 9));
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(random(1, 5));
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure push_p_proc
begin
    script_overrides;
    reg_anim_func(2, self_obj);
    reg_anim_func(1, 1);
    if (random(1, 2) == 1) then begin
        reg_anim_animate(self_obj, 20, -1);
        reg_anim_animate(self_obj, 37, -1);
    end
    else begin
        reg_anim_animate(self_obj, 21, -1);
        reg_anim_animate(self_obj, 36, -1);
    end
    play_sfx("HMXXXXBB");
    reg_anim_func(3, 0);
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 1);
end

procedure talk_p_proc
begin
    float_msg(self_obj, mstr(random(1000, 1009)), FLOAT_MSG_NORMAL);
end

procedure destroy_p_proc
begin
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - random(2, 3));
end

procedure use_skill_on_p_proc
begin
    if (action_being_used == 10) then begin
        if ((get_sfall_global_int(1) == 6) and (get_sfall_global_int(13) == 0)) then begin
            script_overrides;
            set_sfall_global(13, 1);
        end
        else begin
            if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
                if (global_var(GVAR_VAULT_CITIZENSHIP) < get_pc_stat(PCSTAT_level)) then begin
                    if (is_success(roll_vs_skill(dude_obj, 10, 0))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 3);
                    end
                    else begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, global_var(GVAR_QUEST_FIND_THOMAS) + 1);
                    end
                    if (global_var(GVAR_QUEST_FIND_THOMAS) >= (2 * get_pc_stat(PCSTAT_level))) then begin
                        set_global_var(GVAR_QUEST_FIND_THOMAS, 0);
                        set_global_var(GVAR_VAULT_CITIZENSHIP, global_var(GVAR_VAULT_CITIZENSHIP) + 1);
                        critter_mod_skill(dude_obj, SKILL_STEAL, 1);
                        display_msg(message_str(SCRIPT_STTEXT, 410));
                    end
                end
            end
            steal_perk := 0;
            steal_gloves := 0;
            if (has_trait(TRAIT_PERK, dude_obj, PERK_pickpocket) != 0) then begin
                steal_perk := steal_perk + 15;
            end
            if (has_trait(TRAIT_PERK, dude_obj, PERK_master_thief) != 0) then begin
                steal_perk := steal_perk + 30;
            end
            if ((obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND)) == 245) or (obj_pid(critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND)) == 245)) then begin
                steal_gloves := 10;
            end
            if (random(0, 100) <= ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25)))) then begin
                display_msg(message_str(SCRIPT_STTEXT, random(145, 148)));
            end
            else begin
                script_overrides;
                if (random(0, 100) <= (25 - floor((((dude_luck - 4) * 4) - (difficulty_level * 4)) / 3))) then begin
                    float_msg(self_obj, message_str(SCRIPT_STTEXT, random(206, 209)), FLOAT_MSG_RED);
                    set_local_var(2, 1);
                end
                else begin
                    display_msg(message_str(SCRIPT_STTEXT, random(200, 203)));
                end
            end
        end
    end
    if (action_being_used == 12) then begin
        script_overrides;
        display_msg(message_str(SCRIPT_STTEXT, 204) + ((dude_skill(SKILL_STEAL) / 2) + (((3 * get_critter_stat(dude_obj, STAT_ag)) + (((dude_luck - 4) * 4) - (difficulty_level * 4)) + (2 * steal_perk) + steal_gloves) / (local_var(4) / 25))) + message_str(SCRIPT_STTEXT, 205));
    end
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(2, 1);
    end
end

procedure map_enter_p_proc
begin
    max_distance := random(15, 20);
end

procedure timed_event_p_proc
begin
    if ((fixed_param == 1) and not(combat_is_initialized)) then begin
        if (tile_distance(tile_num(self_obj), local_var(3)) < max_distance) then begin
            reg_anim_func(2, self_obj);
            reg_anim_func(1, 1);
            reg_anim_obj_move_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), random(0, 5), random(5, 12)), -1);
            reg_anim_func(3, 0);
        end
        else begin
            if (tile_num(self_obj) != tile_num_in_direction(local_var(3), random(0, 5), random(2, 10))) then begin
                reg_anim_func(2, self_obj);
                reg_anim_func(1, 1);
                if (tile_distance(tile_num(self_obj), tile_num_in_direction(local_var(3), random(0, 5), random(2, 10))) >= 25) then begin
                    reg_anim_obj_move_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), rotation_to_tile(tile_num(self_obj), tile_num_in_direction(local_var(3), random(0, 5), random(2, 10))), random(12, 22)), -1);
                end
                else begin
                    reg_anim_obj_move_to_tile(self_obj, tile_num_in_direction(local_var(3), random(0, 5), random(2, 10)), -1);
                end
                reg_anim_func(3, 0);
            end
        end
        run_to_dude := 0;
        animation_is_called := 0;
    end
    if ((fixed_param == 2) and not(combat_is_initialized) and obj_can_see_obj(self_obj, dude_obj) and (tile_distance(tile_num(self_obj), dude_tile) <= 10)) then begin
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_obj_run_to_tile(self_obj, dude_tile, -1);
        reg_anim_func(3, 0);
        run_to_dude := 1;
        animation_is_called := 0;
    end
end
