procedure start;
procedure timed_event_p_proc;


procedure start
begin
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        float_msg(self_obj, message_str(1304, 400), -2);
        add_timer_event(dude_obj, game_ticks(15), 3);
    end
    else begin
        if (fixed_param == 2) then begin
            float_msg(self_obj, message_str(1304, 402), -2);
            add_timer_event(dude_obj, game_ticks(10), 3);
        end
        else begin
            if (fixed_param == 3) then begin
                play_gmovie(7);
                metarule(13, 0);
            end
        end
    end
end

