procedure start;
procedure do_dialogue;

variable HOSTILE;
variable only_once := 1;


procedure start
begin
    if (only_once) then begin
        only_once := 0;
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 34);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_SUPER_MUTANT_GUARD);
    end
    else begin
        if (script_action == damage_proc) then begin
            if (global_var(GVAR_ENEMY_VAULT_13) == 0) then begin
                set_global_var(GVAR_ENEMY_VAULT_13, 1);
            end
        end
        else begin
            if (script_action == talk_proc) then begin
                call do_dialogue();
            end
            else begin
                if (script_action == pickup_proc) then begin
                    HOSTILE := 1;
                end
            end
        end
    end
    if (script_action == critter_proc) then begin
        if (HOSTILE) then begin
            HOSTILE := 0;
            attack(dude_obj);
        end
    end
    else begin
        if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
            script_overrides;
        end
        else begin
            if (script_action == destroy_proc) then begin
                if (source_obj == dude_obj) then begin
                    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
                        set_global_var(GVAR_BERSERKER_REPUTATION, 1);
                        set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                    end
                    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
                        set_global_var(GVAR_CHAMPION_REPUTATION, 1);
                        set_global_var(GVAR_BERSERKER_REPUTATION, 0);
                    end
                    set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
                    if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
                        set_global_var(GVAR_PLAYER_REPUATION, global_var(GVAR_PLAYER_REPUATION) + 1);
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    float_msg(self_obj, message_str(SCRIPT_AIRGRD, 143), FLOAT_MSG_RED);
end
