procedure start;
procedure do_dialogue;
procedure groundr00;
procedure groundr01;
procedure Critter_Action;
procedure timetomove;

variable Hostile;
variable init;
variable maxleash := 9;
variable noevent;
variable loopcount;
variable rndx;
variable rndy;
variable rndz;
variable dist;
variable sleep_tile;
variable new_tile;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;

procedure set_sleep_tile;


procedure start
begin
    if (not(init)) then begin
        if (local_var(6) == 0) then begin
            set_local_var(6, tile_num(self_obj));
            set_local_var(5, 1);
        end
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 31);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_GHOUL_COWARD);
        init := 1;
    end
    if (script_action == timed_event_proc) then begin
        call timetomove();
    end
    else begin
        if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
            script_overrides;
            display_mstr(100);
        end
        else begin
            if (script_action == talk_proc) then begin
                call do_dialogue();
            end
            else begin
                if (script_action == pickup_proc) then begin
                    Hostile := 1;
                end
                else begin
                    if (script_action == critter_proc) then begin
                        call Critter_Action();
                    end
                    else begin
                        if (script_action == destroy_proc) then begin
                            if (source_obj == dude_obj) then begin
                                if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
                                    set_global_var(GVAR_BERSERKER_REPUTATION, 1);
                                    set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                                end
                                if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
                                    set_global_var(GVAR_CHAMPION_REPUTATION, 1);
                                    set_global_var(GVAR_BERSERKER_REPUTATION, 0);
                                end
                                set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
                                if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
                                    set_global_var(GVAR_PLAYER_REPUATION, global_var(GVAR_PLAYER_REPUATION) - 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    call get_reaction();
    if (local_var(1) < 2) then begin
        call groundr01();
    end
    else begin
        call groundr00();
    end
end

procedure groundr00
begin
    float_msg(self_obj, mstr(random(101, 104)), FLOAT_MSG_NORMAL);
end

procedure groundr01
begin
    float_msg(self_obj, mstr(random(105, 107)), FLOAT_MSG_NORMAL);
end

procedure Critter_Action
begin
    if (Hostile > 0) then begin
        Hostile := 0;
        attack(dude_obj);
    end
    else begin
        if (local_var(5)) then begin
            loopcount := loopcount + 1;
            if (loopcount > 40) then begin
                loopcount := 0;
                if (noevent == 0) then begin
                    noevent := 1;
                    add_timer_event(self_obj, game_ticks(random(5, 13)), 0);
                end
            end
        end
    end
end

procedure timetomove
begin
    noevent := 0;
    set_local_var(7, tile_num(self_obj));
    new_tile := tile_num_in_direction(local_var(7), random(0, 5), 2);
    if (tile_distance(local_var(6), new_tile) < maxleash) then begin
        animate_move_obj_to_tile(self_obj, new_tile, 0);
    end
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_PLAYER_REPUATION) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
        end
        if (global_var(GVAR_CHILDKILLER_REPUATION) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end

procedure set_sleep_tile
begin
    if (local_var(6) == 21943) then begin
        sleep_tile := 21143;
    end
    else begin
        if (local_var(6) == 21541) then begin
            sleep_tile := 20537;
        end
        else begin
            if (local_var(6) == 21740) then begin
                sleep_tile := 20735;
            end
        end
    end
end
