procedure start;
procedure combat;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure flee_dude;
procedure damage_p_proc;
procedure Flower00;
procedure Flower01;
procedure Flower02;
procedure Flower03;
procedure Flower03a;
procedure Flower04;
procedure Flower04a;
procedure Flower05;
procedure Flower05a;
procedure Flower06;
procedure Flower07;
procedure Flower08;
procedure Flower09;
procedure Flower10;
procedure Flower11;
procedure Flower12;
procedure Flower13;
procedure Flower14;

variable hostile;
variable Only_Once := 1;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;


procedure start
begin
    if (Only_Once) then begin
        Only_Once := 0;
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 72);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_LITTLE_KIDS);
    end
    if (script_action == look_at_proc) then begin
        call look_at_p_proc();
    end
    else begin
        if (script_action == pickup_proc) then begin
            call pickup_p_proc();
        end
        else begin
            if (script_action == talk_proc) then begin
                call talk_p_proc();
            end
            else begin
                if (script_action == critter_proc) then begin
                    call critter_p_proc();
                end
                else begin
                    if (script_action == destroy_proc) then begin
                        call destroy_p_proc();
                    end
                end
            end
        end
    end
end

procedure combat
begin
    hostile := 1;
end

procedure critter_p_proc
begin
    if (hostile) then begin
        hostile := 0;
        attack(dude_obj);
    end
    if ((map_var(6) == 1) and (obj_can_see_obj(self_obj, dude_obj) == 1)) then begin
        critter_set_flee_state(self_obj, 1);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        hostile := 1;
    end
end

procedure talk_p_proc
begin
    call get_reaction();
    if ((global_var(GVAR_CATHEDRAL_ENEMY) == 1) or (map_var(0) == 1)) then begin
        call Flower00();
    end
    else begin
        if (global_var(GVAR_CHILDKILLER_REPUATION) == 1) then begin
            call Flower01();
        end
        else begin
            if (obj_is_carrying_obj_pid(dude_obj, 117) == 1) then begin
                float_msg(self_obj, mstr(114), FLOAT_MSG_RED);
            end
            else begin
                start_gdialog(588, self_obj, 4, -1, -1);
                gsay_start;
                call Flower02();
                gsay_end;
                end_dialogue;
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_CHILDKILLER_REPUATION, global_var(GVAR_CHILDKILLER_REPUATION) + 1);
        set_global_var(GVAR_PLAYER_REPUATION, global_var(GVAR_PLAYER_REPUATION) - 1);
    end
    if (source_obj == dude_obj) then begin
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if ((global_var(GVAR_GOOD_MONSTER) % 2) == 0) then begin
            set_global_var(GVAR_PLAYER_REPUATION, global_var(GVAR_PLAYER_REPUATION) - 1);
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure flee_dude
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    while (LVar1 < 5) do begin
        if (tile_distance(dude_tile, tile_num_in_direction(tile_num(self_obj), LVar1, 3)) > LVar2) then begin
            LVar0 := tile_num_in_direction(tile_num(self_obj), LVar1, 3);
            LVar2 := tile_distance(dude_tile, LVar0);
        end
        LVar1 := LVar1 + 1;
    end
    animate_move_obj_to_tile(self_obj, LVar0, 0);
end

procedure damage_p_proc
begin
    variable LVar0 := 0;
    LVar0 := obj_pid(source_obj);
    if (party_member_obj(LVar0) != 0) then begin
        set_map_var(6, 1);
    end
end

procedure Flower00
begin
    float_msg(self_obj, mstr(101), FLOAT_MSG_RED);
    call flee_dude();
end

procedure Flower01
begin
    float_msg(self_obj, mstr(102), FLOAT_MSG_RED);
    call flee_dude();
end

procedure Flower02
begin
    if (dude_gender == 0) then begin
        Reply(103);
    end
    else begin
        Reply(104);
    end
    giq_option(7, NAME, 106, Flower03, NEUTRAL_REACTION);
    giq_option(7, NAME, 107, Flower04, NEUTRAL_REACTION);
    giq_option(4, NAME, 108, Flower05, NEUTRAL_REACTION);
    giq_option(4, NAME, 109, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 110, Flower07, BAD_REACTION);
    giq_option(4, NAME, 111, Flower07, BAD_REACTION);
    giq_option(-3, NAME, 112, Flower08, GOOD_REACTION);
    giq_option(-3, NAME, 113, Flower09, BAD_REACTION);
end

procedure Flower03
begin
    Reply(115);
    giq_option(7, NAME, 116, Flower03a, GOOD_REACTION);
    giq_option(7, NAME, 107, Flower04, NEUTRAL_REACTION);
    giq_option(4, NAME, 109, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 110, Flower07, BAD_REACTION);
    giq_option(4, NAME, 119, Flower07, BAD_REACTION);
end

procedure Flower03a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, 20)) == 1) then begin
        call Flower10();
    end
    else begin
        call Flower11();
    end
end

procedure Flower04
begin
    Reply(121);
    giq_option(7, NAME, 123, Flower12, NEUTRAL_REACTION);
    giq_option(7, NAME, 124, Flower04a, GOOD_REACTION);
    giq_option(4, NAME, 125, Flower05, NEUTRAL_REACTION);
    giq_option(4, NAME, 126, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 110, Flower07, BAD_REACTION);
    giq_option(4, NAME, 119, Flower07, BAD_REACTION);
end

procedure Flower04a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, 0)) == 1) then begin
        call Flower13();
    end
    else begin
        call Flower11();
    end
end

procedure Flower05
begin
    Reply(129);
    giq_option(7, NAME, 130, Flower05a, GOOD_REACTION);
    giq_option(7, NAME, 131, Flower04a, GOOD_REACTION);
    giq_option(4, NAME, 132, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 110, Flower07, BAD_REACTION);
    giq_option(4, NAME, 119, Flower07, BAD_REACTION);
end

procedure Flower05a
begin
    if (is_success(roll_vs_skill(dude_obj, 14, 0)) == 1) then begin
        call Flower14();
    end
    else begin
        call Flower11();
    end
end

procedure Flower06
begin
    variable LVar0 := 0;
    LVar0 := create_object(117, 0, 0);
    add_obj_to_inven(dude_obj, LVar0);
    gsay_message(NAME, 135, GOOD_REACTION);
end

procedure Flower07
begin
    gsay_message(NAME, 136, BAD_REACTION);
    call flee_dude();
end

procedure Flower08
begin
    variable LVar0 := 0;
    LVar0 := create_object(117, 0, 0);
    add_obj_to_inven(dude_obj, LVar0);
    gsay_message(NAME, 137, GOOD_REACTION);
end

procedure Flower09
begin
    gsay_message(NAME, 138, BAD_REACTION);
    call flee_dude();
end

procedure Flower10
begin
    variable LVar0 := 0;
    LVar0 := create_object(117, 0, 0);
    add_obj_to_inven(dude_obj, LVar0);
    gsay_message(NAME, 139, GOOD_REACTION);
end

procedure Flower11
begin
    gsay_message(NAME, 140, BAD_REACTION);
    call flee_dude();
end

procedure Flower12
begin
    Reply(141);
    giq_option(7, NAME, 142, Flower05a, NEUTRAL_REACTION);
    giq_option(7, NAME, 143, Flower04a, NEUTRAL_REACTION);
    giq_option(4, NAME, 144, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 145, Flower07, BAD_REACTION);
    giq_option(4, NAME, 146, Flower07, BAD_REACTION);
end

procedure Flower13
begin
    Reply(147);
    giq_option(7, NAME, 148, Flower11, NEUTRAL_REACTION);
    giq_option(4, NAME, 149, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 150, Flower07, BAD_REACTION);
    giq_option(4, NAME, 151, Flower07, BAD_REACTION);
end

procedure Flower14
begin
    set_global_var(GVAR_DESTROY_VATS_9, 1);
    Reply(152);
    giq_option(7, NAME, 153, Flower11, NEUTRAL_REACTION);
    giq_option(4, NAME, 154, Flower06, GOOD_REACTION);
    giq_option(4, NAME, 155, Flower07, BAD_REACTION);
    giq_option(4, NAME, 151, Flower07, BAD_REACTION);
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_PLAYER_REPUATION) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
        end
        if (global_var(GVAR_CHILDKILLER_REPUATION) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end
