procedure start;
procedure do_dialogue;

variable rndx;


procedure start
begin
    variable LVar0 := 0;
    if (script_action == talk_proc) then begin
        call do_dialogue();
        detach;
    end
    else begin
        if (script_action == critter_proc) then begin
            detach;
        end
        else begin
            if (script_action == combat_proc) then begin
                detach;
            end
        end
    end
end

procedure do_dialogue
begin
    rndx := random(1, 3);
    start_dialogue(self_obj, 4);
    sayStart;
    if (rndx == 1) then begin
        sayMessage(0, "Go away.");
    end
    if (rndx == 2) then begin
        sayMessage(0, "I don't like your kind.");
    end
    if (rndx == 3) then begin
        sayMessage(0, "If you have a problem with Set, you have a problem with me.");
    end
    sayEnd;
    end_dialogue;
end
