procedure start;
procedure use_stuff;
procedure pick_lock;

variable unlocked;


procedure start
begin
    if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
        script_overrides;
        display_mstr(100);
    end
    else begin
        if (script_action == use_proc) then begin
            call use_stuff();
        end
        else begin
            if (script_action == use_obj_on_proc) then begin
                if (obj_pid(obj_being_used_with) == 77) then begin
                    call pick_lock();
                end
            end
        end
    end
end

procedure use_stuff
begin
    if (not(unlocked)) then begin
        script_overrides;
        display_mstr(101);
    end
end

procedure pick_lock
begin
    script_overrides;
    if (unlocked) then begin
        display_mstr(102);
    end
    else begin
        if (is_success(roll_vs_skill(dude_obj, 9, -20))) then begin
            display_mstr(103);
            unlocked := 1;
        end
        else begin
            display_mstr(104);
        end
    end
end
