procedure start;
procedure do_dialogue;
procedure robot00;
procedure robot01;
procedure robot02;
procedure robotend;
procedure robotcbt;

variable HOSTILE;
variable only_once := 1;
variable DISGUISED;
variable again;
variable rndx;

procedure get_reaction;
procedure ReactToLevel;
procedure LevelToReact;
procedure UpReact;
procedure DownReact;
procedure BottomReact;
procedure TopReact;
procedure BigUpReact;
procedure BigDownReact;
procedure UpReactLevel;
procedure DownReactLevel;
procedure Goodbyes;

variable exit_line;


procedure start
begin
    if (only_once) then begin
        only_once := 0;
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 55);
        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_ROBOTS);
    end
    else begin
        if (script_action == talk_proc) then begin
            call do_dialogue();
        end
        else begin
            if (script_action == pickup_proc) then begin
                HOSTILE := 1;
            end
        end
    end
    if (script_action == critter_proc) then begin
        if (HOSTILE) then begin
            HOSTILE := 0;
            attack(dude_obj);
        end
        if (obj_can_see_obj(self_obj, dude_obj)) then begin
            DISGUISED := 0;
            if (obj_pid(critter_inven_obj(dude_obj, 0)) == 113) then begin
                if (party_member_count(0) > 1) then begin
                    DISGUISED := 0;
                end
                else begin
                    DISGUISED := 1;
                end
            end
            if ((DISGUISED == 0) and (again == 0)) then begin
                if (tile_distance_objs(self_obj, dude_obj) < 6) then begin
                    again := 1;
                    dialogue_system_enter;
                end
            end
        end
    end
    else begin
        if ((script_action == look_at_proc) or (script_action == description_proc)) then begin
            script_overrides;
        end
        else begin
            if (script_action == destroy_proc) then begin
                if (source_obj == dude_obj) then begin
                    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
                        set_global_var(GVAR_BERSERKER_REPUTATION, 1);
                        set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                    end
                    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
                        set_global_var(GVAR_CHAMPION_REPUTATION, 1);
                        set_global_var(GVAR_BERSERKER_REPUTATION, 0);
                    end
                    set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
                    if ((global_var(GVAR_BAD_MONSTER) % 6) == 0) then begin
                        set_global_var(GVAR_PLAYER_REPUATION, global_var(GVAR_PLAYER_REPUATION) + 1);
                    end
                end
            end
        end
    end
end

procedure do_dialogue
begin
    set_local_var(3, 1);
    call get_reaction();
    if (obj_pid(critter_inven_obj(dude_obj, 0)) == 113) then begin
        if (party_member_count(0) > 1) then begin
            DISGUISED := 0;
        end
        else begin
            DISGUISED := 1;
        end
    end
    if (DISGUISED) then begin
        if (local_var(1) > 1) then begin
            call robot00();
        end
        else begin
            call robot02();
        end
    end
    else begin
        call robot01();
    end
end

procedure robot00
begin
    float_msg(self_obj, mstr(100), FLOAT_MSG_RED);
end

procedure robot01
begin
    rndx := random(1, 4);
    if (rndx == 1) then begin
        float_msg(self_obj, mstr(101), FLOAT_MSG_RED);
    end
    else begin
        if (rndx == 2) then begin
            float_msg(self_obj, mstr(102), FLOAT_MSG_RED);
        end
        else begin
            if (rndx == 3) then begin
                float_msg(self_obj, mstr(103), FLOAT_MSG_RED);
            end
            else begin
                if (rndx == 4) then begin
                    float_msg(self_obj, mstr(104), FLOAT_MSG_RED);
                end
            end
        end
    end
    call robotcbt();
end

procedure robot02
begin
    float_msg(self_obj, mstr(105), FLOAT_MSG_RED);
    call robotcbt();
end

procedure robotend
begin
end

procedure robotcbt
begin
    HOSTILE := 1;
end

procedure get_reaction
begin
    if (local_var(2) == 0) then begin
        set_local_var(0, 50);
        set_local_var(1, 2);
        set_local_var(2, 1);
        set_local_var(0, local_var(0) + (5 * dude_charisma) - 25);
        set_local_var(0, local_var(0) + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence)));
        if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
            if (global_var(GVAR_PLAYER_REPUATION) > 0) then begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
        end
        else begin
            if (local_var(3) == 1) then begin
                set_local_var(0, local_var(0) - global_var(GVAR_PLAYER_REPUATION));
            end
            else begin
                set_local_var(0, local_var(0) + global_var(GVAR_PLAYER_REPUATION));
            end
        end
        if (global_var(GVAR_CHILDKILLER_REPUATION) > 2) then begin
            set_local_var(0, local_var(0) - 30);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(160) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) + 20);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_local_var(0, local_var(0) - 20);
        end
        call ReactToLevel();
    end
end

procedure ReactToLevel
begin
    if (local_var(0) <= 25) then begin
        set_local_var(1, 1);
    end
    else begin
        if (local_var(0) <= 75) then begin
            set_local_var(1, 2);
        end
        else begin
            set_local_var(1, 3);
        end
    end
end

procedure LevelToReact
begin
    if (local_var(1) == 1) then begin
        set_local_var(0, random(1, 25));
    end
    else begin
        if (local_var(1) == 2) then begin
            set_local_var(0, random(26, 75));
        end
        else begin
            set_local_var(0, random(76, 100));
        end
    end
end

procedure UpReact
begin
    set_local_var(0, local_var(0) + 10);
    call ReactToLevel();
end

procedure DownReact
begin
    set_local_var(0, local_var(0) - 10);
    call ReactToLevel();
end

procedure BottomReact
begin
    set_local_var(1, 1);
    set_local_var(0, 1);
end

procedure TopReact
begin
    set_local_var(0, 100);
    set_local_var(1, 3);
end

procedure BigUpReact
begin
    set_local_var(0, local_var(0) + 25);
    call ReactToLevel();
end

procedure BigDownReact
begin
    set_local_var(0, local_var(0) - 25);
    call ReactToLevel();
end

procedure UpReactLevel
begin
    set_local_var(1, local_var(1) + 1);
    if (local_var(1) > 3) then begin
        set_local_var(1, 3);
    end
    call LevelToReact();
end

procedure DownReactLevel
begin
    set_local_var(1, local_var(1) - 1);
    if (local_var(1) < 1) then begin
        set_local_var(1, 1);
    end
    call LevelToReact();
end

procedure Goodbyes
begin
    exit_line := message_str(SCRIPT_MODREACT, random(100, 105));
end
