procedure start;

variable temp;


procedure start
begin
    if (script_action == spatial_proc) then begin
        if (source_obj == dude_obj) then begin
            if (local_var(0) < 1) then begin
                set_local_var(0, 1);
                display_mstr(101);
                display_mstr(100);
                give_exp_points(500);
                display_msg(mstr(102) + 500 + mstr(103));
            end
        end
    end
end
