variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure ..............;

variable ProtoOfItemGiven;
variable ValueOfRollCheck;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure EvaluateKarma;
procedure CheckRep;

variable pointer;
variable Flag;
variable Float_Stage;
variable Drug;
variable Period;
variable Battle_Count;
variable poleflag;
variable pointer2;
variable mantis;
variable Only_Once;

procedure Node999;
procedure Node911;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node019;
procedure Node020;
procedure Node023;
procedure Node024;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node053;
procedure Node054;
procedure Node055;
procedure Node056;
procedure Node093;
procedure Node059;
procedure Node062;
procedure Node065;
procedure Node066;
procedure Node067;
procedure Node068;
procedure Node069;
procedure Node070;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node080;
procedure Node081;
procedure Node082;
procedure Node083;
procedure Node084;
procedure Node085;
procedure Node086;
procedure Node087;
procedure Node088;
procedure Node089;
procedure Node090;
procedure Node091;
procedure Node092;
procedure NodeWarrFail;
procedure critter_p_proc;
procedure timed_event_p_proc;
procedure destroy_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure start;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure EvaluateKarma
begin
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure CheckRep
begin
    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
        set_global_var(GVAR_CHAMPION_REPUTATION, 1);
        set_global_var(GVAR_BERSERKER_REPUTATION, 0);
    end
    if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
        set_global_var(GVAR_BERSERKER_REPUTATION, 1);
        set_global_var(GVAR_CHAMPION_REPUTATION, 0);
    end
end

procedure Node999
begin
end

procedure Node911
begin
    set_local_var(5, 2);
end

procedure Node004
begin
    set_local_var(2, local_var(2) + 1);
    Reply(mstr(214) + dude_name + mstr(215));
    if (obj_is_carrying_obj_pid(dude_obj, 273) > 0) then begin
        giq_option(-1, NAME, 216, "Node005", NEUTRAL_REACTION);
    end
    else begin
        giq_option(-1, NAME, 218, "Node005", NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 220, "Node014", NEUTRAL_REACTION);
    if (dude_iq >= 2) then begin
        giq_option(-4, NAME, 224, "Node014", NEUTRAL_REACTION);
    end
    if (dude_iq >= 2) then begin
        giq_option(-4, NAME, 226, "Node005", NEUTRAL_REACTION);
    end
    if (global_var(GVAR_RNDMDDG_FLAG) >= 1) then begin
        giq_option(5, NAME, 230, "Node014", NEUTRAL_REACTION);
    end
    if (local_var(2) < dude_charisma) then begin
        giq_option(5, NAME, 232, "Node015", NEUTRAL_REACTION);
    end
    else begin
        giq_option(5, NAME, 232, "Node020", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 234, "Node005", NEUTRAL_REACTION);
    if (obj_is_carrying_obj_pid(dude_obj, 7) == 0) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) > 0) and (local_var(0) == 0)) then begin
            giq_option(5, NAME, 236, "Node008", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 236, "Node011", NEUTRAL_REACTION);
        end
    end
    giq_option(1, NAME, 238, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
    Reply(240);
    giq_option(-1, NAME, 242, "Node006", NEUTRAL_REACTION);
    giq_option(1, NAME, 244, "Node006", NEUTRAL_REACTION);
    giq_option(8, NAME, 246, "Node006", NEUTRAL_REACTION);
    giq_option(5, NAME, 248, Node999, NEUTRAL_REACTION);
    giq_option(-4, NAME, 250, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    Reply(252);
    if (dude_strength > 6) then begin
        giq_option(-4, NAME, 254, "Node012", NEUTRAL_REACTION);
    end
    if (dude_strength > 6) then begin
        giq_option(5, NAME, 256, "Node012", NEUTRAL_REACTION);
    end
    if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal) and (dude_charisma > 5)) then begin
        giq_option(1, NAME, 258, "Node007", NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 260, "Node014", NEUTRAL_REACTION);
    giq_option(1, NAME, 262, "Node014", NEUTRAL_REACTION);
    giq_option(5, NAME, 264, "Node014", NEUTRAL_REACTION);
end

procedure Node007
begin
    Reply(266);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node008
begin
    Reply(268);
    giq_option(1, NAME, 270, "Node010", NEUTRAL_REACTION);
    if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal) or (do_check(dude_obj, 6, 0) == 2)) then begin
        giq_option(1, NAME, 272, "Node010", NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 272, "Node011", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 274, Node999, NEUTRAL_REACTION);
end

procedure Node009
begin
    Reply(276);
    giq_option(1, NAME, 282, Node999, NEUTRAL_REACTION);
end

procedure Node010
begin
    set_local_var(0, 1);
    rm_mult_objs_from_inven(self_obj, obj_carrying_pid_obj(self_obj, 7), 1);
    add_mult_objs_to_inven(dude_obj, create_object(7, 0, 0), 1);
    Reply(284);
    giq_option(1, NAME, 288, Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    Reply(290);
    giq_option(1, NAME, 292, Node999, NEUTRAL_REACTION);
end

procedure Node012
begin
    Reply(294);
    giq_option(5, NAME, 296, "Node014", NEUTRAL_REACTION);
    giq_option(-4, NAME, 298, "Node014", NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(302);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 304, Node999, NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 306, Node999, NEUTRAL_REACTION);
    giq_option(5, NAME, 308, Node999, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(310);
    giq_option(1, NAME, 312, "Node016", NEUTRAL_REACTION);
    giq_option(1, NAME, 314, "Node017", NEUTRAL_REACTION);
    giq_option(1, NAME, 318, "Node019", NEUTRAL_REACTION);
    giq_option(1, NAME, 322, Node999, NEUTRAL_REACTION);
end

procedure Node016
begin
    set_local_var(3, local_var(3) + 1);
    Reply(324);
    if (local_var(3) < dude_charisma) then begin
        giq_option(1, NAME, 326, Node015, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 326, "Node020", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 328, Node999, NEUTRAL_REACTION);
end

procedure Node017
begin
    set_local_var(3, local_var(3) + 1);
    Reply(330);
    if (local_var(3) < dude_charisma) then begin
        giq_option(1, NAME, 332, Node015, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 332, "Node020", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 334, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    set_local_var(3, local_var(3) + 1);
    Reply(342);
    if (local_var(3) < dude_charisma) then begin
        giq_option(1, NAME, 344, Node015, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 344, "Node020", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 346, Node999, NEUTRAL_REACTION);
end

procedure Node020
begin
    Reply(348);
    giq_option(5, NAME, 350, Node999, NEUTRAL_REACTION);
    giq_option(-4, NAME, 352, Node999, NEUTRAL_REACTION);
end

procedure Node023
begin
    set_local_var(2, local_var(2) + 1);
    Reply(mstr(380) + dude_name + mstr(381));
    giq_option(-1, NAME, 382, "Node029", NEUTRAL_REACTION);
    giq_option(-1, NAME, 384, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 386, "Node029", NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 388, Node999, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 392, "Node029", NEUTRAL_REACTION);
    if (local_var(3) < dude_charisma) then begin
        giq_option(5, NAME, 394, Node015, NEUTRAL_REACTION);
    end
    else begin
        giq_option(5, NAME, 394, Node020, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 396, "Node027", NEUTRAL_REACTION);
    giq_option(5, NAME, 402, Node999, NEUTRAL_REACTION);
end

procedure Node024
begin
    set_local_var(2, local_var(2) + 1);
    Reply(mstr(404) + dude_name + mstr(405));
    giq_option(-1, NAME, 406, "Node029", NEUTRAL_REACTION);
    giq_option(-1, NAME, 408, "Node028", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 410, "Node029", NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 412, "Node028", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 414, "Node027", NEUTRAL_REACTION);
    giq_option(5, NAME, 416, "Node029", NEUTRAL_REACTION);
    giq_option(5, NAME, 418, "Node028", NEUTRAL_REACTION);
    giq_option(5, NAME, 420, Node999, NEUTRAL_REACTION);
end

procedure Node027
begin
    set_local_var(2, local_var(2) + 10);
    set_local_var(7, 1);
    Reply(436);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node028
begin
    set_local_var(2, local_var(2) + 10);
    Reply(438);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node029
begin
    Reply(440);
    giq_option(-1, NAME, 442, "Node030", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 444, "Node030", NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 446, "Node030", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 448, "Node030", NEUTRAL_REACTION);
    giq_option(2, NAME, 450, Node999, NEUTRAL_REACTION);
end

procedure Node030
begin
    Reply(452);
    giq_option(-1, NAME, 454, "Node034", NEUTRAL_REACTION);
    giq_option(-1, NAME, 456, "Node033", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 460, Node028, NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 462, "Node034", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 464, "Node034", NEUTRAL_REACTION);
    giq_option(5, NAME, 470, Node028, NEUTRAL_REACTION);
end

procedure Node033
begin
    Reply(500);
    giq_option(1, NAME, 502, "Node034", NEUTRAL_REACTION);
    giq_option(1, NAME, 504, Node028, NEUTRAL_REACTION);
end

procedure Node034
begin
    set_global_var(GVAR_ACFIRST_Q1_SKINS, 1);
    set_global_var(GVAR_ARROYO_MEMBER, 2);
    set_local_var(6, game_time);
    Reply(mstr(506) + dude_name + mstr(507));
    giq_option(-1, NAME, 508, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 510, Node999, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 512, Node999, NEUTRAL_REACTION);
end

procedure Node035
begin
    set_local_var(2, local_var(2) + 1);
    Reply(mstr(514) + dude_name + mstr(515));
    giq_option(-1, NAME, 516, Node999, NEUTRAL_REACTION);
    giq_option(-1, NAME, 518, "Node038", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 520, Node999, NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 522, "Node038", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 524, Node027, NEUTRAL_REACTION);
    giq_option(5, NAME, 526, "Node038", NEUTRAL_REACTION);
    giq_option(5, NAME, 528, Node999, NEUTRAL_REACTION);
end

procedure Node037
begin
    Reply(538);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node038
begin
    Reply(540);
    giq_option(-1, NAME, 542, "Node042", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 544, "Node042", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 546, "Node042", NEUTRAL_REACTION);
    if ((dude_skill(SKILL_SPEECH) >= 35) and (dude_charisma >= 8)) then begin
        giq_option(5, NAME, 548, "Node039", NEUTRAL_REACTION);
    end
    giq_option(-4, NAME, 550, Node999, NEUTRAL_REACTION);
    giq_option(5, NAME, 554, Node999, NEUTRAL_REACTION);
end

procedure Node039
begin
    Reply(556);
    giq_option(-1, NAME, 558, Node030, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 560, Node030, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 562, Node030, NEUTRAL_REACTION);
    giq_option(-1, NAME, 564, Node028, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 566, Node028, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 568, Node028, NEUTRAL_REACTION);
end

procedure Node041
begin
    set_local_var(2, local_var(2) + 1);
    Reply(578);
    if ((dude_gender == 0) and ((dude_strength + get_critter_stat(dude_obj, STAT_ag) + dude_endurance) >= 15)) then begin
        giq_option(-1, NAME, 580, "Node043", NEUTRAL_REACTION);
    end
    else begin
        giq_option(-1, NAME, 580, "Node042", NEUTRAL_REACTION);
    end
    if (dude_iq <= 4) then begin
        if ((dude_gender == 0) and ((dude_strength + get_critter_stat(dude_obj, STAT_ag) + dude_endurance) >= 15)) then begin
            giq_option(2, NAME, 582, "Node043", NEUTRAL_REACTION);
        end
        else begin
            giq_option(2, NAME, 582, "Node042", NEUTRAL_REACTION);
        end
    end
    if ((dude_gender == 0) and ((dude_strength + get_critter_stat(dude_obj, STAT_ag) + dude_endurance) >= 15)) then begin
        giq_option(5, NAME, 584, "Node043", NEUTRAL_REACTION);
    end
    else begin
        giq_option(5, NAME, 584, "Node042", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 586, "Node045", NEUTRAL_REACTION);
    giq_option(5, NAME, 588, "Node044", NEUTRAL_REACTION);
    giq_option(5, NAME, 590, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 592, Node999, NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 594, Node999, NEUTRAL_REACTION);
end

procedure Node042
begin
    Reply(596);
    giq_option(5, NAME, 598, Node999, NEUTRAL_REACTION);
    giq_option(-4, NAME, 600, Node999, NEUTRAL_REACTION);
end

procedure Node043
begin
    Reply(602);
    giq_option(1, NAME, 604, Node999, NEUTRAL_REACTION);
end

procedure Node044
begin
    Reply(606);
    giq_option(1, NAME, 608, Node999, NEUTRAL_REACTION);
end

procedure Node045
begin
    Reply(610);
    giq_option(1, NAME, 612, Node999, NEUTRAL_REACTION);
end

procedure Node053
begin
    Reply(mstr(662));
    if (local_var(7) == 0) then begin
        giq_option(-1, NAME, 664, Node999, NEUTRAL_REACTION);
        if (dude_iq <= 4) then begin
            giq_option(2, NAME, 670, "Node056", NEUTRAL_REACTION);
        end
        giq_option(5, NAME, 674, "Node056", NEUTRAL_REACTION);
    end
    else begin
        giq_option(-1, NAME, 664, Node999, NEUTRAL_REACTION);
        if (dude_iq <= 4) then begin
            giq_option(2, NAME, 670, Node999, NEUTRAL_REACTION);
        end
        giq_option(5, NAME, 674, Node999, NEUTRAL_REACTION);
    end
end

procedure Node054
begin
    Reply(676);
    if (dude_gender == 1) then begin
        if (dude_charisma >= 8) then begin
            giq_option(1, NAME, 678, "Node072", NEUTRAL_REACTION);
        end
        else begin
            giq_option(1, NAME, 678, "Node055", NEUTRAL_REACTION);
        end
    end
    giq_option(5, NAME, 680, "Node072", NEUTRAL_REACTION);
    giq_option(1, NAME, 682, Node999, NEUTRAL_REACTION);
end

procedure Node055
begin
    Reply(684);
    giq_option(1, NAME, 686, Node999, NEUTRAL_REACTION);
end

procedure Node056
begin
    Reply(688);
    giq_option(-1, NAME, 690, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 692, Node999, NEUTRAL_REACTION);
    end
    if (local_var(4) > 0) then begin
        giq_option(5, NAME, 694, Node054, NEUTRAL_REACTION);
    end
    else begin
        giq_option(5, NAME, 694, "Node069", NEUTRAL_REACTION);
    end
    if ((obj_is_carrying_obj_pid(dude_obj, 7) == 0) and (dude_gender == 0)) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) == 0) or (local_var(0) > 0)) then begin
            giq_option(5, NAME, 752, "Node066", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 752, "Node067", NEUTRAL_REACTION);
        end
    end
    if ((obj_is_carrying_obj_pid(dude_obj, 7) == 0) and (dude_gender == 1)) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) > 0) and (local_var(0) == 0)) then begin
            giq_option(5, NAME, 236, Node008, NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 236, Node011, NEUTRAL_REACTION);
        end
    end
    giq_option(5, NAME, 696, Node999, NEUTRAL_REACTION);
end

procedure Node093
begin
    Reply(688);
    giq_option(-1, NAME, 690, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 692, Node999, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 694, "Node090", NEUTRAL_REACTION);
    if ((obj_is_carrying_obj_pid(dude_obj, 7) == 0) and (dude_gender == 0)) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) == 0) or (local_var(0) > 0)) then begin
            giq_option(5, NAME, 752, "Node066", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 752, "Node067", NEUTRAL_REACTION);
        end
    end
    if ((obj_is_carrying_obj_pid(dude_obj, 7) == 0) and (dude_gender == 1)) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) > 0) and (local_var(0) == 0)) then begin
            giq_option(5, NAME, 236, Node008, NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 236, Node011, NEUTRAL_REACTION);
        end
    end
    giq_option(5, NAME, 696, Node999, NEUTRAL_REACTION);
end

procedure Node059
begin
    set_local_var(2, local_var(2) + 1);
    Reply(710);
    giq_option(5, NAME, 712, Node037, NEUTRAL_REACTION);
    if (global_var(GVAR_ACJORDAN_FIND) == 1) then begin
        giq_option(5, NAME, 716, "Node062", NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 718, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 720, Node999, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 722, Node999, NEUTRAL_REACTION);
end

procedure Node062
begin
    Reply(736);
    giq_option(1, NAME, 738, Node999, NEUTRAL_REACTION);
end

procedure Node065
begin
    set_local_var(2, local_var(2) + 1);
    Reply(750);
    if (obj_is_carrying_obj_pid(dude_obj, 7) == 0) then begin
        if ((obj_is_carrying_obj_pid(self_obj, 7) == 0) or (local_var(0) > 0)) then begin
            giq_option(5, NAME, 752, "Node066", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 752, "Node067", NEUTRAL_REACTION);
        end
    end
    if (obj_is_carrying_obj_pid(dude_obj, 277) >= 3) then begin
        if (has_trait(TRAIT_PERK, dude_obj, PERK_gecko_skinning_perk) > 0) then begin
            giq_option(5, NAME, 754, "Node084", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 754, "NodeWarrFail", NEUTRAL_REACTION);
        end
    end
    if (obj_is_carrying_obj_pid(dude_obj, 277) >= 3) then begin
        if (has_trait(TRAIT_PERK, dude_obj, PERK_gecko_skinning_perk) > 0) then begin
            giq_option(-1, NAME, 756, "Node084", NEUTRAL_REACTION);
        end
        else begin
            giq_option(-1, NAME, 756, "NodeWarrFail", NEUTRAL_REACTION);
        end
    end
    if ((obj_is_carrying_obj_pid(dude_obj, 277) >= 3) and (dude_iq <= 4)) then begin
        if (has_trait(TRAIT_PERK, dude_obj, PERK_gecko_skinning_perk) > 0) then begin
            giq_option(2, NAME, 758, "Node084", NEUTRAL_REACTION);
        end
        else begin
            giq_option(2, NAME, 758, "NodeWarrFail", NEUTRAL_REACTION);
        end
    end
    giq_option(-1, NAME, 760, "Node080", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 762, "Node080", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 764, "Node080", NEUTRAL_REACTION);
    if (local_var(4) == 0) then begin
        giq_option(5, NAME, 766, "Node069", NEUTRAL_REACTION);
    end
    else begin
        if ((local_var(9) == 0) or (((game_time - local_var(9)) / (60 * 600)) > 12)) then begin
            giq_option(5, NAME, 766, "Node072", NEUTRAL_REACTION);
        end
        else begin
            giq_option(5, NAME, 766, "Node082", NEUTRAL_REACTION);
        end
    end
end

procedure Node066
begin
    Reply(768);
    giq_option(1, NAME, 770, Node999, NEUTRAL_REACTION);
    giq_option(1, NAME, 772, Node999, NEUTRAL_REACTION);
end

procedure Node067
begin
    set_local_var(0, 1);
    rm_mult_objs_from_inven(self_obj, obj_carrying_pid_obj(self_obj, 7), 1);
    add_mult_objs_to_inven(dude_obj, create_object(7, 0, 0), 1);
    Reply(774);
    giq_option(1, NAME, 776, Node999, NEUTRAL_REACTION);
end

procedure Node068
begin
    rm_mult_objs_from_inven(dude_obj, obj_carrying_pid_obj(dude_obj, 277), 3);
    set_global_var(GVAR_ACFIRST_Q1_SKINS, 2);
    set_global_var(GVAR_JENFARM_FLAGS, 1);
    game_time_advance(12 * 60 * 60 * 10);
    set_local_var(4, local_var(4) + 1);
    give_exp_points(400);
    display_msg(g_mstr(100) + 400 + g_mstr(101));
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 10);
    set_global_var(GVAR_TOWN_REP_ARROYO, global_var(GVAR_TOWN_REP_ARROYO) + 10);
    Reply(778);
    giq_option(-1, NAME, 780, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 782, Node999, NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 784, Node999, NEUTRAL_REACTION);
    if (local_var(4) == 0) then begin
        giq_option(4, NAME, 788, "Node069", NEUTRAL_REACTION);
    end
    else begin
        if ((local_var(9) == 0) or (((game_time - local_var(9)) / (60 * 600)) > 12)) then begin
            giq_option(4, NAME, 788, "Node072", NEUTRAL_REACTION);
        end
        else begin
            giq_option(4, NAME, 788, "Node082", NEUTRAL_REACTION);
        end
    end
end

procedure Node069
begin
    Reply(790);
    giq_option(5, NAME, 792, Node999, NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 794, Node999, NEUTRAL_REACTION);
    end
    giq_option(-1, NAME, 796, Node999, NEUTRAL_REACTION);
end

procedure Node070
begin
    Reply(798);
    if ((local_var(9) == 0) or (((game_time - local_var(9)) / (60 * 600)) > 12)) then begin
        giq_option(1, NAME, 802, "Node072", NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 802, "Node082", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 806, Node999, NEUTRAL_REACTION);
end

procedure Node072
begin
    Reply(812);
    if (dude_skill(SKILL_MELEE) > 90) then begin
        giq_option(1, NAME, 814, Node070, NEUTRAL_REACTION);
    end
    else begin
        if (dude_skill(SKILL_MELEE) > 50) then begin
            if (local_var(4) > 0) then begin
                if ((global_var(GVAR_ACFIRST_Q1_SKINS) == 2) and (dude_endurance > 5) and (local_var(8) == 1)) then begin
                    giq_option(1, NAME, 814, "Node077", NEUTRAL_REACTION);
                end
                else begin
                    giq_option(1, NAME, 814, "Node073", NEUTRAL_REACTION);
                end
            end
        end
        else begin
            giq_option(1, NAME, 814, "Node076", NEUTRAL_REACTION);
        end
    end
    if (dude_skill(SKILL_UNARMED_COMBAT) > 90) then begin
        giq_option(1, NAME, 816, Node070, NEUTRAL_REACTION);
    end
    else begin
        if (dude_skill(SKILL_UNARMED_COMBAT) > 60) then begin
            if (local_var(4) > 0) then begin
                if ((global_var(GVAR_ACFIRST_Q1_SKINS) == 2) and (dude_endurance > 4) and (local_var(8) == 2)) then begin
                    giq_option(1, NAME, 816, "Node078", NEUTRAL_REACTION);
                end
                else begin
                    giq_option(1, NAME, 816, "Node074", NEUTRAL_REACTION);
                end
            end
        end
        else begin
            giq_option(1, NAME, 816, "Node076", NEUTRAL_REACTION);
        end
    end
    giq_option(1, NAME, 820, Node999, NEUTRAL_REACTION);
end

procedure Node073
begin
    if (local_var(8) == 1) then begin
        Float_Stage := 4;
        Reply(875);
        if (local_var(11) == 0) then begin
            add_obj_to_inven(dude_obj, create_object(320, 0, 0));
        end
        set_local_var(11, 1);
    end
    else begin
        Float_Stage := 1;
        if (local_var(11) == 0) then begin
            add_obj_to_inven(dude_obj, create_object(320, 0, 0));
        end
        set_local_var(11, 1);
    end
    Drug := 1;
    Flag := 0;
    poleflag := 0;
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node074
begin
    if (local_var(8) == 2) then begin
        Float_Stage := 5;
    end
    else begin
        Float_Stage := 2;
    end
    Drug := 1;
    Flag := 0;
    Reply(875);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node076
begin
    Reply(842);
    if ((local_var(9) == 0) or (((game_time - local_var(9)) / (60 * 600)) > 12)) then begin
        giq_option(1, NAME, 844, Node072, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, NAME, 844, "Node082", NEUTRAL_REACTION);
    end
    giq_option(1, NAME, 846, Node999, NEUTRAL_REACTION);
end

procedure Node077
begin
    if (local_var(8) == 1) then begin
        Float_Stage := 4;
        Reply(875);
        if (local_var(11) == 0) then begin
            add_obj_to_inven(dude_obj, create_object(320, 0, 0));
        end
        set_local_var(11, 1);
    end
    else begin
        Float_Stage := 1;
        if (local_var(11) == 0) then begin
            add_obj_to_inven(dude_obj, create_object(320, 0, 0));
        end
        set_local_var(11, 1);
    end
    Drug := 2;
    Flag := 0;
    poleflag := 0;
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node078
begin
    if (local_var(8) == 2) then begin
        Float_Stage := 5;
    end
    else begin
        Float_Stage := 2;
    end
    Drug := 2;
    Flag := 0;
    Reply(875);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node080
begin
    Reply(866);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node081
begin
    Reply(mstr(868) + dude_name + mstr(869));
    if (local_var(4) > 0) then begin
        if ((local_var(9) == 0) or (((game_time - local_var(9)) / (60 * 600)) > 12)) then begin
            giq_option(4, NAME, 870, Node072, NEUTRAL_REACTION);
        end
        else begin
            giq_option(4, NAME, 870, "Node082", NEUTRAL_REACTION);
        end
    end
    else begin
        giq_option(4, NAME, 870, Node069, NEUTRAL_REACTION);
    end
    giq_option(2, NAME, 872, Node999, NEUTRAL_REACTION);
    giq_option(-1, NAME, 874, Node999, NEUTRAL_REACTION);
end

procedure Node082
begin
    Reply(867);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node083
begin
    Reply(865);
    giq_option(1, SCRIPT_GENERIC, 350, Node999, NEUTRAL_REACTION);
end

procedure Node084
begin
    Reply(910);
    giq_option(-1, NAME, 912, "Node085", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 914, "Node085", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 916, "Node085", NEUTRAL_REACTION);
end

procedure Node085
begin
    Reply(918);
    giq_option(-1, NAME, 920, "Node086", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 922, "Node086", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 924, "Node086", NEUTRAL_REACTION);
end

procedure Node086
begin
    Reply(926);
    giq_option(-1, NAME, 928, "Node087", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 930, "Node087", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 932, "Node087", NEUTRAL_REACTION);
end

procedure Node087
begin
    Reply(934);
    giq_option(-1, NAME, 936, "Node088", NEUTRAL_REACTION);
    if (dude_iq <= 4) then begin
        giq_option(2, NAME, 938, "Node088", NEUTRAL_REACTION);
    end
    giq_option(5, NAME, 940, "Node088", NEUTRAL_REACTION);
end

procedure Node088
begin
    Reply(942);
    giq_option(1, NAME, 944, "Node089", NEUTRAL_REACTION);
end

procedure Node089
begin
    gfade_out(600);
    gfade_in(600);
    Reply(946);
    giq_option(-1, NAME, 948, Node068, NEUTRAL_REACTION);
    giq_option(2, NAME, 950, Node068, NEUTRAL_REACTION);
end

procedure Node090
begin
    if ((local_var(10) == 0) or (local_var(11) == 0)) then begin
        Reply(812);
        if (local_var(10) == 0) then begin
            giq_option(2, NAME, 814, "Node091", NEUTRAL_REACTION);
        end
        if (local_var(11) == 0) then begin
            giq_option(2, NAME, 816, "Node092", NEUTRAL_REACTION);
        end
        giq_option(2, NAME, 820, Node999, NEUTRAL_REACTION);
    end
    else begin
        Reply(798);
        giq_option(2, NAME, 794, Node999, NEUTRAL_REACTION);
    end
end

procedure Node091
begin
    Reply(892);
    giq_option(2, NAME, 872, Node999, NEUTRAL_REACTION);
    critter_mod_skill(dude_obj, SKILL_MELEE, 10);
    game_time_advance(24 * 60 * 60 * 10);
    set_local_var(10, 1);
    gfade_out(600);
    gfade_in(600);
end

procedure Node092
begin
    Reply(894);
    giq_option(2, NAME, 872, Node999, NEUTRAL_REACTION);
    critter_mod_skill(dude_obj, SKILL_UNARMED_COMBAT, 10);
    game_time_advance(24 * 60 * 60 * 10);
    set_local_var(11, 1);
    gfade_out(600);
    gfade_in(600);
end

procedure NodeWarrFail
begin
    set_global_var(GVAR_ACFIRST_Q1_SKINS, 3);
    Reply(952);
    giq_option(1, NAME, 954, Node999, NEUTRAL_REACTION);
end

procedure critter_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
    if ((global_var(GVAR_ENEMY_ARROYO) == 1) and obj_can_see_obj(self_obj, dude_obj)) then begin
        attack(dude_obj);
    end
    if (global_var(GVAR_ACFIRST_Q1_SKINS) == 1) then begin
        if (((game_time - local_var(6)) / (24 * 60 * 60 * 10)) >= 14) then begin
            display_mstr(999);
            set_global_var(GVAR_ACFIRST_Q1_SKINS, 3);
        end
    end
    if ((Float_Stage > 0) and (Flag >= 0)) then begin
        if ((tile_distance_objs(self_obj, dude_obj) == 1) and obj_can_see_obj(self_obj, dude_obj) and (anim_busy(dude_obj) == 0)) then begin
            LVar1 := 0;
            LVar0 := critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND);
            if (LVar0 == 0) then begin
                LVar0 := critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND);
            end
            if (LVar0 != 0) then begin
                if (obj_pid(LVar0) == 320) then begin
                    LVar1 := 1;
                end
            end
            if ((Float_Stage == 1) or (Float_Stage == 4) and (LVar1 == 0)) then begin
                if (poleflag == 0) then begin
                    poleflag := 1;
                    float_msg(self_obj, mstr(977), FLOAT_MSG_NORMAL);
                end
            end
            else begin
                game_ui_disable;
                anim(self_obj, 1000, rotation_to_tile(tile_num(self_obj), dude_tile));
                anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(self_obj)));
                Flag := -1;
                add_timer_event(self_obj, 1, Float_Stage);
            end
        end
        else begin
            if (Flag == 0) then begin
                float_msg(self_obj, mstr(876), FLOAT_MSG_NORMAL);
                Flag := 1;
            end
        end
    end
end

procedure timed_event_p_proc
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    if (fixed_param <= 6) then begin
        set_local_var(8, Float_Stage);
        Float_Stage := (Float_Stage * 10) + 1;
        set_map_start((tile_num(self_obj) % 200) - 5, tile_num(self_obj) / 200, elevation(self_obj), 0);
        add_timer_event(self_obj, 70 / 5, Float_Stage);
    end
    if (fixed_param == 900) then begin
        fade_out;
        if (Drug == 1) then begin
            game_time_advance(288000);
        end
        else begin
            game_time_advance(432000);
        end
        add_timer_event(self_obj, 3, 901);
    end
    if (fixed_param == 901) then begin
        set_obj_visibility(self_obj, 0);
        fade_in;
        add_timer_event(self_obj, 70 / 5, Float_Stage);
    end
    if (fixed_param == 999) then begin
        game_ui_enable;
        Float_Stage := 0;
        set_local_var(4, local_var(4) - 1);
    end
    if (fixed_param == 11) then begin
        Battle_Count := 0;
        Float_Stage := Float_Stage + 1;
        add_timer_event(self_obj, 0, Float_Stage);
    end
    if (fixed_param == 12) then begin
        Battle_Count := Battle_Count + 1;
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 41, 0);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 41, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 3, Float_Stage);
    end
    if (fixed_param == 13) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(random(887, 891)), FLOAT_MSG_RED);
        LVar3 := sfx_build_char_name(dude_obj, 20, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 20, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 0);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 14) then begin
        Float_Stage := Float_Stage + 1;
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 37, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 1) then begin
            add_timer_event(self_obj, 20, Float_Stage);
        end
        else begin
            Float_Stage := 16;
            add_timer_event(self_obj, 20, Float_Stage);
        end
    end
    if (fixed_param == 15) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(978), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 40, Float_Stage);
    end
    if (fixed_param == 16) then begin
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(dude_obj, 41, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 41, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 3, Float_Stage);
    end
    if (fixed_param == 17) then begin
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 40, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 40, -1);
        reg_anim_play_sfx(self_obj, LVar3, 0);
        reg_anim_func(3, 0);
        if (Battle_Count == 4) then begin
            add_timer_event(self_obj, 10, 900);
        end
        else begin
            Float_Stage := 12;
            add_timer_event(self_obj, 5, Float_Stage);
        end
    end
    if (fixed_param == 18) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(980), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 19) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(982), FLOAT_MSG_GREEN);
        display_mstr(900);
        critter_mod_skill(dude_obj, SKILL_MELEE, 4);
        display_mstr(101);
        set_local_var(9, game_time);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 20) then begin
        LVar3 := sfx_build_char_name(dude_obj, 39, 0);
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(882), FLOAT_MSG_NORMAL);
        add_timer_event(self_obj, 70, 999);
    end
    if (fixed_param == 21) then begin
        Battle_Count := 0;
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(960), FLOAT_MSG_NORMAL);
        add_timer_event(self_obj, 5, Float_Stage);
    end
    if (fixed_param == 22) then begin
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 16, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 16, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 4, Float_Stage);
    end
    if (fixed_param == 23) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(888), FLOAT_MSG_RED);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 14, -1);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 24) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(962), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 25) then begin
        Battle_Count := Battle_Count + 1;
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(dude_obj, 16, 0);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 16, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 0);
        reg_anim_func(3, 0);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 13, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 9, Float_Stage);
    end
    if (fixed_param == 26) then begin
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 16, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 16, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 4, Float_Stage);
    end
    if (fixed_param == 27) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(random(887, 891)), FLOAT_MSG_RED);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 14, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 5) then begin
            add_timer_event(self_obj, 10, 900);
        end
        else begin
            Float_Stage := 25;
            add_timer_event(self_obj, 14, Float_Stage);
        end
    end
    if (fixed_param == 28) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(964), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 29) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(966), FLOAT_MSG_GREEN);
        display_mstr(892);
        critter_mod_skill(dude_obj, SKILL_UNARMED_COMBAT, 4);
        display_mstr(105);
        set_local_var(9, game_time);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 30) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(882), FLOAT_MSG_YELLOW);
        add_timer_event(self_obj, 70, 999);
    end
    if (fixed_param == 41) then begin
        Battle_Count := 0;
        Float_Stage := Float_Stage + 1;
        add_timer_event(self_obj, 0, Float_Stage);
    end
    if (fixed_param == 42) then begin
        Battle_Count := Battle_Count + 1;
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 41, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 41, -1);
        reg_anim_play_sfx(self_obj, LVar3, 0);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 3, Float_Stage);
    end
    if (fixed_param == 43) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(random(887, 891)), FLOAT_MSG_RED);
        LVar3 := sfx_build_char_name(dude_obj, 20, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 20, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 0);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 44) then begin
        Float_Stage := Float_Stage + 1;
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 37, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 1) then begin
            float_msg(self_obj, mstr(962), FLOAT_MSG_GREEN);
        end
        add_timer_event(self_obj, 20, Float_Stage);
    end
    if (fixed_param == 45) then begin
        Float_Stage := Float_Stage + 1;
        if (Battle_Count == 1) then begin
            float_msg(dude_obj, mstr(968), FLOAT_MSG_RED);
        end
        LVar3 := sfx_build_char_name(dude_obj, 41, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 41, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 0);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 4, Float_Stage);
    end
    if (fixed_param == 46) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(random(895, 899)), FLOAT_MSG_GREEN);
        LVar3 := sfx_build_char_name(self_obj, 20, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 20, -1);
        reg_anim_play_sfx(self_obj, LVar3, 0);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 47) then begin
        Float_Stage := Float_Stage + 1;
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 37, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 1) then begin
            float_msg(self_obj, mstr(970), FLOAT_MSG_GREEN);
        end
        if (Battle_Count == 2) then begin
            add_timer_event(self_obj, 10, 900);
        end
        else begin
            Float_Stage := 42;
            add_timer_event(self_obj, 20, Float_Stage);
        end
    end
    if (fixed_param == 48) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(972), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 49) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(974), FLOAT_MSG_GREEN);
        display_mstr(894);
        critter_mod_skill(dude_obj, SKILL_MELEE, 8);
        display_mstr(102);
        set_local_var(9, game_time);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 50) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(882), FLOAT_MSG_YELLOW);
        add_timer_event(self_obj, 70, 999);
    end
    if (fixed_param == 51) then begin
        Battle_Count := 0;
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(960), FLOAT_MSG_NORMAL);
        add_timer_event(self_obj, 5, Float_Stage);
    end
    if (fixed_param == 52) then begin
        Battle_Count := Battle_Count + 1;
        Float_Stage := Float_Stage + 1;
        LVar3 := sfx_build_char_name(self_obj, 16, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 16, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 4, Float_Stage);
    end
    if (fixed_param == 53) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(random(887, 891)), FLOAT_MSG_RED);
        LVar3 := sfx_build_char_name(dude_obj, 20, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 20, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 54) then begin
        Float_Stage := Float_Stage + 1;
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 37, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 1) then begin
            float_msg(self_obj, mstr(962), FLOAT_MSG_GREEN);
        end
        add_timer_event(self_obj, 20, Float_Stage);
    end
    if (fixed_param == 55) then begin
        Float_Stage := Float_Stage + 1;
        if (Battle_Count == 1) then begin
            float_msg(dude_obj, mstr(968), FLOAT_MSG_RED);
        end
        LVar3 := sfx_build_char_name(dude_obj, 16, 4);
        reg_anim_func(2, dude_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(dude_obj, 16, -1);
        reg_anim_play_sfx(dude_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 4, Float_Stage);
    end
    if (fixed_param == 56) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(random(895, 899)), FLOAT_MSG_GREEN);
        LVar3 := sfx_build_char_name(self_obj, 20, 4);
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 20, -1);
        reg_anim_play_sfx(self_obj, LVar3, 4);
        reg_anim_func(3, 0);
        add_timer_event(self_obj, 70 / 2, Float_Stage);
    end
    if (fixed_param == 57) then begin
        Float_Stage := Float_Stage + 1;
        reg_anim_func(2, self_obj);
        reg_anim_func(1, 1);
        reg_anim_animate(self_obj, 37, -1);
        reg_anim_func(3, 0);
        if (Battle_Count == 1) then begin
            float_msg(self_obj, mstr(970), FLOAT_MSG_GREEN);
        end
        if (Battle_Count == 2) then begin
            add_timer_event(self_obj, 10, 900);
        end
        else begin
            Float_Stage := 52;
            add_timer_event(self_obj, 20, Float_Stage);
        end
    end
    if (fixed_param == 58) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(972), FLOAT_MSG_GREEN);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 59) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(self_obj, mstr(974), FLOAT_MSG_GREEN);
        display_mstr(894);
        critter_mod_skill(dude_obj, SKILL_UNARMED_COMBAT, 8);
        display_mstr(106);
        set_local_var(9, game_time);
        add_timer_event(self_obj, 70, Float_Stage);
    end
    if (fixed_param == 60) then begin
        Float_Stage := Float_Stage + 1;
        float_msg(dude_obj, mstr(882), FLOAT_MSG_YELLOW);
        add_timer_event(self_obj, 70, 999);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (global_var(GVAR_ACFIRST_Q1_SKINS) == 1) then begin
            set_global_var(GVAR_ACFIRST_Q1_SKINS, 3);
        end
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - 15);
        call EvaluateKarma();
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    variable LVar0 := 0;
    if (global_var(GVAR_ACFIRST_Q1_SKINS) == 3) then begin
        start_gdialog(215, self_obj, 4, -1, -1);
        gsay_start;
        call Node083();
        gsay_end;
        end_dialogue;
    end
    else begin
        if (global_var(GVAR_ARTEMPLE_PROVE) == 1) then begin
            start_gdialog(215, self_obj, 4, -1, -1);
            gsay_start;
            call Node059();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(GVAR_ARROYO_MEMBER) == 1) then begin
                if (local_var(2) == 0) then begin
                    if (dude_gender == 1) then begin
                        start_gdialog(215, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node004();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if ((dude_strength + get_critter_stat(dude_obj, STAT_ag) + dude_endurance) >= 15) then begin
                            start_gdialog(215, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node023();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            start_gdialog(215, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node035();
                            gsay_end;
                            end_dialogue;
                        end
                    end
                end
                else begin
                    if ((dude_gender == 0) and (local_var(2) <= 3) and ((dude_strength + get_critter_stat(dude_obj, STAT_ag) + dude_endurance) >= 15)) then begin
                        start_gdialog(215, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node024();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if ((dude_gender == 1) and (local_var(2) <= 3)) then begin
                            start_gdialog(215, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node004();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            start_gdialog(215, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node041();
                            gsay_end;
                            end_dialogue;
                        end
                    end
                end
            end
            else begin
                if (global_var(GVAR_ACFIRST_Q1_SKINS) == 0) then begin
                    start_gdialog(215, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node053();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    if (global_var(GVAR_ACFIRST_Q1_SKINS) == 1) then begin
                        start_gdialog(215, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node065();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        start_gdialog(215, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node081();
                        gsay_end;
                        end_dialogue;
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(random(200, 201));
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(204);
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
        set_global_var(GVAR_ENEMY_ARROYO, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 1);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_ARROYO_WARRIOR);
    if (map_first_run) then begin
        set_local_var(4, 1);
    end
end

procedure start
begin
end
