variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure party_armor_fid(variable arg0, variable arg1);
procedure start;
procedure critter_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node999;
procedure redoing;
procedure increase_menu;
procedure decrease_menu;

variable dialog_part;
variable which_dialog;

procedure timed_event_p_proc;
procedure destroy_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure party_armor_fid(variable arg0, variable arg1)
begin
    variable LVar2 := 0;
    variable LVar3 := 0;
    LVar3 := critter_inven_obj(self_obj, 1);
    if (obj_item_subtype(LVar3) != 3) then begin
        LVar3 := critter_inven_obj(self_obj, 2);
    end
    if (critter_inven_obj(self_obj, 0) != arg0) then begin
        if (critter_inven_obj(self_obj, 0) == 0) then begin
            art_change_fid_num(self_obj, 16777216 + arg1);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 1) or (obj_pid(critter_inven_obj(self_obj, 0)) == 379)) then begin
            art_change_fid_num(self_obj, 16777228);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 232) or (obj_pid(critter_inven_obj(self_obj, 0)) == 3)) then begin
            art_change_fid_num(self_obj, 16777217);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 349) or (obj_pid(critter_inven_obj(self_obj, 0)) == 348)) then begin
            art_change_fid_num(self_obj, 16777287);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 240) or (obj_pid(critter_inven_obj(self_obj, 0)) == 380) or (obj_pid(critter_inven_obj(self_obj, 0)) == 2)) then begin
            art_change_fid_num(self_obj, 16777230);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 74) or (obj_pid(critter_inven_obj(self_obj, 0)) == 265)) then begin
            art_change_fid_num(self_obj, 16777229);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 239) or (obj_pid(critter_inven_obj(self_obj, 0)) == 17) or (obj_pid(critter_inven_obj(self_obj, 0)) == 381)) then begin
            art_change_fid_num(self_obj, 16777226);
        end
        if ((obj_pid(critter_inven_obj(self_obj, 0)) == 524) or (obj_pid(critter_inven_obj(self_obj, 0)) == 113)) then begin
            art_change_fid_num(self_obj, 16777218);
        end
        LVar2 := critter_inven_obj(self_obj, 1);
        debug_msg("armour pid == " + obj_pid(LVar2));
        rm_obj_from_inven(self_obj, LVar2);
        add_obj_to_inven(self_obj, LVar2);
        wield_obj_critter(self_obj, LVar3);
    end
    return 0;
    arg0 := 0;
    arg1 := 0;
    LVar2 := 0;
    LVar3 := 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if (map_var(34) == 1) then begin
        gfade_out(1000);
        gfade_in(1000);
        display_mstr(1810);
        if ((dude_iq > 7) and ((dude_skill(SKILL_REPAIR) + dude_skill(SKILL_SCIENCE) + dude_skill(SKILL_DOCTOR)) > 220)) then begin
            set_map_var(34, 5);
            set_map_var(32, 1);
            set_global_var(GVAR_BRTHD_ATTACK_MUTS, 2);
            set_global_var(GVAR_SULIK_SISTER_STATE, 1);
            set_global_var(GVAR_TOWN_REP_BURIED_VAULT, global_var(GVAR_TOWN_REP_BURIED_VAULT) + 20);
            float_msg(self_obj, mstr(mstr(2000) + mstr(2000 + random(1, 3))), FLOAT_MSG_YELLOW);
            display_msg(2005);
            give_exp_points(4500);
        end
        else begin
            set_map_var(34, 2);
            float_msg(self_obj, mstr(1900), FLOAT_MSG_YELLOW);
        end
    end
    if (map_var(34) == 3) then begin
        gfade_out(1000);
        gfade_in(1000);
        display_mstr(1810);
        if ((dude_iq > 7) and ((dude_skill(SKILL_REPAIR) + dude_skill(SKILL_SCIENCE) + dude_skill(SKILL_DOCTOR)) > 220)) then begin
            set_map_var(34, 5);
            set_map_var(32, 1);
            set_global_var(GVAR_BRTHD_ATTACK_MUTS, 2);
            set_global_var(GVAR_SULIK_SISTER_STATE, 1);
            float_msg(self_obj, mstr(mstr(2000) + mstr(2000 + random(1, 3))), FLOAT_MSG_YELLOW);
            display_msg(2005);
            give_exp_points(4500);
        end
        else begin
            set_map_var(32, 1);
            set_map_var(34, 2);
            float_msg(self_obj, mstr(1900), FLOAT_MSG_YELLOW);
        end
    end
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_mstr(1);
    end
    else begin
        display_mstr(2);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(3);
end

procedure use_skill_on_p_proc
begin
end

procedure use_obj_on_p_proc
begin
end

procedure damage_p_proc
begin
end

procedure map_enter_p_proc
begin
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
    if ((map_var(32) != 1) and (global_var(GVAR_BRTHD_ATTACK_MUTS) > 0)) then begin
        if ((map_var(33) > 0) and ((game_time - map_var(33)) > (2 * (60 * (60 * 10))))) then begin
            float_msg(self_obj, mstr(850), FLOAT_MSG_YELLOW);
        end
        else begin
            start_gdialog(1673, self_obj, -1, -1, -1);
            gsay_start;
            set_local_var(4, 1);
            if (map_var(34) == 2) then begin
                call Node019();
            end
            else begin
                call Node001();
            end
            gsay_end;
            end_dialogue;
        end
    end
    else begin
        float_msg(self_obj, mstr(2100), FLOAT_MSG_YELLOW);
    end
end

procedure Node001
begin
    Reply(100);
    giq_option(1, NAME, 110, Node002, -1);
    giq_option(1, NAME, 111, Node999, -1);
end

procedure Node002
begin
    Reply(200);
    giq_option(1, NAME, dude_name, Node004, -1);
    giq_option(1, NAME, dude_name + mstr(211), Node999, -1);
    giq_option(1, NAME, 212, Node999, -1);
end

procedure Node003
begin
    gsay_message(NAME, 300, GOOD_REACTION);
    set_map_var(32, 1);
end

procedure Node004
begin
    Reply(mstr(400) + dude_name + mstr(401));
    giq_option(1, NAME, 410, Node006, -1);
    giq_option(1, NAME, 411, Node999, -1);
    giq_option(1, NAME, 412, Node005, -1);
end

procedure Node005
begin
    Reply(500);
    giq_option(1, NAME, 510, Node006, -1);
    giq_option(1, NAME, 511, Node007, -1);
end

procedure Node006
begin
    Reply(600);
    giq_option(1, NAME, 610, Node010, -1);
    giq_option(1, NAME, 611, Node008, -1);
    giq_option(1, NAME, 612, Node999, -1);
end

procedure Node007
begin
    gsay_message(NAME, 700, GOOD_REACTION);
    set_map_var(32, 1);
end

procedure Node008
begin
    gsay_message(NAME, 800, GOOD_REACTION);
    set_map_var(33, game_time);
end

procedure Node009
begin
    gsay_message(NAME, 900, GOOD_REACTION);
    set_map_var(32, 1);
end

procedure Node010
begin
    which_dialog := "Node010";
    Reply(1000);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1010, Node011, -1);
        giq_option(1, NAME, 1011, Node011, -1);
        giq_option(1, NAME, 1012, Node011, -1);
        giq_option(1, NAME, 1013, Node011, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1014, Node013, -1);
        giq_option(1, NAME, 1015, Node011, -1);
        giq_option(1, NAME, 1016, Node011, -1);
        giq_option(1, NAME, 1017, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node011
begin
    gsay_message(NAME, 1100, GOOD_REACTION);
    set_map_var(32, 1);
end

procedure Node012
begin
    gsay_message(NAME, 1200, GOOD_REACTION);
    set_map_var(32, 1);
end

procedure Node013
begin
    which_dialog := "Node013";
    Reply(1300);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1310, Node014, -1);
        giq_option(1, NAME, 1311, Node011, -1);
        giq_option(1, NAME, 1312, Node011, -1);
        giq_option(1, NAME, 1313, Node011, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1314, Node011, -1);
        giq_option(1, NAME, 1315, Node011, -1);
        giq_option(1, NAME, 1316, Node011, -1);
        giq_option(1, NAME, 1317, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node014
begin
    which_dialog := "Node014";
    Reply(1400);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1410, Node011, -1);
        giq_option(1, NAME, 1411, Node011, -1);
        giq_option(1, NAME, 1412, Node015, -1);
        giq_option(1, NAME, 1413, Node011, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1414, Node011, -1);
        giq_option(1, NAME, 1415, Node011, -1);
        giq_option(1, NAME, 1416, Node011, -1);
        giq_option(1, NAME, 1417, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node015
begin
    which_dialog := "Node015";
    Reply(1500);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1510, Node011, -1);
        giq_option(1, NAME, 1511, Node011, -1);
        giq_option(1, NAME, 1512, Node016, -1);
        giq_option(1, NAME, 1513, Node011, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1514, Node011, -1);
        giq_option(1, NAME, 1515, Node011, -1);
        giq_option(1, NAME, 1516, Node011, -1);
        giq_option(1, NAME, 1517, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node016
begin
    which_dialog := "Node016";
    Reply(1700);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1710, Node011, -1);
        giq_option(1, NAME, 1711, Node011, -1);
        giq_option(1, NAME, 1712, Node011, -1);
        giq_option(1, NAME, 1713, Node017, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1714, Node011, -1);
        giq_option(1, NAME, 1715, Node011, -1);
        giq_option(1, NAME, 1716, Node011, -1);
        giq_option(1, NAME, 1717, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node017
begin
    which_dialog := "Node017";
    Reply(1600);
    if (dialog_part == 0) then begin
        giq_option(1, NAME, 1610, Node011, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 1) then begin
        giq_option(1, NAME, 1611, Node018, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 2) then begin
        giq_option(1, NAME, 1612, Node011, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 3) then begin
        giq_option(1, NAME, 1613, Node011, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 4) then begin
        giq_option(1, NAME, 1614, Node011, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 5) then begin
        giq_option(1, NAME, 1615, Node011, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
        giq_option(1, NAME, 2500, increase_menu, -1);
    end
    if (dialog_part == 6) then begin
        giq_option(1, NAME, 1616, Node011, -1);
        giq_option(1, NAME, 1617, Node012, -1);
        giq_option(1, NAME, 2501, decrease_menu, -1);
    end
end

procedure Node018
begin
    set_map_var(34, 1);
    gsay_message(NAME, 1800, GOOD_REACTION);
end

procedure Node019
begin
    Reply(1850);
    giq_option(1, NAME, 1851, Node999, -1);
    giq_option(1, NAME, 1852, redoing, -1);
end

procedure Node999
begin
end

procedure redoing
begin
    set_map_var(34, 3);
end

procedure increase_menu
begin
    dialog_part := dialog_part + 1;
    call which_dialog();
end

procedure decrease_menu
begin
    dialog_part := dialog_part - 1;
    call which_dialog();
end

procedure timed_event_p_proc
begin
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                if ((CUR_MAP_EPA2) or (CUR_MAP_EPAENT)) then begin
                    set_global_var(GVAR_LARS_MOTEL_QUEST, global_var(GVAR_LARS_MOTEL_QUEST) + -8);
                end
                else begin
                    set_global_var(GVAR_JOIN_ABBEY, global_var(GVAR_JOIN_ABBEY) + -8);
                end
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if ((CUR_MAP_EPA2) or (CUR_MAP_EPAENT)) then begin
            set_global_var(GVAR_LARS_MOTEL_QUEST, global_var(GVAR_LARS_MOTEL_QUEST) + -5);
        end
        else begin
            set_global_var(GVAR_JOIN_ABBEY, global_var(GVAR_JOIN_ABBEY) + -5);
        end
        debug_msg("Added " + -5 + " to Town Rep");
    end
end
