procedure start;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;


procedure start
begin
end

procedure use_p_proc
begin
    script_overrides;
    reg_anim_func(2, dude_obj);
    reg_anim_func(1, 1);
    reg_anim_animate(dude_obj, 25, -1);
    reg_anim_func(3, 0);
    display_mstr(101);
end

procedure look_at_p_proc
begin
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(100);
end
