import variable becky_guard_obj;

procedure def_pickup_p_proc;
procedure def_talk_p_proc;
procedure check_pickup;
procedure do_talk_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;

variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure Node998;
procedure Node999;
procedure NodePassLine;
procedure NodeDontPassLine;
procedure NodeComeLine;
procedure NodeDontComeLine;
procedure NodePropBet;
procedure NodePlaceBet;
procedure NodeFieldBet;
procedure Node001;
procedure NodeBet1;
procedure NodeBet2;
procedure NodeBet3;
procedure NodeBet4;
procedure NodeBet5;
procedure calculateTotal;
procedure getValue(variable arg0);
procedure exchangeCaps(variable arg0);
procedure Clear_All_Vars;

variable Only_Once;
variable betOption;
variable die1;
variable die2;
variable sayString;
variable canleave;
variable removePoint;

procedure NodeBet0;
procedure Node7_Prop;
procedure Node3s_Prop;
procedure Node4s_Prop;
procedure Node5s_Prop;
procedure Node2s_Prop;
procedure Node1_2_Prop;
procedure Node5_6_Prop;
procedure Node1_1_Prop;
procedure Node6_6_Prop;
procedure Node_Craps_Prop;
procedure NodeSingleProp;
procedure NodeHardwayProp;
procedure NodePlace4;
procedure NodePlace5;
procedure NodePlace6;
procedure NodePlace8;
procedure NodePlace9;
procedure NodePlace10;
procedure getNumVar(variable arg0);
procedure getOddsVar(variable arg0);
procedure set_number_bet(variable arg0, variable arg1);
procedure set_dont_number_bet(variable arg0, variable arg1);
procedure check_Pass_Line;
procedure check_Dont_Pass_Line;
procedure check_Come_Line;
procedure check_Dont_Come_Line;
procedure check_Prop_7;
procedure check_Prop_d3;
procedure check_Prop_d4;
procedure check_Prop_d5;
procedure check_Prop_d2;
procedure check_Prop_1_2;
procedure check_Prop_5_6;
procedure check_Prop_1_1;
procedure check_Prop_6_6;
procedure check_Prop_Craps;
procedure check_Place_4;
procedure check_Place_5;
procedure check_Place_6;
procedure check_Place_8;
procedure check_Place_9;
procedure check_Place_10;
procedure check_Field_Bet;
procedure calculateOdds(variable arg0);
procedure calculateDont(variable arg0);
procedure check_Num_4;
procedure check_Num_5;
procedure check_Num_6;
procedure check_Num_8;
procedure check_Num_9;
procedure check_Num_10;
procedure checkPoint;
procedure NodePayOff;
procedure superRandom(variable arg0, variable arg1);
procedure NodeRoll;
procedure NOdds04;
procedure NOdds14;
procedure NOdds24;
procedure NOdds34;
procedure NOdds05;
procedure NOdds15;
procedure NOdds25;
procedure NOdds35;
procedure NOdds06;
procedure NOdds16;
procedure NOdds26;
procedure NOdds36;
procedure NOdds08;
procedure NOdds18;
procedure NOdds28;
procedure NOdds38;
procedure NOdds09;
procedure NOdds19;
procedure NOdds29;
procedure NOdds39;
procedure NOdds010;
procedure NOdds110;
procedure NOdds210;
procedure NOdds310;
procedure NodeOdds4;
procedure NodeOdds5;
procedure NodeOdds6;
procedure NodeOdds8;
procedure NodeOdds9;
procedure NodeOdds10;
procedure NodeOdds;

variable caught_thief;
variable the_follow_obj;


procedure def_pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure def_talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 2;
    Karma_Perception := 1;
    start_gdialog(583, self_obj, 4, -1, -1);
    gsay_start;
    call Node001();
    gsay_end;
    end_dialogue;
end

procedure check_pickup
begin
    if ((source_obj == dude_obj) or (party_member_obj(obj_pid(source_obj)) != 0)) then begin
        caught_thief := 0;
        if (CUR_MAP_DENBUS1) then begin
            if (tile_in_tile_rect(16679, 16667, 19479, 19467, source_obj) and (becky_guard_obj != 0)) then begin
                metarule3(100, becky_guard_obj, 12, 0);
                add_timer_event(becky_guard_obj, 0, 12);
            end
        end
        if (caught_thief == 0) then begin
            call def_pickup_p_proc();
        end
    end
end

procedure do_talk_p_proc
begin
    if ((global_var(GVAR_DEN_FLAG_3) bwand 2048) != 0) then begin
        float_msg(self_obj, mstr(100), FLOAT_MSG_YELLOW);
    end
    else begin
        call def_talk_p_proc();
    end
end

procedure pickup_p_proc
begin
    call check_pickup();
end

procedure talk_p_proc
begin
    call do_talk_p_proc();
end

procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == 2) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - -15);
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_msg(message_str(SCRIPT_ZCCRPDEL, 100 + (1000 * (self_gender == 1))));
    end
    else begin
        display_msg(message_str(SCRIPT_ZCCRPDEL, 101));
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(SCRIPT_ZCCRPDEL, 102 + (1000 * (self_gender == 1))));
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(6, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 116);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS);
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    call Clear_All_Vars();
end

procedure NodePassLine
begin
    betOption := 1;
    gsay_reply(SCRIPT_ZCCRPDEL, 104);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure NodeDontPassLine
begin
    betOption := 2;
    gsay_reply(SCRIPT_ZCCRPDEL, 105);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure NodeComeLine
begin
    betOption := 4;
    gsay_reply(SCRIPT_ZCCRPDEL, 106);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure NodeDontComeLine
begin
    betOption := 5;
    gsay_reply(SCRIPT_ZCCRPDEL, 107);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure NodePropBet
begin
    gsay_reply(SCRIPT_ZCCRPDEL, 156);
    giq_option(1, SCRIPT_ZCCRPDEL, 154, NodeSingleProp, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 155, NodeHardwayProp, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlaceBet
begin
    gsay_reply(SCRIPT_ZCCRPDEL, 299);
    giq_option(1, SCRIPT_ZCCRPDEL, 300, NodePlace4, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 301, NodePlace5, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 302, NodePlace6, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 303, NodePlace8, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 304, NodePlace9, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 305, NodePlace10, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeFieldBet
begin
    betOption := 3;
    gsay_reply(SCRIPT_ZCCRPDEL, 108);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure Node001
begin
    call calculateTotal();
    sayString := "";
    if (local_var(40) == 0) then begin
        gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 103) + " " + (message_str(SCRIPT_ZCCRPDEL, 109) + " " + local_var(40) + ". " + message_str(SCRIPT_ZCCRPDEL, 139) + getValue(28) + " " + message_str(SCRIPT_ZCCRPDEL, 145) + local_var(34) + " " + message_str(SCRIPT_ZCCRPDEL, 140) + getValue(29) + " " + message_str(SCRIPT_ZCCRPDEL, 146) + local_var(35) + " " + message_str(SCRIPT_ZCCRPDEL, 141) + getValue(30) + " " + message_str(SCRIPT_ZCCRPDEL, 147) + local_var(36) + " " + message_str(SCRIPT_ZCCRPDEL, 142) + getValue(31) + " " + message_str(SCRIPT_ZCCRPDEL, 148) + local_var(37) + " " + message_str(SCRIPT_ZCCRPDEL, 143) + getValue(32) + " " + message_str(SCRIPT_ZCCRPDEL, 149) + local_var(38) + " " + message_str(SCRIPT_ZCCRPDEL, 144) + getValue(33) + " " + message_str(SCRIPT_ZCCRPDEL, 150) + local_var(39)));
        if (local_var(7) == 0) then begin
            giq_option(1, SCRIPT_ZCCRPDEL, 110, NodePassLine, NEUTRAL_REACTION);
        end
        else begin
            giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 119) + local_var(7), NodePassLine, NEUTRAL_REACTION);
        end
    end
    else begin
        gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 109) + " " + local_var(40) + ". " + message_str(SCRIPT_ZCCRPDEL, 139) + getValue(28) + " " + message_str(SCRIPT_ZCCRPDEL, 145) + local_var(34) + " " + message_str(SCRIPT_ZCCRPDEL, 140) + getValue(29) + " " + message_str(SCRIPT_ZCCRPDEL, 146) + local_var(35) + " " + message_str(SCRIPT_ZCCRPDEL, 141) + getValue(30) + " " + message_str(SCRIPT_ZCCRPDEL, 147) + local_var(36) + " " + message_str(SCRIPT_ZCCRPDEL, 142) + getValue(31) + " " + message_str(SCRIPT_ZCCRPDEL, 148) + local_var(37) + " " + message_str(SCRIPT_ZCCRPDEL, 143) + getValue(32) + " " + message_str(SCRIPT_ZCCRPDEL, 149) + local_var(38) + " " + message_str(SCRIPT_ZCCRPDEL, 144) + getValue(33) + " " + message_str(SCRIPT_ZCCRPDEL, 150) + local_var(39));
        if (local_var(9) == 0) then begin
            giq_option(1, SCRIPT_ZCCRPDEL, 112, NodeComeLine, NEUTRAL_REACTION);
        end
        else begin
            giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 121) + local_var(9), NodeComeLine, NEUTRAL_REACTION);
        end
        giq_option(1, SCRIPT_ZCCRPDEL, 800, NodeOdds, NEUTRAL_REACTION);
    end
    if ((local_var(11) or local_var(12) or local_var(13) or local_var(14) or local_var(15) or local_var(16) or local_var(17) or local_var(18) or local_var(19) or local_var(20)) == 0) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 114, NodePropBet, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 123) + local_var(11) + " " + message_str(SCRIPT_ZCCRPDEL, 124) + local_var(12) + " " + message_str(SCRIPT_ZCCRPDEL, 125) + local_var(13) + " " + message_str(SCRIPT_ZCCRPDEL, 126) + local_var(14) + " " + message_str(SCRIPT_ZCCRPDEL, 127) + local_var(15) + " " + message_str(SCRIPT_ZCCRPDEL, 128) + local_var(16) + " " + message_str(SCRIPT_ZCCRPDEL, 129) + local_var(17) + " " + message_str(SCRIPT_ZCCRPDEL, 130) + local_var(18) + " " + message_str(SCRIPT_ZCCRPDEL, 131) + local_var(19) + " " + message_str(SCRIPT_ZCCRPDEL, 132) + local_var(20), NodePropBet, NEUTRAL_REACTION);
    end
    if ((local_var(21) or local_var(22) or local_var(23) or local_var(24) or local_var(25) or local_var(26)) == 0) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 115, NodePlaceBet, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 133) + local_var(21) + " " + message_str(SCRIPT_ZCCRPDEL, 134) + local_var(22) + " " + message_str(SCRIPT_ZCCRPDEL, 135) + local_var(23) + " " + message_str(SCRIPT_ZCCRPDEL, 136) + local_var(24) + " " + message_str(SCRIPT_ZCCRPDEL, 137) + local_var(25) + " " + message_str(SCRIPT_ZCCRPDEL, 138) + local_var(26), NodePlaceBet, NEUTRAL_REACTION);
    end
    if (local_var(27) == 0) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 116, NodeFieldBet, NEUTRAL_REACTION);
    end
    else begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 151) + local_var(27), NodeFieldBet, NEUTRAL_REACTION);
    end
    if (local_var(41) > 0) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 118, NodeRoll, NEUTRAL_REACTION);
    end
    if ((local_var(28) or local_var(29) or local_var(30) or local_var(31) or local_var(32) or local_var(33)) == 0) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 712, Node999, NEUTRAL_REACTION);
    end
end

procedure NodeBet1
begin
    if (betOption == 1) then begin
        set_local_var(7, 5);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 5);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 5);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 5);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 5);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 5);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 5);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 5);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 5);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 5);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 5);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 5);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 5);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 5);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 5);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 10);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 10);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 10);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 10);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 10);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 10);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure NodeBet2
begin
    if (betOption == 1) then begin
        set_local_var(7, 10);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 10);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 10);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 10);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 10);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 10);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 10);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 10);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 10);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 10);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 10);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 10);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 10);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 10);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 10);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 10);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 10);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 10);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 10);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 10);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 10);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure NodeBet3
begin
    if (betOption == 1) then begin
        set_local_var(7, 15);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 15);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 15);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 15);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 15);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 15);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 15);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 15);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 15);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 15);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 15);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 15);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 15);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 15);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 15);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 15);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 15);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 15);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 15);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 15);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 15);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure NodeBet4
begin
    if (betOption == 1) then begin
        set_local_var(7, 20);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 20);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 20);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 20);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 20);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 20);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 20);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 20);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 20);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 20);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 20);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 20);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 20);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 20);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 20);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 20);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 20);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 20);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 20);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 20);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 20);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure NodeBet5
begin
    if (betOption == 1) then begin
        set_local_var(7, 100);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 100);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 100);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 100);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 100);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 100);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 100);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 100);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 100);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 100);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 100);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 100);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 100);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 100);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 100);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 100);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 100);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 100);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 100);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 100);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 100);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure calculateTotal
begin
    set_local_var(41, local_var(7) + local_var(8) + local_var(9) + local_var(10) + local_var(11) + local_var(12) + local_var(13) + local_var(14) + local_var(15) + local_var(16) + local_var(17) + local_var(18) + local_var(19) + local_var(20) + local_var(21) + local_var(22) + local_var(23) + local_var(24) + local_var(25) + local_var(26) + local_var(27) + local_var(28) + local_var(29) + local_var(30) + local_var(31) + local_var(32) + local_var(33) + local_var(34) + local_var(35) + local_var(36) + local_var(37) + local_var(38) + local_var(39));
end

procedure getValue(variable arg0)
begin
    return local_var(arg0);
end

procedure exchangeCaps(variable arg0)
begin
    arg0 := floor(arg0);
    debug_msg("ZCCRPDEL: giving player: " + arg0);
    item_caps_adjust(dude_obj, arg0);
end

procedure Clear_All_Vars
begin
    set_local_var(7, 0);
    set_local_var(8, 0);
    set_local_var(9, 0);
    set_local_var(10, 0);
    set_local_var(11, 0);
    set_local_var(12, 0);
    set_local_var(13, 0);
    set_local_var(14, 0);
    set_local_var(15, 0);
    set_local_var(16, 0);
    set_local_var(17, 0);
    set_local_var(18, 0);
    set_local_var(19, 0);
    set_local_var(20, 0);
    set_local_var(21, 0);
    set_local_var(22, 0);
    set_local_var(23, 0);
    set_local_var(24, 0);
    set_local_var(25, 0);
    set_local_var(26, 0);
    set_local_var(27, 0);
    set_local_var(28, 0);
    set_local_var(29, 0);
    set_local_var(30, 0);
    set_local_var(31, 0);
    set_local_var(32, 0);
    set_local_var(33, 0);
    set_local_var(34, 0);
    set_local_var(35, 0);
    set_local_var(36, 0);
    set_local_var(37, 0);
    set_local_var(38, 0);
    set_local_var(39, 0);
    set_local_var(40, 0);
    set_local_var(41, 0);
end

procedure NodeBet0
begin
    if (betOption == 1) then begin
        set_local_var(7, 0);
    end
    else begin
        if (betOption == 2) then begin
            set_local_var(8, 0);
        end
        else begin
            if (betOption == 3) then begin
                set_local_var(27, 0);
            end
            else begin
                if (betOption == 4) then begin
                    set_local_var(9, 0);
                end
                else begin
                    if (betOption == 5) then begin
                        set_local_var(10, 0);
                    end
                    else begin
                        if (betOption == 6) then begin
                            set_local_var(20, 0);
                        end
                        else begin
                            if (betOption == 7) then begin
                                set_local_var(19, 0);
                            end
                            else begin
                                if (betOption == 8) then begin
                                    set_local_var(18, 0);
                                end
                                else begin
                                    if (betOption == 9) then begin
                                        set_local_var(16, 0);
                                    end
                                    else begin
                                        if (betOption == 10) then begin
                                            set_local_var(17, 0);
                                        end
                                        else begin
                                            if (betOption == 11) then begin
                                                set_local_var(15, 0);
                                            end
                                            else begin
                                                if (betOption == 12) then begin
                                                    set_local_var(14, 0);
                                                end
                                                else begin
                                                    if (betOption == 13) then begin
                                                        set_local_var(13, 0);
                                                    end
                                                    else begin
                                                        if (betOption == 14) then begin
                                                            set_local_var(12, 0);
                                                        end
                                                        else begin
                                                            if (betOption == 15) then begin
                                                                set_local_var(11, 0);
                                                            end
                                                            else begin
                                                                if (betOption == 16) then begin
                                                                    set_local_var(21, 0);
                                                                end
                                                                else begin
                                                                    if (betOption == 17) then begin
                                                                        set_local_var(22, 0);
                                                                    end
                                                                    else begin
                                                                        if (betOption == 18) then begin
                                                                            set_local_var(23, 0);
                                                                        end
                                                                        else begin
                                                                            if (betOption == 19) then begin
                                                                                set_local_var(24, 0);
                                                                            end
                                                                            else begin
                                                                                if (betOption == 20) then begin
                                                                                    set_local_var(25, 0);
                                                                                end
                                                                                else begin
                                                                                    if (betOption == 21) then begin
                                                                                        set_local_var(26, 0);
                                                                                    end
                                                                                end
                                                                            end
                                                                        end
                                                                    end
                                                                end
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node001();
end

procedure Node7_Prop
begin
    betOption := 15;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node3s_Prop
begin
    betOption := 14;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node4s_Prop
begin
    betOption := 13;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node5s_Prop
begin
    betOption := 12;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node2s_Prop
begin
    betOption := 11;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node1_2_Prop
begin
    betOption := 9;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node5_6_Prop
begin
    betOption := 10;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node1_1_Prop
begin
    betOption := 8;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node6_6_Prop
begin
    betOption := 7;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 713), Node001, NEUTRAL_REACTION);
end

procedure Node_Craps_Prop
begin
    betOption := 6;
    gsay_reply(SCRIPT_ZCCRPDEL, 153);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeSingleProp
begin
    gsay_reply(SCRIPT_ZCCRPDEL, 152);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 200) + ": " + local_var(11), Node7_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 205) + ": " + local_var(16), Node1_2_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 206) + ": " + local_var(17), Node5_6_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 207) + ": " + local_var(18), Node1_1_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 208) + ": " + local_var(19), Node6_6_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 209) + ": " + local_var(20), Node_Craps_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeHardwayProp
begin
    gsay_reply(SCRIPT_ZCCRPDEL, 152);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 201) + ": " + local_var(12), Node3s_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 202) + ": " + local_var(13), Node4s_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 203) + ": " + local_var(14), Node5s_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 204) + ": " + local_var(15), Node2s_Prop, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace4
begin
    betOption := 16;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace5
begin
    betOption := 17;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace6
begin
    betOption := 18;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace8
begin
    betOption := 19;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace9
begin
    betOption := 20;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodePlace10
begin
    betOption := 21;
    gsay_reply(SCRIPT_ZCCRPDEL, 157);
    giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 0 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet0, NEUTRAL_REACTION);
    if ((item_caps_total(dude_obj) - local_var(41)) > 5) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 5 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet1, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 10) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 10 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet2, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 15) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 15 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet3, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 20) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 20 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet4, NEUTRAL_REACTION);
    end
    if ((item_caps_total(dude_obj) - local_var(41)) > 100) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 500) + 100 + message_str(SCRIPT_ZCCRPDEL, 501), NodeBet5, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure getNumVar(variable arg0)
begin
    if (arg0 == 4) then begin
        return 28;
    end
    if (arg0 == 5) then begin
        return 29;
    end
    if (arg0 == 6) then begin
        return 30;
    end
    if (arg0 == 8) then begin
        return 31;
    end
    if (arg0 == 9) then begin
        return 32;
    end
    if (arg0 == 10) then begin
        return 33;
    end
end

procedure getOddsVar(variable arg0)
begin
    if (arg0 == 4) then begin
        return 34;
    end
    if (arg0 == 5) then begin
        return 35;
    end
    if (arg0 == 6) then begin
        return 36;
    end
    if (arg0 == 8) then begin
        return 37;
    end
    if (arg0 == 9) then begin
        return 38;
    end
    if (arg0 == 10) then begin
        return 39;
    end
end

procedure set_number_bet(variable arg0, variable arg1)
begin
    variable LVar2 := 0;
    LVar2 := getNumVar(arg0);
    set_local_var(LVar2, arg1);
end

procedure set_dont_number_bet(variable arg0, variable arg1)
begin
    variable LVar2 := 0;
    LVar2 := getNumVar(arg0);
    set_local_var(LVar2, arg1);
    set_local_var(LVar2, local_var(LVar2) bwor --2147483648);
end

procedure check_Pass_Line
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    debug_msg("ZCCRPDEL: checking pass line totol die rolls: " + LVar0);
    if (local_var(40) == 0) then begin
        if (LVar0 == 7) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 600) + " ");
            call exchangeCaps(local_var(7));
            set_local_var(7, 0);
        end
        else begin
            if (LVar0 == 11) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 601) + " ");
                call exchangeCaps(local_var(7));
                set_local_var(7, 0);
            end
            else begin
                if (LVar0 == 2) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 602) + " ");
                    call exchangeCaps(-local_var(7));
                    set_local_var(7, 0);
                end
                else begin
                    if (LVar0 == 3) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 603) + " ");
                        call exchangeCaps(-local_var(7));
                        set_local_var(7, 0);
                    end
                    else begin
                        if (LVar0 == 12) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 604) + " ");
                            call exchangeCaps(-local_var(7));
                            set_local_var(7, 0);
                        end
                        else begin
                            removePoint := 0;
                            set_local_var(40, LVar0);
                            call set_number_bet(LVar0, local_var(7));
                            set_local_var(7, 0);
                        end
                    end
                end
            end
        end
    end
end

procedure check_Dont_Pass_Line
begin
    variable LVar0 := 0;
    if (local_var(40) == 0) then begin
        LVar0 := die1 + die2;
        if (local_var(8) > 0) then begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 610) + " ");
                call exchangeCaps(-local_var(8));
                set_local_var(8, 0);
            end
            else begin
                if (LVar0 == 11) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 611) + " ");
                    call exchangeCaps(-local_var(8));
                    set_local_var(8, 0);
                end
                else begin
                    if (LVar0 == 2) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 612) + " ");
                        call exchangeCaps(local_var(8));
                        set_local_var(8, 0);
                    end
                    else begin
                        if (LVar0 == 3) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 613) + " ");
                            call exchangeCaps(local_var(8));
                            item_caps_adjust(dude_obj, local_var(8));
                            set_local_var(8, 0);
                        end
                        else begin
                            if (LVar0 == 12) then begin
                                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 614) + " ");
                                set_local_var(8, 0);
                            end
                            else begin
                                set_local_var(40, LVar0);
                                call set_dont_number_bet(LVar0, local_var(8));
                                set_local_var(8, 0);
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure check_Come_Line
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(9) > 0) then begin
        if (LVar0 == 7) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 600) + " ");
            call exchangeCaps(local_var(9));
            set_local_var(9, 0);
        end
        else begin
            if (LVar0 == 11) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 601) + " ");
                call exchangeCaps(local_var(9));
                set_local_var(9, 0);
            end
            else begin
                if (LVar0 == 2) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 602) + " ");
                    call exchangeCaps(-local_var(9));
                    set_local_var(9, 0);
                end
                else begin
                    if (LVar0 == 3) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 603) + " ");
                        call exchangeCaps(-local_var(9));
                        set_local_var(9, 0);
                    end
                    else begin
                        if (LVar0 == 12) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 604) + " ");
                            call exchangeCaps(-local_var(9));
                            set_local_var(9, 0);
                        end
                        else begin
                            call set_number_bet(LVar0, local_var(9));
                            set_local_var(9, 0);
                        end
                    end
                end
            end
        end
    end
end

procedure check_Dont_Come_Line
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(10) > 0) then begin
        if (LVar0 == 7) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 610) + " ");
            call exchangeCaps(-local_var(10));
            set_local_var(10, 0);
        end
        else begin
            if (LVar0 == 11) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 611) + " ");
                call exchangeCaps(-local_var(10));
                set_local_var(10, 0);
            end
            else begin
                if (LVar0 == 2) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 612) + " ");
                    call exchangeCaps(local_var(10));
                    set_local_var(10, 0);
                end
                else begin
                    if (LVar0 == 3) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 613) + " ");
                        call exchangeCaps(local_var(10));
                        set_local_var(10, 0);
                    end
                    else begin
                        if (LVar0 == 12) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 614) + " ");
                            set_local_var(10, 0);
                        end
                        else begin
                            call set_dont_number_bet(LVar0, local_var(10));
                            set_local_var(10, 0);
                        end
                    end
                end
            end
        end
    end
end

procedure check_Prop_7
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(11)) then begin
        if (LVar0 == 7) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 620) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(11) * 5);
            set_local_var(11, 0);
        end
        else begin
            if (LVar0 != 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 620) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(11));
                set_local_var(11, 0);
            end
        end
    end
end

procedure check_Prop_d3
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(12)) then begin
        if ((die1 == 3) and (die2 == 3)) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 621) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(12) * 9);
            set_local_var(12, 0);
        end
        else begin
            if ((LVar0 == 6) or ((LVar0 == 7) or (LVar0 == 11) and (local_var(40) == 0))) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 621) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(12));
                set_local_var(12, 0);
            end
        end
    end
end

procedure check_Prop_d4
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(13)) then begin
        if ((die1 == 4) and (die2 == 4)) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 622) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(13) * 9);
            set_local_var(13, 0);
        end
        else begin
            if ((LVar0 == 8) or ((LVar0 == 7) or (LVar0 == 11) and (local_var(40) == 0))) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 622) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(13));
                set_local_var(13, 0);
            end
        end
    end
end

procedure check_Prop_d5
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(14)) then begin
        if ((die1 == 5) and (die2 == 5)) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 623) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(14) * 7);
            set_local_var(14, 0);
        end
        else begin
            if ((LVar0 == 10) or ((LVar0 == 7) or (LVar0 == 11) and (local_var(40) == 0))) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 623) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(14));
                set_local_var(14, 0);
            end
        end
    end
end

procedure check_Prop_d2
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(15)) then begin
        if ((die1 == 2) and (die2 == 2)) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 624) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(15) * 7);
            set_local_var(15, 0);
        end
        else begin
            if ((LVar0 == 4) or ((LVar0 == 7) or (LVar0 == 11) and (local_var(40) == 0))) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 624) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(15));
                set_local_var(15, 0);
            end
        end
    end
end

procedure check_Prop_1_2
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(16)) then begin
        if (LVar0 == 3) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 625) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(16) * 15);
            set_local_var(16, 0);
        end
        else begin
            if (LVar0 != 3) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 625) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(16));
                set_local_var(16, 0);
            end
        end
    end
end

procedure check_Prop_5_6
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(17)) then begin
        if (LVar0 == 11) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 626) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(17) * 15);
            set_local_var(17, 0);
        end
        else begin
            if (LVar0 != 11) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 626) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(17));
                set_local_var(17, 0);
            end
        end
    end
end

procedure check_Prop_1_1
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(18)) then begin
        if (LVar0 == 2) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 627) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(18) * 30);
            set_local_var(18, 0);
        end
        else begin
            if (LVar0 != 2) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 627) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(18));
                set_local_var(18, 0);
            end
        end
    end
end

procedure check_Prop_6_6
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(19)) then begin
        if (LVar0 == 12) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 628) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(19) * 30);
            set_local_var(19, 0);
        end
        else begin
            if (LVar0 != 12) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 628) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(19));
                set_local_var(19, 0);
            end
        end
    end
end

procedure check_Prop_Craps
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(20)) then begin
        if ((LVar0 == 2) or (LVar0 == 3) or (LVar0 == 12)) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 629) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(20) * 7);
            set_local_var(20, 0);
        end
        else begin
            if ((LVar0 != 2) or (LVar0 != 3) or (LVar0 != 12)) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 629) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(20));
                set_local_var(20, 0);
            end
        end
    end
end

procedure check_Place_4
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(21)) then begin
        if (LVar0 == 4) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 650) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(21) * 1.80000);
            set_local_var(21, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 650) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(21));
                set_local_var(21, 0);
            end
        end
    end
end

procedure check_Place_5
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(22)) then begin
        if (LVar0 == 5) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 651) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(22) * 1.50000);
            set_local_var(22, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 651) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(22));
                set_local_var(22, 0);
            end
        end
    end
end

procedure check_Place_6
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(23)) then begin
        if (LVar0 == 6) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 652) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(23) * 1.16000);
            set_local_var(23, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 652) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(23));
                set_local_var(23, 0);
            end
        end
    end
end

procedure check_Place_8
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(24)) then begin
        if (LVar0 == 8) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 653) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(24) * 1.16000);
            set_local_var(24, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 653) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(24));
                set_local_var(24, 0);
            end
        end
    end
end

procedure check_Place_9
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(25)) then begin
        if (LVar0 == 9) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 654) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(25) * 1.50000);
            set_local_var(25, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 654) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(25));
                set_local_var(25, 0);
            end
        end
    end
end

procedure check_Place_10
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(26)) then begin
        if (LVar0 == 10) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 655) + " ");
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 631) + " ");
            call exchangeCaps(local_var(26) * 1.80000);
            set_local_var(26, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 655) + " ");
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                call exchangeCaps(-local_var(26));
                set_local_var(26, 0);
            end
        end
    end
end

procedure check_Field_Bet
begin
    variable LVar0 := 0;
    LVar0 := die1 + die2;
    if (local_var(27)) then begin
        if (LVar0 == 2) then begin
            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 660) + " ");
            call exchangeCaps(local_var(27) * 2);
        end
        else begin
            if (LVar0 == 3) then begin
                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 661) + " ");
                call exchangeCaps(local_var(27));
            end
            else begin
                if (LVar0 == 4) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 662) + " ");
                    call exchangeCaps(local_var(27));
                end
                else begin
                    if (LVar0 == 9) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 663) + " ");
                        call exchangeCaps(local_var(27));
                    end
                    else begin
                        if (LVar0 == 10) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 664) + " ");
                            call exchangeCaps(local_var(27));
                        end
                        else begin
                            if (LVar0 == 11) then begin
                                sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 665) + " ");
                                call exchangeCaps(local_var(27));
                            end
                            else begin
                                if (LVar0 == 12) then begin
                                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 666) + " ");
                                    call exchangeCaps(local_var(27) * 3);
                                end
                                else begin
                                    sayString := sayString + message_str(SCRIPT_ZCCRPDEL, 667);
                                    call exchangeCaps(-local_var(27));
                                end
                            end
                        end
                    end
                end
            end
        end
        set_local_var(27, 0);
    end
end

procedure calculateOdds(variable arg0)
begin
    if ((arg0 == 4) or (arg0 == 10)) then begin
        return 2;
    end
    if ((arg0 == 5) or (arg0 == 9)) then begin
        return 1.50000;
    end
    if ((arg0 == 6) or (arg0 == 8)) then begin
        return 1.20000;
    end
end

procedure calculateDont(variable arg0)
begin
    if ((arg0 == 4) or (arg0 == 10)) then begin
        return 0.50000;
    end
    if ((arg0 == 5) or (arg0 == 9)) then begin
        return 0.66600;
    end
    if ((arg0 == 6) or (arg0 == 8)) then begin
        return 0.83300;
    end
end

procedure check_Num_4
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(28)) then begin
        if (local_var(28) bwand --2147483648) then begin
            local_var(28);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(28);
            LVar1 := 0;
        end
        if (LVar0 == 4) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(34)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(34) * calculateOdds(4));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(34)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(34));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(34)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(34)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(28, 0);
            set_local_var(34, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(34)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(34));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(34)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(34) * calculateDont(4));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(34)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 670) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(34)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 680) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(28, 0);
                set_local_var(34, 0);
            end
        end
    end
end

procedure check_Num_5
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(29)) then begin
        if (local_var(29) bwand --2147483648) then begin
            local_var(29);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(29);
            LVar1 := 0;
        end
        if (LVar0 == 5) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(35)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(35) * calculateOdds(5));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(35)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(35));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(35)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(35)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(29, 0);
            set_local_var(35, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(35)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(35));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(35)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(35) * calculateDont(5));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(35)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 671) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(35)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 681) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(29, 0);
                set_local_var(35, 0);
            end
        end
    end
end

procedure check_Num_6
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(30)) then begin
        if (local_var(30) bwand --2147483648) then begin
            local_var(30);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(30);
            LVar1 := 0;
        end
        if (LVar0 == 6) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(36)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(36) * calculateOdds(6));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(36)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(36));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(36)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(36)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(30, 0);
            set_local_var(36, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(36)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(36));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(36)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(36) * calculateDont(6));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(36)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 672) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(36)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 682) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(30, 0);
                set_local_var(36, 0);
            end
        end
    end
end

procedure check_Num_8
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(31)) then begin
        if (local_var(31) bwand --2147483648) then begin
            local_var(31);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(31);
            LVar1 := 0;
        end
        if (LVar0 == 8) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(37)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(37) * calculateOdds(8));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(37)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(37));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(37)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(37)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(31, 0);
            set_local_var(37, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(37)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(37));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(37)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(37) * calculateDont(8));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(37)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 673) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(37)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 683) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(31, 0);
                set_local_var(37, 0);
            end
        end
    end
end

procedure check_Num_9
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(32)) then begin
        if (local_var(32) bwand --2147483648) then begin
            local_var(32);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(32);
            LVar1 := 0;
        end
        if (LVar0 == 9) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(38)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(38) * calculateOdds(9));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(38)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(38));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(38)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(38)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(32, 0);
            set_local_var(38, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(38)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(38));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(38)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(38) * calculateDont(9));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(38)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 674) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(38)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 684) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(32, 0);
                set_local_var(38, 0);
            end
        end
    end
end

procedure check_Num_10
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    LVar0 := die1 + die2;
    if (local_var(33)) then begin
        if (local_var(33) bwand --2147483648) then begin
            local_var(33);
            LVar2 := --2147483648;
            LVar1 := 1;
        end
        else begin
            LVar2 := local_var(33);
            LVar1 := 0;
        end
        if (LVar0 == 10) then begin
            if (local_var(40)) then begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(39)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(local_var(39) * calculateOdds(10));
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(39)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-local_var(39));
                    end
                end
            end
            else begin
                if (LVar1 == 0) then begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                    call exchangeCaps(LVar2);
                    if (local_var(39)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
                else begin
                    sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                    call exchangeCaps(-LVar2);
                    if (local_var(39)) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                    end
                end
            end
            if (local_var(40) == LVar0) then begin
                debug_msg("ZCCRPDEL: uhh removing point: " + local_var(40) + " total " + LVar0);
                removePoint := 1;
            end
            set_local_var(33, 0);
            set_local_var(39, 0);
        end
        else begin
            if (LVar0 == 7) then begin
                if (local_var(40)) then begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(39)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                            call exchangeCaps(-local_var(39));
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(39)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                            call exchangeCaps(local_var(39) * calculateDont(10));
                        end
                    end
                end
                else begin
                    if (LVar1 == 0) then begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 630) + " ");
                        call exchangeCaps(-LVar2);
                        if (local_var(39)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 701) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 700) + " ");
                        end
                    end
                    else begin
                        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 675) + " " + message_str(SCRIPT_ZCCRPDEL, 631) + " ");
                        call exchangeCaps(LVar2);
                        if (local_var(39)) then begin
                            sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 702) + ":" + message_str(SCRIPT_ZCCRPDEL, 685) + " " + message_str(SCRIPT_ZCCRPDEL, 702) + " ");
                        end
                    end
                end
                removePoint := 1;
                set_local_var(33, 0);
                set_local_var(39, 0);
            end
        end
    end
end

procedure checkPoint
begin
    if (removePoint) then begin
        removePoint := 0;
        set_local_var(40, 0);
    end
    if (local_var(40)) then begin
        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 109) + " " + local_var(40) + " ");
    end
    else begin
        sayString := sayString + (message_str(SCRIPT_ZCCRPDEL, 714) + " ");
    end
end

procedure NodePayOff
begin
    call check_Prop_7();
    call check_Prop_d3();
    call check_Prop_d4();
    call check_Prop_d5();
    call check_Prop_d2();
    call check_Prop_1_2();
    call check_Prop_5_6();
    call check_Prop_1_1();
    call check_Prop_6_6();
    call check_Prop_Craps();
    call check_Place_4();
    call check_Place_5();
    call check_Place_6();
    call check_Place_8();
    call check_Place_9();
    call check_Place_10();
    call check_Field_Bet();
    call check_Num_4();
    call check_Num_5();
    call check_Num_6();
    call check_Num_8();
    call check_Num_9();
    call check_Num_10();
    call check_Pass_Line();
    call check_Dont_Pass_Line();
    call check_Come_Line();
    call check_Dont_Come_Line();
    call checkPoint();
    gsay_reply(SCRIPT_ZCCRPDEL, sayString);
    giq_option(1, SCRIPT_ZCCRPDEL, g_mstr(352), Node001, NEUTRAL_REACTION);
end

procedure superRandom(variable arg0, variable arg1)
begin
    variable LVar2 := 0;
    variable LVar3 := 0;
    variable LVar4 := 0;
    variable LVar5 := 0;
    LVar2 := random(25, 55);
    LVar5 := random(arg0, arg1);
    while (LVar3 < LVar2) do begin
        LVar5 := random(arg0, arg1);
        if (random(0, 1)) then begin
            LVar4 := LVar5;
        end
        LVar3 := LVar3 + 1;
    end
    return LVar4;
end

procedure NodeRoll
begin
    if (local_var(41) > item_caps_total(dude_obj)) then begin
        gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 154) + local_var(41));
        giq_option(0, SCRIPT_ZCCRPDEL, g_mstr(352), Node001, NEUTRAL_REACTION);
    end
    else begin
        play_sfx("dice");
        die1 := superRandom(1, 6);
        die2 := superRandom(1, 6);
        gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 710) + " " + die1 + " " + message_str(SCRIPT_ZCCRPDEL, 711) + " " + die2);
        giq_option(1, SCRIPT_ZCCRPDEL, g_mstr(352), NodePayOff, NEUTRAL_REACTION);
    end
end

procedure NOdds04
begin
    set_local_var(getOddsVar(4), local_var(getNumVar(4)) * 0);
    call Node001();
end

procedure NOdds14
begin
    set_local_var(getOddsVar(4), local_var(getNumVar(4)) * 1);
    call Node001();
end

procedure NOdds24
begin
    set_local_var(getOddsVar(4), local_var(getNumVar(4)) * 2);
    call Node001();
end

procedure NOdds34
begin
    set_local_var(getOddsVar(4), local_var(getNumVar(4)) * 3);
    call Node001();
end

procedure NOdds05
begin
    set_local_var(getOddsVar(5), local_var(getNumVar(5)) * 0);
    call Node001();
end

procedure NOdds15
begin
    set_local_var(getOddsVar(5), local_var(getNumVar(5)) * 1);
    call Node001();
end

procedure NOdds25
begin
    set_local_var(getOddsVar(5), local_var(getNumVar(5)) * 2);
    call Node001();
end

procedure NOdds35
begin
    set_local_var(getOddsVar(5), local_var(getNumVar(5)) * 3);
    call Node001();
end

procedure NOdds06
begin
    set_local_var(getOddsVar(6), local_var(getNumVar(6)) * 0);
    call Node001();
end

procedure NOdds16
begin
    set_local_var(getOddsVar(6), local_var(getNumVar(6)) * 1);
    call Node001();
end

procedure NOdds26
begin
    set_local_var(getOddsVar(6), local_var(getNumVar(6)) * 2);
    call Node001();
end

procedure NOdds36
begin
    set_local_var(getOddsVar(6), local_var(getNumVar(6)) * 3);
    call Node001();
end

procedure NOdds08
begin
    set_local_var(getOddsVar(8), local_var(getNumVar(8)) * 0);
    call Node001();
end

procedure NOdds18
begin
    set_local_var(getOddsVar(8), local_var(getNumVar(8)) * 1);
    call Node001();
end

procedure NOdds28
begin
    set_local_var(getOddsVar(8), local_var(getNumVar(8)) * 2);
    call Node001();
end

procedure NOdds38
begin
    set_local_var(getOddsVar(8), local_var(getNumVar(8)) * 3);
    call Node001();
end

procedure NOdds09
begin
    set_local_var(getOddsVar(9), local_var(getNumVar(9)) * 0);
    call Node001();
end

procedure NOdds19
begin
    set_local_var(getOddsVar(9), local_var(getNumVar(9)) * 1);
    call Node001();
end

procedure NOdds29
begin
    set_local_var(getOddsVar(9), local_var(getNumVar(9)) * 2);
    call Node001();
end

procedure NOdds39
begin
    set_local_var(getOddsVar(9), local_var(getNumVar(9)) * 3);
    call Node001();
end

procedure NOdds010
begin
    set_local_var(getOddsVar(10), local_var(getNumVar(10)) * 0);
    call Node001();
end

procedure NOdds110
begin
    set_local_var(getOddsVar(10), local_var(getNumVar(10)) * 1);
    call Node001();
end

procedure NOdds210
begin
    set_local_var(getOddsVar(10), local_var(getNumVar(10)) * 2);
    call Node001();
end

procedure NOdds310
begin
    set_local_var(getOddsVar(10), local_var(getNumVar(10)) * 3);
    call Node001();
end

procedure NodeOdds4
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(4)) * 1;
    LVar2 := local_var(getNumVar(4)) * 2;
    LVar3 := local_var(getNumVar(4)) * 3;
    LVar0 := local_var(getOddsVar(4));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 4 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds04, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds14, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds24, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds34, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds5
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(5)) * 1;
    LVar2 := local_var(getNumVar(5)) * 2;
    LVar3 := local_var(getNumVar(5)) * 3;
    LVar0 := local_var(getOddsVar(5));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 5 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds05, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds15, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds25, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds35, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds6
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(6)) * 1;
    LVar2 := local_var(getNumVar(6)) * 2;
    LVar3 := local_var(getNumVar(6)) * 3;
    LVar0 := local_var(getOddsVar(6));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 6 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds06, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds16, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds26, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds36, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds8
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(8)) * 1;
    LVar2 := local_var(getNumVar(8)) * 2;
    LVar3 := local_var(getNumVar(8)) * 3;
    LVar0 := local_var(getOddsVar(8));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 8 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds08, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds18, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds28, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds38, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds9
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(9)) * 1;
    LVar2 := local_var(getNumVar(9)) * 2;
    LVar3 := local_var(getNumVar(9)) * 3;
    LVar0 := local_var(getOddsVar(9));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 9 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds09, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds19, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds29, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds39, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds10
begin
    variable LVar0 := 0;
    variable LVar1 := 1;
    variable LVar2 := 2;
    variable LVar3 := 3;
    LVar1 := local_var(getNumVar(10)) * 1;
    LVar2 := local_var(getNumVar(10)) * 2;
    LVar3 := local_var(getNumVar(10)) * 3;
    LVar0 := local_var(getOddsVar(10));
    gsay_reply(SCRIPT_ZCCRPDEL, message_str(SCRIPT_ZCCRPDEL, 801) + 10 + " " + message_str(SCRIPT_ZCCRPDEL, 803) + LVar0);
    giq_option(1, SCRIPT_ZCCRPDEL, "0" + message_str(583, 802) + ". (0)", NOdds010, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 1 + message_str(583, 802) + ". (" + LVar1 + ")", NOdds110, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 2 + message_str(583, 802) + ". (" + LVar2 + ")", NOdds210, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 3 + message_str(583, 802) + ". (" + LVar3 + ")", NOdds310, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end

procedure NodeOdds
begin
    debug_msg("got to node odds");
    gsay_reply(SCRIPT_ZCCRPDEL, 810);
    if (local_var(28)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 804, NodeOdds4, NEUTRAL_REACTION);
    end
    if (local_var(29)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 805, NodeOdds5, NEUTRAL_REACTION);
    end
    if (local_var(30)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 806, NodeOdds6, NEUTRAL_REACTION);
    end
    if (local_var(31)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 807, NodeOdds8, NEUTRAL_REACTION);
    end
    if (local_var(32)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 808, NodeOdds9, NEUTRAL_REACTION);
    end
    if (local_var(33)) then begin
        giq_option(1, SCRIPT_ZCCRPDEL, 809, NodeOdds10, NEUTRAL_REACTION);
    end
    giq_option(1, SCRIPT_ZCCRPDEL, 713, Node001, NEUTRAL_REACTION);
end
