variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;
variable caught_thief;
variable the_follow_obj;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_exit_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;

import variable vic_door_guard_obj;
import variable vic_door_obj;

variable door_was_locked;

procedure Node990;
procedure Node989;
procedure Node988;
procedure Node987;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    vic_door_guard_obj := self_obj;
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if (((local_var(4) bwand 2) != 0) or ((global_var(GVAR_DEN_FLAG_2) bwand 16777216) != 0)) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack(dude_obj);
            end
        end
    end
    else begin
        if (tile_num(self_obj) != local_var(7)) then begin
            animate_move_obj_to_tile(self_obj, local_var(7), 0);
        end
        else begin
            if (obj_get_rot(self_obj) != local_var(8)) then begin
                anim(self_obj, 1000, local_var(8));
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        call Node998();
    end
end

procedure talk_p_proc
begin
    if (((local_var(4) bwand 2) != 0) or ((global_var(GVAR_DEN_FLAG_2) bwand 16777216) != 0)) then begin
        call Node021();
    end
    else begin
        if ((global_var(GVAR_DEN_FLAG_1) bwand 134217728) != 0) then begin
            call Node026();
        end
        else begin
            if (in_dialog == 0) then begin
                in_dialog := 1;
                start_gdialog(914, self_obj, 4, -1, -1);
                gsay_start;
                call Node004();
                gsay_end;
                end_dialogue;
                in_dialog := 0;
            end
            else begin
                call Node004();
            end
        end
    end
    set_local_var(4, local_var(4) bwor 1);
end

procedure destroy_p_proc
begin
    vic_door_guard_obj := 0;
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) - -15);
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(150);
    set_local_var(4, local_var(4) bwor 4);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(4, local_var(4) bwor 8);
        set_local_var(4, local_var(4) bwor 2);
        set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 16777216);
    end
end

procedure map_enter_p_proc
begin
    vic_door_guard_obj := self_obj;
    if (is_loading_game == 0) then begin
        if (map_first_run) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 12);
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_SLAVER);
            set_local_var(7, tile_num(self_obj));
            set_local_var(8, obj_get_rot(self_obj));
        end
        if (tile_num(self_obj) != local_var(7)) then begin
            critter_attempt_placement(self_obj, local_var(7), elevation(self_obj));
        end
        if (obj_get_rot(self_obj) != local_var(8)) then begin
            anim(self_obj, 1000, local_var(8));
        end
    end
end

procedure map_exit_p_proc
begin
end

procedure timed_event_p_proc
begin
    if (fixed_param == 0) then begin
    end
    else begin
        if (fixed_param == 6) then begin
            call Node001();
        end
        else begin
            if (fixed_param == 7) then begin
                call Node002();
            end
            else begin
                if (fixed_param == 9) then begin
                    call Node003();
                end
            end
        end
    end
end

procedure Node998
begin
    set_local_var(4, local_var(4) bwor 2);
    set_global_var(GVAR_DEN_FLAG_2, global_var(GVAR_DEN_FLAG_2) bwor 16777216);
end

procedure Node999
begin
end

procedure Node001
begin
    if ((local_var(4) bwand 512) != 0) then begin
        float_msg(self_obj, mstr(201), FLOAT_MSG_YELLOW);
        call Node998();
    end
    else begin
        float_msg(self_obj, mstr(200), FLOAT_MSG_YELLOW);
        set_local_var(4, local_var(4) bwor 512);
    end
end

procedure Node002
begin
    float_msg(self_obj, mstr(local_var(5)), FLOAT_MSG_YELLOW);
    if (local_var(5) < 2) then begin
        set_local_var(5, local_var(5) + 1);
    end
end

procedure Node003
begin
    float_msg(self_obj, mstr(220), FLOAT_MSG_YELLOW);
end

procedure Node004
begin
    if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
        Reply(231 + ((local_var(4) bwand 1024) != 0));
        set_local_var(4, local_var(4) bwor 1024);
        giq_option(4, NAME, 236, Node999, NEUTRAL_REACTION);
    end
    else begin
        Reply(230);
        giq_option(4, NAME, 235, Node999, NEUTRAL_REACTION);
        giq_option(-3, NAME, 237, Node020, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_DEN_VIC_KNOWN) == 2) then begin
        giq_option(4, NAME, 234, Node005, NEUTRAL_REACTION);
        giq_option(-3, NAME, 238, Node015, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 233, Node005, NEUTRAL_REACTION);
    end
    giq_option(-3, NAME, 239, Node014, NEUTRAL_REACTION);
    giq_option(-3, NAME, 240, Node014, NEUTRAL_REACTION);
end

procedure Node005
begin
    if ((local_var(4) bwand 2048) != 0) then begin
        Reply(254);
    end
    else begin
        set_local_var(4, local_var(4) bwor 2048);
        if (global_var(GVAR_DEN_VIC_KNOWN) == 2) then begin
            Reply(250 + (global_var(GVAR_REPUTATION_SLAVER) == 1));
        end
        else begin
            Reply(252 + (global_var(GVAR_REPUTATION_SLAVER) == 1));
        end
    end
    if (2 > global_var(GVAR_DEN_VIC_KNOWN)) then begin
        set_global_var(GVAR_DEN_VIC_KNOWN, 2);
    end
    giq_option(4, NAME, 255, Node010, NEUTRAL_REACTION);
    if (((global_var(GVAR_DEN_FLAG_1) bwand 32768) != 0) == 0) then begin
        giq_option(4, NAME, 256, Node010, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_DEN_SEE_VIC) == 2) == 0) then begin
        giq_option(4, NAME, 257, Node990, NEUTRAL_REACTION);
    end
    else begin
        if (vic_door_obj != 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                giq_option(4, NAME, 260, Node009, NEUTRAL_REACTION);
            end
        end
    end
    if (is_skill_tagged(SKILL_REPAIR) or (dude_skill(SKILL_REPAIR) >= 60)) then begin
        giq_option(4, NAME, 258, Node017, GOOD_REACTION);
    end
    if (is_skill_tagged(SKILL_SCIENCE) or (dude_skill(SKILL_SCIENCE) >= 60)) then begin
        giq_option(4, NAME, 259, Node017, GOOD_REACTION);
    end
    giq_option(4, NAME, 261, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            rm_fixed_timer_event(self_obj, 9);
            add_timer_event(self_obj, 1, 9);
        end
    end
    if (global_var(GVAR_DEN_SEE_VIC) == 1) then begin
        item_caps_adjust(dude_obj, -300);
        if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
            set_global_var(GVAR_DEN_SEE_VIC, 2);
        end
        Reply(275);
    end
    else begin
        Reply(276);
    end
    if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 2);
    end
    set_global_var(GVAR_DEN_FLAG_1, global_var(GVAR_DEN_FLAG_1) bwor 32768);
    giq_option(4, NAME, 277, Node999, NEUTRAL_REACTION);
end

procedure Node007
begin
    Reply(285 + ((global_var(GVAR_DEN_FLAG_2) bwand 4194304) != 0));
    if (((global_var(GVAR_DEN_FLAG_1) bwand 32768) != 0) == 0) then begin
        giq_option(4, NAME, 287, Node010, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_DEN_SEE_VIC) == 2) == 0) then begin
        giq_option(4, NAME, 257, Node990, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 290, Node999, NEUTRAL_REACTION);
end

procedure Node008
begin
    if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 2);
    end
    Reply(295 + ((global_var(GVAR_REPUTATION_SLAVER) == 1) == 0));
    if (vic_door_obj != 0) then begin
        if (obj_is_locked(vic_door_obj)) then begin
            giq_option(4, NAME, 297, Node009, NEUTRAL_REACTION);
        end
    end
    giq_option(4, NAME, 298, Node999, NEUTRAL_REACTION);
end

procedure Node009
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            rm_fixed_timer_event(self_obj, 9);
            add_timer_event(self_obj, 1, 9);
        end
    end
    if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 2);
    end
    Reply(305);
    giq_option(4, NAME, 306, Node999, NEUTRAL_REACTION);
end

procedure Node010
begin
    Reply(310);
    giq_option(4, NAME, 311, Node012, NEUTRAL_REACTION);
    giq_option(4, NAME, 312, Node011, NEUTRAL_REACTION);
    giq_option(4, NAME, 313, Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    Reply(320);
    giq_option(4, NAME, 321, Node999, BAD_REACTION);
    giq_option(4, NAME, 322, Node999, GOOD_REACTION);
end

procedure Node012
begin
    Reply(330 + (dude_gender == 1));
    giq_option(4, NAME, 332, Node013, NEUTRAL_REACTION);
    giq_option(4, NAME, 333, Node999, NEUTRAL_REACTION);
end

procedure Node013
begin
    Reply(340);
    giq_option(4, NAME, 341, Node999, NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(350);
    giq_option(-3, NAME, 351, Node999, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(360 + (global_var(GVAR_REPUTATION_SLAVER) == 1));
    giq_option(-3, NAME, 362, Node016, GOOD_REACTION);
    giq_option(-3, NAME, 363, Node014, NEUTRAL_REACTION);
    giq_option(-3, NAME, 364, Node999, NEUTRAL_REACTION);
end

procedure Node016
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            rm_fixed_timer_event(self_obj, 9);
            add_timer_event(self_obj, 1, 9);
        end
    end
    Reply(370 + door_was_locked);
    if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 2);
    end
    giq_option(-3, NAME, 372, Node999, NEUTRAL_REACTION);
end

procedure Node017
begin
    door_was_locked := 0;
    if (vic_door_obj != 0) then begin
        if (obj_is_open(vic_door_obj) == 0) then begin
            if (obj_is_locked(vic_door_obj)) then begin
                door_was_locked := 1;
                obj_unlock(vic_door_obj);
            end
            obj_open(vic_door_obj);
            rm_fixed_timer_event(self_obj, 9);
            add_timer_event(self_obj, 1, 9);
        end
    end
    Reply(380);
    giq_option(4, NAME, 381, Node999, NEUTRAL_REACTION);
end

procedure Node018
begin
    if (global_var(GVAR_DEN_SEE_VIC) == 1) then begin
        Reply(392);
        if (item_caps_total(dude_obj) >= 300) then begin
            giq_option(4, NAME, 395, Node006, NEUTRAL_REACTION);
        end
        giq_option(4, NAME, 396, Node999, NEUTRAL_REACTION);
    end
    else begin
        if ((local_var(4) bwand 4096) != 0) then begin
            Reply(391);
            if (global_var(GVAR_DEN_SEE_VIC) == 0) then begin
                giq_option(4, NAME, 394, Node022, NEUTRAL_REACTION);
            end
        end
        else begin
            set_local_var(4, local_var(4) bwor 4096);
            Reply(390);
            if (global_var(GVAR_DEN_SEE_VIC) == 0) then begin
                giq_option(4, NAME, 393, Node022, NEUTRAL_REACTION);
            end
        end
    end
    if (((global_var(GVAR_DEN_FLAG_1) bwand 32768) != 0) == 0) then begin
        giq_option(4, NAME, 397, Node010, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 398, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    if (local_var(6) <= 2) then begin
        Reply(410 + local_var(6));
        set_local_var(6, local_var(6) + 1);
        giq_option(4, NAME, 414, Node999, NEUTRAL_REACTION);
    end
    else begin
        Reply(413);
        door_was_locked := 0;
        if (vic_door_obj != 0) then begin
            if (obj_is_open(vic_door_obj) == 0) then begin
                if (obj_is_locked(vic_door_obj)) then begin
                    door_was_locked := 1;
                    obj_unlock(vic_door_obj);
                end
                obj_open(vic_door_obj);
                rm_fixed_timer_event(self_obj, 9);
                add_timer_event(self_obj, 1, 9);
            end
        end
        if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
            set_global_var(GVAR_DEN_SEE_VIC, 2);
        end
        giq_option(4, NAME, 415, Node999, NEUTRAL_REACTION);
    end
end

procedure Node020
begin
    if ((local_var(4) bwand 8192) != 0) then begin
        Reply(432);
    end
    else begin
        set_local_var(4, local_var(4) bwor 8192);
        Reply(430 + (dude_gender == 1));
    end
    giq_option(-3, NAME, 433, Node014, NEUTRAL_REACTION);
    giq_option(-3, NAME, 434, Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, 435, Node999, NEUTRAL_REACTION);
end

procedure Node021
begin
    float_msg(self_obj, mstr(450 + (dude_gender == 1)), FLOAT_MSG_YELLOW);
    call Node998();
end

procedure Node022
begin
    Reply(460);
    giq_option(4, NAME, 461, Node989, NEUTRAL_REACTION);
    giq_option(4, NAME, 462, Node988, NEUTRAL_REACTION);
    giq_option(4, NAME, 463, Node999, NEUTRAL_REACTION);
end

procedure Node023
begin
    if (1 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 1);
    end
    Reply(470);
    giq_option(4, NAME, 471, Node024, NEUTRAL_REACTION);
    giq_option(4, NAME, 472, Node987, BAD_REACTION);
    if (item_caps_total(dude_obj) >= 300) then begin
        giq_option(4, NAME, 473, Node006, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 474, Node999, NEUTRAL_REACTION);
end

procedure Node024
begin
    Reply(480);
    giq_option(4, NAME, 481, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 482, Node999, BAD_REACTION);
end

procedure Node025
begin
    if ((local_var(4) bwand 16384) != 0) then begin
        if (3 > global_var(GVAR_DEN_SEE_VIC)) then begin
            set_global_var(GVAR_DEN_SEE_VIC, 3);
        end
        Reply(491);
    end
    else begin
        set_local_var(4, local_var(4) bwor 16384);
        Reply(490);
    end
    giq_option(4, NAME, 492, Node999, NEUTRAL_REACTION);
end

procedure Node026
begin
    if (((global_var(GVAR_DEN_FLAG_1) bwand 32) != 0) == 0) then begin
        float_msg(self_obj, mstr(random(503, 504)), FLOAT_MSG_YELLOW);
    end
    else begin
        if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
            float_msg(self_obj, mstr(random(505, 507)), FLOAT_MSG_YELLOW);
        end
        else begin
            float_msg(self_obj, mstr(random(500, 502)), FLOAT_MSG_YELLOW);
        end
    end
end

procedure Node990
begin
    if ((global_var(GVAR_REPUTATION_SLAVER) == 1) or (global_var(GVAR_DEN_SEE_VIC) == 2)) then begin
        call Node009();
    end
    else begin
        if ((global_var(GVAR_DEN_FLAG_2) bwand 4194304) != 0) then begin
            call Node008();
        end
        else begin
            if (global_var(GVAR_DEN_SEE_VIC) == 3) then begin
                call Node019();
            end
            else begin
                call Node018();
            end
        end
    end
end

procedure Node989
begin
    if (is_skill_tagged(SKILL_REPAIR) or is_success(roll_vs_skill(dude_obj, 14, -10))) then begin
        if (2 > global_var(GVAR_DEN_SEE_VIC)) then begin
            set_global_var(GVAR_DEN_SEE_VIC, 2);
        end
        call Node006();
    end
    else begin
        call Node025();
    end
end

procedure Node988
begin
    if (is_success(roll_vs_skill(dude_obj, 15, -20))) then begin
        call Node023();
    end
    else begin
        call Node025();
    end
end

procedure Node987
begin
    if (3 > global_var(GVAR_DEN_SEE_VIC)) then begin
        set_global_var(GVAR_DEN_SEE_VIC, 3);
    end
    call Node024();
end
