procedure start;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure map_enter_p_proc;
procedure description_p_proc;
procedure look_at_p_proc;


procedure start
begin
end

procedure talk_p_proc
begin
    float_msg(self_obj, mstr(random(101, 105)), FLOAT_MSG_YELLOW);
end

procedure destroy_p_proc
begin
    if (CUR_MAP_BHRNDDST) then begin
        set_map_var(1, map_var(1) - 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 177);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_DOCTOR);
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(100);
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100);
end
