variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure map_enter_p_proc;
procedure use_obj_on_p_proc;
procedure use_p_proc;
procedure talk_p_proc;
procedure pickup_p_proc;
procedure destroy_p_proc;
procedure drop_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node999;

export variable baby_obj;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure map_enter_p_proc
begin
    baby_obj := self_obj;
end

procedure use_obj_on_p_proc
begin
    script_overrides;
    if (obj_pid(obj_being_used_with) == 584) then begin
        if ((global_var(GVAR_EPA_LENNY_STATE) > (1 - 1)) and (global_var(GVAR_EPA_LENNY_STATE) < (2 + 1))) then begin
            set_global_var(GVAR_EPA_LENNY_STATE, 3);
            display_mstr(700);
        end
    end
end

procedure use_p_proc
begin
    dialogue_system_enter;
end

procedure talk_p_proc
begin
    if (local_var(2) == 0) then begin
        start_gdialog(1700, self_obj, 4, 19, 21);
        gsay_start;
        set_local_var(4, 1);
        call Node001();
        gsay_end;
        end_dialogue;
    end
    else begin
        float_msg(self_obj, mstr(random(235, 241)), FLOAT_MSG_YELLOW);
    end
end

procedure pickup_p_proc
begin
end

procedure destroy_p_proc
begin
end

procedure drop_p_proc
begin
end

procedure Node001
begin
    Reply(200);
    giq_option(4, NAME, 210, Node002, NEUTRAL_REACTION);
    giq_option(4, NAME, 211, Node003, NEUTRAL_REACTION);
    giq_option(4, NAME, 212, Node004, NEUTRAL_REACTION);
    giq_option(-3, NAME, 220, Node007, NEUTRAL_REACTION);
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) > 114)) then begin
        giq_option(4, NAME, 213, Node005, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) < 115)) then begin
        giq_option(4, NAME, 213, Node006, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 214, Node999, NEUTRAL_REACTION);
end

procedure Node002
begin
    Reply(300);
    giq_option(4, NAME, 211, Node003, NEUTRAL_REACTION);
    giq_option(4, NAME, 212, Node004, NEUTRAL_REACTION);
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) > 114)) then begin
        giq_option(4, NAME, 213, Node005, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) < 115)) then begin
        giq_option(4, NAME, 213, Node006, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 214, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    Reply(400);
    giq_option(4, NAME, 211, Node003, NEUTRAL_REACTION);
    giq_option(4, NAME, 212, Node004, NEUTRAL_REACTION);
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) > 114)) then begin
        giq_option(4, NAME, 213, Node005, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) < 115)) then begin
        giq_option(4, NAME, 213, Node006, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 214, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    Reply(500);
    giq_option(4, NAME, 210, Node002, NEUTRAL_REACTION);
    giq_option(4, NAME, 211, Node003, NEUTRAL_REACTION);
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) > 114)) then begin
        giq_option(4, NAME, 213, Node005, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_EPA_LENNY_STATE) > 0) and has_trait(TRAIT_PERK, dude_obj, PERK_scrounger) and (dude_skill(SKILL_SCIENCE) < 115)) then begin
        giq_option(4, NAME, 213, Node006, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 214, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
    set_global_var(GVAR_EPA_LENNY_STATE, 3);
    Reply(700);
    giq_option(4, NAME, 214, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    set_global_var(GVAR_PRIMIT_MONK_STATE, 1);
    Reply(600);
    giq_option(4, NAME, 214, Node999, BAD_REACTION);
end

procedure Node007
begin
    set_local_var(2, 1);
    Reply(221);
    giq_option(-3, NAME, 222, Node008, BAD_REACTION);
    giq_option(-3, NAME, 223, Node999, BAD_REACTION);
    giq_option(-3, NAME, 224, Node999, BAD_REACTION);
end

procedure Node008
begin
    Reply(230);
    giq_option(-3, NAME, 223, Node999, BAD_REACTION);
    giq_option(-3, NAME, 224, Node999, BAD_REACTION);
end

procedure Node999
begin
end
