variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node026;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure startDeath;
procedure continueDeath;
procedure doDeathWalk;

variable Only_Once;
variable g1;
variable g2;
variable cDeathCount;

procedure Node171819;
procedure Node010a;
procedure Node016a;
procedure Node999b;
procedure Node034a;
procedure Node034b;
procedure Node034c;
procedure Node034d;
procedure Node034e;
procedure Node034f;
procedure Node999a;

variable counter;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure critter_p_proc
begin
    if ((local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 512) != 0) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 2);
    end
    if ((local_var(11) != 0) and obj_on_screen(self_obj) and not(combat_is_initialized)) then begin
        if (game_time > local_var(11)) then begin
            set_local_var(11, 0);
            call startDeath();
        end
    end
    if ((local_var(12) == 1) and (tile_num(self_obj) == 27101)) then begin
        set_local_var(12, 2);
        g1 := create_object(16777518, 27703, 0);
        g2 := create_object(16777518, 27699, 0);
        reg_anim_func(2, g1);
        reg_anim_func(1, 1);
        anim(g1, 1000, rotation_to_tile(27703, tile_num(self_obj)));
        reg_anim_func(3, 0);
        reg_anim_func(2, g2);
        reg_anim_func(1, 1);
        anim(g2, 1000, rotation_to_tile(27699, tile_num(self_obj)));
        reg_anim_func(3, 0);
        float_msg(self_obj, mstr(203), FLOAT_MSG_RED);
        add_timer_event(self_obj, game_ticks(3), 1);
    end
    else begin
        if (local_var(12) == 1) then begin
            if (tile_distance_objs(self_obj, dude_obj) >= 10) then begin
                move_to(dude_obj, tile_num(self_obj), 0);
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    Evil_Critter := 0;
    Slavery_Tolerant := 1;
    Karma_Perception := 1;
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (dude_charisma - self_charisma) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    if (reaction_bonus_karma >= 0) then begin
        reaction_bonus_karma := reaction_bonus_karma / 1000;
    end
    else begin
        reaction_bonus_karma := -1 * (-1 * reaction_bonus_karma / 1000);
    end
    if (global_var(GVAR_TOWN_REP_SAN_FRANCISCO) >= 0) then begin
        reaction_bonus_town_rep := global_var(GVAR_TOWN_REP_SAN_FRANCISCO) / 2;
    end
    else begin
        reaction_bonus_town_rep := -1 * (-1 * global_var(GVAR_TOWN_REP_SAN_FRANCISCO) / 2);
    end
    if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
        if (dude_gender == self_gender) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        Static_Reaction := Static_Reaction - reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction - -5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction - -10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction - -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction - -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
            Static_Reaction := Static_Reaction + (2 * -25);
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                Static_Reaction := Static_Reaction + -25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                    Static_Reaction := Static_Reaction - -25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(GVAR_CHILDKILLER_REPUTATION) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if (not(local_var(12) != 0)) then begin
        if ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 512) != 0) then begin
            start_gdialog(821, self_obj, 4, -1, -1);
            gsay_start;
            call Node028();
            gsay_end;
            end_dialogue;
        end
        else begin
            if (global_var(GVAR_SAN_FRAN_BADGER) == 512) then begin
                call Node031();
            end
            else begin
                if (global_var(GVAR_SAN_FRAN_BADGER) == 256) then begin
                    call Node030();
                end
                else begin
                    if ((global_var(GVAR_SAN_FRAN_BADGER) == 32) and not(local_var(8))) then begin
                        start_gdialog(821, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node025();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if ((global_var(GVAR_SAN_FRAN_BADGER) == 16) and not(local_var(8))) then begin
                            if (local_var(7) == 1) then begin
                                if (game_time > local_var(10)) then begin
                                    start_gdialog(821, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node024();
                                    gsay_end;
                                    end_dialogue;
                                end
                                else begin
                                    start_gdialog(821, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node029();
                                    gsay_end;
                                    end_dialogue;
                                end
                            end
                            else begin
                                if (local_var(7) == 0) then begin
                                    set_local_var(7, local_var(7) + 1);
                                    start_gdialog(821, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node023();
                                    gsay_end;
                                    end_dialogue;
                                end
                            end
                        end
                        else begin
                            if (global_var(GVAR_SAN_FRAN_BADGER) == 8) then begin
                                start_gdialog(821, self_obj, 4, -1, -1);
                                gsay_start;
                                call Node022();
                                gsay_end;
                                end_dialogue;
                            end
                            else begin
                                if (local_var(9)) then begin
                                    debug_msg("FCBADGER: hacking : " + local_var(8));
                                    if ((game_time >= local_var(9)) and (local_var(8) < 4)) then begin
                                        start_gdialog(821, self_obj, 4, -1, -1);
                                        gsay_start;
                                        call Node026();
                                        gsay_end;
                                        end_dialogue;
                                    end
                                    else begin
                                        if ((game_time >= local_var(9)) and (local_var(8) < 8)) then begin
                                            start_gdialog(821, self_obj, 4, -1, -1);
                                            gsay_start;
                                            call Node027();
                                            gsay_end;
                                            end_dialogue;
                                        end
                                        else begin
                                            if (game_time < local_var(9)) then begin
                                                call Node008();
                                            end
                                        end
                                    end
                                end
                                else begin
                                    start_gdialog(821, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node001();
                                    gsay_end;
                                    end_dialogue;
                                end
                            end
                        end
                    end
                end
            end
        end
        // O_JMP (0);
    end
end

procedure destroy_p_proc
begin
    variable LVar0 := 0;
    LVar0 := create_object(1, 0, 0);
    add_obj_to_inven(self_obj, LVar0);
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(GVAR_SAN_FRAN_BADGER, 128);
    return 0;
    LVar0 := 0;
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(102);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (obj_in_party(source_obj)) then begin
        set_local_var(6, 1);
        set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 512);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 193);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_BADGER);
    if ((global_var(GVAR_SAN_FRAN_BADGER) == 256) and (local_var(11) == 0)) then begin
        set_local_var(11, game_time + (24 * (60 * (60 * 10)) * random(1, 3)));
    end
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        call continueDeath();
    end
    else begin
        if (fixed_param == 2) then begin
            call doDeathWalk();
        end
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    Reply(103);
    giq_option(1, NAME, 104, Node002, NEUTRAL_REACTION);
    giq_option(-3, NAME, 105, Node004, NEUTRAL_REACTION);
    giq_option(4, NAME, 106, Node004, NEUTRAL_REACTION);
    giq_option(4, NAME, 107, Node006, NEUTRAL_REACTION);
    giq_option(4, NAME, 108, Node007, NEUTRAL_REACTION);
    if (not(global_var(GVAR_SAN_FRAN_BADGER) == 0) and (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 16777216) != 0) or (global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4) or (global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 4))) then begin
        giq_option(4, NAME, 109, Node171819, NEUTRAL_REACTION);
    end
    if (local_var(8) != 0) then begin
        giq_option(4, NAME, 110, Node008, NEUTRAL_REACTION);
    end
    if (((global_var(GVAR_SAN_FRAN_TANKER) bwand 1) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
        giq_option(4, NAME, 199, Node032, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 111, Node999, NEUTRAL_REACTION);
end

procedure Node002
begin
    Reply(112);
    giq_option(1, NAME, 113, Node003, NEUTRAL_REACTION);
    giq_option(1, NAME, 114, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    Reply(115);
    giq_option(4, NAME, 116, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    Reply(117);
    giq_option(-3, NAME, 118, Node005, NEUTRAL_REACTION);
    giq_option(4, NAME, 119, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 120, Node010a, BAD_REACTION);
    giq_option(4, NAME, 121, Node011, NEUTRAL_REACTION);
    giq_option(4, NAME, 122, Node999, NEUTRAL_REACTION);
end

procedure Node005
begin
    Reply(123);
    giq_option(1, NAME, 124, Node999, NEUTRAL_REACTION);
end

procedure Node006
begin
    Reply(125);
    giq_option(4, NAME, 126, Node012, NEUTRAL_REACTION);
    giq_option(4, NAME, 127, Node013, NEUTRAL_REACTION);
end

procedure Node007
begin
    Reply(128);
    giq_option(4, NAME, 129, Node009, NEUTRAL_REACTION);
    giq_option(4, NAME, 130, Node999, NEUTRAL_REACTION);
end

procedure Node008
begin
    float_msg(self_obj, mstr(131), FLOAT_MSG_NORMAL);
end

procedure Node009
begin
    Reply(133);
    if (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 16777216) != 0) or (global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4) or (global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 4)) then begin
        giq_option(4, NAME, 134, Node171819, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 135, Node015, NEUTRAL_REACTION);
end

procedure Node010
begin
    Reply(136);
    giq_option(4, NAME, 137, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 138, Node998, NEUTRAL_REACTION);
end

procedure Node011
begin
    Reply(139);
    giq_option(4, NAME, 140, Node016a, NEUTRAL_REACTION);
    giq_option(4, NAME, 141, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 142, Node010a, NEUTRAL_REACTION);
end

procedure Node012
begin
    Reply(143);
    giq_option(4, NAME, 144, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 145, Node999, NEUTRAL_REACTION);
end

procedure Node013
begin
    Reply(146);
    giq_option(4, NAME, 147, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 148, Node999, NEUTRAL_REACTION);
end

procedure Node014
begin
    Reply(149);
    giq_option(4, NAME, 150, Node171819, NEUTRAL_REACTION);
    giq_option(4, NAME, 151, Node999, NEUTRAL_REACTION);
end

procedure Node015
begin
    Reply(152);
    if (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 16777216) != 0) or (global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4) or (global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 4)) then begin
        giq_option(4, NAME, 153, Node014, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 154, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 155, Node999, NEUTRAL_REACTION);
end

procedure Node016
begin
    Reply(156);
    giq_option(4, NAME, 157, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 158, Node999, NEUTRAL_REACTION);
end

procedure Node017
begin
    Reply(159);
    giq_option(4, NAME, 160, Node020, NEUTRAL_REACTION);
    giq_option(4, NAME, 161, Node021, NEUTRAL_REACTION);
    giq_option(4, NAME, 162, Node999, NEUTRAL_REACTION);
end

procedure Node018
begin
    Reply(163);
    giq_option(4, NAME, 164, Node020, NEUTRAL_REACTION);
    giq_option(4, NAME, 165, Node021, NEUTRAL_REACTION);
    giq_option(4, NAME, 166, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    Reply(167);
    giq_option(4, NAME, 168, Node999b, NEUTRAL_REACTION);
    giq_option(4, NAME, 169, Node999, NEUTRAL_REACTION);
end

procedure Node020
begin
    if ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 524288) != 0) then begin
        Reply(196);
        giq_option(4, NAME, 154, Node001, NEUTRAL_REACTION);
        giq_option(4, NAME, 158, Node999, NEUTRAL_REACTION);
    end
    else begin
        Reply(170);
        if (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
            giq_option(4, NAME, 209, Node034d, NEUTRAL_REACTION);
        end
        if ((global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 8) and ((global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 4) or ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 33554432) != 0))) then begin
            giq_option(4, NAME, 210, Node034e, NEUTRAL_REACTION);
        end
        if (((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 8) and ((global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 4) or ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 33554432) != 0)))) then begin
            giq_option(4, NAME, 211, Node034f, NEUTRAL_REACTION);
        end
        giq_option(4, NAME, 217, Node999, NEUTRAL_REACTION);
    end
end

procedure Node021
begin
    if ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 1024) != 0) then begin
        Reply(196);
        giq_option(4, NAME, 154, Node001, NEUTRAL_REACTION);
        giq_option(4, NAME, 158, Node999, NEUTRAL_REACTION);
    end
    else begin
        Reply(173);
        giq_option(4, NAME, 212, Node033, NEUTRAL_REACTION);
        giq_option(4, NAME, 213, Node999, NEUTRAL_REACTION);
    end
end

procedure Node022
begin
    Reply(176);
    giq_option(4, NAME, 177, Node999, NEUTRAL_REACTION);
end

procedure Node023
begin
    set_local_var(10, game_time + (60 * (60 * 10) * 3));
    if (global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST) != 2) then begin
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 2);
        set_global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST, 2);
    end
    Reply(178);
    giq_option(4, NAME, 179, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 180, Node010a, NEUTRAL_REACTION);
end

procedure Node024
begin
    Reply(181);
    giq_option(4, NAME, 182, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 183, Node999, NEUTRAL_REACTION);
end

procedure Node025
begin
    if (global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST) != 2) then begin
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 15);
        debug_msg("Player gains " + 15 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 5);
        give_exp_points(5000);
        display_msg(g_mstr(100) + 5000 + g_mstr(101));
        set_global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST, 2);
    end
    Reply(184);
    giq_option(4, NAME, 185, Node001, NEUTRAL_REACTION);
    giq_option(4, NAME, 186, Node999a, NEUTRAL_REACTION);
end

procedure Node026
begin
    set_global_var(GVAR_SAN_FRAN_BADGER, 256);
    Reply(187);
    giq_option(4, NAME, 219, Node035, NEUTRAL_REACTION);
end

procedure Node027
begin
    set_global_var(GVAR_SAN_FRAN_BADGER, 512);
    Reply(190);
    giq_option(4, NAME, 219, Node035, NEUTRAL_REACTION);
end

procedure Node028
begin
    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 1);
    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 262144);
    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 256);
    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 512);
    Reply(193);
    giq_option(4, NAME, 194, Node998, NEUTRAL_REACTION);
end

procedure Node029
begin
    Reply(195);
    giq_option(4, NAME, 179, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 180, Node010a, NEUTRAL_REACTION);
end

procedure Node030
begin
    float_msg(self_obj, mstr(197), FLOAT_MSG_NORMAL);
end

procedure Node031
begin
    float_msg(self_obj, mstr(198), FLOAT_MSG_NORMAL);
end

procedure Node032
begin
    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwor 16777216);
    if ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) then begin
        Reply(200);
    end
    else begin
        Reply(201);
    end
    giq_option(4, NAME, 202, Node014, NEUTRAL_REACTION);
    giq_option(4, NAME, 192, Node999, NEUTRAL_REACTION);
end

procedure Node033
begin
    Reply(214);
    if (not((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
        giq_option(4, NAME, 215, Node034a, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 8) and ((global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4) or ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 33554432) != 0))) then begin
        giq_option(4, NAME, 210, Node034b, NEUTRAL_REACTION);
    end
    if (not((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 8) and ((global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4) or ((global_var(GVAR_SAN_FRAN_FLAGS) bwand 33554432) != 0)))) then begin
        giq_option(4, NAME, 211, Node034c, NEUTRAL_REACTION);
    end
    if (not((global_var(GVAR_SAN_FRAN_FLAGS) bwand 32768) != 0) and not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) or ((global_var(GVAR_SAN_FRAN_SHI_WHIRLY) == 8) and (global_var(GVAR_SAN_FRAN_ELRON_WHIRLY) == 4))) then begin
        giq_option(4, NAME, 216, Node999, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 217, Node999, NEUTRAL_REACTION);
end

procedure Node034
begin
    Reply(218);
    giq_option(4, NAME, 130, Node999, NEUTRAL_REACTION);
end

procedure Node035
begin
    if (local_var(8) == 1) then begin
        if (not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
            set_global_var(GVAR_SAN_FRAN_TANKER, global_var(GVAR_SAN_FRAN_TANKER) bwor 8);
        end
        if (((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_TANKER) bwand 4) != 0)) then begin
            if (global_var(GVAR_FALLOUT_2) < 7) then begin
                set_global_var(GVAR_FALLOUT_2, 7);
            end
        end
        if (821 != 950) then begin
            if (5 != 0) then begin
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
            end
            debug_msg("Player gains " + 5 + " Karma Points.");
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
            set_global_var(GVAR_KARMA_DEFENDER, 0);
            set_global_var(GVAR_KARMA_WANDERER, 0);
            set_global_var(GVAR_KARMA_BETRAYER, 0);
            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
            set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
            if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                            set_global_var(GVAR_KARMA_DEFENDER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                set_global_var(GVAR_KARMA_WANDERER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                    set_global_var(GVAR_KARMA_BETRAYER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                            set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                        end
                                        else begin
                                            set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            if (0 != 0) then begin
                set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 0);
            end
            if (5000 != 0) then begin
                give_exp_points(5000);
            end
            display_msg(g_mstr(100) + 5000 + g_mstr(101));
        end
        set_global_var(GVAR_SAN_FRAN_FUEL_TANK_QST, 2);
        set_local_var(8, 4);
        Reply(220);
    end
    else begin
        if (local_var(8) == 2) then begin
            set_local_var(8, 4);
            add_obj_to_inven(dude_obj, create_object(446, 0, 0));
            Reply(221);
        end
        else begin
            if (local_var(8) == 3) then begin
                if (not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
                    set_global_var(GVAR_SAN_FRAN_TANKER, global_var(GVAR_SAN_FRAN_TANKER) bwor 8);
                end
                if (((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_TANKER) bwand 4) != 0)) then begin
                    if (global_var(GVAR_FALLOUT_2) < 7) then begin
                        set_global_var(GVAR_FALLOUT_2, 7);
                    end
                end
                if (821 != 950) then begin
                    if (5 != 0) then begin
                        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
                    end
                    debug_msg("Player gains " + 5 + " Karma Points.");
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                    set_global_var(GVAR_KARMA_DEFENDER, 0);
                    set_global_var(GVAR_KARMA_WANDERER, 0);
                    set_global_var(GVAR_KARMA_BETRAYER, 0);
                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                        set_global_var(GVAR_KARMA_WANDERER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                            end
                                            else begin
                                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                                end
                                                else begin
                                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                    if (0 != 0) then begin
                        set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 0);
                    end
                    if (5000 != 0) then begin
                        give_exp_points(5000);
                    end
                    display_msg(g_mstr(100) + 5000 + g_mstr(101));
                end
                set_global_var(GVAR_SAN_FRAN_FUEL_TANK_QST, 2);
                set_local_var(8, 4);
                add_obj_to_inven(dude_obj, create_object(446, 0, 0));
                Reply(222);
            end
            else begin
                if (local_var(8) == 5) then begin
                    set_local_var(8, 8);
                    if (not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
                        set_global_var(GVAR_SAN_FRAN_TANKER, global_var(GVAR_SAN_FRAN_TANKER) bwor 8);
                    end
                    if (((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_TANKER) bwand 4) != 0)) then begin
                        if (global_var(GVAR_FALLOUT_2) < 7) then begin
                            set_global_var(GVAR_FALLOUT_2, 7);
                        end
                    end
                    if (821 != 950) then begin
                        if (5 != 0) then begin
                            set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
                        end
                        debug_msg("Player gains " + 5 + " Karma Points.");
                        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                        set_global_var(GVAR_KARMA_DEFENDER, 0);
                        set_global_var(GVAR_KARMA_WANDERER, 0);
                        set_global_var(GVAR_KARMA_BETRAYER, 0);
                        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                            set_global_var(GVAR_KARMA_WANDERER, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                                            end
                                            else begin
                                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                                end
                                                else begin
                                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                                    end
                                                    else begin
                                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                        if (0 != 0) then begin
                            set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 0);
                        end
                        if (5000 != 0) then begin
                            give_exp_points(5000);
                        end
                        display_msg(g_mstr(100) + 5000 + g_mstr(101));
                    end
                    set_global_var(GVAR_SAN_FRAN_FUEL_TANK_QST, 2);
                    set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwand (-1 - 32768));
                    Reply(220);
                end
                else begin
                    if (local_var(8) == 6) then begin
                        set_local_var(8, 8);
                        add_obj_to_inven(dude_obj, create_object(446, 0, 0));
                        Reply(221);
                    end
                    else begin
                        if (local_var(8) == 7) then begin
                            set_local_var(8, 8);
                            add_obj_to_inven(dude_obj, create_object(446, 0, 0));
                            if (not((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0)) then begin
                                set_global_var(GVAR_SAN_FRAN_TANKER, global_var(GVAR_SAN_FRAN_TANKER) bwor 8);
                            end
                            if (((global_var(GVAR_SAN_FRAN_TANKER) bwand 8) != 0) and ((global_var(GVAR_SAN_FRAN_TANKER) bwand 4) != 0)) then begin
                                if (global_var(GVAR_FALLOUT_2) < 7) then begin
                                    set_global_var(GVAR_FALLOUT_2, 7);
                                end
                            end
                            if (821 != 950) then begin
                                if (5 != 0) then begin
                                    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
                                end
                                debug_msg("Player gains " + 5 + " Karma Points.");
                                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                                set_global_var(GVAR_KARMA_DEFENDER, 0);
                                set_global_var(GVAR_KARMA_WANDERER, 0);
                                set_global_var(GVAR_KARMA_BETRAYER, 0);
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                                            end
                                            else begin
                                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                                end
                                                else begin
                                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                                    end
                                                    else begin
                                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                                        end
                                                        else begin
                                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                                            end
                                                            else begin
                                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                                            end
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                                if (0 != 0) then begin
                                    set_global_var(GVAR_TOWN_REP_SAN_FRANCISCO, global_var(GVAR_TOWN_REP_SAN_FRANCISCO) + 0);
                                end
                                if (5000 != 0) then begin
                                    give_exp_points(5000);
                                end
                                display_msg(g_mstr(100) + 5000 + g_mstr(101));
                            end
                            set_global_var(GVAR_SAN_FRAN_FUEL_TANK_QST, 2);
                            set_global_var(GVAR_SAN_FRAN_FLAGS, global_var(GVAR_SAN_FRAN_FLAGS) bwand (-1 - 32768));
                            Reply(222);
                        end
                    end
                end
            end
        end
    end
    giq_option(4, NAME, 223, Node999, NEUTRAL_REACTION);
end

procedure startDeath
begin
    fade_out;
    game_ui_disable;
    set_obj_visibility(dude_obj, 1);
    move_to(dude_obj, tile_num_in_direction(tile_num(self_obj), 0, 1), 0);
    fade_in;
    float_msg(self_obj, mstr(206), FLOAT_MSG_NORMAL);
    add_timer_event(self_obj, game_ticks(1), 2);
    set_local_var(12, 1);
end

procedure continueDeath
begin
    variable LVar0 := 0;
    variable LVar1 := 0;
    variable LVar2 := 0;
    variable LVar3 := 0;
    variable LVar4 := 0;
    cDeathCount := cDeathCount + 1;
    if (cDeathCount == 1) then begin
        float_msg(g1, mstr(204), FLOAT_MSG_NORMAL);
        add_timer_event(self_obj, game_ticks(3), 1);
    end
    else begin
        if (cDeathCount == 2) then begin
            float_msg(g2, mstr(205), FLOAT_MSG_RED);
            reg_anim_func(2, g1);
            LVar0 := create_object(391, 0, 0);
            add_obj_to_inven(g1, LVar0);
            wield_obj_critter(g1, LVar0);
            reg_anim_func(2, g2);
            LVar1 := create_object(391, 0, 0);
            add_obj_to_inven(g2, LVar1);
            wield_obj_critter(g2, LVar1);
            add_timer_event(self_obj, game_ticks(3), 1);
        end
        else begin
            if (cDeathCount == 3) then begin
                float_msg(self_obj, mstr(208), FLOAT_MSG_GREEN);
                add_timer_event(self_obj, game_ticks(3), 1);
            end
            else begin
                if (cDeathCount == 4) then begin
                    LVar2 := sfx_build_weapon_name(1, obj_carrying_pid_obj(g1, 391), 0, self_obj);
                    reg_anim_func(2, g1);
                    reg_anim_func(1, 1);
                    reg_anim_animate(g1, 46, -1);
                    reg_anim_func(3, 0);
                    reg_anim_func(2, g2);
                    reg_anim_func(1, 1);
                    reg_anim_animate(g2, 46, -1);
                    reg_anim_play_sfx(g2, LVar2, 0);
                    reg_anim_play_sfx(g2, LVar2, -1);
                    reg_anim_play_sfx(g2, LVar2, -1);
                    reg_anim_play_sfx(g2, LVar2, -1);
                    reg_anim_func(3, 0);
                    add_timer_event(self_obj, game_ticks(1), 1);
                end
                else begin
                    if (cDeathCount == 5) then begin
                        LVar3 := sfx_build_weapon_name(4, obj_carrying_pid_obj(g1, 391), 0, self_obj);
                        LVar4 := sfx_build_char_name(self_obj, 25, 3);
                        reg_anim_func(2, self_obj);
                        reg_anim_func(1, 1);
                        reg_anim_animate(self_obj, 25, -1);
                        reg_anim_play_sfx(self_obj, LVar4, 0);
                        reg_anim_func(3, 0);
                        add_timer_event(self_obj, game_ticks(1), 1);
                    end
                    else begin
                        if (not(anim_busy(self_obj))) then begin
                            fade_out;
                            destroy_object(g1);
                            destroy_object(g2);
                            game_ui_enable;
                            set_obj_visibility(dude_obj, 0);
                            fade_in;
                            float_msg(dude_obj, mstr(207), FLOAT_MSG_NORMAL);
                            set_global_var(GVAR_SAN_FRAN_BADGER, 2);
                            critter_heal(self_obj, -500);
                        end
                        else begin
                            add_timer_event(self_obj, 2, 1);
                        end
                    end
                end
            end
        end
    end
    return 0;
    LVar0 := 0;
    LVar1 := 0;
    LVar2 := 0;
    LVar3 := 0;
    LVar4 := 0;
end

procedure doDeathWalk
begin
    if (tile_num(self_obj) != 27101) then begin
        if (not(anim_busy(self_obj))) then begin
            reg_anim_func(2, self_obj);
            reg_anim_func(1, 1);
            animate_move_obj_to_tile(self_obj, 27101, 0);
            reg_anim_func(3, 0);
        end
        if (counter > 20) then begin
            reg_anim_func(2, self_obj);
            move_to(dude_obj, tile_num_in_direction(27101, 0, 1), dude_elevation);
            move_to(self_obj, 27101, elevation(self_obj));
        end
        else begin
            counter := counter + 1;
            add_timer_event(self_obj, 10, 2);
        end
    end
end

procedure Node171819
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 32) then begin
        call Node017();
    end
    else begin
        if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
            call Node018();
        end
        else begin
            set_global_var(GVAR_SAN_FRAN_BADGER, 64);
            call Node019();
        end
    end
end

procedure Node010a
begin
    set_local_var(3, local_var(3) + -30);
    set_local_var(0, local_var(0) + -30);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node010();
end

procedure Node016a
begin
    set_local_var(3, local_var(3) + 20);
    set_local_var(0, local_var(0) + 20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node016();
end

procedure Node999b
begin
    set_global_var(GVAR_SAN_FRAN_BADGER, 8);
    if (global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST) == 0) then begin
        set_global_var(GVAR_SAN_FRAN_BADGER_GFRIEND_QST, 1);
    end
    call Node999();
end

procedure Node034a
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 1);
    call Node034();
end

procedure Node034b
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 2);
    call Node034();
end

procedure Node034c
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 3);
    call Node034();
end

procedure Node034d
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 5);
    call Node034();
end

procedure Node034e
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 6);
    call Node034();
end

procedure Node034f
begin
    if (global_var(GVAR_SAN_FRAN_BADGER) == 16) then begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10)) * 3));
    end
    else begin
        set_local_var(9, game_time + (24 * (60 * (60 * 10))));
    end
    set_local_var(8, 7);
    call Node034();
end

procedure Node999a
begin
    set_local_var(3, local_var(3) + 20);
    set_local_var(0, local_var(0) + 20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node999();
end
