variable tmp_gen_rep;
variable global_temp;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure combat;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node012a;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node015a;
procedure Node016;
procedure Node016a;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node025;
procedure Node027;
procedure Node028;
procedure Node029;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node036;
procedure Node037;
procedure Node038;
procedure Node039;
procedure Node040;
procedure Node041;

variable From_WTG;
variable From_5;
variable Barter_Count;


procedure start
begin
end

procedure critter_p_proc
begin
    if ((global_var(GVAR_ENEMY_BROKEN_HILLS) == 1) or (local_var(5) == 2) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        attack(dude_obj);
    end
    if ((global_var(GVAR_BH_CONSPIRACY) == 5) or (global_var(GVAR_BH_FTM) == 6)) then begin
        if (obj_is_visible_flag(self_obj)) then begin
            set_obj_visibility(self_obj, 1);
        end
    end
    else begin
        if (not(obj_is_visible_flag(self_obj))) then begin
            set_obj_visibility(self_obj, 0);
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (local_var(2) == 0) then begin
        set_local_var(2, 1);
        set_local_var(3, (dude_charisma - self_charisma) * 5);
        debug_msg("Base Reaction == " + local_var(3));
    end
    Static_Reaction := 0;
    set_local_var(0, 0);
    debug_msg("Start Reaction == " + local_var(0));
    reaction_bonus_karma := floor(reaction_bonus_karma / 1000);
    reaction_bonus_town_rep := floor(global_var(GVAR_TOWN_REP_BROKEN_HILLS) / 2);
    if (has_trait(TRAIT_TRAIT, dude_obj, TRAIT_sex_appeal)) then begin
        if (dude_gender == self_gender) then begin
            Static_Reaction := Static_Reaction + -20;
        end
        else begin
            Static_Reaction := Static_Reaction + 20;
        end
        debug_msg("Sex Appeal Bonus == " + Static_Reaction);
    end
    else begin
        debug_msg("Sex Appeal Bonus == 0");
    end
    if (Evil_Critter == 1) then begin
        if (reaction_bonus_karma >= 0) then begin
            Static_Reaction := Static_Reaction - reaction_bonus_karma;
        end
        else begin
            Static_Reaction := Static_Reaction + reaction_bonus_karma;
        end
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        if (reaction_bonus_town_rep >= 0) then begin
            Static_Reaction := Static_Reaction - reaction_bonus_town_rep;
        end
        else begin
            Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        end
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
        if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
            tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction - 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction - 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction - 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction - 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction - 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction + 5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction + 10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction + 15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + 20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Bad Person Reaction Bonus == " + Static_Reaction);
    end
    else begin
        Static_Reaction := Static_Reaction + reaction_bonus_karma;
        debug_msg("Karma Reaction Bonus == " + Static_Reaction);
        Static_Reaction := Static_Reaction + reaction_bonus_town_rep;
        debug_msg("Town Rep Bonus == " + Static_Reaction);
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
        if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
            tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        if (global_var(GVAR_KARMA_HOLY_WARRIOR) == 1) then begin
            Static_Reaction := Static_Reaction + 20;
        end
        else begin
            if (global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES) == 1) then begin
                Static_Reaction := Static_Reaction + 15;
            end
            else begin
                if (global_var(GVAR_KARMA_SHIELD_OF_HOPE) == 1) then begin
                    Static_Reaction := Static_Reaction + 10;
                end
                else begin
                    if (global_var(GVAR_KARMA_DEFENDER) == 1) then begin
                        Static_Reaction := Static_Reaction + 5;
                    end
                    else begin
                        if (global_var(GVAR_KARMA_WANDERER) == 1) then begin
                            Static_Reaction := Static_Reaction + 0;
                        end
                        else begin
                            if (global_var(GVAR_KARMA_BETRAYER) == 1) then begin
                                Static_Reaction := Static_Reaction + -5;
                            end
                            else begin
                                if (global_var(GVAR_KARMA_SWORD_OF_DESPAIR) == 1) then begin
                                    Static_Reaction := Static_Reaction + -10;
                                end
                                else begin
                                    if (global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE) == 1) then begin
                                        Static_Reaction := Static_Reaction + -15;
                                    end
                                    else begin
                                        Static_Reaction := Static_Reaction + -20;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        debug_msg("Good Person Reaction Bonus == " + Static_Reaction);
    end
    if (Slavery_Tolerant == 0) then begin
        if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
            Static_Reaction := Static_Reaction - 50;
        end
    end
    else begin
        if (Slavery_Tolerant == 1) then begin
            if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                Static_Reaction := Static_Reaction - 25;
            end
        end
        else begin
            if (Slavery_Tolerant == 3) then begin
                if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                    Static_Reaction := Static_Reaction + 25;
                end
            end
        end
    end
    debug_msg("Slaver + Aligned Reaction == " + Static_Reaction);
    Static_Reaction := Static_Reaction + (10 * has_trait(TRAIT_PERK, dude_obj, PERK_presence));
    debug_msg("Presence Reaction == " + Static_Reaction);
    if (global_var(GVAR_CHILDKILLER_REPUTATION) >= 2) then begin
        Static_Reaction := Static_Reaction + -30;
    end
    debug_msg("Childkiller Reaction == " + Static_Reaction);
    if (has_trait(TRAIT_PERK, dude_obj, PERK_cult_of_personality)) then begin
        if (Evil_Critter == 1) then begin
            if (Static_Reaction > 0) then begin
                Static_Reaction := Static_Reaction * -1;
            end
        end
        else begin
            if (Static_Reaction < 0) then begin
                Static_Reaction := Static_Reaction * -1;
            end
        end
    end
    set_local_var(0, local_var(3) + Static_Reaction);
    debug_msg("Initial Reaction == " + local_var(0));
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    From_WTG := 1;
    From_5 := 0;
    Barter_Count := 0;
    if (local_var(5) != 0) then begin
        call Node998();
    end
    else begin
        if (global_var(GVAR_BH_MINE) == 2) then begin
            start_gdialog(607, self_obj, 4, -1, -1);
            gsay_start;
            call Node023();
            gsay_end;
            end_dialogue;
        end
        else begin
            if ((global_var(GVAR_BH_MINE) == 3) or (global_var(GVAR_BH_MINE) == 4)) then begin
                start_gdialog(607, self_obj, 4, -1, -1);
                gsay_start;
                call Node024();
                gsay_end;
                end_dialogue;
            end
            else begin
                if ((global_var(GVAR_BH_MINE) == 5) or (global_var(GVAR_BH_MINE) == 6)) then begin
                    start_gdialog(607, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node025();
                    gsay_end;
                    end_dialogue;
                end
                else begin
                    if (global_var(GVAR_BH_MINE) == 8) then begin
                        start_gdialog(607, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node027();
                        gsay_end;
                        end_dialogue;
                    end
                    else begin
                        if (global_var(GVAR_BH_MINE) == 7) then begin
                            start_gdialog(607, self_obj, 4, -1, -1);
                            gsay_start;
                            call Node028();
                            gsay_end;
                            end_dialogue;
                        end
                        else begin
                            if (global_var(GVAR_READ_FRANCIS_NOTE) == 2) then begin
                                start_gdialog(607, self_obj, 4, -1, -1);
                                gsay_start;
                                call Node038();
                                gsay_end;
                                end_dialogue;
                            end
                            else begin
                                if (global_var(GVAR_BH_MINE) == 9) then begin
                                    start_gdialog(607, self_obj, 4, -1, -1);
                                    gsay_start;
                                    call Node022();
                                    gsay_end;
                                    end_dialogue;
                                end
                                else begin
                                    if ((global_var(GVAR_BH_CONSPIRACY) == 6) or (global_var(GVAR_ENEMY_BROKEN_HILLS) == 1)) then begin
                                        call Node029();
                                    end
                                    else begin
                                        start_gdialog(607, self_obj, 4, -1, -1);
                                        gsay_start;
                                        if (local_var(4) == 0) then begin
                                            call Node001();
                                        end
                                        else begin
                                            if (dude_is_stupid) then begin
                                                call Node008();
                                            end
                                            else begin
                                                call Node022();
                                            end
                                        end
                                        gsay_end;
                                        end_dialogue;
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_local_var(4, 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
        if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
            tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_BROKEN_HILLS, global_var(GVAR_TOWN_REP_BROKEN_HILLS) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (local_var(4) == 0) then begin
        display_mstr(100);
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(102);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
        set_global_var(GVAR_ENEMY_BROKEN_HILLS, 1);
    end
end

procedure map_enter_p_proc
begin
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 120);
    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_TOUGH_CITIZEN);
    if (map_first_run) then begin
        set_local_var(7, 500);
        set_local_var(8, -25);
    end
    if ((global_var(GVAR_BH_FTM) == 6) or (global_var(GVAR_BH_CONSPIRACY) == 5)) then begin
        set_obj_visibility(self_obj, 1);
    end
    else begin
        set_obj_visibility(self_obj, 0);
    end
end

procedure combat
begin
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
end

procedure Node001
begin
    Reply(103);
    if (dude_obj == 1) then begin
        giq_option(1, NAME, 104, Node002, NEUTRAL_REACTION);
    end
    if ((dude_obj == 2) or (dude_obj == 3)) then begin
        giq_option(2, NAME, 105, Node003, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 106, Node004, NEUTRAL_REACTION);
    giq_option(4, NAME, 107, Node005, GOOD_REACTION);
    giq_option(4, NAME, 108, Node006, BAD_REACTION);
    if (global_var(GVAR_BH_MINE) == 1) then begin
        giq_option(4, NAME, 109, Node007, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 110, Node033, NEUTRAL_REACTION);
    if (global_var(GVAR_DOGMEAT_HAS_ARMOR) == 3) then begin
        giq_option(4, NAME, 409, Node039, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
end

procedure Node002
begin
    item_caps_adjust(dude_obj, 5);
    Reply(111);
    giq_option(-3, NAME, 112, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    if (global_var(GVAR_BH_MIGHTY_MAN) == 0) then begin
        set_global_var(GVAR_BH_MIGHTY_MAN, 1);
    end
    Reply(113);
    giq_option(-3, NAME, 114, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    if (global_var(GVAR_BH_MINE) == 0) then begin
        set_global_var(GVAR_BH_MINE, 1);
    end
    if (From_5 == 1) then begin
        From_5 := 0;
        Reply(mstr(118) + " " + mstr(115));
    end
    else begin
        Reply(115);
    end
    giq_option(4, NAME, 116, Node011, NEUTRAL_REACTION);
    giq_option(4, NAME, 117, Node012, NEUTRAL_REACTION);
end

procedure Node005
begin
    From_5 := 1;
    set_local_var(3, local_var(3) + 20);
    set_local_var(0, local_var(0) + 20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node004();
end

procedure Node006
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    Reply(120);
    giq_option(4, NAME, 121, Node013, BAD_REACTION);
    giq_option(4, NAME, 122, Node007, GOOD_REACTION);
    giq_option(4, NAME, 123, Node014, BAD_REACTION);
    giq_option(4, NAME, 124, Node015, NEUTRAL_REACTION);
end

procedure Node007
begin
    if (global_var(GVAR_BH_MINE) == 0) then begin
        set_global_var(GVAR_BH_MINE, 1);
    end
    Reply(125);
    giq_option(4, NAME, 126, Node012, NEUTRAL_REACTION);
    giq_option(4, NAME, 127, Node011, NEUTRAL_REACTION);
end

procedure Node008
begin
    Reply(128);
    if (dude_iq == 1) then begin
        giq_option(1, NAME, 129, Node009, NEUTRAL_REACTION);
    end
    if ((dude_iq == 2) or (dude_iq == 3)) then begin
        giq_option(2, NAME, 130, Node010, NEUTRAL_REACTION);
    end
end

procedure Node009
begin
    gsay_message(NAME, 131, NEUTRAL_REACTION);
end

procedure Node010
begin
    gsay_message(NAME, 132, NEUTRAL_REACTION);
end

procedure Node011
begin
    gsay_message(NAME, 133, NEUTRAL_REACTION);
end

procedure Node012
begin
    set_global_var(GVAR_BH_MINE, 2);
    Reply(134);
    giq_option(4, NAME, 135, Node012a, NEUTRAL_REACTION);
    giq_option(4, NAME, 136, Node017, NEUTRAL_REACTION);
    giq_option(4, NAME, 137, Node018, NEUTRAL_REACTION);
end

procedure Node012a
begin
    call Node016();
end

procedure Node013
begin
    set_global_var(GVAR_BH_MINE, 2);
    Reply(138);
    giq_option(4, NAME, 139, Node012a, NEUTRAL_REACTION);
    giq_option(4, NAME, 140, Node017, NEUTRAL_REACTION);
    giq_option(4, NAME, 141, Node018, NEUTRAL_REACTION);
end

procedure Node014
begin
    set_local_var(3, local_var(3) + -20);
    set_local_var(0, local_var(0) + -20);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    gsay_message(NAME, 142, NEUTRAL_REACTION);
end

procedure Node015
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(GVAR_BH_MINE, 2);
    Reply(143);
    giq_option(4, NAME, 144, Node012a, NEUTRAL_REACTION);
    giq_option(4, NAME, 145, Node017, NEUTRAL_REACTION);
    giq_option(4, NAME, 146, Node015a, BAD_REACTION);
end

procedure Node015a
begin
    set_local_var(3, local_var(3) + -10);
    set_local_var(0, local_var(0) + -10);
    if (local_var(0) <= -75) then begin
        set_local_var(1, -4);
    end
    else begin
        if (local_var(0) <= -50) then begin
            set_local_var(1, -3);
        end
        else begin
            if (local_var(0) <= -25) then begin
                set_local_var(1, -2);
            end
            else begin
                if (local_var(0) <= -10) then begin
                    set_local_var(1, -1);
                end
                else begin
                    if (local_var(0) <= 10) then begin
                        set_local_var(1, 0);
                    end
                    else begin
                        if (local_var(0) <= 25) then begin
                            set_local_var(1, 1);
                        end
                        else begin
                            if (local_var(0) <= 50) then begin
                                set_local_var(1, 2);
                            end
                            else begin
                                if (local_var(0) <= 75) then begin
                                    set_local_var(1, 3);
                                end
                                else begin
                                    set_local_var(1, 4);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node018();
end

procedure Node016
begin
    Reply(mstr(302) + local_var(7) + mstr(147));
    giq_option(4, NAME, 148, Node016a, NEUTRAL_REACTION);
    giq_option(4, NAME, 149, Node019, GOOD_REACTION);
    giq_option(4, NAME, 150, Node021, BAD_REACTION);
end

procedure Node016a
begin
    if ((local_var(7) >= 1000) or (Barter_Count == 4)) then begin
        call Node020();
    end
    else begin
        Barter_Count := Barter_Count + 1;
        if (is_success(roll_vs_skill(dude_obj, 15, local_var(8)))) then begin
            set_local_var(7, local_var(7) + 100);
            set_local_var(8, local_var(8) - 25);
            call Node016();
        end
        else begin
            call Node020();
        end
    end
end

procedure Node017
begin
    set_global_var(GVAR_BH_MINE, 4);
    if (town_known(7) == 0) then begin
        debug_msg("  mark_on_map(" + 7 + ")");
        mark_area_known(0, 7, 1);
    end
    Reply(151);
    giq_option(4, NAME, 152, Node999, NEUTRAL_REACTION);
end

procedure Node018
begin
    Reply(153);
    giq_option(4, NAME, 154, Node999, NEUTRAL_REACTION);
end

procedure Node019
begin
    variable LVar0 := 0;
    LVar0 := local_var(7) / 2;
    item_caps_adjust(dude_obj, LVar0);
    set_global_var(GVAR_BH_MINE, 3);
    if (town_known(7) == 0) then begin
        debug_msg("  mark_on_map(" + 7 + ")");
        mark_area_known(0, 7, 1);
    end
    Reply(mstr(302) + local_var(7) + mstr(155));
    giq_option(4, NAME, 156, Node999, NEUTRAL_REACTION);
    return 0;
    LVar0 := 0;
end

procedure Node020
begin
    Reply(157);
    giq_option(4, NAME, 158, Node019, NEUTRAL_REACTION);
    giq_option(4, NAME, 159, Node021, BAD_REACTION);
end

procedure Node021
begin
    Reply(160);
    giq_option(4, NAME, 161, Node999, NEUTRAL_REACTION);
end

procedure Node022
begin
    if (From_WTG == 1) then begin
        From_WTG := 0;
        if ((global_var(GVAR_BH_JAIL) == 7) or (global_var(GVAR_BH_CONSPIRACY) == 7)) then begin
            Reply(165);
        end
        else begin
            if (local_var(1) >= 2) then begin
                Reply(162);
            end
            else begin
                if (local_var(1) <= -2) then begin
                    Reply(163);
                end
                else begin
                    Reply(164);
                end
            end
        end
    end
    else begin
        Reply(169);
    end
    giq_option(4, NAME, 170, Node033, NEUTRAL_REACTION);
    if (global_var(GVAR_BH_MINE) == 1) then begin
        giq_option(4, NAME, 171, Node007, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 172, Node034, NEUTRAL_REACTION);
    if (global_var(GVAR_DOGMEAT_HAS_ARMOR) == 3) then begin
        giq_option(4, NAME, 409, Node039, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 173, Node035, NEUTRAL_REACTION);
end

procedure Node023
begin
    Reply(174);
    giq_option(4, NAME, 175, Node016, NEUTRAL_REACTION);
    giq_option(4, NAME, 176, Node017, NEUTRAL_REACTION);
    giq_option(4, NAME, 177, Node018, NEUTRAL_REACTION);
    giq_option(4, NAME, 178, Node018, NEUTRAL_REACTION);
    if (global_var(GVAR_DOGMEAT_HAS_ARMOR) == 3) then begin
        giq_option(4, NAME, 409, Node039, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
end

procedure Node024
begin
    Reply(179);
    giq_option(4, NAME, 180, Node030, NEUTRAL_REACTION);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 181, Node031, BAD_REACTION);
    end
    else begin
        giq_option(4, NAME, 381, Node031, BAD_REACTION);
    end
    giq_option(4, NAME, 182, Node032, NEUTRAL_REACTION);
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
end

procedure Node025
begin
    Reply(183);
    giq_option(4, NAME, 184, Node032, NEUTRAL_REACTION);
    giq_option(7, NAME, 185, Node030, NEUTRAL_REACTION);
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
end

procedure Node027
begin
    variable LVar0 := 0;
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 20);
    debug_msg("Player gains " + 20 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
    if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
    end
    if (tmp_gen_rep >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (tmp_gen_rep >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (tmp_gen_rep >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (tmp_gen_rep >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (tmp_gen_rep > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(GVAR_BH_MINE, 9);
    LVar0 := create_object(242, 0, 0);
    add_obj_to_inven(dude_obj, LVar0);
    Reply(189);
    giq_option(4, NAME, 190, Node999, NEUTRAL_REACTION);
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
    return 0;
    LVar0 := 0;
end

procedure Node028
begin
    variable LVar0 := 0;
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 20);
    debug_msg("Player gains " + 20 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
    if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
    end
    if (tmp_gen_rep >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (tmp_gen_rep >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (tmp_gen_rep >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (tmp_gen_rep >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (tmp_gen_rep > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    set_global_var(GVAR_BH_MINE, 9);
    LVar0 := local_var(7) / 2;
    item_caps_adjust(dude_obj, LVar0);
    Reply(191);
    giq_option(4, NAME, 190, Node999, NEUTRAL_REACTION);
    if (global_var(GVAR_READ_FRANCIS_NOTE) == 1) then begin
        giq_option(4, NAME, 400, Node036, NEUTRAL_REACTION);
    end
    return 0;
    LVar0 := 0;
end

procedure Node029
begin
    float_msg(self_obj, mstr(192), FLOAT_MSG_YELLOW);
    call Node998();
end

procedure Node030
begin
    Reply(193);
    giq_option(4, NAME, 194, Node999, GOOD_REACTION);
    if (dude_gender == 0) then begin
        giq_option(4, NAME, 195, Node031, BAD_REACTION);
    end
    else begin
        giq_option(4, NAME, 382, Node031, BAD_REACTION);
    end
end

procedure Node031
begin
    if (local_var(9) == 0) then begin
        set_local_var(9, 1);
        set_local_var(3, local_var(3) + -10);
        set_local_var(0, local_var(0) + -10);
        if (local_var(0) <= -75) then begin
            set_local_var(1, -4);
        end
        else begin
            if (local_var(0) <= -50) then begin
                set_local_var(1, -3);
            end
            else begin
                if (local_var(0) <= -25) then begin
                    set_local_var(1, -2);
                end
                else begin
                    if (local_var(0) <= -10) then begin
                        set_local_var(1, -1);
                    end
                    else begin
                        if (local_var(0) <= 10) then begin
                            set_local_var(1, 0);
                        end
                        else begin
                            if (local_var(0) <= 25) then begin
                                set_local_var(1, 1);
                            end
                            else begin
                                if (local_var(0) <= 50) then begin
                                    set_local_var(1, 2);
                                end
                                else begin
                                    if (local_var(0) <= 75) then begin
                                        set_local_var(1, 3);
                                    end
                                    else begin
                                        set_local_var(1, 4);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    if (dude_gender == 0) then begin
        Reply(196);
    end
    else begin
        Reply(383);
    end
    giq_option(4, NAME, 197, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 198, Node998, BAD_REACTION);
end

procedure Node032
begin
    Reply(199);
    giq_option(4, NAME, 200, Node999, NEUTRAL_REACTION);
end

procedure Node033
begin
    From_WTG := 0;
    Reply(201);
    giq_option(4, NAME, 202, Node022, NEUTRAL_REACTION);
    giq_option(4, NAME, 203, Node999, NEUTRAL_REACTION);
end

procedure Node034
begin
    From_WTG := 0;
    Reply(204);
    giq_option(4, NAME, 205, Node022, NEUTRAL_REACTION);
end

procedure Node035
begin
    Reply(206);
    giq_option(4, NAME, 207, Node999, NEUTRAL_REACTION);
end

procedure Node036
begin
    Reply(401);
    giq_option(4, NAME, 402, Node037, NEUTRAL_REACTION);
    giq_option(4, NAME, 403, Node999, NEUTRAL_REACTION);
end

procedure Node037
begin
    Reply(404);
    giq_option(4, NAME, 405, Node999, NEUTRAL_REACTION);
end

procedure Node038
begin
    set_global_var(GVAR_READ_FRANCIS_NOTE, 3);
    Reply(406);
    giq_option(4, NAME, 407, Node022, NEUTRAL_REACTION);
    giq_option(4, NAME, 408, Node999, NEUTRAL_REACTION);
end

procedure Node039
begin
    Reply(410);
    giq_option(4, NAME, 411, Node040, NEUTRAL_REACTION);
    giq_option(4, NAME, 412, Node999, NEUTRAL_REACTION);
end

procedure Node040
begin
    Reply(413);
    giq_option(4, NAME, 414, Node041, NEUTRAL_REACTION);
end

procedure Node041
begin
    set_global_var(GVAR_DOGMEAT_HAS_ARMOR, 4);
end
