procedure spatial_p_proc;
procedure start;


procedure spatial_p_proc
begin
    if ((global_var(GVAR_BH_MISSING) == 5) or (global_var(GVAR_BH_MISSING) == 6) and (source_obj == dude_obj) and (local_var(0) == 0)) then begin
        set_local_var(0, local_var(0) + 1);
        if (global_var(GVAR_BH_MISSING) == 6) then begin
            set_global_var(GVAR_BH_MISSING, 8);
        end
        else begin
            set_global_var(GVAR_BH_MISSING, 7);
        end
        display_mstr(100);
        give_exp_points(500);
        display_msg(g_mstr(100) + 500 + g_mstr(101));
        set_global_var(GVAR_TOWN_REP_BROKEN_HILLS, global_var(GVAR_TOWN_REP_BROKEN_HILLS) + 5);
    end
end

procedure start
begin
end
