variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure timed_event_p_proc;
procedure Node000;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;
procedure Node022;
procedure Node023;
procedure Node024;
procedure Node030;
procedure Node031;
procedure Node032;
procedure Node033;
procedure Node034;
procedure Node035;
procedure Node040;
procedure Node041;
procedure Node042;
procedure Node043;
procedure Node044;
procedure Node045;
procedure Node046;
procedure Node050;
procedure Node051;
procedure Node052;
procedure Node053;
procedure Node060;
procedure Node061;
procedure Node062;
procedure Node063;
procedure Node064;
procedure Node065;
procedure Node070;
procedure Node071;
procedure Node072;
procedure Node073;
procedure Node074;
procedure Node075;
procedure Node076;
procedure Node077;
procedure Node078;
procedure Node079;
procedure Node080;
procedure Node081;
procedure Node082;
procedure Node083;
procedure Node085;
procedure Node086;
procedure Node087;
procedure Node088;
procedure Node089;
procedure Node090;
procedure Node091;
procedure Node092;
procedure Node093;
procedure Node094;
procedure Node999;
procedure Node998;
procedure Node996;

import variable modoc_jo_box_obj;
import variable generic_temp_box;
import variable modoc_jo_obj;
import variable ghost_farm_slag_obj;

procedure combat_p_proc;
procedure Node994;
procedure Node992;
procedure Node991;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    modoc_jo_obj := self_obj;
end

procedure critter_p_proc
begin
    variable LVar0 := 0;
    if (((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 200) or ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 300)) then begin
        if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 13) then begin
            anim(self_obj, 1000, 3);
            fade_in;
            set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (3 * 10));
            add_timer_event(self_obj, game_ticks(3) - 2, 666);
            set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 14);
            debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
        end
        else begin
            if (game_time >= global_var(GVAR_MODOC_STAGE_TIMER)) then begin
                if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 14) then begin
                    float_msg(self_obj, mstr(600), 8 + ((9 - 8) * has_trait(TRAIT_PERK, dude_obj, PERK_empathy)));
                    set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (3 * 10));
                    add_timer_event(self_obj, game_ticks(3) - 2, 666);
                    set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 15);
                    debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
                end
                else begin
                    if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 16) then begin
                        display_mstr(602 + (10 * ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 524288) != 0)));
                        float_msg(self_obj, mstr(603), FLOAT_MSG_YELLOW);
                        set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (5 * 10));
                        add_timer_event(self_obj, game_ticks(5) - 2, 666);
                        set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 17);
                        debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
                    end
                    else begin
                        if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 20) then begin
                            set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (5 * 10));
                            add_timer_event(self_obj, game_ticks(5) - 2, 666);
                            LVar0 := mstr(604);
                            if ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 200) then begin
                                LVar0 := LVar0 + (mstr(629) + mstr(605) + dude_name + mstr(606));
                            end
                            else begin
                                LVar0 := LVar0 + (dude_name + mstr(605) + mstr(630) + mstr(606));
                            end
                            if ((dude_gender == 0) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 200) or ((dude_gender == 1) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 300))) then begin
                                LVar0 := LVar0 + mstr(625);
                            end
                            else begin
                                LVar0 := LVar0 + mstr(627);
                            end
                            float_msg(self_obj, LVar0, 8 + ((9 - 8) * has_trait(TRAIT_PERK, dude_obj, PERK_empathy)));
                            set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 21);
                            debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
                        end
                        else begin
                            if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 22) then begin
                                set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (5 * 10));
                                add_timer_event(self_obj, game_ticks(5) - 2, 666);
                                LVar0 := mstr(604);
                                if ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 300) then begin
                                    LVar0 := LVar0 + (mstr(630) + mstr(605) + dude_name + mstr(606));
                                end
                                else begin
                                    LVar0 := LVar0 + (dude_name + mstr(605) + mstr(629) + mstr(606));
                                end
                                if ((dude_gender == 0) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 200) or ((dude_gender == 1) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 300))) then begin
                                    LVar0 := LVar0 + mstr(626);
                                end
                                else begin
                                    LVar0 := LVar0 + mstr(628);
                                end
                                float_msg(self_obj, LVar0, 8 + ((9 - 8) * has_trait(TRAIT_PERK, dude_obj, PERK_empathy)));
                                set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 23);
                                debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
                            end
                            else begin
                                if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 26) then begin
                                    if ((dude_gender == 0) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 200) or ((dude_gender == 1) and ((global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100)) == 300))) then begin
                                        float_msg(self_obj, mstr(607), 8 + ((9 - 8) * has_trait(TRAIT_PERK, dude_obj, PERK_empathy)));
                                    end
                                    else begin
                                        float_msg(self_obj, mstr(608 + (dude_gender == 0)), 8 + ((9 - 8) * has_trait(TRAIT_PERK, dude_obj, PERK_empathy)));
                                    end
                                    set_global_var(GVAR_MODOC_STAGE_TIMER, game_time + (5 * 10));
                                    add_timer_event(self_obj, game_ticks(5) - 2, 666);
                                    set_global_var(GVAR_MODOC_STAGE_STATE, global_var(GVAR_MODOC_STAGE_STATE) - (global_var(GVAR_MODOC_STAGE_STATE) % 100) + 27);
                                    debug_msg("\n SET_STAGE_EVENT == " + global_var(GVAR_MODOC_STAGE_STATE) + " in script " + self_name);
                                end
                                else begin
                                    if ((global_var(GVAR_MODOC_STAGE_STATE) % 100) == 27) then begin
                                        fade_out;
                                        game_ui_enable;
                                        set_global_var(GVAR_MODOC_STAGE_STATE, 0);
                                        set_global_var(GVAR_PARTY_NO_FOLLOW, 0);
                                        fade_in;
                                        set_local_var(5, 20143);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    else begin
        if (obj_can_see_obj(self_obj, dude_obj)) then begin
            if (((local_var(4) bwand 2) != 0) or (global_var(GVAR_TOWN_REP_MODOC) <= -1000)) then begin
                if (critter_is_fleeing(self_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                            if (anim_busy(self_obj) == 0) then begin
                                global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                                while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                                    debug_msg("flee loop: rot == " + global_temp);
                                    animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                    global_temp := (global_temp + 1) % 6;
                                end
                            end
                        end
                    end
                end
                else begin
                    attack(dude_obj);
                end
            end
        end
        if (CUR_MAP_GSTFARM) then begin
            if (obj_is_visible_flag(self_obj)) then begin
                if (obj_can_see_obj(self_obj, ghost_farm_slag_obj)) then begin
                    attack(ghost_farm_slag_obj);
                end
                else begin
                    if (tile_distance_objs(self_obj, dude_obj) > 8) then begin
                        if (tile_distance_objs(self_obj, dude_obj) > (8 * 2)) then begin
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 5), 1);
                        end
                        else begin
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(dude_tile, (obj_get_rot(dude_obj) + 3) % 6, 5), 0);
                        end
                    end
                end
            end
        end
        else begin
            if (local_var(6) < map_var(0)) then begin
                if (local_var(6) < 3) then begin
                    float_msg(self_obj, mstr(153 + local_var(6)), FLOAT_MSG_YELLOW);
                    set_local_var(6, local_var(6) + 1);
                end
                if (local_var(6) >= 3) then begin
                    debug_msg("calling Node998 from critter_p_proc");
                    call Node998();
                end
            end
        end
        if (tile_num(self_obj) != local_var(5)) then begin
            if ((tile_num(self_obj) != local_var(5)) and (local_var(5) != 0)) then begin
                if ((dest_tile == local_var(5)) and (step_tile < 0)) then begin
                    step_tile := step_tile + 1;
                end
                else begin
                    if (anim_busy(self_obj) == 0) then begin
                        dest_tile := local_var(5);
                        step_tile := local_var(5);
                        animate_move_obj_to_tile(self_obj, step_tile, 0);
                        while ((anim_busy(self_obj) == 0) and (tile_distance(tile_num(self_obj), local_var(5)) >= tile_distance(step_tile, local_var(5)))) do begin
                            step_tile := tile_num_in_direction(step_tile, rotation_to_tile(step_tile, tile_num(self_obj)), (1 % tile_distance(step_tile, tile_num(self_obj))) + 1);
                            animate_move_obj_to_tile(self_obj, step_tile, 0);
                        end
                        if (anim_busy(self_obj) == 0) then begin
                            if (tile_get_next_critter(tile_num_in_direction(tile_num(self_obj), obj_get_rot(self_obj), 1), elevation(self_obj), 0) != 0) then begin
                                if (anim_busy(self_obj) == 0) then begin
                                    global_temp := rotation_to_tile(tile_num_in_direction(tile_num(self_obj), rotation_to_tile(tile_num_in_direction(tile_num(self_obj), obj_get_rot(self_obj), 1), tile_num(self_obj)), 1), tile_num(self_obj));
                                    animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(2, 5)), 0);
                                    global_temp := (global_temp + 1) % 6;
                                    while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(tile_num_in_direction(tile_num(self_obj), rotation_to_tile(tile_num_in_direction(tile_num(self_obj), obj_get_rot(self_obj), 1), tile_num(self_obj)), 1), tile_num(self_obj)))) do begin
                                        debug_msg("flee loop: rot == " + global_temp);
                                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(2, 5)), 0);
                                        global_temp := (global_temp + 1) % 6;
                                    end
                                end
                            end
                            else begin
                                step_tile := -10;
                            end
                        end
                    end
                    else begin
                        if (tile_distance(tile_num(self_obj), local_var(5)) < tile_distance(dest_tile, local_var(5))) then begin
                            reg_anim_func(2, self_obj);
                        end
                    end
                end
            end
        end
    end
    return 0;
    LVar0 := 0;
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        debug_msg("BEEN CAUGHT STEALING!");
        call Node998();
    end
end

procedure talk_p_proc
begin
    script_overrides;
    if ((global_var(GVAR_MODOC_GHOST_FARM_SEED) == 2) or (((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) <= 0) or ((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) > 31) and (global_var(GVAR_SLAUGHTER_SLAG_TIME) > 0))) then begin
        float_msg(self_obj, mstr(150), FLOAT_MSG_YELLOW);
    end
    else begin
        if (CUR_MAP_GSTFARM) then begin
            float_msg(self_obj, message_str(SCRIPT_MODMAIN, random(1000, 1003)), FLOAT_MSG_RED);
        end
        else begin
            if ((local_var(4) bwand 512) != 0) then begin
                float_msg(self_obj, mstr(331), FLOAT_MSG_YELLOW);
            end
            else begin
                if (global_var(GVAR_MODOC_ENDINGS) == 4) then begin
                    move_obj_inven_to_obj(self_obj, generic_temp_box);
                    move_obj_inven_to_obj(modoc_jo_box_obj, self_obj);
                    start_gdialog(102, self_obj, 4, -1, -1);
                    gsay_start;
                    call Node090();
                    gsay_end;
                    end_dialogue;
                    move_obj_inven_to_obj(self_obj, modoc_jo_box_obj);
                    move_obj_inven_to_obj(generic_temp_box, self_obj);
                end
                else begin
                    if (global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) then begin
                        move_obj_inven_to_obj(self_obj, generic_temp_box);
                        move_obj_inven_to_obj(modoc_jo_box_obj, self_obj);
                        start_gdialog(102, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node003();
                        gsay_end;
                        end_dialogue;
                        move_obj_inven_to_obj(self_obj, modoc_jo_box_obj);
                        move_obj_inven_to_obj(generic_temp_box, self_obj);
                    end
                    else begin
                        move_obj_inven_to_obj(self_obj, generic_temp_box);
                        move_obj_inven_to_obj(modoc_jo_box_obj, self_obj);
                        start_gdialog(102, self_obj, 4, -1, -1);
                        gsay_start;
                        if ((((local_var(4) bwand 1) != 0) == 0) and ((global_var(GVAR_PLAYER_MARRIED) != 0) == 0)) then begin
                            call Node000();
                        end
                        else begin
                            if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) and (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) < 7)) then begin
                                call Node002();
                            end
                            else begin
                                call Node001();
                            end
                        end
                        gsay_end;
                        end_dialogue;
                        move_obj_inven_to_obj(self_obj, modoc_jo_box_obj);
                        move_obj_inven_to_obj(generic_temp_box, self_obj);
                        set_local_var(4, local_var(4) bwor 1);
                    end
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_GOOD_MONSTER, global_var(GVAR_GOOD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
        debug_msg("Player gains " + -10 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + -5);
        debug_msg("Added " + -5 + " to Town Rep");
    end
    set_global_var(GVAR_MODOC_GENERIC_FLAG_1, global_var(GVAR_MODOC_GENERIC_FLAG_1) bwor 524288);
end

procedure look_at_p_proc
begin
    script_overrides;
    if ((local_var(4) bwand 1) != 0) then begin
        display_mstr(random(102 + (1398 * ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 524288) != 0)), 106 + (1394 * ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 524288) != 0))));
    end
    else begin
        display_mstr(101);
    end
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(101);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        if ((global_var(GVAR_TOWN_REP_MODOC) <= -1000) == 0) then begin
            set_global_var(GVAR_TOWN_REP_MODOC, -1000);
        end
        debug_msg("calling Node998 from damage_p_proc");
        call Node998();
    end
end

procedure map_enter_p_proc
begin
    if ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 524288) != 0) then begin
        if (CUR_MAP_GSTFARM) then begin
            if (obj_is_visible_flag(self_obj) == 1) then begin
                set_obj_visibility(self_obj, 1);
            end
            destroy_object(self_obj);
        end
    end
    else begin
        if (is_loading_game == 0) then begin
            if ((obj_in_party(self_obj)) == 0) then begin
                if (CUR_MAP_GSTFARM) then begin
                    if (((global_var(GVAR_MODOC_GENERIC_FLAG_2) bwand 1024) != 0) and (global_var(GVAR_SLAG_CNT) <= 0) or ((global_var(GVAR_MODOC_GHOST_FARM_SEED) == 2) or (((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) <= 0) or ((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) > 31) and (global_var(GVAR_SLAUGHTER_SLAG_TIME) > 0)))) then begin
                        debug_msg("no need for attackers");
                        if (obj_is_visible_flag(self_obj) == 1) then begin
                            set_obj_visibility(self_obj, 1);
                        end
                        destroy_object(self_obj);
                    end
                    else begin
                        if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 1) then begin
                            debug_msg("showing need for attackers");
                            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
                            if (obj_is_visible_flag(self_obj) == 0) then begin
                                set_obj_visibility(self_obj, 0);
                            end
                        end
                        else begin
                            debug_msg("hiding need for attackers");
                            if (obj_is_visible_flag(self_obj) == 1) then begin
                                set_obj_visibility(self_obj, 1);
                            end
                        end
                    end
                end
            end
        end
    end
    if ((CUR_MAP_MODINN) and (elevation(self_obj) != ((global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 1) != 0))) then begin
        move_to(self_obj, tile_num(self_obj), (global_var(GVAR_MODOC_GENERIC_FLAG_1) bwand 1) != 0);
    end
    modoc_jo_obj := self_obj;
    if (map_first_run) then begin
        if (CUR_MAP_MODMAIN) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 28);
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PEASANTS);
        end
        set_local_var(5, tile_num(self_obj));
        restock_amt := random(20, 20);
        if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
            if (100 >= random(1, 100)) then begin
                if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
                    restock_obj := create_object(41, 0, 0);
                    add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 41));
                end
                else begin
                    if (obj_is_carrying_obj_pid(self_obj, 41) > restock_amt) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 41);
                        if ((obj_is_carrying_obj_pid(self_obj, 41) - restock_amt) < removed_qty) then begin
                            removed_qty := obj_is_carrying_obj_pid(self_obj, 41) - restock_amt;
                        end
                        if (removed_qty > 0) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 41);
                            if (obj_type(self_obj) == 1) then begin
                                restock_obj := obj_carrying_pid_obj(self_obj, 41);
                                if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                                    if (obj_item_subtype(critter_inven_obj(self_obj, INVEN_TYPE_WORN)) == 0) then begin
                                        restock_obj := critter_inven_obj(self_obj, INVEN_TYPE_WORN);
                                        debug_msg("armour pid == " + obj_pid(restock_obj));
                                        rm_obj_from_inven(self_obj, restock_obj);
                                        add_obj_to_inven(self_obj, restock_obj);
                                    end
                                end
                                else begin
                                    if ((critter_inven_obj(self_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(self_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                                        inven_unwield(self_obj);
                                    end
                                end
                            end
                            restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                            destroy_object(restock_obj);
                        end
                        restock_obj := 0;
                        restock_amt := 0;
                    end
                    else begin
                        restock_obj := 0;
                    end
                end
            end
        end
        else begin
            if (obj_is_carrying_obj_pid(self_obj, 41) < restock_amt) then begin
                restock_obj := create_object(41, 0, 0);
                add_mult_objs_to_inven(self_obj, restock_obj, restock_amt - obj_is_carrying_obj_pid(self_obj, 41));
            end
            else begin
                if (obj_is_carrying_obj_pid(self_obj, 41) > restock_amt) then begin
                    removed_qty := obj_is_carrying_obj_pid(self_obj, 41);
                    if ((obj_is_carrying_obj_pid(self_obj, 41) - restock_amt) < removed_qty) then begin
                        removed_qty := obj_is_carrying_obj_pid(self_obj, 41) - restock_amt;
                    end
                    if (removed_qty > 0) then begin
                        restock_obj := obj_carrying_pid_obj(self_obj, 41);
                        if (obj_type(self_obj) == 1) then begin
                            restock_obj := obj_carrying_pid_obj(self_obj, 41);
                            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                                if (obj_item_subtype(critter_inven_obj(self_obj, INVEN_TYPE_WORN)) == 0) then begin
                                    restock_obj := critter_inven_obj(self_obj, INVEN_TYPE_WORN);
                                    debug_msg("armour pid == " + obj_pid(restock_obj));
                                    rm_obj_from_inven(self_obj, restock_obj);
                                    add_obj_to_inven(self_obj, restock_obj);
                                end
                            end
                            else begin
                                if ((critter_inven_obj(self_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(self_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                                    inven_unwield(self_obj);
                                end
                            end
                        end
                        restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
                        destroy_object(restock_obj);
                    end
                    restock_obj := 0;
                    restock_amt := 0;
                end
                else begin
                    restock_obj := 0;
                end
            end
        end
    end
    else begin
        if (cur_map_index != MAP_GSTFARM) then begin
            critter_attempt_placement(self_obj, local_var(5), dude_elevation);
        end
    end
end

procedure map_update_p_proc
begin
    modoc_jo_obj := self_obj;
end

procedure timed_event_p_proc
begin
    if (fixed_param == 666) then begin
        float_msg(self_obj, " ", FLOAT_MSG_YELLOW);
        float_msg(dude_obj, " ", FLOAT_MSG_YELLOW);
        float_msg_clear(self_obj);
        float_msg_clear(dude_obj);
    end
    else begin
        if (map_var(0) < 4) then begin
            set_map_var(0, map_var(0) + 1);
        end
    end
end

procedure Node000
begin
    debug_msg("Node000");
    Reply(156);
    giq_option(4, NAME, 157, Node010, NEUTRAL_REACTION);
    giq_option(4, NAME, 158, Node040, NEUTRAL_REACTION);
    if ((global_var(GVAR_DUDE_STOMACH) >= 4) and (global_var(GVAR_DUDE_STOMACH) < 7) or ((global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) >= 4) and (global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) < 7))) then begin
        giq_option(4, NAME, 159, Node060, NEUTRAL_REACTION);
    end
    giq_option(-3, NAME, 160, Node030, NEUTRAL_REACTION);
end

procedure Node001
begin
    debug_msg("Node001");
    Reply(161);
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) == 0) then begin
        giq_option(4, NAME, 162, Node050, NEUTRAL_REACTION);
        giq_option(-3, NAME, 168, Node030, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_DUDE_STOMACH) >= 4) and (global_var(GVAR_DUDE_STOMACH) < 7) or ((global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) >= 4) and (global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) < 7))) then begin
        giq_option(4, NAME, 164, Node060, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 165, Node051, NEUTRAL_REACTION);
    giq_option(4, NAME, 166, Node045, NEUTRAL_REACTION);
    giq_option(4, NAME, 167, Node052, NEUTRAL_REACTION);
    giq_option(4, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, g_mstr(random(300, 303)), Node999, NEUTRAL_REACTION);
end

procedure Node002
begin
    debug_msg("Node002");
    Reply(169);
    if (((global_var(GVAR_MODOC_GENERIC_FLAG_2) bwand 1024) != 0) and (global_var(GVAR_SLAG_CNT) <= 0) or ((global_var(GVAR_MODOC_GHOST_FARM_SEED) == 2) or (((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) <= 0) or ((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) > 31) and (global_var(GVAR_SLAUGHTER_SLAG_TIME) > 0)))) then begin
        giq_option(4, NAME, 170, Node081, NEUTRAL_REACTION);
        giq_option(-3, NAME, 174, Node065, NEUTRAL_REACTION);
    end
    if (obj_is_carrying_obj_pid(dude_obj, 263) > 0) then begin
        giq_option(4, NAME, 171, Node070, NEUTRAL_REACTION);
        giq_option(-3, NAME, 172, Node061, NEUTRAL_REACTION);
    end
    giq_option(-3, NAME, 173, Node064, NEUTRAL_REACTION);
    giq_option(-3, NAME, 175, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 176, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    variable LVar0 := 0;
    debug_msg("Node003");
    LVar0 := global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24));
    if (((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) <= 0) or ((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) > 31) and (global_var(GVAR_SLAUGHTER_SLAG_TIME) > 0)) then begin
        Reply(803);
        giq_option(4, NAME, 804, Node991, NEUTRAL_REACTION);
        giq_option(4, NAME, 805, Node991, NEUTRAL_REACTION);
    end
    else begin
        if (LVar0 == 1) then begin
            Reply(802);
        end
        else begin
            Reply(mstr(800) + LVar0 + mstr(801));
        end
    end
    if (((global_var(GVAR_MODOC_GENERIC_FLAG_2) bwand 1024) != 0) and (global_var(GVAR_SLAG_CNT) <= 0) or ((global_var(GVAR_MODOC_GHOST_FARM_SEED) == 2) or (((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) <= 0) or ((global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))) > 31) and (global_var(GVAR_SLAUGHTER_SLAG_TIME) > 0)))) then begin
        giq_option(4, NAME, 170, Node085, NEUTRAL_REACTION);
    end
    else begin
        if ((global_var(GVAR_MODOC_SLAUGHTER_BESS_TIME) >= 1) and (((local_var(4) bwand 4096) != 0) == 0)) then begin
            giq_option(4, NAME, 179, Node086, NEUTRAL_REACTION);
        end
        if ((global_var(GVAR_KARL_STATE) >= 1) and (((local_var(4) bwand 1024) != 0) == 0)) then begin
            giq_option(4, NAME, 180, Node087, NEUTRAL_REACTION);
        end
        giq_option(4, NAME, 181, Node089, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 806, Node991, NEUTRAL_REACTION);
    giq_option(4, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
    giq_option(-3, NAME, 175, Node999, NEUTRAL_REACTION);
    return 0;
    LVar0 := 0;
end

procedure Node010
begin
    debug_msg("Node010");
    Reply(182);
    giq_option(4, NAME, 183, Node011, NEUTRAL_REACTION);
    giq_option(4, NAME, 166, Node045, NEUTRAL_REACTION);
    giq_option(4, NAME, 167, Node052, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node011
begin
    debug_msg("Node011");
    Reply(186);
    giq_option(4, NAME, 187, Node035, NEUTRAL_REACTION);
    giq_option(4, NAME, 188, Node035, NEUTRAL_REACTION);
    giq_option(4, NAME, 189, Node012, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node012
begin
    debug_msg("Node012");
    Reply(190);
    giq_option(1, NAME, 191, Node013, NEUTRAL_REACTION);
end

procedure Node013
begin
    debug_msg("Node013");
    Reply(192);
    giq_option(1, NAME, 193, Node014, NEUTRAL_REACTION);
end

procedure Node014
begin
    debug_msg("Node014");
    Reply(194);
    giq_option(1, NAME, 195, Node015, NEUTRAL_REACTION);
end

procedure Node015
begin
    debug_msg("Node015");
    Reply(196);
    giq_option(1, NAME, 197, Node016, NEUTRAL_REACTION);
end

procedure Node016
begin
    debug_msg("Node016");
    Reply(198);
    giq_option(1, NAME, 199, Node017, NEUTRAL_REACTION);
end

procedure Node017
begin
    debug_msg("Node017");
    Reply(200);
    giq_option(1, NAME, 201, Node018, NEUTRAL_REACTION);
end

procedure Node018
begin
    debug_msg("Node018");
    Reply(202);
    giq_option(1, NAME, 203, Node019, NEUTRAL_REACTION);
end

procedure Node019
begin
    debug_msg("Node019");
    Reply(204);
    giq_option(1, NAME, 205, Node020, NEUTRAL_REACTION);
end

procedure Node020
begin
    debug_msg("Node020");
    Reply(206);
    giq_option(4, NAME, 207, Node994, NEUTRAL_REACTION);
    giq_option(4, NAME, 208, Node022, NEUTRAL_REACTION);
end

procedure Node021
begin
    debug_msg("Node021");
    Reply(209);
    giq_option(4, NAME, 210, Node022, NEUTRAL_REACTION);
    giq_option(4, NAME, 400, Node992, NEUTRAL_REACTION);
    giq_option(4, NAME, 211, Node023, NEUTRAL_REACTION);
end

procedure Node022
begin
    debug_msg("Node022");
    if (town_known(20) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 20 + ")");
        mark_area_known(MARK_TYPE_TOWN, 20, MARK_STATE_KNOWN);
    end
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 1) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 1);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) < 4) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 4);
    end
    Reply(212);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node023
begin
    debug_msg("Node023");
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
    debug_msg("Player gains " + -10 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    Reply(213);
    giq_option(1, NAME, g_mstr(350), Node998, NEUTRAL_REACTION);
end

procedure Node024
begin
    debug_msg("Node024");
    Reply(215);
    giq_option(4, NAME, 216, Node022, NEUTRAL_REACTION);
    giq_option(1, NAME, 217, Node999, NEUTRAL_REACTION);
end

procedure Node030
begin
    debug_msg("Node030");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 1);
    end
    Reply(218);
    giq_option(-3, NAME, 219, Node032, NEUTRAL_REACTION);
    giq_option(-3, NAME, 220, Node031, NEUTRAL_REACTION);
end

procedure Node031
begin
    debug_msg("Node031");
    Reply(222);
    giq_option(1, NAME, 223, Node999, NEUTRAL_REACTION);
end

procedure Node032
begin
    debug_msg("Node032");
    Reply(224);
    giq_option(-3, NAME, 225, Node033, NEUTRAL_REACTION);
    giq_option(-3, NAME, 226, Node034, NEUTRAL_REACTION);
end

procedure Node033
begin
    debug_msg("Node033");
    mark_area_known(MARK_TYPE_TOWN, 20, MARK_STATE_KNOWN);
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 1) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 1);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) < 4) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 4);
    end
    Reply(227);
    giq_option(1, NAME, 228, Node999, NEUTRAL_REACTION);
end

procedure Node034
begin
    debug_msg("Node034");
    Reply(229);
    giq_option(1, NAME, g_mstr(350), Node999, NEUTRAL_REACTION);
end

procedure Node035
begin
    debug_msg("Node035");
    Reply(230);
    giq_option(1, NAME, g_mstr(350), Node999, NEUTRAL_REACTION);
end

procedure Node040
begin
    debug_msg("Node040");
    Reply(231);
    giq_option(4, NAME, 232, Node041, NEUTRAL_REACTION);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node041
begin
    debug_msg("Node041");
    set_global_var(GVAR_MODOC_BODIES, 1);
    Reply(237);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node042
begin
    debug_msg("Node042");
    set_global_var(GVAR_MODOC_SLAUGHTER_FLAG, 1);
    Reply(242);
    giq_option(4, NAME, 232, Node041, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node043
begin
    debug_msg("Node043");
    set_global_var(GVAR_MODOC_ROSE_FLAG, 1);
    Reply(247);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 232, Node041, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node044
begin
    debug_msg("Node044");
    set_global_var(GVAR_MODOC_TANNERY_FLAG, 1);
    Reply(252);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 232, Node041, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node045
begin
    debug_msg("Node045");
    Reply(257);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 410, Node046, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node046
begin
    debug_msg("Node046");
    Reply(500);
    giq_option(4, NAME, 233, Node042, NEUTRAL_REACTION);
    giq_option(4, NAME, 235, Node043, NEUTRAL_REACTION);
    giq_option(4, NAME, 234, Node044, NEUTRAL_REACTION);
    giq_option(4, NAME, 236, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node050
begin
    debug_msg("Node050");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 1);
    end
    Reply(262);
    giq_option(4, NAME, 263, Node011, NEUTRAL_REACTION);
    giq_option(1, NAME, 264, Node999, NEUTRAL_REACTION);
end

procedure Node051
begin
    debug_msg("Node051");
    Reply(265);
    giq_option(4, NAME, 266, Node996, NEUTRAL_REACTION);
    giq_option(4, NAME, 267, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, 268, Node999, NEUTRAL_REACTION);
end

procedure Node052
begin
    debug_msg("Node052");
    Reply(269);
    giq_option(4, NAME, 270, Node053, NEUTRAL_REACTION);
    giq_option(1, NAME, 271, Node999, NEUTRAL_REACTION);
end

procedure Node053
begin
    debug_msg("Node053");
    Reply(272);
    giq_option(4, NAME, 273, Node001, NEUTRAL_REACTION);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node060
begin
    debug_msg("Node060");
    Reply(274);
    giq_option(1, NAME, g_mstr(350), Node999, NEUTRAL_REACTION);
end

procedure Node061
begin
    debug_msg("Node061");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 4) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 4);
    end
    set_global_var(GVAR_SLAUGHTER_SLAG_TIME, -1);
    debug_msg("set_modoc_ending_happy");
    if ((global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) == 0) then begin
        set_global_var(GVAR_SLAUGHTER_SLAG_TIME, (game_time / (10 * 60 * 60 * 24)) + 31);
    end
    debug_msg("didn't set new kill slag time");
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 263);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 263);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 263);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        destroy_object(restock_obj);
    end
    restock_obj := 0;
    restock_amt := 0;
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + 15);
    set_global_var(GVAR_TOWN_REP_GHOST_FARM, global_var(GVAR_TOWN_REP_GHOST_FARM) + 15);
    display_mstr(1000);
    give_exp_points(2000);
    display_msg(g_mstr(100) + 2000 + g_mstr(101));
    Reply(275);
    giq_option(-3, NAME, 276, Node062, NEUTRAL_REACTION);
end

procedure Node062
begin
    debug_msg("Node062");
    gdialog_set_barter_mod(-50);
    Reply(277);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(-3, NAME, 278, Node063, NEUTRAL_REACTION);
    giq_option(1, NAME, 220, Node999, NEUTRAL_REACTION);
end

procedure Node063
begin
    debug_msg("Node063");
    Reply(280);
    giq_option(1, NAME, 220, Node999, NEUTRAL_REACTION);
end

procedure Node064
begin
    debug_msg("Node064");
    Reply(282);
    giq_option(1, NAME, g_mstr(random(300, 303)), Node999, NEUTRAL_REACTION);
end

procedure Node065
begin
    debug_msg("Node065");
    if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_GHOST_FARM_SEED, 1);
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    Reply(283);
    giq_option(-3, NAME, 284, Node062, NEUTRAL_REACTION);
end

procedure Node070
begin
    debug_msg("Node070");
    if ((global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) == 0) then begin
        set_global_var(GVAR_SLAUGHTER_SLAG_TIME, (game_time / (10 * 60 * 60 * 24)) + 31);
    end
    debug_msg("didn't set new kill slag time");
    debug_msg("days_till_slag_attack == " + (global_var(GVAR_SLAUGHTER_SLAG_TIME) - (game_time / (10 * 60 * 60 * 24))));
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 2) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 2);
    end
    debug_msg("set_modoc_ending_wipeout_1");
    removed_qty := obj_is_carrying_obj_pid(dude_obj, 263);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(dude_obj, 263);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(dude_obj, 263);
            if (critter_inven_obj(self_obj, INVEN_TYPE_WORN) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(dude_obj, INVEN_TYPE_WORN)) == 0) then begin
                    restock_obj := critter_inven_obj(dude_obj, INVEN_TYPE_WORN);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(dude_obj, restock_obj);
                    add_obj_to_inven(dude_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(dude_obj, INVEN_TYPE_LEFT_HAND) == restock_obj) or (critter_inven_obj(dude_obj, INVEN_TYPE_RIGHT_HAND) == restock_obj)) then begin
                    inven_unwield(dude_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(dude_obj, restock_obj, removed_qty);
        destroy_object(restock_obj);
    end
    restock_obj := 0;
    restock_amt := 0;
    set_global_var(GVAR_MODOC_MESSAGE, 2);
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    Reply(285);
    if ((global_var(GVAR_KARL_STATE) >= 1) and (((local_var(4) bwand 1024) != 0) == 0)) then begin
        giq_option(4, NAME, 286, Node071, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_MODOC_SLAUGHTER_BESS_TIME) >= 1) and (((local_var(4) bwand 4096) != 0) == 0)) then begin
        giq_option(4, NAME, 288, Node086, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_SLAG_ATTACK) >= 2) then begin
        giq_option(4, NAME, 289, Node079, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 820, Node083, NEUTRAL_REACTION);
    giq_option(4, NAME, 821, Node080, NEUTRAL_REACTION);
end

procedure Node071
begin
    debug_msg("Node071");
    set_local_var(4, local_var(4) bwor 1024);
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 4) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 4);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    Reply(290);
    if (global_var(GVAR_MODOC_SLAUGHTER_BESS_TIME) >= 1) then begin
        giq_option(4, NAME, 288, Node075, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_MODOC_GENERIC_FLAG_2) bwand 2) != 0) then begin
        giq_option(4, NAME, 292, Node072, NEUTRAL_REACTION);
    end
    else begin
        giq_option(4, NAME, 850, Node003, NEUTRAL_REACTION);
    end
end

procedure Node072
begin
    debug_msg("Node072");
    Reply(293);
    giq_option(4, NAME, 294, Node073, NEUTRAL_REACTION);
    if ((global_var(GVAR_MODOC_GENERIC_FLAG_2) bwand 1) != 0) then begin
        giq_option(4, NAME, 295, Node077, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 296, Node080, NEUTRAL_REACTION);
end

procedure Node073
begin
    debug_msg("Node073");
    if ((global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) == 0) then begin
        set_global_var(GVAR_SLAUGHTER_SLAG_TIME, (game_time / (10 * 60 * 60 * 24)) + 31);
    end
    debug_msg("didn't set new kill slag time");
    Reply(297);
    giq_option(1, NAME, 298, Node999, NEUTRAL_REACTION);
    giq_option(4, NAME, 299, Node074, NEUTRAL_REACTION);
end

procedure Node074
begin
    debug_msg("Node074");
    Reply(300);
    giq_option(1, NAME, 301, Node999, NEUTRAL_REACTION);
end

procedure Node075
begin
    debug_msg("Node075");
    set_global_var(GVAR_MODOC_GENERIC_FLAG_2, global_var(GVAR_MODOC_GENERIC_FLAG_2) bwor 131072);
    debug_msg("set_karl_come_home");
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 5) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 5);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    set_local_var(4, local_var(4) bwor 4096);
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 4) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 4);
    end
    set_global_var(GVAR_SLAUGHTER_SLAG_TIME, -1);
    debug_msg("set_modoc_ending_happy");
    set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + 30);
    set_global_var(GVAR_TOWN_REP_GHOST_FARM, global_var(GVAR_TOWN_REP_GHOST_FARM) + 30);
    display_mstr(1000);
    give_exp_points(3500);
    display_msg(g_mstr(100) + 3500 + g_mstr(101));
    Reply(302);
    giq_option(1, NAME, 303, Node076, NEUTRAL_REACTION);
end

procedure Node076
begin
    debug_msg("Node076");
    set_map_var(0, -1);
    gdialog_set_barter_mod(-75);
    Reply(304);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node077
begin
    debug_msg("Node077");
    Reply(305);
    giq_option(4, NAME, 306, Node078, NEUTRAL_REACTION);
    giq_option(4, NAME, 307, Node083, NEUTRAL_REACTION);
end

procedure Node078
begin
    debug_msg("Node078");
    if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_GHOST_FARM_SEED, 1);
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 3) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 3);
    end
    debug_msg("set_modoc_ending_wipeout_2");
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    Reply(308);
    giq_option(1, NAME, g_mstr(350), Node991, NEUTRAL_REACTION);
end

procedure Node079
begin
    debug_msg("Node079");
    if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_GHOST_FARM_SEED, 1);
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 3) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 3);
    end
    debug_msg("set_modoc_ending_wipeout_2");
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    Reply(309);
    giq_option(1, NAME, g_mstr(350), Node991, NEUTRAL_REACTION);
end

procedure Node080
begin
    debug_msg("Node080");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 2) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 2);
    end
    debug_msg("set_modoc_ending_wipeout_1");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 3) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 3);
    end
    debug_msg("set_modoc_ending_wipeout_2");
    if ((global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) == 0) then begin
        set_global_var(GVAR_SLAUGHTER_SLAG_TIME, (game_time / (10 * 60 * 60 * 24)) + 31);
    end
    debug_msg("didn't set new kill slag time");
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + -5);
    set_global_var(GVAR_TOWN_REP_GHOST_FARM, global_var(GVAR_TOWN_REP_GHOST_FARM) + -5);
    give_exp_points(700);
    display_msg(g_mstr(100) + 700 + g_mstr(101));
    set_local_var(4, local_var(4) bwor 512);
    Reply(310);
    if (town_known(5) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 5 + ")");
        mark_area_known(MARK_TYPE_TOWN, 5, MARK_STATE_KNOWN);
    end
    giq_option(1, NAME, g_mstr(350), Node999, NEUTRAL_REACTION);
end

procedure Node081
begin
    debug_msg("Node081");
    if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_GHOST_FARM_SEED, 1);
        set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + -20);
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    Reply(311);
    giq_option(4, NAME, 312, Node082, NEUTRAL_REACTION);
    giq_option(4, NAME, 313, Node076, NEUTRAL_REACTION);
end

procedure Node082
begin
    debug_msg("Node082");
    set_local_var(4, local_var(4) bwor 512);
    Reply(314);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node083
begin
    debug_msg("Node083");
    if ((global_var(GVAR_SLAUGHTER_SLAG_TIME) != 0) == 0) then begin
        set_global_var(GVAR_SLAUGHTER_SLAG_TIME, (game_time / (10 * 60 * 60 * 24)) + 31);
    end
    debug_msg("didn't set new kill slag time");
    Reply(315 + (((local_var(4) bwand 1024) != 0) == 0));
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node085
begin
    debug_msg("Node085");
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    set_local_var(4, local_var(4) bwor 512);
    Reply(317);
    giq_option(1, NAME, g_mstr(random(375, 376)), Node999, NEUTRAL_REACTION);
end

procedure Node086
begin
    debug_msg("Node086");
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 4) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 4);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    set_global_var(GVAR_MODOC_GENERIC_FLAG_2, global_var(GVAR_MODOC_GENERIC_FLAG_2) bwor 131072);
    debug_msg("set_karl_come_home");
    if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 5) then begin
        set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 5);
    end
    debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    set_local_var(4, local_var(4) bwor 4096);
    Reply(318);
    if ((local_var(4) bwand 1024) != 0) then begin
        giq_option(4, NAME, 320, Node088, NEUTRAL_REACTION);
    end
    else begin
        if (global_var(GVAR_KARL_STATE) >= 1) then begin
            giq_option(4, NAME, 319, Node087, NEUTRAL_REACTION);
        end
        giq_option(1, NAME, 321, Node999, NEUTRAL_REACTION);
    end
end

procedure Node087
begin
    debug_msg("Node087");
    set_local_var(4, local_var(4) bwor 1024);
    Reply(322);
    if (global_var(GVAR_MODOC_SLAUGHTER_BESS_TIME) >= 1) then begin
        giq_option(4, NAME, 320, Node088, NEUTRAL_REACTION);
    end
    else begin
        if (global_var(GVAR_MODOC_SLAUGHTER_BESS_TIME) >= 1) then begin
            giq_option(4, NAME, 288, Node086, NEUTRAL_REACTION);
        end
        giq_option(1, NAME, 321, Node999, NEUTRAL_REACTION);
    end
end

procedure Node088
begin
    debug_msg("Node088");
    if (global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) then begin
        if (global_var(GVAR_MODOC_GHOST_SEED_PIP) < 3) then begin
            set_global_var(GVAR_MODOC_GHOST_SEED_PIP, 3);
        end
        debug_msg("ghost pip == " + global_var(GVAR_MODOC_GHOST_SEED_PIP));
    end
    if (global_var(GVAR_MODOC_ENDINGS) < 4) then begin
        set_global_var(GVAR_MODOC_ENDINGS, 4);
    end
    set_global_var(GVAR_SLAUGHTER_SLAG_TIME, -1);
    debug_msg("set_modoc_ending_happy");
    set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + 30);
    set_global_var(GVAR_TOWN_REP_GHOST_FARM, global_var(GVAR_TOWN_REP_GHOST_FARM) + 30);
    give_exp_points(3500);
    display_msg(g_mstr(100) + 3500 + g_mstr(101));
    Reply(326);
    giq_option(4, NAME, 327, Node076, NEUTRAL_REACTION);
end

procedure Node089
begin
    variable LVar0 := "";
    debug_msg("Node089");
    if (((local_var(4) bwand 1024) != 0) == 0) then begin
        LVar0 := LVar0 + mstr(328);
    end
    if (((local_var(4) bwand 4096) != 0) == 0) then begin
        LVar0 := LVar0 + mstr(329);
    end
    Reply(LVar0);
    giq_option(1, NAME, 330, Node999, NEUTRAL_REACTION);
    return 0;
    LVar0 := 0;
end

procedure Node090
begin
    if ((local_var(4) bwand 2048) != 0) then begin
        Reply(900);
    end
    else begin
        set_local_var(4, local_var(4) bwor 2048);
        Reply(152);
    end
    giq_option(-3, NAME, g_mstr(random(300, 303)), Node999, NEUTRAL_REACTION);
    if ((global_var(GVAR_DUDE_STOMACH) >= 4) and (global_var(GVAR_DUDE_STOMACH) < 7) or ((global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) >= 4) and (global_var(GVAR_MODOC_FAMILY_FEUD_SEED_ONE) < 7))) then begin
        giq_option(4, NAME, 159, Node060, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 165, Node996, NEUTRAL_REACTION);
    if ((global_var(GVAR_ROOM_OPEN) == 0) and (global_var(GVAR_MODOC_ENDINGS) == 4) and (global_var(GVAR_COLD_HEARTS_ENEMY) == 1)) then begin
        giq_option(4, NAME, 1001, Node091, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ROOM_OPEN) == 2) then begin
        giq_option(4, NAME, 1006, Node093, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ROOM_OPEN) == 5) then begin
        giq_option(4, NAME, 1009, Node094, NEUTRAL_REACTION);
    end
    giq_option(4, NAME, 925, Node999, NEUTRAL_REACTION);
end

procedure Node091
begin
    Reply(1002);
    giq_option(4, NAME, 1003, Node092, NEUTRAL_REACTION);
end

procedure Node092
begin
    Reply(1004);
    giq_option(4, NAME, 1005, Node999, NEUTRAL_REACTION);
    set_global_var(GVAR_ROOM_OPEN, 1);
end

procedure Node093
begin
    Reply(1007);
    giq_option(4, NAME, 1008, Node999, NEUTRAL_REACTION);
end

procedure Node094
begin
    Reply(1010);
    giq_option(4, NAME, 1011, Node999, NEUTRAL_REACTION);
    restock_obj := create_object(95, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 2);
    restock_obj := create_object(94, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    item_caps_adjust(dude_obj, 500);
    give_exp_points(500);
    display_msg(g_mstr(100) + 500 + g_mstr(101));
    display_mstr(1012);
    set_global_var(GVAR_ROOM_OPEN, global_var(GVAR_ROOM_OPEN) + 1);
end

procedure Node999
begin
end

procedure Node998
begin
    debug_msg("Node998");
    set_local_var(4, local_var(4) bwor 2);
end

procedure Node996
begin
    gdialog_barter;
    if (global_var(GVAR_MODOC_ENDINGS) == 4) then begin
        call Node090();
    end
    else begin
        call Node001();
    end
end

procedure combat_p_proc
begin
    if (global_var(GVAR_TOWN_REP_MODOC) <= -1000) then begin
        if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 0) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 28);
        end
    end
    else begin
        if (CUR_MAP_GSTFARM) then begin
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 0);
        end
    end
end

procedure Node994
begin
    if (is_success(roll_vs_skill(dude_obj, 14, 0))) then begin
        call Node021();
    end
    else begin
        call Node024();
    end
end

procedure Node992
begin
    set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -10);
    debug_msg("Player gains " + -10 + " Karma Points.");
    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
    set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
    set_global_var(GVAR_KARMA_DEFENDER, 0);
    set_global_var(GVAR_KARMA_WANDERER, 0);
    set_global_var(GVAR_KARMA_BETRAYER, 0);
    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
    set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
    if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
    end
    else begin
        if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
            set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                    set_global_var(GVAR_KARMA_DEFENDER, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                        set_global_var(GVAR_KARMA_WANDERER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                            set_global_var(GVAR_KARMA_BETRAYER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                    set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                end
                                else begin
                                    set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    call Node022();
end

procedure Node991
begin
    set_global_var(GVAR_SLAUGHTER_SLAG_TIME, -1);
    set_global_var(GVAR_MODOC_GENERIC_FLAG_1, global_var(GVAR_MODOC_GENERIC_FLAG_1) bwor 512);
    debug_msg("HEY: I SET ENEMY SLAGS!!!! I'M SCRIPT #" + 102);
    if (global_var(GVAR_MODOC_GHOST_FARM_SEED) == 0) then begin
        set_global_var(GVAR_MODOC_GHOST_FARM_SEED, 1);
        set_global_var(GVAR_TOWN_REP_MODOC, global_var(GVAR_TOWN_REP_MODOC) + -20);
    end
    if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 4) == 0) then begin
        set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 3);
    end
    else begin
        if ((global_var(GVAR_MODOC_VERMIN_HUNTER_SEED) >= 7) == 0) then begin
            set_global_var(GVAR_MODOC_VERMIN_HUNTER_SEED, 8);
        end
    end
    game_time_advance(24 * (60 * (60 * 10)));
    game_time_advance((24 * (60 * (60 * 10)) * (game_time_hour > 100)) + (((100 / 100) - (game_time_hour / 100)) * (60 * (60 * 10))) + (((100 % 100) - (game_time_hour % 100)) * (60 * 10)));
    set_global_var(GVAR_MODOC_GENERIC_FLAG_2, global_var(GVAR_MODOC_GENERIC_FLAG_2) bwor 2048);
    load_map(24, 0);
end
