variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable Static_Reaction;
variable Evil_Critter;
variable Slavery_Tolerant := 2;
variable Karma_Perception;
variable reaction_bonus_town_rep;
variable reaction_bonus_karma;
variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;
procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node003;
procedure Node003a;
procedure Node003b;
procedure Node002;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node021;
procedure Node021a;
procedure Node022;
procedure Node022a;
procedure Node022b;
procedure Node025;
procedure Node026;
procedure Node015a;
procedure Node015b;
procedure Node018a;
procedure Node007a;
procedure Node013a;
procedure Node027;
procedure Node011a;
procedure Node028;
procedure Node007b;
procedure Node029;
procedure Node030;

variable Only_Once;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
    set_local_var(9, 19277);
end

procedure critter_p_proc
begin
    if ((local_var(5) != 0) and obj_can_see_obj(self_obj, dude_obj)) then begin
        set_local_var(5, 1);
        if (critter_is_fleeing(self_obj)) then begin
            if (anim_busy(self_obj) == 0) then begin
                if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                    if (anim_busy(self_obj) == 0) then begin
                        global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                        animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                        global_temp := (global_temp + 1) % 6;
                        while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                            debug_msg("flee loop: rot == " + global_temp);
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                        end
                    end
                end
            end
        end
        else begin
            attack(dude_obj);
        end
    end
    if ((global_var(GVAR_KILL_TREASURE_HUNTER) == 1) or (global_var(GVAR_KILL_TREASURE_HUNTER) == 2)) then begin
        set_local_var(8, 1);
    end
    if ((global_var(GVAR_SELL_METZGER_MUM) == 1) or (global_var(GVAR_SELL_METZGER_MUM) == 2) or (global_var(GVAR_SELL_METZGER_MUM) == 3)) then begin
        set_local_var(8, 1);
    end
    if ((global_var(GVAR_ESCORT_JIMMY_TO_RENO) == 1) or (global_var(GVAR_ESCORT_JIMMY_TO_RENO) == 2) or (global_var(GVAR_ESCORT_JIMMY_TO_RENO) == 3)) then begin
        set_local_var(8, 1);
    end
    if ((global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK) == 1) or (global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK) == 2)) then begin
        set_local_var(8, 1);
    end
    if (global_var(GVAR_LINK_THETOWNS) == 1) then begin
        animate_move_obj_to_tile(self_obj, 19277, 0);
    end
    if (tile_num(self_obj) == local_var(9)) then begin
        set_global_var(GVAR_LINK_THETOWNS, 2);
        move_to(self_obj, 11665, 0);
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(5, 2);
    end
end

procedure talk_p_proc
begin
    if (global_var(GVAR_LAST_BATTLE_BEGIN) == 1) then begin
        if (local_var(8) == 1) then begin
            start_gdialog(1781, self_obj, 4, -1, -1);
            gsay_start;
            call Node002();
            gsay_end;
            end_dialogue;
        end
        else begin
            start_gdialog(1781, self_obj, 4, -1, -1);
            gsay_start;
            call Node003();
            gsay_end;
            end_dialogue;
        end
    end
    else begin
        if (global_var(GVAR_LAST_BATTLE_BEGIN) == 2) then begin
            if (global_var(GVAR_LINK_THETOWNS) == 1) then begin
                start_gdialog(1781, self_obj, 4, -1, -1);
                gsay_start;
                call Node021();
                gsay_end;
                end_dialogue;
            end
            else begin
                start_gdialog(1781, self_obj, 4, -1, -1);
                gsay_start;
                call Node001();
                gsay_end;
                end_dialogue;
            end
        end
        else begin
            start_gdialog(1781, self_obj, 4, -1, -1);
            gsay_start;
            call Node001();
            gsay_end;
            end_dialogue;
        end
    end
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
        if (critter_kill_type(self_obj) == KILL_TYPE_children_kills) then begin
            if (source_obj == dude_obj) then begin
                set_global_var(GVAR_CHAMPION_REPUTATION, 0);
                set_global_var(GVAR_CHILDKILLER_REPUTATION, global_var(GVAR_CHILDKILLER_REPUTATION) + 1);
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -15);
                debug_msg("Player gains " + -15 + " Karma Points.");
                set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
                set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
                set_global_var(GVAR_KARMA_DEFENDER, 0);
                set_global_var(GVAR_KARMA_WANDERER, 0);
                set_global_var(GVAR_KARMA_BETRAYER, 0);
                set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
                set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
                if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
                    set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                            set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                                set_global_var(GVAR_KARMA_DEFENDER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                                    set_global_var(GVAR_KARMA_WANDERER, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                        set_global_var(GVAR_KARMA_BETRAYER, 1);
                                    end
                                    else begin
                                        if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                            set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                        end
                                        else begin
                                            if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                                set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                            end
                                            else begin
                                                set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
                set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + -8);
                debug_msg("Added " + -8 + " to Town Rep");
            end
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 5);
        debug_msg("Player gains " + 5 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        if (global_var(GVAR_PLAYER_REPUTATION) >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (global_var(GVAR_PLAYER_REPUTATION) >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (global_var(GVAR_PLAYER_REPUTATION) >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (global_var(GVAR_PLAYER_REPUTATION) >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (global_var(GVAR_PLAYER_REPUTATION) > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (global_var(GVAR_PLAYER_REPUTATION) > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (global_var(GVAR_PLAYER_REPUTATION) > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (global_var(GVAR_PLAYER_REPUTATION) > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 2);
        debug_msg("Added " + 2 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
end

procedure description_p_proc
begin
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (obj_in_party(source_obj)) then begin
        set_local_var(6, 1);
    end
end

procedure map_enter_p_proc
begin
    Only_Once := 0;
end

procedure timed_event_p_proc
begin
    if (fixed_param == 1) then begin
        gfade_out(10 * 6);
        game_ui_disable;
        move_to(self_obj, 11665, 0);
        game_ui_enable;
        gfade_in(10 * 6);
    end
    else begin
        if (fixed_param == 2) then begin
            gfade_out(10 * 6);
            game_ui_disable;
            move_to(self_obj, 11665, 0);
            load_map(154, -1);
            game_ui_enable;
            gfade_in(10 * 6);
        end
    end
end

procedure Node998
begin
    set_local_var(5, 2);
end

procedure Node999
begin
    debug_msg("LVAR_Herebefore == " + local_var(4));
    if (local_var(4) == 0) then begin
        set_local_var(4, 1);
    end
end

procedure Node001
begin
    gsay_reply(SCRIPT_RAFAEL, 200);
    giq_option(4, SCRIPT_RAFAEL, 201, Node999, NEUTRAL_REACTION);
end

procedure Node003
begin
    if (global_var(GVAR_ENTER_ELDRIDGE_BASEMENT) == 6) then begin
        call Node003b();
    end
    else begin
        call Node003a();
    end
end

procedure Node003a
begin
    gsay_reply(SCRIPT_RAFAEL, message_str(SCRIPT_RAFAEL, 209) + dude_name + message_str(SCRIPT_RAFAEL, 210));
    giq_option(4, SCRIPT_RAFAEL, 211, Node004, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_RAFAEL, 212, Node005, NEUTRAL_REACTION);
end

procedure Node003b
begin
    gsay_reply(SCRIPT_RAFAEL, 410);
    giq_option(4, SCRIPT_RAFAEL, 411, Node005, NEUTRAL_REACTION);
end

procedure Node002
begin
    gsay_reply(SCRIPT_RAFAEL, message_str(SCRIPT_RAFAEL, 209) + dude_name + message_str(SCRIPT_RAFAEL, 220));
    if (global_var(GVAR_KILL_TREASURE_HUNTER) == 2) then begin
        giq_option(4, SCRIPT_RAFAEL, 221, Node011, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_SELL_METZGER_MUM) == 3) then begin
        giq_option(4, SCRIPT_RAFAEL, 222, Node015, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ESCORT_JIMMY_TO_RENO) == 3) then begin
        giq_option(4, SCRIPT_RAFAEL, 223, Node016, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ESCORT_JIMMY_TO_RENO) == 2) then begin
        giq_option(4, SCRIPT_RAFAEL, 224, Node018, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK) == 3) then begin
        giq_option(4, SCRIPT_RAFAEL, 225, Node019, NEUTRAL_REACTION);
    end
    if (global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK) == 4) then begin
        giq_option(4, SCRIPT_RAFAEL, 409, Node029, NEUTRAL_REACTION);
    end
    giq_option(4, SCRIPT_RAFAEL, 401, Node999, NEUTRAL_REACTION);
end

procedure Node004
begin
    gsay_reply(SCRIPT_RAFAEL, 230);
    giq_option(4, SCRIPT_RAFAEL, 231, Node005, NEUTRAL_REACTION);
end

procedure Node005
begin
    gsay_reply(SCRIPT_RAFAEL, 240);
    giq_option(4, SCRIPT_RAFAEL, 241, Node006, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_RAFAEL, 242, Node007, NEUTRAL_REACTION);
end

procedure Node006
begin
    gsay_reply(SCRIPT_RAFAEL, 250);
    giq_option(4, SCRIPT_RAFAEL, 251, Node007, NEUTRAL_REACTION);
end

procedure Node007
begin
    gsay_reply(SCRIPT_RAFAEL, 260);
    if (not((global_var(GVAR_DEN_FLAG_1) bwand 4) != 0)) then begin
        giq_option(4, SCRIPT_RAFAEL, 261, Node008, NEUTRAL_REACTION);
    end
    if (not((global_var(GVAR_DEN_FLAG_1) bwand 4) != 0)) then begin
        giq_option(4, SCRIPT_RAFAEL, 262, Node007a, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_DEN_FLAG_1) bwand 4) != 0) then begin
        giq_option(4, SCRIPT_RAFAEL, 407, Node007b, NEUTRAL_REACTION);
    end
end

procedure Node008
begin
    gsay_reply(SCRIPT_RAFAEL, 270);
    giq_option(4, SCRIPT_RAFAEL, 271, Node009, NEUTRAL_REACTION);
end

procedure Node009
begin
    gsay_reply(SCRIPT_RAFAEL, 280);
    giq_option(4, SCRIPT_RAFAEL, 281, Node999, NEUTRAL_REACTION);
    restock_obj := create_object(569, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
end

procedure Node011
begin
    if (obj_is_carrying_obj_pid(dude_obj, 568) == 1) then begin
        call Node027();
    end
    else begin
        call Node011a();
    end
end

procedure Node012
begin
    gsay_reply(SCRIPT_RAFAEL, 300);
    giq_option(4, SCRIPT_RAFAEL, 301, Node013, NEUTRAL_REACTION);
end

procedure Node013
begin
    gsay_reply(SCRIPT_RAFAEL, 310);
    giq_option(4, SCRIPT_RAFAEL, 311, Node013a, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_RAFAEL, 312, Node008, NEUTRAL_REACTION);
end

procedure Node015
begin
    if (obj_is_carrying_obj_pid(dude_obj, 568) == 1) then begin
        call Node027();
    end
    else begin
        call Node015b();
    end
end

procedure Node016
begin
    gsay_reply(SCRIPT_RAFAEL, 330);
    giq_option(4, SCRIPT_RAFAEL, 331, Node017, NEUTRAL_REACTION);
end

procedure Node017
begin
    gsay_reply(SCRIPT_RAFAEL, message_str(SCRIPT_RAFAEL, 340) + dude_name + message_str(SCRIPT_RAFAEL, 341));
    giq_option(4, SCRIPT_RAFAEL, 342, Node009, NEUTRAL_REACTION);
end

procedure Node018
begin
    gsay_reply(SCRIPT_RAFAEL, 350);
    if (not((global_var(GVAR_DEN_FLAG_1) bwand 1) != 0)) then begin
        giq_option(4, SCRIPT_RAFAEL, 351, Node008, NEUTRAL_REACTION);
    end
    if (not((global_var(GVAR_DEN_FLAG_1) bwand 1) != 0)) then begin
        giq_option(4, SCRIPT_RAFAEL, 352, Node018a, NEUTRAL_REACTION);
    end
    if ((global_var(GVAR_DEN_FLAG_1) bwand 1) != 0) then begin
        giq_option(4, SCRIPT_RAFAEL, 404, Node028, NEUTRAL_REACTION);
    end
    set_global_var(GVAR_ESCORT_JIMMY_TO_RENO, 4);
    give_exp_points(200);
    display_msg(g_mstr(100) + 200 + g_mstr(101));
end

procedure Node019
begin
    gsay_message(SCRIPT_RAFAEL, 360, NEUTRAL_REACTION);
    set_local_var(4, 1);
    set_global_var(GVAR_LAST_BATTLE_BEGIN, 2);
    give_exp_points(200);
    display_msg(g_mstr(100) + 200 + g_mstr(101));
    set_global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK, 6);
end

procedure Node021
begin
    if ((global_var(GVAR_NEW_RENO_SALVATORE) bwand 512) != 0) then begin
        call Node030();
    end
    else begin
        if (((global_var(GVAR_DEN_FLAG_1) bwand 1) != 0) and not((global_var(GVAR_NEW_RENO_SALVATORE) bwand 512) != 0)) then begin
            float_msg(self_obj, 103, FLOAT_MSG_RED);
        end
        else begin
            call Node021a();
        end
    end
end

procedure Node021a
begin
    gsay_reply(SCRIPT_RAFAEL, 370);
    giq_option(4, SCRIPT_RAFAEL, 371, Node022, NEUTRAL_REACTION);
end

procedure Node022
begin
    gsay_reply(SCRIPT_RAFAEL, 380);
    giq_option(4, SCRIPT_RAFAEL, 381, Node022b, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_RAFAEL, 382, Node022a, NEUTRAL_REACTION);
end

procedure Node022a
begin
    set_global_var(GVAR_LINK_THETOWNS, 2);
    add_timer_event(self_obj, 10, 1);
end

procedure Node022b
begin
    set_global_var(GVAR_LINK_THETOWNS, 3);
    add_timer_event(self_obj, 10, 2);
end

procedure Node025
begin
    gsay_message(SCRIPT_RAFAEL, 390, NEUTRAL_REACTION);
    set_local_var(4, 1);
end

procedure Node026
begin
    gsay_message(SCRIPT_RAFAEL, 400, NEUTRAL_REACTION);
    set_local_var(4, 1);
end

procedure Node015a
begin
    set_global_var(GVAR_SELL_METZGER_MUM, 4);
    if (global_var(GVAR_ESCORT_JIMMY_TO_RENO) != 2) then begin
        set_global_var(GVAR_ESCORT_JIMMY_TO_RENO, 1);
    end
    restock_obj := create_object(280, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    restock_obj := create_object(25, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    restock_obj := create_object(51, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    give_exp_points(100);
    display_msg(g_mstr(100) + 100 + g_mstr(101));
end

procedure Node015b
begin
    gsay_reply(SCRIPT_RAFAEL, 320);
    giq_option(4, SCRIPT_RAFAEL, 321, Node015a, NEUTRAL_REACTION);
    restock_obj := create_object(51, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
end

procedure Node018a
begin
    set_global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK, 1);
    if (town_known(10) == MARK_STATE_UNKNOWN) then begin
        debug_msg("  mark_on_map(" + 10 + ")");
        mark_area_known(MARK_TYPE_TOWN, 10, MARK_STATE_KNOWN);
    end
end

procedure Node007a
begin
    set_global_var(GVAR_KILL_TREASURE_HUNTER, 1);
    restock_obj := create_object(567, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    restock_obj := create_object(568, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
end

procedure Node013a
begin
    set_global_var(GVAR_SELL_METZGER_MUM, 1);
    restock_obj := create_object(570, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
    restock_obj := create_object(568, 0, 0);
    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
end

procedure Node027
begin
    gsay_reply(SCRIPT_RAFAEL, 402);
    giq_option(4, SCRIPT_RAFAEL, 403, Node009, NEUTRAL_REACTION);
end

procedure Node011a
begin
    gsay_reply(SCRIPT_RAFAEL, 290);
    giq_option(4, SCRIPT_RAFAEL, 291, Node012, NEUTRAL_REACTION);
    set_global_var(GVAR_KILL_TREASURE_HUNTER, 3);
    give_exp_points(100);
    display_msg(g_mstr(100) + 100 + g_mstr(101));
end

procedure Node028
begin
    gsay_reply(SCRIPT_RAFAEL, 405);
    giq_option(4, SCRIPT_RAFAEL, 406, Node999, NEUTRAL_REACTION);
    set_local_var(8, 0);
end

procedure Node007b
begin
    gsay_reply(SCRIPT_RAFAEL, 408);
    giq_option(4, SCRIPT_RAFAEL, 261, Node008, NEUTRAL_REACTION);
    giq_option(4, SCRIPT_RAFAEL, 262, Node007a, NEUTRAL_REACTION);
end

procedure Node029
begin
    set_local_var(8, 0);
    gsay_reply(SCRIPT_RAFAEL, 405);
    giq_option(4, SCRIPT_RAFAEL, 406, Node999, NEUTRAL_REACTION);
    set_global_var(GVAR_LAST_BATTLE_BEGIN, 2);
    set_global_var(GVAR_ALLOWED_TO_SPEAK_TO_JACK, 6);
end

procedure Node030
begin
    gsay_reply(SCRIPT_RAFAEL, 413);
    giq_option(4, SCRIPT_RAFAEL, 406, Node999, NEUTRAL_REACTION);
    add_timer_event(self_obj, 10, 1);
    set_global_var(GVAR_LINK_THETOWNS, 14);
end
