variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;
variable last_timed_obj;
variable last_timed_param;
variable check_still_kill;
variable stored_msg;
variable stored_node;
variable top_msg;
variable var_num;

procedure ChooseFromList;
procedure CLICK_PREV;
procedure CLICK_0;
procedure CLICK_1;
procedure CLICK_2;
procedure CLICK_3;
procedure CLICK_4;
procedure CLICK_MORE;

variable floater_patch_msg;
variable hs_temp;

procedure start;
procedure critter_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure combat_p_proc;
procedure pickup_p_proc;
procedure timed_event_p_proc;
procedure Node998;
procedure Node999;

import variable announcer_obj;
import variable ring_girl_obj;
import variable prize_fighter_obj;

variable the_roll;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure ChooseFromList
begin
    variable LVar0 := 0;
    Reply(stored_msg);
    if (message_str(SCRIPT_NEWR1, top_msg - 1) != "") then begin
        giq_option(1, NAME, message_str(SCRIPT_NEWR1, 150), CLICK_PREV, NEUTRAL_REACTION);
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 0) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, top_msg + 0), CLICK_0, NEUTRAL_REACTION);
        end
        else begin
            LVar0 := 1;
        end
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 1) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, top_msg + 1), CLICK_1, NEUTRAL_REACTION);
        end
        else begin
            LVar0 := 1;
        end
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 2) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, top_msg + 2), CLICK_2, NEUTRAL_REACTION);
        end
        else begin
            LVar0 := 1;
        end
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 3) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, top_msg + 3), CLICK_3, NEUTRAL_REACTION);
        end
        else begin
            LVar0 := 1;
        end
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 4) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, top_msg + 4), CLICK_4, NEUTRAL_REACTION);
        end
        else begin
            LVar0 := 1;
        end
    end
    if (LVar0 == 0) then begin
        if (message_str(SCRIPT_NEWR1, top_msg + 5) != "") then begin
            giq_option(1, NAME, message_str(SCRIPT_NEWR1, 151), CLICK_MORE, NEUTRAL_REACTION);
        end
    end
end

procedure CLICK_PREV
begin
    top_msg := top_msg - 5;
    call ChooseFromList();
end

procedure CLICK_0
begin
    set_global_var(var_num, (global_var(var_num) / 100 * 100) + (top_msg % 100));
    call stored_node();
end

procedure CLICK_1
begin
    set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 1) % 100));
    call stored_node();
end

procedure CLICK_2
begin
    set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 2) % 100));
    call stored_node();
end

procedure CLICK_3
begin
    set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 3) % 100));
    call stored_node();
end

procedure CLICK_4
begin
    set_global_var(var_num, (global_var(var_num) / 100 * 100) + ((top_msg + 4) % 100));
    call stored_node();
end

procedure CLICK_MORE
begin
    top_msg := top_msg + 5;
    call ChooseFromList();
end

procedure start
begin
    if (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0) then begin
        prize_fighter_obj := self_obj;
    end
end

procedure critter_p_proc
begin
    if (global_var(GVAR_NEW_RENO_ROUND_TIME) != 0) then begin
        debug_msg("prizefighter critter_p_proc");
        if (critter_is_fleeing(self_obj)) then begin
            if (2 != 0) then begin
                if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 2);
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 200);
                    add_timer_event(announcer_obj, game_ticks(5), 200);
                end
            end
            else begin
                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
            end
            debug_msg("set_fight_status(" + 2 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
            debug_msg("call fight over: start");
            gfade_out(10);
            set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            move_to(dude_obj, 25076, elevation(self_obj));
            anim(dude_obj, 1000, 3);
            if (prize_fighter_obj != 0) then begin
                if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                    if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                        set_obj_visibility(prize_fighter_obj, 1);
                    end
                    prize_fighter_obj := 0;
                end
                else begin
                    animate_stand_obj(prize_fighter_obj);
                    critter_injure(prize_fighter_obj, 2 bwor 8388608);
                    move_to(prize_fighter_obj, 25674, elevation(self_obj));
                    anim(prize_fighter_obj, 1000, 3);
                end
            end
            if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                set_obj_visibility(ring_girl_obj, 1);
            end
            if (obj_is_visible_flag(announcer_obj) == 0) then begin
                set_obj_visibility(announcer_obj, 0);
            end
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            gfade_in(10);
            debug_msg("call fight over: end");
            debug_msg("win boxing match: " + self_name);
        end
        else begin
            if (critter_state(self_obj) bwand 2) then begin
                if (1 != 0) then begin
                    if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 1);
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 200);
                        add_timer_event(announcer_obj, game_ticks(5), 200);
                    end
                end
                else begin
                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                end
                debug_msg("set_fight_status(" + 1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                debug_msg("call fight over: start");
                gfade_out(10);
                set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                if (CUR_MAP_NEWR2) then begin
                    if (announcer_obj != 0) then begin
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 48);
                        add_timer_event(announcer_obj, game_ticks(0), 48);
                    end
                end
                set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                move_to(dude_obj, 25076, elevation(self_obj));
                anim(dude_obj, 1000, 3);
                if (prize_fighter_obj != 0) then begin
                    if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                        if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                            set_obj_visibility(prize_fighter_obj, 1);
                        end
                        prize_fighter_obj := 0;
                    end
                    else begin
                        animate_stand_obj(prize_fighter_obj);
                        critter_injure(prize_fighter_obj, 2 bwor 8388608);
                        move_to(prize_fighter_obj, 25674, elevation(self_obj));
                        anim(prize_fighter_obj, 1000, 3);
                    end
                end
                if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                    set_obj_visibility(ring_girl_obj, 1);
                end
                if (obj_is_visible_flag(announcer_obj) == 0) then begin
                    set_obj_visibility(announcer_obj, 0);
                end
                if (CUR_MAP_NEWR2) then begin
                    if (announcer_obj != 0) then begin
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 48);
                        add_timer_event(announcer_obj, game_ticks(0), 48);
                    end
                end
                set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                gfade_in(10);
                debug_msg("call fight over: end");
                debug_msg("win boxing match: " + self_name);
            end
            else begin
                if (critter_state(dude_obj) bwand 2) then begin
                    if (-1 != 0) then begin
                        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -1);
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 200);
                            add_timer_event(announcer_obj, game_ticks(5), 200);
                        end
                    end
                    else begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                    end
                    debug_msg("set_fight_status(" + -1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                    debug_msg("call fight over: start");
                    gfade_out(10);
                    set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    move_to(dude_obj, 25076, elevation(self_obj));
                    anim(dude_obj, 1000, 3);
                    if (prize_fighter_obj != 0) then begin
                        if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                            if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                set_obj_visibility(prize_fighter_obj, 1);
                            end
                            prize_fighter_obj := 0;
                        end
                        else begin
                            animate_stand_obj(prize_fighter_obj);
                            critter_injure(prize_fighter_obj, 2 bwor 8388608);
                            move_to(prize_fighter_obj, 25674, elevation(self_obj));
                            anim(prize_fighter_obj, 1000, 3);
                        end
                    end
                    if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                        set_obj_visibility(ring_girl_obj, 1);
                    end
                    if (obj_is_visible_flag(announcer_obj) == 0) then begin
                        set_obj_visibility(announcer_obj, 0);
                    end
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    gfade_in(10);
                    debug_msg("call fight over: end");
                    debug_msg("lose boxing match: " + self_name);
                end
                else begin
                    attack(dude_obj);
                end
            end
        end
    end
end

procedure destroy_p_proc
begin
    debug_msg("prizefighter destroy_p_proc");
    if (obj_pid(self_obj) == 16777649) then begin
        set_global_var(GVAR_NEW_RENO_FLAG_3, global_var(GVAR_NEW_RENO_FLAG_3) bwor 512);
    end
    else begin
        if (obj_pid(self_obj) == 16777648) then begin
            set_global_var(GVAR_NEW_RENO_FLAG_3, global_var(GVAR_NEW_RENO_FLAG_3) bwor 1024);
        end
        else begin
            if (obj_pid(self_obj) == 16777647) then begin
                set_global_var(GVAR_NEW_RENO_FLAG_3, global_var(GVAR_NEW_RENO_FLAG_3) bwor 2048);
            end
        end
    end
    set_global_var(GVAR_NEW_RENO_FLAG_3, global_var(GVAR_NEW_RENO_FLAG_3) bwor 8192);
    if (1 != 0) then begin
        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 1);
            last_timed_obj := announcer_obj;
            last_timed_param := last_timed_param;
            rm_fixed_timer_event(announcer_obj, 200);
            add_timer_event(announcer_obj, game_ticks(5), 200);
        end
    end
    else begin
        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
    end
    debug_msg("set_fight_status(" + 1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
    debug_msg("call fight over: start");
    gfade_out(10);
    set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
    if (CUR_MAP_NEWR2) then begin
        if (announcer_obj != 0) then begin
            last_timed_obj := announcer_obj;
            last_timed_param := last_timed_param;
            rm_fixed_timer_event(announcer_obj, 48);
            add_timer_event(announcer_obj, game_ticks(0), 48);
        end
    end
    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
    move_to(dude_obj, 25076, elevation(self_obj));
    anim(dude_obj, 1000, 3);
    if (prize_fighter_obj != 0) then begin
        if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
            if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                set_obj_visibility(prize_fighter_obj, 1);
            end
            prize_fighter_obj := 0;
        end
        else begin
            animate_stand_obj(prize_fighter_obj);
            critter_injure(prize_fighter_obj, 2 bwor 8388608);
            move_to(prize_fighter_obj, 25674, elevation(self_obj));
            anim(prize_fighter_obj, 1000, 3);
        end
    end
    if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
        set_obj_visibility(ring_girl_obj, 1);
    end
    if (obj_is_visible_flag(announcer_obj) == 0) then begin
        set_obj_visibility(announcer_obj, 0);
    end
    if (CUR_MAP_NEWR2) then begin
        if (announcer_obj != 0) then begin
            last_timed_obj := announcer_obj;
            last_timed_param := last_timed_param;
            rm_fixed_timer_event(announcer_obj, 48);
            add_timer_event(announcer_obj, game_ticks(0), 48);
        end
    end
    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
    gfade_in(10);
    debug_msg("call fight over: end");
    debug_msg("win boxing match: " + self_name);
    removed_qty := obj_is_carrying_obj_pid(self_obj, 489);
    if (1 < removed_qty) then begin
        removed_qty := 1;
    end
    if (removed_qty > 0) then begin
        restock_obj := obj_carrying_pid_obj(self_obj, 489);
        if (obj_type(self_obj) == 1) then begin
            restock_obj := obj_carrying_pid_obj(self_obj, 489);
            if (critter_inven_obj(self_obj, 0) == restock_obj) then begin
                if (obj_item_subtype(critter_inven_obj(self_obj, 0)) == 0) then begin
                    restock_obj := critter_inven_obj(self_obj, 0);
                    debug_msg("armour pid == " + obj_pid(restock_obj));
                    rm_obj_from_inven(self_obj, restock_obj);
                    add_obj_to_inven(self_obj, restock_obj);
                end
            end
            else begin
                if ((critter_inven_obj(self_obj, 2) == restock_obj) or (critter_inven_obj(self_obj, 1) == restock_obj)) then begin
                    inven_unwield(self_obj);
                end
            end
        end
        restock_amt := rm_mult_objs_from_inven(self_obj, restock_obj, removed_qty);
        destroy_object(restock_obj);
    end
    restock_obj := 0;
    restock_amt := 0;
end

procedure look_at_p_proc
begin
    script_overrides;
    display_msg(mstr(100) + message_str(SCRIPT_NEWR1, 700 + (50 * ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 4096) != 0)) + global_var(GVAR_NEW_RENO_FIGHT_LEVEL)) + mstr(101));
end

procedure description_p_proc
begin
    script_overrides;
    display_mstr(random(150, 152));
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(1, local_var(1) + 1);
        debug_msg("total punches dude thrown == " + local_var(1));
        if (target_obj != 0) then begin
            if ((obj_pid(target_obj) != 497) and (obj_pid(target_obj) != 496)) then begin
                if (-3 != 0) then begin
                    if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -3);
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 200);
                        add_timer_event(announcer_obj, game_ticks(5), 200);
                    end
                end
                else begin
                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                end
                debug_msg("set_fight_status(" + -3 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                debug_msg("call fight over: start");
                gfade_out(10);
                set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                if (CUR_MAP_NEWR2) then begin
                    if (announcer_obj != 0) then begin
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 48);
                        add_timer_event(announcer_obj, game_ticks(0), 48);
                    end
                end
                set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                move_to(dude_obj, 25076, elevation(self_obj));
                anim(dude_obj, 1000, 3);
                if (prize_fighter_obj != 0) then begin
                    if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                        if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                            set_obj_visibility(prize_fighter_obj, 1);
                        end
                        prize_fighter_obj := 0;
                    end
                    else begin
                        animate_stand_obj(prize_fighter_obj);
                        critter_injure(prize_fighter_obj, 2 bwor 8388608);
                        move_to(prize_fighter_obj, 25674, elevation(self_obj));
                        anim(prize_fighter_obj, 1000, 3);
                    end
                end
                if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                    set_obj_visibility(ring_girl_obj, 1);
                end
                if (obj_is_visible_flag(announcer_obj) == 0) then begin
                    set_obj_visibility(announcer_obj, 0);
                end
                if (CUR_MAP_NEWR2) then begin
                    if (announcer_obj != 0) then begin
                        last_timed_obj := announcer_obj;
                        last_timed_param := last_timed_param;
                        rm_fixed_timer_event(announcer_obj, 48);
                        add_timer_event(announcer_obj, game_ticks(0), 48);
                    end
                end
                set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                gfade_in(10);
                debug_msg("call fight over: end");
                debug_msg("lose boxing match: " + self_name);
            end
            else begin
                if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand --2147483648) != 0) then begin
                    if (obj_pid(self_obj) == 16777647) then begin
                        the_roll := roll_vs_skill(dude_obj, 3, -get_critter_stat(self_obj, STAT_max_hp));
                        if (is_success(the_roll)) then begin
                            if (is_critical(the_roll)) then begin
                                if (((global_var(GVAR_EMILY_SUBST_TIME) bwand 1) != 0) == 0) then begin
                                    display_msg(message_str(SCRIPT_NEWR1, 1700));
                                    restock_obj := create_object(485, 0, 0);
                                    add_mult_objs_to_inven(dude_obj, restock_obj, 1);
                                end
                                set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 1);
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure map_enter_p_proc
begin
    if (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0) then begin
        prize_fighter_obj := self_obj;
    end
end

procedure map_update_p_proc
begin
    if (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0) then begin
        prize_fighter_obj := self_obj;
    end
end

procedure combat_p_proc
begin
    debug_msg("seconds til round is over == " + ((global_var(GVAR_NEW_RENO_ROUND_TIME) - game_time) / 10));
    debug_msg("   critter_state(self_obj) == " + critter_state(self_obj));
    debug_msg("   critter_state(dude_obj) == " + critter_state(dude_obj));
    if ((((global_var(GVAR_NEW_RENO_ROUND_TIME) - game_time) / 10) <= 0) and (global_var(GVAR_NEW_RENO_ROUND_TIME) != 0)) then begin
        play_sfx("boxbel2");
        terminate_combat;
        gfade_out(10);
        if (obj_is_visible_flag(announcer_obj) == 1) then begin
            set_obj_visibility(announcer_obj, 1);
        end
        if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
            set_obj_visibility(ring_girl_obj, 1);
        end
        debug_msg("end boxing round start");
        if (CUR_MAP_NEWR2) then begin
            if (announcer_obj != 0) then begin
                last_timed_obj := announcer_obj;
                last_timed_param := last_timed_param;
                rm_fixed_timer_event(announcer_obj, 48);
                add_timer_event(announcer_obj, game_ticks(0), 48);
            end
        end
        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
        debug_msg("combat terminated");
        set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
        set_global_var(GVAR_NEW_RENO_ROUND_NUMBER, global_var(GVAR_NEW_RENO_ROUND_NUMBER) + 1);
        animate_stand_obj(dude_obj);
        if ((prize_fighter_obj != 0) and (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0)) then begin
            animate_stand_obj(prize_fighter_obj);
        end
        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
            debug_msg("check_fight_status(fight_status_fighting)");
            debug_msg("move_boxers_to_corners: start");
            move_to(dude_obj, 24479, elevation(self_obj));
            critter_injure(dude_obj, 2 bwor 8388608);
            if ((prize_fighter_obj != 0) and (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0)) then begin
                move_to(prize_fighter_obj, 26471, elevation(self_obj));
                animate_stand_obj(prize_fighter_obj);
                critter_injure(prize_fighter_obj, 2 bwor 8388608);
                anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(prize_fighter_obj)));
                anim(prize_fighter_obj, 1000, rotation_to_tile(tile_num(prize_fighter_obj), dude_tile));
            end
            animate_stand_obj(dude_obj);
            debug_msg("move_boxers_to_corners: end");
            set_global_var(GVAR_NEW_RENO_DUDE_SCORE, global_var(GVAR_NEW_RENO_DUDE_SCORE) + 9);
            set_global_var(GVAR_NEW_RENO_BOXER_SCORE, global_var(GVAR_NEW_RENO_BOXER_SCORE) + 9);
            if ((local_var(1) > local_var(2)) or ((local_var(1) == local_var(2)) and random(0, 1))) then begin
                set_global_var(GVAR_NEW_RENO_DUDE_SCORE, global_var(GVAR_NEW_RENO_DUDE_SCORE) + 1);
            end
            else begin
                set_global_var(GVAR_NEW_RENO_BOXER_SCORE, global_var(GVAR_NEW_RENO_BOXER_SCORE) + 1);
            end
            if (global_var(GVAR_NEW_RENO_ROUND_NUMBER) <= 12) then begin
                critter_heal(dude_obj, dude_endurance);
                critter_heal(prize_fighter_obj, get_critter_stat(prize_fighter_obj, STAT_en));
                set_local_var(1, 0);
                set_local_var(2, 0);
                if (obj_is_visible_flag(ring_girl_obj) == 0) then begin
                    set_obj_visibility(ring_girl_obj, 0);
                end
                last_timed_obj := announcer_obj;
                last_timed_param := last_timed_param;
                rm_fixed_timer_event(announcer_obj, 110);
                add_timer_event(announcer_obj, game_ticks(5), 110);
            end
            else begin
                if (global_var(GVAR_NEW_RENO_BOXER_SCORE) > global_var(GVAR_NEW_RENO_DUDE_SCORE)) then begin
                    if (-4 != 0) then begin
                        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -4);
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 200);
                            add_timer_event(announcer_obj, game_ticks(5), 200);
                        end
                    end
                    else begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                    end
                    debug_msg("set_fight_status(" + -4 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                    debug_msg("call fight over: start");
                    gfade_out(10);
                    set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    move_to(dude_obj, 25076, elevation(self_obj));
                    anim(dude_obj, 1000, 3);
                    if (prize_fighter_obj != 0) then begin
                        if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                            if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                set_obj_visibility(prize_fighter_obj, 1);
                            end
                            prize_fighter_obj := 0;
                        end
                        else begin
                            animate_stand_obj(prize_fighter_obj);
                            critter_injure(prize_fighter_obj, 2 bwor 8388608);
                            move_to(prize_fighter_obj, 25674, elevation(self_obj));
                            anim(prize_fighter_obj, 1000, 3);
                        end
                    end
                    if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                        set_obj_visibility(ring_girl_obj, 1);
                    end
                    if (obj_is_visible_flag(announcer_obj) == 0) then begin
                        set_obj_visibility(announcer_obj, 0);
                    end
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    gfade_in(10);
                    debug_msg("call fight over: end");
                    debug_msg("lose boxing match: " + self_name);
                end
                else begin
                    if (4 != 0) then begin
                        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 4);
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 200);
                            add_timer_event(announcer_obj, game_ticks(5), 200);
                        end
                    end
                    else begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                    end
                    debug_msg("set_fight_status(" + 4 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                    debug_msg("call fight over: start");
                    gfade_out(10);
                    set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    move_to(dude_obj, 25076, elevation(self_obj));
                    anim(dude_obj, 1000, 3);
                    if (prize_fighter_obj != 0) then begin
                        if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                            if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                set_obj_visibility(prize_fighter_obj, 1);
                            end
                            prize_fighter_obj := 0;
                        end
                        else begin
                            animate_stand_obj(prize_fighter_obj);
                            critter_injure(prize_fighter_obj, 2 bwor 8388608);
                            move_to(prize_fighter_obj, 25674, elevation(self_obj));
                            anim(prize_fighter_obj, 1000, 3);
                        end
                    end
                    if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                        set_obj_visibility(ring_girl_obj, 1);
                    end
                    if (obj_is_visible_flag(announcer_obj) == 0) then begin
                        set_obj_visibility(announcer_obj, 0);
                    end
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    gfade_in(10);
                    debug_msg("call fight over: end");
                    debug_msg("win boxing match: " + self_name);
                end
            end
        end
        if (CUR_MAP_NEWR2) then begin
            if (announcer_obj != 0) then begin
                last_timed_obj := announcer_obj;
                last_timed_param := last_timed_param;
                rm_fixed_timer_event(announcer_obj, 48);
                add_timer_event(announcer_obj, game_ticks(0), 48);
            end
        end
        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
        gfade_in(10);
        debug_msg("end boxing round end");
    end
    if (global_var(GVAR_NEW_RENO_ROUND_TIME) != 0) then begin
        if (fixed_param == 2) then begin
            set_local_var(2, local_var(2) + 1);
            debug_msg("total punches boxer thrown == " + local_var(2));
            if (obj_pid(self_obj) == 16777647) then begin
                the_roll := roll_vs_skill(self_obj, 3, -get_critter_stat(dude_obj, STAT_max_hp));
                if (is_success(the_roll)) then begin
                    if (is_critical(the_roll)) then begin
                        if (((global_var(GVAR_NEW_RENO_FLAG_3) bwand --2147483648) != 0) == 0) then begin
                            set_critter_stat(dude_obj, STAT_ch, -1);
                            display_msg(message_str(SCRIPT_NEWR1, 1600));
                            restock_obj := create_object(484, 0, 0);
                            add_mult_objs_to_inven(dude_obj, restock_obj, 1);
                        end
                        set_global_var(GVAR_NEW_RENO_FLAG_3, global_var(GVAR_NEW_RENO_FLAG_3) bwor --2147483648);
                    end
                end
            end
        end
        else begin
            if (fixed_param == 4) then begin
                debug_msg("boxer: COMBAT_SUBTYPE_TURN");
                if (critter_is_fleeing(self_obj)) then begin
                    if (2 != 0) then begin
                        if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 2);
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 200);
                            add_timer_event(announcer_obj, game_ticks(5), 200);
                        end
                    end
                    else begin
                        set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                    end
                    debug_msg("set_fight_status(" + 2 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                    debug_msg("call fight over: start");
                    gfade_out(10);
                    set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    move_to(dude_obj, 25076, elevation(self_obj));
                    anim(dude_obj, 1000, 3);
                    if (prize_fighter_obj != 0) then begin
                        if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                            if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                set_obj_visibility(prize_fighter_obj, 1);
                            end
                            prize_fighter_obj := 0;
                        end
                        else begin
                            animate_stand_obj(prize_fighter_obj);
                            critter_injure(prize_fighter_obj, 2 bwor 8388608);
                            move_to(prize_fighter_obj, 25674, elevation(self_obj));
                            anim(prize_fighter_obj, 1000, 3);
                        end
                    end
                    if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                        set_obj_visibility(ring_girl_obj, 1);
                    end
                    if (obj_is_visible_flag(announcer_obj) == 0) then begin
                        set_obj_visibility(announcer_obj, 0);
                    end
                    if (CUR_MAP_NEWR2) then begin
                        if (announcer_obj != 0) then begin
                            last_timed_obj := announcer_obj;
                            last_timed_param := last_timed_param;
                            rm_fixed_timer_event(announcer_obj, 48);
                            add_timer_event(announcer_obj, game_ticks(0), 48);
                        end
                    end
                    set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                    gfade_in(10);
                    debug_msg("call fight over: end");
                    debug_msg("win boxing match: " + self_name);
                end
                else begin
                    if (critter_state(self_obj) bwand 2) then begin
                        if (1 != 0) then begin
                            if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 1);
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 200);
                                add_timer_event(announcer_obj, game_ticks(5), 200);
                            end
                        end
                        else begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                        end
                        debug_msg("set_fight_status(" + 1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                        debug_msg("call fight over: start");
                        gfade_out(10);
                        set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        move_to(dude_obj, 25076, elevation(self_obj));
                        anim(dude_obj, 1000, 3);
                        if (prize_fighter_obj != 0) then begin
                            if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                                if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                    set_obj_visibility(prize_fighter_obj, 1);
                                end
                                prize_fighter_obj := 0;
                            end
                            else begin
                                animate_stand_obj(prize_fighter_obj);
                                critter_injure(prize_fighter_obj, 2 bwor 8388608);
                                move_to(prize_fighter_obj, 25674, elevation(self_obj));
                                anim(prize_fighter_obj, 1000, 3);
                            end
                        end
                        if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                            set_obj_visibility(ring_girl_obj, 1);
                        end
                        if (obj_is_visible_flag(announcer_obj) == 0) then begin
                            set_obj_visibility(announcer_obj, 0);
                        end
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        gfade_in(10);
                        debug_msg("call fight over: end");
                        debug_msg("win boxing match: " + self_name);
                    end
                    else begin
                        if (critter_state(dude_obj) bwand 2) then begin
                            if (-1 != 0) then begin
                                if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -1);
                                    last_timed_obj := announcer_obj;
                                    last_timed_param := last_timed_param;
                                    rm_fixed_timer_event(announcer_obj, 200);
                                    add_timer_event(announcer_obj, game_ticks(5), 200);
                                end
                            end
                            else begin
                                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                            end
                            debug_msg("set_fight_status(" + -1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                            debug_msg("call fight over: start");
                            gfade_out(10);
                            set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                            if (CUR_MAP_NEWR2) then begin
                                if (announcer_obj != 0) then begin
                                    last_timed_obj := announcer_obj;
                                    last_timed_param := last_timed_param;
                                    rm_fixed_timer_event(announcer_obj, 48);
                                    add_timer_event(announcer_obj, game_ticks(0), 48);
                                end
                            end
                            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                            move_to(dude_obj, 25076, elevation(self_obj));
                            anim(dude_obj, 1000, 3);
                            if (prize_fighter_obj != 0) then begin
                                if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                                    if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                        set_obj_visibility(prize_fighter_obj, 1);
                                    end
                                    prize_fighter_obj := 0;
                                end
                                else begin
                                    animate_stand_obj(prize_fighter_obj);
                                    critter_injure(prize_fighter_obj, 2 bwor 8388608);
                                    move_to(prize_fighter_obj, 25674, elevation(self_obj));
                                    anim(prize_fighter_obj, 1000, 3);
                                end
                            end
                            if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                                set_obj_visibility(ring_girl_obj, 1);
                            end
                            if (obj_is_visible_flag(announcer_obj) == 0) then begin
                                set_obj_visibility(announcer_obj, 0);
                            end
                            if (CUR_MAP_NEWR2) then begin
                                if (announcer_obj != 0) then begin
                                    last_timed_obj := announcer_obj;
                                    last_timed_param := last_timed_param;
                                    rm_fixed_timer_event(announcer_obj, 48);
                                    add_timer_event(announcer_obj, game_ticks(0), 48);
                                end
                            end
                            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                            gfade_in(10);
                            debug_msg("call fight over: end");
                            debug_msg("lose boxing match: " + self_name);
                        end
                        else begin
                            if ((global_var(GVAR_NEW_RENO_ROUND_TIME) != 0) and (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0)) then begin
                                if (anim_busy(self_obj) == 0) then begin
                                    if (critter_state(self_obj) bwand 1) then begin
                                    end
                                    else begin
                                        if (tile_distance_objs(self_obj, dude_obj) > 2) then begin
                                            if (random(1, 3) != 2) then begin
                                                if ((obj_item_subtype(critter_inven_obj(self_obj, 1)) == 3) or (obj_item_subtype(critter_inven_obj(self_obj, 2)) == 3)) then begin
                                                    debug_msg("unweilding boxer weapon");
                                                    inven_unwield(self_obj);
                                                end
                                                else begin
                                                    if (obj_art_fid(self_obj) == 16777312) then begin
                                                        if (obj_is_carrying_obj_pid(self_obj, 489) > 0) then begin
                                                            debug_msg("weilding boxer weapon");
                                                            wield_obj_critter(self_obj, obj_carrying_pid_obj(self_obj, 489));
                                                        end
                                                    end
                                                end
                                            end
                                            attack(dude_obj);
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end

procedure pickup_p_proc
begin
    script_overrides;
end

procedure timed_event_p_proc
begin
    if (fixed_param == 41) then begin
        debug_msg("prizefighter got timed event: knockout_param");
        if (critter_state(dude_obj) bwand 2) then begin
            if (-1 != 0) then begin
                if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -1);
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 200);
                    add_timer_event(announcer_obj, game_ticks(5), 200);
                end
            end
            else begin
                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
            end
            debug_msg("set_fight_status(" + -1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
            debug_msg("call fight over: start");
            gfade_out(10);
            set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            move_to(dude_obj, 25076, elevation(self_obj));
            anim(dude_obj, 1000, 3);
            if (prize_fighter_obj != 0) then begin
                if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                    if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                        set_obj_visibility(prize_fighter_obj, 1);
                    end
                    prize_fighter_obj := 0;
                end
                else begin
                    animate_stand_obj(prize_fighter_obj);
                    critter_injure(prize_fighter_obj, 2 bwor 8388608);
                    move_to(prize_fighter_obj, 25674, elevation(self_obj));
                    anim(prize_fighter_obj, 1000, 3);
                end
            end
            if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                set_obj_visibility(ring_girl_obj, 1);
            end
            if (obj_is_visible_flag(announcer_obj) == 0) then begin
                set_obj_visibility(announcer_obj, 0);
            end
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            gfade_in(10);
            debug_msg("call fight over: end");
            debug_msg("lose boxing match: " + self_name);
        end
        else begin
            if (1 != 0) then begin
                if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                    set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 1);
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 200);
                    add_timer_event(announcer_obj, game_ticks(5), 200);
                end
            end
            else begin
                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
            end
            debug_msg("set_fight_status(" + 1 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
            debug_msg("call fight over: start");
            gfade_out(10);
            set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            move_to(dude_obj, 25076, elevation(self_obj));
            anim(dude_obj, 1000, 3);
            if (prize_fighter_obj != 0) then begin
                if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                    if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                        set_obj_visibility(prize_fighter_obj, 1);
                    end
                    prize_fighter_obj := 0;
                end
                else begin
                    animate_stand_obj(prize_fighter_obj);
                    critter_injure(prize_fighter_obj, 2 bwor 8388608);
                    move_to(prize_fighter_obj, 25674, elevation(self_obj));
                    anim(prize_fighter_obj, 1000, 3);
                end
            end
            if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                set_obj_visibility(ring_girl_obj, 1);
            end
            if (obj_is_visible_flag(announcer_obj) == 0) then begin
                set_obj_visibility(announcer_obj, 0);
            end
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            gfade_in(10);
            debug_msg("call fight over: end");
            debug_msg("win boxing match: " + self_name);
        end
    end
    else begin
        if (fixed_param == 42) then begin
            debug_msg("prizefighter got timed event: round_over_param");
            play_sfx("boxbel2");
            terminate_combat;
            gfade_out(10);
            if (obj_is_visible_flag(announcer_obj) == 1) then begin
                set_obj_visibility(announcer_obj, 1);
            end
            if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                set_obj_visibility(ring_girl_obj, 1);
            end
            debug_msg("end boxing round start");
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            debug_msg("combat terminated");
            set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
            set_global_var(GVAR_NEW_RENO_ROUND_NUMBER, global_var(GVAR_NEW_RENO_ROUND_NUMBER) + 1);
            animate_stand_obj(dude_obj);
            if ((prize_fighter_obj != 0) and (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0)) then begin
                animate_stand_obj(prize_fighter_obj);
            end
            if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                debug_msg("check_fight_status(fight_status_fighting)");
                debug_msg("move_boxers_to_corners: start");
                move_to(dude_obj, 24479, elevation(self_obj));
                critter_injure(dude_obj, 2 bwor 8388608);
                if ((prize_fighter_obj != 0) and (((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) == 0)) then begin
                    move_to(prize_fighter_obj, 26471, elevation(self_obj));
                    animate_stand_obj(prize_fighter_obj);
                    critter_injure(prize_fighter_obj, 2 bwor 8388608);
                    anim(dude_obj, 1000, rotation_to_tile(dude_tile, tile_num(prize_fighter_obj)));
                    anim(prize_fighter_obj, 1000, rotation_to_tile(tile_num(prize_fighter_obj), dude_tile));
                end
                animate_stand_obj(dude_obj);
                debug_msg("move_boxers_to_corners: end");
                set_global_var(GVAR_NEW_RENO_DUDE_SCORE, global_var(GVAR_NEW_RENO_DUDE_SCORE) + 9);
                set_global_var(GVAR_NEW_RENO_BOXER_SCORE, global_var(GVAR_NEW_RENO_BOXER_SCORE) + 9);
                if ((local_var(1) > local_var(2)) or ((local_var(1) == local_var(2)) and random(0, 1))) then begin
                    set_global_var(GVAR_NEW_RENO_DUDE_SCORE, global_var(GVAR_NEW_RENO_DUDE_SCORE) + 1);
                end
                else begin
                    set_global_var(GVAR_NEW_RENO_BOXER_SCORE, global_var(GVAR_NEW_RENO_BOXER_SCORE) + 1);
                end
                if (global_var(GVAR_NEW_RENO_ROUND_NUMBER) <= 12) then begin
                    critter_heal(dude_obj, dude_endurance);
                    critter_heal(prize_fighter_obj, get_critter_stat(prize_fighter_obj, STAT_en));
                    set_local_var(1, 0);
                    set_local_var(2, 0);
                    if (obj_is_visible_flag(ring_girl_obj) == 0) then begin
                        set_obj_visibility(ring_girl_obj, 0);
                    end
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 110);
                    add_timer_event(announcer_obj, game_ticks(5), 110);
                end
                else begin
                    if (global_var(GVAR_NEW_RENO_BOXER_SCORE) > global_var(GVAR_NEW_RENO_DUDE_SCORE)) then begin
                        if (-4 != 0) then begin
                            if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, -4);
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 200);
                                add_timer_event(announcer_obj, game_ticks(5), 200);
                            end
                        end
                        else begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                        end
                        debug_msg("set_fight_status(" + -4 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                        debug_msg("call fight over: start");
                        gfade_out(10);
                        set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        move_to(dude_obj, 25076, elevation(self_obj));
                        anim(dude_obj, 1000, 3);
                        if (prize_fighter_obj != 0) then begin
                            if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                                if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                    set_obj_visibility(prize_fighter_obj, 1);
                                end
                                prize_fighter_obj := 0;
                            end
                            else begin
                                animate_stand_obj(prize_fighter_obj);
                                critter_injure(prize_fighter_obj, 2 bwor 8388608);
                                move_to(prize_fighter_obj, 25674, elevation(self_obj));
                                anim(prize_fighter_obj, 1000, 3);
                            end
                        end
                        if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                            set_obj_visibility(ring_girl_obj, 1);
                        end
                        if (obj_is_visible_flag(announcer_obj) == 0) then begin
                            set_obj_visibility(announcer_obj, 0);
                        end
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        gfade_in(10);
                        debug_msg("call fight over: end");
                        debug_msg("lose boxing match: " + self_name);
                    end
                    else begin
                        if (4 != 0) then begin
                            if (global_var(GVAR_NEW_RENO_FIGHT_STATUS) == 0) then begin
                                set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 4);
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 200);
                                add_timer_event(announcer_obj, game_ticks(5), 200);
                            end
                        end
                        else begin
                            set_global_var(GVAR_NEW_RENO_FIGHT_STATUS, 0);
                        end
                        debug_msg("set_fight_status(" + 4 + ") == " + global_var(GVAR_NEW_RENO_FIGHT_STATUS));
                        debug_msg("call fight over: start");
                        gfade_out(10);
                        set_global_var(GVAR_NEW_RENO_ROUND_TIME, 0);
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        move_to(dude_obj, 25076, elevation(self_obj));
                        anim(dude_obj, 1000, 3);
                        if (prize_fighter_obj != 0) then begin
                            if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 8192) != 0) then begin
                                if (obj_is_visible_flag(prize_fighter_obj) == 1) then begin
                                    set_obj_visibility(prize_fighter_obj, 1);
                                end
                                prize_fighter_obj := 0;
                            end
                            else begin
                                animate_stand_obj(prize_fighter_obj);
                                critter_injure(prize_fighter_obj, 2 bwor 8388608);
                                move_to(prize_fighter_obj, 25674, elevation(self_obj));
                                anim(prize_fighter_obj, 1000, 3);
                            end
                        end
                        if (obj_is_visible_flag(ring_girl_obj) == 1) then begin
                            set_obj_visibility(ring_girl_obj, 1);
                        end
                        if (obj_is_visible_flag(announcer_obj) == 0) then begin
                            set_obj_visibility(announcer_obj, 0);
                        end
                        if (CUR_MAP_NEWR2) then begin
                            if (announcer_obj != 0) then begin
                                last_timed_obj := announcer_obj;
                                last_timed_param := last_timed_param;
                                rm_fixed_timer_event(announcer_obj, 48);
                                add_timer_event(announcer_obj, game_ticks(0), 48);
                            end
                        end
                        set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
                        gfade_in(10);
                        debug_msg("call fight over: end");
                        debug_msg("win boxing match: " + self_name);
                    end
                end
            end
            if (CUR_MAP_NEWR2) then begin
                if (announcer_obj != 0) then begin
                    last_timed_obj := announcer_obj;
                    last_timed_param := last_timed_param;
                    rm_fixed_timer_event(announcer_obj, 48);
                    add_timer_event(announcer_obj, game_ticks(0), 48);
                end
            end
            set_global_var(GVAR_EMILY_SUBST_TIME, global_var(GVAR_EMILY_SUBST_TIME) bwor 2);
            gfade_in(10);
            debug_msg("end boxing round end");
        end
    end
end

procedure Node998
begin
end

procedure Node999
begin
end
