variable tmp_gen_rep;
variable global_temp;
variable floater_patch_msg;

procedure start;
procedure critter_p_proc;
procedure pickup_p_proc;
procedure talk_p_proc;
procedure destroy_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure damage_p_proc;
procedure map_enter_p_proc;
procedure timed_event_p_proc;
procedure map_update_p_proc;
procedure push_p_proc;
procedure Node998;
procedure Node999;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;
procedure Node013;
procedure Node014;
procedure Node015;
procedure Node016;
procedure Node017;
procedure Node018;
procedure Node019;
procedure Node020;
procedure Node021;

variable message_type;

import variable new_reno_cats_paw_obj;


procedure start
begin
end

procedure critter_p_proc
begin
    if (obj_can_see_obj(self_obj, dude_obj)) then begin
        if ((local_var(0) bwand 2) != 0) then begin
            if (critter_is_fleeing(self_obj)) then begin
                if (anim_busy(self_obj) == 0) then begin
                    if ((tile_distance_objs(self_obj, dude_obj) < 8) or obj_can_see_obj(self_obj, dude_obj)) then begin
                        if (anim_busy(self_obj) == 0) then begin
                            global_temp := rotation_to_tile(dude_tile, tile_num(self_obj));
                            animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                            global_temp := (global_temp + 1) % 6;
                            while ((anim_busy(self_obj) == 0) and (global_temp != rotation_to_tile(dude_tile, tile_num(self_obj)))) do begin
                                debug_msg("flee loop: rot == " + global_temp);
                                animate_move_obj_to_tile(self_obj, tile_num_in_direction(tile_num(self_obj), global_temp, random(3, 10)), 1);
                                global_temp := (global_temp + 1) % 6;
                            end
                        end
                    end
                end
            end
            else begin
                attack(dude_obj);
            end
        end
        else begin
            if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87) then begin
                if (obj_is_visible_flag(self_obj) and (elevation(self_obj) == elevation(dude_obj))) then begin
                    if (new_reno_cats_paw_obj == 0) then begin
                        new_reno_cats_paw_obj := self_obj;
                    end
                    else begin
                        if ((obj_can_see_obj(new_reno_cats_paw_obj, dude_obj) == 0) or (critter_state(new_reno_cats_paw_obj) bwand 1)) then begin
                            new_reno_cats_paw_obj := self_obj;
                        end
                    end
                end
            end
        end
    end
end

procedure pickup_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(0, local_var(0) bwor 2);
    end
end

procedure talk_p_proc
begin
    message_type := 2;
    debug_msg("self_team == " + has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM));
    if (global_var(GVAR_FALLOUT_2) == 8) then begin
        call Node013();
    end
    else begin
        if ((obj_pid(critter_inven_obj(dude_obj, 0)) == 3) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 348) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 349) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 232)) then begin
            call Node014();
        end
        else begin
            if (global_var(GVAR_NEW_RENO_PORN_STAR) > 0) then begin
                if (dude_gender == 1) then begin
                    call Node004();
                end
                else begin
                    call Node003();
                end
            end
            else begin
                if (global_var(GVAR_NEW_RENO_HAS_REP_PRIZEFIGHTER) > 0) then begin
                    if (dude_gender == 1) then begin
                        call Node015();
                    end
                    else begin
                        call Node005();
                    end
                end
                else begin
                    if (global_var(GVAR_NEW_RENO_MADE_MAN) > 0) then begin
                        call Node016();
                    end
                    else begin
                        if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                            call Node017();
                        end
                        else begin
                            if (obj_can_see_obj(self_obj, party_member_obj(16777295)) or obj_can_see_obj(self_obj, party_member_obj(16777377))) then begin
                                call Node009();
                            end
                            else begin
                                if (obj_can_see_obj(self_obj, party_member_obj(16777376))) then begin
                                    call Node010();
                                end
                                else begin
                                    if (obj_can_see_obj(self_obj, party_member_obj(16777313))) then begin
                                        call Node018();
                                    end
                                    else begin
                                        call Node019();
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    metarule3(100, self_obj, 1, 0);
    add_timer_event(self_obj, game_ticks(5 + random(1, 7)), 1);
end

procedure destroy_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_global_var(GVAR_BAD_MONSTER, global_var(GVAR_BAD_MONSTER) + 1);
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(GVAR_GOOD_MONSTER) > (2 * global_var(GVAR_BAD_MONSTER))) or (global_var(GVAR_BERSERKER_REPUTATION) == 1))) then begin
            set_global_var(GVAR_BERSERKER_REPUTATION, 1);
            set_global_var(GVAR_CHAMPION_REPUTATION, 0);
        end
        if (((global_var(GVAR_BAD_MONSTER) + global_var(GVAR_GOOD_MONSTER)) >= 25) and ((global_var(4) > (3 * global_var(GVAR_GOOD_MONSTER))) or (global_var(GVAR_CHAMPION_REPUTATION) == 1)) and (global_var(GVAR_CHILDKILLER_REPUTATION) == 0)) then begin
            set_global_var(GVAR_CHAMPION_REPUTATION, 1);
            set_global_var(GVAR_BERSERKER_REPUTATION, 0);
        end
        set_global_var(GVAR_PLAYER_REPUTATION, global_var(GVAR_PLAYER_REPUTATION) + 1);
        debug_msg("Player gains " + 1 + " Karma Points.");
        set_global_var(GVAR_KARMA_HOLY_WARRIOR, 0);
        set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 0);
        set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 0);
        set_global_var(GVAR_KARMA_DEFENDER, 0);
        set_global_var(GVAR_KARMA_WANDERER, 0);
        set_global_var(GVAR_KARMA_BETRAYER, 0);
        set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 0);
        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 0);
        set_global_var(GVAR_KARMA_DEMON_SPAWN, 0);
        tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION);
        if (has_trait(TRAIT_PERK, dude_obj, PERK_karma_beacon_perk)) then begin
            tmp_gen_rep := global_var(GVAR_PLAYER_REPUTATION) * 2;
        end
        if (tmp_gen_rep >= 1000) then begin
            set_global_var(GVAR_KARMA_HOLY_WARRIOR, 1);
        end
        else begin
            if (tmp_gen_rep >= 750) then begin
                set_global_var(GVAR_KARMA_GUARDIAN_OF_THE_WASTES, 1);
            end
            else begin
                if (tmp_gen_rep >= 500) then begin
                    set_global_var(GVAR_KARMA_SHIELD_OF_HOPE, 1);
                end
                else begin
                    if (tmp_gen_rep >= 250) then begin
                        set_global_var(GVAR_KARMA_DEFENDER, 1);
                    end
                    else begin
                        if (tmp_gen_rep > -250) then begin
                            set_global_var(GVAR_KARMA_WANDERER, 1);
                        end
                        else begin
                            if (tmp_gen_rep > -500) then begin
                                set_global_var(GVAR_KARMA_BETRAYER, 1);
                            end
                            else begin
                                if (tmp_gen_rep > -750) then begin
                                    set_global_var(GVAR_KARMA_SWORD_OF_DESPAIR, 1);
                                end
                                else begin
                                    if (tmp_gen_rep > -1000) then begin
                                        set_global_var(GVAR_KARMA_SCOURGE_OF_THE_WASTE, 1);
                                    end
                                    else begin
                                        set_global_var(GVAR_KARMA_DEMON_SPAWN, 1);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        set_global_var(GVAR_TOWN_REP_NEW_RENO, global_var(GVAR_TOWN_REP_NEW_RENO) + 2);
        debug_msg("Added " + 2 + " to Town Rep");
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    display_mstr(100 + (3000 * (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87)));
end

procedure description_p_proc
begin
    script_overrides;
    if ((local_var(0) bwand 4) != 0) then begin
        if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87) then begin
            display_mstr(random(3151, 3158));
        end
        else begin
            display_mstr(random(151, 158));
        end
    end
    else begin
        display_mstr(150 + (3000 * (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87)));
    end
    set_local_var(0, local_var(0) bwor 4);
end

procedure use_skill_on_p_proc
begin
end

procedure damage_p_proc
begin
    if (source_obj == dude_obj) then begin
        set_local_var(0, local_var(0) bwor 8);
        set_local_var(0, local_var(0) bwor 2);
    end
end

procedure map_enter_p_proc
begin
    if (is_loading_game == 0) then begin
        if (map_first_run) then begin
            set_local_var(1, tile_num(self_obj));
            if (tile_in_tile_rect(20493, 20481, 26493, 26481, tile_num(self_obj)) and (CUR_MAP_NEWR1) and ((elevation(self_obj) == 0) or (-1 == 0))) then begin
                critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 87);
            end
            else begin
                if (tile_in_tile_rect(8296, 8258, 15896, 15858, tile_num(self_obj)) and (CUR_MAP_NEWR1) and ((elevation(self_obj) == 0) or (-1 == 0)) or (tile_in_tile_rect(12744, 12712, 20344, 20312, tile_num(self_obj)) and (CUR_MAP_NEWR2) and ((elevation(self_obj) == 0) or (-1 == 0)))) then begin
                    critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 62);
                end
                else begin
                    if (tile_in_tile_rect(11134, 11106, 19534, 19506, tile_num(self_obj)) and (CUR_MAP_NEWR1) and ((elevation(self_obj) == 0) or (-1 == 0)) or (tile_in_tile_rect(7902, 7862, 20302, 20262, tile_num(self_obj)) and (CUR_MAP_NEWR2) and ((elevation(self_obj) == 0) or (-1 == 0)))) then begin
                        critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 89);
                    end
                    else begin
                        if (tile_in_tile_rect(21544, 21512, 30344, 30312, tile_num(self_obj)) and (CUR_MAP_NEWR2) and ((elevation(self_obj) == 0) or (-1 == 0))) then begin
                            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 90);
                        end
                        else begin
                            if (tile_in_tile_rect(21502, 21466, 30301, 30266, tile_num(self_obj)) and (CUR_MAP_NEWR2) and ((elevation(self_obj) == 0) or (-1 == 0))) then begin
                                critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_TEAM_NUM, 91);
                            end
                        end
                    end
                end
            end
            critter_add_trait(self_obj, TRAIT_OBJECT, OBJECT_AI_PACKET, AI_PROSTITUTE);
        end
        metarule3(100, self_obj, 1, 0);
        add_timer_event(self_obj, game_ticks(5 + random(1, 7)), 1);
    end
end

procedure timed_event_p_proc
begin
    variable LVar0 := 0;
    if ((combat_is_initialized == 0) and obj_is_visible_flag(self_obj)) then begin
        if (((global_var(GVAR_NEW_RENO_FLAG_2) bwand 1073741824) != 0) == 0) then begin
            if (obj_can_see_obj(self_obj, dude_obj) and (random(1, 2) == 1)) then begin
                message_type := 1;
                if (global_var(GVAR_FALLOUT_2) == 8) then begin
                    call Node001();
                end
                else begin
                    if ((obj_pid(critter_inven_obj(dude_obj, 0)) == 3) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 348) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 349) or (obj_pid(critter_inven_obj(dude_obj, 0)) == 232)) then begin
                        call Node002();
                    end
                    else begin
                        if (global_var(GVAR_NEW_RENO_PORN_STAR) > 0) then begin
                            if (dude_gender == 1) then begin
                                call Node004();
                            end
                            else begin
                                call Node003();
                            end
                        end
                        else begin
                            if (global_var(GVAR_NEW_RENO_HAS_REP_PRIZEFIGHTER) > 0) then begin
                                if (dude_gender == 1) then begin
                                    call Node006();
                                end
                                else begin
                                    call Node005();
                                end
                            end
                            else begin
                                if (global_var(GVAR_NEW_RENO_MADE_MAN) > 0) then begin
                                    call Node007();
                                end
                                else begin
                                    if (global_var(GVAR_REPUTATION_SLAVER) == 1) then begin
                                        call Node008();
                                    end
                                    else begin
                                        if (obj_can_see_obj(self_obj, party_member_obj(16777295)) or obj_can_see_obj(self_obj, party_member_obj(16777377))) then begin
                                            call Node009();
                                        end
                                        else begin
                                            if (obj_can_see_obj(self_obj, party_member_obj(16777376))) then begin
                                                call Node010();
                                            end
                                            else begin
                                                if (obj_can_see_obj(self_obj, party_member_obj(16777313))) then begin
                                                    call Node011();
                                                end
                                                else begin
                                                    call Node012();
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
            else begin
                if ((has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87) and obj_on_screen(self_obj)) then begin
                    call Node020();
                end
            end
        end
        if ((has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 87) == 0) then begin
            if ((anim_busy(self_obj) == 0) and (random(1, 5) == 1)) then begin
                if (tile_num(self_obj) != local_var(1)) then begin
                    animate_move_obj_to_tile(self_obj, local_var(1), 0);
                end
                else begin
                    LVar0 := tile_num_in_direction(tile_num(self_obj), random(0, 5), random(5, 15));
                    if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 62) then begin
                        if (CUR_MAP_NEWR1) then begin
                            if (tile_in_tile_rect(8296, 8258, 15896, 15858, tile_num(self_obj)) and (tile_in_tile_rect(8292, 8246, 15092, 15046, tile_num(self_obj)) == 0)) then begin
                                animate_move_obj_to_tile(self_obj, LVar0, 0);
                            end
                        end
                        else begin
                            if (CUR_MAP_NEWR2) then begin
                                if (tile_in_tile_rect(12744, 12712, 20344, 20312, tile_num(self_obj)) and (tile_in_tile_rect(13540, 13516, 19540, 19516, tile_num(self_obj)) == 0)) then begin
                                    animate_move_obj_to_tile(self_obj, LVar0, 0);
                                end
                            end
                        end
                    end
                    else begin
                        if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 89) then begin
                            if (CUR_MAP_NEWR1) then begin
                                if (tile_in_tile_rect(11134, 11106, 19534, 19506, tile_num(self_obj)) and (tile_in_tile_rect(11930, 11910, 18730, 18710, tile_num(self_obj)) == 0)) then begin
                                    animate_move_obj_to_tile(self_obj, LVar0, 0);
                                end
                            end
                            else begin
                                if (CUR_MAP_NEWR2) then begin
                                    if (tile_in_tile_rect(7902, 7862, 20302, 20262, tile_num(self_obj)) and (tile_in_tile_rect(7898, 7862, 19498, 19462, tile_num(self_obj)) == 0)) then begin
                                        animate_move_obj_to_tile(self_obj, LVar0, 0);
                                    end
                                end
                            end
                        end
                        else begin
                            if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 90) then begin
                                if (tile_in_tile_rect(21544, 21512, 30344, 30312, tile_num(self_obj)) and (tile_in_tile_rect(22340, 22316, 29540, 29516, tile_num(self_obj)) == 0)) then begin
                                    animate_move_obj_to_tile(self_obj, LVar0, 0);
                                end
                            end
                            else begin
                                if (has_trait(TRAIT_OBJECT, self_obj, OBJECT_TEAM_NUM) == 91) then begin
                                    if (tile_in_tile_rect(21502, 21466, 30301, 30266, tile_num(self_obj)) and (tile_in_tile_rect(22298, 22266, 29498, 29466, tile_num(self_obj)) == 0)) then begin
                                        animate_move_obj_to_tile(self_obj, LVar0, 0);
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
    metarule3(100, self_obj, 1, 0);
    add_timer_event(self_obj, game_ticks(5 + random(1, 7)), 1);
    return 0;
    LVar0 := 0;
end

procedure map_update_p_proc
begin
    if ((global_var(GVAR_NEW_RENO_FLAG_3) bwand 536870912) != 0) then begin
        if (obj_is_visible_flag(self_obj)) then begin
            if (tile_in_tile_rect(22298, 22266, 29498, 29466, tile_num(self_obj)) == 0) then begin
                if (obj_is_visible_flag(self_obj) == 1) then begin
                    set_obj_visibility(self_obj, 1);
                end
                set_local_var(0, local_var(0) bwor 512);
            end
        end
    end
    else begin
        if ((local_var(0) bwand 512) != 0) then begin
            if (obj_is_visible_flag(self_obj) == 0) then begin
                set_obj_visibility(self_obj, 0);
            end
            set_local_var(0, local_var(0) bwand (-1 - 512));
        end
    end
end

procedure push_p_proc
begin
    if (tile_num(self_obj) == local_var(1)) then begin
        script_overrides;
    end
end

procedure Node998
begin
    set_local_var(0, local_var(0) bwor 2);
end

procedure Node999
begin
end

procedure Node001
begin
    floater_patch_msg := random(178 - (3 * (dude_gender == 0)), 180 + (3 * (dude_gender == 1)));
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + dude_name + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node002
begin
    float_msg(self_obj, mstr(190), FLOAT_MSG_SEQUENTIAL);
end

procedure Node003
begin
    floater_patch_msg := random(197 - (2 * (message_type == 1)), 200 + (11 * (message_type == 2)));
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 500 + global_var(GVAR_NEW_RENO_PORN_STAR)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node004
begin
    float_msg(self_obj, mstr(random(225 - (13 * (message_type == 1)), 238 + (13 * (message_type == 2)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node005
begin
    floater_patch_msg := random(266 - (14 * (message_type == 1)), 272 + (5 * (message_type == 2)));
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 400 + global_var(GVAR_NEW_RENO_PRIZEFIGHTER)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node006
begin
    floater_patch_msg := random(278, 284);
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 400 + global_var(GVAR_NEW_RENO_PRIZEFIGHTER)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node007
begin
    floater_patch_msg := random(292 - (7 * (dude_gender == 0)), 294 + (5 * (dude_gender == 1)));
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 300 + (global_var(GVAR_NEW_RENO_MADE_MAN) % 100)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node008
begin
    float_msg(self_obj, mstr(random(336 - (36 * (dude_gender == 0)), 444 + (15 * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node009
begin
    if (obj_can_see_obj(self_obj, party_member_obj(16777295))) then begin
        float_msg(self_obj, mstr(random(460, 464)), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        if (obj_can_see_obj(self_obj, party_member_obj(16777377))) then begin
            float_msg(self_obj, mstr(random(465, 470)), FLOAT_MSG_SEQUENTIAL);
        end
    end
end

procedure Node010
begin
    float_msg(self_obj, mstr(random(471, 482)), FLOAT_MSG_SEQUENTIAL);
end

procedure Node011
begin
    float_msg(self_obj, mstr(random(524 - (41 * (dude_gender == 0)), 636 + (18 * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node012
begin
    float_msg(self_obj, mstr(random(696 - ((696 - 655) * (dude_gender == 0)), 799 + ((817 - 799) * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node013
begin
    float_msg(self_obj, mstr(random(818, 834)), FLOAT_MSG_SEQUENTIAL);
end

procedure Node014
begin
    float_msg(self_obj, mstr(random(842 - (7 * (dude_gender == 0)), 851 + (2 * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node015
begin
    floater_patch_msg := random(854, 864);
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 400 + global_var(GVAR_NEW_RENO_PRIZEFIGHTER)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node016
begin
    floater_patch_msg := random(867 - (2 * (dude_gender == 0)), 872 + (2 * (dude_gender == 1)));
    if ((floater_patch_msg == 175) or (floater_patch_msg == 178) or (floater_patch_msg == 181) or (floater_patch_msg == 195) or (floater_patch_msg == 197) or (floater_patch_msg == 210) or (floater_patch_msg == 263) or (floater_patch_msg == 264) or (floater_patch_msg == 268) or (floater_patch_msg == 272) or ((278 <= floater_patch_msg) and (floater_patch_msg <= 280)) or ((292 <= floater_patch_msg) and (floater_patch_msg <= 295)) or (floater_patch_msg == 285) or (floater_patch_msg == 855) or (floater_patch_msg == 858) or (floater_patch_msg == 861) or (floater_patch_msg == 865) or (floater_patch_msg == 867) or (floater_patch_msg == 868) or (floater_patch_msg == 870) or (floater_patch_msg == 873)) then begin
        float_msg(self_obj, mstr(floater_patch_msg) + message_str(SCRIPT_NEWR1, 300 + (global_var(GVAR_NEW_RENO_MADE_MAN) % 100)) + mstr(floater_patch_msg + 2000), FLOAT_MSG_SEQUENTIAL);
    end
    else begin
        float_msg(self_obj, mstr(floater_patch_msg), FLOAT_MSG_SEQUENTIAL);
    end
end

procedure Node017
begin
    float_msg(self_obj, mstr(random(918 - ((918 - 875) * (dude_gender == 0)), 1030 + ((1049 - 1030) * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node018
begin
    float_msg(self_obj, mstr(random(1091 - ((1091 - 1050) * (dude_gender == 0)), 1204 + ((1222 - 1204) * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node019
begin
    float_msg(self_obj, mstr(random(1264 - ((1264 - 1223) * (dude_gender == 0)), 1378 + ((1395 - 1378) * (dude_gender == 1)))), FLOAT_MSG_SEQUENTIAL);
end

procedure Node020
begin
    float_msg(self_obj, mstr(random(3200, 3215)), FLOAT_MSG_SEQUENTIAL);
end

procedure Node021
begin
    float_msg(self_obj, mstr(random(1223, 1260)), FLOAT_MSG_SEQUENTIAL);
end
