procedure start;
procedure map_exit_p_proc;
procedure map_enter_p_proc;
procedure map_update_p_proc;
procedure Make_Plants;

export variable GHOST_obj;
export variable WARRIOR_obj;
export variable SULIK_SIS_obj;


procedure start
begin
end

procedure map_exit_p_proc
begin
    if (global_var(GVAR_SULIK_DEAD) == 4) then begin
        set_global_var(GVAR_SULIK_DEAD, 5);
    end
    if (global_var(GVAR_FIND_SULIK) >= 3) then begin
        if (tile_contains_obj_pid(21648, 0, 16777750)) then begin
            destroy_object(tile_contains_pid_obj(21648, 0, 16777750));
        end
    end
end

procedure map_enter_p_proc
begin
    variable LVar0 := 0;
    if (elevation(dude_obj) == 0) then begin
        if ((game_time < 0) and (map_var(3) == 0)) then begin
            set_map_var(2, game_time - 1);
            set_map_var(3, 1);
        end
        if (map_var(2) < game_time) then begin
            set_map_var(2, (random(6, 8) * (24 * (60 * (60 * 10)))) + game_time);
            call Make_Plants();
        end
    end
    if ((global_var(GVAR_ABBEY_FORMAT_DATABASES) > 1) and ((global_var(GVAR_ABBEY_FORMAT_DATABASES) < 6) or (global_var(GVAR_LOAD_MAP_INDEX) == 901))) then begin
        move_to(dude_obj, 22887, 1);
    end
    if (global_var(GVAR_WIPED_OUT_RANGER_SAFE_HOUSES) == 4) then begin
        LVar0 := create_object_sid(16777418, 18517, 1, SCRIPT_RTRIBEC9);
        move_to(dude_obj, 20518, 1);
        anim(dude_obj, 1000, 5);
        display_mstr(102);
        give_exp_points(600);
        display_msg(g_mstr(100) + 600 + g_mstr(101));
        set_global_var(GVAR_TOWN_REP_PRIMITIVE_TRIBE, global_var(GVAR_TOWN_REP_PRIMITIVE_TRIBE) + 15);
    end
    if (map_first_run) then begin
        display_mstr(100);
    end
    if (global_var(GVAR_LOAD_MAP_INDEX) == 900) then begin
        set_global_var(GVAR_SULIK_DEAD, 3);
        display_mstr(200);
        give_exp_points(1000);
        display_msg(g_mstr(100) + 1000 + g_mstr(101));
        set_global_var(GVAR_TOWN_REP_PRIMITIVE_TRIBE, global_var(GVAR_TOWN_REP_PRIMITIVE_TRIBE) + 15);
        LVar0 := create_object_sid(16777754, 22101, 1, SCRIPT_RTRIBEC7);
        move_to(dude_obj, 22104, 1);
        anim(LVar0, 1000, 4);
        anim(dude_obj, 1000, 1);
    end
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 45);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(90 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 45);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(90 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 45);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(90 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 45);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(90 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
    set_global_var(GVAR_LOAD_MAP_INDEX, 0);
    return 0;
    LVar0 := 0;
end

procedure map_update_p_proc
begin
    if ((get_month >= 3) and (get_month < 5)) then begin
        if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
            set_light_level(game_time_hour - 600 + 45);
        end
        else begin
            if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                set_light_level(100);
            end
            else begin
                if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                    set_light_level(90 - (game_time_hour - 1800));
                end
                else begin
                    set_light_level(40);
                end
            end
        end
    end
    else begin
        if ((get_month >= 5) and (get_month < 9)) then begin
            if ((game_time_hour >= 500) and (game_time_hour < (500 + 100))) then begin
                set_light_level(game_time_hour - 500 + 45);
            end
            else begin
                if ((game_time_hour >= (500 + 100)) and (game_time_hour < 1900)) then begin
                    set_light_level(100);
                end
                else begin
                    if ((game_time_hour >= 1900) and (game_time_hour < (1900 + 100))) then begin
                        set_light_level(90 - (game_time_hour - 1900));
                    end
                    else begin
                        set_light_level(40);
                    end
                end
            end
        end
        else begin
            if ((get_month >= 9) and (get_month < 11)) then begin
                if ((game_time_hour >= 600) and (game_time_hour < (600 + 100))) then begin
                    set_light_level(game_time_hour - 600 + 45);
                end
                else begin
                    if ((game_time_hour >= (600 + 100)) and (game_time_hour < 1800)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1800) and (game_time_hour < (1800 + 100))) then begin
                            set_light_level(90 - (game_time_hour - 1800));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
            else begin
                if ((game_time_hour >= 700) and (game_time_hour < (700 + 100))) then begin
                    set_light_level(game_time_hour - 700 + 45);
                end
                else begin
                    if ((game_time_hour >= (700 + 100)) and (game_time_hour < 1700)) then begin
                        set_light_level(100);
                    end
                    else begin
                        if ((game_time_hour >= 1700) and (game_time_hour < (1700 + 100))) then begin
                            set_light_level(90 - (game_time_hour - 1700));
                        end
                        else begin
                            set_light_level(40);
                        end
                    end
                end
            end
        end
    end
end

procedure Make_Plants
begin
    variable LVar0 := 0;
    if (not(tile_contains_obj_pid(16081, 0, 272))) then begin
        LVar0 := create_object(272, 16081, 0);
    end
    if (not(tile_contains_obj_pid(21251, 0, 272))) then begin
        LVar0 := create_object(272, 21251, 0);
    end
    if (not(tile_contains_obj_pid(16850, 0, 271))) then begin
        LVar0 := create_object(271, 16850, 0);
    end
    if (not(tile_contains_obj_pid(21134, 0, 271))) then begin
        LVar0 := create_object(271, 21134, 0);
    end
    return 0;
    LVar0 := 0;
end
