procedure start;
procedure spatial_p_proc;
procedure Node001;
procedure Node002;
procedure Node003;
procedure Node004;
procedure Node005;
procedure Node006;
procedure Node007;
procedure Node008;
procedure Node009;
procedure Node010;
procedure Node011;
procedure Node012;

import variable GECKO_obj;
import variable WARRIOR_obj;


procedure start
begin
end

procedure spatial_p_proc
begin
    if (source_obj == dude_obj) then begin
        if (global_var(GVAR_WIPED_OUT_RANGER_SAFE_HOUSES) == 2) then begin
            if (not(WARRIOR_obj == -1)) then begin
                if (map_var(0) == 1) then begin
                    if (local_var(4) == 0) then begin
                        set_local_var(4, 1);
                        start_gdialog(1510, self_obj, 4, -1, -1);
                        gsay_start;
                        call Node001();
                        gsay_end;
                        end_dialogue;
                    end
                end
            end
        end
    end
end

procedure Node001
begin
    gsay_reply(SCRIPT_TRIBEC1, 5200);
    giq_option(4, SCRIPT_TRIBEC1, 5201, Node002, NEUTRAL_REACTION);
end

procedure Node002
begin
    gsay_reply(SCRIPT_TRIBEC1, 5202);
    giq_option(4, SCRIPT_TRIBEC1, 5203, Node003, NEUTRAL_REACTION);
end

procedure Node003
begin
    gsay_reply(SCRIPT_TRIBEC1, 5204);
    giq_option(4, SCRIPT_TRIBEC1, 5205, Node004, NEUTRAL_REACTION);
end

procedure Node004
begin
    gsay_reply(SCRIPT_TRIBEC1, 5206);
    giq_option(4, SCRIPT_TRIBEC1, 5207, Node005, NEUTRAL_REACTION);
end

procedure Node005
begin
    gsay_reply(SCRIPT_TRIBEC1, 5208);
    giq_option(4, SCRIPT_TRIBEC1, 5209, Node006, NEUTRAL_REACTION);
end

procedure Node006
begin
    gsay_reply(SCRIPT_TRIBEC1, 5210);
    giq_option(4, SCRIPT_TRIBEC1, 5211, Node007, NEUTRAL_REACTION);
end

procedure Node007
begin
    gsay_reply(SCRIPT_TRIBEC1, 5212);
    if (dude_skill(SKILL_DOCTOR) > 100) then begin
        giq_option(4, SCRIPT_TRIBEC1, 5213, Node008, NEUTRAL_REACTION);
    end
    else begin
        if (dude_strength > 5) then begin
            giq_option(4, SCRIPT_TRIBEC1, 5214, Node011, NEUTRAL_REACTION);
        end
        else begin
            if (party_member_obj(16777377) != 0) then begin
                giq_option(4, SCRIPT_TRIBEC1, 5217, Node011, NEUTRAL_REACTION);
            end
            else begin
                if (party_member_obj(16777313) != 0) then begin
                    giq_option(4, SCRIPT_TRIBEC1, 5216, Node011, NEUTRAL_REACTION);
                end
                else begin
                    giq_option(4, SCRIPT_TRIBEC1, 5215, Node012, NEUTRAL_REACTION);
                end
            end
        end
    end
end

procedure Node008
begin
    critter_injure(self_obj, 8 bwor 8388608);
    display_msg(message_str(SCRIPT_TRIBEC1, 5600));
    give_exp_points(25);
    display_msg(g_mstr(100) + 25 + g_mstr(101));
    gsay_reply(SCRIPT_TRIBEC1, 5218);
    giq_option(4, SCRIPT_TRIBEC1, 5209, Node009, NEUTRAL_REACTION);
end

procedure Node009
begin
    critter_injure(self_obj, 8 bwor 8388608);
    critter_heal(self_obj, 10);
    gsay_reply(SCRIPT_TRIBEC1, 5219);
    giq_option(4, SCRIPT_TRIBEC1, 5220, Node010, NEUTRAL_REACTION);
end

procedure Node010
begin
    gfade_out(600);
    gfade_in(600);
    game_time_advance(60 * 10 * 15);
    gsay_reply(SCRIPT_TRIBEC1, 5221);
    set_global_var(GVAR_WIPED_OUT_RANGER_SAFE_HOUSES, 4);
    kill_critter_type(16777752, 0);
    load_map(163, 0);
end

procedure Node011
begin
    kill_critter_type(16777752, 0);
    load_map(163, 0);
    set_global_var(GVAR_WIPED_OUT_RANGER_SAFE_HOUSES, 4);
end

procedure Node012
begin
    set_global_var(GVAR_WIPED_OUT_RANGER_SAFE_HOUSES, 3);
end
