variable ProtoOfItemGiven;
variable ValueOfRollCheck := 1;
variable Scenery_Creation;
variable Scenery_Creation_Hex;
variable Scenery_Creation_Count;
variable Temp_Scenery_Creation_Hex;
variable Scenery_Creation_Ptr;
variable How_Many_Party_Members_Are_Injured;
variable How_Many_Party_Members_Armed;
variable PartyHealingItem;

procedure checkPartyMembersNearDoor;

variable global_temp;
variable dest_tile;
variable step_tile;
variable in_dialog;
variable forced_node;
variable restock_amt;
variable restock_obj;
variable restock_trash;
variable removed_qty;

procedure start;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;


procedure checkPartyMembersNearDoor
begin
    if (party_member_obj(16777278) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777278)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777376) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777376)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777377) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777377)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777305) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777305)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777313) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777313)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777323) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777323)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777352) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777352)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777378) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777378)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777368) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777368)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777379) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777379)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777380) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777380)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777295) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777295)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777381) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777381)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777407) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777407)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777411) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777411)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777412) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777412)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777413) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777413)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777481) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777481)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777558) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777558)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777600) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777600)) <= 5) then begin
            return 1;
        end
    end
    if (party_member_obj(16777703) != 0) then begin
        if (tile_distance_objs(self_obj, party_member_obj(16777703)) <= 5) then begin
            return 1;
        end
    end
    return 0;
end

procedure start
begin
end

procedure use_skill_on_p_proc
begin
    variable LVar0 := 0;
    LVar0 := action_being_used;
    if (LVar0 == 13) then begin
        if (not(map_var(4) == 2)) then begin
            script_overrides;
            if (has_skill(source_obj, SKILL_REPAIR) < 110) then begin
                display_msg(message_str(SCRIPT_V14SLDR1, 219));
            end
            else begin
                if (is_success(roll_vs_skill(source_obj, 13, -30))) then begin
                    display_msg(message_str(SCRIPT_V14SLDR1, 223));
                    set_light_level(50);
                    set_map_var(4, 2);
                    if (local_var(0) == 0) then begin
                        display_msg(message_str(SCRIPT_V14SLDR1, 225));
                        give_exp_points(1500);
                        display_msg(g_mstr(100) + 1500 + g_mstr(101));
                        set_local_var(0, 1);
                    end
                end
                else begin
                    set_local_var(1, local_var(1) + 1);
                    if (local_var(1) == 1) then begin
                        display_msg(message_str(SCRIPT_V14SLDR1, 220));
                    end
                    else begin
                        if (local_var(1) == 2) then begin
                            display_msg(message_str(SCRIPT_V14SLDR1, 221));
                        end
                        else begin
                            display_msg(message_str(SCRIPT_V14SLDR1, 222));
                        end
                    end
                end
            end
        end
    end
    return 0;
    LVar0 := 0;
end

procedure use_obj_on_p_proc
begin
    if (not(map_var(4) == 2) and (obj_pid(obj_being_used_with) == 75)) then begin
        script_overrides;
        if (has_skill(source_obj, SKILL_REPAIR) < 110) then begin
            display_msg(message_str(SCRIPT_V14SLDR1, 219));
        end
        else begin
            if (is_success(roll_vs_skill(source_obj, 13, -30 + 20))) then begin
                display_msg(message_str(SCRIPT_V14SLDR1, 223));
                set_light_level(50);
                set_map_var(4, 2);
                if (local_var(0) == 0) then begin
                    display_msg(message_str(SCRIPT_V14SLDR1, 225));
                    give_exp_points(1500);
                    display_msg(g_mstr(100) + 1500 + g_mstr(101));
                    set_local_var(0, 1);
                end
            end
            else begin
                set_local_var(1, local_var(1) + 1);
                if (local_var(1) == 1) then begin
                    display_msg(message_str(SCRIPT_V14SLDR1, 220));
                end
                else begin
                    if (local_var(1) == 2) then begin
                        display_msg(message_str(SCRIPT_V14SLDR1, 221));
                    end
                    else begin
                        display_msg(message_str(SCRIPT_V14SLDR1, 222));
                    end
                end
            end
        end
    end
end

procedure look_at_p_proc
begin
    script_overrides;
    if (map_var(4) == 2) then begin
        display_msg(message_str(SCRIPT_V14SLDR1, 217));
    end
    else begin
        display_msg(message_str(SCRIPT_V14SLDR1, 215));
    end
end

procedure description_p_proc
begin
    script_overrides;
    if (map_var(4) == 2) then begin
        display_msg(message_str(SCRIPT_V14SLDR1, 218));
    end
    else begin
        display_msg(message_str(SCRIPT_V14SLDR1, 216));
    end
end
