procedure description_p_proc;
procedure look_at_proc;
procedure start_p_proc;
procedure use_p_proc;
procedure Node000;
procedure Node001;
procedure Node002;
procedure Node999;
procedure ToggleLights;
procedure ToggleElevator;


procedure description_p_proc
begin
    script_overrides;
    display_msg(message_str(SCRIPT_KLATRAP, 11201));
end

procedure look_at_proc
begin
    script_overrides;
    display_msg(message_str(SCRIPT_KLATRAP, 11200));
end

procedure start_p_proc
begin
end

procedure use_p_proc
begin
    if (source_obj == dude_obj) then begin
        start_gdialog(964, self_obj, 4, -1, -1);
        gsay_start;
        call Node000();
        gsay_end;
        end_dialogue;
    end
end

procedure Node000
begin
    gsay_reply(SCRIPT_KLATRAP, 11202);
    giq_option(1, SCRIPT_KLATRAP, 11209, Node001, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_KLATRAP, 11210, Node002, NEUTRAL_REACTION);
    giq_option(1, SCRIPT_KLATRAP, 11208, Node999, NEUTRAL_REACTION);
end

procedure Node001
begin
    if (map_var(0) == 0) then begin
        gsay_reply(SCRIPT_KLATRAP, 11203);
        giq_option(1, SCRIPT_KLATRAP, 11211, ToggleElevator, NEUTRAL_REACTION);
    end
    else begin
        if (map_var(0) == 1) then begin
            gsay_reply(SCRIPT_KLATRAP, 11204);
            giq_option(1, SCRIPT_KLATRAP, 11212, ToggleElevator, NEUTRAL_REACTION);
        end
    end
    giq_option(1, SCRIPT_KLATRAP, 11207, Node000, NEUTRAL_REACTION);
end

procedure Node002
begin
    if (map_var(1) == 0) then begin
        gsay_reply(SCRIPT_KLATRAP, 11205);
        giq_option(1, SCRIPT_KLATRAP, 11211, ToggleLights, NEUTRAL_REACTION);
    end
    else begin
        if (map_var(1) == 1) then begin
            gsay_reply(SCRIPT_KLATRAP, 11206);
            giq_option(1, SCRIPT_KLATRAP, 11212, ToggleLights, NEUTRAL_REACTION);
        end
    end
    giq_option(1, SCRIPT_KLATRAP, 11207, Node000, NEUTRAL_REACTION);
end

procedure Node999
begin
end

procedure ToggleLights
begin
    if (map_var(1) == 0) then begin
        set_map_var(1, 1);
    end
    else begin
        if (map_var(1) == 1) then begin
            set_map_var(1, 0);
        end
    end
    call Node002();
end

procedure ToggleElevator
begin
    if (map_var(0) == 0) then begin
        set_map_var(0, 1);
    end
    else begin
        if (map_var(0) == 1) then begin
            set_map_var(0, 0);
        end
    end
    call Node001();
end
